### ISSUE TITLE
install nni offline

### ISSUE THREAD

**Issue by ldd91** [Microsoft/nni#1008]
**Short summary about the issue/question**:I want to use nni in Kubeflow Mode,however in my cluster we cannot contack public net,i wonder if there is a document to show how to install nni offline.

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:linux
- nni version:v0.6
- nni mode(local|pai|remote):Kubeflow Mode
- OS:Centos7
- python version:python3.6
- is conda or virtualenv used?: no
- is running in docker?:no

**need to update document(yes/no)**:yes

**Anything else we need to know**:

**Comment by peipei-pig** [comment]
How did you  solve this problem?  Can you give me some suggestions?

**Comment by ldd91** [comment]
I used docker to deployment nni,and i execed docker run -t --network host ...，Please  let  me konw whether this  is helpful to you

**Comment by peipei-pig** [comment]
@ldd91 I solved this problem.
1. download PythonWebHDFS-0.2.3-py3-none-any.whl on the website: https://pypi.org/
2. download nni-0.6-py3-none-manylinux1_x86_64.whl
3. use pip command Install the package above

**Comment by ldd91** [comment]
I'm very glad to here that you have  solved this problem@peipei-pig

**Comment by ldd91** [comment]
Have you tried KubeflowMode,and is it works?
