### ISSUE TITLE
create trial failed on kubeflowMode

### ISSUE THREAD

**Issue by ldd91** [microsoft/nni#1016]
**Short summary about the issue/question**:I use the example in /trial/mnist-discributed,when i exec nnictl create --config config_kubeflow.yaml,the log shows ERROR;Your config file is not correct,please check your config file content,Key 'kubeflowConfig' error...,however i didn't modify ang code in config_kubeflow.yaml

**Brief what process you are following**: 

**How to reproduce it**: Just use the example in /trials/mnist-distributed

**nni Environment**:
- nni version:v0.6
- nni mode(local|pai|remote):KubeflowMode
- OS:
- python version:python3.6
- is conda or virtualenv used?: no
- is running in docker?:nni is in docker 

**need to update document(yes/no)**:

**Anything else we need to know**: I deploymend nni in docker ,and my enviroment is kubernetes,i haved also deploymend an tf-operator

**Comment by ldd91** [comment]
In my enviroment, i  have tested that the  nfs is working

**Comment by SparkSnail** [comment]
Hi, this error happens because your kubeflowConfig field format in config file is not correct. Could you please paste your config file content here? 
Here is the example of kubeflowConfig field:
```
kubeflowConfig:
  operator: tf-operator
  apiVersion: v1alpha2
  storage: nfs
  nfs:
    server: 10.10.10.10
    path: /mnt/temp
```

**Comment by ldd91** [comment]
Just the same as you display, i just modified the ip of server and path

**Comment by SparkSnail** [comment]
Could you please check the value of server and path? The value in these field should be string type, not number.

**Comment by scarlett2018** [comment]
@ldd91 - are you already get out of the issue? if you are still facing the issue, may you share more info as @SparkSnail suggested? or IM discuss with us on Gitter? thanks.

**Comment by xieydd** [comment]
@scarlett2018 KubeflowMode only support the NFS or AzureStorage is limited.For kubeflow job, extend the common api, support the all kinds of [k8s storage](https://kubernetes.io/docs/concepts/storage/) binding with  pv/pvc .

**Comment by xieydd** [comment]
@scarlett2018 Is there a plen support mpi-operator in nni kubeflow mode.

**Comment by xieydd** [comment]
Solved, @ldd91 can close it.
