### ISSUE TITLE
tail: cannot open ‘/tmp/nni/script/gpu_metrics’ for reading: No such file or directory

### ISSUE THREAD

**Issue by xingwangsfu** [microsoft/nni#1017]
**Short summary about the issue/question**:

When I tried to run mnist examples with multiple gpus, I encountered this error 'cannot open ‘/tmp/nni/script/gpu_metrics’ for reading: No such file or directory'.

**Brief what process you are following**: 

When I changed the gpuNum from 3 to 1, everything was working as expected. But after switching back to 3 and changing the trialConcurrency from 1 to 3, the error happened. 

**How to reproduce it**: 

**nni Environment**:
- nni version:  0.6
- nni mode(local|pai|remote): local
- OS: Debian
- python version: 3.5
- is conda or virtualenv used?: Conda is used.
- is running in docker?: No

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by QuanluZhang** [comment]
Thanks for raising this issue, could provide the content of `nnimanager.log`? You could find this log file by following the guidance [here](https://nni.readthedocs.io/en/latest/HowToDebug.html#experiment-root-directory).

**Comment by QuanluZhang** [comment]
We cannot reproduce this problem on ubuntu 16.04.
To figure out the reason of this problem, could you please first run the command: `pgrep -fx 'python3 -m nni_gpu_tool.gpu_metrics_collector'` to check whether there is any such process running. After making sure there is no such process running and no nni experiment running, please start the experiment with gpuNum 3 to check whether there is the same error.

**Comment by zyznull** [comment]
same problem

**Comment by QuanluZhang** [comment]
> We cannot reproduce this problem on ubuntu 16.04.
> To figure out the reason of this problem, could you please first run the command: `pgrep -fx 'python3 -m nni_gpu_tool.gpu_metrics_collector'` to check whether there is any such process running. After making sure there is no such process running and no nni experiment running, please start the experiment with gpuNum 3 to check whether there is the same error.

@zyznull Could you try the above solution to check whether there is the same error?

**Comment by zyznull** [comment]
> > We cannot reproduce this problem on ubuntu 16.04.
> > To figure out the reason of this problem, could you please first run the command: `pgrep -fx 'python3 -m nni_gpu_tool.gpu_metrics_collector'` to check whether there is any such process running. After making sure there is no such process running and no nni experiment running, please start the experiment with gpuNum 3 to check whether there is the same error.
> 
> @zyznull Could you try the above solution to check whether there is the same error?

I have tried and there is a process running.And whatever I set gpunum,the problem still remain.
my nni Environment:
nni version: 0.6
nni mode(local|pai|remote): local
OS: CentOS Linux release 7.4.1708 (Core) 
python version: 3.5
is conda or virtualenv used?: virtualenv is used.
is running in docker?: No
need to update document(yes/no):

**Comment by QuanluZhang** [comment]
@zyznull please kill this process before starting an experiment. nni experiment won't create such a process again if it detected that there is already a process running, however, this running process may be a zombie process.

**Comment by zyznull** [comment]
> @zyznull please kill this process before starting an experiment. nni experiment won't create such a process again if it detected that there is already a process running, however, this running process may be a zombie process.

This process is create by the experiment.When I stop a experiment,the process not exist.

**Comment by QuanluZhang** [comment]
Thanks, @zyznull . Could you join in gitter (https://gitter.im/Microsoft/nni?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to talk about this problem?

**Comment by QuanluZhang** [comment]
Thanks for @zyznull 's assistance. The reason of this error is that the file `gpu_metrics` is read before this file is created. But this does not affect the execution of the experiment. We will make this error log more clear. The problem that the trial job keeps in waiting state is because all gpus are occupied by other processes.
