### ISSUE TITLE
[feature request] Support Kubeflow TFJob/PyTorchJob v1beta2

### ISSUE THREAD

**Issue by gaocegege** [microsoft/nni#1033]
**What would you like to be added**:

Kubeflow now releases tf-operator/pytorch-operator 0.5, which introduces v1beta2 CRD. I think we should support the new CRD.

**Why is this needed**:

Sync with the Kubeflow release.

**Without this feature, how does current nni work**：

Use v1alpha2 or v1beta1.

**Components that may involve changes**:

`src/nni_manager/config/kubeflow/`, `docs` about kubeflow, `src/nni_manager/training_service/kubernetes/kubeflow`

**Brief description of your proposal if any**:

Support Kubeflow TFJob/PyTorchJob v1beta2

**Comment by SparkSnail** [comment]
Will v1alpha2 and v1beta1 still be supported in kubeflow? And what are the new features in v1beta2?

**Comment by gaocegege** [comment]
v1alpha2 is not supported in the new version, but I think we should keep it since the users may use older version. v1beta1 is still supported.

In v1beta2, we add two new fields in CRD:

```diff
< package v1beta1
---
> package v1beta2
18c18
< 	common "github.com/kubeflow/tf-operator/pkg/apis/common/v1beta1"
---
> 	common "github.com/kubeflow/tf-operator/pkg/apis/common/v1beta2"
23d22
< // +genclient:noStatus
45a45,54
> 	// Specifies the duration in seconds relative to the startTime that the job may be active
> 	// before the system tries to terminate it; value must be positive integer.
> 	// This method applies only to pods with restartPolicy == OnFailure or Always.
> 	// +optional
> 	ActiveDeadlineSeconds *int64 `json:"activeDeadlineSeconds,omitempty"`
> 
> 	// Optional number of retries before marking this job failed.
> 	// +optional
> 	BackoffLimit *int32 `json:"backoffLimit,omitempty"`
> 
```

But it does not affect nni, IMO.

**Comment by SparkSnail** [comment]
Hi, thanks for your advice for nni. Since v1beta2 is the latest release of kubeflow, nni may support this new feature in v0.8 release before the end of May.
