### ISSUE TITLE
question about kubeflow storage

### ISSUE THREAD

**Issue by WestonLu** [Microsoft/nni#1034]
Hi, I am new to kubeflow and nni, I am learning  AutoML, I am curious about how is the following function implemented?

"Output files of kubeflow job, like stdout, stderr, trial.log or model files, will also be copied back to the storage volumn. " 

https://github.com/Microsoft/nni/blob/afce6d4a709d7d9123dfafc83ea550b47bef2db3/docs/en_US/KubeflowMode.md

Which code should I learn to understand this?  Thank you for any help.

**Comment by gaocegege** [comment]
I am not one of the authors of nni but I am the maintainer @kubeflow , I think the code is here: https://github.com/Microsoft/nni/blob/master/src/nni_manager/training_service/kubernetes/kubeflow/kubeflowTrainingService.ts#L423

In kubeflow tf-operator v0.5 (newest version), we do not have built-in PVC support. nni inserts a PVC in every replica's spec, then all output files will be stored in the PVC.

**Comment by WestonLu** [comment]
@gaocegege Thank you. I also have tried to use [katib](https://github.com/kubeflow/katib), which is a component of kubeflow. May i ask if katib has the same function so I can persistent these output files?

**Comment by gaocegege** [comment]
The feature is not supported in katib yet. Because it is hard to cleanup the volume when the experiment is deleted.

**Comment by WestonLu** [comment]
@gaocegege ok, thank you very much.

**Comment by SparkSnail** [comment]
The answer from @gaocegege is correct, I'll close this issue, if you have any problem, you can reopen it.
