### ISSUE TITLE
[feature request] Show metric in hyperparameter visualization page

### ISSUE THREAD

**Issue by gaocegege** [Microsoft/nni#1044]
**What would you like to be added**:\

Now we only show the hyperparameters:

![image](https://user-images.githubusercontent.com/5100735/57189072-579ae280-6f3c-11e9-91b7-7e5d2c3dd205.png)

And it does not help us understand the relation between the hyperparameters and metrics. It will be better to add a new dimension `objective` in the graph, just like vizier does:

![image](https://user-images.githubusercontent.com/5100735/57189086-97fa6080-6f3c-11e9-803b-cba88a3012ba.png)

**Why is this needed**:

Easy to use.

**Without this feature, how does current nni work**：

No idea.

**Components that may involve changes**:

Frontend

**Brief description of your proposal if any**:

**Comment by QuanluZhang** [comment]
@gaocegege , we use curve color to show how good each configuration is, the darker the better.

**Comment by gaocegege** [comment]
OK gotcha, personally prefer the vizier way. Thanks for the reply
