### ISSUE TITLE
Add a parallel algorithm to improve the performance of TPE with large concurrency

### ISSUE THREAD

**Issue by PurityFan** [microsoft/nni#1052]
**What would you like to be added**: When the number of concurrencies is large, the points selected by the TPE will be concentrated, we will add excellent parallel algorithms to solve this problem.

**Why is this needed**: Better usage of computing resource

**Components that may involve changes**: A new algorithm to handle parallel TPE and related doc

**Comment by Crysple** [comment]
I've run experiments on some [test functions](https://en.wikipedia.org/wiki/Test_functions_for_optimization) with different experimental configuration ( trial concurrency, constant_liar_type etc.).

# Experiment One on [Ackley Function](https://en.wikipedia.org/wiki/Ackley_function)

## Ackley Function

- There are only two args in the Ackley Function. Denote them as x and y, then the function is:
![image](https://user-images.githubusercontent.com/20517842/60771042-7c662e80-a114-11e9-9f5e-2d0862622c77.png)

- Its global optimum point is:

  ![image](https://user-images.githubusercontent.com/20517842/60771047-9142c200-a114-11e9-8bfc-a7e44f8b8a57.png)

- An image on it might be:

![image](https://user-images.githubusercontent.com/20517842/60771058-afa8bd80-a114-11e9-954a-539c8fb710c7.png)

## Experiment

### Setup

Two contrast experiments: Exp 1 with Exp 2 and Exp 3 with Exp 4 to see if there's any improvement.

|       | Max Trial Num | Trial Concurrency | Parallel_Optimize    | Constant_liar |
|-------|---------------|-------------------|----------------------|---------------|
| Exp 1 | 160           | 20                | True                 | min           |
| Exp 2 | 160           | 20                | False (original TPE) | /             |
| Exp 3 | 400           | 50                | True                 | min           |
| Exp 4 | 400           | 50                | False (original TPE) | /             |

### Result

#### Exp 1 and Exp 2

- Exp 1 (new TPE with min)

  - Top 10
    ![image](https://user-images.githubusercontent.com/20517842/60771159-2e522a80-a116-11e9-963b-fe80fc4f35c8.png)
  - Distribution of Sampled Points
    ![image](https://user-images.githubusercontent.com/20517842/60771176-85f09600-a116-11e9-9ed7-2288a863e4bd.png)



- Exp 2 (old TPE)
  - Top 10
    ![image](https://user-images.githubusercontent.com/20517842/60771153-14184c80-a116-11e9-83e8-373f25cc160f.png)
  - Distribution of Sampled Points
    ![image](https://user-images.githubusercontent.com/20517842/60771180-9dc81a00-a116-11e9-8806-811d91231115.png)




#### Exp 3 and Exp 4

- Exp 3 (new TPE with min)

  - Top 10
    ![image](https://user-images.githubusercontent.com/20517842/60771203-dec02e80-a116-11e9-8dd1-4ea680ea4dee.png)

  - Distribution of Sampled Points
    ![image](https://user-images.githubusercontent.com/20517842/60771211-fe575700-a116-11e9-9b94-4b039e5535de.png)




- Exp 4 (old TPE)
  - Top 10
    ![image](https://user-images.githubusercontent.com/20517842/60771197-c7814100-a116-11e9-8ce1-cb100679d826.png)
  - Distribution of Sampled Points
    ![image](https://user-images.githubusercontent.com/20517842/60771207-f26b9500-a116-11e9-87fc-5bc1c96abd1a.png)


In this experiment on Ackley Function, TPE in parallel mode tends to explore more and find a better 'best result'.
Besides, It can be seen that in the new version of TPE, the distribution of the sampled points is more even

#### Strange Phenomenon

With parallel optimize mode on, TPE will generate several trial configurations that are totally the same. **This might be a potential bug.**

![image](https://user-images.githubusercontent.com/20517842/60771306-a7eb1800-a118-11e9-9f51-6501f9892598.png)

**Comment by scarlett2018** [comment]
- [ ] Need an option to switch between parallel model and non-parallel model

**Comment by suiguoxin** [comment]
solved in https://github.com/microsoft/nni/pull/1373
