### ISSUE TITLE
Remote TrainingService on Windows

### ISSUE THREAD

**Issue by demianzhang** [microsoft/nni#1053]
**What would you like to be added**: Remote support on Windows and build pipeline for it

**Comment by scarlett2018** [comment]
> **What would you like to be added**: Remote support on Windows and build pipeline for it

Hi @demianzhang - For your requirement to make windows remote training node, would you mind share what's the target OS (i.e. server or windows 10)?

**Comment by demianzhang** [comment]
> > **What would you like to be added**: Remote support on Windows and build pipeline for it
> 
> Hi @demianzhang - For your requirement to make windows remote training node, would you mind share what's the target OS (i.e. server or windows 10)?

Hi Scarlett, the remote mode in this part means from Windows 10 (local) to connect with Linux remote servers.

**Comment by scarlett2018** [comment]
> Hi Scarlett, the remote mode in this part means from Windows 10 (local) to connect with Linux remote servers.

Thanks @demianzhang for the quick responds, this should already supported.

**Comment by squirrelsc** [comment]
It's already supported, not a feature request.
