### ISSUE TITLE
Tensorflow version before 1.12.2 has security issue

### ISSUE THREAD

**Issue by leelaylay** [microsoft/nni#1057]
**Short summary about the issue/question**:
The tensorflow 1.4 and 1.12 dependencies in following requirements.txt are reported as vulnerabilities.
 1. https://github.com/Microsoft/nni/blob/master/examples/trials/ga_squad/requirements.txt
2. https://github.com/Microsoft/nni/blob/master/examples/trials/network_morphism/requirements.txt
 
 
The security issue is extracted from here by github:
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=tensorflow

**Brief what process you are following**: 
Upgrade tensorflow version in the ga_squad and network_morphism examples.

**How to reproduce it**: 
I upgrade Tensorflow version to 1.13.1 and test the examples above successfully in local conda environment and docker python environment.

**nni Environment**:
- nni version: v0.7
- nni mode(local|pai|remote): local
- OS: Linux
- python version: 3.6
- is conda or virtualenv used?:  conda
- is running in docker?: yes

**Anything else we need to know**:
Related to #1056

**Comment by xuehui1991** [comment]
Fixed and close.
