### ISSUE TITLE
Tutorial for automatically tuning SPTAG on nni

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#1059]
SPTAG(https://github.com/Microsoft/SPTAG) is a distributed approximate nearest neighborhood search (ANN) library which provides a high quality vector index build, search and distributed online serving toolkits for large scale vector search scenario. It has around 10 hyperparameters. nni would help a lot on finding good configurations for it. It would be better to have a tutorial for this scenario.

**Comment by scarlett2018** [comment]
@QuanluZhang - we might able to use this one: https://github.com/microsoft/SPTAG/blob/7b531ea5e1d9ae8dc9dae7c515536cf56c162141/docs/Parameters.md#nni-for-parameters-tuning

**Comment by ultmaster** [comment]
Done.
