### ISSUE TITLE
[bug]Local TrainingService read gpu metrics file before it is created

### ISSUE THREAD

**Issue by SparkSnail** [microsoft/nni#1061]
**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version: v0.7
- nni mode(local|pai|remote):
- OS: Linux
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by szymonzmyslony** [comment]
Does anybody know what this might be caused by or how should I go around solving it?

**Comment by SparkSnail** [comment]
This bug is caused because nni create gpu_metric file slower than reading process, so nni will read gpu_metrics file before it is created. NNI will catch this error, and the experiment will continue to run after the gpu_metrics file is created, but there will be an error message in nniManager.log. This bug will be fixed in pr https://github.com/microsoft/nni/pull/1068
