### ISSUE TITLE
Unable to open webUI link

### ISSUE THREAD

**Issue by PurityFan** [microsoft/nni#1063]
**Short summary about the issue/question**: After launching the NNI experiment using the nnictl, the corresponding WebUI link cannot be opened.

**How to reproduce it**: 

Start an NNI experiment and we will get info like this:

```
INFO: Starting restful server...
INFO: Successfully started Restful server!
INFO: Setting local config...
INFO: Successfully set local config!
INFO: Starting experiment...
INFO: Successfully started experiment!
-----------------------------------------------------------------------
The experiment id is bbAwkH5z
The Web UI urls are: http://127.0.0.1:8050   http://172.17.0.1:8050
-----------------------------------------------------------------------

You can use these commands to get more information about the experiment
```

But we can't open the WebUI link of http://127.0.0.1:8050, or http://172.17.0.1:8050

The information of the WebUI is:

```
This site can’t be reached xxx refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

**nni Environment**: 
- nni version: v0.7
- nni mode(local|pai|remote): local
- OS: Linux
- python version: python 3.5
- is conda or virtualenv used?: no 
- is running in docker?: no

**need to update document(yes/no)**: yes

**Comment by PurityFan** [comment]
This question is raised by external users.

Unable to open the WebUI may have the following reasons:

1.  http://127.0.0.1, http://172.17.0.1 and http://10.0.0.15 are referred to localhost, if you start your experiment on the server or remote machine. You can replace the IP to your server IP to view the WebUI,  like http://[your_server_ip]:8080
2. If you still can't see the WebUI after you use the server IP, you can check the proxy and the firewall of your machine. Or use the browser on the machine where you start your NNI experiment.
3. Another reason may be your experiment is failed and NNI may fail to get the experiment infomation. You can check the log of NNImanager in the following directory: ~/nni/experiment/[your_experiment_id] /log/nnimanager.log

@PurityFan Will also update the doc in QuickStart and FAQ.

**Comment by MDaskalovAtBE** [comment]
I had the error - This site can’t be reached localhost:8080 refused to connect.
After some digging I was able to sort it by signing in via the docker desktop app.
Then go to Settings -> Features in development -> Enable host networking

And then it started working as intended.

Hope that helps someone in the future.
