### ISSUE TITLE
nnictl: command not found

### ISSUE THREAD

**Issue by FerusAndBeyond** [microsoft/nni#1065]
I've followed the instructions for installation on macOS Mojave 10.14.4 but when I try to run an example I get ```nnictl: command not found```. I tried install using ```pip3 install nni``` and also installing from the source but for both I get the same thing.

**Comment by FerusAndBeyond** [comment]
Fixed it by running setup.py in nni, but this wasn't specified in the instructions.

**Comment by sunyinglong** [comment]
我也碰巧遇到了这个问题，并且使用  **running setup.py** 的方法，但是问题依然存在，请问如何解决

**Comment by huhuhang** [comment]
> 我也碰巧遇到了这个问题，并且使用 **running setup.py** 的方法，但是问题依然存在，请问如何解决

安装好之后，可以尝试刷新 `source ~/.bashrc`
zsh 就是 `source ~/.zshrc`

**Comment by blakeedwards823** [comment]
> Fixed it by running setup.py in nni, but this wasn't specified in the instructions

where did you find setup.py? I am running into the same issue!

**Comment by andreyvelich** [comment]
Try to add `/Users/{user_id}/Library/Python/3.7/bin` folder to your PATH. 
The `nnictl` binary file should be there.
