### ISSUE TITLE
Status DONE even though experiment failed

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/nni#1082]
In https://github.com/Microsoft/Recommenders project we found an issue while using nni with version 0.5.2.1

A experiment that we were running failed, however, when doing `nnictl experiment status` we get DONE as status. See an example here
```
t43sJ           2019/05/14 12:37:13       2019/05/14 12:37:20       FAILED
mjcHW           2019/05/14 12:37:13       2019/05/14 12:37:20       FAILED
UUY52           2019/05/14 12:37:13       2019/05/14 12:37:18       FAILED
ZwbPn           2019/05/14 12:37:13       2019/05/14 12:37:22       FAILED
N5eqe           2019/05/14 12:37:13       2019/05/14 12:37:23       FAILED
-------------------------------------------------------------------------------------
(reco_bare) recocat@recotestmachineclone:/tmp/tmpl9sbi9m2/experiments/DrwXiO1B/trials/A6Te2$ nnictl experiment status
{
    "errors":[],
    "status":"DONE"
}

```

Is this fixed in a newer version of nni?

FYI @anargyri

**Comment by anargyri** [comment]
To add some context: the trials failed because of a bug in the script. However, the failure of the trials does not propagate to the experiment.

**Comment by miguelgfierro** [comment]
This is the bug Andreas was referring to:

the reason why the run failed is because we had a bug in our code:
```
[2019-05-14 12:36:45] PRINT Processing epoch 27
[2019-05-14 12:36:46] PRINT Processing epoch 28
[2019-05-14 12:36:46] PRINT Processing epoch 29
[2019-05-14 12:36:46] DEBUG (surprise_svd/MainThread) Evaluating...
[2019-05-14 12:36:46] DEBUG (surprise_svd/MainThread) rmse = 0.976205
[2019-05-14 12:36:46] ERROR (surprise_svd/MainThread) compute_ranking_predictions() got an unexpected keyword argument 'recommend_seen'
Traceback (most recent call last):
  File "svd_training.py", line 145, in <module>
    main(params)
  File "svd_training.py", line 129, in main
    svd = svd_training(params)
  File "svd_training.py", line 60, in svd_training
    recommend_seen=params['recommend_seen'])
TypeError: compute_ranking_predictions() got an unexpected keyword argument 'recommend_seen'

```

**Comment by anargyri** [comment]
> This is the bug Andreas was referring to:
> 
> the reason why the run failed is because we had a bug in our code:
> 
> ```
> [2019-05-14 12:36:45] PRINT Processing epoch 27
> [2019-05-14 12:36:46] PRINT Processing epoch 28
> [2019-05-14 12:36:46] PRINT Processing epoch 29
> [2019-05-14 12:36:46] DEBUG (surprise_svd/MainThread) Evaluating...
> [2019-05-14 12:36:46] DEBUG (surprise_svd/MainThread) rmse = 0.976205
> [2019-05-14 12:36:46] ERROR (surprise_svd/MainThread) compute_ranking_predictions() got an unexpected keyword argument 'recommend_seen'
> Traceback (most recent call last):
>   File "svd_training.py", line 145, in <module>
>     main(params)
>   File "svd_training.py", line 129, in main
>     svd = svd_training(params)
>   File "svd_training.py", line 60, in svd_training
>     recommend_seen=params['recommend_seen'])
> TypeError: compute_ranking_predictions() got an unexpected keyword argument 'recommend_seen'
> ```

This is the output of trial.log.

**Comment by QuanluZhang** [comment]
@miguelgfierro @anargyri , this is an expected behavior. Trial's failure is not propagated to experiment's state. As long as the experiment successfully finishes all the trials (succeeded or failed) or consumes the whole time budget, its state would become DONE. Errors from components, such as tuning algorithms, nnimanager, training services, lead to ERROR state of the experiment.

For your requirement, a possible solution is checking both experiment's state and trial's state. Trials' state can be obtained through `nnictl trial ls`, or directly calling restful api: http://IP:Port/api/v1/nni/trial-jobs

**Comment by miguelgfierro** [comment]
awesome @QuanluZhang, thanks for the explanation
