### ISSUE TITLE
similar issue to #769, can't run mnist example with gpu, python is installed by pyenv

### ISSUE THREAD

**Issue by benwu232** [microsoft/nni#1087]
Hi,

I met issue similar to #769 

My env is:
python 3.7.2 under ananaconda installed on pyenv
ubuntu 16.04
nvidia 1070, cuda10, 
nni 0.7

When I run mnist or other examples with gpunum = 0, everything is ok. But when I set gpuNum = 1, the status in the WebUI is always waiting. 
![image](https://user-images.githubusercontent.com/3946864/57967410-20dbb800-7991-11e9-850d-353c61c7de52.png)

I tired setting the absolute path of python in config.yml like

 `command:` /home/abc/.pyenv/versions/anaconda3-5.3.1/bin/python mnist.py

but no luck.  I have no idea now. 

Any help is welcome! Thanks!

**Comment by demianzhang** [comment]
Hi, this issue may cause by other process occupying gpu(there is no free gpu found), please have a check refer to [#1037](https://github.com/microsoft/nni/issues/1037#issuecomment-487909455)

**Comment by benwu232** [comment]
Here is my nnimanager.log. I found some erros:

[2019-5-18 17:05:16] ERROR [ 'Read GPU summary failed with error: ',
  { ChildProcessError: Command failed: tail -n 1 /tmp/nni/script/gpu_metrics
  tail: cannot open '/tmp/nni/script/gpu_metrics' for reading: No such file or directory
   `tail -n 1 /tmp/nni/script/gpu_metrics` (exited with error code 1)

Please have a look! Below is the fulltext.

[2019-5-18 17:05:13] INFO [ 'Datastore initialization done' ]
[2019-5-18 17:05:13] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2019-5-18 17:05:13] INFO [ 'RestServer start' ]
[2019-5-18 17:05:13] INFO [ 'Construct local machine training service.' ]
[2019-5-18 17:05:13] INFO [ 'RestServer base port is 8080' ]
[2019-5-18 17:05:15] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"/home/wb/.pyenv/versions/anaconda3-5.3.1/bin/python mnist-keras.py","codeDir":"/media/wb/T08/work/try_nni/.","gpuNum":1}' ]
[2019-5-18 17:05:15] INFO [ 'required GPU number is 1' ]
[2019-5-18 17:05:15] INFO [ 'Starting experiment: yo157VGs' ]
[2019-5-18 17:05:15] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2019-5-18 17:05:15] INFO [ 'Add event listeners' ]
[2019-5-18 17:05:15] INFO [ 'Run local machine training service.' ]
[2019-5-18 17:05:16] ERROR [ 'Read GPU summary failed with error: ',
  { ChildProcessError: Command failed: tail -n 1 /tmp/nni/script/gpu_metrics
  tail: cannot open '/tmp/nni/script/gpu_metrics' for reading: No such file or directory
   `tail -n 1 /tmp/nni/script/gpu_metrics` (exited with error code 1)
      at callback (/home/wb/.pyenv/versions/anaconda3-5.3.1/nni/node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:296:5)
      at ChildProcess.emit (events.js:182:13)
      at maybeClose (internal/child_process.js:962:16)
      at Socket.stream.socket.on (internal/child_process.js:381:11)
      at Socket.emit (events.js:182:13)
      at Pipe._handle.close (net.js:606:12)
    name: 'ChildProcessError',
    code: 1,
    childProcess:
     { ChildProcess: [Function],
       fork: [Function: fork],
       _forkChild: [Function: _forkChild],
       exec: [Function: exec],
       execFile: [Function: execFile],
       spawn: [Function: spawn],
       spawnSync: [Function: spawnSync],
       execFileSync: [Function: execFileSync],
       execSync: [Function: execSync] },
    stdout: '',
    stderr:
     'tail: cannot open \'/tmp/nni/script/gpu_metrics\' for reading: No such file or directory\n' } ]
[2019-5-18 17:05:16] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2019-5-18 17:05:16] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"optimizer": "Adam", "learning_rate": 0.001}}' ]
[2019-5-18 17:05:21] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"optimizer\\": \\"Adam\\", \\"learning_rate\\": 0.001}}","index":0}}' ]
[2019-5-18 18:05:26] INFO [ 'Change NNIManager status from: RUNNING to: NO_MORE_TRIAL' ]

**Comment by demianzhang** [comment]
It doesn't matter with this error in version 0.7, the experiment will continue to run. BTW, [#1061](https://github.com/microsoft/nni/issues/1061) has fixed it. Could you provide the gpu utilization. Is there any other process running on the gpu? Currently only free gpu without any process will be found to run trial, otherwise it will wait in loop.

**Comment by benwu232** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:03:00.0  On |                  N/A |
| 18%   47C    P8    11W / 180W |    756MiB /  8118MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1611      G   /usr/lib/xorg/Xorg                           453MiB |
|    0      2270      G   cinnamon                                     221MiB |
|    0      2950      G   ...quest-channel-token=4014920997432722048    73MiB |
|    0     11350      G   .../tools/pycharm-community/jre64/bin/java     3MiB |
|    0     12388      G   nvidia-settings                                0MiB |
+-----------------------------------------------------------------------------+

In my case, I didn't start other process. When I start nnictl with gpuNum=1, the process is waiting, gpu utilization is about 0. When the gpuNun is changed to 0, everything is ok. 

Why can't nni just run the process and don't care about if the gpu is free or not?

**Comment by demianzhang** [comment]
| 0 1611 G /usr/lib/xorg/Xorg 453MiB |
| 0 2270 G cinnamon 221MiB |
| 0 2950 G ...quest-channel-token=4014920997432722048 73MiB |
| 0 11350 G .../tools/pycharm-community/jre64/bin/java 3MiB |
| 0 12388 G nvidia-settings 0MiB |
These are the other processes running on the gpu, there are two ways to solve it currently:
1. Make a free gpu without any processes.
2. Get around way referring to [#1037](https://github.com/microsoft/nni/issues/1037#issuecomment-487873290)

**Comment by benwu232** [comment]
At least the first two processes are managed by system so I can't stop them. There are many users like me don't have multiple GPUs. 

I think it would be better if you provide an option for the users to run the task and take the risk. In most cases, the existed processes are small and will not influnce the task and can be ignored. A warning message is enough here.

**Comment by demianzhang** [comment]
Have you tried second method? Set gpuNum = 0 and set CUDA_VISIBLE_DEVICES = '0' in your code or CUDA_VISIBLE_DEVICES=0 python3 mnist.py. It will get around of the problem.

**Comment by demianzhang** [comment]
hi @benwu232  nni v0.8 [PR 1109](https://github.com/microsoft/nni/pull/1109/files) have fixed the problem, you can   set maxTrialNumPerGpu and useActiveGpu variables in config yaml to run the example.

`useActiveGpu: true` will solved the problem you met. You can alse set `maxTrialNumPerGpu` to specify the max concurrency trial number on a GPU device. Please have a try with nni v0.8.

**Comment by leckie-chn** [comment]
close this issue. @benwu232 feel free to reopen it if not solved.

**Comment by cjissmart** [comment]
I have the same problem. I have only one nvidia's card in ubuntu. And the card is partly occupied by the system's process which isn't killed. It results that I can't use the efficient GPU resource. I think it is a huge bug so that some people give up the package. I hope nni team can fix it as possible as quickly.

**Comment by cjissmart** [comment]
> | 0 1611 G /usr/lib/xorg/Xorg 453MiB |
> | 0 2270 G cinnamon 221MiB |
> | 0 2950 G ...quest-channel-token=4014920997432722048 73MiB |
> | 0 11350 G .../tools/pycharm-community/jre64/bin/java 3MiB |
> | 0 12388 G nvidia-settings 0MiB |
> These are the other processes running on the gpu, there are two ways to solve it currently:
> 
>     1. Make a free gpu without any processes.
> 
>     2. Get around way referring to [#1037](https://github.com/microsoft/nni/issues/1037#issuecomment-487873290)
> 
> 
> If the gpu is occupied by other process with certain Memory-Usage which may cause OOM error and it is hard to manage how to find available gpu.

I have tried every method you suggest. However none of all works for me!

**Comment by shaofulien** [comment]
I was also suffered in this problem by using xgboost-gpu version. Setting "useActiveGpu: true " solve this issue for my case.
