### ISSUE TITLE
ChildProcessError while using examples/trials/cifar10_pytorch

### ISSUE THREAD

**Issue by janehiii** [microsoft/nni#1090]
shows following in nnimanagerLog.json:

 { ChildProcessError: Command failed: tail -n 1 /tmp/nni/script/gpu_metrics
  tail: 无法打开'/tmp/nni/script/gpu_metrics' 读取数据: 没有那个文件或目录
   `tail -n 1 /tmp/nni/script/gpu_metrics` (exited with error code 1)

**Short summary about the issue/question**:
cann't run examples/trials/cifar10_pytorch correctly

**Brief what process you are following**: 
command as folling:
nnictl create --config nni/examples/trials/cifar10_pytorch/config.yml

**How to reproduce it**: 

**nni Environment**:
- nni version:0.7
- nni mode(local|pai|remote):local
- OS:ubuntu18.04
- python version:3.7
- is conda or virtualenv used?: yes
- is running in docker?:no

**need to update document(yes/no)**:no

**Anything else we need to know**:

**Comment by QuanluZhang** [comment]
@janehiii  Could you go through the following issues: https://github.com/microsoft/nni/issues/1017 and https://github.com/microsoft/nni/issues/1061, and see whether they could solve your problem?

**Comment by janehiii** [comment]
> @janehiii Could you go through the following issues: #1017 and #1061, and see whether they could solve your problem?

thank you . But I still strongly request an error report about this problem.
Is there any way let the experiment running even though there are other processes on GPU? Is it must be  exclusive？

**Comment by QuanluZhang** [comment]
@janehiii good suggestion, we will provide this option to users in the next release.
