### ISSUE TITLE
[dup #608] GPU can't be total free, anyway to run trials use only one GPU

### ISSUE THREAD

**Issue by YangZeyu95** [microsoft/nni#1092]
Hello nni team!

When I set gpuNum: 1 in 'config.py'  the trial is keeping waiting.
I know that was because of  GPU is not totally free but I have only one GPU and can't terminate all process run on GPU. Is there any way to use GPU?

**Comment by YangZeyu95** [comment]
![Screenshot from 2019-05-21 13-08-36](https://user-images.githubusercontent.com/28431121/58069885-90d48300-7bc9-11e9-85c4-ded3a15d290f.png)
![Screenshot from 2019-05-21 13-09-26](https://user-images.githubusercontent.com/28431121/58069909-ac3f8e00-7bc9-11e9-8f94-7dbc9a622fc1.png)

**Comment by janehiii** [comment]
ref: nni/src/nni_manager/training_service/local/gpuScheduler.ts 
line80
this.gpuSummary.gpuInfos.filter((info: GPUInfo) => info.activeProcessNum === 0)

**Comment by YangZeyu95** [comment]
@janehiii I replaced line 80 with line 77 and run 'install.sh' but didn't work

**Comment by scarlett2018** [comment]
@YangZeyu95 - we are working on sharing GPU feature in #608, the code is under review now, any suggestions or questions is appreciated.

**Comment by SparkSnail** [comment]
This feature is supported in https://github.com/microsoft/nni/pull/1109.
