### ISSUE TITLE
IPv4 error

### ISSUE THREAD

**Issue by janehiii** [microsoft/nni#1102]
**Short summary about the issue/question**:
It will throw this when i use pai (not openpai)
https://github.com/microsoft/nni/blob/e9eaa00dcdfe2b4649016af8506c2ae7858432bd/src/nni_manager/common/utils.ts#L322

I have to fix my IP in code and succeed.
https://github.com/microsoft/nni/blob/e9eaa00dcdfe2b4649016af8506c2ae7858432bd/src/nni_manager/training_service/pai/paiTrainingService.ts#L429

as
`        const nniManagerIp: string = '192.168.xxx.xxx';`

**Comment by QuanluZhang** [comment]
@janehiii [this](https://nni.readthedocs.io/en/latest/FAQ.html#job-management-error-getipv4address-failed-because-os-networkinterfaces-eth0-is-undefined) may be helpful. You could specify IP address in the config file.

**Comment by janehiii** [comment]
> @janehiii [this FAQ](https://nni.readthedocs.io/en/latest/FAQ.html#job-management-error-getipv4address-failed-because-os-networkinterfaces-eth0-is-undefined) may be helpful. You could specify IP address in the config file.

thank you,solved
