### ISSUE TITLE
Silent fail on Windows using included examples

### ISSUE THREAD

**Issue by DianeHu** [microsoft/nni#1104]
The mnist example fails silently on Windows. The service starts successfully but all trials fail and no error logs exist. The directory where logs should be stored according to documentation has the logs for the startup process, but the logs for each trial don't exist. Stdout/Stderror also don't have any output. None of this changes if I change the flag for log level (e.g., even with --debug on startup no logs are produced).

**Comment by demianzhang** [comment]
Hi, have you run PowerShell as administrator with this command first?
```bash
    Set-ExecutionPolicy -ExecutionPolicy Unrestricted
```

**Comment by scarlett2018** [comment]
@demianzhang - is it possible to check the ExecutionPolicy before running the trials?

**Comment by DianeHu** [comment]
I did, and yes 64 bit anaconda

**Comment by demianzhang** [comment]
Could you have a try with v0.8 and provide more details, such as the nnimanager startup log. Which example have you tried (config_windows.yml)? Does webui show errors？

**Comment by scarlett2018** [comment]
@DianeHu @demianzhang  - in case of need, you guys can have the Gitter IM in NNI's gitter channel: https://gitter.im/Microsoft/nni

**Comment by DianeHu** [comment]
I just tried with v0.8 and there's no difference, the startup output seems to be normal:

![image](https://user-images.githubusercontent.com/26827404/58999106-f1aeae80-87b8-11e9-93b8-74a02c4055af.png)

config_windows.yml is the one I tried, I've also tried mnist-keras config.yml. The webui doesn't show any errors in overview but it shows all trials failing in trial details. Stderr and stdout are pretty empty:

![image](https://user-images.githubusercontent.com/26827404/58999161-35a1b380-87b9-11e9-9724-d2f0a5334435.png)

![image](https://user-images.githubusercontent.com/26827404/58999168-3c302b00-87b9-11e9-8ed1-989ef88b6076.png)

The trial logs don't exist--those folders are completely empty.

**Comment by demianzhang** [comment]
Could you provide the nnimanager.log refer to [How to debug](https://github.com/microsoft/nni/blob/master/docs/en_US/HowToDebug.md#experiment-root-directory)? Thanks.

**Comment by DianeHu** [comment]
I'm not sure why but I just reran with config_windows and it seems to be working. I didn't change anything but I think it's all good now--thanks!

**Comment by leckie-chn** [comment]
close this issue. @DianeHu feel free to reopen it.
