### ISSUE TITLE
Enhancement: ability to adjust rendering interval.

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#1106]
**Background**
When running experiments that have 2000+ trials, the web page is overloaded for frequent rendering. We need the ability to adjust rendering interval (manually or automatically).

**Without this feature, how does current nni work**：slow render

**Components that may involve changes**: webui

**Brief description of your proposal if any**:--

**Comment by yangou1988** [comment]
Add auto refresh setting drop-down & Refresh button  at the top navigation area.

- Users can click the drop down and choose auto refresh 10s, 30s, 60s or disable it.
- Users can also click the Refresh button to refresh manually.

overview
![Web 1920 – 2](https://user-images.githubusercontent.com/44491713/58446384-22e10c00-8133-11e9-996e-3d0853b67045.png)

Drop down
![image](https://user-images.githubusercontent.com/44491713/58446409-32f8eb80-8133-11e9-9f18-5b224f5156ac.png)

After secleted 'Refresh every 30s'
![image](https://user-images.githubusercontent.com/44491713/58446432-4efc8d00-8133-11e9-9a9e-53bb1d7cdfe2.png)
