### ISSUE TITLE
WebUI not support nested params visualization

### ISSUE THREAD

**Issue by silverlining21** [microsoft/nni#1110]
![image](https://user-images.githubusercontent.com/8264748/58393596-e4374d00-8071-11e9-875c-9350c6a0522a.png)

I try the expample/trials/mnist-cascade-space/mnist.py got the problem. 

any support plans？

BRs

**Comment by scarlett2018** [comment]
@silverlining21 - thanks for raising the issue, just added this to our backlog and would need more discussion on how to implement it in the future. If you have any suggestions on the design or would like to contribute directly that will be highly appreciated.

For now, @leelaylay - may you update the example, to let users know this feature is broken and under design.

**Comment by leelaylay** [comment]
> @silverlining21 - thanks for raising the issue, just added this to our backlog and would need more discussion on how to implement it in the future. If you have any suggestions on the design or would like to contribute directly that will be highly appreciated.
> 
> For now, @leelaylay - may you update the example, to let users know this feature is broken and under design.

@scarlett2018   I will check it later.

**Comment by xuehui1991** [comment]
@silverlining21 @scarlett2018  For now, we don't support showing nested search space in WebUI. Ans we update docs in this PR[https://github.com/microsoft/nni/pull/1115].

**Comment by lvybriage** [comment]
estimate: 2d

**Comment by ultmaster** [comment]
Nested params is working for at least examples now.
