### ISSUE TITLE
Files opened but not closed, replace the syntax with "with open(filename, mode)"

### ISSUE THREAD

**Issue by farziengineer** [microsoft/nni#1124]
https://github.com/microsoft/nni/blob/e6b3828cc98119e4ba9293f73fb9a0b5b0ce3740/tools/nni_cmd/tensorboard_utils.py#L98-L99

https://github.com/microsoft/nni/blob/252d35e0773a652ee1f108b0303e342cb2367b7e/tools/nni_cmd/launcher.py#L128-L129

The above two files are opened, but not closed. Can this be replaced with the following sytax
```python
with open(filename, mode) as f:
  ...
```

> f you do not explicitly close it then the file will be closed automatically when the file object is destroyed. In CPython this will happen as soon as there are no more references to it, e.g. if it is a local variable in a function and the function ends. However if an exception is thrown in the function and file is not explicitly closed using a with statement or a try:...finally: then a reference to the file will be kept as part of the stack trace in the traceback object and the file will not be closed, at least until the next exception is thrown.
[Read here](https://stackoverflow.com/a/2404671/8577285)

Can I raise a PR for the above?

**Comment by QuanluZhang** [comment]
Sure, go ahead. Thanks

**Comment by QuanluZhang** [comment]
fixed by contributor @farziengineer , thanks!
