### ISSUE TITLE
Iterating over the dictionary twice.

### ISSUE THREAD

**Issue by farziengineer** [microsoft/nni#1134]
https://github.com/microsoft/nni/blob/358efb26b6d7576bc8179a37c190e5f916773b5e/examples/trials/ga_squad/trial.py#L82-L84

https://github.com/microsoft/nni/blob/358efb26b6d7576bc8179a37c190e5f916773b5e/examples/trials/weight_sharing/ga_squad/data.py#L244-L246

The above snippets iterate over the dictionary twice. Shall we change it more efficient and pythonic
```python
return word_dict.get(word, word_dict['<unk>'])
```

**Comment by xuehui1991** [comment]
@farziengineer  Thank you for your questions. Good suggestion!

**Comment by scarlett2018** [comment]
@farziengineer - Thanks a lot for the feedback, it sounds like a good enhancement for the tool, would you like to commit a PR for your suggestion?

**Comment by farziengineer** [comment]
@scarlett2018 Hi, I have already raised a PR for this. https://github.com/microsoft/nni/pull/1140

**Comment by scarlett2018** [comment]
@farziengineer - wonderful, thanks for contribute to NNI =)!
