### ISSUE TITLE
inconsistent format of "nnictl update" commands

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#1137]
**Short summary about the issue/question**: `nnictl update trialnum` and `nnictl update duration` have different formats of optional args. For `nnictl update trialnum`, the format should be `nnictl update trialnum --id XXX --value XXX`, while for `nnictl update duration`, the format should be `nnictl update duration XXX --value XXX`.

**Brief what process you are following**: after creating an experiment, then update its maxTrialNum, and maxDuration.

**How to reproduce it**: after creating an experiment, then update its maxTrialNum, and maxDuration.

**nni Environment**:
- nni version: v0.7
- nni mode(local|pai|remote): local
- OS: ubuntu
- python version: 3.5
- is conda or virtualenv used?: no
- is running in docker?: no

**need to update document(yes/no)**: maybe

**Anything else we need to know**: None

**Comment by SparkSnail** [comment]
Fixed in https://github.com/microsoft/nni/pull/1146
