### ISSUE TITLE
What does batch_num mean? What value should it be?

### ISSUE THREAD

**Issue by pratimanagare** [microsoft/nni#1155]
**Short summary about the issue/question**:
I want to know what the batch_num argument means? why is it in the parameters dict since it consists of hyperparameters? Default value for batch_num is 2000, does that mean it'll take 2000 batches of a given batch_size?

**nni Environment**:
- nni version: 0.7
- nni mode(local|pai|remote): local
- OS: Ubuntu 18.04(server)
- python version: 3.5.2
- is conda or virtualenv used?:  no
- is running in docker?: yes

**Comment by xuehui1991** [comment]
Hello @pratimanagare.  The batch_num means the "it'll take 2000 batches of a given batch_size data". 

“batch_num” doesn't have to be put into parameter dict that consists of hyper-parameter. You also could hard-code in trial codes.
