### ISSUE TITLE
support third party tuner, assessor, advisor.

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/nni#1165]
Currently, some contributors write tuners for NNI, and they'd like to merge tuners into NNI repo. It's not easy to control quality and fix bugs. So it's better to let contributors maintain their tuner, assessor, advisor on their repos, and NNI provides a way to install it. It's a different scenario with customized, as it's focus on sharing.

Supported functions,
1. Install by nnictl packages like below. Support a config url. In the config, it should includes, name, type(tuner, assessor, advisor), dependent pip packages, copied sources, entry(inherited tuner), help url(optional), description(optional)
   nnictl package install --config=https://github.com/my/tuner/customized_tuner.config
2. List supported tuners, so user know which is installed.
3. When using it, user just needs to specify name, not full path like customized tuner. It needs NNI to check name conflict when install package.
4. uninstall?

**Comment by leckie-chn** [comment]
The fundamental issue is **name resolution** of tuners, no matter its usage scenarios (built-in, customized, etc. ). In my opinion, a good design to leverage [Python module search mechanism](https://docs.python.org/3/tutorial/modules.html#the-module-search-path) and let user make the tuner available through one of the following ways:
* configure `PYTHONPATH` with the code of tuner
* install tuner module through package management systems such as `pip` or `conda`

Then `config.yml` can looks like:
```yaml
tuner:
    tunerName: tuner.module.name # just make this tuner class importable 
...
```

My key concern is to keep the software complexity of NNI at a low level.

**Comment by squirrelsc** [comment]
> The fundamental issue is **name resolution** of tuners, no matter its usage scenarios (built-in, customized, etc. ). In my opinion, a good design to leverage [Python module search mechanism](https://docs.python.org/3/tutorial/modules.html#the-module-search-path) and let user make the tuner available through one of the following ways:
> 
> * configure `PYTHONPATH` with the code of tuner
> * install tuner module through package management systems such as `pip` or `conda`
> 
> Then `config.yml` can looks like:
> 
> ```yaml
> tuner:
>     tunerName: tuner.module.name # just make this tuner class importable 
> ...
> ```
> 
> My key concern is to keep the software complexity of NNI at a low level.

I added one more feature, NNI should support a configurable name list, so that user needs to specify name in config only. And when installation, NNI should detect name conflict.

**Comment by scarlett2018** [comment]
@QuanluZhang - i believe this is supported with #2287, right?

**Comment by kvartet** [comment]
> @QuanluZhang - i believe this is supported with #2287, right?

yes, it had been supported, although I'm not sure whether in this pr. I will close this issue, feel free to reopen it.
