### ISSUE TITLE
UX improvement for showing Error log

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#1173]
**What would you like to be added**: When an experiment is failed, users have to go to "~/nni/experiments/<experiment-id>/log/" to check `nnimanager.log` and `dispatcher.log`. For some users, they may not know where these log files are. Even if they know the location of these log files, every time the experiment is failed, they have to check those files manually. If users can click and view the content of these files directly through webui, it would be more friendly and convenient.

**Why is this needed**: more convenient

**Without this feature, how does current nni work**：stated above

**Components that may involve changes**: webui

**Comment by yangou1988** [comment]
Click/hover Erro 'i' button > Erro information > Click '**Learn more**'
![Erro-Learnmore](https://user-images.githubusercontent.com/44491713/59327580-831fa280-8d1c-11e9-93f1-4ad291ac9403.jpg)
Anchored **Dispatcher Log / NNI Manager Log** from right side
So users can check and preview the log information (Last 4096 bytes) at NNI portal directly and then download or view the full log.
![Dispatcher Log](https://user-images.githubusercontent.com/44491713/59327592-8c107400-8d1c-11e9-8b18-e27cbe81a24f.png)
![NNI Manager Log](https://user-images.githubusercontent.com/44491713/59327594-8dda3780-8d1c-11e9-9a47-3942847f7c37.png)

Also redesign the UX of **Download** in the navigation 
![image](https://user-images.githubusercontent.com/44491713/59327893-7fd8e680-8d1d-11e9-82f6-1f5585240b02.png)

Click Download > Click **Experiment parameters**
![Download-ExperimentParameter](https://user-images.githubusercontent.com/44491713/59327923-94b57a00-8d1d-11e9-8cea-600b9df09d96.png)

Anchored **Experiment parameters** from right side as same as **Dispatcher Log / NNI Manager Log** 
![ExperimentParameter](https://user-images.githubusercontent.com/44491713/59327960-adbe2b00-8d1d-11e9-9769-e3ee4df33e80.png)
