### ISSUE TITLE
can all the tune algorithm in NNI are use to solve CASH  problems?

### ISSUE THREAD

**Issue by ajoeajoe** [microsoft/nni#1178]
CASH problems is short for combined algorithm selection and tune hyper-parameters, is it NNI are treated algorithm selection and tune hyper-parameters as a  CASH problems.

**Comment by ajoeajoe** [comment]
I just want to make a  comparison of different tune algorithm regarding to the CASH problems

**Comment by ajoeajoe** [comment]
>>> import openml
>>> benchmark_suite = openml.study.get_study('OpenML-CC18', 'tasks')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joe/anaconda3/envs/openml/lib/python3.6/site-packages/openml/study/functions.py", line 64, in get_study
    study = cast(OpenMLStudy, _get_study(study_id, entity_type='run'))
  File "/Users/joe/anaconda3/envs/openml/lib/python3.6/site-packages/openml/study/functions.py", line 83, in _get_study
    main_entity_type, entity_type,
ValueError: Unexpected entity type 'task' reported by the server, expected 'run'

**Comment by ajoeajoe** [comment]
I can fix it use study.get_suite('OpenML-CC18')
but when I run use the following codes，errors happened：



from openml import study,datasets, tasks, runs, flows, config
import sklearn
from sklearn import tree
from sklearn.impute import SimpleImputer
benchmark_suite = study.get_suite('OpenML-CC18') # obtain the benchmark suite
print(benchmark_suite.tasks)
clf = sklearn.pipeline.Pipeline(steps=[('imputer',SimpleImputer()),('estimator',tree.DecisionTreeClassifier())]) # build a sklearn classifier
for task_id in benchmark_suite.tasks: # iterate over all tasks
  print(task_id)
  task = tasks.get_task(task_id) # download the OpenML task
  X, y = task.get_X_and_y() # get the data (not used in this example)
  config.apikey = '' # set the OpenML Api Key
  run = runs.run_model_on_task(task,clf) # run classifier on splits (requires API key)
  score = run.get_metric_fn(sklearn.metrics.accuracy_score) # print accuracy score
  print('Data set: %s; Accuracy: %0.2f' % (task.get_dataset().name,score.mean()))
  run.publish() # publish the experiment on OpenML (optional)
  print('URL for run: %s/run/%d' %(config.server,run.run_id))

**Comment by ajoeajoe** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-10-cd1a278b05b9> in <module>()
     12   X, y = task.get_X_and_y() # get the data (not used in this example)
     13   config.apikey = '0e5ae5d3e3522ac3ee387344173e3a97' # set the OpenML Api Key
---> 14   run = runs.run_model_on_task(task,clf) # run classifier on splits (requires API key)
     15   score = run.get_metric_fn(sklearn.metrics.accuracy_score) # print accuracy score
     16   print('Data set: %s; Accuracy: %0.2f' % (task.get_dataset().name,score.mean()))

1 frames
/usr/local/lib/python3.6/dist-packages/openml/extensions/functions.py in get_extension_by_model(model, raise_if_no_extension)
     91     if len(candidates) == 0:
     92         if raise_if_no_extension:
---> 93             raise ValueError('No extension registered which can handle model: {}'.format(model))
     94         else:
     95             return None

ValueError: No extension registered which can handle model: <openml.tasks.task.OpenMLClassificationTask object at 0x7f68c50fe630>

**Comment by QuanluZhang** [comment]
@ajoeajoe NNI could deal with the CASH problem. A simple example is shown in https://github.com/microsoft/nni/tree/master/examples/trials/sklearn/regression, it chooses different models for regression, and tunes hyper-parameters. 

You could also use [nested search space](https://nni.readthedocs.io/en/latest/SearchSpaceSpec.html#types) ([example](https://github.com/microsoft/nni/blob/master/examples/trials/mnist-nested-search-space/search_space.json) of nested search space) to deal with more real scenarios, for example, choosing a model and tuning the hyper-parameters that only belongs to this model.

**Comment by ajoeajoe** [comment]
is it also a Cash example in https://github.com/microsoft/nni/tree/master/examples/trials/sklearn/classification，i just can not figure out which example is a cash problem for there so many trials in NNI，and is NNI designed using Cash(combined algorithm selection and tune hyper-parameters) as Auto-sklearn do？ have you any release paper for NNI，it is a black box for me.

**Comment by QuanluZhang** [comment]
The "sklearn/classification" is not a CASH example, because it does not choose model. Another example for CASH is https://github.com/microsoft/nni/blob/master/examples/trials/cifar10_pytorch/search_space.json, it chooses both model and hyper-parameters.

NNI could help users to tune both models and hyper-parameters, but NNI does **not** focus on the end-to-end scenario, in which users simply provide training data then the best found model is returned. For the CASH problem, NNI supports the following use case: you want to find the best model as well as the corresponding hyper-parameters from several candidate models (along with their hyper-parameters) for your task.

The difference between Auto-sklearn and NNI is that, Auto-sklearn targets the end-to-end scenario, it implements some for example regression models and specifies the range of each models' tunable hyper-parameters. After you provide the training data, it finds the best model and hyper-parameters from that search space. NNI is more like a framework, auto-sklearn can be implemented on NNI, leveraging different tuning algorithms on NNI and NNI's scalability. 

We will provide the paper for NNI soon.

**Comment by ajoeajoe** [comment]
Many thanks,  I can see something and judged by the search_space.json file and looking forward to reading the paper.

**Comment by ajoeajoe** [comment]
I just want to open this issue:   is it Grid Search can solve CASH problems , it seems that it usually used for hyper-parameters optimization, have you do some revision for Grid Search.
