### ISSUE TITLE
UX for Resubmit FAILED trial

### ISSUE THREAD

**Issue by leckie-chn** [microsoft/nni#1180]
@yangou1988 @lvybriage please fill in the details

- Only failed trials can be "resubmit"
- Resubmited trial is reusing the original trial's parameter, same parameter ids
- A new trial id will be generated on the resubmission action
--- should we overwrite(delete) the original trial on the success of the new trial: NO, keep them as standalone trials
--- total trial count keep the same or --: --

**Comment by yangou1988** [comment]
Redesign the Intermediate, Retry and Kill as three button，Show full name when hover over
![image](https://user-images.githubusercontent.com/44491713/60698889-1e72f480-9f24-11e9-807a-ad0ce09985a0.png)
Small Pane
![image](https://user-images.githubusercontent.com/44491713/60699037-b07afd00-9f24-11e9-9e7c-43770d757243.png)

**Comment by yangou1988** [comment]
Add tooltip design of resubmit
**After select 'Resubmit' button**
![image](https://user-images.githubusercontent.com/44491713/61444287-a83bac80-a97d-11e9-8052-7376dbcf1d5a.png)

**After select 'Confirm' button** 
![image](https://user-images.githubusercontent.com/44491713/61444401-e89b2a80-a97d-11e9-821e-26210cfef1c5.png)

1 step: Selcet 'Resubmit'
![image](https://user-images.githubusercontent.com/44491713/61444460-09638000-a97e-11e9-90e5-90dba8732247.png)
2 step: Select ' Confirm'
3 step: Resubmit successfully - 'OK'
![image](https://user-images.githubusercontent.com/44491713/61444507-184a3280-a97e-11e9-92db-f358d3af981e.png)

**Comment by scarlett2018** [comment]
We had discussed to change to other designs, closing this as won't fix.
