### ISSUE TITLE
Can I report multiple metrics to the tuner?

### ISSUE THREAD

**Issue by pratimanagare** [microsoft/nni#1183]
**Short summary about the issue/question**:
Can I report multiple metrics to the tuner? Like accuracy, f1score, etc. If yes, how do I do that?
Currently we can report one metric which is considered default by the tuner.

**nni Environment**:
- nni version: 0.8
- nni mode(local|pai|remote): local
- OS:Ubuntu 18.04
- python version: 
- is conda or virtualenv used?:  no
- is running in docker?: yes

**need to update document(yes/no)**: yes

**Comment by xuehui1991** [comment]
Hey @pratimanagare, you could report multiple metrics to the tuner. 
You could give a python dict like "{'default': accuracy,  "f1_score": f1score}" to nni.report_final_result(). Then tuner will receive the dict but only considered the value which key is 'default' by the built-in tuner in nni.
Other key-value could show in the WebUI, but built-in tuner will not use them.  If you want to consider multiple metrics, I guess there are two ways: 1) pack multiply metric as one.  2) re-implement a new tuner and use multiple metric as you like.

Thank you. 
Feel free to ask more questions.

**Comment by pratimanagare** [comment]
> Hey @pratimanagare, you could report multiple metrics to the tuner.
> You could give a python dict like "{'default': accuracy, "f1_score": f1score}" to nni.report_final_result(). Then tuner will receive the dict but only considered the value which key is 'default' by the built-in tuner in nni.
> 
> Other key-value could show in the WebUI, but built-in tuner will not use them. If you want to consider multiple metrics, I guess there are two ways:
> 
> 1. pack multiply metric as one.
> 2. re-implement a new tuner and use multiple metric as you like.
> 
> Thank you.
> Feel free to ask more questions.

Thank you for the response. I'll post further queries, if any.

**Comment by arvoelke** [comment]
> Other key-value could show in the WebUI ...

I've tried reporting multiple metrics, but I don't see them in the WebUI, or in any of the log files. Do I need to log them myself and then walk through all the trial directories to parse my own logs, or maybe see if they can be retrieved from the `db/nni.sqlite` file? Essentially, I'm trying to look at the relationship between hyper-parameters and a vector of metrics across an experiment (while optimizing for the `'default'` metric, which is a weighted combination of several of these metrics).

**Comment by kingaza** [comment]
@arvoelke, you can access the multiple metrics by clicking the button 'download->experiment summary', and then you can see the values in 'trialMessage->finalMetricData->data->'.
However, it is not friendly to user. 
Please let me know if any other choice or improvement.

**Comment by kingaza** [comment]
Oh, I made a mistake.
You can add columns for multiple metrics in the trial jobs board
