### ISSUE TITLE
MetisTuner doesn't support maximize mode

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/nni#1193]
**Short summary about the issue/question**: 
Metis Tuner doesn't support maximize mode, it converges to the minimum in a toy experiment even though optimize_mode is defined as "maximum".

**Brief what process you are following**: 

**How to reproduce it**: 
Run an experiment in "maximize" mode. 

**nni Environment**:
- nni version: 0.8
- nni mode(local|pai|remote): local
- OS: linux
- python version: 3.7
- is conda or virtualenv used?: conda
- is running in docker?: no

**need to update document(yes/no)**: no

**Anything else we need to know**:
Seems that OptimizeMode from nni.utils is not working.

**Comment by xuehui1991** [comment]
@suiguoxin Could you post your experiment log (or WebUI) here?

**Comment by xuehui1991** [comment]
Fix in #1195 .
