### ISSUE TITLE
Show other metrics effect (corresponding to different params) in hyper-parameter graph

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#1202]
**What would you like to be added**: show other key-values in hyper-graph

**Why is this needed**: When final result is dict, I also want to see other key-values in this graph. But now just have default metric.

![无标题](https://user-images.githubusercontent.com/35484733/60066661-6a5eb600-973a-11e9-88cf-e19b5bc58aad.png)

**Without this feature, how does current nni work**：--

**Components that may involve changes**: webui (UI & UX)

**Brief description of your proposal if any**: --

**Comment by ultmaster** [comment]
Using #1483 to track this issue. Closing it for now.
