### ISSUE TITLE
webui not support search parameters value

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#1208]
**What would you like to be added**: could input trial's parameters value to search specific trial

**Why is this needed**:  It's more convenient to use nni.

**Without this feature, how does current nni work**：--

**Components that may involve changes**: webui

**Brief description of your proposal if any**: --

**Comment by scarlett2018** [comment]
@lvybriage - does cmdline support this?

**Comment by lvybriage** [comment]
> @lvybriage - does cmdline support this?

This issue can also support in July release.

**Comment by lvybriage** [comment]
> @lvybriage - does cmdline support this?

@scarlett2018 Cmdline not support this at present.

**Comment by lvybriage** [comment]
Had supported in V1.0
