### ISSUE TITLE
Can nni show the best metric curve during search progress in WebUI?

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1218]
**Short summary about the issue/question**:
For now, nni shows every trial metric during search progress, but can we show another curve that could represent the best metric curve?

**Brief what process you are following**: 

<!--deployment related issues
Please fill this for deployment related issues: 
N/A

**How to reproduce it**: 

N/A

**nni Environment**:
- nni version: 0.8
- nni mode(local|pai|remote): all mode
- OS: all OS
- python version: pyhon 3.6
- is conda or virtualenv used?:  conda
- is running in docker?: no

**need to update document(yes/no)**: no

**Anything else we need to know**: no

**Comment by suiguoxin** [comment]
![2019-07-22 18_49_17-Bayesian Optimization with Robust Bayesian Neural Networks](https://user-images.githubusercontent.com/12380769/61627059-72fec980-acb1-11e9-8deb-aabd9b09cc05.png)
 
for reference

**Comment by lvybriage** [comment]
![image](https://user-images.githubusercontent.com/35484733/62124289-6fe08a80-b2fc-11e9-8356-9a3863af29d8.png)

![image](https://user-images.githubusercontent.com/35484733/62124297-77a02f00-b2fc-11e9-9deb-acf7db045982.png)
