### ISSUE TITLE
Restful server start failed!

### ISSUE THREAD

**Issue by liudonggang** [microsoft/nni#1223]
When I run an experiment，A "ERROR: Restful server start failed! "has occurred, I don't know why this problem occurred, I was in the docker container to start the trial, run the command: nnictl create  -c config. yml-p XXXX

**Comment by liudonggang** [comment]
I try use  request.get('http://localhost:12306/api/v1/nni/check-status'), An error has occurred，error msg:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7fd77c6e1fd0>: Failed to establish a new connection: [Errno 111] Connectionrefused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=12306): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd77c6e1fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=12306): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd77c6e1fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

Excuse me, why does this happen?

**Comment by liudonggang** [comment]
I solved this problem. When I modified localhost  to 127.0.0.1,then i try  request.get('http://127.0.0.1:12306/api/v1/nni/check-status')
the requests could succeed, but when I used localhost, the NNI Restful server service could not be successfully started. 
My solution was to modify /etc/hosts file and add "127.0.0.1 localhost", so that the bug could be successfully solved.
Is it possible to make changes in the original code?

**Comment by dliang0406** [comment]
I have this issue too! 
I installed nni by pip install and it worked well for days and suddenly one day the error message shows up "Restful server start failed!"
I checked my "/etc/hosts" file and "127.0.0.1 localhost" has been there.
I reinstalled nni with this command "python3 -m pip install nni --no-cache-dir" but nothing changed.

**Comment by Weak-Chicken** [comment]
I had the same problem when I tried to run nni in docker container.

I solved this by removing my docker container proxy config file: ```~/.docker/config.json```

So for those of you who do not use it in docker, I think it is a good idea to check your environment variables like ```HTTP_PROXY``` or ```HTTPS_PROXY``` and remove them if they are set.

**Comment by ultmaster** [comment]
Can we add some FAQs about the common network issue that could cause the start failure of Restful Server?

**Comment by henryslzhao** [comment]
I have this issue too! The nni is run in docker. 
I checked my "/etc/hosts" file and "127.0.0.1 localhost" has been there.

**Comment by scarlett2018** [comment]
> I have this issue too! The nni is run in docker.
> I checked my "/etc/hosts" file and "127.0.0.1 localhost" has been there.

@henryslzhao - may you try suggestions in https://nni.readthedocs.io/en/latest/Tutorial/FAQ.html ? thanks.

**Comment by scarlett2018** [comment]
Closing the issue as overdue (with no updates from user). Please feel free to reopen the issue if you are still seeing the issue and have updates to work with us.

**Comment by hamideh-h** [comment]
I also received this error and I don't know how to fix it.

I checked the node version and it is fine. I also unset the http_proxy && https_proxy
Localhost is also added in the hosts but I still have this problem

INFO: expand codeDir: . to C:\kit\code\Mnist-annotation-autoML.
INFO: Starting restful server...
ERROR: Restful server start failed!
INFO: Stdout:

**Comment by BlancRay** [comment]
Because Windows uses IPv6 by default when available,  you need to change the IPv6/IPv4 preference by add a prefix policy to prefer IPv4 addresses over IPv6.
Simply check is `ping localhost`, see if is `127.0.0.1` or `[::1]`

Default Windows prefix policy table:
```
C:\> netsh interface ipv6 show prefixpolicies
Querying active state...

Precedence  Label  Prefix
----------  -----  --------------------------------
        50      0  ::1/128
        40      1  ::/0
        30      2  2002::/16
        20      3  ::/96
        10      4  ::ffff:0:0/96
         5      5  2001::/32
```

You can change it with `netsh int ipv6 set prefix ::/96 55 3` with `run as administrator` and reboot after set.  #2398

**Comment by hamideh-h** [comment]
Thanks a lot, BlanceRay.

However, I run "netsh int ipv6 set prefix ::/96 55 3" with administrator permission but I am still receiving this error and I think it is because of npm.

ERROR: Restful server start failed!
INFO:   Stdout:
-----------------------------------------------------------------------
                Experiment start time 2020-11-11 08:59:01
-----------------------------------------------------------------------




INFO:   Stderr:
-----------------------------------------------------------------------
                Experiment start time 2020-11-11 08:59:01
-----------------------------------------------------------------------
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'typescript-ioc'

Although I have "typescript-ioc" in "C:\Program Files\nodejs\node_modules\npm\node_modules" directory. my node version is v15.1.0
