### ISSUE TITLE
"passwd" is not allowed to be empty

### ISSUE THREAD

**Issue by husimple** [microsoft/nni#1227]
- nni version:  0.5.2
- nni mode(local|pai|remote): remote
- OS:   centos7
- python version: 3.6.6
- is conda or virtualenv used:  conda used 
- is running in docker?:  yes

ERROR: Failed! Error is: {"statusCode":400,"error":"Bad Request","message":"child "body" fails because [child "machine_list" fails because ["machine_list" at position 0 fails because [child "passwd" fails because ["passwd" is not allowed to be empty]]]]"}

**Comment by ragavvenkatesan** [comment]
@husimple What's the solution for this?

**Comment by ragavvenkatesan** [comment]
Also, I see [this commit](https://github.com/microsoft/nni/commit/1bc23f4f92650af0ac1f58d505c91bee01bc16a6), but it does not seem to be part of version 1.5.
