### ISSUE TITLE
webui nav 

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#1230]
**Short summary about the issue/question**: I think the trial detail and overview are very important, but now it was covered.

![image](https://user-images.githubusercontent.com/35484733/60408172-6c1ff200-9bf0-11e9-9a16-b888397de6b5.png)

**Brief what process you are following**:  --

**How to reproduce it**:  --

**nni Environment**: 
- nni version: 0.9
- nni mode(local|pai|remote): local
- OS: --
- python version: --
- is conda or virtualenv used?:  --
- is running in docker?: --

**need to update document(yes/no)**: --

**Anything else we need to know**: --

**Comment by yangou1988** [comment]
NAV UI updated. 
ps: add icon for Download
Large
![Web 1920 – 13](https://user-images.githubusercontent.com/44491713/60497331-34e03c80-9ce7-11e9-8f71-53c221382cd3.png)

Medium
![Web 1920 – 15](https://user-images.githubusercontent.com/44491713/60497281-1a0dc800-9ce7-11e9-8bf0-238f2fadec73.png)

Small (Mobile)
![iPhone XR-XS Max – 1](https://user-images.githubusercontent.com/44491713/60497384-52150b00-9ce7-11e9-86a6-8999054f0aad.png)
