### ISSUE TITLE
NAS mode doc improvement

### ISSUE THREAD

**Issue by leckie-chn** [microsoft/nni#1233]
add https://github.com/microsoft/nni/pull/1201#issue-291094510 to documentation. 

**Add a config**
multiphase: false
#set multiPhase to true if the experiment is multi-phase.
#Currently, only 3 training service: local, remote and pai mode support multiphase; And the following builtin tuners: .. support multiphase;

update doc: https://github.com/microsoft/nni/blob/master/docs/en_US/AdvancedFeature/MultiPhase.md

**Comment by rabbit008** [comment]
#1242
