### ISSUE TITLE
ENAS Example stuck in WAITING

### ISSUE THREAD

**Issue by gwestner94** [microsoft/nni#1238]
**Short summary about the issue/question**:
When running the CIFAR10 example from https://github.com/countif/enas_nni using the predefined cifar10_macro_config.yml the experiment status is stuck in "WAITING".
I noticed that the `enas_nni` repo references the `dev-enas` branch, which is now fully merged with the master branch, is that correct?
What are the reasons why an experiment is stuck in `WAITING` mode?
Is there any other usage guide for the ENAS tuner?

**Brief what process you are following**: 

**How to reproduce it**: 
- Use pip3 to install NNI
- Download dataset described in https://github.com/countif/enas_nni
- Start trial using `nnictl create --config cifar10_macro_config.yml`

**nni Environment**:
- nni version: 0.9 (pip3 install)
- nni mode(local|pai|remote): local
- OS: ubuntu 16.04
- python version: python 3.5.2
- is conda or virtualenv used?: no
- is running in docker?: no

**need to update document(yes/no)**: yes

**Anything else we need to know**:

**Comment by xuehui1991** [comment]
@gwertzman Thank you. @leelaylay will check this problem.

**Comment by leelaylay** [comment]
@gwertzman 
1. The `dev-enas` branch is deleted in the official repo, but I keep a clone in my fork. https://github.com/leelaylay/nni/tree/dev-enas
I think newer nni version ( before 0.9 ) can still support this `enas_nni` example.
2. After I test this problem on my local environment, I find that it may be related to the version change. NNI changes the multiphase APIs since version 0.9 which is sliightly different from the usage in `enas_nni` repo. The experiment is successfully started when I switch to 0.8 version.
```shell
# uninstall nni first
pip3 uninstall nni
# install nni 0.8 version
pip3 install nni==0.8
```
 3. `WAITING` mode, Each trial in this example needs about 0.5 GPU day to finish and these trials run in sequence. One trial usually takes one full GPU card by default. So, there is always one running experiment as well as one waiting experiment. If you have more GPU cards, you can change `gpuNum` in the config file, such as `cifar10_macro_config.yml`. 
Now, NNI supports flexible GPU assignation, you can refer to this [ExperimentConfig](https://github.com/microsoft/nni/blob/master/docs/en_US/ExperimentConfig.md) for more details.

4. If you want to know about the ENAS tuner, you can refer to this [General NAS Interfaces](https://github.com/microsoft/nni/blob/master/docs/en_US/GeneralNasInterfaces.md).

**Comment by gwestner94** [comment]
Thank you for the quick feedback, I also figured out, that setting the `useActiveGpu` Property is needed to use GPU cards, where other processes are already running, if not the experiment is stuck in WAITING.
I will try the version change in check the ENAS sample.

**Comment by xuehui1991** [comment]
@chicm-ms Seems multiphase refactor may cause some problem. Could you check this problem?

**Comment by chicm-ms** [comment]
Multiphase interface has been updated in nni v0.9,  enas tuner need make some changes to work with nni, reference:  https://github.com/countif/enas_nni/issues/6

**Comment by ultmaster** [comment]
Hi all. It seems the issue itself has been addressed. We will have future plans on NAS refactoring. Closing it for now.

**Comment by qtz93** [comment]
Hello, I ran the cifar10 example of enas_nni(Reference: https://github.com/countif/enas nunni) with NNI version 0.8.1, which caused the following error:

```python
Traceback (most recent call last):
  File "src/ptb/nni_child_ptb.py", line 241, in <module>
    tf.app.run()
  File "/home/hadoop/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/ptb/nni_child_ptb.py", line 226, in main
    child_arc = trial.parset_child_arch(child_arc)
  File "/data/notebook_data/notebook_dirs/qiutongzhu/ex2_nni/trials/trials_enas/trials/enas/src/nni_child.py", line 42, in parset_child_arch
    for i in range(0,len(child_arc)): # TypeError: object of type 'NoneType' has no len()
TypeError: object of type 'NoneType' has no len()
```

Later, I found that during the execution of the program src/cifar10/nni_child_cifar10.py, the following fragment reported an error, in which the printed result of the parameters value was None.

```python
...
    if is_micro:
        while True:
            if epoch >= FLAGS.num_epochs:
                break

            logger.debug("get parameter")
            #parameters =  nni.get_parameters()
            parameters = nni.get_next_parameter()  # The result of parameters is **None**
            logger.debug(parameters)
            normal_arc,reduce_arc = trial.parset_micro_arch(parameters)
            assert len(normal_arc) == len(reduce_arc)

            logger.debug("parse arch finish!")
...
```

Who can help me? Thanks!

**Comment by ultmaster** [comment]
@qtz93 Probably you should try with 0.9.1.1?

**Comment by qtz93** [comment]
> @qtz93 Probably you should try with 0.9.1.1?

Thank you for your prompt answer. I tried 0.9.1.1 yesterday and made the following error:

[10/24/2019, 03:31:30 PM] ERROR (nni.main/MainThread) No module named 'nni.multi_phase'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/nni/__main__.py", line 198, in <module>
    main()
  File "/opt/anaconda3/lib/python3.6/site-packages/nni/__main__.py", line 163, in main
    args.tuner_args)
  File "/opt/anaconda3/lib/python3.6/site-packages/nni/__main__.py", line 76, in create_customized_class_instance
    class_module = importlib.import_module(module_name)
  File "/opt/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "xxx/trials/trials_enas/trials/enas/./../../tuners/enas/nni_controller_ptb.py", line 16, in <module>
    from src.nni_controller import ENASBaseTuner
  File "xxx/trials/trials_enas/trials/enas/./../../tuners/enas/src/nni_controller.py", line 21, in <module>
    from nni.multi_phase.multi_phase_tuner import MultiPhaseTuner
ModuleNotFoundError: No module named 'nni.multi_phase'

After reading @leelaylay's answer, I plan to switch to 0.8 and try, but there are still mistakes. --__--

**Comment by qtz93** [comment]
The statement of nni.get_next_parameter() is None, why? Any ideas will be appreciated.
