### ISSUE TITLE
nni Kubeflow/trial keeper err

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/nni#1240]
**Short summary about the issue/question**:
1.	Trial keeper takes around 10 minutes to exit after the trial is finished.
2.	Outputting logs in trial makes the trial 6X slower than the one that does not output logs.
3.	The error message (at TLSWrap.onStreamRead) 

**Brief what process you are following**: 
run nni in kubeflow

**How to reproduce it**: 

**nni Environment**: 
- nni version: 0.8
- nni mode(local|pai|remote): kubeflow
- OS: Linux 
- python version: 3
- is conda or virtualenv used?:  
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by suiguoxin** [comment]
issue 1: unable to replay
issue 2: what does it mean 'add log in trial' ?

**Comment by suiguoxin** [comment]
issue 3 : same with #1261

**Comment by chicm-ms** [comment]
fixed by disable logCollection by default.
