### ISSUE TITLE
Show the experimental running status more prominently;

### ISSUE THREAD

**Issue by rabbit008** [microsoft/nni#1243]
**What would you like to be added**:More prominently show the experimental running status
![image](https://user-images.githubusercontent.com/28092647/60590997-fb373080-9dcf-11e9-8d81-4becdf76c468.png)

**Why is this needed**:At present, NNI supports the rendering interval. When the interval is long, the user may not know the running state of the experiment. Because the page is completely static, the position of the running state is not obvious. I hope WebUI can add a dynamic flag to display the experiment's running state.

**Without this feature, how does current nni work**：normally

**Components that may involve changes**:Running state

**Brief description of your proposal if any**:Maybe add a dynamic logo instead of "running“.

**Comment by yangou1988** [comment]
![runningload](https://user-images.githubusercontent.com/44491713/60698801-b2908c00-9f23-11e9-9895-75d21b053ede.gif)
