### ISSUE TITLE
ERROR: Kill trial job failed

### ISSUE THREAD

**Issue by cvJie** [microsoft/nni#1256]
I want to kill a trial job,but always faild.

The alg run in windows local.and   use "nnictl trial ls" get the trial message as fllows:

[
    {
        "hyperParameters":[
            "{\"parameter_source\":\"algorithm\",\"parameter_id\":0,\"parameter_index\":0,\"parameters\":{\"learning_rate\":0.001,\"conv_size\":2,\"dropout_rate\":0.7907991690451954,\"batch_size\":32,\"hidden_size\":124}}"
        ],
        "id":"af4FB",
        "logPath":"file://localhost:C:\\Users\\someone\\nni\\experiments\\QM3Nnbkf\\trials\\af4FB",
        "sequenceId":0,
        "startTime":"2019/07/04 06:17:05",
        "status":"RUNNING"
    }
]

Now,I want to kill it . use code as  :  nnictl trial kill -T af4FB    or  nnictl trial kill -T "af4FB"

but it failed.

please give me some advises.

**Comment by scarlett2018** [comment]
@cvJie - which NNI version are you using? any error message when it fails?
