### ISSUE TITLE
The filter button of the intermediate result cannot be clicked

### ISSUE THREAD

**Issue by rabbit008** [microsoft/nni#1263]
**Short summary about the issue/question**:
When I was screening the intermediate results, I found that occasionally the button could not be clicked.
![image](https://user-images.githubusercontent.com/28092647/60702654-16ba4c80-9f32-11e9-8574-0ea8baf45f76.png)

**Brief what process you are following**: 
Click the filter button, without any data, click confirm, will prompt for input data request, close the filter, and then open, there will be a bug that the confirm  button cannot be clicked.

as above
**How to reproduce it**: 
Refresh the page

**nni Environment**:
- nni version:0.9.1906260743
- nni mode(local|pai|remote):local
- OS:Win10 
- python version:3.7
- is conda or virtualenv used?: 
- is running in docker?:no

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by lvybriage** [comment]
It was fixed in pr #1295. @rabbit008
