### ISSUE TITLE
Removal of pipy package version 0.5.2.1 caused all our tests to fail

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/nni#1264]
Hi, in Recommenders project we were using the version 0.5.2.1 https://github.com/microsoft/recommenders/blob/master/scripts/generate_conda_file.py#L95. This package disappeared from pipy, so now all our test pipeline is failing. 

We are using NNI in this notebook https://github.com/microsoft/recommenders/blob/master/notebooks/04_model_select_and_optimize/nni_surprise_svd.ipynb

We have several questions:
1) Would it be possible to put the package 0.5.2.1 back in pipy?
2) If we consider changing to a newer version, are there many breaking changes?
3) do you plan to have a version in pipy tht is not erased?

Thanks

cc @gramhagen, @loomlike @anargyri

**Comment by chicm-ms** [comment]
Hi, we have built version `v0.5.2.1.1` to replace `v0.5.2.1`, if you are not able to use latest version, you can use `v0.5.2.1.1`.  There should not be any breaking changes in `v0.5.2.1.1`.

**Comment by miguelgfierro** [comment]
thanks @chicm-ms, we will add this to the code
