### ISSUE TITLE
always got no more trails, but I set  the maxTrialNum to 20.

### ISSUE THREAD

**Issue by Royzon** [microsoft/nni#1268]
The task always ends after four trails, but I did set the maxTrialNum to 20, where is the possible reason?

**Comment by xuehui1991** [comment]
Hey @Royzon, could you provide some context as follows:

-  nni version

- dispatcher.log and nni_manager.log

- task description

Thank you~

**Comment by Royzon** [comment]
Now I solved, it seems my maxExecDuration is too short to work.
