### ISSUE TITLE
ade

### ISSUE THREAD

**Issue by ademkayalar** [microsoft/nni#1275]
**What would you like to be added**:

**Why is this needed**:

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by rabbit008** [comment]
@ademkayalar Excuse me, do you have any suggestions or questions about nni, if any, please describe as much as possible, we will try our best to assist you..

**Comment by scarlett2018** [comment]
I'm closing this issue, as it does not have any valid inputs.
