### ISSUE TITLE
Add dynamic icon when refresh status is activated

### ISSUE THREAD

**Issue by rabbit008** [microsoft/nni#1279]
**What would you like to be added**:Add dynamic icon and remove the forbidden icon when refresh status is activated .

**Why is this needed**:The current refresh status is not significant.

**Without this feature, how does current nni work**：When the experiment runs very slowly, the user cannot determine if the refresh is successful.

**Components that may involve changes**:fresh button

**Brief description of your proposal if any**:Maybe you can
1.Add a dynamic icon when user clicks the refresh button ;
2.Delete the forbidden icon when user clicks the refresh button ;

**Comment by yangou1988** [comment]
**Refersh button** 
Rest - Hover -Pressed/Selected
![image](https://user-images.githubusercontent.com/44491713/61436452-6c98e680-a96d-11e9-8324-df506ba0a6ff.png)


**Overview**
Hover
![image](https://user-images.githubusercontent.com/44491713/61436766-0f516500-a96e-11e9-91c8-4df522035e34.png)
Pressed/Selected
![image](https://user-images.githubusercontent.com/44491713/61436803-25f7bc00-a96e-11e9-8063-b67e1d177bab.png)

**Trial detail** 
Hover
![image](https://user-images.githubusercontent.com/44491713/61436633-cef1e700-a96d-11e9-8a06-7e4ff055eaff.png)
Pressed/Selected
![image](https://user-images.githubusercontent.com/44491713/61436689-ec26b580-a96d-11e9-9f40-f55ddb34cf00.png)

**Comment by QuanluZhang** [comment]
@yangou1988 can we close this issue now?

**Comment by yangou1988** [comment]
@QuanluZhang Yes, this issue has been fixed.
