### ISSUE TITLE
Customize the interval display of the default metric map

### ISSUE THREAD

**Issue by rabbit008** [microsoft/nni#1280]
**What would you like to be added**:The user can customize the range of the horizontal ordinate interval in the default metric graph just like the trail duration graph .
![image](https://user-images.githubusercontent.com/28092647/60884180-df73d480-a27e-11e9-89bc-299c6230f4f6.png)

**Why is this needed**:When the trials result are concentrated ,it's not conductive to observation.

**Without this feature, how does current nni work**：normally

**Components that may involve changes**:The Default metric map

**Brief description of your proposal if any**:As above

**Comment by yangou1988** [comment]
![image](https://user-images.githubusercontent.com/44491713/61437062-c9e16780-a96e-11e9-9d30-604f81b379c6.png)

**Comment by rabbit008** [comment]
#1360
