### ISSUE TITLE
Add column with the relative value

### ISSUE THREAD

**Issue by rabbit008** [microsoft/nni#1281]
**What would you like to be added**:Add column with the relative value .

**Why is this needed**:Some users need this value  

**Without this feature, how does current nni work**：normally

**Components that may involve changes**:Add column

**Brief description of your proposal if any**:Add column with the relative value,user can choose whether to display it.

**Comment by scarlett2018** [comment]
@rabbit008 please add an example.

**Comment by ultmaster** [comment]
What does "relative value" mean?
