### ISSUE TITLE
Add a button similar to help, link directive related documents

### ISSUE THREAD

**Issue by rabbit008** [microsoft/nni#1282]
**What would you like to be added**:Add a button similar to help, link directive related documents

**Why is this needed**:Some users may not be familiar with nnictl-command,so it would be more friendly if there have a quick view link.

**Without this feature, how does current nni work**: normally

**Components that may involve changes**: A help button

**Brief description of your proposal if any**:as above

**Comment by rabbit008** [comment]
A icon link to https://nni.readthedocs.io/en/latest/Tutorial/WebUI.html

**Comment by lvybriage** [comment]
this issue needs design to estimate.
