### ISSUE TITLE
Mark the maximum and minimum values in the map of the default metric

### ISSUE THREAD

**Issue by rabbit008** [microsoft/nni#1283]
**What would you like to be added**:
Mark the maximum and minimum values in the map of the default metric , maybe mark different color.

**Why is this needed**:be more friendly to users

**Without this feature, how does current nni work**：The user may look for the maximum and minimum values on the graph based on the experimental id.

**Components that may involve changes**: Default metric map

**Brief description of your proposal if any**:as above

**Comment by scarlett2018** [comment]
Let's consider this together with the Max value line request.
