### ISSUE TITLE
Stop experiment failed

### ISSUE THREAD

**Issue by benchuang11046** [microsoft/nni#1292]
**Short summary about the issue/question**:

Cannot stop a experiment by nnictl.

**Brief what process you are following**: 

```
$ nnictl stop dXjB58pq
```
The following is the error log.
```
Traceback (most recent call last):
[0m  File "/usr/local/bin/nnictl", line 10, in <module>
[0m    [0msys.exit(parse_args())[0m
[0m  File "/usr/local/lib/python3.6/site-packages/nni_cmd/nnictl.py", line 215, in parse_args
[0m    [0margs.func(args)[0m
[0m  File "/usr/local/lib/python3.6/site-packages/nni_cmd/nnictl_utils.py", line 219, in stop_experiment
[0m    [0mexperiment_id_list = parse_ids(args)[0m
[0m  File "/usr/local/lib/python3.6/site-packages/nni_cmd/nnictl_utils.py", line 154, in parse_ids
[0m    [0melif args.all:[0m
[0mAttributeError[0m: [0m'Namespace' object has no attribute 'all'[0m
```

It happened on macOS and docker python:3.6.8.
But it work good on nni 0.8.1.

**How to reproduce it**: 

1. Create a experiment using nnictl, the example is mnist
https://github.com/microsoft/nni/tree/master/examples/trials/mnist
2. Stop the experiment using nnictl and error happened.

**nni Environment**:
- nni version: **0.9.1**
- nni mode(local|pai|remote): **local** and **pai**
- OS: **macos** and **ubuntu**
- python version: **3.6.6** and **3.6.8**
- is conda or virtualenv used?: **conda**
- is running in docker?: **local** and **docker**

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by SunYanCN** [comment]
I have the same error
- centos 
- nni version: 0.9.1

**Comment by rabbit008** [comment]
Hey @SunYanCN, could you provide some context as follows:
nni mode(local|pai|remote): 
python version:
dispatcher.log and nni_manager.log
task description
config,yml and search_space.json
Thank you~

**Comment by Crysple** [comment]
Hi, thanks for reporting this. It is a known issue after v0.9 and we've submitted a PR #1290  to fix it.
Currently you could try `nnictl stop` to stop one experiment... Or you could modify your source code just as the PR did and re-install.

**Comment by QuanluZhang** [comment]
add IT for `nnictl stop`

**Comment by SunYanCN** [comment]
Thank you for your efforts! I hope this tool is getting better and better! @Crysple
