### ISSUE TITLE
Add a new interface in trial SDK

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#1302]
**What would you like to be added**: Some tuning algorithms want to suspend a (or several) running trials, and try new trial configurations. With the tuning procedure going on, some suspended trials may be resumed again. Some examples are [Gandiva: Introspective Cluster Scheduling for Deep Learning](https://www.usenix.org/conference/osdi18/presentation/xiao), [Freeze-Thaw Bayesian Optimization](https://arxiv.org/abs/1406.3896), [Hyperband](https://arxiv.org/abs/1603.06560).

A possible way to satisfy this requirement is adding a new API in trial SDK, for example, `nni.wait_signal`, which keeps blocking until a signal (from tuner or training service) is received.

**Without this feature, how does current nni work**：Users need to write checkpoint save and load in their trial code.

**Components that may involve changes**: trial SDK

**Comment by ultmaster** [comment]
I think we've discussed and our current challenge is to find a shared storage for users to write checkpoints?

**Comment by QuanluZhang** [comment]
closed, as not plan to support in short term
