### ISSUE TITLE
Problem while installing NNI on windows

### ISSUE THREAD

**Issue by anandh02** [microsoft/nni#1310]
I'm facing some problem while installing NNI. I don't have much knowledge on shell script.
Windows 10 environment 
 
**nni Environment**:
- nni version: v0.9
- nni mode(local|pai|remote): local
- OS: windows 10
- python version: 3.6.7

script : powershell -ExecutionPolicy Bypass -file install.ps1
Error : 
----------------------------------------------------------------------------------------------------------
Rename-Item : Cannot bind argument to parameter 'Path' because it is null.
At G:\NNI\nni\install.ps1:100 char:21
+         Rename-Item $unzipYarnDir "nni-yarn"
+                     ~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Rename-Item], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RenameItemC
   ommand

Copy-Item : Cannot find path 'G:\NNI\nni\src\webui\build' because it does not exist.
At G:\NNI\nni\install.ps1:133 char:1
+ Copy-Item "src\webui\build" $NNI_PKG_FOLDER_STATIC -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (G:\NNI\nni\src\webui\build:String) [Copy-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

----------------------------------------------------------------------------------------------------------

Any lead will be appreciated 
Thanks.

**Comment by xuehui1991** [comment]
Thank you for your question  @anandh02.
@SparkSnail will follow this question.

**Comment by SparkSnail** [comment]
Hi, have you tried using `python -m pip install --upgrade nni` to install nni? could you please show the result of command `$PSVersionTable`?

**Comment by anandh02** [comment]
This worked for me python -m pip install --upgrade nni but installing from source code didn't work for me. 
Anyways thanks. You can close the issue.

**Comment by SparkSnail** [comment]
I'll close this issue, if you have any problem , you could reopen it again, thanks.
