### ISSUE TITLE
Issue while setting up NNI python library

### ISSUE THREAD

**Issue by anandh02** [microsoft/nni#1311]
I'm facing some problem while installing NNI. 
nni Environment:

nni version: v0.9
nni mode(local|pai|remote): local
OS: windows 10
python version: 3.6.7

commands : 
python -m pip install --upgrade nni
git clone -b v0.9 https://github.com/Microsoft/nni.git
nnictl create --config nni\examples\trials\mnist\config_windows.yml

INFO: expand searchSpacePath: search_space.json to G:\NNI\nni\examples\trials\mnist\search_space.json
INFO: expand codeDir: . to G:\NNI\nni\examples\trials\mnist\.
INFO: Starting restful server...
ERROR: Fail to find nni under python library

PS : There was no error while installing NNI from pip

Why is it throwing an error even after installing the python library?

Any leads will be appreciated
Thanks

**Comment by xuehui1991** [comment]
I follow the commands that you list and I cannot reproduce your result. Can you offer more info?

**Comment by anandh02** [comment]
Where can I find the installation logs ? 
And it's in local environment not in any virtual env

**Comment by anandh02** [comment]
NNI package is installed in my system
but in NNI launcher.py I see this error when python dir is not found

it would be of great help if someone can tell me how can I get rid of this issue 

In line 92 :
   if python_dir:
        entry_file = os.path.join(python_dir, 'nni', 'main.js')
        if os.path.isfile(entry_file):
            return os.path.join(python_dir, 'nni')
    print_error('Fail to find nni under python library')

the package is installed  (pic attached for reference)

![image](https://user-images.githubusercontent.com/12907396/61350122-b4abf200-a823-11e9-801f-39fb9fab862d.png)

**Comment by demianzhang** [comment]
Hi @anandh02, it seems like nni installation is failed. Please uninstall nni and reinstall it.

**Comment by anandh02** [comment]
@de

> Hi @anandh02, it seems like nni installation is failed. Please uninstall nni and reinstall it.

That's the first thing I tried

**Comment by demianzhang** [comment]
Did you meet some errors when you install, could you provide the output information of  installation.

**Comment by anandh02** [comment]
uninstalling and installing didn't work but uninstalling followed by a restart and then installing again worked.
Thanks for the help, you can close the issue.
