### ISSUE TITLE
cannot set population_size for builtin tuner Evolution

### ISSUE THREAD

**Issue by xingwangsfu** [microsoft/nni#1317]
In the source code of evolution tuner, the default value of population_size is 32. But in the config_schema.py, setting population_size to arbitrary value is not allowed since in 
tuner_schema_dict = {
    ('TPE', 'Anneal', 'SMAC', 'Evolution'): {
        'builtinTunerName': setChoice('builtinTunerName', 'TPE', 'Anneal', 'SMAC', 'Evolution'),
        Optional('classArgs'): {
            'optimize_mode': setChoice('optimize_mode', 'maximize', 'minimize'),
        },
only 'optimize_mode' is supported in classArgs.

**Comment by xuehui1991** [comment]
@xingwangsfu Thank you for your suggestion. We will update this feature recently.
