### ISSUE TITLE
'quniform' has different meaning beween GridSearch  and other tuner.

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1335]
**Short summary about the issue/question**:

The 'qunform' has different meaning between GridSearch and Other tuner.

Such as these json file:
![image](https://user-images.githubusercontent.com/6280746/61509923-5b121600-aa23-11e9-911b-762668175694.png)

in GridSearch, the '10' means count, but in other tuner, the '10' means step. 

There are some code for parsing 'quniform' in GridSearch.

![image](https://user-images.githubusercontent.com/6280746/61509909-4e8dbd80-aa23-11e9-9b60-e75fe7be40ba.png)

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version: N/A
- nni mode(local|pai|remote): N/A
- OS:N/A
- python version: N/A
- is conda or virtualenv used?: N/A 
- is running in docker?: N/A

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by ultmaster** [comment]
Just spent an hour figuring out why my learning rate are all zero, after I switched my tuner from GridSearch to TPE... Even didn't realize this when I read the docs of hyperopt...
