### ISSUE TITLE
Add Settings to WebUI

### ISSUE THREAD

**Issue by yangou1988** [microsoft/nni#1337]
**Short summary about the issue/question**:Add Settings to WebUI include Auto refresh setting (moved from NAV), Location of download file ... 

**Brief what process you are following**: Completed draft UI design 

![image](https://user-images.githubusercontent.com/44491713/61518997-6d00b280-aa3d-11e9-86b1-7e8179fafdea.png)

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**: 

**Anything else we need to know**: Need more ideas and suggestion what should be added in the Settings

**Comment by QuanluZhang** [comment]
@yangou1988 have we supported it?

**Comment by yangou1988** [comment]
No, we are not going to support it since the content of the setting is not ready.
