### ISSUE TITLE
Throws bash error when sending command line arguments

### ISSUE THREAD

**Issue by pratimanagare** [microsoft/nni#1343]
**Short summary about the issue/question**: I want to pass command line arguments to my algorithm. So when I add them, it throws bash error 

> syntax error near unexpected token `('

**Brief what process you are following**:  The command key in the config.yml has value as python algo.py -c '{"path": "xyz"}'

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote): 
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?: yes

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by suiguoxin** [comment]
command: python algo.py -c '{"path": "xyz"}' doesn't conform to yaml file format, could you pls precise what command you are using ?

**Comment by pratimanagare** [comment]
That tells me NNI does not support command line arguments. Thanks.
