### ISSUE TITLE
Is it possible to start new searching experiments using same experiment ID or port as last one?

### ISSUE THREAD

**Issue by Guptajakala** [microsoft/nni#1355]
Hello,
I'm wondering if it's possible to start new searching experiments but use same experiment ID or port as last one, because I want to make all the experiments results in the same nni board for more convenient comparison.

A more concrete example is that the first experiment I specify
` "conv_size":{"_type":"choice","_value":[2,3,4]},`
But experiments turns out that I may want to try another range 
` "conv_size":{"_type":"choice","_value":[4,5,6]},`
To start this second one, if I use 
`nnictl create ...`
Then I'm forced to change the port which will make this experiment showing in a separate nni board. Is there a way to make them showing together in one nni board?

**Comment by xuehui1991** [comment]
Hello @Guptajakala. Seems nni do not support running multiple experiments in one port at the same time. 

But I think we could discuss your case with nni teams and try to find a solution. Thank you.

**Comment by ultmaster** [comment]
In this case, will the first experiment be stopped or not? Do you mean to combine/update search space so that they can be seen as a single experiment?

**Comment by Guptajakala** [comment]
@ultmaster The first experiment either is stopped or not is fine. I'm mostly curious about the second part: to combine/update search space so that they can be seen as a single experiment.

**Comment by ultmaster** [comment]
Looks like what you need is to update the search space of a running experiment. This can be done with `nnictl update`:

![image](https://user-images.githubusercontent.com/8463288/67155097-fe343d80-f33a-11e9-83ea-d1a3ee0ae1ad.png)

**Comment by Guptajakala** [comment]
@ultmaster This looks exactly what I want. Thanks!
