### ISSUE TITLE
WebUI上显示的metric可以动态调整下画图的区间吗？

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1360]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/6280746/61762850-e9144500-ae05-11e9-8142-66c18e8c57c5.png)

如上图，目前得到的trial的metric都在0.7 - 0.8 之间， 很遗憾的是， WebUI不会对齐动态调整，以至于我在图上根本看出来差别。

但是这个top10的图里， 我可以非常清楚的看到差别：
![image](https://user-images.githubusercontent.com/6280746/61762902-152fc600-ae06-11e9-9f75-636da7090452.png)

谢谢！
**Why is this needed**:

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by lvybriage** [comment]
@xuehui1991 好的，这个不难实现，会release在1.0版本上。

**Comment by rabbit008** [comment]
#1280 https://github.com/microsoft/nni/issues/1280
