### ISSUE TITLE
Can not run parallel trials on different GPUs

### ISSUE THREAD

**Issue by stas-semeniuta** [microsoft/nni#1366]
**Short summary about the issue/question**:
I want run multiple trials in parallel, each on its own GPU. Can't configure NNI to do so so far.

**How to reproduce it**: 

Config I use:

authorName: default
experimentName: mnist
trialConcurrency: 4

maxExecDuration: 1h
maxTrialNum: 8
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: Random
trial:
  command: python3 main.py --config mnist_mlp --mode tune
  codeDir: ../..
  gpuNum: 4
localConfig:
  maxTrialNumPerGpu: 1
  gpuIndices: 0,1,3,4
  useActiveGpu: true

I am successfully able to run multiple trials when running on CPUs. When running on GPUs, I observe that the first trial occupies all GPUs, since  CUDA_VISIBLE_DEVICES are set to 0,1,3,4 for all trials, and other trials wait for it's completion. setting useActiveGpu to true does not help. I have tried programmatically changing CUDA_VISIBLE_DEVICES to restrict the script to one GPU and while it did work, other trials still wait for its completion. Is there a way to set different values of CUDA_VISIBLE_DEVICES for each trial?
I have seen mentions of trialGpuNum parameter in the doc, but I am not able to use this parameter now.

**nni Environment**:
- nni version: 0.9.1.1.
- nni mode(local|pai|remote): local
- OS: Ubuntu 16.04.6 LTS
- python version: 3.6
- is conda or virtualenv used?: conda
- is running in docker?: no

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by QuanluZhang** [comment]
@stas-semeniuta  in your case, `gpuNum` should be one, each trial uses one GPU. You configured `trialConcurrency` to be 4, this is correct. There are 4 concurrent trial jobs and each one uses 1 GPU.

**Comment by stas-semeniuta** [comment]
@QuanluZhang that did it. Thank you very much and thank you for the great tool!
