### ISSUE TITLE
Can we get a trial_id in trial code?

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1368]
**What would you like to be added**:
If we want to dump some models in trial code, we would like to know the trial_id in a different trial.

Does nni have any API could get trial_id in trial code?

**Why is this needed**:

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by suiguoxin** [comment]
added in this pr https://github.com/microsoft/nni/pull/1353
