### ISSUE TITLE
design for re-submit

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/nni#1383]
Problem: 
- new trial job id can't be returned
- not friendly in webUI
Principle & Guideline: 
- support in REST, not only in WebUI
- Tuner designers wasn't informed to deal with multiple results of a single parameter_id
Approaches:
- new API: get_trials_by_parameter_id
**- Label :{source:, ...}**
- Source 
Risk:
- current tuners don't support re-submit
Questions:
- Succeed  trials can be resubmitted ? Disable in webUI, no constraints in back
-  Failed jobs can be resubmitted multiple times ?

**Comment by rabbit008** [comment]
#883

**Comment by scarlett2018** [comment]
old discussion, will track the feature in other new issues.
