### ISSUE TITLE
The second choice type can not select data from yAxis when search space have 2 choice type

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#1398]
This problem is blocked by [Echarts](https://github.com/apache/incubator-echarts/issues/8473)
I'll continue to focus this.
The first choice type can be selected from yAxis, like this
![image](https://user-images.githubusercontent.com/35484733/62271446-3da16b00-b46b-11e9-80e0-be5bc9550e1b.png)

And the second choice type...
![image](https://user-images.githubusercontent.com/35484733/62271258-c10e8c80-b46a-11e9-9681-7610b7fccc45.png)

**Comment by ultmaster** [comment]
Seems to me that echarts is blocking a number of features and bugs. Can we consider switching to other libraries?

**Comment by Lijiaoa** [comment]
@lvybriage 
@ultmaster had used `d3.js` libriary to refactor hyper-parameter chart. It is released in `v1.8`.

**Comment by kvartet** [comment]
@Lijiaoa Can you update the status of this issue?

**Comment by Lijiaoa** [comment]
Hi, @kvartet  This issue had been fixed in `v1.8` by @ultmaster ! So could you help close this issue? Thanks.
