### ISSUE TITLE
Release NNI source to pypi? 

### ISSUE THREAD

**Issue by MingzhouZhou** [microsoft/nni#1406]
Hi NNI team,

We would like to try out NNI to tune our experimental model internally, but our external library request policy doesn't allow to pull wheels, do you mind release source to pypi? Thanks!

**Comment by liuzhe-lz** [comment]
Hello
You can install from source code for now. See `install through source code` part in README for details.
We need some time to discuss whether and how to support pip no-binary install. Because NNI is not a pure Python library and it can be tricky to build node modules.

**Comment by MingzhouZhou** [comment]
Hi @liuzhe-lz , thanks a lot for your reply! I'll close the issue for now.
