### ISSUE TITLE
Provide command to show experiment only.

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/nni#1414]
Currently, if user wants to look an experiment result, it have to use `nnictl resume`. It does some validation, and easy to fail. There should be a command like `nnictl view experiment` to start webui for view only.

**Comment by scarlett2018** [comment]
@rabbit008 - please investigate and make a proposal for team discussion.

**Comment by mys007** [comment]
This would be a great feature to have! The major problem with `nnictl resume` for viewing previous experiments via WebUI is that it starts new trials as well if the experiment has been terminated prematurely.

**Comment by scarlett2018** [comment]
Thanks @mys007  for the feedback, we are also collecting feedback for experiment comparision, would you like to share your view as well? https://github.com/microsoft/nni/issues/1529.

**Comment by SparkSnail** [comment]
@squirrelsc If users use `nnictl view experiment`, should we let users change experiment parameters using webUI or nnictl command?

**Comment by squirrelsc** [comment]
> @squirrelsc If users use `nnictl view experiment`, should we let users change experiment parameters using webUI or nnictl command?

It depends. In general, when viewing an experiment, the experience data should be readonly. It means nothing is saved back to storage. But if there is any parameter impacting how an experiment showing, it could be able to changed. If there are some examples, feel free to let me know.

**Comment by liuzhe-lz** [comment]
#1524
