### ISSUE TITLE
How to debug NNI runtime?

### ISSUE THREAD

**Issue by anandhperumal** [microsoft/nni#1421]
How to debug the source code during run-time while running it through NNI? I don't see any documentation on it.
Any lead will be appreciated.
Thanks

**Comment by QuanluZhang** [comment]
NNI's source code, or your trial's source code?

**Comment by ultmaster** [comment]
He/She means NNI's source code. #1367

**Comment by anandh02** [comment]
@QuanluZhang  yes NNI source code

**Comment by QuanluZhang** [comment]
@anandh02 NNI does not have dedicated tool for debugging the ts code. You could write log in the source code, the log will be written in nnimanager.log (or dispatcher.log if you are debugging tuning algorithms). You may find [this doc](https://nni.readthedocs.io/en/latest/Tutorial/HowToDebug.html) helpful.

We may provide debugging tool in future.

**Comment by dliang0406** [comment]
@QuanluZhang 
How to debug my own source code then?
I tried to add "--debug" when I use "nnictl create" to create a new session and wanted to see some data during the process, but "nnictl log stdout" only shows the start time like this:
-----------------------------------------------------------------------
                Experiment start time 2019-08-15 14:32:19
-----------------------------------------------------------------------
What I really want to see is the result:
logger = logging.getLogger('mnist_nested_search_space')

if __name__ == '__main__':
    try:
        # get parameters form tuner
        data = nni.get_next_parameter()
        logger.debug(data)

Specifying the log level to DEBUG in my code like this "logger.setLevel(logging.DEBUG)" shows nothing as well.

**Comment by scarlett2018** [comment]
Closing the issue as the question has been answered.
