### ISSUE TITLE
Improve WebUI loading performance (esp. for large data size experiment)

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/nni#1425]
有个experiment，数据量比较大，返回也慢。有时候会发生第一次刷新还没有返回的时候，第二次刷新就开始了，这样会堆积很多次刷新请求，越刷服务器越慢。我觉得前端查询数据的时候，是不是可以等上次都返回完了，再间隔指定时间后，获取下次数据？

**Comment by lvybriage** [comment]
3d

**Comment by ultmaster** [comment]
Tracking in a new issue #1490. Closing it.
