### ISSUE TITLE
Minor issues of WebUI

### ISSUE THREAD

**Issue by liuzhe-lz** [microsoft/nni#1446]
These are low priority issues and are not expected to fix by v1.0 due.

- [X]  1. The width of some containers are incorrect on certain resolution/dpi/scale. I can't reproduce it on other devices. May be an antd bug.
 2. Cannot search hyper-parameters by field (e.g. "conv_size: 5"). I don't know if "real" users will do this.
- [X] 3. Mouse wheel is not functional in experiment error log window.
 4. Refreshing/reopening the page clears most states.

![Screenshot_20190809_105001](https://user-images.githubusercontent.com/40699903/62751538-ace41400-ba96-11e9-9534-e179ba0f0cab.png)

**Comment by QuanluZhang** [comment]
@lvybriage could you update the status related to this issue?
