### ISSUE TITLE
Could control the expansion of all trials' open row

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#1465]
**What would you like to be added**:
Add a button to control table's open row, could close all or open all.

**Why is this needed**:

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by ultmaster** [comment]
It seems to be that this feature is actually intended to show parameters as table columns.

**Comment by Lijiaoa** [comment]
`Show parameters as table columns` function had been implemented. You could use latest version to try it!
