### ISSUE TITLE
The trail failed at last step and don't know how to debug

### ISSUE THREAD

**Issue by dliang0406** [microsoft/nni#1473]
When I try to tune my own parameters with nni.report_final_result() to report the trail result, the webUI would report **FAIL**.

The value passed to nni.report_final_result() can be printed and recorded in trial.log right before this call.

And the value is also found in .nni/metrics like this:
ME000096{"parameter_id": 0, "trial_job_id": "KF9Qg", "type": "FINAL", "sequence": 0, "value": 0.833333}

But the weird thing is this log in stderr file:
**tee: 'standard output': Connection reset by peer**

No other useful information any more.

I configured my config.yml to set the platform as local and maxTrialNum as 1.

**nni Environment**:
- nni version:0.9.1.1
- nni mode: Local
- OS: Ubuntu 18.04
- python version: python 3.6
- is conda or virtualenv used?: No 
- is running in docker?: No

The examples for MNIST can be executed well.

**Comment by dliang0406** [comment]
Narrow down the possible root cause, my python script invokes a bash command with os.system(cmd) and it took over 1 minute to complete.

The function getTrialJob() in .local/nni/training_service/local/localTrainingService.js thinks the trial job is not alive and sends a signal to stderr thus "tee: 'standard output': Connection reset by peer" is seen.

When the bash command returns and python process becomes alive and writes the nni results in .nni.
But still NNI thinks this trial has failed.

**Comment by rabbit008** [comment]
Solved in NNI v1.0
