### ISSUE TITLE
"The number q in quniform and qloguniform has special meaning in GridSearchTuner" will make user confused.

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1485]
**What would you like to be added**:

**Why is this needed**:
As title.

**Without this feature, how does current nni work**：
https://github.com/microsoft/nni/blob/master/docs/en_US/Tuner/GridsearchTuner.md

**Components that may involve changes**:
GridSearchTuner
 
**Brief description of your proposal if any**:

**Comment by rabbit008** [comment]
#1486
