### ISSUE TITLE
Proposal to enhance logPath in PAI mode

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#1488]
Currently logPath in PAI mode is not useful; users still have to go to the PAI portal to check stdout and stderr. According to Quanlu, this is attributed to the missing information returned by OpenPAI API. So I propose a workaround to get the webpage directly from the portal and parse the webpage to get the link.

The code is almost ready. All I need to do is to inject it into NNI manager. So should we do it or not?

**Comment by scarlett2018** [comment]
Close as won't fix after team discussion, will create a new issue for generic capability to create logPath for all the training services.
