### ISSUE TITLE
Enhancement to trial duration display

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#1489]
Can we enhance the time duration display? It's really hard to "guess" how many hours or how many days from a number with 9 digits.

![image](https://user-images.githubusercontent.com/8463288/63635717-6eef0e80-c698-11e9-9e56-08b93a015476.png)

**Comment by rabbit008** [comment]
Plan: change to :  h min s ; like 1h20min30s

**Comment by QuanluZhang** [comment]
@ultmaster can we close this issue now?

**Comment by ultmaster** [comment]
No. It hasn't been done yet. I don't know why people forget it.
