### ISSUE TITLE
Improve web UI performance for large experiment

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#1490]
## REST Server Side ##
* Add API: get latest metric of each trial
* Add API: get metrics from a list of trials

## Web UI Side ##
* Maintain a collection of all received metric
* On loading, request trial metrics by group (maybe 100 trials each time?)
* For unfinished (`WAITING`, `RUNNING`, ...) trials, periodically request metrics and update the collection
* For finished (`SUCCEEDED`, `FAILED`, `EARLY_STOPPED`, ...) trials, only request metrics once

## Open Questions ##
* How to show learning curves when there are too many trials
* How to improve the performance of NNI manager

**Comment by lvybriage** [comment]
webui estimate: 4d

**Comment by rabbit008** [comment]
related #907

**Comment by lvybriage** [comment]
related PR: #1557
