### ISSUE TITLE
 mnist-annotation with config_remote.yml  run fail!

### ISSUE THREAD

**Issue by lizhaodong** [microsoft/nni#1495]
**Short summary about the issue/question**:
Error: TrainingService setClusterMetadata timeout. Please check your config file.

**Brief what process you are following**: 
open 8080 and 8081 port.
This command was successfully executed in window's cmd window : ssh -l lzd 192.168.64.233  -p 8080

**How to reproduce it**: Run your demo directly.

**nni Environment**:
- nni version:0.9.1.1
- nni mode(local|pai|remote):remote
- OS: win10
- python version:3.6.8
- is conda or virtualenv used?: conda
- is running in docker?:no

**need to update document(yes/no)**:no

**Anything else we need to know**:

My configuration file is as follows:
config_remote.yml:
authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: remote
#choice: true, false
useAnnotation: true
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0
#machineList can be empty if the platform is local
machineList:
  - ip: 192.168.64.233
    username: lzd
    passwd: abcd.123
    #port can be skip if using default ssh port 22
    port: 8080

**Comment by scarlett2018** [comment]
@SparkSnail - are you able to reproduce this with 0.9.1? if not, any info is needed for debugging? thanks.

**Comment by lizhaodong** [comment]
Thanks for the nni team's reply！

As shown, the version of this nni is 0.9.1。

The results of running the demo are as follows:

As shown, this is my log, using port 8080. But using the default port 22, the error is the same.

ssh -l lzd 192.168.64.233  -p 8080  or  ssh -l lzd 192.168.64.233  ----  The execution of these commands was successful.











At 2019-08-27 16:20:35, "Scarlett Li" <notifications@github.com> wrote:


@SparkSnail - are you able to reproduce this with 0.9.1? if not, any info is needed for debugging? thanks.

**Comment by lizhaodong** [comment]
my config_remote.yml, beyond that, nothing has been changed.






At 2019-08-27 16:20:35, "Scarlett Li" <notifications@github.com> wrote:


@SparkSnail - are you able to reproduce this with 0.9.1? if not, any info is needed for debugging? thanks.

**Comment by SparkSnail** [comment]
Hi @lizhaodong ,  
      I can not reproduce this problem in my windows 10 machine. This kind of problem may be caused by the ssh connection error when NNI tried to connect to remote machine using ssh client, could you please check the username and password is correct in your config file? And have you ever tried using [sshKeyPath](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#configuration-spec) to start an experiment?
   Please show the log content in `C:\Users\{username}\nni\experiments\{id}\log` here. You could get the latest experiment folder according the folder create time.

**Comment by scarlett2018** [comment]
> Hi @lizhaodong ,
> I can not reproduce this problem in my windows 10 machine. This kind of problem may be caused by the ssh connection error when NNI tried to connect to remote machine using ssh client, could you please check the username and password is correct in your config file? And have you ever tried using [sshKeyPath](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#configuration-spec) to start an experiment?
> Please show the log content in `C:\Users\{username}\nni\experiments\{id}\log` here. You could get the latest experiment folder according the folder create time.

@lizhaodong had you got a chance try what @SparkSnail suggested? or the problem is fixed on your side for other reasons? would you mind to update the latest status here? thanks.

**Comment by lizhaodong** [comment]
@scarlett2018   Thank you ! The problem had solved! This issue had closed!
