### ISSUE TITLE
Can we save experiment parameters in the experiment log folder

### ISSUE THREAD

**Issue by gxiaotian** [microsoft/nni#1506]
**Short summary about the issue/question**:
Save experiment parameters in the exmperiment log folder.

**Brief what process you are following**: 
Json file of experiment parameters can be downloaded with WebUI, but cannot be found in the corresponding log folder. There are only dispatcher.log and nnimanager.log.

**How to reproduce it**: 

**nni Environment**:
- nni version: v0.8-319-g19173aa4
- nni mode(local|pai|remote): local
- OS: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)
- python version: Python 3.7.3
- is conda or virtualenv used?:  Conda
- is running in docker?: no

**need to update document(yes/no)**: no

**Anything else we need to know**:

**Comment by martsalz** [comment]
Inside the code, where is `experiment.json` created for the web interface?

**Comment by martsalz** [comment]
https://github.com/microsoft/nni/blob/master/src/webui/src/static/function.ts (line 150)

**Comment by ultmaster** [comment]
I don't think I'd totally understand. By experiment parameters, do you mean search space? or the parameters in a single trial?

**Comment by gxiaotian** [comment]
![image](https://user-images.githubusercontent.com/17501307/67154568-25860d00-f331-11e9-9f03-323fedbfa21f.png)

**Comment by ultmaster** [comment]
If this downloadable, there should be a corresponding Restful API. You can investigate into it after you press F12 to see the console. And if it's not listed in our documentation, this might be a docs issue.

**Comment by gxiaotian** [comment]
Each experiment has its own log folder located at `~/nni/experiment/XXXX/log`.  For now, there are only `dispatcher.log` and `nnimanager.log`. What I am saying is that can we save the downloadable `experiment.json` in this folder as well, so that we could easily fetch all experiment details even webui is closed.

**Comment by ultmaster** [comment]
If you are trying to get experiment parameters without WebUI, you can try `nnictl`. Refer to the docs for more details.

**Comment by gxiaotian** [comment]
I don't think I can get all historical experiment parameters via `nnictl`.

**Comment by ultmaster** [comment]
In the next release, 1.1, you will be able to use `nnictl experiment view` to launch a WebUI to view a historical experiment. Maybe we should make this tool more powerful.

**Comment by gxiaotian** [comment]
Sounds cool~ Looking forward to the next release.

**Comment by scarlett2018** [comment]
> Sounds cool~ Looking forward to the next release.

Please check 1.1, and let us know your feedback =).
