### ISSUE TITLE
Save experiment parameters in the exmperiment log folder

### ISSUE THREAD

**Issue by gxiaotian** [microsoft/nni#1507]
**Short summary about the issue/question**:
Save experiment parameters in the exmperiment log folder.

**Brief what process you are following**: 
The json file of experiment parameters can be downloaded with WebUI, but cannot be found in the corresponding log folder, where only dispatcher.log and nnimanager.log exist.  Could we save the file of experiment parameters there as well?

**How to reproduce it**: 

**nni Environment**:
- nni version: v0.8-319-g19173aa4
- nni mode(local|pai|remote): local
- OS: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)
- python version: Python 3.7.3
- is conda or virtualenv used?:  Conda
- is running in docker?: no

**need to update document(yes/no)**: no

**Anything else we need to know**:

**Comment by martsalz** [comment]
Good suggestion. Why is the issue closed?

**Comment by gxiaotian** [comment]
I submitted it twice due to browser crash #1506
