### ISSUE TITLE
Validate the search space to avoid invalided usages

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#1511]
Issue found during investigating: https://github.com/microsoft/nni/issues/1496

@leelaylay checked @LongzeSong's config and find there is one mistake. According to [SearchSpaceSpec.md](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/SearchSpaceSpec.md), the range in `uniform` should be `[low, high]` instead of  `[high, low]`.
**search_space.json**
```diff
{
-  "learning_rate": {"_type":"uniform","_value":[1e-3,1e-5]}
+  "learning_rate": {"_type":"uniform","_value":[1e-5,1e-3]}
}
```

Hope this might help you.

_Originally posted by @leelaylay in https://github.com/microsoft/nni/issues/1496#issuecomment-525580918_

**Comment by scarlett2018** [comment]
Assign to @liuzhe-lz for engineering estimation and suggestions.

**Comment by kvartet** [comment]
@kvartet - need to test whether this issue exists in the latest version.
