### ISSUE TITLE
Allow NNI not to fork to background

### ISSUE THREAD

**Issue by Markus92** [microsoft/nni#1515]
**What would you like to be added**:
Currently, NNI forks to the background as soon as the webui is up. I'd like an option to disable this behavior, in order for NNI to work better with my job scheduler (SLURM).

**Why is this needed**:
We run our AutoML jobs at a small cluster using SLURM for GPU and other resource scheduling. When the foreground command exits, it will think the task is done training and release resources for other people. So in practice, we cannot use NNI to queue hyperparameter search and execute it when resources are available, as it does not run.

**Without this feature, how does current nni work**：
See above

**Components that may involve changes**:
nnictl

**Brief description of your proposal if any**:
Add a commandline option or config option, so the main process will not exit after launching the webui.

**Comment by liuzhe-lz** [comment]
I suggest writing a wrapper script in your case.
You should not rely on existence of NNI process to tell whether job is running. NNI will never exit until you manually run `nnictl stop`, because it has to keep a process to serve the web UI. So if we bring the process to foreground, your scheduler will find the job running forever.

Following script can help you do the trick:
```python
import subprocess, time
subprocess.run(['nnictl', 'create', '--config', 'YOUR_CONFIG.yml'], check=True)
while True:
    time.sleep(60)
    p = subprocess.run(['nnictl', 'experiment', 'status'], capture_output=True)
    if b'RUNNING' not in p.stdout:
        print(p.stdout)
        break
```

**Comment by Markus92** [comment]
Thank you for the script! Indeed it's not an ideal situation but this workaround should do.

**Comment by nikhil-garg** [comment]
@liuzhe-lz is this a SLURM script? I am not able to  follow thorough about when to export the experiment log. 
I wish to run this command after all experiment get's finished. 
`nnictl experiment export --filename nni_log.csv --type csv`
