### ISSUE TITLE
Outdated document of builtin tuner grid search 

### ISSUE THREAD

**Issue by gxiaotian** [microsoft/nni#1519]
The document of builtin tuner [grid search](https://github.com/microsoft/nni/blob/master/docs/en_US/Tuner/GridsearchTuner.md) seems outdated. From my experiment, the number `q` in `quniform` has the same meaning as the spec in [search space spec](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/SearchSpaceSpec.md).

**How to reproduce it**: 

**nni Environment**: 
- nni version: v0.8-319-g19173aa4
- nni mode(local|pai|remote): local
- OS: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)
- python version: Python 3.7.3
- is conda or virtualenv used?: Conda
- is running in docker?: no

**need to update document(yes/no)**: Maybe

**Comment by suiguoxin** [comment]
Sorry for the latency. The latest doc is here: https://github.com/microsoft/nni/blob/v1.0/docs/en_US/Tutorial/SearchSpaceSpec.md . We will merge this back to master very soon

**Comment by gxiaotian** [comment]
Great! Really appreciate it!
