### ISSUE TITLE
[Feedback Needed] Compare different experiment result in WebUI

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1529]
This is a **help wanted** to all the NNI users. If you have any suggestions or scenarios related to the following question, please add a comment in the issue. 

**What would you like to be added**:
Do we need to add a function that compares different experiments result in WebUI? like  "nnictl compare --expeirment_id1 id1 --expeirmnet_id2 id2"?

**Why is this needed**:

**Without this feature, how does current nni work**：

**Comment by scarlett2018** [comment]
@kostasfilip - would you like to share more suggestions given you had raised similar request in #774 ? thanks.

**Comment by rabbit008** [comment]
1.Compare different tuners,searchspace by default metric graph.

**Comment by rabbit008** [comment]
NNI v1.1 will add a new command, 'nnictl view expriment_id' to view the webui of the experiment that has been stopped without resume it. When you specifies a different port number, you can open different experimental webui at the same time for comparison.But this may be a bit of a hassle, if you have specific comparison needs, please add a comment in this issue.

**Comment by ultmaster** [comment]
Our current design is to add a command in nnictl that will compare several experiments in the past and generate, maybe, a simple HTML.
