### ISSUE TITLE
Some improvements on WebUI

### ISSUE THREAD

**Issue by rabbit008** [microsoft/nni#1537]
1.The coordinate name in the current intermediate result graph ("Intermediate") is not the same as the title of the table ("Intermediate Count"), which may make users feel confused.
![image](https://user-images.githubusercontent.com/28092647/64515744-becc0780-d31f-11e9-8b94-1245c3fb06be.png)
2.Currently, we have 7 optional columns available, this 1.1-release will add new columns like starttime and endtime, maybe we need to limit the maximum number of columns added to the table.
![image](https://user-images.githubusercontent.com/28092647/64516099-76f9b000-d320-11e9-8b2e-fb17de3bf8f7.png)

**Comment by scarlett2018** [comment]
use **# Intermediate Result** for both then.

**Comment by rabbit008** [comment]
For the second question:
1. Do not limit the number of columns;
2. For the part that exceeds the display width, add a scroll wheel to the bottom of the table to view all.
