### ISSUE TITLE
Show trial error message

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#1541]
Currently, the storage full message is only able to be got from the trial-jobs RESTful API, would like to expose it to the WEBUI.

![image](https://user-images.githubusercontent.com/35484733/64665344-cfe25900-d484-11e9-8e10-c5333f0defaa.png)

**Comment by scarlett2018** [comment]
@lvybriage @yangou1988 - seems this one is a good one to merge with the warning message. we can show error/warning message in one style somehow. cc @QuanluZhang

**Comment by Lijiaoa** [comment]
This issue had fixed in PR https://github.com/microsoft/nni/pull/2424

WebUI will show /trial-jobs error message if /trial-jobs return error filed. And website will stop refreshing page.

**Comment by scarlett2018** [comment]
in 1.6.
