### ISSUE TITLE
"search space" JSON file has length limitation

### ISSUE THREAD

**Issue by daniel347x** [microsoft/nni#1544]
**Short summary about the issue/question**:

I attempted a search space for the "batch" mode with more than 400 entries, each with about 15 parameters.  When attempting to run the `nnictl create` command using this search space JSON file, the `nnictl` command throws a JSON parse exception.  Simply making the search space file smaller by shortening variable names allows it to run.

**Brief what process you are following**: 

Create a 'search space' file with more than 400 entries for use with batch mode, each entry with about 15 parameters.  Attempt to run the batch job.

**How to reproduce it**: 

See above.

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by rabbit008** [comment]
hi,@daniel347x ,could you paste the content of your search space file here, including the original file and the updated file, I would check the content and have a try,thanks!

**Comment by ultmaster** [comment]
@daniel347x Any updates?

**Comment by chicm-ms** [comment]
Closed since no response,  you can reopen it if you still have this issue.
