### ISSUE TITLE
GPTuner does not support string choices

### ISSUE THREAD

**Issue by mys007** [microsoft/nni#1546]
**Short summary about the issue/question**:

GPTuner raises an exception when search space contains a choice over strings:
```
{
    ....
    "model_config": {"_type": "choice", "_value": ["A", "B"]}
}
```
```
......
  File "/home/xxx/miniconda3/envs/spur/lib/python3.7/site-packages/nni/tuner.py", line 52, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/home/xxx/miniconda3/envs/spur/lib/python3.7/site-packages/nni/gp_tuner/gp_tuner.py", line 101, in generate_parameters
    results = self._space.random_sample()
  File "/home/xxx/miniconda3/envs/spur/lib/python3.7/site-packages/nni/gp_tuner/target_space.py", line 180, in random_sample
    _bound['_value'], self.random_state)
ValueError: could not convert string to float: 'A'
```
This is caused by https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/gp_tuner/target_space.py#L176, which enforces float types. I believe replacing the line with `params = []*self.dim` could solve the issue?

**nni Environment**:
- nni version: 1.0
- nni mode(local|pai|remote): local
- OS: Ubuntu
- python version: 3.7
- is conda or virtualenv used?:  conda
- is running in docker?: no

**Comment by scarlett2018** [comment]
@mys007 - Thanks for raising the problem, this is a known limitation, our current GPTuner reference implementation only support **choice** for integer and float. @suiguoxin  will update the document to let users know about this limitation.

**Comment by rabbit008** [comment]
#1551 add doc for GP-Tuner: support only numerical values
