### ISSUE TITLE
Close file descriptor.

### ISSUE THREAD

**Issue by farziengineer** [microsoft/nni#1552]
https://github.com/microsoft/nni/blob/59ce65c50fe89e1c61b86211683975d2a8cd4e44/src/sdk/pynni/nni/common.py#L55-L60

The ```logger_file``` file descriptor has been opened, but not closed. Shall I raise a PR to replace the above syntax with
```python
with open(file_name, 'w') as f:
    fmt = '[%(asctime)s] %(levelname)s (%(name)s/%(threadName)s) %(message)s' 
    logging.Formatter.converter = time.localtime 
    formatter = logging.Formatter(fmt, _time_format) 
    handler = logging.StreamHandler(logger_file) 
    handler.setFormatter(formatter) 
 ```

**Comment by farziengineer** [comment]
Also, if an exception occurs in between, the file does not get closed. It would be better to replace it with the ```with``` statement.

**Comment by scarlett2018** [comment]
@farziengineer - thanks for raising the issue, and great to hear you'd like to contribute PR.

For contributing to NNI, please follow the following instruction:
https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Contributing.md

**Comment by liuzhe-lz** [comment]
The log file should not be closed. Because the logger may write to it at any time.

**Comment by farziengineer** [comment]
@liuzhe-lz Hi, as far as I know, the file descriptor anyway gets closed when the function completes execution.

**Comment by liuzhe-lz** [comment]
@farziengineer It gets closed when nobody reference to the file object.
Since the reference chain _logging module -> global root logger -> handler -> logger_file_ always exists, the file will never close.

**Comment by farziengineer** [comment]
Ah, got it @liuzhe-le
