### ISSUE TITLE
A full example of the MNIST dataset with Keras, where a customized Advisor is specified in the config.yml.

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#1553]
@QuanluZhang , ideally a full example of the MNIST dataset with Keras, where a customized Advisor is specified in the config.yml.

_Originally posted by @martsalz in https://github.com/microsoft/nni/issues/1470#issuecomment-531661428_

**Comment by ultmaster** [comment]
The example can be found here: https://github.com/microsoft/nni/tree/master/examples/tuners/mnist_keras_customized_advisor
