### ISSUE TITLE
Investigating FAILED trials

### ISSUE THREAD

**Issue by apatsekin** [microsoft/nni#1559]
**Short summary about the issue/question**: When running `remote` experiment on two machines, I experience periodical failed starts on one of them. However, I cannot investigate it further, since its temporal location is  being wiped out (i.e.  `tmp/nni/experiments/OlabyaBd/trials/cGBe3`) before I notice that. 

**Brief what process you are following**: Starting a `remote` experiment, having `concurrency=2`, having 2 machines configured. Assuming that each machines hosts 1 trial at a time. 

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.0
- nni mode(local|pai|remote): remote
- OS: Ubuntu 16.04.6 LTS
- python version: 3.6.8
- is conda or virtualenv used?: no
- is running in docker?: yes

**need to update document(yes/no)**: no

**Anything else we need to know**: The actual starting process seems weird to me, according to running tasks table, target machine already had 1 task running. However for some reason scheduler tried to start another one on the same machine. But the point of the ticket is to have an ability to investigate it. Thanks!

**Comment by QuanluZhang** [comment]
@apatsekin thanks for reporting this issue. It might be better for NNI to provide the location info of each trial.

For your problem, could you provide more information:
1. does your trial use gpu (and how many)?  if it uses gpus, then how many gpus in each of the machine.
2. how did you run the experiment in `remote` mode using docker?
3. could you provide the log (i.e., stderr) of the failed trial?
4. what is the status of your experiment, running or error? if it is error, could you also provide the content of nnimanager.log

**Comment by apatsekin** [comment]
@QuanluZhang thank you for quick and detailed response!

1. I run NNI on one machine in `remote` mode, so it can start training on two other machines. Those two `workers` machines has 8 GPUs each.  Trial (training) script takes all GPUs on single machine, so I can run only one trial per machine.
2. Each `worker` machine has running docker container with exposed SSH port. Those containers run persistently. NNI is configured to run tasks in `remote` mode through SSH.
3. That's the main point of this issue. When I see in WebUI those failed trials and press `+` to pull up the log directory, i.e. `/tmp/nni/experiments/OlabyaBd/trials/ENcH2`, it's already doesn't exist. So I have no clue what happened with the trial and why it failed.
![image](https://user-images.githubusercontent.com/15197972/65262621-9aaabc00-dabf-11e9-9c85-f5b6fce9ba7f.png)
4. The status was `running` after first couple of fails, although trials directories were still wiped for failed ones. Now it's `finished` because it reached max number of attempts.
Here is part of nnimanager.log when trial fails:
`[9/19/2019, 3:41:55 AM] INFO [ 'POST: /version/OlabyaBd/Sl0x3: body:\n{\n    "tag": "VCSuccess"\n}' ]
[9/19/2019, 3:41:55 AM] INFO [ 'Version check in trialKeeper success!' ]
[9/19/2019, 3:41:55 AM] INFO [ 'POST: /stdout/OlabyaBd/Sl0x3: body:\n{\n    "stdOutputType": "Stdout",\n    "tag": "trial_keeper",\n    "msg": "[2019-09-19 03:41:55.907084] INFO Trial keeper spawns a subprocess (pid 37880) to run command: [\'/root/.pyenv/shims/python3\', \'train.py\', \'--config=config/path_to_config.py\']"\n}' ]
[9/19/2019, 3:41:59 AM] INFO [ 'Trial job Sl0x3 status changed from WAITING to RUNNING' ]
[9/19/2019, 3:42:05 AM] INFO [ 'POST: /stdout/OlabyaBd/Sl0x3: body:\n{\n    "stdOutputType": "Stdout",\n    "tag": "trial_keeper",\n    "msg": "[2019-09-19 03:42:05.930426] INFO subprocess terminated. Exit code is 1. Quit"\n}' ]
[9/19/2019, 3:42:05 AM] INFO [ 'POST: /stdout/OlabyaBd/Sl0x3: body:\n{\n    "stdOutputType": "Stdout",\n    "tag": "trial_keeper",\n    "msg": "[2019-09-19 03:42:05.941913] INFO NNI trial keeper exit with code 1"\n}' ]
[9/19/2019, 3:42:09 AM] INFO [ 'Trial job Sl0x3 status changed from RUNNING to FAILED' ]`

**Comment by apatsekin** [comment]
I figured it out. That was my fault related to docker containers. Sorry for taking your time.
