### ISSUE TITLE
nnictl package install not working for venv

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#1576]
It seems that `nnictl package install` makes the package going to user level, which makes it not accessible from a venv.

Warning:

```
Installing collected packages: ConfigSpaceNNI, docutils, pynisher, pyrfr, sphinxcontrib-htmlhelp, sphinxcontrib-qthelp, sphinxcontrib-devhelp, imagesize, Jinja2, sphinxcontrib-applehelp, alabaster, sphinxcontrib-jsmath, Pygments, snowballstemmer, sphinxcontrib-serializinghtml, packaging, sphinx, sphinx-rtd-theme, smac
  Running setup.py install for ConfigSpaceNNI ... done
  The script pygmentize is installed in '/home/zhangyuge/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for snowballstemmer ... done
  The scripts sphinx-apidoc, sphinx-autogen, sphinx-build and sphinx-quickstart are installed in '/home/zhangyuge/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for smac ... done
```

Corresponding code:

https://github.com/microsoft/nni/blob/958efabf066b975a5cdcde293c9de33ec1430cb2/tools/nni_cmd/command_utils.py#L49

We could consider removing this `--user`.

**Comment by QuanluZhang** [comment]
@ultmaster Could you try to fix it?

**Comment by ultmaster** [comment]
Sure. By removing this `--user`. I just don't understand why we have it in the first place.

**Comment by QuanluZhang** [comment]
If users installed nni locally (not in virtual env), no `--user` means users have to use `sudo` to run pip command.

**Comment by ultmaster** [comment]
I don't know about this. As far as I remember, last time I run pip outside a virtual env, it automatically goes into some `~/.pip` without asking `sudo`. I think removing `--user` is better than adding this, because `--user` might contaminate the outside environment, which is definitely not wanted.

Meanwhile, I will check whether there is a way to tell `pip` is inside a virtualenv/conda or not.
