### ISSUE TITLE
failed to train with remote mode

### ISSUE THREAD

**Issue by justttry** [microsoft/nni#1578]
hello, everyone,
      I used the experiment examples/trials/weight_sharing/ga_squad/config_remote.yml, and I modified the machineList with my own machine, but the experiment was waiting and the log is below. Is there any suggestion?
```
[9/29/2019, 4:40:41 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:40:41 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:40:44 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:40:44 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:40:47 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:40:47 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:40:50 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:40:50 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:40:53 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:40:53 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:40:56 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:40:56 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:40:59 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:40:59 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:02 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:02 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:05 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:05 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:08 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:08 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:11 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:11 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:14 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:14 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:17 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:17 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:20 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:20 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:23 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:23 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:26 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:26 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:29 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:29 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:32 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[9/29/2019, 4:41:32 PM] INFO [ 'Right now no available GPU can be allocated for trial iwzEY, will try to schedule later' ]
[9/29/2019, 4:41:35 PM] WARNING [ 'Scheduler: trialJob id iwzEY, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
```

**Comment by martsalz** [comment]
Can you check if `nvidia-smi` is available on your machine?

**Comment by xuehui1991** [comment]
The log shows that you might have enough GPU resource to run this code. If you want to run in CPU, you can change the setting in `config.yml`.

**Comment by justttry** [comment]
@martsalz nvidia-smi is available and the print is below. I want to use the GPUs, but it seems to find no GPUs. @xuehui1991 
`
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:04:00.0 Off |                    0 |
| N/A   26C    P8    16W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           On   | 00000000:05:00.0 Off |                    0 |
| N/A   24C    P8    16W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           On   | 00000000:08:00.0 Off |                    0 |
| N/A   26C    P8    16W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           On   | 00000000:09:00.0 Off |                    0 |
| N/A   28C    P8    16W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P40           On   | 00000000:85:00.0 Off |                    0 |
| N/A   29C    P8    17W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P40           On   | 00000000:86:00.0 Off |                    0 |
| N/A   29C    P8    16W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P40           On   | 00000000:89:00.0 Off |                    0 |
| N/A   28C    P8    16W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P40           On   | 00000000:8A:00.0 Off |                    0 |
| N/A   29C    P8    16W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
`

**Comment by martsalz** [comment]
Do other applications/users use the GPUs in parallel? If yes, please specify `useActiveGpu=true` in the `config.yml`. By default, NNI will use the GPU only if there is no another active process in the GPU. See:

https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md

**Comment by justttry** [comment]
The config.yml is below:
`authorName: default
experimentName: example_cifar10-network-morphism
trialConcurrency: 2
maxExecDuration: 48h
maxTrialNum: 200
#choice: local, remote, pai
trainingServicePlatform: remote
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #for now, this tuner only supports cv domain
    task: cv
    #input image width
    input_width: 32
    #input image channel
    input_channel: 3
    #number of classes
    n_output_node: 10
trial:
  command: python3 cifar10_pytorch.py
  codeDir: .
  gpuNum: 1
#local, machineList is Null
machineList:
    -ip : xxx.xxx.xxx.xxx
     username: xxxx
     passwd: xxxxxx`

**Comment by Fangyh09** [comment]
I had the same problem...

**Comment by chicm-ms** [comment]
@justttry Would you please paste the config.yml as @martsalz  mentioned.  
There is a similar issue #1852 which has already been fixed, please check it.

**Comment by xingwangsfu** [comment]
Hi @chicm-ms,
I also met the same problem. I followed the instructions in #1852 , but got no luck.  There is no such file 'tmp/root/nni/scripts/gpu_metrics'  in my remote machine although I can generate it manually with `bash -c echo $$ > /tmp/root/nni/scripts/pid ; METRIC_OUTPUT_DIR=/tmp/root/nni/scripts python3 -m nni_gpu_tool.gpu_metrics_collector`.  

The config.yml and nnimanager.log are attached as follows

`authorName: default
debug: true
experimentName: example_cifar_pytorch
trialConcurrency: 2
maxExecDuration: 1h
maxTrialNum: 128
#choice: local, remote, pai
trainingServicePlatform: remote
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
    builtinTunerName: TPE
    classArgs:
        optimize_mode: maximize

trial:
  command: python3 cifar.py
  codeDir: .
  gpuNum: 1

  #    - ip: 10.22.225.144
  #    username: root
  #    port: 9002
  #    sshKeyPath: /root/.ssh/id_rsa

machineList:
    - ip: 10.22.228.140
      username: root
      port: 9003
      sshKeyPath: /root/.ssh/id_rsa
    - ip: 10.22.226.194
      username: root
      port: 9000
      sshKeyPath: /root/.ssh/id_rsa`

`  1 [3/11/2020, 10:17:13 AM] DEBUG [ 'Database directory: /root/nni/experiments/oxNT5WxA/db' ]
  2 [3/11/2020, 10:17:13 AM] INFO [ 'Datastore initialization done' ]
  3 [3/11/2020, 10:17:13 AM] INFO [ 'RestServer start' ]
  4 [3/11/2020, 10:17:13 AM] INFO [ 'Construct remote machine training service.' ]
  5 [3/11/2020, 10:17:13 AM] INFO [ 'RestServer base port is 6666' ]
  6 [3/11/2020, 10:17:13 AM] INFO [ 'Rest server listening on: http://0.0.0.0:6666' ]
  7 [3/11/2020, 10:17:16 AM] DEBUG [ 'GET: /check-status: body:\n{}' ] 
  8 [3/11/2020, 10:17:16 AM] DEBUG [ 'PUT: /experiment/cluster-metadata: body:\n{\n    "machine_list": [\n        {\n            "ip": "10.22.228.140",\n                "username": "root",\n            "port": 9003,\n            "sshKeyPath": "/root/.ssh/id_rsa"\n        },\n        {\n            "ip": "10.22.226.    194",\n            "username": "root",\n            "port": 9000,\n            "sshKeyPath": "/root/.ssh/id_rsa"\n        }\n    ]\n}' ]
  9 [3/11/2020, 10:17:16 AM] INFO [ 'NNIManager setClusterMetadata, key: machine_list, value: [{"ip":"10.22.228.140","username":"root","port":9003,"sshKeyPath    ":"/root/.ssh/id_rsa"},{"ip":"10.22.226.194","username":"root","port":9000,"sshKeyPath":"/root/.ssh/id_rsa"}]' ]
 10 [3/11/2020, 10:17:16 AM] DEBUG [ 'Connecting to remote machines: [{"ip":"10.22.228.140","username":"root","port":9003,"sshKeyPath":"/root/.ssh/id_rsa"},{"    ip":"10.22.226.194","username":"root","port":9000,"sshKeyPath":"/root/.ssh/id_rsa"}]' ]
 11 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [mkdir -p /tmp/nni/experiments/oxNT5WxA]' ]
 12 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [mkdir -p /tmp/nni/experiments/oxNT5WxA]' ]
 13 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [(umask 0 ; mkdir -p /tmp/root/nni/scripts)]' ]
 14 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [chmod 777 /tmp/nni /tmp/nni/* /tmp/nni/scripts/*]' ]
 15 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [bash -c \'echo $$ > /tmp/root/nni/scripts/pid ; METRIC_OUTPUT_DIR=/tmp/root/nni/scripts pyth    on3 -m nni_gpu_tool.gpu_metrics_collector\']' ]
 16 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [(umask 0 ; mkdir -p /tmp/root/nni/scripts)]' ]
 17 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [chmod 777 /tmp/nni /tmp/nni/* /tmp/nni/scripts/*]' ]
 18 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [bash -c \'echo $$ > /tmp/root/nni/scripts/pid ; METRIC_OUTPUT_DIR=/tmp/root/nni/scripts pyth    on3 -m nni_gpu_tool.gpu_metrics_collector\']' ]
 19 [3/11/2020, 10:17:16 AM] DEBUG [ 'PUT: /experiment/cluster-metadata: body:\n{\n    "trial_config": {\n        "command": "python3 cifar.py",\n        "cod    eDir": "/mnt/cephfs_new_wj/cv/wangxing/source_code/bytennf/examples/trials/cifar-rcnsa-advisor/.",\n        "gpuNum": 1\n    }\n}' ]
 20 [3/11/2020, 10:17:16 AM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python3 cifar.py","codeDir":"/mnt/cephfs_new_wj/cv/w    angxing/source_code/bytennf/examples/trials/cifar-rcnsa-advisor/.","gpuNum":1}' ]
 21 [3/11/2020, 10:17:16 AM] DEBUG [ 'POST: /experiment: body:\n{\n    "authorName": "default",\n    "experimentName": "example_cifar_pytorch",\n    "trialCon    currency": 2,\n    "maxExecDuration": 3600,\n    "maxTrialNum": 128,\n    "searchSpace": "{\\"in_channel_1\\": {\\"_type\\": \\"choice\\", \\"_value\\": [    8, 16, 24, 32]}, \\"in_channel_2\\": {\\"_type\\": \\"choice\\", \\"_value\\": [8, 16, 24, 32]}, \\"in_channel_3\\": {\\"_type\\": \\"choice\\", \\"_value    \\": [8, 16, 24, 32]}, \\"in_channel_4\\": {\\"_type\\": \\"choice\\", \\"_value\\": [8, 16, 24, 32]}, \\"hidden_size\\": {\\"_type\\": \\"choice\\", \\"_    value\\": [128, 256, 512, 1024]}}",\n    "trainingServicePlatform": "remote",\n    "tuner": {\n        "builtinTunerName": "TPE",\n        "classArgs": {\    n            "optimize_mode": "maximize"\n        }\n    },\n    "versionCheck": false,\n    "clusterMetaData": [\n        {\n            "key": "machine_    list",\n            "value": [\n                {\n                    "ip": "10.22.228.140",\n                    "username": "root",\n                        "port": 9003,\n                    "sshKeyPath": "/root/.ssh/id_rsa"\n                },\n                {\n                    "ip": "10.22.226.194",\    n                    "username": "root",\n                    "port": 9000,\n                    "sshKeyPath": "/root/.ssh/id_rsa"\n                }\n                ]\n        },\n        {\n            "key": "trial_config",\n            "value": {\n                "command": "python3 cifar.py",\n                    "codeDir": "/mnt/cephfs_new_wj/cv/wangxing/source_code/bytennf/examples/trials/cifar-rcnsa-advisor/.",\n                "gpuNum": 1\n            }\n            }\n    ]\n}' ]
 22 [3/11/2020, 10:17:16 AM] INFO [ 'Starting experiment: oxNT5WxA' ]
 23 [3/11/2020, 10:17:16 AM] DEBUG [ 'Setup tuner...' ] 
[3/11/2020, 10:17:16 AM] DEBUG [ 'dispatcher command: python3 -m nni --exp_params eyJhdXRob3JOYW1lIjoiZGVmYXVsdCIsImV4cGVyaW1lbnROYW1lIjoiZXhhbXBsZV9jaWZh    cl9weXRvcmNoIiwidHJpYWxDb25jdXJyZW5jeSI6MiwibWF4RXhlY0R1cmF0aW9uIjozNjAwLCJtYXhUcmlhbE51bSI6MTI4LCJ0cmFpbmluZ1NlcnZpY2VQbGF0Zm9ybSI6InJlbW90ZSIsInR1bmVyIj    p7ImJ1aWx0aW5UdW5lck5hbWUiOiJUUEUiLCJjbGFzc0FyZ3MiOnsib3B0aW1pemVfbW9kZSI6Im1heGltaXplIn19LCJ2ZXJzaW9uQ2hlY2siOmZhbHNlLCJjbHVzdGVyTWV0YURhdGEiOlt7ImtleSI6    Im1hY2hpbmVfbGlzdCIsInZhbHVlIjpbeyJpcCI6IjEwLjIyLjIyOC4xNDAiLCJ1c2VybmFtZSI6InJvb3QiLCJwb3J0Ijo5MDAzLCJzc2hLZXlQYXRoIjoiL3Jvb3QvLnNzaC9pZF9yc2EifSx7ImlwIj    oiMTAuMjIuMjI2LjE5NCIsInVzZXJuYW1lIjoicm9vdCIsInBvcnQiOjkwMDAsInNzaEtleVBhdGgiOiIvcm9vdC8uc3NoL2lkX3JzYSJ9XX0seyJrZXkiOiJ0cmlhbF9jb25maWciLCJ2YWx1ZSI6eyJj    b21tYW5kIjoicHl0aG9uMyBjaWZhci5weSIsImNvZGVEaXIiOiIvbW50L2NlcGhmc19uZXdfd2ovY3Yvd2FuZ3hpbmcvc291cmNlX2NvZGUvYnl0ZW5uZi9leGFtcGxlcy90cmlhbHMvY2lmYXItcmNuc2    EtYWR2aXNvci8uIiwiZ3B1TnVtIjoxfX1dfQ==' ]
 25 [3/11/2020, 10:17:16 AM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
 26 [3/11/2020, 10:17:16 AM] INFO [ 'Add event listeners' ]
 27 [3/11/2020, 10:17:16 AM] DEBUG [ 'Send tuner command: INITIALIZE: {"in_channel_1": {"_type": "choice", "_value": [8, 16, 24, 32]}, "in_channel_2": {"_type    ": "choice", "_value": [8, 16, 24, 32]}, "in_channel_3": {"_type": "choice", "_value": [8, 16, 24, 32]}, "in_channel_4": {"_type": "choice", "_value": [8,     16, 24, 32]}, "hidden_size": {"_type": "choice", "_value": [128, 256, 512, 1024]}}' ]
 28 [3/11/2020, 10:17:16 AM] DEBUG [ 'ipcInterface command type: [IN], content:[{"in_channel_1": {"_type": "choice", "_value": [8, 16, 24, 32]}, "in_channel_2    ": {"_type": "choice", "_value": [8, 16, 24, 32]}, "in_channel_3": {"_type": "choice", "_value": [8, 16, 24, 32]}, "in_channel_4": {"_type": "choice", "_v    alue": [8, 16, 24, 32]}, "hidden_size": {"_type": "choice", "_value": [128, 256, 512, 1024]}}]' ]
 29 [3/11/2020, 10:17:16 AM] DEBUG [ 'ipcInterface command type: [PI], content:[]' ]
 30 [3/11/2020, 10:17:16 AM] INFO [ 'RestServer start' ]
 31 [3/11/2020, 10:17:16 AM] INFO [ 'RestServer base port is 6667' ]
 32 [3/11/2020, 10:17:16 AM] INFO [ 'Run remote machine training service.' ]
 33 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 34 [3/11/2020, 10:17:16 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 35 [3/11/2020, 10:17:17 AM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
 36 [3/11/2020, 10:17:17 AM] DEBUG [ 'ipcInterface command type: [GE], content:[2]' ]
 37 [3/11/2020, 10:17:17 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"in_    channel_1": 24, "in_channel_2": 32, "in_channel_3": 8, "in_channel_4": 24, "hidden_size": 128}, "parameter_index": 0}' ]
 38 [3/11/2020, 10:17:17 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"in_    channel_1": 16, "in_channel_2": 24, "in_channel_3": 16, "in_channel_4": 32, "hidden_size": 512}, "parameter_index": 0}' ]
 39 [3/11/2020, 10:17:17 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 40 [3/11/2020, 10:17:17 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 41 [3/11/2020, 10:17:18 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 42 [3/11/2020, 10:17:18 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 43 [3/11/2020, 10:17:19 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 44 [3/11/2020, 10:17:19 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 45 [3/11/2020, 10:17:20 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 46 [3/11/2020, 10:17:20 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 47 [3/11/2020, 10:17:21 AM] DEBUG [ 'ipcInterface command type: [PI], content:[]' ]
 48 [3/11/2020, 10:17:21 AM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algo    rithm\\", \\"parameters\\": {\\"in_channel_1\\": 24, \\"in_channel_2\\": 32, \\"in_channel_3\\": 8, \\"in_channel_4\\": 24, \\"hidden_size\\": 128}, \\"pa    rameter_index\\": 0}","index":0}}' ]
 49 [3/11/2020, 10:17:21 AM] DEBUG [ 'storeTrialJobEvent: event: WAITING, data: {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"in_channe    l_1": 24, "in_channel_2": 32, "in_channel_3": 8, "in_channel_4": 24, "hidden_size": 128}, "parameter_index": 0}, jobDetail: {"id":"P9vW6","status":"WAITIN    G","submitTime":1583921841578,"workingDirectory":"/tmp/nni/experiments/oxNT5WxA/trials/P9vW6","form":{"sequenceId":0,"hyperParameters":{"value":"{\\"param    eter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"in_channel_1\\": 24, \\"in_channel_2\\": 32, \\"in_channel_3\\": 8, \\"in_ch    annel_4\\": 24, \\"hidden_size\\": 128}, \\"parameter_index\\": 0}","index":0}},"tags":[],"gpuIndices":[]}' ]
 52 [3/11/2020, 10:17:21 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 53 [3/11/2020, 10:17:21 AM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
 54 [3/11/2020, 10:17:22 AM] WARNING [ 'Scheduler: trialJob id P9vW6, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
 55 [3/11/2020, 10:17:22 AM] INFO [ 'Right now no available GPU can be allocated for trial P9vW6, will try to schedule later' ]`

**Comment by chicm-ms** [comment]
@xingwangsfu Are your remote machines in docker containers?  
Would you please check following?
1. nni version on remote remote machine
2. Whether  process `nni_gpu_tool.gpu_metrics_collector` is running on remote machine while nni is started.
3. Whether /tmp/root/nni/scripts/pid  file exist on remote machine if you do not generate gpu metrics manually while nni is started.

**Comment by xingwangsfu** [comment]
Update on this @chicm-ms :
I have to run nni in conda on remote machine. But the remote mode always call the '/usr/bin/python3' to generate gpu_metric file. That's why the problem happened. To solve this problem, I also installed nni with '/usr/bin/python3'. Then, the error disappeared. I think this problem is related to #1712 .

**Comment by scarlett2018** [comment]
> Update on this @chicm-ms :
> I have to run nni in conda on remote machine. But the remote mode always called the '/usr/bin/python3' to generate gpu_metric file. That's why the problem happened. To solve this problem, I also installed nni with '/usr/bin/python3'. Then, the error disappeared. I think this problem is related to #1712 .
> 
> Is there a way to force nni to use the user specified python3 to generate gpu_metric instead of '/usr/bin/python3' on the remote machine?

@chicm-ms @QuanluZhang @SparkSnail - this sounds a fair ask =).

**Comment by chicm-ms** [comment]
@scarlett2018  Yes, I also think this is a reasonable requirement, currently the python executable is hard coded as `python3`: 
https://github.com/microsoft/nni/blob/master/src/nni_manager/training_service/common/util.ts#L205
