### ISSUE TITLE
[10/01/2019, 07:44:07 PM] ERROR (nni.msg_dispatcher_base/Thread-1) index 510 is out of bounds for axis 1 with size 507

### ISSUE THREAD

**Issue by modaiwang** [microsoft/nni#1581]
when i run my experiment on nni，i find my WebUI is offline，and i search for the logs, i see the message below:

[10/01/2019, 07:44:07 PM] ERROR (nni.msg_dispatcher_base/Thread-1) index 510 is out of bounds for axis 1 with size 507

i don't know how to fix it .

**nni Environment**:
- nni version: latest
- nni mode  local
- OS: linux ubuntu
- python version:3.6
- is conda or virtualenv used?: yes
- is running in docker?:no

**Comment by modaiwang** [comment]
o, i figure out the problem right now, i have save the tf model every optimal step ( wrong), maybe the random filename is out of range, delete my wrong code, the tuner can work well. Sorry for that.

**Comment by chicm-ms** [comment]
Close the issue since it has been resolved.
