### ISSUE TITLE
logDir: Allow to have spaces in the path to the directory

### ISSUE THREAD

**Issue by thomas-beznik** [microsoft/nni#1583]
Hello everyone!

**Short summary about the issue/question**:
I would like to save the experiments in a specific folder; I thus set the "logDir" in the config file to the path to this folder. The problem is that in the path to that folder there is a folder which has a space in its name ("My Drive"). The name of this last folder cannot be changed. Because of this space, I get the following error:

ERROR [ 'ChildProcessError: Command failed: mkdir -p /content/gdrive/My Drive/3DSegmentation/relu-framework/Sessions/Test/py8x7FgL/trials/Ugn5Y\nmkdir: cannot create directory ‘/content/gdrive/My’: Operation not supported\n `mkdir -p /content/gdrive/My Drive/3DSegmentation/relu-framework/Sessions/Test/py8x7FgL/trials/Ugn5Y` (exited with error code 1)\n    at callback (/usr/local/nni/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:296:5)\n    at ChildProcess.emit (events.js:182:13)\n    at maybeClose (internal/child_process.js:962:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)' ]

Would it be possible to support paths with spaces in them ? How could I fix this myself in the meantime ?

Thank you for the help!

Thomas

**Comment by SparkSnail** [comment]
Hi, thanks for raising the issue. NNI does not support spaces in logDir yet, we will support the feature in next release.

**Comment by xinshouke** [comment]
I had met this issue now,will fix refer to the above later...

**Comment by SparkSnail** [comment]
fixed in https://github.com/microsoft/nni/pull/1694, close this issue.
