### ISSUE TITLE
How to request the specific GPU(a GPU with large memory) in OpenPAI?

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1584]
**Short summary about the issue/question**:
Some task may cost large memory usage of GPU, how can I request a GPU with large memory when using nni PAI mode?

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by SparkSnail** [comment]
Hi, according to https://github.com/microsoft/pai/blob/b2324866d0280a2d22958717ea6025740f71b9f0/docs/job_tutorial.md, pai support setting gpuType in configuration, this parameter will set specific kind of GPU (with large memory). NNI does not support setting gpuType configuration.
PAI also support [dedicated_vc](https://github.com/microsoft/pai/blob/65b44e1ab37cab0790af392a016cc9fb1d2318fe/docs/tools/dedicated_vc.md#dedicated_vc), which could allocate some kind of gpu machine to a VC, and users could submit specific kind of jobs to this VC,then the job could use the wanted GPUs. NNI support setting virtualCluster in configuration.
