### ISSUE TITLE
NAS-cifar10 Example got some error  in version 1.0

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1585]
**Short summary about the issue/question**:
when running the [example](https://github.com/microsoft/nni/tree/master/examples/trials/nas_cifar10) in nni-1.0, got some error like:
ERRPR: tuner builtinTunerName error!

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**: linux
- nni version: 1.0
- nni mode(local|pai|remote): 
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by ultmaster** [comment]
It turns out that PPO Tuner isn't included in 1.0 release. Please install by master or daily build.
