### ISSUE TITLE
Can nni support to customize a  One-Shot tuner?

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1586]
**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by ultmaster** [comment]
It's already supported: `https://github.com/microsoft/nni/tree/master/examples/trials/mnist-nas`

Please make this clear. What type of one-shot tuner do you want?

**Comment by scarlett2018** [comment]
The support document for One-shot: https://github.com/microsoft/nni/blob/482c70d1ea57dc88c6e354248fc9fc65d0d7841f/docs/en_US/AdvancedFeature/GeneralNasInterfaces.md#oneshot_mode

**Comment by xuehui1991** [comment]
Just wondering can I use it to run in PAI? How about weight sharing? Does this example sharing weight in local or remote mode?

**Comment by xuehui1991** [comment]
I change the title.

**Comment by ultmaster** [comment]
Currently no. It's already in our plan.

**Comment by QuanluZhang** [comment]
supported, close
