### ISSUE TITLE
Can nni offer some test metric for the example using one-shot/dart/enas model?

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1598]
**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by ultmaster** [comment]
This will be done after we implement the "correct" one-shot model.

**Comment by scarlett2018** [comment]
> This will be done after we implement the "correct" one-shot model.

Assign @ultmaster for follow up with when/how the "correct" one-shot model implementation address the issue

**Comment by ultmaster** [comment]
Reproduction results of DARTS have been released in docs. ENAS is still under revision.

**Comment by scarlett2018** [comment]
> Reproduction results of DARTS have been released in docs. ENAS is still under revision.

@ultmaster - what's the left work for this issue?

**Comment by scarlett2018** [comment]
should work after NAS refactoring.
