### ISSUE TITLE
show more readable content in the generated search space file

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/nni#160]
In v0.1 and v0.2, if users use nni annotation in their trial code and use for example `@nni.function_choice` in their code, nni will use different numbers to designate different candidate functions from `@nni.function_choice` in the generated search space file. Thus, in webui, users only get the numbers instead of the real function names, which is very unfriendly. It would be great to use function names in the generated search space file.

**Comment by yds05** [comment]
Already fixed. Close it.
