### ISSUE TITLE
Merge pai configuration with NNI

### ISSUE THREAD

**Issue by SparkSnail** [microsoft/nni#1606]
In current NNI design, if users want to use a new PAI configuration, NNI should use add the 
 configuration and have a lot of code change. It's better to support merging PAI configuration with NNI configuration, and no need to change NNI code to support new config anymore.

**Comment by scarlett2018** [comment]
Assign to @SparkSnail for driving the design and discussion first.

**Comment by scarlett2018** [comment]
> Assign to @SparkSnail for driving the design and discussion first.

@SparkSnail - may we close this issue?

**Comment by SparkSnail** [comment]
> > Assign to @SparkSnail for driving the design and discussion first.
> 
> @SparkSnail - may we close this issue?

yes
