### ISSUE TITLE
The mnist example failed to run on the Tensorflow 1.14 GPU of the CentOS7 system.

### ISSUE THREAD

**Issue by qtz93** [microsoft/nni#1609]
**Short summary about the issue/question**:
When I run the mnist sample, the results of accessing the web page always show failed.

**Brief what process you are following**: 
After viewing the log, it was found that the data was not read successfully and the tensorflow interface call failed. The error log is as follows:

Traceback (most recent call last):
  File "mnist.py", line 10, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
ModuleNotFoundError: No module named 'tensorflow.examples'.

Later, I copied an input_data.py file and defined placeholder as tf1.14(tf.compat.v1.placeholder). The following errors were reported: 

AttributeError: model tensorflow has no attribute compat.

**How to reproduce it**: 

**nni Environment**:
- nni version: 0.9.1.1
- nni mode(local|pai|remote): local
- OS: CentOS7.4.1708
- python version: Python3.6.5
- is conda or virtualenv used?:  conda
- is running in docker?: no

**need to update document(yes/no)**: yes

**Anything else we need to know**:

**Comment by ultmaster** [comment]
See https://stackoverflow.com/questions/50313441/modulenotfounderror-no-module-named-tensorflow-examples.

Please check whether you code can work without nni first.

**Comment by qtz93** [comment]
The mnist example can be run without the nni framework. --__--

**Comment by ultmaster** [comment]
@qtz93 So your problem is: your tensorflow works in an environment without nni, but doesn't work in whatever environment is launched by nni.

Sounds like you are using different environments to me. My suggestion is to reinstall in a new environment, with conda or without conda, installing tensorflow with conda or without conda, trying tensorflow from 1.12 to 1.14, and update nni to 1.0.

**Comment by qtz93** [comment]
Thank you, I downgraded tensorflow version to 1.13.1 and passed the mnist test. ^_^
