### ISSUE TITLE
TensorFlow 2.0 API change

### ISSUE THREAD

**Issue by liuzhe-lz** [microsoft/nni#1614]
TensorFlow 2.0 have significantly changed their API. `tensorflow.compat.v1` must be used to make legacy code work.
However this module only appears in latest versions of TensorFlow. And we want to keep NNI compatible with "stable" platforms.
Let's discuss a solution.

An example approach (does not work if user wants to use tf 2.0 features):
```python
try:
    import tensorflow as tf
    import tensorflow.compat.v1 as tf
    tf.disable_v2_behavior()
except (ModuleNotFoundError, AttributeError):
    pass
```

**Comment by QuanluZhang** [comment]
@liuzhe-lz can we close this issue now?

**Comment by liuzhe-lz** [comment]
This is only partially done.
For example our docker image is still using TF 1.10.

**Comment by scarlett2018** [comment]
won't fix, is not needed.
