### ISSUE TITLE
Bug: Error: EMFILE: too many open files, open  at lazyFs.open (internal/fs/streams.js:273:12)

### ISSUE THREAD

**Issue by apatsekin** [microsoft/nni#1620]
**Short summary about the issue/question**:
NNI control server crashes while running experiment for several days. The only signs of crash are found in `nnictl log stderr [exp_id]`. Everything else just looks like process disappeared.

**Brief what process you are following**: Running a `nnicreate` on one machine to create `remote` experiment which involves 2 workers (2 different machines). After 6 days of running nni control daemon fails with:
```
(node:41922) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10569)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open '/root/nni/experiments/cJd6Fzn0/log/nnimanager.log'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:141:20)

```

**How to reproduce it**: 

**nni Environment**:
nni version: 1.0
nni mode(local|pai|remote): remote
OS: Ubuntu 16.04.6 LTS
python version: 3.6.8
is conda or virtualenv used?: no
is running in docker?: yes

**need to update document(yes/no)**: no

**Anything else we need to know**: 
Relevant logs: 
[nnimanager.log](https://github.com/microsoft/nni/files/3736870/nnimanager.log)
[nni_stderr.log](https://github.com/microsoft/nni/files/3736871/nni_stderr.log)
[dispatcher.log](https://github.com/microsoft/nni/files/3736872/dispatcher.log)

**Comment by ultmaster** [comment]
It looks to me that the upper limit of number of files opened is reached. Is there other processes running that would open a lot of files (like file sync, or database...).

**Comment by apatsekin** [comment]
So far every `remote` experiments eventually errors out with this message. After resuming this experiment it had been working for 5 days until crash. Same error message. 
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open '/root/nni/experiments/cJd6Fzn0/log/nnimanager.log'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
```


also this warning in stderr is pretty annoying (takes MBs of logs):
```
(node:48255) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at AnonymousObserver.disposable.timer.subscribe [as _onNext] (/root/.pyenv/versions/3.6.8/nni/training_service/remote_machine/remoteMachineTrainingService.js:331:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

@ultmaster thanks for response! not really, server is almost idle. I don't even run training on the machine where nni manager is working. Also I noticed that with time web UI becomes super slow: initial AJAX request of trials might take like 10 seconds to load.

**Comment by apatsekin** [comment]
After 12 hours of run, `node` keeps 1.5m opened file handlers to `log/nnimanager.log`.

**Comment by SparkSnail** [comment]
Hi, @apatsekin . Thanks for raising the issue, does this problem only occur on remote mode? will it happen on local mode?

**Comment by apatsekin** [comment]
Hi @SparkSnail . Thanks for reacting! The same experiment run in a local mode doesn't cause this growth of unclosed handlers. So it's something specific to `remote` mode.

**Comment by apatsekin** [comment]
bump... any ideas? I'm sure it's a matter of one-line closing file handler in some `final` block.

 ```
**138492** 5883 node
    264 5905 python3
     38 3300 sshd
     29 6363 zsh
     29 4860 zsh
     29 3753 zsh
     29 1 zsh
     17 6525 lsof
     12 6526 lsof
     11 5904 sh
      1 PID COMMAND
```

**Comment by scarlett2018** [comment]
@SparkSnail seems a remote mode problem.

**Comment by SparkSnail** [comment]
Hi @apatsekin , thanks for raising the problem, I've checked NNI's code, and perhaps this problem is caused by https://github.com/microsoft/nni/blob/master/src/nni_manager/training_service/remote_machine/sshClientUtility.ts#L152. I'm investigating and will give a hot fix ASAP.

**Comment by SparkSnail** [comment]
https://github.com/microsoft/nni/pull/1749

**Comment by SparkSnail** [comment]
https://github.com/microsoft/nni/pull/1755
