### ISSUE TITLE
Can't run any trials

### ISSUE THREAD

**Issue by cjissmart** [microsoft/nni#1621]
When I run the NNI example mnist in a Linux environment, it seems like everything is ok. However, it can't run any trials and the experiment has been over. Could you give me some suggestions?
Notation that the environment which I can't manage is a Cloud Platform controlled by someone, and any python script is run by sbatch, python x.py is prohibited.

![image](https://user-images.githubusercontent.com/37531166/67018765-42062780-f12e-11e9-85d9-219ee7a6b37f.png)

**nni Environment**:
- nni version:
- nni mode(local|pai|remote): local ( I upload all of dataset and code)
- OS: Linux
- python version: 3.6
- is conda or virtualenv used?: conda 
- is running in docker?: No
It seems everything is ok unless it can't run any trials.

**Comment by ultmaster** [comment]
Can you share your `config.yml`? Did you use `sbatch` to launch trial? As far as I know, `sbatch` will return immediately when the job gets queued.

**Comment by cjissmart** [comment]
> Can you share your `config.yml`? Did you use `sbatch` to launch trial? As far as I know, `sbatch` will return immediately when the job gets queued.

This is my config.yml. And I don't know how to run a trial by sbatch. I can run a experiment by sbatch only.
![image](https://user-images.githubusercontent.com/37531166/67063570-d8236780-f199-11e9-8ee3-1a609ecc44bb.png)

**Comment by ultmaster** [comment]
So you run `nnictl` with `sbatch` right? It's like `sbatch nnictl ...`?

Assuming you are using slurm, did you check `squeue` for your job status? Does the job complete very quickly in seconds (or minutes)?

**Comment by cjissmart** [comment]
> So you run `nnictl` with `sbatch` right? It's like `sbatch nnictl ...`?
> 
> Assuming you are using slurm, did you check `squeue` for your job status? Does the job complete very quickly in seconds (or minutes)?

I checked squeue. The job finishes quickly ( about two or three munites ).

I modify my sbatch file, according to your advice
![image](https://user-images.githubusercontent.com/37531166/67078473-f00fe100-f1c3-11e9-8397-800de98f73b4.png)
Then I find it doesn't still work. And NNI's log file is empty.

**Comment by cjissmart** [comment]
> So you modify your file to be `sbatch nnictl`? So what did you do previously? Where did you use `sbatch`?
> 
> To run nni on slurm, a simple workaround is to try to add `sleep 30000000` after `nnictl`. Because `nnictl` exits immediately after it launches the experiment, and slurm believes your job has finished and will release your resources. That's why your experiment exists quickly.

Thanks for your help !!!
How to add sleep 30000000 after nnitcl ?
modify the config file?

**Comment by ultmaster** [comment]
@cjissmart You can follow the practice of sbatch, which writes a script containing nnictl and sleep. I'm sure it's mentioned in your manual.

**Comment by scarlett2018** [comment]
> > So you modify your file to be `sbatch nnictl`? So what did you do previously? Where did you use `sbatch`?
> > To run nni on slurm, a simple workaround is to try to add `sleep 30000000` after `nnictl`. Because `nnictl` exits immediately after it launches the experiment, and slurm believes your job has finished and will release your resources. That's why your experiment exists quickly.
> 
> Thanks for your help !!!
> How to add sleep 30000000 after nnitcl ?
> modify the config file?

Seems the "can't run trials" problem is resolved closing the issue. thanks for the feedback, feel free to open issue for new questions or reopen the issue if the problem occur again.
