### ISSUE TITLE
report_result fails when running in standalone mode

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#1622]
In standalone mode, report intermediate result and final result will both fail because `_params` is None.

Now I have to do this as a workaround:

```python
if trial_env_vars.NNI_PLATFORM is not None:
    if epoch + 1 >= opt.n_epochs and not periodical:
        nni.report_final_result(val_loss.avg)
    else:
        nni.report_intermediate_result(val_loss.avg)
```

Maybe this workaround should be embedded into trial SDK.

**Comment by chicm-ms** [comment]
Need to support standalone mode.

**Comment by QuanluZhang** [comment]
resolved, close
