### ISSUE TITLE
hyperopt 0.2 support

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/nni#1623]

**Comment by ultmaster** [comment]
Temporarily fixed to 0.1.2 via #1625.

**Comment by haoren3696** [comment]
https://github.com/microsoft/nni/blob/master/setup.py#L33
Hi, @ultmaster, @suiguoxin ,why does NNI depend on Hyperopt 0.1.2? the latest hyperopt version is 0.2.5. when will nni support hyperot 0.2.5?

**Comment by ultmaster** [comment]
Hi @haoren3696, hyperopt 0.2 has updated its API and NNI hasn't updated its implementation accordingly. We believe that this is a low priority issue. Please tell us why this is urgent. Thanks.

**Comment by haoren3696** [comment]
Hi, @ultmaster , because hyperopt 0.2.5 has been installed in my system and some softwares  depends on hyperopt 0.2, now I try to install nni on my system and failed due to conflict hyperopt version requirement.

**Comment by ultmaster** [comment]
@haoren3696, thanks for letting us know that you are experiencing such issue. We will put it on the agenda, hopefully in the next release.

Meanwhile, pip has a `--no-dependencies` option. You can ignore that dependency and use hyperopt on your own if you are not using any tuners that relies on hyperopt (TPE, Random, Anneal).

**Comment by Ennosigaeon** [comment]
Any updates on this issue? hyperopt 0.1.2 is by now 3.5 years old.

**Comment by liuzhe-lz** [comment]
Removed hyperopt from required dependency.
