### ISSUE TITLE
Dedicated command and viewer to browse all experiments

### ISSUE THREAD

**Issue by ksachdeva** [microsoft/nni#1629]
**What would you like to be added**:

At present the process to look at the results of old experiments is bit tedious. It would be good to have the webui present an interface that allows one to browse old experiments. Click on an experiment and see what happened (readonly mode). 

**Why is this needed**:

Browsing and managing old experiments are tedious and not very friendly. 

**Without this feature, how does current nni work**：

- First list the experiments
- Second figure out the experiment name by going in all experiments
- Finally,iIssue nnictl view command to start a server to see the results of that experiment 

**Components that may involve changes**:

**Brief description of your proposal if any**:

The command nnictl view could be used to start a UI that let's you browse all past experiments in readonly mode.

**Comment by ultmaster** [comment]
In NNI 1.1, there will be a `nnictl view` command to launch a WebUI to see an old experiment. Maybe that's what you need.

**Comment by scarlett2018** [comment]
@ksachdeva let us know if the nnictl view does not fit your need.
