### ISSUE TITLE
scikit-nni - A helper tool to tune parameters of scikit-learn pipelines (for classification) using NNI

### ISSUE THREAD

**Issue by ksachdeva** [microsoft/nni#1633]
Hi,

This is not an issue. 

First, thanks for this awesome tool. Really great work. I played with it for last 2 days and it works really well.

I was tuning some classification algorithms and end up creating a generic tool and package that I call scikit-nni. 

Please find the repository here - https://github.com/ksachdeva/scikit-nni. 

It essentially generates the NNI configuration files and also has a generic scikit pipeline builder that takes the specification (from YAML file). This way users of NNI do not have to write the code for the scikit pipelines. I have multiple examples and a decemt documentation in the repository. 

Would appreciate any feedback you may have.

Thanks again for NNI. 

Regards
Kapil

**Comment by xuehui1991** [comment]
Hello @ksachdeva  This work is interesting! It's a good example of using NNI to build a tool~

**Comment by QuanluZhang** [comment]
@ksachdeva thanks for your work, we will add a reference to your repo soon.

**Comment by ksachdeva** [comment]
Hi @QuanluZhang , I also wrote an article about Microsoft NNI and it got published few hours ago. 

Title- Find thy hyper-parameters for scikit-learn pipelines using Microsoft NNI

Here is the link to the post - 

https://towardsdatascience.com/find-thy-hyper-parameters-for-scikit-learn-pipelines-using-microsoft-nni-f1015b1224c1

Here is the friend link to the post to avoid the membership limitations of medium -

https://medium.com/p/find-thy-hyper-parameters-for-scikit-learn-pipelines-using-microsoft-nni-f1015b1224c1?source=email-d95181aaafe2--writer.postDistributed&sk=b894354f22ea47cc9c1e9605d131ce82

Thanks for your great work with Microsoft NNI.

Regards
Kapil

**Comment by QuanluZhang** [comment]
@ksachdeva thanks again for your contribution, we have reference the repo and article in pr #1754.
