### ISSUE TITLE
new pylint rules plan

### ISSUE THREAD

**Issue by leckie-chn** [microsoft/nni#1638]
reference: [Pylint Documentation](https://buildmedia.readthedocs.org/media/pdf/pylint/latest/pylint.pdf)

* On CI pipeline, by default enable all Error(E), Fatal(F) check, along with the following rules:
          **W0614, C0326, W0611, C0330, C0411, C0303, W1201, C0301, W0612, W0401, W0235, C1801, W1202, W0622, W1505**
* **C0111** will be enabled later
* **E1101, R0912, W0212** will not be enforced on pipeline, but recommend contributors comply their coding style to these rules.

**Comment by leckie-chn** [comment]
related PR: https://github.com/microsoft/nni/pull/1643

**Comment by liuzhe-lz** [comment]
Done in PR #1697
