### ISSUE TITLE
Need Contributing.md for future contributors 

### ISSUE THREAD

**Issue by vipulgupta2048** [Microsoft/nni#164]
Hey, I was going through #114 and trying to solve it and writing code for it. But later realized that the repository has no CONTRIBUTING document, should I go ahead and make a starter one. You guys could suggest any changes that you want in it. This would really help future contributors for reference when they need it.

**Comment by scarlett2018** [comment]
Thanks @vipulgupta2048 , the majority of the team are on public holiday, it will be great help if you start one draft and we discuss based on that. And another thanks is for contributing to #114, that is also appreciated =).

**Comment by vipulgupta2048** [comment]
Roger that. I will draft one up. 
Ps. You guys have a good one.

**Comment by vipulgupta2048** [comment]
Closed #164 by #165
