### ISSUE TITLE
Temporary dir for gpu collection is not always unique among users

### ISSUE THREAD

**Issue by Markus92** [microsoft/nni#1665]
**Short summary about the issue/question**:
When running NNI, it puts the gpu metrics collector in /tmp/nni/script, which is not unique among users. So two people cannot run NNI simultaneously (for example on different GPU).

**Brief what process you are following**: 
User 1: runs NNI fine
User 2: runs NNI on different port, but it'll give status error: "Training service error: EACCES: permission denied, open '/tmp/nni/script/gpu_metrics_collector.sh'"

**How to reproduce it**: 
See above

**nni Environment**:
- nni version: 1.0 (but also present in HEAD)
- nni mode(local|pai|remote): local
- OS: Ubuntu 18.04LTS
- python version: 3.6
- is conda or virtualenv used?:  Yes (conda)
- is running in docker?: We run it in Singularity (github.com/sylabs/singularity/), with mounted /tmp as our containers itself are read-only. Redefining /tmp is not an option unfortunately (breaks too many other things it seems). Our containers are self-made from a ubuntu base, with conda, then `pip install nni`

**need to update document(yes/no)**:
Maybe

**Anything else we need to know**:
Bug can be traced to line 435 - 437 of /src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
Clearly `path.basename(os.homedir());` doesn't expand to username in our configuration, even though os.homedir() should work in our containers (homedir is mounted).

A solution would be to use either (/var)/run/user/$PID/, create a /tmp/$PID/ or add a random nonce to the path (for example trial id). Another solution would be allowing to specify your own temporary dir. Upstream at nodejs there might also be a fix possible to use the temporary dir supplied by systemd.

**Comment by QuanluZhang** [comment]
fixed, close.
