### ISSUE TITLE
Tuners should have precondition check

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#1667]
Tuners should throw error in case of invalid search space, such as: `{"_type": "randint", "_value": [1, 2, 3]}`, or `{"_type": "randint", "_value": [0.5, 1.5]}`.

**Comment by chicm-ms** [comment]
@ultmaster What is current Tuners behaviour in case of invalid search space?

**Comment by ultmaster** [comment]
Sometimes they get processed as is. Sometimes tuners fail. Tuners' behaviors are undefined.

**Comment by scarlett2018** [comment]
Assign to @QuanluZhang for further triage.
