### ISSUE TITLE
Redesign SDK hierarchy

### ISSUE THREAD

**Issue by liuzhe-lz** [microsoft/nni#1668]
The current hierarchy of Python SDK is very free-style. For example compressors are grouped in "compression" folder while tuners are placed at top-level directory. Also it's verbose to import some classes like `nni.tuner.Tuner` or even `nni.curvefitting_assessor.curvefitting_assessor.CurvefittingAssessor`.
We should redesign both Python package structure and source files' organization.

**Comment by scarlett2018** [comment]
Assign to @liuzhe-lz to drive the design and discussion first.

**Comment by liuzhe-lz** [comment]
Refactor started in issue #2889
