### ISSUE TITLE
train on linux ,then view the result through webui on windows10

### ISSUE THREAD

**Issue by wshzd** [microsoft/nni#1673]
recently l carry out examples\trials\mnist on linux GPU,the result is normal and is also right on linux,but l want to view the training process through webui on windows10.l use the command: ssh -p <remote_port> -L 8888:127.0.0.1:8888 <username>@<remote_ip>,when l login in 127.0.0.1:8888 on windows,unexpectedly,l get the message that  our access is refused  by 127.0.0.1, that is why?

l have another example that l run my NER project in the same manner, the status is always INITIALIZED for several hours,do you tell me the reason? As a result,
l can login the website of Neural Network Intelligence on windows,  there is the head of the webui , however, the context of webui is empty,that is why as well?

**Comment by wshzd** [comment]
of course, l know NNI's default port is 8080,but it is what you want only to reseted again by the command -p or --port, this is not important

**Comment by wshzd** [comment]
is anyone successful about training  models on linux even mnist?

**Comment by chicm-ms** [comment]
@wshzd   Probably you want to firstly check your network and ssh forwarding configuration using other simple program such as `python -m http.server`,   then double check the webui  URL from nnictl command output.

**Comment by Markus92** [comment]
@wshzd yes, our lab does it all the time though we don't use port forwarding (nni listens on external ip by default so we just access server/port directly).

**Comment by wshzd** [comment]
@Markus92 yes ,access server/port directly, a blog confuse me, thank you very much.
