### ISSUE TITLE
nnictl tensorboard start failed!

### ISSUE THREAD

**Issue by Steffy-zxf** [microsoft/nni#1677]
I tried the mnist experiment as demo provided. The webui was started successful as followed:
![image](https://user-images.githubusercontent.com/48793257/67917323-9f40b500-fbd3-11e9-8aed-78ec40fc9a77.png)
But, I wanna view the visualization by the nnctl tensorboard command!
The info is that the process was started successfully!
![image](https://user-images.githubusercontent.com/48793257/67917556-4887ab00-fbd4-11e9-9813-69ec52b9e083.png)
But I try to access the url unavailably.
![image](https://user-images.githubusercontent.com/48793257/67917624-8ab0ec80-fbd4-11e9-87a1-f90eb2887c83.png)

**Comment by SparkSnail** [comment]
NNI use `tensorboard --logdir {log path} --port {port}` command to start the tensorboard process. Could you please use the command in your own terminal to check if  `tensorboard`  could work normally in your machine? the {log path} is show in NNI's `INFO` information.

**Comment by Steffy-zxf** [comment]
I try the command tensorboad for other programs not nni. It works on my computer. But it still doesn't work via the comand nnictl tensorboard.

**Comment by SparkSnail** [comment]
Hi @Steffy-zxf , could you please try if your data used in tensorboard is under the path listed in nnictl? Could you please offer the log content in `/tmp/nni/{experimentId}/tensorboard_stdout` and `/tmp/nni/{experimentId}/tensorboard_stderr`?

**Comment by scarlett2018** [comment]
Hi @Steffy-zxf , had you got a chance try what @SparkSnail suggest? would you mind to update it here? thanks.

> Hi @Steffy-zxf , could you please try if your data used in tensorboard is under the path listed in nnictl? Could you please offer the log content in `/tmp/nni/{experimentId}/tensorboard_stdout` and `/tmp/nni/{experimentId}/tensorboard_stderr`?

**Comment by kvartet** [comment]
I’m closing this issue as it has no updates from customer for 3 months, please feel free to reopen if you are still seeing it an active issue.
