### ISSUE TITLE
Run experiment without web server

### ISSUE THREAD

**Issue by YiChunHung** [microsoft/nni#1689]
**What would you like to be added**:
Support running experiment without actually launch web server/ui.

**Why is this needed**:
As the normal user in the shared resource, it is usually that normal users have no auth to open a specific port.

**Without this feature, how does current nni work**：
As the doc mentions, nni would create a web server to control the experiment. 

**Components that may involve changes**:
nni web server

**Brief description of your proposal if any**:
nni can probably just log down the necessary information, such as metric lists and intermediate result. After that, the user can download the log files to the local laptop for the visualization.

**Comment by SparkSnail** [comment]
Hi, in remote/pai/kubeflow mode, NNI need another port to accept metric data from trail_keeper, so if we support this kind of running mode, NNI may need a lot of refactor change, it might be a big effort. As we discussed internal, we may not support this feature. If you have another good suggestion, please feel free to give feedback. Thanks!

**Comment by scarlett2018** [comment]
reopen, as I'm thinking whether we can save the key results info in a JSON or HTML format just for browsing. open to discussion.
