### ISSUE TITLE
What happens with the experiments if there is not enough GPU memory?

### ISSUE THREAD

**Issue by martsalz** [microsoft/nni#1699]
**Short summary about the issue/question**:

I get the impression that if there is not enough GPU memory available, sometimes experiments are put in a "queue" and executed later, and sometimes experiments are aborted - how exactly does NNI react in this situation?

![image](https://user-images.githubusercontent.com/12211578/68102925-1d070800-fed5-11e9-8afd-87f3059fc5fc.png)

**Comment by chicm-ms** [comment]
NNI training services schedule trial jobs base on number of GPUs / number of trials per GPU configuration, no GPU memory is used in current job scheduliing.  Users need to ensure the trial jobs can run with the GPU configuration they specify.

**Comment by martsalz** [comment]
> Users need to ensure the trial jobs can run with the GPU configuration they specify.

What do you mean by that and how does NNI react if this is not considered?

**Comment by chicm-ms** [comment]
For example, I have 4 GPUs (16GB memory for each GPU) on my system,  each trial jobs consumes 7GB GPU Memory, then I will set:
```
trialConcurrency: 8
localConfig:
  maxTrialNumPerGpu: 2
```

If my trial jobs consumes 17GB Memory, I know that this trial job can not run on this system. I must know the GPU Memory usage of my trial jobs before running NNI, then I can configure GPU settings properly.
