### ISSUE TITLE
Where can I change nni_output_dir?

### ISSUE THREAD

**Issue by Kongyj** [microsoft/nni#1717]
**Short summary about the issue/question**: I want to change the output dir but I don't know where and how to change.

**Brief what process you are following**: 

I found some code in the nni_trial_tools/constant.py:
HOME_DIR = os.path.join(os.environ['HOME'], 'nni')
LOG_DIR = os.environ['NNI_OUTPUT_DIR']
and I changed HOME_DIR with  HOME_DIR = os.path.join("D:/coding",  'nni') but the outputdir didn't change and I did't find where to change os.environ['NNI_OUTPUT_DIR']. I just want to change the HOME_DIR. For example, changing the outputdir from HOME/nni/experiments/Output_messeage to My_path/nni/experiments/Output_messeage. 
Thanks.

How to reproduce it: change the HOME_DIR = os.path.join(os.environ['HOME'], 'nni') in nni_trial_tools/constant.py but the outputdir does't change.

**nni Environment**:
- nni version:1.1
- nni mode(local|pai|remote): local
- OS:windows 10
- python version: 3.6
- is conda or virtualenv used?: 
- is running in docker?: no

**need to update document(yes/no)**: 

**Anything else we need to know**:

**Comment by liuzhe-lz** [comment]
Have you tried setting `$env:NNI_OUTPUT_DIR="YOUR_PATH"` in powershell?
I'm not familiar with the Windows part.
@SparkSnail

**Comment by scarlett2018** [comment]
@Cjkkkk to follow up.

**Comment by SparkSnail** [comment]
Hi @Kongyj, if you want to run NNI on local mode of windows OS, you will not use `nni_trial_tools/constant.py` file. Do you mean that you want to change the log output path of NNI? You could set `logDir` in you config file. [refer](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#configuration-spec)

**Comment by Kongyj** [comment]
> Hi @Kongyj, if you want to run NNI on local mode of windows OS, you will not use `nni_trial_tools/constant.py` file. Do you mean that you want to change the log output path of NNI? You could set `logDir` in you config file. [refer](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#configuration-spec)

Thank you. It's useful.

**Comment by scarlett2018** [comment]
> > Hi @Kongyj, if you want to run NNI on local mode of windows OS, you will not use `nni_trial_tools/constant.py` file. Do you mean that you want to change the log output path of NNI? You could set `logDir` in you config file. [refer](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#configuration-spec)
> 
> Thank you. It's useful.

@Kongyj - seems the question is addressed, I'm closing the issue for now. feel free to reopen if there are still problems with it.
