### ISSUE TITLE
show warning and error messages on webui through notification popup

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#1724]
**What would you like to be added**: show warning and error messages on webui through notification popup

**Why is this needed**: more friendly and timely show warnings and errors to users

**Without this feature, how does current nni work**：users need view the full log of nnimanager.log and dispatcher.log from the top row `Download` on webui.

**Comment by kvartet** [comment]
@Lijiaoa - would you mind checking whether this feature had been supported in the latest version of NNI? If it it, I will close this issue. Thank you~

**Comment by Lijiaoa** [comment]
@kvartet This issue had been fixed on `v1.6` look like this [picture:](https://user-images.githubusercontent.com/61399850/76919459-f685be80-6903-11ea-9cb5-0ca6a5dd75d3.png) , so could close this issue.
