### ISSUE TITLE
GPU utilizations monitoring in remote experiments

### ISSUE THREAD

**Issue by apatsekin** [microsoft/nni#1733]
**Short summary about the issue/question**: currently `gpu_metrics_collector.sh` collects GPU utilization data for each available GPU to figure out if on this node a trial can be run. However, if nni is run in Docker container, it doesn't see external processes that may occupy GPUs. Solution to that might be monitoring memory utilization of GPUs as well, when you can set in configuration required memory size for a model per GPU in megabytes. i.e. `gpuMemSize: 6000`. This parameter is visible inside any container through `nvidia-smi`.

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
@apatsekin - the scenario is valid, but currently NNI would like to focus more on the API for parameter selection and architecture search, and leverage OpenPAI or Kubeflow alike platform to handle the GPU scheduling and utilization. hope it makes senses to you.
