### ISSUE TITLE
Feature request: UNKNOWN state - ability to cancel trial

### ISSUE THREAD

**Issue by apatsekin** [microsoft/nni#1735]
In remote experiment, when one of the nodes by any chance goes off, there is no way to recover from that state. In webUI this trial just goes in "UNKNOWN" state and that's it. You can't cancel current trial and let it start new one when machine is back online. Especially when it's docker, and node doesn't even have trial src in /tmp folder anymore.

Feature request: enable "cancel" action for `UNKNOWN` trial state, which disregards current trial and tries to start new one.

Thanks!

**Comment by liuzhe-lz** [comment]
Plan to be implemented in v1.3 release.

**Comment by scarlett2018** [comment]
released the feature in 1.4, welcome to try it out and feedback, thanks.
