### ISSUE TITLE
Potential typo in sklearn example

### ISSUE THREAD

**Issue by jimbojumbo** [microsoft/nni#1750]
**There is a potential typo in the sklearn trail example**:

I was looking at the example provided to run the sklearn trail, and I noticed in the 'main.py' file,  the 'run' function takes PARAM as one of the input, should it be model instead? 

```python
def run(X_train, X_test, y_train, y_test, PARAMS):
    '''Train model and predict result'''
    model.fit(X_train, y_train)
    predict_y = model.predict(X_test)
    score = r2_score(y_test, predict_y)
    LOG.debug('r2 score: %s' % score)
    nni.report_final_result(score)

# When executing
run(X_train, X_test, y_train, y_test, model)
```

Maybe I understand something wrong here, any clarification would be appreciated?

Thanks and great work!

**Comment by QuanluZhang** [comment]
fixed, and closed
