### ISSUE TITLE
cannot sort by Default metric in the Trial jobs tab

### ISSUE THREAD

**Issue by kepsail** [microsoft/nni#1764]
In the Trial jobs tab, when I click the (sort by) Default metric button, the results are always sorted by the column Trial No.

**Comment by kepsail** [comment]
In Edge, the results are actually sorted by Trial No.
In Chrome, the results are confused.

**Comment by lvybriage** [comment]
@kepsail Thanks for reporting this bug. I'll fix it soon.

**Comment by lvybriage** [comment]
> In Edge, the results are actually sorted by Trial No.
> In Chrome, the results are confused.

The results are not sorted by `Trial No.` when you sorted by `default metric` column. Because webui sorted `default metric` column by trial's final metric but some trial hadn't final metric. It caused the confuse. I'll sort `default metric` by `final/Iatest intermediate` metric.
