### ISSUE TITLE
Can the server push the result to web ui using websocket rather than frequently request from frontend

### ISSUE THREAD

**Issue by joshua-xia** [microsoft/nni#1801]
**What would you like to be added**:

push the result to web ui using websocket

**Why is this needed**:

frontend need not frequently request data from server and the information update/refresh in time

**Without this feature, how does current nni work**：

current nni  request data from server frequently even the data not updated

**Components that may involve changes**:

 server and frontend

**Brief description of your proposal if any**:
 server and frontend add websocket pub/sub

**Comment by liuzhe-lz** [comment]
By default NNI web UI only raises two requests per 10 seconds. So I think HTTP protocol overhead is not the bottleneck.
I do agree that incremental loading can potentially improve the performance, but it may need some huge refactor and is therefore unlikely to happen in near releases.

**Comment by scarlett2018** [comment]
> **What would you like to be added**:
> 
> push the result to web ui using websocket
> 
> **Why is this needed**:
> 
> frontend need not frequently request data from server and the information update/refresh in time
> 
> **Without this feature, how does current nni work**：
> 
> current nni request data from server frequently even the data not updated
> 
> **Components that may involve changes**:
> 
> server and frontend
> 
> **Brief description of your proposal if any**:
> server and frontend add websocket pub/sub

Would you like to con

> By default NNI web UI only raises two requests per 10 seconds. So I think HTTP protocol overhead is not the bottleneck.
> I do agree that incremental loading can potentially improve the performance, but it may need some huge refactor and is therefore unlikely to happen in near releases.

@joshua-xia would you like to submit PR and contribute to this change?
