### ISSUE TITLE
Confuse about windows doc.

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1802]
**Short summary about the issue/question**:
Can we run nni manager in one windows machine and remote trials to other windows machines?
The [doc](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/NniOnWindows.md) only mention "Currently we support local, remote and pai mode on Windows. Windows 10.1809 is well tested and recommended." which confuse me.

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
https://github.com/microsoft/nni/pull/1901

**Comment by scarlett2018** [comment]
fixed in another PR.
