### ISSUE TITLE
Strange param search field while using Annotation mode

### ISSUE THREAD

**Issue by BaySalt** [microsoft/nni#1812]
Environment :  tf-GPU == 1.8.0 on python 3.6 on Ubuntu with virtualenv
i was trying to create a nni experiment with Annotation mode , and files are like this:

>./run.py
>./models/model_A.py
>./models/model_B.py

firstly i did these :
>add 'import models.model_A as model'  in ./run.py
>add '@nni.variable(nni.choice(1,2,3), name=param_A)'' in ./models/model_A.py

then i opened an experiment , and it looks fine on Web Watcher , nni begins to search models/model_A/param_A  in [1,2,3] as expected

later i did these:
>change 'import models.model_A as model'  to  'import models.model_B as model'  in ./run.py
>add '@nni.variable(nni.choice(4,5,6), name=param_B)'' to ./models/model_B.py

then i opened an experiment , but on Web Watcher nni begins to search both models/model_A/param_A  in [1,2,3]  , bur  models/model_B/param_B  in [4,5,6] as well

this confused me a lot and the same issue accures when i put files like:
>./run.py
>./models/backup_folder/model_A.py
>./models/model_B.py

or

>./run.py
>./models/model_A.py
>./model_B.py

it seems when i opened an experiment , nni will search Annotation usage in every file under the root folder but not only files the python proj. actually uses

please kindly let me know how i can solve or avoid this or what i may ignored , very thanks !

**Comment by QuanluZhang** [comment]
@BaySalt thanks for reporting this. This is a known issue. NNI will extract annotation lines from all the .py files under codeDir. One workaround is move `model_B.py` out of codeDir when using `model_A.py`. Another workaround is remove suffix `.py` of `model_B.py` when using `model_A.py`.

We have not supported only parsing used py files, the current behavior is parsing all the py files under codeDir. We will find a more user friendly solution for this issue.

**Comment by BaySalt** [comment]
> @BaySalt thanks for reporting this. This is a known issue. NNI will extract annotation lines from all the .py files under codeDir. One workaround is move `model_B.py` out of codeDir when using `model_A.py`. Another workaround is remove suffix `.py` of `model_B.py` when using `model_A.py`.
> 
> We have not supported only parsing used py files, the current behavior is parsing all the py files under codeDir. We will find a more user friendly solution for this issue.

Thanks for your reply !
Currently i avoid this by copying minimized project-files to another folder path,
Looking forward to your further Annotation Update :P
