### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by nwb5233** [microsoft/nni#1816]
Job management error: getIPV4Address() failed because os.networkInterfaces().eth0 is undefined.

**Comment by chicm-ms** [comment]
This is a known issue, reference: https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/FAQ.md

**Comment by chicm-ms** [comment]
Closing the issue, @nwb5233  you can reopen this if you still having the problem after looking through the documents.
