### ISSUE TITLE
Suggestion: Allow gpuNum: 0 to be run on kubernetes

### ISSUE THREAD

**Issue by skyser2003** [microsoft/nni#1818]
**What would you like to be added**:
gpuNum: 0 to be possible on k8s/kubeflow

**Why is this needed**:
For CPU training or for other reasons,
sometimes no gpu containers is needed.

**Without this feature, how does current nni work**：
Always requires at least one nvidia.com/gpu resource.

**Components that may involve changes**:

**Brief description of your proposal if any**:

Hello, I am currently using nni to tune some TF models.
While using nni, I sometimes need zero gpu containers(CPU training, logging, etc).

So I looked the sources, and found this comment in kubernetesTrainingService.ts file.
```
// Nvidia devcie plugin for K8S has a known issue that requesting zero GPUs allocates all GPUs
// Refer https://github.com/NVIDIA/k8s-device-plugin/issues/61
// So we have to explicitly set CUDA_VISIBLE_DEVICES to empty if user sets gpuNum to 0 in NNI config file
```

The nvidia issue hasn't been fixed yet, but there can be a workaround this issue.
That is, if container requests "nvidia.com/gpu: 0" and env variable CUDA_VISIBLE_DEVICES is set to empty string, it can essentially function as zero gpu using container.

Below is pseudo-diff of how the source can be changed to function.

```
// nni_manager/training_service/kubernetes/kubernetesTrainingService.ts

// From
public generatePodResource(memory: number, cpuNum: number, gpuNum: number): any {
    return {
        memory: `${memory}Mi`,
        cpu: `${cpuNum}`,
        'nvidia.com/gpu': `${gpuNum}`
    };
}

// To
public generatePodResource(memory: number, cpuNum: number, gpuNum: number): any {
    const resources = {
        memory: `${memory}Mi`,
        cpu: `${cpuNum}`,
        'nvidia.com/gpu': `${gpuNum}`
    };

    if (gpuNum !== 0) {
        resources['nvidia.com/gpu'] = gpuNum;
    }

    return resources;
}


// From
if (gpuNum === 0) {
    nvidiaScript = `export CUDA_VISIBLE_DEVICES='0'`;
}

// To
if (gpuNum === 0) {
    nvidiaScript = 'export CUDA_VISIBLE_DEVICES=';
}```

**Comment by SparkSnail** [comment]
Hi @skyser2003 ,
    Thanks for raising the issue. In current design, NNI support setting gpuNum=0 by using `export CUDA_VISIBLE_DEVICES='0'`  command to shield gpu in kubeflow, at the same time, NNI will use 
```
    return {
        memory: `${memory}Mi`,
        cpu: `${cpuNum}`,
        'nvidia.com/gpu': `${gpuNum}`
    };
```
to set `'nvidia.com/gpu': `${gpuNum}``, which `${gpuNum}` could be 0.
I didn't get the point by changing code to 
```
public generatePodResource(memory: number, cpuNum: number, gpuNum: number): any {
    const resources = {
        memory: `${memory}Mi`,
        cpu: `${cpuNum}`,
        'nvidia.com/gpu': `${gpuNum}`
    };

    if (gpuNum !== 0) {
        resources['nvidia.com/gpu'] = gpuNum;
    }

    return resources;
}
```
Do you mean that if you set gpuNum=0 in NNI config, it does not work?

**Comment by skyser2003** [comment]
Yes, because of 

```if (gpuNum === 0) {
    nvidiaScript = `export CUDA_VISIBLE_DEVICES='0'`;
}```

this part, even if I set gpuNum:0,
it always uses gpu with index 0 inside the container.
This happens on v0.7.

**Comment by SparkSnail** [comment]
It seems that `CUDA_VISIBLE_DEVICES='0'` does not work on your k8s,  this might be a bug of NNI. Have you tried changing the source code to `export CUDA_VISIBLE_DEVICES=''` or `export CUDA_VISIBLE_DEVICES='-1'`, and use `source install.sh` to test?

**Comment by skyser2003** [comment]
Tested CUDA_VISIBLE_DEVICES='', it works fine.

As long as I know, CUDA_VISIBLE_DEVICES is used to set index of gpus you want to use, not the number of gpus.

So if the above code is intended to use 0 gpus inside the container, I think it is wrongly used.

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on

**Comment by SparkSnail** [comment]
It seems so. I'll fix it ASAP, or if you are interested in NNI, it will be great if you can give a pr to fix this bug. 
Thanks for giving the feedback.
