### ISSUE TITLE
DocError: some details of document needs be updated.

### ISSUE THREAD

**Issue by wrzzd** [microsoft/nni#1884]
**Short summary about the issue/question**:
some details of document needs be updated.

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:
yes
**Anything else we need to know**:
Some details of document,  at 'https://github.com/microsoft/nni/blob/master/docs/en_US/Compressor/Quantizer.md', maybe old which needs be updated: 
like: nni.compressors.torch.NaiveQuantizer(model).compress()
should be updated by: nni.compression.torch.NaiveQuantizer(model).compress()

thx.

**Comment by scarlett2018** [comment]
Adding @Cjkkkk to validate and update accordingly

**Comment by Cjkkkk** [comment]
Thank you for bringing up this issue. The doc has been updated accordingly in PR #1881
