### ISSUE TITLE
Web UI Imrpovement 

### ISSUE THREAD

**Issue by yangou1988** [microsoft/nni#1908]
**1. Top Navigation**  @lvybriage 

- [x] Change the name 'View' to 'Download'
- [x] Too many buttons on the right side of top navigation, let's keep the 'Auto-refresh'  and 'Download' and then combine 'Feedback', 'Help', and 'Version' into a drop-down 'About'  
- [x] Change the name 'Experiment Parameters' to 'Experiment  Summary'
- [x] Merge the two buttons 'NNImanager Logfile' and 'Dispatcher Logfile' to one 'Logfiles'

![image](https://user-images.githubusercontent.com/44491713/71610554-00cdd180-2bcd-11ea-9321-796216f346a2.png)

**2. Overview - Status** @lvybriage 

- [ ] Need a tooltip with a sentence: " **TrialConcurrency is the number of trials running concurrently, which is the number of GPUs you want to use if you are setting gpuNum to 1.**" on 'Concurrency' to introduce what is Concurrency for. 

**3. Overview - Profile** @lvybriage 

- [x] - Rename 'Profile' to 'Config' 
- [ ] - Convert the format of JSON to Yaml 

**4. Overview - Search space** @lvybriage 

- [ ] ~blank space bug~

**5. Trials detail -Default metric**

- [ ] Change the name 'Optimization curve' to 'Search progress curve' (TBD)
- [ ] Add a description under the button @scarlett2018 @lvybriage

 

**6. Trials detail -Hyper-parameter** (Replace the Echarts)

**7. Trial Duration** @lvybriage #1489 

- [ ] To show more detail information like trial no., trial ID, and time in the Tooltip ，Sample: Trial no. 9, Trial ID:ogiNQ, Time 30.601s, 
- [x] Add title like Trial No. on Y-axis, and add time unit (s, min or h) on X-axis

**8. Intermediate result** @ultmaster will prepare a new plan for Intermedia result chart
	
**9. Trial jobs** 
- [ ] User don't know how to use 'Search by parameters' and highlight the search result   @lvybriage @yangou1988
- [x] Redesign the button 'Parameters' and  'Log' for users more obviously to click @yangou1988

**Comment by lvybriage** [comment]
Merge the two buttons 'NNImanager Logfile' and 'Dispatcher Logfile' to one 'Logfiles'
question: when user click the "Disable auto refresh", what's the title change?

**Comment by yangou1988** [comment]
@lvybriage question: when user click the "Disable auto-refresh", what's the title change?

![image](https://user-images.githubusercontent.com/44491713/71651432-58e50f00-2d58-11ea-8388-7ee138f9e152.png)

**Comment by lvybriage** [comment]
2. Overview - Status @lvybriage
where to put this sentence?
 ` Need a tooltip with a sentence: " TrialConcurrency is the number of trials running concurrently, which is the number of GPUs you want to use if you are setting gpuNum to 1." on 'Concurrency' to introduce what is Concurrency for.`
3. Overview - Profile @lvybriage 
  - Convert the format of JSON to Yaml
4. Overview - Search space @lvybriage 
  blank space bug
5. Trials detail -Default metric

  Change the name 'Optimization curve' to 'Search progress curve' (TBD)
  Add a description under the button @scarlett2018 @lvybriage
6. Trials detail -Hyper-parameter (Replace the Echarts)

7. Trial Duration @lvybriage #1489

  To show more detail information like trial no., trial ID, and time in the Tooltip ，Sample: Trial no. 9, Trial ID:ogiNQ, Time 30.601s,
  Add title like Trial No. on Y-axis, and add time unit (s, min or h) on X-axis
8. Intermediate result @ultmaster will prepare a new plan for Intermedia result chart

9. Trial jobs
User don't know how to use 'Search by parameters' @lvybriage @yangou1988

**Comment by scarlett2018** [comment]
@yangou1988 @lvybriage - are we done with the issue? anything left here?

**Comment by yangou1988** [comment]
@scarlett2018  Not yet. Just checked with @lvybriage today. 6 more items left to do.

**Comment by scarlett2018** [comment]
> @scarlett2018 Not yet. Just checked with @lvybriage today. 6 more items left to do.

May you two move the left work into a new ticket and close this one? thanks.

**Comment by yangou1988** [comment]
> > @scarlett2018 Not yet. Just checked with @lvybriage today. 6 more items left to do.
> 
> May you two move the left work into a new ticket and close this one? thanks.

Ok.
