### ISSUE TITLE
WebUI is broken when final result's type is tensor

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#1918]
**Short summary about the issue/question**:
```
"finalMetricData":[
            {
                "data":"{\"__instance_type__\":[\"torch\",\"Tensor\"],\"attributes\":{}}",
                "parameterId":"3",
                "sequence":0,
                "timestamp":1578029488459,
                "trialJobId":"t9wYQ",
                "type":"FINAL"
            }
        ],
```

![image](https://user-images.githubusercontent.com/35484733/71709184-b187db00-2e30-11ea-817e-3f9a3c272877.png)

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by lvybriage** [comment]
WebUI doesn't support the final result's type is `tensor` at present. Please return the final result type as `{default: string}` or `{default: dict}`.

**Comment by scarlett2018** [comment]
> WebUI doesn't support the final result's type is `tensor` at present. Please return the final result type as `{default: string}` or `{default: dict}`.
> 
> And the broken page by final tensor type we'll fix soon.

@lvybriage - any work left for this issue? may we close it now?
