### ISSUE TITLE
为什么模型压缩后的占用空间没有减小？

### ISSUE THREAD

**Issue by 205418367** [microsoft/nni#1927]
我执行main_torch_pruner.py这个脚本，发现模型压缩前后没有什么变化

**Comment by QuanluZhang** [comment]
hi @205418367 , please refer to issue #1846 . This is a feature that will be included in release v1.4. You can refer to #1900 for the release plan.

**Comment by scarlett2018** [comment]
Added to #1900 so that we can revisit this issue when it is resolved.

**Comment by StephenLee2016** [comment]
> Added to #1900 so that we can revisit this issue when it is resolved.

你好，什么时候可以支持将压缩后的模型导出呢？

**Comment by QuanluZhang** [comment]
@StephenLee2016  , it will be included in v1.4, https://github.com/microsoft/nni/issues/1900

**Comment by QuanluZhang** [comment]
@StephenLee2016 @205418367 model speedup has been supported in v1.4, please refer to [this doc](https://nni.readthedocs.io/en/latest/Compressor/ModelSpeedup.html) and [this example](https://github.com/microsoft/nni/blob/master/examples/model_compress/model_speedup.py). Note that it is still in an Alpha version
