### ISSUE TITLE
does sklearn algorithm can run in distributed machine?

### ISSUE THREAD

**Issue by monkeyshichi** [microsoft/nni#1930]
**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by SparkSnail** [comment]
Hi @monkeyshichi , for `sklearn` algorithm, do you mean NNI's tuner algorithm? 
NNI support kubeflow/FrameworkController TrainingService, which support distributed training mode ,or you could use remote machine to run multiple trial jobs. 
For tuner algorithm, NNI only support running in single machine.

**Comment by monkeyshichi** [comment]
@SparkSnail  i mean those algorithm implemented in sklearn,like svc,logistic regreesion etc.

**Comment by SparkSnail** [comment]
@monkeyshichi sorry, I'm not sure about the sklearn implementation.

**Comment by monkeyshichi** [comment]
@SparkSnail . I want to speed up sklearn algorithm run  in distributed machines with nni .Thank you anyway.

**Comment by xuehui1991** [comment]
@monkeyshichi  I don't think NNI could support that.
