### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by Chen-Hongji** [microsoft/nni#1931]
**nni Environment**:
- nni version: 1.0
- nni mode(local|pai|remote): remote
- OS: ubuntu16.04
- python version: 3.6
- is conda or virtualenv used?:  no
- is running in docker?: no

I run nni in an environment without graphics, and I get ERROR when running. Because there is no start trial, there is no information under / tmp / nni. At the same time, I have no condition to access the web with a browser, I cannot get web error information, I cannot locate the bug, what methods can I use to debug？

It can be confirmed that the master and slave nodes have established a connection, because the slave's / tmp / nni has a corresponding Experiment directory, but the use case is not running, so the / tmp / nni / Experiment is empty.

![2020-01-07 15-51-18屏幕截图](https://user-images.githubusercontent.com/48662199/71879365-e6fe3280-3168-11ea-8822-5e515fac6995.png)

**config.yml**
`authorName: default
experimentName: example_cifar10-network-morphism-test
trialConcurrency: 2
maxExecDuration: 24h
maxTrialNum: 6000
trainingServicePlatform: remote
nniManagerIp: 89.72.32.34
useAnnotation: false
tuner:
  builtinTunerName: NetworkMorphism
  classArgs:
    optimize_mode: maximize
    task: cv
    input_width: 32
    input_channel: 3
    n_output_node: 10
trial:
  command: python3 cifar10_pytorch.py
  codeDir: .
  gpuNum: 1
machineList:
  - ip: 89.72.32.24
    port: 22
    username: chj
    sshKeyPath: /home/chj/.ssh/id_rsa
`

**Comment by SparkSnail** [comment]
Hi @Chen-Hongji , there is a [doc](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md) to introduce debug method in NNI.
You could also use `nnictl log stderr` command to get the stderr information from restserver, and use `nnictl log trial` command to get the logPath of trial jobs. In the logPath, you could get the error information for every trial job. You could find also `nniManager.log` and `dispatcher.log` file in `~/nni/experiments/{expId}/log` folder, these two files contains more log information.

**Comment by Chen-Hongji** [comment]
thank you very much @SparkSnail
