### ISSUE TITLE
Question: How to config NNI run on Spark ?

### ISSUE THREAD

**Issue by kala-Chen** [microsoft/nni#1937]
I read the document(https://github.com/microsoft/nni/tree/master/docs/zh_CN/TrainingService), But can not found how to config NNI run On Spark(Example Run XGB On Spark). Is it support now?

**Comment by SparkSnail** [comment]
Hi @kala-Chen, NNI support running on local machine, remote machine, kubernetes and OpenPAI platform, does support running on Spark platform.

**Comment by kala-Chen** [comment]
> Hi @kala-Chen, NNI support running on local machine, remote machine, kubernetes and OpenPAI platform, does support running on Spark platform.

hi~ sparkSnail, "does support running on Spark platform" ?  , can you give me a reference document link or a demo link ?

**Comment by SparkSnail** [comment]
> > Hi @kala-Chen, NNI support running on local machine, remote machine, kubernetes and OpenPAI platform, does support running on Spark platform.
> 
> hi~ sparkSnail, "does support running on Spark platform" ? , can you give me a reference document link or a demo link ?

sorry. spelling mistake. I mean that NNI does not support spark.
