### ISSUE TITLE
Is there any convenient way to debug the model for NAS task?

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#1941]
I'm trying to use enas to search a model based on my dataset. But it seems that we need to first build mutator, trainer, etc. before we can run the model. I'm wondering is there any easier way to test our model, just like a normal model:

```
class NasNet(nn.Module):
    ...
x = torch.rand(2,3,224,224)
net = NasNet()
net(x)
```

**Comment by QuanluZhang** [comment]
hi @marsggbo , if you want to try the search approach of enas (i.e., weight sharing and enas controller), there is no need to write a new mutator and trainer, simply use `EnasTrainer` in NNI SDK.

If you want to debug your model which uses `LayerChoice` and `InputChoice`, we provide [RandomMutator](https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/nas/pytorch/random/mutator.py). It randomly samples a concrete choice from `LayerChoice` and `InputChoice` every time `mutator.reset()` is called. For your code snippet, we show an example of how to use `RandomMutator` below:

```
from nni.nas.pytorch import random
class NasNet(nn.Module):
    ...
x = torch.rand(2,3,224,224)
net = NasNet()
mutator = random.RandomMutator(net)
mutator.reset()
net(x)
```
`mutator.reset()` can also be called before every epoch (or mini-batch), meaning that the following epoch (or mini-batch) uses the newly sampled choice.

**Comment by marsggbo** [comment]
> hi @marsggbo , if you want to try the search approach of enas (i.e., weight sharing and enas controller), there is no need to write a new mutator and trainer, simply use `EnasTrainer` in NNI SDK.
> 
> If you want to debug your model which uses `LayerChoice` and `InputChoice`, we provide [RandomMutator](https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/nas/pytorch/random/mutator.py). It randomly samples a concrete choice from `LayerChoice` and `InputChoice` every time `mutator.reset()` is called. For your code snippet, we show an example of how to use `RandomMutator` below:
> 
> ```
> from nni.nas.pytorch import random
> class NasNet(nn.Module):
>     ...
> x = torch.rand(2,3,224,224)
> net = NasNet()
> mutator = random.RandomMutator(net)
> mutator.reset()
> net(x)
> ```
> 
> `mutator.reset()` can also be called before every epoch (or mini-batch), meaning that the following epoch (or mini-batch) uses the newly sampled choice.

Thank u so much!
