### ISSUE TITLE
How to reload the parameter and fine-tune the best generated model in NAS?

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#1948]
In DARTS and ENAS, after the searching stage, only a list of json files are saved without model parameters. If we want to finetune the best child model, we have to train it from scratch. 

To this end, **how to save the parameters of the supernet and load the corresponding part of parameters to the child model and finetune it?**

**Comment by ultmaster** [comment]
Hi @marsggbo. Thanks for raising this issue.

In DARTS and ENAS, you can add a `ModelCheckpoint` to the callbacks for trainers, which will export the supernet weight into a file. For details, refer to https://github.com/microsoft/nni/blob/30152b04c4739f5b4f95087dee5f1e66ee893078/src/sdk/pynni/nni/nas/pytorch/callbacks.py#L61

To load, all you need to do this use `model.load_state_dict(torch.load(...))` before applying fixed architecture.

Feel free to ask if you have more questions.

**Comment by scarlett2018** [comment]
> Hi @marsggbo. Thanks for raising this issue.
> 
> In DARTS and ENAS, you can add a `ModelCheckpoint` to the callbacks for trainers, which will export the supernet weight into a file. For details, refer to
> 
> https://github.com/microsoft/nni/blob/30152b04c4739f5b4f95087dee5f1e66ee893078/src/sdk/pynni/nni/nas/pytorch/callbacks.py#L61
> 
> To load, all you need to do this use `model.load_state_dict(torch.load(...))` before applying fixed architecture.
> 
> Feel free to ask if you have more questions.

@ultmaster, may we add this issue to the FAQ? this sounds very useful to new users.

closing the ticket as ultmaster has provided the answer.

**Comment by QingquanBao** [comment]
Hi, in the retiarii version of NNI, the trainer is deprecated. I only see specifying `export_onnx` in the evaluator (`ClassificationModule` exactly). So how can we save the supernet parameters, and reload them when we start a new experiment or continue an old experiment?

**Comment by ultmaster** [comment]
See this example pls https://github.com/microsoft/nni/blob/master/examples/nas/oneshot/spos/search.py

**Comment by QingquanBao** [comment]
> See this example pls https://github.com/microsoft/nni/blob/master/examples/nas/oneshot/spos/search.py

Thank you for the reply!!! My further question is that in the example of SPOS, the supernet-training process still use the old API, i.e., `SinglePathTrainer`, but the new API should be `RandomOneShot`. For the former one, I see how to save the checkpoints cuz it is just a pytorch class, but for the latter one which is `xxxSpace`, I cannot figure out how to save. 

So do you mean that currently using old API like `SingPathTrainer` is a better option?

 I am quite confused and hope for your reply, thank you!!!
