### ISSUE TITLE
Bugfix for nnictl

### ISSUE THREAD

**Issue by tyusr** [microsoft/nni#1949]
Bugfix for `nnictl experiment delete <experiment_id>`:

in `nni/tools/nni_cmd/config_utils.py`   line 79:

https://github.com/microsoft/nni/blob/30152b04c4739f5b4f95087dee5f1e66ee893078/tools/nni_cmd/config_utils.py#L77-L81

`id` should be `expId`

**Comment by scarlett2018** [comment]
> Bugfix for `nnictl experiment delete <experiment_id>`:
> 
> in `nni/tools/nni_cmd/config_utils.py` line 79:
> 
> https://github.com/microsoft/nni/blob/30152b04c4739f5b4f95087dee5f1e66ee893078/tools/nni_cmd/config_utils.py#L77-L81
> 
> `id` should be `expId`

would you like to submit a PR? =).

**Comment by tyusr** [comment]
> > Bugfix for `nnictl experiment delete <experiment_id>`:
> > in `nni/tools/nni_cmd/config_utils.py` line 79:
> > https://github.com/microsoft/nni/blob/30152b04c4739f5b4f95087dee5f1e66ee893078/tools/nni_cmd/config_utils.py#L77-L81
> > 
> > `id` should be `expId`
> 
> would you like to submit a PR? =).

Done. #1953

**Comment by QuanluZhang** [comment]
Thanks for your contribution.
