### ISSUE TITLE
Refine log

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1952]
The current log is redundant and some of them are meaningless.

For example,

![image](https://user-images.githubusercontent.com/6280746/72309205-5029fc80-36b9-11ea-926e-ba51e64d3836.png)

**What would you like to be added**:

**Why is this needed**:

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by liuzhe-lz** [comment]
You can raise log level to `INFO` if you want.
Maybe we can default to that.

**Comment by xuehui1991** [comment]
@liuzhe-lz I think we should. This log come from users.

**Comment by liuzhe-lz** [comment]
I have confirmed the default log level is `INFO`.
The user is using `--debug` flag.
