### ISSUE TITLE
Can we train Enas or Darts in a distributed way?

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#1962]
Currently, I'm using Enas to search the network for my own dataset. Because my dataset is very large, it almost takes one night to search for only two epochs. So I wonder is it possible to search the model in a distributed way? Thanks a lot!

**Comment by QuanluZhang** [comment]
@marsggbo , ENAS supports DataParallel, you could simply wrapper your model with pytorch DataParallel. DARTS in NNI has not supported DataParallel yet, we are working on it.

We have not supported running ENAS and DARTS in a distributed way yet.

**Comment by scarlett2018** [comment]
@marsggbo - closing the issue as the question has been answered. please feel free to open new issues if there are more questions or issues.
