### ISSUE TITLE
Add a BibTeX citation text or link

### ISSUE THREAD

**Issue by YanjieGao** [microsoft/nni#1970]
**What would you like to be added**:
Add a BibTeX citation text or link for reference
**Why is this needed**:
for research work citation
**Without this feature, how does current nni work**：
hands on write, not clear write which year?
**Components that may involve changes**:
document
**Brief description of your proposal if any**:
You could refer autokeras
https://github.com/keras-team/autokeras#cite-this-work

**Comment by kvartet** [comment]
Thank you, we have added BibTeX citation text in PR #3150, and I will close the issue.
