### ISSUE TITLE
How to visualize the model generated during the search stage?

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#1980]

**Comment by QuanluZhang** [comment]
@marsggbo thanks for asking, we are working on visualization of NAS, hopefully we can release this feature in v1.5 in March.

**Comment by jeffltc** [comment]
Thanks for redirecting. Just curious are there any work around to export at least the connection information for each nodes in json form? Thanks in advance.

**Comment by ultmaster** [comment]
There has already been support in v1.5. It’s still experimental and we are actively improving it.
