### ISSUE TITLE
The image in doc is out of date

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1984]
![image](https://user-images.githubusercontent.com/6280746/73514256-ef762000-442b-11ea-81ff-dce46c9e1fda.png)

 The picture of WebUI in PAI doc is out of date.

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by lvybriage** [comment]
I'll fix soon. Thank you, @xuehui1991

**Comment by scarlett2018** [comment]
> I'll fix soon. Thank you, @xuehui1991

@lvybriage - - any work left for this issue? may we close it now?

**Comment by scarlett2018** [comment]
in 1.6.
