### ISSUE TITLE
WebUI error

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1986]
![image](https://user-images.githubusercontent.com/6280746/73586762-cb2e4800-44ec-11ea-85ac-4666d4a51767.png)

1. Intermediate results show as "FINAL" result.

2. Error when showing the comparison of the parameters.

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by ultmaster** [comment]
Could you please share the experiment parameters which is downloadable at the upper-right corner on WebUI?

**Comment by xuehui1991** [comment]
Of course.

The parameter as following:
![image](https://user-images.githubusercontent.com/6280746/73914687-be4a9380-48f4-11ea-8b08-34dc642f93b7.png)

Json format is:
[
    "{\"parameter_id\":0,\"parameter_source\":\"algorithm\",\"parameters\":{\"batch_size\":128,\"hidden_size\":1024,\"gamma\":0.95,\"policy_lr\":0.0008350295839947315,\"value_lr\":0.0013780050113098535,\"discrete_log_prob_scale\":2.7489078010190826,\"action_std\":0.1334962415791382,\"soft_tau\":0.0021531543793422135},\"parameter_index\":0}"
]

**Comment by ultmaster** [comment]
I mean the whole dict including results, like:

```
{
            "id": "Fr3SU",
            "status": "SUCCEEDED",
            "hyperParameters": [
                "..."
            ],
            "logPath": "file://localhost:/xxx",
            "startTime": 1580160230416,
            "sequenceId": 894,
            "endTime": 1580160916617,
            "finalMetricData": [
                {
                    "timestamp": 1580160913582,
                    "trialJobId": "Fr3SU",
                    "parameterId": "894",
                    "type": "FINAL",
                    "sequence": 0,
                    "data": "???"
                }
            ],
            "intermediate": [
                {
                    "timestamp": 1580160824451,
                    "trialJobId": "Fr3SU",
                    "parameterId": "894",
                    "type": "PERIODICAL",
                    "sequence": 0,
                    "data": "???"
                },
                {
                    "timestamp": 1580160913406,
                    "trialJobId": "Fr3SU",
                    "parameterId": "894",
                    "type": "PERIODICAL",
                    "sequence": 1,
                    "data": "???"
                },
                {
                    "timestamp": 1580160913582,
                    "trialJobId": "Fr3SU",
                    "parameterId": "894",
                    "type": "FINAL",
                    "sequence": 0,
                    "data": "???"
                }
            ]
        }
```

**Comment by xuehui1991** [comment]
You could find the experiment parameters in upper link.

**Comment by ultmaster** [comment]
The issue hasn't been active for two months. Does this problem still exist?
