### ISSUE TITLE
Trial search keywords get cleared when search type is changed

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#1990]
For example, when search type is changed from ID to params, keywords that has already been typed get cleared.

**Comment by scarlett2018** [comment]
Lijiao, @yangou1988 @ultmaster to figure out what's the common behavior for this kind of Web UI control.

**Comment by kvartet** [comment]
@Lijiaoa - would you mind testing this issue existing now?

**Comment by Lijiaoa** [comment]
It is by design... Also, we refactor the search ([the design](https://www.figma.com/file/HX8Og03m2rwNU1TS6rMTF1/0416-Fluent-Web-NNI-Filter?node-id=40047%3A6959)) on nni `v2.3`. It had fixed this question.

**Comment by kvartet** [comment]
> It is by design... Also, we refactor the search ([the design](https://www.figma.com/file/HX8Og03m2rwNU1TS6rMTF1/0416-Fluent-Web-NNI-Filter?node-id=40047%3A6959)) on nni `v2.3`. It had fixed this question.

as it has been fixed, I will close this issue
