### ISSUE TITLE
Export the topology graph the NAS result.

### ISSUE THREAD

**Issue by jeffltc** [microsoft/nni#1991]
**What would you like to be added**:Plot the structure of final NAS result.

**Why is this needed**:Demonstrate the topology of the result structure.

![image](https://user-images.githubusercontent.com/29009209/73643367-5440ad00-46ae-11ea-9b57-293e2792944d.png)

**Without this feature, how does current nni work**：I tried to use trainer.export() function to export the final structure, but what I got is which layer is used. I cannot find the connection between the nodes.
For example I use DARTS code in the naive example, the result of export() is the final choice of node on every layer, but the connection is missing.

**Components that may involve changes**:The trainer.export() function may change.

**Brief description of your proposal if any**:Exporting the json file with connection should help. It would be fantastic if the topology graph export feature is supported.

**Comment by ultmaster** [comment]
Thanks for asking. Related to #1980.

**Comment by scarlett2018** [comment]
> **What would you like to be added**:Plot the structure of final NAS result.
> 
> **Why is this needed**:Demonstrate the topology of the result structure.
> 
> ![image](https://user-images.githubusercontent.com/29009209/73643367-5440ad00-46ae-11ea-9b57-293e2792944d.png)
> 
> **Without this feature, how does current nni work**：I tried to use trainer.export() function to export the final structure, but what I got is which layer is used. I cannot find the connection between the nodes.
> For example I use DARTS code in the naive example, the result of export() is the final choice of node on every layer, but the connection is missing.
> 
> **Components that may involve changes**:The trainer.export() function may change.
> 
> **Brief description of your proposal if any**:Exporting the json file with connection should help. It would be fantastic if the topology graph export feature is supported.

@jeffltc - a very initial version of NAS visualization had been released recently in v1.5. It’s still experimental, we are more than willing to hear your feedbacks and improve it together =).
