### ISSUE TITLE
[PAIYarn Mode] No metric curve and intermediate info available.

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#1994]
**Short summary about the issue/question**:
I'm using NNI + PAIYarn mode, the jobs have been submitted correctly and succeeded on running. I can see the trial result in PAI's stdout log. but the default metric on NNI side is empty, so does intermediate results for each trial (empty as well).

![image](https://user-images.githubusercontent.com/39592018/73737854-58d49680-477e-11ea-92cc-54aa47dded65.png)

**Brief what process you are following**: 

**nni Environment**:
- nni version: 1.3
- nni mode(local|pai|remote): paiYarn
- OS: Windows' Ubuntu App
- python version: 3.7
- is conda or virtualenv used?: N
- is running in docker?: N

**Comment by SparkSnail** [comment]
For some reason, PAI's container could not access VPN IP address. Might caused by the machine's port, fire wall or some other reasons.
