### ISSUE TITLE
default metric graphs are empty after completing run of examples\trials\mnist-pytorch\config_windows.yml

### ISSUE THREAD

**Issue by jlema** [microsoft/nni#2000]
Repro steps:
Environment: Conda 4.8.1 on Windows 10, CUDA 10.1, CUDNN 7501, GeForce Drivers 441.87.
Hardware: Dell XPS 15, NVIDIA GeForce GTX 1050 TI

1. Install nni v1.3, pytorch 1.3.1
2. Open config_windows.yml on examples\trials\mnist-pytorch
2.1. Update line 21 to enable GPU training: **gpuNum: 1**
3. Star the experiment: nnictl create --config examples\trials\mnist-pytorch\config_windows.yml
4. Wait until all 10 trials complete with status SUCCEEDED, best default metric is 98.9.
5. Go to Overview (http://127.0.0.1:8080/oview), realize that top 10 graphs (maximal, minimal) are empty.
6. Go to Trials Details (http://127.0.0.1:8080/detail), realize that Default metric graph is empty, Hyperparameter lines do not connect to Default metric column.
6. Review displatcher.log file, find **Failed to load dill**. (attached is full log.)
[02/05/2020, 12:37:45 PM] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
7. Review nnimanager.log file, find **Read GPU summary failed with error**. (attached is full log.)
[2/5/2020, 1:29:36 PM] INFO [ 'Experiment done.' ]
**[2/5/2020, 1:33:11 PM] ERROR [ 'Read GPU summary failed with error: ',
  SyntaxError: Unexpected token { in JSON at position 144
      at JSON.parse (<anonymous>)
      at GPUScheduler.updateGPUSummary (c:\users\v-
[nnimanager.log](https://github.com/microsoft/nni/files/4162302/nnimanager.log)
julema\.conda\envs\xt\nni\training_service\local\gpuScheduler.js:69:40)
      at process._tickCallback (internal/process/next_tick.js:68:7) ]
[2/5/2020, 1:48:45 PM] ERROR [ 'Read GPU summary failed with error: ',
  SyntaxError: Unexpected token { in JSON at position 144
      at JSON.parse (<anonymous>)
      at GPUScheduler.updateGPUSummary (c:\users\v-julema\.conda\envs\xt\nni\training_service\local\gpuScheduler.js:69:40)
      at process._tickCallback (internal/process/next_tick.js:68:7) ]**

[nnimanager.log](https://github.com/microsoft/nni/files/4162315/nnimanager.log)
[dispatcher.log](https://github.com/microsoft/nni/files/4162316/dispatcher.log)

Overview
![image](https://user-images.githubusercontent.com/9736891/73891708-a823d100-4829-11ea-8f97-15656c28de92.png)

Trials Details - Hyperparameter
![image](https://user-images.githubusercontent.com/9736891/73891655-8c202f80-4829-11ea-9a3f-1de85d368510.png)

Trials Details - Default Metric
![image](https://user-images.githubusercontent.com/9736891/73891677-980bf180-4829-11ea-803a-a8afc5a52b5b.png)

**Comment by SparkSnail** [comment]
Hi @jlema, thanks for raising the issue. Could you please use `nnictl create --config examples\trials\mnist-pytorch\config_windows.yml --debug` command to start experiment, and provide `nniManager.log` here? The `debug` mode will provide more log information.
You could find a `metrics` file in your local trial's folder. You could find your trial's log path by `nnictl log trial` or from webUI, could you please provide the content of `metrics` file too?

**Comment by scarlett2018** [comment]
> Hi @jlema, thanks for raising the issue. Could you please use `nnictl create --config examples\trials\mnist-pytorch\config_windows.yml --debug` command to start experiment, and provide `nniManager.log` here? The `debug` mode will provide more log information.
> You could find a `metrics` file in your local trial's folder. You could find your trial's log path by `nnictl log trial` or from webUI, could you please provide the content of `metrics` file too?

@jlema are you still facing the issue after re-run? if so, may you provide the logs @SparkSnail mentioned above? thanks.

**Comment by jlema** [comment]
@scarlett2018 I'm in the process of repeating the test with the --debug flag and will post my results, including the nniManager.log in a few minutes.

**Comment by jlema** [comment]
I confirm I'm still facing the issue when I re-run.
I've re-run with --debug, attached are the files inside the experiment folder, including nniManager.log and the metrics files.
[nni_experiments_XX5gmtKl.zip](https://github.com/microsoft/nni/files/4201737/nni_experiments_XX5gmtKl.zip)

**Comment by SparkSnail** [comment]
I've checked the content of metrics and logs, there are a log of `null` code in these files.
![image](https://user-images.githubusercontent.com/22682999/74618376-6faabe00-516c-11ea-87fe-ada74c790eef.png)

**Comment by jlema** [comment]
@SparkSnail this conda environment was created from scratch specifically for nni.
Do you have any example code that I could use to repro the null code output you mention?
I'm attaching the output of doing pip freeze and conda list --export for your reference.

[env_pip.txt](https://github.com/microsoft/nni/files/4222164/env_pip.txt)
[env_conda.txt](https://github.com/microsoft/nni/files/4222165/env_conda.txt)

**Comment by SparkSnail** [comment]
Hi @jlema, the corresponding code in NNI is https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/platform/local.py#L72. You could use the code in following format
```
_metric_file = open('/tmp', 'wb')
data = ('test').encode('utf8')
_metric_file.write(data)
_metric_file.flush()
```
You could write data with larger size to test if it always works in your machine. If the `_metric_file.write(data)` always works in your machine, there might be some unknown issue in NNI.

**Comment by jlema** [comment]
Hi @SparkSnail, I used your code with larger size data (a text with 4395 characters instead of 'test') and it is working with no NUL characters being generated. I've attached the output text.

I had to change the output file specification to tmp.txt, as using /tmp gives PermissionError: [Errno 13] Permission denied: '/tmp' - this is on anaconda on Windows 10.

_metric_file = open('tmp.txt', 'wb')
data = ('<insert text with 4395 characters here>').encode('utf8')
_metric_file.write(data)
_metric_file.flush()

[tmp.txt](https://github.com/microsoft/nni/files/4257687/tmp.txt)

**Comment by jlema** [comment]
I think this may be a similar issue: https://github.com/microsoft/nni/issues/1701

**Comment by SparkSnail** [comment]
> I think this may be a similar issue: #1701
> 
> Would this be why I'm having issues in windows? My config_windows.yml file uses _trainingServicePlatform: local_
> 
> From https://nni.readthedocs.io/en/latest/Tutorial/HowToUseDocker.html
> 
> `NNI only support Ubuntu and MacOS system in local mode for the moment, please use correct docker image type.If you want to use gpu in docker container, please use nvidia-docker.`

Are you running NNI on a windows docker? What is your basic OS?

**Comment by jlema** [comment]
No I am running directly on windows anaconda, not docker.

**Comment by SparkSnail** [comment]
Hi @jlema, I've suspected the log content you provided, and I find that there are a log of `null` characters in `metric` file and `trial.log` files, I think if there are a log of log content in the trial's code, there might be some influence in NNI's metric file. So I write a naive test code which only include NNI API functions, could you please try running this code and test if it works in your environment? Thanks!!
[naive_example.zip](https://github.com/microsoft/nni/files/4285568/naive_example.zip)

**Comment by scarlett2018** [comment]
> Hi @jlema, I've suspected the log content you provided, and I find that there are a log of `null` characters in `metric` file and `trial.log` files, I think if there are a log of log content in the trial's code, there might be some influence in NNI's metric file. So I write a naive test code which only include NNI API functions, could you please try running this code and test if it works in your environment? Thanks!!
> [naive_example.zip](https://github.com/microsoft/nni/files/4285568/naive_example.zip)

@jlema - got a chance try this? thanks.

**Comment by scarlett2018** [comment]
> > Hi @jlema, I've suspected the log content you provided, and I find that there are a log of `null` characters in `metric` file and `trial.log` files, I think if there are a log of log content in the trial's code, there might be some influence in NNI's metric file. So I write a naive test code which only include NNI API functions, could you please try running this code and test if it works in your environment? Thanks!!
> > [naive_example.zip](https://github.com/microsoft/nni/files/4285568/naive_example.zip)
> 
> @jlema - got a chance try this? thanks.

@jlema - got a chance try this? thanks.
