### ISSUE TITLE
WIKI is out of date

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2002]
![image](https://user-images.githubusercontent.com/6280746/73904031-b7605880-48d5-11ea-9851-c3a45a43692b.png)

![image](https://user-images.githubusercontent.com/6280746/73904042-c1825700-48d5-11ea-95bd-806323eb8231.png)

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
@xuehui1991, the first search result I got from Google is no more exist. and the 2nd search result is correct: https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#resume.

The last discussion we made for Wiki was: will not use wiki but use https://nni.readthedocs.io/en/latest/ to document features. so, let's close this issue?

**Comment by scarlett2018** [comment]
had archived all the out of date wiki, we should use readthedocs for API and features documentation moving forward.
