### ISSUE TITLE
Performance issue-curvefitting assessor

### ISSUE THREAD

**Issue by Sundrops** [microsoft/nni#2006]
**Short summary about the issue/question**:

Firstly, Thanks for your great work.
Curvefitting is not ideal. The result predicted by curvefitting is much lower than actual value.

**How to reproduce it**: 
```python
from nni.curvefitting_assessor.curvefitting_assessor import CurvefittingAssessor
from nni.curvefitting_assessor.model_factory import CurveModel
from nni.assessor import AssessResult
# total: 120，60th: 0.48461，120th: 0.62371
train_top1_str = '0.03067 0.1549 0.24439 0.2958 0.32483 0.34807 0.36728 0.37919 0.38899 0.39597 0.40227 0.40688 0.41147 0.41503 0.41848 0.42127 0.42405 0.42626 0.42857 0.43035 0.43205 0.43415 0.43533 0.43664 0.4388 0.44001 0.44114 0.44239 0.44391 0.44562 0.44621 0.44746 0.44948 0.45023 0.45154 0.45291 0.45439 0.45492 0.45603 0.45782 0.45887 0.45964 0.46145 0.46245 0.46379 0.46552 0.46642 0.46831 0.46934 0.47049 0.47181 0.47378 0.47434 0.47594 0.47746 0.47924 0.48024 0.4814 0.48303 0.48461 0.48655 0.48852 0.48974 0.49162 0.49388 0.49501 0.49696 0.49824 0.50038 0.5026 0.50436 0.50578 0.50796 0.51038 0.51237 0.51423 0.51706 0.51853 0.52077 0.52291 0.52592 0.52769 0.52973 0.53194 0.5345 0.53724 0.53947 0.54241 0.54516 0.54755 0.55014 0.55259 0.55572 0.55878 0.56198 0.56476 0.56796 0.57071 0.57345 0.5765 0.57952 0.58325 0.58691 0.58975 0.59223 0.5952 0.59976 0.60217 0.60488 0.60855 0.61108 0.61337 0.61641 0.61801 0.61985 0.6215 0.62258 0.62357 0.62352 0.62371'
train_top1 = [float(i)for i in train_top1_str.split(' ')]
curvemodel = CurveModel(120)
# 0.4857947474778695 <<< 0.62371  so low?
curvemodel.predict(train_top1[:60])
```
![image](https://user-images.githubusercontent.com/14829222/73945864-ef948500-492f-11ea-80ae-2d0a30983921.png)

**nni Environment**:
- nni version: 1.3

**Comment by QuanluZhang** [comment]
@Sundrops , thanks for reporting this issue. Could you help check the prediction result when you feed in 100 points?

**Comment by Sundrops** [comment]
@QuanluZhang The prediction result is 0.5572954354900362 when I feed in 100 points(0.5765).

**Comment by QuanluZhang** [comment]
@Sundrops thanks for reporting this issue. I guess this is an expected behavior, because the curve fitting algorithm uses several typical curves (i.e., the figure in [this page](https://nni.readthedocs.io/en/latest/Assessor/CurvefittingAssessor.html)) to fit the learning curve. It is hard for those curves to know there is a faster increase after point 60, if you only give them 60 points. If you are curious about this, you could check the fitted curves in this algorithm (need to read and modify the source code to do this).

**Comment by Sundrops** [comment]
@QuanluZhang Ok, I see. Thanks for your reply.
