### ISSUE TITLE
 webui pages are inconsistent

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2007]
In the overview page:

![image](https://user-images.githubusercontent.com/6280746/73951540-9b41d300-4938-11ea-826e-70a3a9550c88.png)

on the Trial details page:

![image](https://user-images.githubusercontent.com/6280746/73951595-b57bb100-4938-11ea-9ce1-0b3f2a5609fc.png)

The trial status are inconsistent.

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
Waiting status is missing.
