### ISSUE TITLE
Why not put the lastest result in the picture?

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2010]
![image](https://user-images.githubusercontent.com/6280746/73996263-21d8cd80-4996-11ea-9c12-8185715411a6.png)

The top10 result only contains the final result. Why not put the lastest trial result here? because some trials might be achieved good results but fail accidentally.

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
The original design for this chart is to display "Top 10" out of all the completed results, but what Hui suggests makes senses for a long running job. While if showing the "running" but not completed job there, we need to adjust the display style for that point, and might also need to adjust the description for that chart. 

@yangou1988 @lvbridge - please follow up with @xuehui1991.

**Comment by yangou1988** [comment]
Design plan #2142

**Comment by Lijiaoa** [comment]
@xuehui1991 @scarlett2018 @yangou1988 PR #2417 is for this issue, @kvartet  Could you help close this issue?
