### ISSUE TITLE
Loading WebUI is too slow

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2018]
When I loading the WebUI,  it takes almost 3-4 minutes to load.

![image](https://user-images.githubusercontent.com/6280746/74095288-a3149980-4b29-11ea-8529-3112726e0855.png)

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
Not sure whether the delay is caused by VPN or other factors. assigning @lvbridge to reproduce the issue first.
