### ISSUE TITLE
Values ​​on the x axis lack of units

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2021]
![image](https://user-images.githubusercontent.com/6280746/74102244-a2f1b980-4b7c-11ea-841d-051ecd1cbb09.png)

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by lvybriage** [comment]
had fixed in PR https://github.com/microsoft/nni/pull/1964.

**Comment by scarlett2018** [comment]
> had fixed in PR #1964.

@xuehui1991 please help to verify with the new 1.4 build
