### ISSUE TITLE
Error in veiw command

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2038]
![image](https://user-images.githubusercontent.com/6280746/74302996-487e7600-4d93-11ea-88f7-bd8c989403ab.png)

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by SparkSnail** [comment]
https://github.com/microsoft/nni/pull/2044

**Comment by scarlett2018** [comment]
> #2044

merged to 1.4? @SparkSnail, @QuanluZhang ?

**Comment by SparkSnail** [comment]
> > #2044
> 
> merged to 1.4? @SparkSnail, @QuanluZhang ?

Yes, the pr is merged to 1.4
