### ISSUE TITLE
Get Platform's information in msg_dispatcher.py

### ISSUE THREAD

**Issue by Chen-Hongji** [microsoft/nni#2053]
**Short summary about the issue/question**:
I'm learning NNI. In ~/nni/src/sdk/pynni/nni/platform/__init__.py, what I get from printing trial_env_vars.NNI_PLATFORM in the master is None, and the call to get_experiment() in the ~/nni/src/sdk/pynni/nni/msg_msg_dispatcher.py is also None. Why are both None? What do I need to get experiment_id and platform in the ~/nni/src/sdk/pynni/nni/msg_msg_dispatcher.py?

**nni Environment**:networknetworkmorphism/cifar10_pytorch.py
- nni version: v1.0
- nni mode(local|pai|remote): remote
- OS: ubuntu16.04
- python version: 3.7
- is conda or virtualenv used?: 
- is running in docker?: yes

**Comment by chicm-ms** [comment]
Hi @Chen-Hongji,  nni trial jobs are running on training services platform, the directory `nni/src/sdk/pynni/nni/platform/` is a part of the NNI APIs which are supposed to be called from within NNI trial jobs.  When nni is started, necessary environment variables are configured properly for trial jobs by training services.  
`nni/src/sdk/pynni/nni/msg_dispatcher.py` is a part of nni dispatcher process, which contains tuners and assessors. It is a separate process running on the host where you start nni.  There are also environment configurations need to be setup while dispatcher process is started.

`get_experiment_id()` is a NNI trial API, you need to call it from your trial code, such as this one (https://github.com/microsoft/nni/blob/master/examples/trials/mnist-pytorch/mnist.py#L157) ,
then start nni with `nnictl create` command (https://github.com/microsoft/nni)

**Comment by scarlett2018** [comment]
closing the issue as the answer is provided.
