### ISSUE TITLE
NNI does not detect GPU on Windows

### ISSUE THREAD

**Issue by Markus92** [microsoft/nni#2055]
**Short summary about the issue/question**:
On my Windows machine, which has only one GPU, the GPU Metrics collector does not detect my GPU.

**Brief what process you are following**: 
Run NNI with a sample experiment.

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.3
- nni mode(local|pai|remote): local
- OS: Windows 10 1909
- python version: 3.7.3
- is conda or virtualenv used?:  conda
- is running in docker?: no

**Anything else we need to know**:
Bug seems to be related to the GPU metrics collector script. Here's sample output:

```
{"Timestamp": "Thu Feb 13 15:55:28 2020", "gpuCount": 0, "gpuInfos": []}
```

Running `NVIDIA-SMI` results in the following. The GPU is detect and the tool is in path,
```
C:\Users\xxx>nvidia-smi
Thu Feb 13 17:02:08 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 432.00       Driver Version: 432.00       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp           WDDM  | 00000000:03:00.0 Off |                  N/A |
| 23%   37C    P8    17W / 250W |   1827MiB / 12288MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       432    C+G   ...ge_8wekyb3d8bbwe\MicrosoftPdfReader.exe N/A      |
....
|    0     21596    C+G   ...6)\Google\Chrome\Application\chrome.exe N/A      |
+-----------------------------------------------------------------------------+
```

**Comment by SparkSnail** [comment]
Hi @Markus92 , could you please run this script file [gpu_metrics_collector.zip](https://github.com/microsoft/nni/files/4207918/gpu_metrics_collector.zip) in your machine? This is the script NNI used to detect your gpu devices, you could change the `$env:METRIC_OUTPUT_DIR="C:\Users"` field to your own path.

**Comment by scarlett2018** [comment]
> Hi @Markus92 , could you please run this script file [gpu_metrics_collector.zip](https://github.com/microsoft/nni/files/4207918/gpu_metrics_collector.zip) and get the output in your machine? This is the script NNI used to detect your gpu devices, you could change the `$env:METRIC_OUTPUT_DIR="C:\Users"` field in the script to your own path.

@Markus92 any feedback? thanks.

**Comment by Markus92** [comment]
Hi @scarlett2018, due to the covid-19 situation we have very limited access to research PCs right now and have not had the opportunity to run this script yet, sorry about that. We have to use all resources for caring for our patients :)

Feel free to close this issue and I will reopen it when things have calmed down a bit, and I can run the script and have access again.

**Comment by scarlett2018** [comment]
> Hi @scarlett2018, due to the covid-19 situation we have very limited access to research PCs right now and have not had the opportunity to run this script yet, sorry about that. We have to use all resources for caring for our patients :)
> 
> Feel free to close this issue and I will reopen it when things have calmed down a bit, and I can run the script and have access again.

Thanks @Markus92 , stay healthy =).
