### ISSUE TITLE
GPU usage information cannot be detected by gpustat or nvidia-smi

### ISSUE THREAD

**Issue by UCASJingKun** [microsoft/nni#2059]
**Short summary about the issue/question**:
GPU usage information cannot be detected by gpustat or nvidia-smi.

**Brief what process you are following**: 
I run a experiment following the config:
authorName: Jing
experimentName: gan_pytorch
trialConcurrency: 1
maxExecDuration: 20h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: GPTuner
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python gan_automl.py
  codeDir: .
  gpuNum: 1

GPU usage information cannot be detected by gpustat or nvidia-smi. I'm not sure if the experiment is running on a GPU. Is this normal?

**Comment by QuanluZhang** [comment]
@UCASJingKun you ran this experiment on linux or windows? do you want your trial to use GPU, you set gpuNum to 1 which means each trial job needs 1 GPU.

If you want your trial to use GPU and nvidia-smi does not work, you need to make sure cuda is correctly installed on your machine. If you do not want your trial to use GPU, then simply set gpuNum to 0.

**Comment by UCASJingKun** [comment]
> @UCASJingKun you ran this experiment on linux or windows? do you want your trial to use GPU, you set gpuNum to 1 which means each trial job needs 1 GPU.
> 
> If you want your trial to use GPU and nvidia-smi does not work, you need to make sure cuda is correctly installed on your machine. If you do not want your trial to use GPU, then simply set gpuNum to 0.

Thanks. I found the first trail was still 'waiting' state because all gpu was busy. Now, it works.
