### ISSUE TITLE
Cannot report dict metric to nni now but works in 0.9.1 version

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2060]
![image](https://user-images.githubusercontent.com/6280746/74581247-39443600-4fe8-11ea-89d1-c9211dad112b.png)

the variable `feature_importances` is a dataframe object(pandas).

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.3
- nni mode(local|pai|remote): all
- OS: linux
- python version: 3.6
- is conda or virtualenv used?:  yes
- is running in docker?: no

**need to update document(yes/no)**:

**Anything else we need to know**:

works in nni==0.9.1

**Comment by xuehui1991** [comment]
I think this bug is not only in WebUI. It should be in nni manager or dispatcher.

**Comment by lvybriage** [comment]
> I think this bug is not only in WebUI. It should be in nni manager or dispatcher.

Hi, @xuehui1991  This issue had fixed in PR #2067, in version V1.4

**Comment by ultmaster** [comment]
#2152
