### ISSUE TITLE
WebUI is loading slow with 1000 trial and 5000 intermediate results

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2062]
I have some suggestion as following:

1) the nnimanager.log is too large, most of the information that users don't need to know and meaningless.

2) Can WebUI only show part of data at the beginning? For example, if user doesn't want to check the nnimanager.log or dispatcher.log, WebUI doesn't need to load them.  

3) Can WebUI consider load the final metric and the lastest intermediate result first? (due to some trial are long-running jobs, and they have thousands of  intermediate results.)

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
How slow is it now? If webUI performance is a problem, we need to have a test case and run it as a baseline before, then set an improvement goal before discuss about the solutions.

@xuehui1991 may you share the slow case here? we can have a discussion on the issue based on the case. cc @chicm-ms @liuzhe-lz @lvybriage @QuanluZhang

**Comment by xuehui1991** [comment]
I think it could reproduce in that case:

Run 1000 trial and each trial have 50000 intermediate results. And you know how slow the WebUI now.

**Comment by scarlett2018** [comment]
> hello @scarlett2018
> 
> I think it could reproduce/test in that case:
> 
> Run 1000 trial and each trial have 5000 intermediate results and log with 100 sentences. And you know how slow the WebUI.
> 
> By the way, when the data(about 1G) become large, the WEBUI may crash and throw an "out of memory " node error.

Let's set these 2 as improve target goal scenarios.

**Comment by QuanluZhang** [comment]
optimized by @liuzhe-lz , closed
