### ISSUE TITLE
`nnictl stop` cannot stop a failed experiment sometime

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#2080]
**Short summary about the issue/question**: if I have some kind of error occur in the Python code, and that error generates an exception, then the REST server continues to run, occupying the port, but I can't stop it, because it says there is no experiment running. I found the node.js server process that I needed to kill, but there should be some way to have it either die when there's an error, or have the 'stop' command work even though no experiment has been started properly.

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**Comment by SparkSnail** [comment]
https://github.com/microsoft/nni/pull/2086
