### ISSUE TITLE
WebUI crash after refresh

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2087]
![image](https://user-images.githubusercontent.com/6280746/75002969-31313e00-54a1-11ea-80da-57a2215ac515.png)

The experiment only have one trial and one final data.

![image](https://user-images.githubusercontent.com/6280746/75002996-49a15880-54a1-11ea-917d-3c221db2e7f7.png)

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by lvybriage** [comment]
will design an error page to show this status.
