### ISSUE TITLE
Why does the model get bigger after quantization(NAIVE,BNN)? 

### ISSUE THREAD

**Issue by Greyman-Seu** [microsoft/nni#2095]
**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
> **Short summary about the issue/question**:
> 
> **Brief what process you are following**:
> 
> **How to reproduce it**:
> 
> **nni Environment**:
> 
> * nni version:
> * nni mode(local|pai|remote):
> * OS:
> * python version:
> * is conda or virtualenv used?:
> * is running in docker?:
> 
> **need to update document(yes/no)**:
> 
> **Anything else we need to know**:

@Greyman-Seu - could you please enter the above info so that we know your environment and issue better?

**Comment by Cjkkkk** [comment]
Hi @Greyman-Seu, could you tell us how to reproduce your case? Maybe with some code you are using if it is possible?

**Comment by QuanluZhang** [comment]
duplicate to #2097 , close
