### ISSUE TITLE
Invalid typeof check in observableTimer

### ISSUE THREAD

**Issue by guilhermehn** [microsoft/nni#2100]
**Short summary about the issue/question**:

The `unsubscribe` method is doing an invalid typeof check:

https://github.com/microsoft/nni/blob/ff2728c0a8ed1d9db95cee7878ee1d81ef0a3a8d/src/nni_manager/common/observableTimer.ts#L22

```js
typeof undefined !== undefined
// true

typeof undefined === 'undefined'
// true
```

**Brief what process you are following**: 

Nothing, I was just reading through the codebase :)

**Anything else we need to know**:

ESLint is already configured to use the "recommended" preset which has the `valid-typeof`, so maybe this was introduced before ESLint was setup.

**Comment by chicm-ms** [comment]
@guilhermehn   Thanks for your good catch, will you send a PR to fix it? The intention was to check whether subscription is undefined. It is a mistake.

**Comment by guilhermehn** [comment]
Just opened #2106.
