### ISSUE TITLE
ERROR: Port 8080 is used by another process, please reset the port!

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/nni#2108]
ERROR: Port 8080 is used by another process, please reset the port!

**Comment by SparkSnail** [comment]
Hi @Jie-Yuan, NNI use 8080 port as the default to start restful server, if this port is used by other process in your environment, you could use `--port` command to set the port NNI used. [refer](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#create)

**Comment by scarlett2018** [comment]
As the question is answered, I'm closing it. @Jie-Yuan feel free to reopen if it does not fix your issue.
