### ISSUE TITLE
Web UI does not support search for a specific Trial

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/nni#211]
I ran an experiment, and it failed with an "Error" status. After check the log, I got info about few trial did not successfully got the status. I got the trial id, but the trial table does not support search.

**Comment by scarlett2018** [comment]
@yhung119 - Thank you for the attention to our project and glad you are interested in contributing to it.

To start contributing, you can follow up with our contribution guideline: https://github.com/Microsoft/nni/wiki/How-To-Contribute.

For this individual item, @lvybriage had just implemented the support for search trial by NO. the corresponding codes are at
https://github.com/Microsoft/nni/blob/v0.4/src/webui/src/components/TrialsDetail.tsx#L204  
_line 204-229 & line 287-299_

Please add the support for "trial id" and submit your PR. Looking forward for your codes and inputs.

Best Regards,
Scarlett

**Comment by yds05** [comment]
Resolved. Close.
