### ISSUE TITLE
The Web detail page is not displayed

### ISSUE THREAD

**Issue by Haitons** [microsoft/nni#2114]
**Short summary about the issue/question**:
![image](https://user-images.githubusercontent.com/33169108/75781306-e57f6e00-5d97-11ea-8bdd-fe1ddeb98e99.png)

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by liuzhe-lz** [comment]
Can you paste the output of `nnictl experiment status`? We need to know if the whole experiment is dead or it's only a web UI issue.
If the experiment it self is still working, please show us the console output of your browser. You can open the browser console by pressing `F12` then clicking the `Console` tab.

**Comment by Haitons** [comment]
The output is {
    "errors":[],
    "status":"RUNNING"
}
Now the detail page can be displayed normally. I found that this problem only occurs when starting a new trial. When `nni.report_final_result` gets the first value, the page can be opened.

**Comment by liuzhe-lz** [comment]
You can try refresh the page if you run into this problem again.
We will investigate the root cause later. Thanks for your report.

**Comment by Haitons** [comment]
Thank you for your reply.
