### ISSUE TITLE
Tips: No module named 'nni.feature_engineering'

### ISSUE THREAD

**Issue by stone-doc** [microsoft/nni#2118]
nni:1.4

ModuleNotFoundError: No module named 'nni.feature_engineering'

**Comment by liuzhe-lz** [comment]
Can you try if `import nni` works? How did you install nni package?

**Comment by stone-doc** [comment]
> 你能试试看`import nni`吗？您是如何安装nni软件包的？
1、Can import NNI
2、Install with PIP 
3、The installation should not be completed
4、tips：OSError: [Errno 39] Directory not empty: '/root/.python/python3.6/dist-packages/simplejson'
5、Use in docker
![image](https://user-images.githubusercontent.com/59304289/75841718-60cd3800-5e09-11ea-8d7f-dbf1c4c04128.png)




![image](https://user-images.githubusercontent.com/59304289/75841603-1e0b6000-5e09-11ea-82d6-244b9ba359e6.png)

**Comment by stone-doc** [comment]
> 你能试试看`import nni`吗？您是如何安装nni软件包的？

![image](https://user-images.githubusercontent.com/59304289/75842011-2f08a100-5e0a-11ea-955b-031c0b9113f6.png)

**Comment by liuzhe-lz** [comment]
Looks like the installtion progress has failed and you are still using an old version of nni, which does not include feature engineering.
Please try remove and reinstall `simplejson` package first, it's preventing your pip from installing any package. If `pip uninstall` fails, you can remove the files manually.

**Comment by stone-doc** [comment]
> Looks like the installtion progress has failed and you are still using an old version of nni, which does not include feature engineering.
> Please try remove and reinstall `simplejson` first, it's preventing your pip from installing any package. If `pip uninstall` fails, you can remove the folders manually.

I did the following：
1、pip uninstall simplejson
2、pip install nni     'successful'
3、Run code prompt：：ModuleNotFoundError: No module named 'nni.feature_engineering'

![image](https://user-images.githubusercontent.com/59304289/75843116-3bdac400-5e0d-11ea-8d22-998d8290bd87.png)
![image](https://user-images.githubusercontent.com/59304289/75843134-45fcc280-5e0d-11ea-839a-18ab2a005de7.png)

**Comment by stone-doc** [comment]
nni installation prompt successful

> > Looks like the installtion progress has failed and you are still using an old version of nni, which does not include feature engineering.
> > Please try remove and reinstall `simplejson` first, it's preventing your pip from installing any package. If `pip uninstall` fails, you can remove the folders manually.
> 
> I did the following：
> 1、pip uninstall simplejson
> 2、pip install nni 'successful'
> 3、Run code prompt：：ModuleNotFoundError: No module named 'nni.feature_engineering'
> 
> ![image](https://user-images.githubusercontent.com/59304289/75843116-3bdac400-5e0d-11ea-8d22-998d8290bd87.png)
> ![image](https://user-images.githubusercontent.com/59304289/75843134-45fcc280-5e0d-11ea-839a-18ab2a005de7.png)
nni installation prompt successful

**Comment by liuzhe-lz** [comment]
Please check if your `pip` and `python` are using the same environment. You can compare `pip show nni` and `python -c 'import nni; print(nni.__path__)`.

**Comment by stone-doc** [comment]
> Please check if your `pip` and `python` are using the same environment. You can compare `pip show nni` and `python -c 'import nni; print(nni.__path__)`.

I found that there was a lack of configuration and dependency in the docker,have already been solved，thanks
