### ISSUE TITLE
TensorFlow v2 Support

### ISSUE THREAD

**Issue by liuzhe-lz** [microsoft/nni#2127]
Scope for July release:
- [ ] Review on how the current NNI Pytorch model compression implementation, survey and compare the corresponding TF 2.0 supportability. ETA 7/22
- [ ] design depends on the survey results

-------------------
This issue tracks pending jobs for TensorFlow v2 support.

- [x] HPO
- [x] NAS: classic NAS tuning + ENAS, DARTS algo refresh
- [ ] model compression
- [ ] feature engineering

-----------------------------------------------------
+ [ ] Examples
  - [x] **P1 - Rewrite TFv1 example trials (naive example) with TFv2** **(May release)**
  - [ ] **P2 - Rewrite TFv1 example trials (DARTS) with TFv2**
  - [ ] **P0** NAS performance improvement (June)
  - [ ] **P2** Move pipelines to v2
+ [ ] NAS
  - [x] **P0 - SDK and ENAS** **(May release)**
  - [ ] Implement algorithms
+ [ ] Static graph speed-up for NAS and Model Compression
  - [ ] Ad-hoc optimization for built-in algorithms
  - [ ] Public optimizing API
+ [ ] Update building- and releasing-related scripts
+ [ ] Update documentation

**Comment by scarlett2018** [comment]
released in 1.6, will keep on the rest in June release
>   * [x]  **P1 - Rewrite TFv1 example trials (naive example) with TFv2**
>   * [x]  **P0 - SDK and ENAS**

**Comment by scarlett2018** [comment]
[3.1] performance for all, slower than pytorch, GPU usage is slow, need improvement
[3.2] test pipeline for TF2.0
[3.3] TF NAS API style refactor -> to tf style
[3.4] model compression for TF2.0
[3.5] Feature Enginerring for TF2.0
[3.6] Support all NAS algorithms for TF2.0
