### ISSUE TITLE
Need more friendly hint if the specific port has been occupied

### ISSUE THREAD

**Issue by goooxu** [Microsoft/nni#213]
The default port 51188 has been occupied by other service, and if try to run the below command and got such hint, want a more friendly one.
![image](https://user-images.githubusercontent.com/22703054/46930181-b5d2a780-d076-11e8-8471-74b668fd29ba.png)
And, before the ERROR message, it was waiting more than one minute without any message.

**Comment by SparkSnail** [comment]
https://github.com/Microsoft/nni/pull/207
fixed.
