### ISSUE TITLE
Web UI Improvement (Mar.)

### ISSUE THREAD

**Issue by yangou1988** [microsoft/nni#2135]
**1. Overview - Status** @lvybriage 

- [ ] Need a tooltip with a sentence: " **TrialConcurrency is the number of trials running concurrently, which is the number of GPUs you want to use if you are setting gpuNum to 1.**" on 'Concurrency' to introduce what is Concurrency for. 

**2. Overview - Profile** @lvybriage 

- [ ] - Convert the format of JSON to Yaml 

**3. Trials detail -Default metric**

- [ ] Change the name 'Optimization curve' to 'Search progress curve' (TBD)
- [ ] Add a description under the button @scarlett2018 @lvybriage

**4. Trials detail -Hyper-parameter** (Replace the Echarts)

**5. Trial Duration** @lvybriage #1489 

- [ ] To show more detail information like trial no., trial ID, and time in the Tooltip ，Sample: Trial no. 9, Trial ID:ogiNQ, Time 30.601s, 

**6. Intermediate result** @ultmaster will prepare a new plan for Intermedia result chart
	
**7. Trial jobs** 
- [ ] User don't know how to use 'Search by parameters' and highlight the search result   @lvybriage @yangou1988

**Comment by Lijiaoa** [comment]
detail table:
[] waiting bg-color
[] operation disable button's bg-color
[] open row & select row click conflict
