### ISSUE TITLE
NotImplementedError: Quantizer must overload quantize_output()

### ISSUE THREAD

**Issue by Blue-Eagle-10** [microsoft/nni#2138]
For help, I use the quantization tool in nni to quantify the yolov3 model I created: 
model = nni.compression.torch.NaiveQuantizer (model, config_list) .compress ()
But the following error occurred, how can I modify it? thank you very much!

![image](https://user-images.githubusercontent.com/24905967/76205754-d8e69400-6235-11ea-9867-1e8fe5931204.png)
![image](https://user-images.githubusercontent.com/24905967/76205453-3af2c980-6235-11ea-8f73-278cde88e0d1.png)

**Comment by chicm-ms** [comment]
@Blue-Eagle-10 The NaiveQuantizer does not support quantizing model output,  you can either change quantizer to another type which support quantizing output,  such as QAT_Quantizer, or remove the second part of config_list whose quant_types is 'output'

**Comment by Blue-Eagle-10** [comment]
Hi@chicm-ms,
Thank you very much for your reply, the problem has been solved, thank you very much! I would like to ask, does this kind of NaiveQuantizer have reference documentation on quantization methods and principles? Can it be quantized to 16 bits?

**Comment by chicm-ms** [comment]
@Blue-Eagle-10 
Quantizer documents can be found here, https://github.com/microsoft/nni/blob/master/docs/en_US/Compressor/Quantizer.md#naive-quantizer , the function of NaiveQuantizer is very limited (like a helloworld), I suggest you to use other 3 types of Quantizer per your need, they support 16 bits.  You can check their source code here   
if you can not find some details in doc: https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/compression/torch/quantizers.py

**Comment by scarlett2018** [comment]
Closing the issue as the question has been welled answered. Thanks @Blue-Eagle-10 and @chicm-ms .
