### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nnictl': 'nnictl'   in jupyter

### ISSUE THREAD

**Issue by stone-doc** [microsoft/nni#2141]
Using jupyternotebooks, prompted: 
**FileNotFoundError: [Errno 2] No such file or directory: 'nnictl': 'nnictl'** 
codes:
import nnicli as nc
nc.start_nni(config_file='../trials/mnist/config.yml'
prompted:
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-14-4b8fff04b962> in <module>
----> 1 nc.start_nni(config_file='/root/codes/nni_example/nni_ression/config.yml')

~/.local/lib/python3.6/site-packages/nnicli/nni_client.py in start_nni(config_file)
     96     """start nni experiment with specified configuration file"""
     97     cmd = 'nnictl create --config {}'.format(config_file).split(' ')
---> 98     if _create_process(cmd) != 0:
     99         raise RuntimeError('Failed to start nni.')
    100 

~/.local/lib/python3.6/site-packages/nnicli/nni_client.py in _create_process(cmd)
     85         process = subprocess.Popen(cmd, stdout=subprocess.PIPE, creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
     86     else:
---> 87         process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
     88 
     89     while process.poll() is None:

/usr/lib/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    727                                 c2pread, c2pwrite,
    728                                 errread, errwrite,
--> 729                                 restore_signals, start_new_session)
    730         except:
    731             # Cleanup if the child failed starting.

/usr/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1362                         if errno_num == errno.ENOENT:
   1363                             err_msg += ': ' + repr(err_filename)
-> 1364                     raise child_exception_type(errno_num, err_msg, err_filename)
   1365                 raise child_exception_type(err_msg)
   1366 

FileNotFoundError: [Errno 2] No such file or directory: 'nnictl': 'nnictl'

nni:1.4
can run nictl in CMD

![image](https://user-images.githubusercontent.com/59304289/76269645-74671b80-62ad-11ea-88ed-fed20a37f66a.png)

**Comment by chicm-ms** [comment]
@stone-doc nni needs to be installed in the jupyter environment, you can either install it in command line:
`python3 -m pip install --upgrade nni`
or do it in notebook:
`!pip install --upgrade nni`

**Comment by chicm-ms** [comment]
@stone-doc have you tried the solution?  Closing this issue, if you still having the problem, you can reopen it.
