### ISSUE TITLE
UX Enhancement - User can edit the Top k manually in WebUI

### ISSUE THREAD

**Issue by yangou1988** [microsoft/nni#2142]
**Short summary about the issue/question**:
Users hope that they can edit the range of Top K as top 10, 20, 30, 50, 100... in WebUI Overview (home) page when they are running a experiment with lots of trials.

**Brief what process you are following**: 
Draft UX design plan. wait for review.

**How to reproduce it**: 
Add a drop down button at the top-right of Top max/min to choose the number of top trials( 10, 20, 30, 50, 100 ).

Defaut (Top10)
![Web 1920 – 3](https://user-images.githubusercontent.com/44491713/76310319-8a0a2e80-6309-11ea-9d1e-2f78ef8d4be8.png)

Click drop down - choose top30
![Web 1920 – 6](https://user-images.githubusercontent.com/44491713/76310323-8c6c8880-6309-11ea-978d-b1a7ccdbb3ef.png)

Display top 30 trials in right list and left chart
![Web 1920 – 7](https://user-images.githubusercontent.com/44491713/76310324-8d051f00-6309-11ea-8d4d-a9d90d37f2e6.png)

---------------------------------------------
No successes trials scenario
Message: The experiment is running, please wait for the final metric patiently. 
You could also find status of trial job with Trials detail button.
![Web 1920 – 5](https://user-images.githubusercontent.com/44491713/76310664-33e9bb00-630a-11ea-917a-914eee78a6b2.png)

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**Comment by yangou1988** [comment]
#2007

**Comment by yangou1988** [comment]
#2007

**Comment by Lijiaoa** [comment]
No successes trials scenario: PR https://github.com/microsoft/nni/pull/2318.
Still have task to do.

**Comment by ultmaster** [comment]
It's done in v1.7
