### ISSUE TITLE
Nnictl tensorboard runs successfully. The interface of tensorboard prompts: No dashboards  are active

### ISSUE THREAD

**Issue by lizhaodong** [microsoft/nni#2185]
**Short summary about the issue/question**:
Nnictl tensorboard runs successfully. The interface of tensorboard prompts: No dashboards  are active
**Brief what process you are following**: 
1. Run this demo: https://github.com/microsoft/nni/tree/master/examples/trials/mnist-keras, the selected configuration file is config.yml
2. When all experiments are complete, run this command: nnictl  tensorboard start  --trial_id  T4ix3    --port  8089  M2Fc761e
![1](https://user-images.githubusercontent.com/1129767/77033858-543d0800-69e3-11ea-9aae-4066029d2d82.png)
But, The IP---127.0.0.1:8090 displays as follows：
![2](https://user-images.githubusercontent.com/1129767/77033979-9ebe8480-69e3-11ea-80d3-de12eb47697b.png)
3. However, I run this command--- “tensorboard --logdir ./train --port 8090 ” and it shows success!
![3](https://user-images.githubusercontent.com/1129767/77034126-24dacb00-69e4-11ea-8d20-4a7d3faf1d10.png)

**How to reproduce it**: 

**nni Environment**:ubuntu18.04 
- nni version:1.4 
- nni mode(local|pai|remote):local
- OS:ubuntu18.04 
- python version: 3.6 
- is conda or virtualenv used?: NO 
- is running in docker?:NO 

**need to update document(yes/no)**:NO

**Anything else we need to know**:
Your source code: 
![9](https://user-images.githubusercontent.com/1129767/77034328-9a469b80-69e4-11ea-975e-93d50204daef.png)
According to the command in the red box, it is clear that the 'logdir' path of  tensorboard is not correct.

**Comment by SparkSnail** [comment]
Hi @lizhaodong, I can not reproduce your issue. Could you please use `nnictl trial ls` to get the logPath of the trial, and show the folder structure here? Do you have a `events.out.tfevents.**` file in that log path?

**Comment by lizhaodong** [comment]
1.  folder structure:
![1](https://user-images.githubusercontent.com/1129767/77128268-72aa0e80-6a8a-11ea-9a95-75f1c56df737.png)
2. Running the command in the figure below still does not show the contents of the tensorboard,The red box shows the logpath.
![3](https://user-images.githubusercontent.com/1129767/77128411-fa901880-6a8a-11ea-8b19-2aad45489258.png)
3. nnictl trial ls:
![4](https://user-images.githubusercontent.com/1129767/77128487-3fb44a80-6a8b-11ea-8281-78572a957c81.png)
4. If I run this command, tensorboard shows the content:
![9](https://user-images.githubusercontent.com/1129767/77128666-e26cc900-6a8b-11ea-9f9c-088df3a985fd.png)

**Comment by lizhaodong** [comment]
@SparkSnail

**Comment by lizhaodong** [comment]
@SparkSnail This operation is also successful:
![110](https://user-images.githubusercontent.com/1129767/77129254-44c6c900-6a8e-11ea-8ccf-eaa21df4da2c.png)
![944](https://user-images.githubusercontent.com/1129767/77129368-c28ad480-6a8e-11ea-91f8-f14120cf7424.png)

**Comment by lizhaodong** [comment]
The reply has been submitted on git hub this morning。













At 2020-03-19 21:47:50, "SparkSnail" <notifications@github.com> wrote:

Hi @lizhaodong, I can not reproduce your issue. Could you please use nnictl trial ls to get the logPath of the trial, and show the folder structure here? Do you have a events.out.tfevents.** file in that log path?

**Comment by SparkSnail** [comment]
Hi @lizhaodong, could you please using the following command to install NNI, and run an `nnictl tensorboard` command again? I've add some debug info in this version of code.
```
git clone -b dev-debug https://github.com/SparkSnail/nni.git
cd nni
source install.sh
```

**Comment by lizhaodong** [comment]
@SparkSnail  My network is very poor, the external network resources download very slowly, estimated can not use this code to reproduce。

**Comment by lizhaodong** [comment]
@SparkSnail   How to execute this command in Windows 10 system？
                       source install.sh

**Comment by lizhaodong** [comment]
@SparkSnail   in window10 platform : cd  nni ;  powershell -ExecutionPolicy Bypass -file install.ps1 , right?

**Comment by SparkSnail** [comment]
Hi @lizhaodong , the installation commands in windows is 
```
git clone -b v1.4 https://github.com/Microsoft/nni.git
cd nni
powershell -ExecutionPolicy Bypass -file install.ps1
```
refer https://nni.readthedocs.io/en/latest/Tutorial/InstallationWin.html#installation

**Comment by lizhaodong** [comment]
git clone -b dev-debug https://github.com/SparkSnail/nni.git
cd nni
source install.sh
The command above has been successfully installed in ubuntu 18.04。
![QQ图片20200324183339](https://user-images.githubusercontent.com/1129767/77415846-04ed4200-6dfe-11ea-9b05-e07d042fe7ca.png)
The command in the red box still cannot display the content on the tensorboard, while the command in the green box can successfully display the content on the tensorboard.

**Comment by lizhaodong** [comment]
@SparkSnail  look at  above!

**Comment by SparkSnail** [comment]
how about `tensorboard --logdir name1:/home/{name}/nni/experiments/YUfUzvW7/trials/DtAql --port 8090`? I noticed that the only difference between NNI's commands and your command is that NNI's logdir has a `name1:` before the logdir.

**Comment by lizhaodong** [comment]
@SparkSnail  tensorboard --logdir name1:/home/{name}/nni/experiments/YUfUzvW7/trials/DtAql --port 8090
![636](https://user-images.githubusercontent.com/1129767/77490254-60a6e200-6e75-11ea-84fe-3899cdca71b5.png)
, run this command, it cannot display the content on the tensorboard.
result of execution:
![选区_141](https://user-images.githubusercontent.com/1129767/77490367-a1066000-6e75-11ea-9561-e415562a8cad.png)

**Comment by lizhaodong** [comment]
@SparkSnail  Ask a question: 
                          if machineList  have two IP , but neither of these IP machines has eth0, so 
                          nniManagerIp can be configured this way:
                                                                                   nniManagerIp : ip1, ip2

**Comment by SparkSnail** [comment]
> @SparkSnail Ask a question:
> if machineList have two IP , but neither of these IP machines has eth0, so
> nniManagerIp can be configured this way:
> nniManagerIp : ip1, ip2

Seems that the problem is caused by `tensorboard` command, your tensorboard does not support adding a `name1:` before logdir, what is your tensorboard's version?
nniManagerIp can only set one IP address, which is your nniManager machine's IP. machineList has two IPs, do you mean that you run NNI in remote mode? Don't need to set nniManagerIp for remote machines.

**Comment by lizhaodong** [comment]
@SparkSnail  my tensorboard version is  2.0.2

**Comment by lizhaodong** [comment]
@SparkSnail   Thank you ! What version of tensorboard should be set to?

**Comment by lizhaodong** [comment]
tensorboard  2.0.2 ：
![2558](https://user-images.githubusercontent.com/1129767/77603943-42f87c00-6f4c-11ea-9fe1-7b6737bdbe38.png)

**Comment by lizhaodong** [comment]
@SparkSnail   My tensorboard's version is 2.0.2 .
![343](https://user-images.githubusercontent.com/1129767/77605635-67565780-6f50-11ea-84a9-0d227cc652f5.png)
Running commands in the red box does not show the contents of the tensorboard, but running commands in the green box shows the contents of the tensorboard.

**Comment by SparkSnail** [comment]
Hi @lizhaodong , I've reproduced your issue, and checked that tensorboard 2.x support `--logdir_spec` command instead of `--logdir`, and I've give a hotfix pr https://github.com/microsoft/nni/pull/2242 to fix this issue.  
Thanks for your contribution to this issue.
