### ISSUE TITLE
Experiment log path is not user-defined 

### ISSUE THREAD

**Issue by JuneWangRL** [microsoft/nni#2195]
**Short summary about the issue/question**:
When using nni in remote server, the experiment log path is defined by the developer but not by the user in config.yml. This could cause error since user do not have the permission to write the file in the path in some situation.   
**Brief what process you are following**: 

![image](https://user-images.githubusercontent.com/37281306/77054021-24edc180-6a0a-11ea-98af-bff82cd3de3b.png)

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by JuneWangRL** [comment]
![image](https://user-images.githubusercontent.com/37281306/77054079-3fc03600-6a0a-11ea-99ba-11a40e263a71.png)

**Comment by QuanluZhang** [comment]
@JuneWangRL yes, you can configure this path, please refer to https://nni.readthedocs.io/en/latest/Tutorial/ExperimentConfig.html#logdir
