### ISSUE TITLE
nnictl trial ls

### ISSUE THREAD

**Issue by JuneWangRL** [microsoft/nni#2199]
**Short summary about the issue/question**:
I can use `nnictl trial ls` to get the output of the experiment infomation. I want to ask how could I get these information by using `port` of the experiment? The information I want to get is showed below. Hope for your answer!
![image](https://user-images.githubusercontent.com/37281306/77132092-1d292e00-6a99-11ea-8ff1-71b3ffc0f561.png)

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by SparkSnail** [comment]
Hi @JuneWangRL, I didn't get the point of your request, what's the meaning of `get these information by using port of the experiment`? There are some commands to get experiment information like `nnictl experiment`, `nnictl trial`, `nnictl log`, you could check thise commands from https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#log.

**Comment by JuneWangRL** [comment]
> Hi @JuneWangRL, I didn't get the point of your request, what's the meaning of `get these information by using port of the experiment`? There are some commands to get experiment information like `nnictl experiment`, `nnictl trial`, `nnictl log`, you could check thise commands from https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#log.

Hello @SparkSnail . Thanks for your reply. I am sorry that I may not express my question clearly. Now, I use one example to illustrate my problem so that you could understand my meaning. For example, if I want to  stop one experiment which is in port 8088, I could do that by using `nnictl stop --port 8088`. 
But if I run many experiments in one server, when I use `nnictl trial ls `,  I can only see the experiment ids which are running on the machine. So if I want to see the parameter inforamtion(like the picture I showed before) of one specific experiment, I could only use the command `nnictl  trial ls experiment id`. So my question is how could I see the experiment parameters through pointing the port. I see the command `nnictl trial ls --port 8088` is not functional to realize my goal.

**Comment by SparkSnail** [comment]
Hi @JuneWangRL, I see. In current design, `nnictl trial ls` does support setting port, and only support using `nnictl trial ls {experimentId}` to specify an experiment. If you forget the mapping between experiment and the port, you could use `nnictl experiment list` to get the port information of an experiment, and find the experimentId you want to use.
