### ISSUE TITLE
data for KDD Cup 2019 AutoML for Temporal Relational Data

### ISSUE THREAD

**Issue by Sandy4321** [microsoft/nni#2221]
great code thanks
only can you help to find data
KDD Cup 2019 AutoML for Temporal Relational Data
https://codalab.lri.fr/competitions/559
it is stated in 
https://github.com/SpongebBob/AutoTableGBDT

that you do have this data?

**Comment by xuehui1991** [comment]
Hello @Sandy4321. Thanks for your question.

We did have data, but consider the license, I think you could download from Kaggle or this [link](https://www.4paradigm.com/competition/kddcup2019#data)? 

Thank you and best wishes.

**Comment by Sandy4321** [comment]
It is the problem
Even after registration they do not share data
Since link on data download is broken
Can you contact them to ask to fix data link
Or 
Or change your code example to refer to valid data

**Comment by xuehui1991** [comment]
So sorry because I have no right to share the data.  But you could reference this [repo](https://github.com/SpongebBob/tabular_automl_NNI), it contains many valid data.

**Comment by scarlett2018** [comment]
Closing the issue as the answer had given.
