### ISSUE TITLE
code example FeatureEngineering/GradientFeatureSelector

### ISSUE THREAD

**Issue by Sandy4321** [microsoft/nni#2222]
do you have code example for
https://nni.readthedocs.io/en/latest/FeatureEngineering/GradientFeatureSelector.html
for
scikit learn

**Comment by xuehui1991** [comment]
hello @Sandy4321  please reference [here](https://github.com/microsoft/nni/blob/master/examples/feature_engineering/gradient_feature_selector/sklearn_test.py)

Thank you.

**Comment by scarlett2018** [comment]
Closing the issue as the question has been answered.
