### ISSUE TITLE
Is SlimPruner only available for PyTorch?

### ISSUE THREAD

**Issue by snippler** [microsoft/nni#2244]
from nni.compression.tensorflow import SlimPruner
results in the error
ImportError: cannot import name 'SlimPruner' from 'nni.compression.tensorflow'

so I'm wondering: is it only available for PyTorch?

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by QuanluZhang** [comment]
@snippler currently yes. The support of tensorflow on model compression is still ongoing, it is highly likely to be included in v1.6 release.

**Comment by scarlett2018** [comment]
Closing the question as it has been answered. @snippler thanks for supporting and watching NNI, we have continuous plan on model compression development, you are warmly welcome to provide your feedbacks in recent iteration plan: https://github.com/microsoft/nni/issues/2299 or the backlog: https://github.com/microsoft/nni/issues/1917. Feature requests or feedbacks to the model compression features are highly appreciated.
