### ISSUE TITLE
Just a quick question about NNI from tech logic

### ISSUE THREAD

**Issue by cqduan** [microsoft/nni#2263]
**Short summary about the issue/question**:

I do understand NNI could enable us to speed up the experiment. Any explanation for how NNI help users save computing resource? Thanks.

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by JSong-Jia** [comment]
Thanks for your question.  Here is a brief introduction of the NNI's efficiency.

Traditionally, scientists need to tune parameters manually to find the optimal combination of algorithm parameters, such as grid search and random search. The system continuously samples the possible parameter combination randomly, and tries to find the optimal parameter group through continuous iteration. However, the trial is independent of each other in this process. Thus it may take you more time and computing resources.

**NNI could tackle the issue with its built-in Tuner and Accessor.** The tuner built-in optimized efficient algorithm could be developed in the last round of better parameter interval to reduce parameter exploration times. Accessor could analyze the intermediate results of the Trial (such as the periodic accuracy of test data set) to determine whether the experiment needs to be terminated in advance or not. In another word, it could make adjustment quickly thus save computing resources.

In addition, **NNI's WebUI** provides a friendly **trial comparison function** that allows users to compare the results of different trials based on real-time data before the outcome of final result, and to decide whether it is necessary to end the trial early or not, which could also save computing resources.

Hope the answer is helpful.☺

**Comment by cqduan** [comment]
Ths answer is clear. Thanks！
