### ISSUE TITLE
[nni] When I try to run the trial examples with tensorflow, I got the bug 'ModuleNotFoundError: No module named 'nni.multi_phase''

### ISSUE THREAD

**Issue by Zhang-haotian** [microsoft/nni#2277]
![problem](https://user-images.githubusercontent.com/39946575/78686785-09e5e180-7926-11ea-9282-07a338b7a589.png)
As picture shows!

`ModuleNotFoundError: No module named 'nni.multi_phase'`

**Comment by Zhang-haotian** [comment]
I have been stuck in this BUG for a really long time. I'm sure I have installed the NNI package correctly.
I don't know if it's related to the version of tensorflow-gpu? /(ㄒoㄒ)/~~

**Comment by chicm-ms** [comment]
Hi @zhang-haotian,
Are you using the example `examples/tuners/enas_nni`?  This example is obsoleted and will be removed. The NAS functionality of nni has been refactored.
Please check our new NAS function here:
https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/Overview.md
https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/ENAS.md

**Comment by Zhang-haotian** [comment]
> Hi @Zhang-haotian,
> Are you using the example `examples/tuners/enas_nni`? This example is obsoleted and will be removed. The NAS functionality of nni has been refactored.
> Please check our new NAS function here:
> https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/Overview.md
> https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/ENAS.md
> 
> examples can be found here:
> https://github.com/microsoft/nni/tree/master/examples/nas

yes, I had try this examples. And it runs successfully, but I was thinking if there're some method could use the command 'nnictl create --config xxx.yml' to run this trail? I want to realize the WEB UI fuction.

**Comment by chicm-ms** [comment]
The enas_nni example can work with nni prior to v0.9. You do not need to use nnictl with new nas examples.  Would you please elaborate more about what kind of WEBUI function you are referring to?

**Comment by qtz93** [comment]
@chicm-ms Expect NAS series algorithm to add visual WEBUI. ^_^

**Comment by Zhang-haotian** [comment]
> The enas_nni example can work with nni prior to v0.9. You do not need to use nnictl with new nas examples. Would you please elaborate more about what kind of WEBUI function you are referring to?

@qtz93 @chicm-ms 

Yeah, I mean that the ENAS example could only be runned on terminal. But if I wanna to see the training result on the web just like when running the mnist examples using command 'nnictl create --config xxx.yml'.    :( 

I try to write the config.yml document, however, I could hard write the tuner.py. :( 👍

**Comment by chicm-ms** [comment]
Hi @Zhang-haotian , @qtz93 ,
nni v1.5 released, with brand new NAS WebUI:
https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/Visualization.md

**Comment by Zhang-haotian** [comment]
> Hi @Zhang-haotian , @qtz93 ,
> nni v1.5 released, with brand new NAS WebUI:
> https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/Visualization.md

Thanks @chicm-ms , I'm currently try to debug the Visualization module! 💪
