### ISSUE TITLE
Error reading data when running TensorFlow program in kubeflow mode

### ISSUE THREAD

**Issue by qtz93** [microsoft/nni#2284]
**Short summary about the issue/question**:
After installing and deploying the 0.6 version of kubeflow on a private kubenetes cluster, I was unable to successfully run the example in kubeflow mode under mnist-tfv1. When the NNI experiment is started, the log prompts that the data cannot be read successfully. 
**Remarks**: I used the docker image made by myself and uploaded it to the docker hub, which installed the CPU version of TensorFlow.

**Brief what process you are following**: 
Reference file ["Dockerfile"](https://github.com/microsoft/nni/blob/master/deployment/docker/Dockerfile), I created a Python3.6 version environment based on Ubuntu16.04, which installed some commonly used Python packages, including NNI (1.3). At first, I used the original file of mnist.py and got the following error:

```shell
vim /opt/data2/nfs_nni_share/nni/MUwYfbIg/H4SRl/output/worker_output/trialkeeper_stderr
# [2020-04-08 01:51:29.940952] INFO trial_keeper_version is 1.3
# [2020-04-08 01:51:29.940998] INFO nni_manager_version is 1.3
# [2020-04-08 01:51:29.941007] INFO Version match!
# Get exception HTTPConnectionPool(host='enp6s0f0', port=46002): Max retries exceeded with url: /api/v1/nni-pai/version/XfQ3cHdZ/O3rGw (Caused     by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70a96ed908>: Failed to establish a new connection: [Errno -2] Name or     service not known',)) when sending http post to url http://enp6s0f0:46002/api/v1/nni-pai/version/XfQ3cHdZ/O3rGw
# [2020-04-08 01:51:29.966035] INFO Trial keeper spawns a subprocess (pid 23) to run command: ['python3', 'mnist.py']
# ...
# Please write your own downloading logic.
# ...
# Please use tf.data to implement this functionality.
# <urlopen error [Errno 104] Connection reset by peer>
# ...
# File "mnist.py", line 161, in main
#     mnist = download_mnist_retry(params['data_dir'])
# ...
# urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
# Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
# Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
# ...
# [2020-04-07 10:19:21.009649] INFO subprocess terminated. Exit code is 1. Quit
# [2020-04-07 10:19:21.025906] INFO NNI trial keeper exit with code 1
# ...

```

I don’t quite understand the correct location of the data in the mnist.py file (the field data_dir). Is the data here stored in the container?
I tried to change a line of code in mnist.py, namely:
```shell
    parser.add_argument("--data_dir", type=str, default='/data/mnist_data', help="data directory")

```
And manually upload the data to the same directory in the container.

The error message in the log is very similar to the above, only **the sentence Extracting xxx/train-images-idx3-ubyte.gz is missing**.

I found that exiting the container and entering again, the uploaded data disappeared.

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.3
- nni mode(local|pai|remote): kubeflow
- OS: CentOS7.5
- python version: 3.6.7
- is conda or virtualenv used?: conda
- is running in docker?: yes

**need to update document(yes/no)**: yes

**Anything else we need to know**:
Can you tell me how to prepare the data? **Is it possible to prepare the data in advance?** Thanks ^_^.

**Comment by SparkSnail** [comment]
Hi @qtz93 , NNI's mnist-tfv1 example will download data autonomically in code, and do not need to prepare data in container, refer https://github.com/microsoft/nni/blob/master/examples/trials/mnist-tfv1/mnist.py#L151.  Your error message seems like internet error, could you please check if the following commands works on your environment?
```
from tensorflow.examples.tutorials.mnist import input_data
input_data.read_data_sets("/tmp/tensorflow/mnist/input_data", one_hot=True)
```

**Comment by qtz93** [comment]
@SparkSnail Hello, I am running the mnist-tfv1 example on a separate machine (this machine is dedicated to storing NNI's Trial code, independent of 4 cluster nodes). I have tried to run these two lines of code on this machine and cluster nodes, which can download data.

```shell
# NNI trial client
(base) [root@jaserver2 experiments]# ls /tmp/tensorflow/mnist/input_data/
t10k-images-idx3-ubyte.gz  t10k-labels-idx1-ubyte.gz  train-images-idx3-ubyte.gz  train-labels-idx1-ubyte.gz

# node1
(base) [root@master ~]# ls /tmp/tensorflow/mnist/input_data/
t10k-images-idx3-ubyte.gz  t10k-labels-idx1-ubyte.gz  train-images-idx3-ubyte.gz  train-labels-idx1-ubyte.gz
```

Do you mean that the mnist dataset will not only be downloaded to the /tmp/tensorflow/mnist/input_data/ directory of the container, but also to the /tmp/tensorflow/mnist/input_data/ directory of a node of the cluster or the /tmp/tensorflow/mnist/input_data/ directory of the nni client?

**Comment by SparkSnail** [comment]
No, your trial runs on a docker container in kubeflow mode, and the data will only be download to `/tmp/tensorflow/mnist/input_data/` in the container. So you only need to check if the data could be download in your docker container which started in kubernetes node.

**Comment by qtz93** [comment]
@SparkSnail Okay, thank you very much for solving my doubt. ~_~
