### ISSUE TITLE
Register customized tuner into builtin tuner and install from source

### ISSUE THREAD

**Issue by xingwangsfu** [microsoft/nni#2287]
Hi,
I implemented my own customized tuner, registered it as builtin tuner and installed from source. It worked. The installation took several minutes in macOs. However, it was extremely slow in my gpu server. It mainly halted at "# Installing Python SDK, processing nni"  and "yarn install v1.12.1
info No lockfile found.".

 I don't how to solve this problem. I also tried to set https_proxy and http_proxy. It could only accelerate the download of "nni-node" and "nni-yarn" packages. 

Actually, what I really want is to register my customized tuner as builtin one. Is there any other way instead of installing from source? In fact, my problem is quite similar to #1165. Is #1165 solved or not?

Thanks.

**Comment by QuanluZhang** [comment]
@xingwangsfu could you briefly state your scenario, why you want to make your tuner a builtin tuner rather than a customized tuner?

**Comment by xingwangsfu** [comment]
> @xingwangsfu could you briefly state your scenario, why you want to make your tuner a builtin tuner rather than a customized tuner?

So the scenario is I plan to integrate my own algorithm into nni and let my colleagues to use it. If I use the customized version, it is not very convenient and difficult to do the version control. The users have to manually add the code path, class name etc to the config file. Actually, these details are not necessary for them.

**Comment by QuanluZhang** [comment]
@xingwangsfu thanks for your response. The requirement is reasonable, we will consider improving this part.

**Comment by chicm-ms** [comment]
@xingwangsfu  for now,  as a temporary solution, you can have a try to build nni whl file by yourself using  nni/deployment/pypi

**Comment by chicm-ms** [comment]
@xingwangsfu   This feature has been released in v1.7.   Please try it out:
https://nni.readthedocs.io/en/latest/Tutorial/InstallCustomizedAlgos.html

**Comment by chicm-ms** [comment]
Closing since the feature is completed.
