### ISSUE TITLE
Error `nnictl stop --all` on windows

### ISSUE THREAD

**Issue by leckie-chn** [microsoft/nni#2288]
**Short summary about the issue/question**:
Error when executing `nnictl stop --all` on Windows

**Brief what process you are following**: 
```
python -m pip install nni
nnictl create --config config.yml
# wait until experiment ends
nnictl stop --all
```

**How to reproduce it**: 
```
python -m pip install nni
nnictl create --config config.yml
# wait until experiment ends
nnictl stop --all
```

**nni Environment**:
- nni version: 1.4
- nni mode(local|pai|remote): local
- OS: Windows 10 Enterprise (Version 1909)
- python version: 3.7.6
- is conda or virtualenv used?: No
- is running in docker?: No

**need to update document(yes/no)**: 

**Anything else we need to know**:
```python
INFO: Stoping experiment Si4Y6XNY
OSError: [WinError 87] The parameter is incorrect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\nnictl.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\nni_cmd\nnictl.py", line 219, in parse_args
    args.func(args)
  File "c:\program files\python37\lib\site-packages\nni_cmd\nnictl_utils.py", line 233, in stop_experiment
    kill_command(rest_pid)
  File "c:\program files\python37\lib\site-packages\nni_cmd\command_utils.py", line 38, in kill_command
    process.send_signal(signal.CTRL_BREAK_EVENT)
  File "C:\Users\yann\AppData\Roaming\Python\Python37\site-packages\psutil\__init__.py", line 292, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\yann\AppData\Roaming\Python\Python37\site-packages\psutil\__init__.py", line 1214, in send_signal
    self._proc.send_signal(sig)
  File "C:\Users\yann\AppData\Roaming\Python\Python37\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\yann\AppData\Roaming\Python\Python37\site-packages\psutil\_pswindows.py", line 872, in send_signal
    os.kill(self.pid, sig)
SystemError: <built-in function kill> returned a result with an error set
```

* related issue: [Unable to send CTRL_BREAK_EVENT](https://bugs.python.org/issue33245)

**Comment by moonriversg** [comment]
In function [kill_command(),](https://github.com/microsoft/nni/blob/d2c57770967fc14fe9d6172606b8c2e1903d4e3b/tools/nni_cmd/command_utils.py#L34)  pkg `psutil` is used and signal `CTRL_BREAK_EVENT` is sent to kill the process.

```
def kill_command(pid):
    """kill command"""
    if sys.platform == 'win32':
        process = psutil.Process(pid=pid)
        process.send_signal(signal.CTRL_BREAK_EVENT)
    else:
        cmds = ['kill', str(pid)]
        call(cmds)
```

However, in the [source code](https://github.com/giampaolo/psutil/blob/4d6a086411c77b7909cce8f4f141bbdecfc0d354/psutil/__init__.py#L1207) of pkg `psutil`,  it says that 

> On Windows only `SIGTERM` is valid and is treated as an alias  for kill().

Maybe it is because the incorrect signal caused the bug.

**Comment by SparkSnail** [comment]
> In function [kill_command(),](https://github.com/microsoft/nni/blob/d2c57770967fc14fe9d6172606b8c2e1903d4e3b/tools/nni_cmd/command_utils.py#L34) pkg `psutil` is used and signal `CTRL_BREAK_EVENT` is sent to kill the process.
> 
> ```
> def kill_command(pid):
>     """kill command"""
>     if sys.platform == 'win32':
>         process = psutil.Process(pid=pid)
>         process.send_signal(signal.CTRL_BREAK_EVENT)
>     else:
>         cmds = ['kill', str(pid)]
>         call(cmds)
> ```
> 
> However, in the [source code](https://github.com/giampaolo/psutil/blob/4d6a086411c77b7909cce8f4f141bbdecfc0d354/psutil/__init__.py#L1207) of pkg `psutil`, it says that
> 
> > On Windows only `SIGTERM` is valid and is treated as an alias  for kill().
> 
> Maybe it is because the incorrect signal caused the bug.

@leckie-chn, could you please try if `SIGTERM` works on your machine? Strangely, `SIGBREAK` signal works well on my windows environment.

**Comment by leckie-chn** [comment]
> > In function [kill_command(),](https://github.com/microsoft/nni/blob/d2c57770967fc14fe9d6172606b8c2e1903d4e3b/tools/nni_cmd/command_utils.py#L34) pkg `psutil` is used and signal `CTRL_BREAK_EVENT` is sent to kill the process.
> > ```
> > def kill_command(pid):
> >     """kill command"""
> >     if sys.platform == 'win32':
> >         process = psutil.Process(pid=pid)
> >         process.send_signal(signal.CTRL_BREAK_EVENT)
> >     else:
> >         cmds = ['kill', str(pid)]
> >         call(cmds)
> > ```
> > 
> > 
> > However, in the [source code](https://github.com/giampaolo/psutil/blob/4d6a086411c77b7909cce8f4f141bbdecfc0d354/psutil/__init__.py#L1207) of pkg `psutil`, it says that
> > > On Windows only `SIGTERM` is valid and is treated as an alias  for kill().
> > 
> > 
> > Maybe it is because the incorrect signal caused the bug.
> 
> @leckie-chn, could you please try if `SIGTERM` works on your machine? Strangely, `SIGBREAK` signal works well on my windows environment.

it works for me :)

**Comment by leckie-chn** [comment]
not able to reproduce now. might be triggered by multiple python versions on Windows.
