### ISSUE TITLE
web UI : Hyper-parameter page display problem

### ISSUE THREAD

**Issue by lizhaodong** [microsoft/nni#2293]
**Short summary about the issue/question**:
When multiple models are co-trained, the parameters of other models are also connected when the hyper-referenced page connects the parameters of this model via line segments.
**Brief what process you are following**: 

**How to reproduce it**: 
1. Run this project： nni/examples/trials/sklearn/regression
2. Configuration file selection config.yml

**nni Environment**: Ubuntu18.04 
- nni version: 1.14
- nni mode(local|pai|remote): local
- OS: Ubuntu18.04 
- python version: 3.6
- is conda or virtualenv used?:  no
- is running in docker?: no

**need to update document(yes/no)**:no

**Anything else we need to know**:
As shown in the figure: the red box is LinearRegression, but the red ellipse is not inside the parameters of the LinearRegression model.
![55](https://user-images.githubusercontent.com/1129767/78972509-8227ef00-7b40-11ea-9420-d9b8879b678c.png)

**Comment by lizhaodong** [comment]
![55](https://user-images.githubusercontent.com/1129767/78972738-08443580-7b41-11ea-9b54-f771fc642290.png)

**Comment by lizhaodong** [comment]
![55](https://user-images.githubusercontent.com/1129767/79084861-c4cc1000-7d68-11ea-872a-979dc41ec302.png)

**Comment by SparkSnail** [comment]
This example seems not designed very elegant, perhaps we should consider refactor this example or remove it.

**Comment by SparkSnail** [comment]
fixed in #2330
