### ISSUE TITLE
Trials failed when no space left on device

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2317]
Trials failed and the experiment stopped but no information on WEBUI. The relevant trial log file does not exist. Only use `nnictl view` can see the cause `OSError: [Errno 28] No space left on device`. It is better to show such errors in WEBUI.

**Comment by scarlett2018** [comment]
Thanks @colorjam for reporting the issue, this sounds a good suggestion. 

@Lijiaoa @chicm-ms - may you suggest about the dev effort needed here?

**Comment by colorjam** [comment]
There is Error Status on the Overview page.
