### ISSUE TITLE
Questions on the implementation of DARTS algorithm.

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#2322]
After reading the code of DARTS, I'm a little confused about the implementation of [this line of code](https://github.com/microsoft/nni/blob/f1ce1648b24d2668c2eb8fa02b158a7b6da80ea4/src/sdk/pynni/nni/nas/pytorch/darts/mutator.py#L42).

When the parameter of `LayerChoice` is initialized, you add an extra element (last line).
```python
class DartsMutator:
    def __init__(self,):
        ....
        self.choices = nn.ParameterDict()
        for mutable in self.mutables:
            if isinstance(mutable, LayerChoice):
                self.choices[mutable.key] = nn.Parameter(1.0E-3 * torch.randn(mutable.length + 1))
```

But in `sample_search()`, you return the parameter except for last element. I'm curious as to why you are designing this way, is there a purpose to it?

```python
class DartsMutator:
    ....
    def sample_search(self):
        result = dict()
        for mutable in self.mutables:
            if isinstance(mutable, LayerChoice):
                result[mutable.key] = F.softmax(self.choices[mutable.key], dim=-1)[:-1]
````

**Comment by ultmaster** [comment]
DARTS uses an extra Zero op to indicate no-connection. In the original DARTS code, you would see they have implemented a zero-op.   In our implementation, we don’t need to calculate it at all. But since this op still has architecture weight, we use extending and slicing.

**Comment by marsggbo** [comment]
I see. But it seems that there is a potential error. For example, Zero op indicates that for example a [0,0,0,0] will be returned. However, the `on_forward_layer_choice` function will return `None`, which is not supported for calculation in pytorch. So how do you solve this problem? Thanks!

**Comment by ultmaster** [comment]
You should check whether the function has returned None when you use it. I have to admit this is a little inconvenient. We did this because DARTS can actually choose none of these operators (block the edge) when exporting the final architecture. If we let users to write zero-op in their search space, we cannot know for sure which operator is zero.

**Comment by marsggbo** [comment]
Thanks very much!
