### ISSUE TITLE
How to save the quantized model?

### ISSUE THREAD

**Issue by Blue-Eagle-10** [microsoft/nni#2332]
@QuanluZhang, Excuse me, I installed NNI before and used quantization tools (including naive and QAT, BNN, dorefa), but I found it was simulated-quantization code. After running, it did not speed up inference of the model. How can I save the final quantized model, Used to speed up inference? thank you very much!

**Comment by QuanluZhang** [comment]
@Blue-Eagle-10 yes, the quantization algorithm is to find the best quantization strategy, it is based on simulation. We are working on speeding up compressed models by pruning or quantization. We have released [alpha version for pruning](https://nni.readthedocs.io/en/latest/Compressor/ModelSpeedup.html). Speeding up of quantization will be supported in future release.

**Comment by scarlett2018** [comment]
closing as speedup tool has been provided in previous release.
