### ISSUE TITLE
Random Tuner does not accept argument classArgs

### ISSUE THREAD

**Issue by seanytak** [microsoft/nni#2334]
**Short summary about the issue/question**:

**Brief what process you are following**: 
When specifying a config.yml

```yml
# config.yml
tuner:
  builtinTunerName: Random
  classArgs:
    optimize_mode: maximize
```

an error of

```bash
ERROR: Your config file is not correct, please check your config file content!
ERROR: Wrong key 'classArgs' in {'builtinTunerName': 'Random', 'classArgs': {'optimize_mode': 'maximize'}}
```
is returned from the command
```bash
nnictl create --config config.yml
```
Removing classArgs does appear to fix the issue but the docs say this should be an acceptable key

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.5
- nni mode(local|pai|remote): local
- OS: Ubuntu 18.04
- python version: 3.6.10
- is conda or virtualenv used?: conda
- is running in docker?: no

**need to update document(yes/no)**:
If this is a documentation error on [Random Tuner Docs](https://github.com/microsoft/nni/blob/master/docs/en_US/Tuner/BuiltinTuner.md#Random) yes, otherwise no

**Anything else we need to know**:
Per #903 this seems like a documentation error

**Comment by chicm-ms** [comment]
@seanytak   Thanks for reporting this issue, it is indeed a document error.
