### ISSUE TITLE
关于NNI的NAS Trainer的几个问题

### ISSUE THREAD

**Issue by JunweiSUN** [microsoft/nni#2337]
## 问题概述
您好，首先非常感谢你们对automl的贡献。目前我正在尝试将nni应用到我的项目中，但是对这个项目还不太了解，目前有几个问题想请教开发者团队。
1：如何同时搜索不同层数的结构。例如，我想同时对2层gnn和3层gnn进行搜索，每一层使用一个LayerChoice在几种gcn架构中选择一种。我目前想到的方法是，设置3个LayerChoice，其中一个中除了gcn架构外再加一个恒等函数，从而实现同时实现不同层数模型架构的搜索。但是这样看起来似乎不够优雅，在我想搜索的不同的层数比较多的时候代码量会很大。请问有没有更好的解决方法呢？

2：如何处理层之间的匹配问题。例如，在同一个LayerChoice中我加入了两种不同hidden_size的卷积层，如何保证该层能够自动识别输入的形状，并为之匹配相应的选择结果呢？（例如，LayerChoice中有in_channles分别为8和16的两个卷积层conv1_1和conv1_2，这时候输入数据的in_channels若为8，则只选择第一个卷积层进行搜索。）与之相似的一个问题是如果同一个LayerChoice中的层（gnn）接收的参数数量和类型不同（例如有的接受边的权重，有的不接受），应该如何同时在一个LayerChoice中进行搜索呢？

3：在NAS应用中，train是只会保存最优模型结构，不保存最优模型参数吗？

4：如何在训练时使用k折交叉验证以及设置时间限制（不使用nniclt只使用api）？是需要自己继承Train基类实现自己的trainer吗。

由于目前没有仔细阅读文档，可能以上提出的问题在nni中都有比较好的解决方案而我没有发现，希望开发者能够为我这些比较低级的问题指出一个方向。如果nni现在尚无某个问题的解决方案，我也非常愿意为这个项目贡献自己的一份力。

## 其他建议

**是否需要更新文档（是 / 否）** :希望文档能够有链接跳转到github的对应源码。
**其他分享内容** :

**Comment by ultmaster** [comment]
感谢您的提问。

1. 你可以把层数作为一个超参（跟学习率和 batch size 类似），然后结合 nnictl 启动对超参的联合调优，或者手动启动多个。不过利用 skipconnect 来实现模型深度的搜索，是 NAS community 中的一种常见做法（参考 ProxylessNAS, DARTS）。

2. 目前我们的 assumption 是说，你的输入喂到 layer choice 里的任意一个选择都是 ok 的。至于你说的约束问题的话，我们目前没有提供 interface 去实现。有两种解决方案：一种是去修改 trainer，在 trainer 的级别实现对于某些选择的过滤；一种是干脆把一些兼容的模块捆绑在一起（例如有两个 layer choice 一个是 1 2 选一个，一个是 3 4 选一个，然后你发现 1 必须接 3，2 必须接 4，那就是一个 layer choice，要么选 13 要么选 24）。

3. 你可以导出最优的模型参数，用 PyTorch 的 `torch.save` 就可以，跟传统的模型导出没有任何区别。

4. k-fold 你可以在 trainer 外面包一层（需要让 dataset_train 和 dataset_valid 都变成原来的数据集的一个子集，不知道是否容易），或者直接继承你想要的 trainer 进行修改，或者直接把 trainer 拷出来进行修改。

P.S. 文档跳转是一个不错的建议。

**Comment by JunweiSUN** [comment]
> I'll answer the questions in Chinese since the issue is posted in Chinese.
> 
> 感谢您的提问。
> 
> 1. 你可以把层数作为一个超参（跟学习率和 batch size 类似），然后结合 nnictl 启动对超参的联合调优，或者手动启动多个。不过利用 skipconnect 来实现模型深度的搜索，是 NAS community 中的一种常见做法（参考 ProxylessNAS, DARTS）。
> 2. 目前我们的 assumption 是说，你的输入喂到 layer choice 里的任意一个选择都是 ok 的。至于你说的约束问题的话，我们目前没有提供 interface 去实现。有两种解决方案：一种是去修改 trainer，在 trainer 的级别实现对于某些选择的过滤；一种是干脆把一些兼容的模块捆绑在一起（例如有两个 layer choice 一个是 1 2 选一个，一个是 3 4 选一个，然后你发现 1 必须接 3，2 必须接 4，那就是一个 layer choice，要么选 13 要么选 24）。
> 3. 你可以导出最优的模型参数，用 PyTorch 的 `torch.save` 就可以，跟传统的模型导出没有任何区别。
> 4. k-fold 你可以在 trainer 外面包一层（需要让 dataset_train 和 dataset_valid 都变成原来的数据集的一个子集，不知道是否容易），或者直接继承你想要的 trainer 进行修改，或者直接把 trainer 拷出来进行修改。
> 
> P.S. 文档跳转是一个不错的建议。

您好，我还有两个问题
第一个是我发现用LayerChoice包住的层，在forward的时候没办法用默认值传参。比如我的GCNCell里面有一个叫a的参数，平常我可以通过GCN(data, a=xxx)来进行forward，但是用LayerChoice包住之后只能通过GCN(data, xxx)来调用了，如果用GCN(data, a=xxx)会提示unexpected keword argument.
第二个是为什么一个模型中所有LayerChoice的候选者数目要强制规定相等呢？例如第一层有两个选项，第二层有三个选项，搜索空间为2X3，我认为这完全是可能的。

**Comment by ultmaster** [comment]
第一个，是因为 LayerChoice 没有允许 **kwargs，这个是完全可以做到的，我们会进行相应的改进。谢谢您的建议。

第二个，我们没有禁止 “第一层有两个选项，第二层有三个选项”。不知道您为什么会遇到这个限制。

**Comment by JunweiSUN** [comment]
> 第一个，是因为 LayerChoice 没有允许 **kwargs，这个是完全可以做到的，我们会进行相应的改进。谢谢您的建议。
> 
> 第二个，我们没有禁止 “第一层有两个选项，第二层有三个选项”。不知道您为什么会遇到这个限制。

您好，感谢您的回复。
对第二个问题，具体来说我们在ENAS中遇到了这个Error：
AssertionError: ENAS mutator requires all layer choice have the same number of candidates.
由于我们对ENAS算法并不是很熟，这个问题是否是ENAS算法本身的限制呢？

**Comment by ultmaster** [comment]
对，这是 ENAS 算法的限制。ENAS 论文的作者并没有指出 layer choice 在拥有不同的 candidate 数量的时候应该怎么办，所以我们也没有实现。

如果你有办法把 ENAS 扩展到支持不同数量的 candidate 的话，也欢迎提出。不考虑这种比较复杂的方案的话，我能想到的就是，或许你可以在后面加一些没用的 candidate 让所有 layer choice 都等长。

**Comment by kvartet** [comment]
I’m closing this issue as it has no updates from customer for 3 months, please feel free to reopen if you are still seeing it an active issue.
