### ISSUE TITLE
Update "issue" template to ask for nnimanager.log and dispatcher.log

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#2344]
In addition to the current "Create Issue" template info, we might need to add an ask to users to provide:
- nnimanager.log and dispatcher.log
- nnictl stdout and stderr

Add a reference about how to get these logs.

**Comment by scarlett2018** [comment]
@Lijiaoa

**Comment by Lijiaoa** [comment]
> @Lijiaoa

I will send a PR today!

**Comment by Lijiaoa** [comment]
related PR https://github.com/microsoft/nni/pull/2355

**Comment by scarlett2018** [comment]
> related PR #2355

@Lijiaoa - this issue is not for student program issues but for general NNI issues.

**Comment by Lijiaoa** [comment]
Oh, I put the student program issue and general issue template together. This changes are all in PR #2355.

**Comment by kvartet** [comment]
I’m closing this issue as we have solved the problem.
