### ISSUE TITLE
Update "student program" template 

### ISSUE THREAD

**Issue by JSong-Jia** [microsoft/nni#2345]
Shall we update the template like:
## NNI 学生项目问题概述（中文版）

**请简要概述您的问题 / 观点** :

**请提供 NNI 环境信息**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

## 其他建议

**是否需要更新文档（是 / 否）** :
**其他分享内容** :

## General Question for NNI Student Program (English Version)

**Short summary about the question / idea** :

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:
## Other Advice
**Need to update document ( yes / no )** :
**Anything else we need to know** :

**Comment by scarlett2018** [comment]
@Lijiaoa

**Comment by Lijiaoa** [comment]
had updated in PR: https://github.com/microsoft/nni/pull/2349

**Comment by Lijiaoa** [comment]
@kvartet Could you help close this issue? It had been done a long time ago.
