### ISSUE TITLE
Improve output of model after apply_fixed_architecture

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2352]
Currently, print(model) show LayerChoice. Print the fixed modules would be better.

![image](https://user-images.githubusercontent.com/23700012/79743912-098f1280-8338-11ea-9574-c575a7b4fedb.png)

**Comment by ultmaster** [comment]
Good suggestion. This issue has been already addressed in #2336, but the PR is still under review.

**Comment by ultmaster** [comment]
Duplicate of #2316.
