### ISSUE TITLE
nni的超参搜索是否有类似于nas的one shot API

### ISSUE THREAD

**Issue by JSong-Jia** [microsoft/nni#2353]
## NNI 学生项目问题概述

**请简要概述您的问题 / 观点** :

nni的超参搜索有类似于nas的one shot的api吗？
目前有个需求是实现个接口，数据传进来 模型跑完之后把结果返回。如果用nnictl的话好像需要先把数据保存下来，然后nnictl的trial文件加载数据，搜索完成再把超参组合保存下来，接口再把参数load进来训练最终的模型，如果有api的话就可以直接在接口里面搜索了。

## 其他建议

**是否需要更新文档（是 / 否）** :
**其他分享内容** :

## General Question

**Short summary about the question / idea** :

## Other Advice
**Need to update document ( yes / no )** :
**Anything else we need to know** :

**Comment by ultmaster** [comment]
有。看文档：https://nni.readthedocs.io/en/latest/NAS/Overview.html

**Comment by kvartet** [comment]
I’m closing this issue as it has no updates from user for 3 months, please feel free to reopen if you are still seeing it an active issue.
