### ISSUE TITLE
关于NAS的搜索结果以及webui的ip指定

### ISSUE THREAD

**Issue by Kwongrf** [microsoft/nni#2356]
## 问题概述

**请简要概述您的问题 / 观点** :
你好，关于NAS我有一些疑问：
1. 为什么我两次运行同一份代码进行NAS得到的最优架构却不一样，即使我把seed都固定了（我使用的是ENAS），如果NAS搜索得到的是最合适的架构，不应该不一样吧？
我看源码中ENASMutator的sample_final()就是调用了一次sample_search，所以搜索结束得到的最优架构是不是就是ENASMutator最后的一次取样，而并不一定是在验证集上最优的架构？

2. 我用xshell连接到服务器上进行超参搜索（对服务器来说是local模式）想看webui，得到的ip是127.0.0.1:8080，导致我无法在我的笔记本上通过服务器ip访问到nni的webui，想问一下是否能够修改local模式下的host为0.0.0.0？（类似于tensorboard）,使我能通过服务器的ip访问到webui

## 其他建议

希望超参搜索也能在不运行nnictl create的情况下进行，像one-shot的NAS一样，对于网络结构的超参一些可以用one-shot的NAS，但是像学习率、weight-decay这种就必须通过nnictl create。

**是否需要更新文档（是 / 否）** :
**其他分享内容** ：

**Comment by ultmaster** [comment]
1. 很有可能是因为你的 seed 没有完全固定。pytorch 要固定好几个 seed 并且关掉一个 benchmark。如果这个问题还是存在的话，你可以检查一下两次运行在什么时间点就开始不一样了。

2. 如果网络配置没有问题的话，你应该是能够通过 server_ip:8080 直接访问的（就算显示的是 127.0.0.1）。如果不能的话，想问下你 server 的 OS 环境是什么？我们可以增加一个 --host 选项，但是我不确定有没有必要。@ShinaiYang

About 其他建议：这个是有悖于我们的 design 的。这个看你需求是什么。如果你的需求仅仅是想要在运行起来之后 block 住，不要让程序自动退出的话，你可以试试 --foreground 模式。如果你的需求是想要自动化 nni 启动搜索收集结果的整个 pipeline 的话，可以试试 nnicli。

**Comment by Kwongrf** [comment]
感谢！
1. seed我都设置好了，可能是因为我使用了pytorch_geometric，我看那边[issue](https://github.com/rusty1s/pytorch_geometric/issues/859)有人说是因为torch scatter使用很多原子操作无法保证每次一样...我的损失曲线确实是从一开始就不一样。
2. 之后又可以访问了，应该是我代码的问题，抱歉

我试试nnicli，感谢你

**Comment by kvartet** [comment]
I’m closing this issue as it has no updates from user for 3 months, please feel free to reopen if you are still seeing it an active issue.
