### ISSUE TITLE
NameError: name '_DataLoaderIter' is not defined

### ISSUE THREAD

**Issue by JunweiSUN** [microsoft/nni#2360]
## 问题概述

**请简要概述您的问题 / 观点** :
您好，在用nni的特征工程模块的时候发现了这个import error，与 #2026 描述的相同。我的torch版本是1.2.0。

在import以下模块：
from nni.feature_engineering.gradient_selector import FeatureGradientSelector
报了这个错误
NameError: name '_DataLoaderIter' is not defined

据#2026描述，这是因为torch1.0以上不再有_DataLoaderIter。
请问近期有修复这个问题的计划吗？以及pip仓库什么时候能更新修复之后的版本呢？如果目前暂无修复计划，请问如何修改代码能够绕开这个问题吗？

## 其他建议

**是否需要更新文档（是 / 否）** :
**其他分享内容** :

**Comment by xuehui1991** [comment]
Hello @JunweiSUN .

I think you could install the right torch version or you could reference this PR:
https://github.com/microsoft/nni/pull/2026/files
to fix this problem.

Do not forget to import the _util file. (that why this PR can't work)

**Comment by kvartet** [comment]
I’m closing this issue as it has no updates from user for 3 months, please feel free to reopen if you are still seeing it an active issue.
