### ISSUE TITLE
关于Network Morphism Tuner输入shape的疑问

### ISSUE THREAD

**Issue by GuileCyclone** [microsoft/nni#2363]
## 问题概述

你好，我最近正在尝试利用Network Morphism Tuner寻找最佳网络，但我面临着一个问题：现有的Network Morphism Tuner功能中，只支持W*W*C的输入，我的数据集是(1,1024,2)的输入,我曾经尝试将数据集reshape为(32,32,2)以通过使用Network Morphism Tuner进行网络搜索，但这带来的问题是准确率大幅下降（由固定网络的95%降至Network Morphism Tuner搜索到网络的81%），请问后续是否考虑支持H*W*C形式的输入？谢谢！

## 其他建议

**是否需要更新文档（是 / 否）** :是
**其他分享内容** :在https://github.com/microsoft/nni/blob/master/docs/zh_CN/Tuner/NetworkmorphismTuner.md
中第3节文件结构中针对bayesian.py文件的说明存在错字，我个人猜测：“bayesian.py 是用来基于已经搜索**道德**模型来预测未知模型指标的贝叶斯算法。"应为“bayesian.py 是用来基于已经搜索**到的**模型来预测未知模型指标的贝叶斯算法。”

**Comment by xuehui1991** [comment]
Hello @GuileCyclone .

Thanks for your GOOD suggestion. But I think you propose a new feature but we don't have plan to change it recently. But we welcome all the contributors to improving all the algorithms together.
Does any possible that you help us to improve these code(supporting input with HWC shape)? 

Thanks again.

Best wishes,
HUI.

**Comment by GuileCyclone** [comment]
> Hello @GuileCyclone .
> 
> Thanks for your GOOD suggestion. But I think you propose a new feature but we don't have plan to change it recently. But we welcome all the contributors to improving all the algorithms together.
> Does any possible that you help us to improve these code(supporting input with HWC shape)?
> 
> Thanks again.
> 
> Best wishes,
> HUI.

Hello @xuehui1991 .

I'm glad to receive the invite for contributing. I'm sorry that since I am not a professional programmer, my programming ability can only support me to read the code, instead of rewriting it. I'll try to change the code in private. If it has the possibility that the changed code will work successfully,I'll commit in this issue immediately.

Thanks for your reply.

 
--
