### ISSUE TITLE
Guidelines to handle large files in codeDir

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#2364]
AzureML's practice on handling large files for reference: https://github.com/Azure/MachineLearningNotebooks/issues/288#issuecomment-495233480

Keypoints:

* Total size <= 300MB, file number <= 2000. This limit can be overwritten with config file.
* Won't pack files matching rules in .gitignore. If .amlignore exists, it will be used instead of .gitignore.
* Source directory will be packed into a zip before each experiment, which is called a **snapshot** of the experiment. It's kept unchanged even if code directory has been modified.

NNI's effort:

* There is limit on total number of files, but no limit on total size (needs double-check).
* No support on ignore some files and folders.
* #1577 has proposed a hot-fix. However nnidev believes it's unacceptable.
* Snapshot is taken by training services like remote (once per experiment) and PAI (once per trial), but in local, no snapshots are taken. Snapshots are not exposed to users, not mentioned in documentation either.

Snapshots in local training service:

* **Pros:** Users will be able to check an experiment in the past. Changes made during experiments will not affect the undergoing experiment itself.
* **Cons:** As the experiment would be launched in another directory, hard-coded links will be broken. Also, if users rely on the behavior of "hot-update" of experiment code, it will bring extra efforts.

Current workarounds (to all issues mentioned above):

* Initiate an empty directory as codeDir and use `git clone` as the first command of a trial.

**Comment by kvartet** [comment]
Seems it had been merged, so I closed this issue. Feel free to reopen it.
