### ISSUE TITLE
nnictl export error

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2373]
When export an experiment `nnictl experiment export owfzdUfG -f /mnt/chenqian/RetinaFace/eff_search_05.json -t json` shows the error:

`ERROR: Restful server is not Running`

While using `nnictl view owfzdUfG --port 30022` can show the WebUI.

**Comment by colorjam** [comment]
After view the experiment, it can be exported.

**Comment by QuanluZhang** [comment]
is owfzdUfG stopped before you export?

**Comment by colorjam** [comment]
Yes. After `nnictl view owfzdUfG` it works fine. I will close this issue.
