### ISSUE TITLE
BUG in spos evolution part

### ISSUE THREAD

**Issue by xingwangsfu** [microsoft/nni#2374]
I trained the spos from scratch with supernet.py, but failed to load the checkpoints. It turned out there was a mismatch between load and save part. 

In  the save part  https://github.com/microsoft/nni/blob/69dfbf5e976cf75e89949af4764928dde631a3f6/src/sdk/pynni/nni/nas/pytorch/callbacks.py#L136,  no dict was used. But in the load part,  https://github.com/microsoft/nni/blob/69dfbf5e976cf75e89949af4764928dde631a3f6/examples/nas/spos/network.py#L151,  key 'state_dict' was used. It failed to load the checkpoint. After removing 'state_dict', checkpoint could be loaded and problem was solved.

**Comment by scarlett2018** [comment]
Thanks @xingwangsfu !

@ultmaster  may you help to confirm whether this is a bug and is @xingwangsfu 's fix okey for submit a PR directly?
