### ISSUE TITLE
How to create an experiment without binding a port.

### ISSUE THREAD

**Issue by terrencewayne** [microsoft/nni#2378]
Hi, I want to create an experiment without binding a port, not even the default 8080, for security issues of  my institution. But I can't do this with nnictl command. Is there any approaches to avoid binding a port?

**Comment by ultmaster** [comment]
Hi. Could you provide more information on what's the blocking issue on creating an experiment with a port? The experiment cannot start at all? Or experiment seems starting ok and you cannot access WebUI? If it's the latter case, can you confirm, with nnictl, is your experiment running and your trials running?

**Comment by terrencewayne** [comment]
Thanks for reply. Maybe I didn't make it clear. I can start an experiment and WebUI is fine. 
Thing is, for sake of **data security**, I don't want to use the WebUI. I even don't want to make training information exposed to some port (default is 8080).
So I wonder if there any methods to start an experiment without a port?

**Comment by terrencewayne** [comment]
> 
> 
> Hi. Could you provide more information on what's the blocking issue on creating an experiment with a port? The experiment cannot start at all? Or experiment seems starting ok and you cannot access WebUI? If it's the latter case, can you confirm, with nnictl, is your experiment running and your trials running?

**Comment by terrencewayne** [comment]
> 
> 
> Hi. Could you provide more information on what's the blocking issue on creating an experiment with a port? The experiment cannot start at all? Or experiment seems starting ok and you cannot access WebUI? If it's the latter case, can you confirm, with nnictl, is your experiment running and your trials running?

Thanks for reply. Maybe I didn't make it clear. I can start an experiment and WebUI is fine.
Thing is, for sake of data security, I don't want to use the WebUI. I even don't want to make training information exposed to some port (default is 8080).
So I wonder if there any methods to start an experiment without a port?

**Comment by scarlett2018** [comment]
You want to disable WebUI for your institution security considerations on Web URL exposure, is it right?

**Comment by terrencewayne** [comment]
> 
> 
> You want to disable WebUI for your institution security considerations on Web URL exposure, is it right?

Yes it is.

**Comment by scarlett2018** [comment]
> You want to disable WebUI for your institution security considerations on Web URL exposure, is it right?

@SparkSnail @liuzhe-lz ^^ can we?

**Comment by SparkSnail** [comment]
> > You want to disable WebUI for your institution security considerations on Web URL exposure, is it right?
> 
> @SparkSnail @liuzhe-lz ^^ can we?

NNI need to start a restful server, which will be accessed from NNICTL and WEBUI to control experiments, the port of the restful server is same with WEBUI, default value is 8080. There is no method to create an experiment without binding a port in current design of NNI. @terrencewayne if you do not want to expose the url to other environment, how about using firewall to block the machine's port, then you can not access webui outside of the machine, while you could control NNI experiments from the machine using NNICTL commands.

**Comment by terrencewayne** [comment]
> 
> 
> > > You want to disable WebUI for your institution security considerations on Web URL exposure, is it right?
> > 
> > 
> > @SparkSnail @liuzhe-lz ^^ can we?
> 
> NNI need to start a restful server, which will be accessed from NNICTL and WEBUI to control experiments, the port of the restful server is same with WEBUI, default value is 8080. There is no method to create an experiment without binding a port in current design of NNI. @terrencewayne if you do not want to expose the url to other environment, how about using firewall to block the machine's port, then you can not access webui outside of the machine, while you could control NNI experiments from the machine using NNICTL commands.

Yes, I do think iptables strategies can help. Thanks for reply and suggestions.
