### ISSUE TITLE
Visualization error

### ISSUE THREAD

**Issue by guoshu6699** [microsoft/nni#2380]
We searched through our own dataset, but we had problems with NAS visualization.
 Execute command：
nnictl webui nas --logdir logs/<current_time_stamp> --port <port>

Error: Cannot create a string longer than 0x3fffffe7 characters
How should we solve this error?
Thank you!

**Comment by ultmaster** [comment]
Did you actually type “nnictl webui nas --logdir logs/<current_time_stamp> --port”? You should change logdir to a real log folder and port to a real port.

**Comment by ultmaster** [comment]
@guoshu6699 Hi, it has been several weeks. Any updates?
