### ISSUE TITLE
nni trials silently failing / closing

### ISSUE THREAD

**Issue by p3jawors** [microsoft/nni#2381]
Hello, I have recently started getting a very odd bug that I can not sort out. When I try to run any test in `nni` it will run the first trial fine, but stop the experiment afterwards, regardless of what I set for `trialConcurrency`. I do not get any error or warning printouts, the gui shows the tests as started in the details tab, but the time never updates. If I refresh at this point it shows that the connection is refused / lost. The log files for the first trial that runs all look fine, no errors or odd behaviour. I get the second trials folder created, but it is empty. If I try to run any `nnictl` commands I get the `There is no experiment running...` printout

I had recently made changes to my function that I was testing, but even going back to previous versions that worked a few days ago no longer work. I have made a very simple script that does not work for me, but I have had others test on their machines and it does work.

I have attached the yaml, json, and py scripts here.
[nni_test.zip](https://github.com/microsoft/nni/files/4541782/nni_test.zip)
If you change the `logDir` and `run` paths to where you extract, you can run it with a `nnictl create --config /YOUR_PATH/test.yaml`

I have tried this in a new anaconda environment with 
`conda create --name test python==3.5.2` 
and only installing `nni` through `pip`

The only thing that has changed on my side is that I have just replaced my router, but I do not know if this could affect anything in `nni` (firewall issues possibly?)

**Comment by scarlett2018** [comment]
@p3jawors  - thanks for the feedback, may you provide more info about your NNI environment?

**nni Environment:**

nni version:
nni mode(local|pai|remote):
OS:
python version:
is conda or virtualenv used?:
is running in docker?:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by liuzhe-lz** [comment]
The experiment files look fine.
I believe the framework crashed after running first trial. Please share your framework log file in `~/nni/experiments/<EXPERIMENT_ID>/log/`

**Comment by p3jawors** [comment]
Thank you both for the quick replies. I am running 
`nni == 1.5`
`nni_mode == local`
`OS == Ubuntu 16.04`
`python==3.5.2`
using anaconda, no docker

Here are the two log files you asked for.
[dispatcher.log](https://github.com/microsoft/nni/files/4545870/dispatcher.log)
[nnimanager.log](https://github.com/microsoft/nni/files/4545871/nnimanager.log)
From `~/nni/experiments/<ID>/trials` I can see the results from the first test fine, the second test creates a folder, but it is empty, then I get nothing else passed that.

**Comment by p3jawors** [comment]
Just as an extra debugging step, I've tried with a fresh anaconda install and new environment, but still am having the same issues.

**Comment by scarlett2018** [comment]
> Just as an extra debugging step, I've tried with a fresh anaconda install and new environment, but still am having the same issues.

Thanks @p3jawors for keep trying and sorry for hear it still not working. @liuzhe-lz any hints from the logs?

**Comment by liuzhe-lz** [comment]
The framework log shows nothing special.
Please check nnictrl's stdout/stderr via `nnictl log stdout` and `nnictl log stderr`.
And if they are empty, please retry the experiment in debug mode (`nnictrl create --debug ...`)

**Comment by wanyanchen** [comment]
I meet the same thing, and don't know how to solve it. At first, the experiment runs and everything is normal, then after about 1h or more, it suddenly stopped and the log shows nothing is error.

**Comment by p3jawors** [comment]
This issue had resolved on its own without any changes other than booting into windows, then back into Ubuntu. This has come up again and I've tried restarting, reinstalling nni (both pip install and from source). I've tried on another machine with the same environment and repository I'm testing and it works. To reiterate...

My nni sweeps have been failing silently on the first test. It seems to start fine, but then I'll get a network error print out on the top of the web gui. I don't see any errors in the stderr log and the trial log looks like the experiment ran to completion for the 1 trial. If I run it in debug mode and check the displatcher.log I get this at the end of the file...
[07/29/2020, 09:29:44 AM] DEBUG (nni.protocol/MainThread) Pipe EOF encountered  
[07/29/2020, 09:29:44 AM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[07/29/2020, 09:29:47 AM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager

This seems similar to https://github.com/microsoft/nni/issues/2243 however, I am running on `nni==1.7` when pip installed, and `nni==1.7-35-g2e4a9d9` when installed from source. `stderr` is blank and my `trial.log` has all the printouts for the one test as expected.
[dispatcher.log](https://github.com/microsoft/nni/files/4995593/dispatcher.log)
[nnimanager.log](https://github.com/microsoft/nni/files/4995594/nnimanager.log)

**Comment by p3jawors** [comment]
After further debugging it looks like it has something to do with a port conflict with Dropbox. Is there a way to set the default port nni uses to something other than `8080`?

**Comment by scarlett2018** [comment]
> After further debugging it looks like it has something to do with a port conflict with Dropbox. Is there a way to set the default port nni uses to something other than `8080`?

@p3jawors -  try the `port` option in nnictl:
`nnictl create --config nni/examples/trials/mnist-tfv1/config.yml --port 8088`

**Comment by kvartet** [comment]
@p3jawors @wanyanchen I’m closing this issue as it has no updates from user for 3 months, please feel free to reopen if you are still seeing it an active issue.

**Comment by WANGBohaO-jpg** [comment]
i meet the same problem, when i start the experiment, it will stop silently without any error info

**Comment by BitCalSaul** [comment]
i meet the same problem.
