### ISSUE TITLE
关于 Restful server start failed的问题

### ISSUE THREAD

**Issue by 99hansling** [microsoft/nni#2383]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**

····使用测试用例的时候输入nnictl create --config nni\examples\trials\mnist-tfv1\config_windows.yml
出现Restful server start failed的问题：

····由于我本机装的tensorflow2，因此我的输入命令是nnictl create --config G:\UNIVERSITY\nni-master\examples\trials\mnist-tfv2\config_windows.yml

····最开始启动restful server的时候弹出了允许node.js的消息，我允许了，也出现了错误。后来在管理员权限下运行也不行。

····因此想知道，restful server failed可能是那里出现的问题

····非常感谢！

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:1.5
- nni mode(local|pai|remote):local
- OS:windows10
- python version:3.7
- is conda or virtualenv used?:no
- is running in docker?:no

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

C:\WINDOWS\system32>nnictl create --config  G:\UNIVERSITY\nni-master\examples\trials\mnist-tfv2\config_windows.yml
INFO: expand searchSpacePath: search_space.json to G:\UNIVERSITY\nni-master\examples\trials\mnist-tfv2\search_space.json
INFO: expand codeDir: . to G:\UNIVERSITY\nni-master\examples\trials\mnist-tfv2\.
INFO: Starting restful server...
ERROR: Restful server start failed!
INFO:  Stdout:
-----------------------------------------------------------------------
                Experiment start time 2020-04-28 17:37:17
-----------------------------------------------------------------------

INFO:  Stderr:
-----------------------------------------------------------------------
                Experiment start time 2020-04-28 17:37:17
-----------------------------------------------------------------------
 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by 99hansling** [comment]
已经解决，将windows system32/driver/etc/host中的localhost 127.0.0.1 前面的注释去掉即可

**Comment by kingaza** [comment]
@99hansling 我遇到同样的问题，然后把`127.0.0.1 localhost`前面的注释去掉，可是问题依然存在。请问你是怎么定位和解决这个问题的呢？谢谢啊
