### ISSUE TITLE
使用colab进行NNI实验的问题

### ISSUE THREAD

**Issue by 99hansling** [microsoft/nni#2393]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**

***由于本机性能问题，跑实验的时候CPU会满，目前没有实验室，也没有其他可以用的机器，所以在尝试使用colab进行试验。
虽然在colab中可以进行，但是无法使用弹出的WEB UI中的ip地址

***之后我在View Web UI in Google Colab #1580中，看到了解决办法，
```
! npm install -g localtunnel
! pip install nni
! git clone https://github.com/microsoft/nni
get_ipython().system_raw('nnictl create --config nni/examples/trials/mnist/config.yml --port 5000 2>&1 &')
import time
time.sleep(10)
get_ipython().system_raw('lt --port 5000 >> url.txt 2>&1 &')
time.sleep(5)
! cat url.txt
```
***但是使用了get_ipython().system_raw()之后，colab没有反应，也没有回显，只有采用!nnictl create --config nni/examples/trials/mnist/config.yml --port 5000 2>&1 & 的时候才可以，我的第一个问题是，不知道这两种方式在colab中是否一样呢？

***另外当我执行了
'''
time.sleep(10)
!lt --port 5000 >> url.txt 2>&1 &
time.sleep(5)
! cat url.txt
'''
之后，它会执行一段时间，但是执行完后并没有回显。我本来以为是出现了什么问题，但实际上
执行
‘’‘
!nnictl create --config nni/examples/trials/mnist/config.yml --port 5000 2>&1 & 
’‘’
指令后，是可以通过
‘’‘
!nnictl top
‘’‘
来查看运行状态的，
于是我猜测，之所以
’‘’
! cat url.txt
‘’‘
没有反应是因为实验没有完成吗？ 是只有实验完成之后，我才能看到回显给我的ip地址，从而进入web url吗？ 有没有其他办法快速进入web url呢？

期待您的回答！非常感谢！

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:1.5
- nni mode(local|pai|remote):local(在colab上）
- OS:colab里面的linux
- python version:直接使用colab
- is conda or virtualenv used?:
- is running in docker?:

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by 99hansling** [comment]
另外，发现使用
’‘’
!lt --port 8889
‘’‘
会一致处于运行状态，没有输出结果。

我本来以为可能是npm和node.js版本不统一的问题，但是在升级到npm6并与node 10同意之后，
该命令也还是会一直运行。是现在已经用不了tunnel了吗？

**Comment by ultmaster** [comment]
你可以去找找看别的需要 tunnel 的 application。比如 visdom，这种库用的人会更 popular 一点，你可以看看用这种方法能不能把 visdom 跑起来，如果不行的话看看他们的 issue 里有没有相关的解决方案。

由于我们没有提供 native 的 colab 解决方案，所以麻烦你先调研一下。如果还是存在困难（比如 visdom 能跑但 nni 跑不了）的话，我们可以提供力所能及的帮助。

**Comment by gm3g11** [comment]
> 另外，发现使用
> ’‘’
> !lt --port 8889
> ‘’‘
> 会一致处于运行状态，没有输出结果。
> 
> 我本来以为可能是npm和node.js版本不统一的问题，但是在升级到npm6并与node 10同意之后，
> 该命令也还是会一直运行。是现在已经用不了tunnel了吗？

你好，请问你最后解决了吗？我也遇到相同的问题了，tunnel一直运行，谢谢

**Comment by JunweiSUN** [comment]
hi, @99hansling 请问后来有继续关注这个问题吗？也许你会有兴趣加一下我们的微信用户群，我们可以在群里交流一下~

**Comment by JunweiSUN** [comment]
hi, @99hansling @gm3g11 我们提供了新的在colab上面使用NNI WebUI的解决办法，详见https://nni.readthedocs.io/en/latest/CommunitySharings/NNI_colab_support.html
关于cell一直运行的问题，可以尝试用`get_ipython()`代替`!`来执行命令

**Comment by 99hansling** [comment]
> hi, @99hansling @gm3g11 我们提供了新的在colab上面使用NNI WebUI的解决办法，详见https://nni.readthedocs.io/en/latest/CommunitySharings/NNI_colab_support.html
> 关于cell一直运行的问题，可以尝试用`get_ipython()`代替`!`来执行命令

好的，有机会就去试试

**Comment by gm3g11** [comment]
Hi, Junwei

我试验了，可以打开WEB UI了，多谢多谢。

Junwei Sun <notifications@github.com> 于2020年7月10日周五 上午6:29写道：

**Comment by Giaurora** [comment]
你好，按照更新后教程输入! curl -s http://localhost:4040/api/tunnels后，colab并没有任何的回显，请问应该怎么解决，前面的步骤都没有问题

**Comment by Giaurora** [comment]
> > 你好，按照更新后教程输入! curl -s [http://localhost:4040/api/tunnels后，colab并没有任何的回显，请问应该怎么解决，前面的步骤都没有问题](http://localhost:4040/api/tunnels%E5%90%8E%EF%BC%8Ccolab%E5%B9%B6%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E7%9A%84%E5%9B%9E%E6%98%BE%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%89%8D%E9%9D%A2%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> 
> Cell是一直在running状态还是已经执行完毕了？方便的话可以提供一下notebook链接。

notebook可能不太方便，我去掉了-s选项，发现输入curl http://localhost:4040/api/tunnels后报错 Failed to connect to localhost port 4040: Connection refused，另外通过nnictl top命令看到nni一直在运行，

**Comment by JunweiSUN** [comment]
> > > 你好，按照更新后教程输入! curl -s [http://localhost:4040/api/tunnels后，colab并没有任何的回显，请问应该怎么解决，前面的步骤都没有问题](http://localhost:4040/api/tunnels%E5%90%8E%EF%BC%8Ccolab%E5%B9%B6%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E7%9A%84%E5%9B%9E%E6%98%BE%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%89%8D%E9%9D%A2%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> > 
> > 
> > Cell是一直在running状态还是已经执行完毕了？方便的话可以提供一下notebook链接。
> 
> notebook可能不太方便，我去掉了-s选项，发现输入curl [http://localhost:4040/api/tunnels后报错](http://localhost:4040/api/tunnels%E5%90%8E%E6%8A%A5%E9%94%99) Failed to connect to localhost port 4040: Connection refused，另外通过nnictl top命令看到nni一直在运行，

感觉是ngrok没起起来，检查一下吧

**Comment by JunweiSUN** [comment]
> > > 你好，按照更新后教程输入! curl -s [http://localhost:4040/api/tunnels后，colab并没有任何的回显，请问应该怎么解决，前面的步骤都没有问题](http://localhost:4040/api/tunnels%E5%90%8E%EF%BC%8Ccolab%E5%B9%B6%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E7%9A%84%E5%9B%9E%E6%98%BE%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%89%8D%E9%9D%A2%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> > 
> > 
> > Cell是一直在running状态还是已经执行完毕了？方便的话可以提供一下notebook链接。
> 
> notebook可能不太方便，我去掉了-s选项，发现输入curl [http://localhost:4040/api/tunnels后报错](http://localhost:4040/api/tunnels%E5%90%8E%E6%8A%A5%E9%94%99) Failed to connect to localhost port 4040: Connection refused，另外通过nnictl top命令看到nni一直在运行，
刚才在我自己的notebook上面试了一下，没有问题。注意`! ./ngrok authtoken <your-authtoken>`这条命令要把尖括号以及里面的内容换成你自己的authtoken

**Comment by JunweiSUN** [comment]
> > > 你好，按照更新后教程输入! curl -s [http://localhost:4040/api/tunnels后，colab并没有任何的回显，请问应该怎么解决，前面的步骤都没有问题](http://localhost:4040/api/tunnels%E5%90%8E%EF%BC%8Ccolab%E5%B9%B6%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E7%9A%84%E5%9B%9E%E6%98%BE%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%89%8D%E9%9D%A2%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> > 
> > 
> > Cell是一直在running状态还是已经执行完毕了？方便的话可以提供一下notebook链接。
> 
> notebook可能不太方便，我去掉了-s选项，发现输入curl [http://localhost:4040/api/tunnels后报错](http://localhost:4040/api/tunnels%E5%90%8E%E6%8A%A5%E9%94%99) Failed to connect to localhost port 4040: Connection refused，另外通过nnictl top命令看到nni一直在运行，
刚才在我自己的notebook上面试了一下，没有问题。注意`! ./ngrok authtoken <your-authtoken>`这条命令要把尖括号以及里面的内容换成你自己的authtoken

**Comment by JunweiSUN** [comment]
> > > 你好，按照更新后教程输入! curl -s [http://localhost:4040/api/tunnels后，colab并没有任何的回显，请问应该怎么解决，前面的步骤都没有问题](http://localhost:4040/api/tunnels%E5%90%8E%EF%BC%8Ccolab%E5%B9%B6%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E7%9A%84%E5%9B%9E%E6%98%BE%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%89%8D%E9%9D%A2%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> > 
> > 
> > Cell是一直在running状态还是已经执行完毕了？方便的话可以提供一下notebook链接。
> 
> notebook可能不太方便，我去掉了-s选项，发现输入curl [http://localhost:4040/api/tunnels后报错](http://localhost:4040/api/tunnels%E5%90%8E%E6%8A%A5%E9%94%99) Failed to connect to localhost port 4040: Connection refused，另外通过nnictl top命令看到nni一直在运行，

刚才在我自己的notebook上面试了一下，没有问题。注意! ./ngrok authtoken <your-authtoken>这条命令要把尖括号以及里面的内容换成你自己的authtoken

**Comment by Giaurora** [comment]
> 

嗯嗯  这个我都换了，目前没看到怎么在colab里面查看ngrok的运行状态，我再看看什么问题吧，谢谢

**Comment by Giaurora** [comment]
> 嗯嗯 这个我都换了，目前没看到怎么在colab里面查看ngrok的运行状态，我再看看什么问题吧，谢谢

嗯嗯 这个我都换了，目前没看到怎么在colab里面查看ngrok的运行状态，我再看看什么问题吧，谢谢

> > > > 你好，按照更新后教程输入! curl -s [http://localhost:4040/api/tunnels后，colab并没有任何的回显，请问应该怎么解决，前面的步骤都没有问题](http://localhost:4040/api/tunnels%E5%90%8E%EF%BC%8Ccolab%E5%B9%B6%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E7%9A%84%E5%9B%9E%E6%98%BE%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%89%8D%E9%9D%A2%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> > > 
> > > 
> > > Cell是一直在running状态还是已经执行完毕了？方便的话可以提供一下notebook链接。
> > 
> > 
> > notebook可能不太方便，我去掉了-s选项，发现输入curl [http://localhost:4040/api/tunnels后报错](http://localhost:4040/api/tunnels%E5%90%8E%E6%8A%A5%E9%94%99) Failed to connect to localhost port 4040: Connection refused，另外通过nnictl top命令看到nni一直在运行，
> 
> 刚才在我自己的notebook上面试了一下，没有问题。注意`! ./ngrok authtoken <your-authtoken>`这条命令要把尖括号以及里面的内容换成你自己的authtoken

嗯嗯 这个我都换了，目前没看到怎么在colab里面查看ngrok的运行状态，我再看看什么问题吧，谢谢

**Comment by Giaurora** [comment]
> > > > 你好，按照更新后教程输入! curl -s [http://localhost:4040/api/tunnels后，colab并没有任何的回显，请问应该怎么解决，前面的步骤都没有问题](http://localhost:4040/api/tunnels%E5%90%8E%EF%BC%8Ccolab%E5%B9%B6%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E7%9A%84%E5%9B%9E%E6%98%BE%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%89%8D%E9%9D%A2%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> > > 
> > > 
> > > Cell是一直在running状态还是已经执行完毕了？方便的话可以提供一下notebook链接。
> > 
> > 
> > notebook可能不太方便，我去掉了-s选项，发现输入curl [http://localhost:4040/api/tunnels后报错](http://localhost:4040/api/tunnels%E5%90%8E%E6%8A%A5%E9%94%99) Failed to connect to localhost port 4040: Connection refused，另外通过nnictl top命令看到nni一直在运行，
> 
> 刚才在我自己的notebook上面试了一下，没有问题。注意`! ./ngrok authtoken <your-authtoken>`这条命令要把尖括号以及里面的内容换成你自己的authtoken

已解决，是因为犯了一个很蠢的错误，ngrok激活邮件未确认，抱歉

**Comment by ABChh26** [comment]
> 



> > > > > 你好，按照更新后教程输入! curl -s [http://localhost:4040/api/tunnels后，colab并没有任何的回显，请问应该怎么解决，前面的步骤都没有问题](http://localhost:4040/api/tunnels%E5%90%8E%EF%BC%8Ccolab%E5%B9%B6%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E7%9A%84%E5%9B%9E%E6%98%BE%EF%BC%8C%E8%AF%B7%E9%97%AE%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%89%8D%E9%9D%A2%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> > > > 
> > > > 
> > > > Cell是一直在running状态还是已经执行完毕了？方便的话可以提供一下notebook链接。
> > > 
> > > 
> > > notebook可能不太方便，我去掉了-s选项，发现输入curl [http://localhost:4040/api/tunnels后报错](http://localhost:4040/api/tunnels%E5%90%8E%E6%8A%A5%E9%94%99) Failed to connect to localhost port 4040: Connection refused，另外通过nnictl top命令看到nni一直在运行，
> > 
> > 
> > 刚才在我自己的notebook上面试了一下，没有问题。注意`! ./ngrok authtoken <your-authtoken>`这条命令要把尖括号以及里面的内容换成你自己的authtoken
> 
> 已解决，是因为犯了一个很蠢的错误，ngrok激活邮件未确认，抱歉

请问这个邮件是什么样的，我貌似没收到这样需要确认的邮件

**Comment by ABChh26** [comment]
> 你可以去找找看别的需要 tunnel 的 application。比如 visdom，这种库用的人会更 popular 一点，你可以看看用这种方法能不能把 visdom 跑起来，如果不行的话看看他们的 issue 里有没有相关的解决方案。
> 
> 由于我们没有提供 native 的 colab 解决方案，所以麻烦你先调研一下。如果还是存在困难（比如 visdom 能跑但 nni 跑不了）的话，我们可以提供力所能及的帮助。

您好，我在colab上用nni运行我自己的代码，总是failed，提示没找到日志文件，请问是哪里的设定漏掉了呢？
{"error":"File not found: /root/nni-experiments/rgiu2kbx/trials/rQUUZ/trial.log"}
