### ISSUE TITLE
关于使用gpu进行计算时trial全部fail的问题

### ISSUE THREAD

**Issue by 99hansling** [microsoft/nni#2395]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**
在尝试将
'''
G:\nni-master\examples\trials\mnist-tfv2\config_windows.yml
'''
中的
'''
 gpuNum: 0
'''
改成
'''
 gpuNum: 1
'''
后，我原本期待可以用gpu帮助运算而减轻cpu的负担，然而却发现每个trial都直接failed。

我使用的cuda是10.1版本的。python包安装了tensorflow-gpu 2.0。

但是我mnist.py的代码没有做改变，yml文件也仅做了gpuNum的改变，不知道是不是这里的问题，还是有其他问题？

另外，在最初改变gpuNum的时候我遇到了一个问题就是实验直接失败，之后我观察错误输出后，发现dill没有安装，于是我使用
'''
python -m pip install --upgrade dill
'''
之后，实验直接failed的问题就解决了。但是我不知道是不是这里也可能存在问题？

期待您的回答！

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:1.5
- nni mode(local|pai|remote):local
- OS:windows10
- python version:3.7
- is conda or virtualenv used?:no
- is running in docker?:no

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by scarlett2018** [comment]
@99hansling 能提供一下logs吗？

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by 99hansling** [comment]
> @99hansling 能提供一下logs吗？
> 
> **Log message / 日志信息 :**
> 
> * [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) :
> * [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

[nnimanager.log](https://github.com/microsoft/nni/files/4556408/nnimanager.log)
[dispatcher.log](https://github.com/microsoft/nni/files/4556411/dispatcher.log)

**Comment by ultmaster** [comment]
每个 trial 都 fail 的话，你应该查下 trial 的 log 看看 trial 出什么错误信息。是 import 失败还是其他什么错误。

**Comment by 99hansling** [comment]
> 每个 trial 都 fail 的话，你应该查下 trial 的 log 看看 trial 出什么错误信息。是 import 失败还是其他什么错误。

是查看nnimanager.log文件内容吗？

**Comment by 99hansling** [comment]
tensorflow的话还是会全fail掉

pytorch的话已经不会了。之前全fail的原因似乎是torch和torchvision不匹配的缘故。

要注意requirements.txt文件和版本匹配的问题

**Comment by ultmaster** [comment]
要看的是 trial details 下面每个 trial 对应的 log

**Comment by scarlett2018** [comment]
> 要看的是 trial details 下面每个 trial 对应的 log

@99hansling ^^^
