### ISSUE TITLE
Search Space of Tuner

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2397]
I'm confused of the `quniform` type. I expect it acts like `range`. 
For example, for `_value` as [0.3,1.5,0.2] the output should be [0.3, 0.5, 0.7, 0.9, 1.1, 1.3]. 
But when I set `_value` as [0.3, 1.5, 0.2], the parameters are [0.3, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.5], set `_value` as [0.3, 0.6] the parameters are [0.3, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6].

**Comment by scarlett2018** [comment]
@colorjam - thanks for the feedback. Your understanding is basically right, may you share the search space file you are using? 

Refer to the following doc for definition:
https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/SearchSpaceSpec.md

**Comment by kvartet** [comment]
I’m closing this issue as it has no updates from user for 3 months, please feel free to reopen if you are still seeing it an active issue.
