### ISSUE TITLE
config.yml文件中tuner使用TPE和Anneal都能运行，但是用Random就无法运行，别的地方都没改，就把TPE或者Anneal改成了Random

### ISSUE THREAD

**Issue by spiritmoon333** [microsoft/nni#2402]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?:
- is running in docker?:

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by QuanluZhang** [comment]
please remove `optimize_mode` when using random tuner, because random tuner does not care whether you want to maximize or minimize.
