### ISSUE TITLE
config中，trialConcurrency，gpuNum和maxTrialNumPerGpu分别是怎么起作用的？

### ISSUE THREAD

**Issue by terrencewayne** [microsoft/nni#2415]
**Short summary about the issue/question**:
GPU调度问题，trialConcurrency，gpuNum和maxTrialNumPerGpu分别是怎么起作用的？

**Brief what process you are following**: 
现有8张卡，希望每个trial在一张卡或两张卡上训练，每张卡最多同时被2个trial占用，应该怎么设置config？

**How to reproduce it**: 
我发现trialConcurrency这个选项似乎并不影响gpu的调度情况。
保持trialConcurrency=8，gpuNum=8, 我尝试了下面2种设置方式：

1. maxTrialNumPerGpu=2, 训练脚本中不dataparallel
结果：只启用一张卡同时训练2个trial

2. maxTrialNumPerGpu=2，训练脚本中dataparallel
结果：同时训练2个trial，启用的卡数由dataparallel指定

那么如何在不并行的情况下启用所有的GPU呢？trialConcurrency和maxTrialNumPerGpu的关系是什么样的？不同trial能否在互不交集的gpu组上训练呢？

**nni Environment**:
- nni version: 1.5
- nni mode(local|pai|remote): local
- OS: linux
- python version: 3.7.3
- is conda or virtualenv used?:  no
- is running in docker?: no

**Comment by SparkSnail** [comment]
gpuNum用来设置每个trial需要的GPU数量，trialConcurrency用来设置同时运行的trial数量，maxTrialNumPerGpu用来设置一个GPU最多运行几个trial，useActiveGpu用来设置是否使用有别的进程占用的GPU。
trialConcurrency和GPU设置无关，是实验相关普通配置。默认情况下，一个GPU只有一个trial运行，默认maxTrialNumPerGpu=1。默认情况下，NNI不会使用有非NNI进程占用的GPU，默认useActiveGpu=False。
参考：https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#localconfig

**Comment by terrencewayne** [comment]
谢谢解答！修改设置后，我的实验中GPU的调度正常了。
