### ISSUE TITLE
AttributeError: 'AGP_Pruner' object has no attribute 'export_model'

### ISSUE THREAD

**Issue by bothrasumit** [microsoft/nni#2428]
**Short summary about the issue/question**: I am trying to prune a freezed protobuf model using tensorflow nni.

**Brief what process you are following**:  I am loading the protobuf model and trying to prune it, but unable to export the model

Here is a code snippet:
from nni.compression.tensorflow import *
import nni
import tensorflow as tf

model="/ModelingEBSVol/URPM/sumit/NNI1/scripts/RmajorTFGT.pb"
with tf.io.gfile.GFile(model, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

#config_list = [{ 'sparsity': 0.8, 'op_types': ['default '] }]
config_list = [{
    'initial_sparsity': 0,
    'final_sparsity': 0.8,
    'start_epoch': 0,
    'end_epoch': 10,
    'frequency': 1,
    'op_types': 'default'
}]
pruner = AGP_Pruner(graph_def, config_list)
pruner.compress()
pruner.export_model()

**Comment by chicm-ms** [comment]
Hi @bothrasumit,
Thanks for reporting this issue.  This is a bug and will be fixed.

**Comment by bothrasumit** [comment]
Hi @chicm-ms 

Any update on this?
Thanks
Sumit

**Comment by kvartet** [comment]
@QuanluZhang, is this a bug that needs somebody to fix it?

**Comment by J-shang** [comment]
@QuanluZhang @kvartet We deprecated most pruners and quantizers include AGPPruner in TensorFlow since nni v1.8, and I think this issue can be closed.

**Comment by kvartet** [comment]
hello @bothrasumit, you can upgrade the version of NNI and try again. It seems not a problem now, so I will close this issue, feel free to reopen it.

> @QuanluZhang @kvartet We deprecated most pruners and quantizers include AGPPruner in TensorFlow since nni v1.8, and I think this issue can be closed.
> 
> In the latest version, we support export model in all TensorFlow pruners (Level, Slim).
