### ISSUE TITLE
Remove minimized optimization mode in curve fitting assessor

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/nni#2429]
**Short summary about the issue/question**: Remove minimized optimization mode in curve fitting assessor

**Brief what process you are following**: A user raise a question on abnormal behavior of curve fitting assessor that, it doesn't handle miniminzed optimization direction well. Many better results are earlier stopped. The original paper discusses increasing curves only, and our implemention on minimized mode very limited like below.

```python
if self.higher_better:
    if predict_y > standard_performance:
        return AssessResult.Good
    return AssessResult.Bad
else:
    if predict_y < standard_performance:
        return AssessResult.Good
    return AssessResult.Bad
```

**need to update document(yes/no)**: yes

**Comment by liuzhe-lz** [comment]
Done
