### ISSUE TITLE
How to pass arguments to the sdk pynni nni __main__.py?

### ISSUE THREAD

**Issue by cmleecm** [microsoft/nni#2448]
Any tips or tutorial on how to use the SDK? In particular, I am looking at \_\_main\_\_.py in nni/src/sdk/pynni/nni/ in an attempt to understand how nnictl works under the hood. My question is: how do I pass the related arguments to \_\_main\_\_.py? In nnictl, the various arguments are specified in a yaml file, e.g. config.yml. Does \_\_main\_\_.py take in a yaml file as an argument as well? Many thanks for your help.

**Comment by liuzhe-lz** [comment]
The __main__.py is not supposed to run by end-user.
For Hyper-Parameter Tuning users, you should use `nnictl` to start a experiment, which is documented [here](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/QuickStart.md).
For NAS and Model Compression users, simply `import nni` from your Python code and use corresponding [API](https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/NasGuide.md).

**Comment by cmleecm** [comment]
Many thanks for taking the time to reply. Your kind reply triggers more questions:

1. Who is the targeted user of this SDK?
2. How do I get started with using the SDK?
3. If I am interested in understanding the inner workings of nni, is SDK the way to go? For example, I can set breakpoints and step through the code in PyCharm to understand the program flow.

**Comment by liuzhe-lz** [comment]
> Who should consider using NNI
>  - Those who want to try different AutoML algorithms in their training code/model.
>  - Those who want to run AutoML trial jobs in different environments to speed up search.
>  - Researchers and data scientists who want to easily implement and experiment new AutoML algorithms, may it be: hyperparameter tuning algorithm, neural architect search algorithm or model compression algorithm.
>  - ML Platform owners who want to support AutoML in their platform.

To be more detailed, HPO, NAS, and Model Compression modules are implemented separately, so to use or to understand them you will have different workflow. I'm personally not familiar with Feature Engineering.
To _use_ NNI, each feature has a Quick Start guide: [HPO](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/QuickStart.md), [NAS](https://github.com/microsoft/nni/blob/master/docs/en_US/NAS/QuickStart.md), [Model Compression](https://github.com/microsoft/nni/blob/master/docs/en_US/Compressor/QuickStart.md), [Feature Engineering](https://github.com/microsoft/nni/blob/master/docs/en_US/FeatureEngineering/Overview.md)
The guides above mainly focus on using built-in algorithms to optimize your model. To write your own HPO algorithm, there is another [guide](https://github.com/microsoft/nni/blob/master/docs/en_US/Tuner/CustomizeTuner.md). Unfortunately NNI's NAS and Model Compression framework is not yet mature and we don't have a nice doc at this moment.
To dig into implementation, I'm working on the [developer's manual](https://github.com/microsoft/nni/wiki/%5BDEV%5D-NNI-Modules) and you can check it later. In short HPO as a distributed feature is implemented as a "frontend" Python SDK plus a "backend" TypeScript manager, while NAS and Model Compression are pure Python library.
You can find NAS source code [here](https://github.com/microsoft/nni/tree/master/src/sdk/pynni/nni/nas/pytorch) and Model Compression [here](https://github.com/microsoft/nni/tree/master/src/sdk/pynni/nni/compression/torch). If you have followed NAS or Model Compression guides, it should be easy to find mentioned API functions.
Detailed HPO architecture is too complicated to be explained here.

**Comment by cmleecm** [comment]
Many thanks for providing a detailed reply. I look forward to the developer's manual so that I can build on top of the SDKs. If there is anything I can do to help, please let me know.
