### ISSUE TITLE
微信二维码过期如何加入讨论？

### ISSUE THREAD

**Issue by precision2intelligence** [microsoft/nni#2457]
如题，有没有个人微信号可以拉入到群里？或者更新一下二维码？

**Comment by JSong-Jia** [comment]
Hi~Thanks for your kind remind. The QR code has been updated.

**Comment by pprp** [comment]
The QR code is expired, please update it

**Comment by kvartet** [comment]
@pprp hello, the WeChat QR code is valid, please remove your cookie and try again.
