### ISSUE TITLE
While running encounter errors 

### ISSUE THREAD

**Issue by Fusheng-code** [microsoft/nni#2466]
**Short summary about the issue/question**:
While I run the MNIST-Pytorch example on my own device,an error happened called "Dispatcher error: This socket has been ended by the other party" which I don`t know how to deal with it.
**Brief what process you are following**: 
I copy the code directly from github and put the three files in the same folder and I start the nni experiment.

**nni Environment**:
- nni version:1.5
- nni mode(local|pai|remote):local
- OS:Windows 10 2005
- python version: 3.7.7
- is conda or virtualenv used?: conda used
- is running in docker?:no

**need to update document(yes/no)**:
no
**Anything else we need to know**:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 
[dispatcher.log](https://github.com/microsoft/nni/files/4654427/dispatcher.log)
[nnimanager.log](https://github.com/microsoft/nni/files/4654428/nnimanager.log)

**Comment by chicm-ms** [comment]
Hi @Fusheng-code ,
Thanks for reporting this issue, would you please perform following actions?
1. run `nnictl log stderr`  and   `nnictl log stdout`,  then paste the output here.
2. collect dispatcher.log from ~/nni/experiment/<experiment id/log/dispatcher.log

It seems nni dispatcher process crashed, it will be very helpful to debug by collecting above information.

**Comment by Fusheng-code** [comment]
log stderr contents are below:
-----------------------------------------------------------------------
                Experiment start time 2020-05-22 18:18:52
-----------------------------------------------------------------------
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.dispatcher.onError (d:\programing\anaconda\nni\core\nnimanager.js:505:32)
    at EventEmitter.emit (events.js:182:13)
    at Socket.IpcInterface.outgoingStream.on (d:\programing\anaconda\nni\core\ipcInterface.js:42:72)
    at Socket.emit (events.js:182:13)
    at Socket.writeAfterFIN [as write] (net.js:405:8)
    at IpcInterface.sendCommand (d:\programing\anaconda\nni\core\ipcInterface.js:49:38)
    at NNIManager.pingDispatcher (d:\programing\anaconda\nni\core\nnimanager.js:354:29)

log stdout are here:
-----------------------------------------------------------------------
                Experiment start time 2020-05-22 18:18:52
-----------------------------------------------------------------------

And the dispatcher.log is belowed:
[dispatcher.log](https://github.com/microsoft/nni/files/4667467/dispatcher.log)

Thanks for your help!

**Comment by chicm-ms** [comment]
@chicm-ms 
It seems python can not be found by nni,  do you have python installed on the system?  If not, please install it from https://www.python.org/

**Comment by Fusheng-code** [comment]
I installed anaconda on my computer.
Do I need to install a python again?

**Comment by chicm-ms** [comment]
no need to install again if anaconda is installed, you need to activate the environment and make sure python command can be used,  maybe add the dir of python.exe in PATH environment variable.

**Comment by Fusheng-code** [comment]
![image](https://user-images.githubusercontent.com/60567149/82669213-a281b800-9c6d-11ea-8943-0f9e3cd8d7d5.png)
It seems that I had add it in to Path and I can also use python command in the powershell but the problem still happens.
I run the code in VS Code. Is there anything I should change about it?

**Comment by scarlett2018** [comment]
> ![image](https://user-images.githubusercontent.com/60567149/82669213-a281b800-9c6d-11ea-8943-0f9e3cd8d7d5.png)
> It seems that I had add it in to Path and I can also use python command in the powershell but the problem still happens.
> I run the code in VS Code. Is there anything I should change about it?

@chicm-ms more suggestions here?

**Comment by chicm-ms** [comment]
@Fusheng-code Has the problem been resolved?  Please ensure `python` command is available and python version >= 3.5 before launching NNI.

**Comment by Fusheng-code** [comment]
Do you mean that I can use python command in Windows Terminal? Because I install anaconda in my computer but when I use python in the terminal, it turns to the store`s Python page.

**Comment by chicm-ms** [comment]
You can check Anaconda website to find how to use Anaconda on windows.

**Comment by Fusheng-code** [comment]
Oh I solved the problem! Thanks a lot!
