### ISSUE TITLE
GridSearchTuner not allowing interval for randint

### ISSUE THREAD

**Issue by horuswoo** [microsoft/nni#2468]
**Short summary about the issue/question**:
GridSearchTuner is allowing passing an interval for parameters of type `quniform` but not allowing an interval for `randint`. Both should support specifying an interval/step length.

**Anything else we need to know**:
[Code referenced](https://github.com/microsoft/nni/blob/98f66f76d310b0e0679823d966fdaa6adafb66c2/src/sdk/pynni/nni/gridsearch_tuner/gridsearch_tuner.py#L101)

**Comment by QuanluZhang** [comment]
@horuswoo thanks for reporting this issue. Does interval of `quniform` enough for solving your problem? To me, `quniform` and `randint` with interval have similar capacity to express integers with interval.

**Comment by horuswoo** [comment]
Thanks for the reply. I think that would work, yes. Is it a workaround or a feature by design though?

**Comment by scarlett2018** [comment]
> Thanks for the reply. I think that would work, yes. Is it a workaround or a feature by design though?

@QuanluZhang

**Comment by QuanluZhang** [comment]
> Thanks for the reply. I think that would work, yes. Is it a workaround or a feature by design though?

@horuswoo sorry for the late reply. Yes, this is by design.
