### ISSUE TITLE
 I am a student of Tsinghua University. When I have a problem with the following command, I sincerely look forward to your reply the commond is nnictl create --config   nni/examples/trials/network_morphism/cifar10/config.yml

### ISSUE THREAD

**Issue by xianglei3** [microsoft/nni#2472]
**Short summary about the nnictl create --config  :+1: nni/examples/trials/network_morphism/cifar10/config.yml issue/question**:

I run :  nnictl create --config   nni/examples/trials/network_morphism/cifar10/config.yml
when i use my data like this:

    dataPath = os.environ["HOME"] + "/mountdir/data/"

    data_transform = transforms.Compose([
        transforms.Resize(128),
        #transforms.CenterCrop(128),
        transforms.ToTensor(),
        #transforms.Normalize(mean=[0.485, 0.456, 0.406],
        #                     std=[0.229, 0.224, 0.225])
    ])

    train_dataset =torchvision.datasets.ImageFolder(root='/root/mountdir/dataset/train',transform=data_transform)
    trainloader =DataLoader(train_dataset,batch_size=10, shuffle=True,num_workers=4)

    test_dataset = torchvision.datasets.ImageFolder(root='/root/mountdir/dataset/val',transform=data_transform)
    testloader = DataLoader(test_dataset,batch_size=10, shuffle=True,num_workers=4)

the error is  :
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 161 and 154 in dimension 3 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
.reraise()
  File "/usr/local/lib/python3.5/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
.reraise()
  File "/usr/local/lib/python3.5/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 161 and 154 in dimension 3 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
`    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by chicm-ms** [comment]
In the nni example, it uses 32x32  3 channel RGB data,  would you please firstly check whether your image is 3 channel RGB data,  and also resize to 32x32 instead of 128x128?

**Comment by xianglei3** [comment]
've modified it to 128 * 128 in YML, but the problem is still, what's the reason for sincere consultation? Kneeling, kneeling, is it the problem of transform method, such as resize shouldn't be used

**Comment by chicm-ms** [comment]
Hi @xianglei3 ,
Looks like the tensor shape does not match the model,  I meant firstly check whether your image is is 3 color RGB, you can check it with `file` command on linux,  grayscale images have only 1 channel, if it is grayscale, you need additional preprocess.   Then change the `128` to `32` in your 'transforms.Resize` transform,  since the nni example is using `32`,   the model is expecting input data to be 32x32,  other sizes maybe work,  it is also possible not work because it is not tested with other sizes except 32x32.

**Comment by xianglei3** [comment]
I use transforms.CenterCrop Instead of resize, the problem has been solved. I sincerely ask for help to analyze the reasons. I'm looking forward to the reply

data_transform = transforms.Compose([
    #2466 transforms.Resize(128),
    transforms.CenterCrop(128),
    transforms.ToTensor(),
    #transforms.Normalize(mean=[0.485, 0.456, 0.406],
    #                     std=[0.229, 0.224, 0.225])
])

**Comment by scarlett2018** [comment]
> I use transforms.CenterCrop Instead of resize, the problem has been solved. I sincerely ask for help to analyze the reasons. I'm looking forward to the reply
> 
> data_transform = transforms.Compose([
> #2466 transforms.Resize(128),
> transforms.CenterCrop(128),
> transforms.ToTensor(),
> #transforms.Normalize(mean=[0.485, 0.456, 0.406],
> # std=[0.229, 0.224, 0.225])
> ])

@chicm-ms ping

**Comment by kvartet** [comment]
@xianglei3 I’m closing this issue as it has no updates from user for 3 months, please feel free to reopen if you are still seeing it an active issue.
