### ISSUE TITLE
I am a student of Tsinghua University. When I tested the model trained by NNI, I made the following mistakes. I didn 't solve them all night. I knelt down to beg for the reason. Thank you very much

### ISSUE THREAD

**Issue by xianglei3** [microsoft/nni#2489]
**Short summary about the issue/question**:

the err  is 

return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 708, in _legacy_load
    assert key in deserialized_objects

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by scarlett2018** [comment]
@xianglei3 - I'm closing the issue as it seems a test issue? please adjust the description if it is an real problem you met (and still able to reproduce). thanks.
