### ISSUE TITLE
NNI cannot find installed tensorflow in virtualenv

### ISSUE THREAD

**Issue by penguincwarrior** [microsoft/nni#2493]
**Short summary about the issue/question**:

nni cannot find the installed tensorflow 2.2 in virtualenv

**Brief what process you are following**: 

1) install virtualenv, set env tf2.2, install nni;
2) python mnist_tfv2\mnist.py successful
3) nnictl create --config config_windows.yml
All trials fail, because the log says that no module named tensorflow.

**How to reproduce it**: 

**nni Environment**:
- nni version:1.5
- nni mode(local|pai|remote):local
- OS: win10
- python version: 3.7
- is conda or virtualenv used?: virtualenv used 
- is running in docker?: no

**need to update document(yes/no)**:

**Anything else we need to know**:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) : 
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "mnist.py", line 15, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by liuzhe-lz** [comment]
First please make sure you ran `nnictl` inside virtualenv.
Then use following script as trial code to see used environment in log file:
```python
import sys
import nni
nni.get_next_parameter()
nni.report_final_result(sys.prefix)
```

**Comment by penguincwarrior** [comment]
Thanks for the reply. 
First, I tried to run the mnist.py without nnictl. The log is below:

[05/27/2020, 10:03:38 PM] WARNING (nni) Requesting parameter without NNI framework, returning empty dict
[05/27/2020, 10:03:38 PM] INFO (nni) Final result: "c:\\users\\penguin\\envs\\tf2.2"
[05/27/2020, 10:03:38 PM] WARNING (nni) Requesting parameter without NNI framework, returning empty dict
INFO:mnist_example:Hyper-parameters: {'dropout_rate': 0.5, 'conv_size': 5, 'hidden_size': 1024, 'batch_size': 32, 'learning_rate': 0.0001}
INFO:mnist_example:Model built
INFO:mnist_example:Dataset loaded
WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x00000200B37C6B88> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x00000200B37C6B88> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x00000200B37C6B88> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

The err log using nnictl indicates that nni could not be imported. 

Then, I tried to remove virtualenv and directly install packages on the default environment. However, the problem remains.
The installed pip packages are listed below:
[pipList.txt](https://github.com/microsoft/nni/files/4689559/pipList.txt)

**Comment by liuzhe-lz** [comment]
How did you install Python? Currently NNI does not support Python installed from Windows Store (or from appx package).
If it was installed via exe, please invoke pip from trial code to detect which environment is actually in use.
You should use `python -m pip` instead of `pip` to get accurate result. In certain scenario they may point to different environment.
```python
import logging, subprocess
logging.info(subprocess.run('python -m pip -V'.split(), capture_output=True, text=True).stdout)
logging.info(subprocess.run('python -m pip list'.split(), capture_output=True, text=True).stdout)
```

**Comment by penguincwarrior** [comment]
Thank you for your help! I tried to debug for a few days, and it turns out that the python environment of PowerShell and cmd is different, so invoking python mnist.py in cmd and PowerShell generates different results. 
Now the problem is fixed.
