### ISSUE TITLE
Can not open the link of `Automatic Feature Engineering` example in README_zh_CN.md

### ISSUE THREAD

**Issue by BofengDuke** [microsoft/nni#2495]
**Short summary about the issue/question**:

Can not open the link of `Automatic Feature Engineering` example in README_zh_CN.md

**Brief what process you are following**: 

I got a 404 page when I open the link of `Automatic Feature Engineering` example in readme_zh_CN.md.

It's in section External Repositories and References/External Repositories

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by liuzhe-lz** [comment]
Hello. Thanks for your report.
Which link are you referring to? I cannot find the link in `README_zh_CN.md`.
You can use Chinese if you want.

**Comment by squirrelsc** [comment]
Cannot repro it. Please let us know exact text or link. Thank you.
