### ISSUE TITLE
Why doesn't nni support __deepcopy__ in mutable ?

### ISSUE THREAD

**Issue by CuriousCat-7** [microsoft/nni#2498]
![image](https://user-images.githubusercontent.com/17199271/83098527-805cbf80-a0dd-11ea-91af-9dd1fe90af16.png)
I know that's because of the cyclic reference between "mutable" and "mutator". But when I do want a deepcopy, what's the proper way to do that?

**Comment by ultmaster** [comment]
Good question. The proper workaround is to use `state_dict()` and `load_state_dict()`. I think DARTS have such need when using second order optimization. You can refer to DartsTrainer on how to do that.

One more thing. I have to admit that cyclic reference is not a good idea, which is a flaw in our design. In future, we might refactor it by using hooks (then mutator will work like DistributedDataParallel). Feel free to post if you have other things in your mind.

**Comment by scarlett2018** [comment]
Thanks @CuriousCat-7 for raising the questions and closing it as @ultmaster had provided the answer. Feel free to reopen if you still have questions around the issue.
