### ISSUE TITLE
Why ENAS example gives such a low accuracy?

### ISSUE THREAD

**Issue by curiousjit** [microsoft/nni#2500]
Short summary about the issue/question:

When I run the [ENAS_Micro example](https://github.com/microsoft/nni/blob/master/examples/nas/enas/search.py), the best model's accuracy I found was around 58%. Since it's too low, do I need to retrain the best architecture (like DARTS) to improve the accuracy?

Brief what process you are following:

Run ENAS example for Micro architecture and compare the acuracies of each epoch. 

It's in section External Repositories and References/External Repositories

How to reproduce it:
In [ENAS example](https://github.com/microsoft/nni/blob/master/examples/nas/enas/search.py): 
python3 search.py

nni Environment:

    nni version: 1.5
    nni mode(local|pai|remote): local
    OS: Linux
    python version: 3.6.10
    is conda or virtualenv used?: Conda
    is running in docker?: No

need to update document(yes/no): no

Anything else we need to know: no

**Comment by ultmaster** [comment]
Thanks for asking. The answer is, yes, you need to retrain them.

Note that the ENAS example is just an example to demonstrate how to use EnasTrainer. In future, we might report our reproduction result, but currently they are not ready yet.

**Comment by curiousjit** [comment]
Thank you for clarifying it.
