### ISSUE TITLE
NAS with conditions on parameters

### ISSUE THREAD

**Issue by anadb** [microsoft/nni#2503]
Hello!

I would like to find an architecture where 90% of weights will be less then certain W0.

I am wondering is it possible to make without changing nni algorithms of different nas methods?
If yes, how do you suggest to make it?

**Comment by QuanluZhang** [comment]
@anadb thanks for reporting your requirement. So, your requirement is that there are some layers, you want to tune weight size of these layers. The weight size of the other layers should be smaller than the layer whose weight is W0. right?

Your requirement can be generalized to be putting constraints among DNN layers. For HPO (hyper-parameter tuning), a similar requirement is putting constraints among hyper-parameters. This is a reasonable requirement, we will consider it in future release.

A workaround is using hype-parameter tuning. Each hyper-parameter means the weight size of a layer. Then, in your trial code, you can directly return failure when the hyper-parameters violate the constraints.

**Comment by anadb** [comment]
Thank you for the answer. By using the tuner can I directly access to the weight values and change them?

**Comment by QuanluZhang** [comment]
> Thank you for the answer. By using the tuner can I directly access to the weight values and change them?

Sorry, I thought you only need to control weight size, weight values are not required by tuning algorithms. If weight size is decided based on weight values, then you may want to try [model compression](https://nni.readthedocs.io/en/latest/model_compression.html).
