### ISSUE TITLE
NNI NAS 是否支持对特定操作在网络中位置的搜索

### ISSUE THREAD

**Issue by zl-hw** [microsoft/nni#2505]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
您好，最近学习了一下NNI的NAS API，了解到NNI的搜索空间目前支持layer_choice和input_choice 2种基本类型，通过看NNI的提供的example和源码，知道NNI是通过在网络结构定义的时候通过LayerChoice和InputChoice的模块来定义搜索空间的，在我自己的NAS实验中（20层CNN网络，其中包含一个上采样和一个下采样操作），搜索空间除了层类型和skipconnect，还想同时加入对上采样和下采样层在网络中位置的搜索，请问当前NNI的NAS机制能否支持这种搜索空间的表达？根据我现在的理解，想不出如何通过NNI NAS API表达上/下采样层在网络中的位置，多谢！
**Short summary about the question / idea :**

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Comment by QuanluZhang** [comment]
@zl-hw thanks for reporting your requirement. This is a good point, we are working on this and will release this feature soon.

**Comment by kvartet** [comment]
hi @QuanluZhang, does Retiarii support this feature? would you mind sharing the latest status of this issue? thanks!

**Comment by QuanluZhang** [comment]
@zl-hw , yes, you can write your mutator following [this document](https://nni.readthedocs.io/en/stable/NAS/Mutators.html). The logic of this mutator tries different places for up/down sampling
