### ISSUE TITLE
import experiment from other machine?

### ISSUE THREAD

**Issue by MarkMa1990** [microsoft/nni#2509]
**Short summary about the issue/question**:
Hi developers, I am just wondering whether it is possible to load experiments from other machines?

**Brief what process you are following**: 
For instance, machine A run hyper-searching use nni, after it is finished, copy the "/home/machineA_xxx/nni/experiment/projectId" fold to machine B under "/home/machineBxxx/nni/experiment/projectId". I found in machine B, use "nnictl experiment list -all" just do not recognize that experiment copied from machine A. Is there a way to do this? Thank you. 

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.6
- nni mode(local|pai|remote): local in A
- OS: Ubuntu 16.04
- python version: python 3.6
- is conda or virtualenv used?:  no
- is running in docker?: no

**need to update document(yes/no)**:
no
**Anything else we need to know**:
-the output of "nnictl experiment list --all"

                Experiment information
Id: SaKquErq    Name: example_mnist-keras    Status: STOPPED    Port: 8090    Platform: local    StartTime: 2020/05/27 02:57:46    EndTime: 2020-05-27 02:59:49
Id: WYQzIi4a    Name: example_mnist-keras    Status: STOPPED    Port: 8090    Platform: local    StartTime: 2020/05/27 03:00:04    EndTime: 2020-05-27 03:01:57
Id: UsHSeE1r    Name: example_mnist-keras    Status: STOPPED    Port: 8090    Platform: local    StartTime: 2020/05/27 03:02:12    EndTime: 2020-05-27 03:02:51
Id: s298hlFR    Name: example_mnist-keras    Status: STOPPED    Port: 8090    Platform: local    StartTime: 2020/05/27 03:04:29    EndTime: 2020-05-27 03:05:10
Id: pWlIPmIs    Name: exp_hyperScan    Status: STOPPED    Port: 8090    Platform: local    StartTime: 2020/05/29 18:07:20    EndTime: 2020-05-29 18:11:49

![image](https://user-images.githubusercontent.com/10673026/83315440-9b047500-a252-11ea-9a04-8febbfa80538.png)

the folder "FybXearq" is the one I copied from machine A.

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by SparkSnail** [comment]
Hi @MarkMa1990, nnictl has a metadata folder under `~/.local/nnictl`, you should also copy the sub-folders under this metadata folder, and merge the two `~/.local/nnictl/.experiment` file to one file in your machine B.

**Comment by MarkMa1990** [comment]
> Hi @MarkMa1990, nnictl has a metadata folder under `~/.local/nnictl`, you should also copy the sub-folders under this metadata folder, and merge the two `~/.local/nnictl/.experiment` file to one file in your machine B.

Hi there, thank you very much. Now I understand `nnictl ` reads the configuration file under 
`~/.local/nnictl/.experiment` telling `nnictl`, all the experiment names and their storing locations. The "filename" has a different name with experiment name. inside that filename folder:`~/.local/nnictl/EXPERIMENT_NAME/.config`, the experiment config.yml is there. To `nnictl resume`, one may need to change the `searchSpacePath` and `codeDir` to new path.

Does this appear in the user manual?

**Comment by SparkSnail** [comment]
> > Hi @MarkMa1990, nnictl has a metadata folder under `~/.local/nnictl`, you should also copy the sub-folders under this metadata folder, and merge the two `~/.local/nnictl/.experiment` file to one file in your machine B.
> 
> Hi there, thank you very much. Now I understand `nnictl ` reads the configuration file under
> `~/.local/nnictl/.experiment` telling `nnictl`, all the experiment names and their storing locations. The "filename" has a different name with experiment name. inside that filename folder:`~/.local/nnictl/EXPERIMENT_NAME/.config`, the experiment config.yml is there. To `nnictl resume`, one may need to change the `searchSpacePath` and `codeDir` to new path.
> 
> Does this appear in the user manual?

don't have not any doc for this yet.

**Comment by isbada** [comment]
> Hi @MarkMa1990, nnictl has a metadata folder under `~/.local/nnictl`, you should also copy the sub-folders under this metadata folder, and merge the two `~/.local/nnictl/.experiment` file to one file in your machine B.

what If i use conda?
