### ISSUE TITLE
Due to the limitation of scikit-learn version, I cannot install nni on python3.8

### ISSUE THREAD

**Issue by Reveyer** [microsoft/nni#2511]
nni -> scikit-learn<0.22,>=0.20

scikit-learn=0.21.3 -> python<3.8.0a0,>=3.7

**Comment by liuzhe-lz** [comment]
If you are using Linux, you can install `cython` from your distro's repo to build scikit-learn.
If you are using Windows, I personally suggest you to manually remove the line from `setup.py`. Scikit-learn is only used by specific HPO tuners and I guess most them are compatible with latest version.

I will try to fix this in next release.

**Comment by Reveyer** [comment]
Thanks for your suggest.
I'm using Linux.I finally install NNI from source code by removing the line from `setup.py`.
