### ISSUE TITLE
 Support nested experiment more friendly

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/nni#2513]
**What would you like to be added**:
add more yAxis message in the hyper-parameter

![image](https://user-images.githubusercontent.com/61399850/84591690-0b2a1200-ae73-11ea-9338-28b7da075934.png)

**Why is this needed**:
make netsted experiment get better experience

![image](https://user-images.githubusercontent.com/61399850/84645490-3e33da80-af33-11ea-89b0-3078947d0796.png)

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by chicm-ms** [comment]
flatten all levels

**Comment by Lijiaoa** [comment]
At present(v1.7), webui support nested search space as this picture. And in future, will do more things for better user experience. You can track this issue#https://github.com/microsoft/nni/issues/2555.
