### ISSUE TITLE
NNI NAS API是否支持通道数类型的搜索空间

### ISSUE THREAD

**Issue by zl-hw** [microsoft/nni#2514]
## NNI 学生项目问题概述 / General Question of Student Program
您好，MIT的韩松老师的‘’once for all‘和“gan compression”开源工作，都会在一个超网络上，对不同通道数的子网络进行搜索，以达到网络进行压缩的目的，我自己的NAS项目也希望能在超网络上支持对不同通道数子网络的搜索，但是看了NNI NAS API感觉超网络目前还不支持这种搜索空间，请问我的理解对吗？如果是这样的，是否有计划支持该功能呢？谢谢。

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?:
- is running in docker?:

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by ultmaster** [comment]
NNI 在 model compression 上有对 channel prune 的相关支持，但在 NAS 上现在还没有相关的例子和 API 实现。未来肯定是有打算支持的，但是如何支持还没有具体的设计。

**Comment by zl-hw** [comment]
好的，非常感谢
