### ISSUE TITLE
Suggest to simplify the issue template

### ISSUE THREAD

**Issue by liuzhe-lz** [microsoft/nni#2518]
**Short summary about the issue/question**:

The issue template is too long and many customers did not read it.

**Brief what process you are following**:

1. File an issue on github
2. Choose template
3. Find the template is incredibly long
4. Ignore the template

**How to reproduce it**:

Same as above.

**nni Environment**:
- nni version: any
- nni mode(local|pai|remote): any
- OS: any
- python version: any
- is conda or virtualenv used?: not relevent
- is running in docker?: not relevent

**need to update document(yes/no)**: maybe?

**Anything else we need to know**:

Most parts of this template hardly provide useful information for us developers. And since it's too long many customers did not fill in the key parts.

The template should only contain three sections:
  1. Your problem
  2. NNI environment
  3. Log file

And there should be no hyperlink in the template. The hyperlinks are only clickable by issue viewers, not creators. Our developers don't need those links to learn how to find log.

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by scarlett2018** [comment]
done
