### ISSUE TITLE
Continuing experiments that is finished

### ISSUE THREAD

**Issue by MinfanZhao** [microsoft/nni#2520]
Hello, I'm new to NNI and I've conducted a experiment with the max time limit of 1 day. I've found the results pleasurable, and I wonder if I can continue an experiment which has finished because of the max time limit.

I'm using the `remote` mode with the MetisTuner.

Thanks!

**Comment by QuanluZhang** [comment]
@MinfanZhao yes, you can use [`nnictl update` command](https://nni.readthedocs.io/en/latest/Tutorial/Nnictl.html#update) to update experiment duration and max trial number.

**Comment by scarlett2018** [comment]
Closing the issue as the answer had been provided. @MinfanZhao - feel free to reopen the issue if the resolution provided above does not help.
