### ISSUE TITLE
Questions About Annotations

### ISSUE THREAD

**Issue by mitsuix** [microsoft/nni#2522]
NNI Annotation is a great work!

In this way, I can either run the python code directly or launch NNI to tune hyper-parameter in this code, without changing any codes.

But I found one problem:

If I use   '''@report_intermediate_result(acc)''' in another .py(imported by command-py) , It does not work. Any suggestions? or I should wrote all annotaions in command-py?

**Comment by QuanluZhang** [comment]
@mitsuix the annotations are not necessarily to be put in the command-py. If the "another .py " is under the code directory (i.e., `codeDir`), the annotation should work.

**Comment by mitsuix** [comment]
> @mitsuix the annotations are not necessarily to be put in the command-py. If the "another .py " is under the code directory (i.e., `codeDir`), the annotation should work.

It's in another dir now, not the codeDir, I will move it to the code directory and try again, thanks for your help~
