### ISSUE TITLE
Windows下NNI检测不到GPU

### ISSUE THREAD

**Issue by Scotty1027** [microsoft/nni#2528]
Windows系统nvidia-smi命令使用正常，出现和 #2055 相同的error，在gpu_metrics中显示如下：
{"Timestamp": "Wed Jun  3 18:24:50 2020", "gpuCount": 0, "gpuInfos": []}
看过其他issues后均未能解决问题，求帮助。

**nni Environment :**
- nni version: 1.6
- nni mode(local|pai|remote): local
- OS: Windows10
- python version: Python3.7
- is conda or virtualenv used?: conda used
- is running in docker?: no

**Comment by SparkSnail** [comment]
Hi @Scotty1027, does the `C:\Users\{youraccount}\AppData\Local\Temp\{youraccount}\nni\script` folder has any file in your machine?

**Comment by Scotty1027** [comment]
> Hi @Scotty1027, does the `C:\Users\{youraccount}\AppData\Local\Temp\{youraccount}\nni\script` folder has any file in your machine?

There are three files in this folder ：gpu_metrics,  gpu_metrics_collector,  pid

**Comment by Scotty1027** [comment]
[script.zip](https://github.com/microsoft/nni/files/4739085/script.zip)

**Comment by Scotty1027** [comment]
It shows like this
![output](https://user-images.githubusercontent.com/46108309/83983974-06da9200-a965-11ea-958f-800c844a1a09.png)

**Comment by SparkSnail** [comment]
Seems your machine could parse gpu info correctly, have no idea why the content in metric file generated by NNI is `{"Timestamp": "Wed Jun  3 17:11:02 2020", "gpuCount": 0, "gpuInfos": []}`. When you run this script manually, is the content in your `$env:METRIC_OUTPUT_DIR` correct? did you tried stop `gpu_metrics_collector` services in backend, and restart NNI experiment?

**Comment by Scotty1027** [comment]
Everything was fine when I ran it again earlier today. Interestingly, I did nothing.
Thanks for you kindness !

**Comment by Scotty1027** [comment]
Sorry to bother you again, There comes another problem.
When I use GPU to run it, the trial's status always shows Failed. But when I use CPU, it goes fine.
![trial_status](https://user-images.githubusercontent.com/46108309/84005937-83d72d00-a9a0-11ea-9763-4d904f15ff54.png)
The photo shows the status of trial when I use CPU, it's too slow.

**Comment by Scotty1027** [comment]
> Sorry to bother you again, There comes another problem.
> When I use GPU to run it, the trial's status always shows Failed. But when I use CPU, it goes fine.
> ![trial_status](https://user-images.githubusercontent.com/46108309/84005937-83d72d00-a9a0-11ea-9763-4d904f15ff54.png)
> The photo shows the status of trial when I use CPU, it's too slow.

I think I made a mistake in my code, now it's alright.
Thank you anyway.

**Comment by scarlett2018** [comment]
> Everything was fine when I ran it again earlier today. Interestingly, I did nothing.
> Thanks for you kindness !

closing the issue as it has been resolved
