### ISSUE TITLE
Provide Python or other language API to use NNI, so that it can be integrated in pipeline.

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/nni#2529]
**What would you like to be added**:
Provide programing API to use NNI, so that it can be integrated into continue data processing.

**Why is this needed**:
The hyper-parameters of model may need to be adjusted for different dataset. If some data is very dependent on HPO, AutoML is good to handle this situation. Especially, if AutoML cost is acceptable on feature engineering or on classic ML algorithms.

tpo and ray have this kind of API.

**Without this feature, how does current nni work**：
Currently, user need to call command line `nnictl` to start an experiment, and check restful API regularly, call `nnictl stop` once all trials are done.

**Brief description of your proposal if any**:

With APIs, user can
1. Start an experiment from code, like Python.
1. Once all trials are completed, all NNI resources are released automatically. User can be notified by callback, or end the sync call.
1. User can query score, duration, name, and parameters of top trials.

**Comment by kvartet** [comment]
this feature had been supported, see [here](https://nni.readthedocs.io/en/stable/Tutorial/HowToLaunchFromPython.html). So I will close this issue.
