### ISSUE TITLE
Post-training quantization support

### ISSUE THREAD

**Issue by juliocspires** [microsoft/nni#2537]
**What would you like to be added**:
Post-training quantization

TensorFlow: https://www.tensorflow.org/model_optimization/guide/quantization/post_training
PyTorch: https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html

**Why is this needed**:
Currently, NNI supports Quantization Aware Training(QAT). However, there are scenarios where training can be prohibitive and post-training quantization using an already pre-trained model can be interesting.

**Components that may involve changes**:
Model compression

**Comment by QuanluZhang** [comment]
@juliocspires , thanks for reporting your requirement. The quantization algorithms in NNI support post-training quantization. You can simply take a pretrained model and apply a quantization algorithm, the output will be a quantized model (simulated with float32). Real speedup of the quantized model (using lower bits) will be supported in V2.2, we use TensorRT to do the speedup.

**Comment by kvartet** [comment]
hello @juliocspires, it seems the feature had been supported in NNI, so I will close this issue, feel free to reopen it.
