### ISSUE TITLE
How to manually check the final architecture generated in NAS

### ISSUE THREAD

**Issue by SagnikMukherjee** [microsoft/nni#2543]
**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by ultmaster** [comment]
I think your intention is: how do I know the model implemented is correct?

I'm not sure whether this is helpful: https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html#inspect-the-model-using-tensorboard

**Comment by SagnikMukherjee** [comment]
I was able to do that, but i am not sure where the architecture is applied to the child_model in retrain.py. I think the json (architecture_xy.json) files have the information of the skipconnections. But not sure where you are saving the informatin about the layerchoices.

**Comment by ultmaster** [comment]
Can you post your `architecture.json` here? Do you think your layer choice info is missing?

**Comment by SagnikMukherjee** [comment]
{
  "InputChoice10": [
    false,
    true,
    true
  ],
  "InputChoice11": [
    false,
    false,
    true,
    false
  ],
  "InputChoice13": [
    true,
    true,
    false,
    false
  ],
  "InputChoice14": [
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice16": [
    false,
    false,
    true,
    false,
    true
  ],
  "InputChoice17": [
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice19": [
    false,
    false,
    true,
    false,
    true,
    false
  ],
  "InputChoice2": [
    true
  ],
  "InputChoice20": [
    false,
    false,
    true,
    false,
    false
  ],
  "InputChoice22": [
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice23": [
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice25": [
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice26": [
    false,
    false,
    false,
    false,
    true
  ],
  "InputChoice28": [
    false,
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    true
  ],
  "InputChoice29": [
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice31": [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice32": [
    false,
    false,
    false,
    false,
    true
  ],
  "InputChoice34": [
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    true
  ],
  "InputChoice35": [
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice37": [
    true,
    true,
    false,
    true,
    false,
    true,
    false,
    true,
    false,
    false,
    true,
    false
  ],
  "InputChoice38": [
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice4": [
    false
  ],
  "InputChoice40": [
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    true
  ],
  "InputChoice41": [
    false,
    false,
    true,
    false,
    false
  ],
  "InputChoice43": [
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    true,
    false,
    false
  ],
  "InputChoice44": [
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice46": [
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    true,
    false
  ],
  "InputChoice47": [
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice49": [
    false,
    false,
    true,
    false,
    true,
    false,
    true,
    true,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice5": [
    true,
    false
  ],
  "InputChoice50": [
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice52": [
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    true
  ],
  "InputChoice53": [
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice55": [
    false,
    false,
    false,
    true,
    true,
    false,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice56": [
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice58": [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false
  ],
  "InputChoice59": [
    false,
    false,
    true,
    false,
    false
  ],
  "InputChoice61": [
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    false
  ],
  "InputChoice62": [
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice64": [
    true,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    true,
    false
  ],
  "InputChoice65": [
    false,
    false,
    true,
    false,
    false
  ],
  "InputChoice67": [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false
  ],
  "InputChoice68": [
    false,
    false,
    false,
    false,
    true
  ],
  "InputChoice7": [
    true,
    true
  ],
  "InputChoice70": [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice8": [
    true,
    false,
    false
  ],
  "LayerChoice1": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice12": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice15": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice18": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice21": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice24": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice27": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice3": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice30": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice33": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice36": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice39": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice42": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice45": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice48": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice51": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice54": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice57": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice6": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice60": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice63": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice66": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice69": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice9": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ]
}
This is the content of the json file generated

**Comment by ultmaster** [comment]
Information in layer choices are presented in your file. So they should have been applied.

**Comment by SagnikMukherjee** [comment]
I mean, how does a specific layer know it is RNN or Convolutional layer?
Where is that information saved

**Comment by SagnikMukherjee** [comment]
Got it !! Thanks a lot.

**Comment by ultmaster** [comment]
```
"LayerChoice9": [
false,
false,
false,
true,
false,
false,
false,
false
]
```

You can see here: it is actually a one-hot representation of your choice. Suppose you have 3 options and the vector is `[false, true, false]`, it will choose the 2nd of 3.

**Comment by kvartet** [comment]
@SagnikMukherjee I’m closing this issue as it has no updates from user for 3 months, please feel free to reopen if you are still seeing it an active issue.
