### ISSUE TITLE
unable to run nni under window 10, as my company restrict the powershell script running

### ISSUE THREAD

**Issue by haoshuji** [microsoft/nni#2545]
**Short summary about the issue/question**: my company restricts the powershell script running which nni depends on it, so I got all failed on the trials, but I can run bash script under my window 10, so am wondering if there is anyway to let nni generate and run bash script for the trails under window 10. I saw this code: https://github.com/microsoft/nni/blob/69cae211e2790a14f5a0c667b4ac92daaad5ea00/src/nni_manager/training_service/common/util.ts
but not sure if other codes need to be changed

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:latest
- nni mode(local|pai|remote): local
- OS:windows 10
- python version:3.7
- is conda or virtualenv used?: conda
- is running in docker?:no

**need to update document(yes/no)**:

**Anything else we need to know**:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by liuzhe-lz** [comment]
If you mean WSL or Cygwin, you can use NNI inside it but you are unlikely to be able to use CUDA.
Otherwise NNI does not support Windows OS without powershell. This environment is too unique so NNI will not support it.

**Comment by scarlett2018** [comment]
does run Linux APP on Windows help with this problem?

**Comment by kvartet** [comment]
hello @haoshuji, I will close this issue as it has not been updated for more than three months, feel free to reopen it if you still think it an active issue.
