### ISSUE TITLE
Allow trainingServicePlatform: remote, machineList to support hostname in addition to ip

### ISSUE THREAD

**Issue by awwong1** [microsoft/nni#2546]
**What would you like to be added**:

Please add support for hostnames in [machineList](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#machinelist) configuration of remote experiments.

**Why is this needed**:

- Will support servers that do not have public facing static IP addresses.
- Can be used in combination with [ssh_config](https://linux.die.net/man/5/ssh_config), e.g. ssh-tunneling proxy
- allows definitions in `/etc/hosts`

**Without this feature, how does current nni work**：

Setting a hostname in the ip address field throws the following error:
```text
ERROR: Failed! Error is: {"statusCode":400,"error":"Bad Request","message":"child \"body\" fails because [child \"machine_list\" fails because [\"machine_list\" at position 0 fails because [child \"ip\" fails because [\"ip\" must be a valid ip address with a optional CIDR]]]]"}
```

**Components that may involve changes**:

[/src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts](https://github.com/microsoft/nni/blob/master/src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts)

**Brief description of your proposal if any**:

Behaviour should match [nodejs http server.listen()](https://nodejs.org/dist/latest-v12.x/docs/api/net.html#net_server_listen_port_host_backlog_callback), which [supports hostname strings](https://stackoverflow.com/questions/34715797/how-to-use-the-optional-hostname-parameter-in-node-js-server-listen)

**Comment by ultmaster** [comment]
I met the same problem. Thanks!
