### ISSUE TITLE
Do we need to download Imagenet dataset for ProxylessNAS example?

### ISSUE THREAD

**Issue by curiousjit** [microsoft/nni#2553]
Short summary about the issue/question:
When I try to run [ProxylessNAS](https://github.com/microsoft/nni/tree/master/examples/nas/proxylessnas) example, I get an error that the dataset folder isn't found. Do we have to manually download Imagenet?  

nni Environment:

    nni version: 1.5
    nni mode(local|pai|remote): local
    OS: Linux
    python version: 3.6.10
    is conda or virtualenv used?: Conda
    is running in docker?: No

need to update document(yes/no): no

Anything else we need to know: no

**Comment by ultmaster** [comment]
Yes. You need to manually download ImageNet.

**Comment by curiousjit** [comment]
Thank you!
