### ISSUE TITLE
duplicated Trial No. on webui when an experiment is resumed

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#2560]
**Environment**:
- NNI version: 1.6
- NNI mode (local|remote|pai): local
- Client OS: ubuntu 16.04
- Server OS (for remote mode only):
- Python version: 3.5
- PyTorch/TensorFlow version: --
- Is conda/virtualenv/venv used?: No
- Is running in Docker?: No

 

**What issue meet, what's expected?**: duplicated Trial No. on webui when an experiment is resumed

![image](https://user-images.githubusercontent.com/16907603/84742220-c02f0c80-afe2-11ea-9337-fa469fc4abd7.png)

**How to reproduce it?**: resume an experiment

**Additional information**: --

**Comment by squirrelsc** [comment]
It needs to fix manual created trial get null name too.

**Comment by Lijiaoa** [comment]
This issue had been fixed in v1.8 
PR #https://github.com/microsoft/nni/pull/2760
