### ISSUE TITLE
weights initialization before NAS searching starts

### ISSUE THREAD

**Issue by MarkMa1990** [microsoft/nni#2582]
**Environment**: Ubuntu 16.04
- NNI version: 1.6
- NNI mode (local|remote|pai): local
- Client OS: Ubuntu 16.04
- Server OS (for remote mode only):
- Python version: python 3.6
- PyTorch/TensorFlow version: PyTorch
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

Guys, I am thinking whether it is possible to initialize weights before NAS searching? For example, ENAS. I though the weights are shared between different ENAS layers, however I got errors saying something like hyper-parameters are not the same, so the loading of weights failed. 

**How to reproduce it?**: 

**Additional information**:

**Comment by QuanluZhang** [comment]
@MarkMa1990 we have not exposed an API for users to initialize weights. One approach is writing your own trainer. For example, copy EnasTrainer code and add your own initialization logic in the trainer.

If you want to further debug the errors you got, please attach the error message here.

**Comment by scarlett2018** [comment]
Where can you find the log files: [log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-director), [stdout/stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout)
