### ISSUE TITLE
ImportError: cannot import name 'merge_parameter'

### ISSUE THREAD

**Issue by dany5399** [microsoft/nni#2590]
From what I can tell this is the only one that cannot be imported from the module nni.utils. The other functions can be imported just fine.

This was taken from the Pytorch MNIST example provided:
```
import os
import argparse
import logging
import nni
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from nni.utils import merge_parameter
from torchvision import datasets, transforms
```

**Comment by ultmaster** [comment]
You need to checkout the example from branch v1.6 if you are running the examples with nni v1.6
