### ISSUE TITLE
How to view the final architecture found in NAS?

### ISSUE THREAD

**Issue by curiousjit** [microsoft/nni#2592]
Short summary about the issue/question:

After running the one shot NAS example, we get the final architectures in a JSON file. However I want to view the final architecture as shown in [ENAS](https://arxiv.org/pdf/1802.03268.pdf) or [DARTS](https://arxiv.org/pdf/1806.09055.pdf) papers. I know this question might be similar to [1191](https://github.com/microsoft/nni/issues/1991#issue-558968527) but NAS visualization has a complicated; specially for a large search space with DARTS. I know NAS visualization is still experimental but I was wondering if there is any other way to visualize the final architecture from the JSON file. Can we parse the JSON file and build the topology of final architecture by ourselves by using layer and input choices values? 

nni Environment:

    nni version: 1.5
    nni mode(local|pai|remote): local
    OS: Linux
    python version: 3.6.10
    is conda or virtualenv used?: Conda
    is running in docker?: No

**Comment by QuanluZhang** [comment]
@curiousjit NAS visualization is for monitoring and analyzing the whole search process. Of course, the final exported architecture should be visualized on NAS UI. This is still an ongoing task.

Your requirement is simply visualizing the exported architecture, we will put it in our plan. Also highly encourage you to contribute on this feature :)

**Comment by QuanluZhang** [comment]
@curiousjit thanks for your interest on contributing this part. [This file](https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/_graph_utils.py) is how NNI gets topology of a pytorch model. You can get the topology and extract the module (e.g., cell) that you want to visualize, then update the topology with the exported final architecture. The updated topology is supposed to be visualized by any graph visualization library.
