### ISSUE TITLE
 I am a student of Tsinghua University. I sincerely hope to get a reply. After I gave the model trained and stored by NNI to other students, they made an error in loading the model on the machine without NNI, indicating that some modules of NNI could not be found 

### ISSUE THREAD

**Issue by xianglei3** [microsoft/nni#2593]
**Environment**: ubuntu 
- NNI version: 1.5
- NNI mode (local|remote|pai): local
- Client OS:
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version:1.3
- Is conda/virtualenv/venv used?:no
- Is running in Docker?: yes

**Log message**:

Traceback (most recent call last):
  File "inference.py", line 243, in <module>
    re =  test('1.jpg',"love")
  File "inference.py", line 171, in test
    net=torch.load(savepath+"/1.pth")    
  File "/home/gpdi/.local/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/gpdi/.local/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'nni.networkmorphism_tuner'

 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

 I use the following code to save the model in an environment containing NNI  
 torch.save(net, savepath+"/1.pth")

then  i use the  model in other environment
net=torch.load(savepath+"/1.pth")

i meet error :
File "/home/gpdi/.local/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'nni.networkmorphism_tuner'

**How to reproduce it?**: 
 When using the model of NNI training in other environments where NNI is not installed 

**Additional information**:

**Comment by chicm-ms** [comment]
It depends on how to save the model, if your model code is using nni, nni needs to be installed.
Would you please show how the model is saved?

**Comment by xianglei3** [comment]
i save the mode like this :         
torch.save(net, savepath+"/1.pth")
 The complete code file is ： /root/nni/examples/trials/network_morphism/cifar10/cifar10_pytorch.py
 When I finish training, use the code above to save the model

**Comment by xianglei3** [comment]
Please tell me how to save the model (including network structure and weight) after training, and then tell me how to load the model when I need to use it

**Comment by chicm-ms** [comment]
`net=torch.load(savepath+"/1.pth")` is the right way to load the model.   Since the model is built using nni SDK, nni is needed to be installed on the system it is loaded.

**Comment by kvartet** [comment]
I’m closing this issue as it has no updates from customer for 3 months, please feel free to reopen if you are still seeing it an active issue.
