### ISSUE TITLE
如何使用proxylessNAS来对CIFAR10进行搜索

### ISSUE THREAD

**Issue by YeliTXK** [microsoft/nni#2598]
后续会添加ProxylessNASz中针对CIFAR10数据搜索的代码吗？
如果使用MobileNetv2的backbone来针对CIFAR数据集建立搜索空间，可能得到较好的效果吗？
（我尝试了一下效果很差，是因为我的设置问题，还是MobileNetv2的backbone本身不适合CIFAR10数据集？）
希望得到您的回复。

**Comment by QuanluZhang** [comment]
@YeliTXK , to use cifar10, you can simple provide your own `train_loader` ([doc here](https://nni.readthedocs.io/en/latest/NAS/Proxylessnas.html#usage)). If you want to use a new search space based on MobileNetv2, you can use NNI NAS API to write the model.

For the question about experiment on cifar10, @ultmaster could provide more information on this. Also welcome to share your experience here.

**Comment by ultmaster** [comment]
I haven't seen many works running CIFAR10 on MobileNetV2 backbone. Haven't tried myself though.

An easy way to verify is to randomly sample a few models (e.g., 20) and train them sufficiently on CIFAR10. Then you will find out, whether it's the problem with search space, or training approach, or ProxylessNAS itself.

**Comment by YeliTXK** [comment]
> I haven't seen many works running CIFAR10 on MobileNetV2 backbone. Haven't tried myself though.
> 
> An easy way to verify is to randomly sample a few models (e.g., 20) and train them sufficiently on CIFAR10. Then you will find out, whether it's the problem with search space, or training approach, or ProxylessNAS itself.

Thanks a lot.
