### ISSUE TITLE
How to continually learning?

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#2611]
For example, in the beginning, maybe there are only 3 classes. Because my data is gradually increasing, then there come 1 or 2 new classes. So I wonder does NNI support adaptively support increasing classes when training the neural network. If no, any plan or possible solution to solve this problem?

**Comment by chicm-ms** [comment]
We do not have plan to support this in NNI recently. 
Possible solutions:
1. If you have 3 classes and you estimate there will be at most 100 classes, you can create a model with 100 classes. Fine tune with all data when new data available every time.
2. If you already have a trained 3 classes model,  create a model with  100 classes, copy the weight from 3 classes model to 100 classes model,  check the evaluation result using 3 classes, it should be same.  Then finetune with all data.

**Comment by scarlett2018** [comment]
Thanks for raising the issue, closing it as it is out of our plan and scope.
