### ISSUE TITLE
 I have been studying NNI in Tsinghua University for one year. We want to know how to save the model and weight (note not only the model corresponding to JSON, but also the weight). In addition, how to give the saved model and weight to other friends. In particular, how to use it for friends who have not installed the NNI environment? Thank you. Thank you very much. 

### ISSUE THREAD

**Issue by xianglei3** [microsoft/nni#2618]
I have been studying NNI in Tsinghua University for one year. We want to know how to save the model and weight (note not only the model corresponding to JSON, but also the weight). In addition, how to give the saved model and weight to other friends. In particular, how to use it for friends who have not installed the NNI environment? Thank you. Thank you very much.

**Comment by scarlett2018** [comment]
seems like a duplicated issue.

**Comment by kvartet** [comment]
I’m closing this issue as it has no updates from customer for 3 months, please feel free to reopen if you are still seeing it an active issue.
