### ISSUE TITLE
Wrong key 'gpuNum' in {'builtinAssessorName': 'Medianstop', 'classArgs': {'optimize_mode': 'maximize'}, 'gpuNum': 0}

### ISSUE THREAD

**Issue by yttan** [microsoft/nni#2619]
**Environment**:
- NNI version:
1.6
- NNI mode (local|remote|pai):
remote
- Client OS:
ubuntu
- Server OS (for remote mode only):
centos
- Python version:
python3
- PyTorch/TensorFlow version:
the version in the msranni/nni:latest image
- Is conda/virtualenv/venv used?:
no
- Is running in Docker?:
client side(nnictl) not in docker, remote side is kubeflow.

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
```
ERROR: Your config file is not correct, please check your config file content!
ERROR: Wrong key 'gpuNum' in {'builtinAssessorName': 'Medianstop', 'classArgs': {'optimize_mode': 'maximize'}, 'gpuNum': 0}
```
 

**What issue meet, what's expected?**:

I tried examples/trials/mnist-distributed/config_kubeflow.yml, and got the above error.

**How to reproduce it?**: 

use the config in examples/trials/mnist-distributed
```
nnictl create --config config_kubeflow.yml
```
**Additional information**:

There is no key 'gpuNum' in 'assessor' field according to [config reference](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md)

It seems that the [document](https://github.com/microsoft/nni/blob/master/docs/en_US/TrainingService/KubeflowMode.md#run-an-experiment) and examples are wrong.

**Comment by SparkSnail** [comment]
Thanks, have a pr to fix doc. https://github.com/microsoft/nni/pull/2641

**Comment by yttan** [comment]
Thanks, I will close this issue.
