### ISSUE TITLE
can not write metric in .nni/metric

### ISSUE THREAD

**Issue by LovPe** [microsoft/nni#2624]
Hello,
Thanks for amazing work. I`m using nni for Auto Tuning with detectron2 in pytorch for object detection task and I encounter a problem when using multi-gpu for training.
When training with multi-gpu, nni can not write results into .nni/metric so that no metric results showed in webUI. 
When training with single-gpu, it works well and all results is all right.
Here is the code for detectron2 to implement distributed training:
```
def _find_free_port():
    import socket

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    # Binding to port 0 will cause the OS to find an available port for us
    sock.bind(("", 0))
    port = sock.getsockname()[1]
    sock.close()
    # NOTE: there is still a chance the port could be taken by other processes.
    return port


def launch(main_func, num_gpus_per_machine, num_machines=1, machine_rank=0, dist_url=None, args=()):
    """
    Launch multi-gpu or distributed training.
    This function must be called on all machines involved in the training.
    It will spawn child processes (defined by ``num_gpus_per_machine`) on each machine.

    Args:
        main_func: a function that will be called by `main_func(*args)`
        num_gpus_per_machine (int): number of GPUs per machine
        num_machines (int): the total number of machines
        machine_rank (int): the rank of this machine
        dist_url (str): url to connect to for distributed jobs, including protocol
                       e.g. "tcp://127.0.0.1:8686".
                       Can be set to "auto" to automatically select a free port on localhost
        args (tuple): arguments passed to main_func
    """
    world_size = num_machines * num_gpus_per_machine
    if world_size > 1:
        # https://github.com/pytorch/pytorch/pull/14391
        # TODO prctl in spawned processes

        if dist_url == "auto":
            assert num_machines == 1, "dist_url=auto not supported in multi-machine jobs."
            port = _find_free_port()
            dist_url = f"tcp://127.0.0.1:{port}"
        if num_machines > 1 and dist_url.startswith("file://"):
            logger = logging.getLogger(__name__)
            logger.warning(
                "file:// is not a reliable init_method in multi-machine jobs. Prefer tcp://"
            )

        mp.spawn(
            _distributed_worker,
            nprocs=num_gpus_per_machine,
            args=(main_func, world_size, num_gpus_per_machine, machine_rank, dist_url, args),
            daemon=False,
        )
    else:
        main_func(*args)


def _distributed_worker(
    local_rank, main_func, world_size, num_gpus_per_machine, machine_rank, dist_url, args
):
    assert torch.cuda.is_available(), "cuda is not available. Please check your installation."
    global_rank = machine_rank * num_gpus_per_machine + local_rank
    try:
        dist.init_process_group(
            backend="NCCL", init_method=dist_url, world_size=world_size, rank=global_rank
        )
    except Exception as e:
        logger = logging.getLogger(__name__)
        logger.error("Process group URL: {}".format(dist_url))
        raise e
    # synchronize is needed here to prevent a possible timeout after calling init_process_group
    # See: https://github.com/facebookresearch/maskrcnn-benchmark/issues/172
    comm.synchronize()

    assert num_gpus_per_machine <= torch.cuda.device_count()
    torch.cuda.set_device(local_rank)

    # Setup the local process group (which contains ranks within the same machine)
    assert comm._LOCAL_PROCESS_GROUP is None
    num_machines = world_size // num_gpus_per_machine
    for i in range(num_machines):
        ranks_on_i = list(range(i * num_gpus_per_machine, (i + 1) * num_gpus_per_machine))
        pg = dist.new_group(ranks_on_i)
        if i == machine_rank:
            comm._LOCAL_PROCESS_GROUP = pg

    main_func(*args)

```

**Comment by chicm-ms** [comment]
@LovPe ,
Thanks for reporting this issue.
Where did you call `nni.report_intermediate_result()` and `nni.report_final_result()`, could you paste the code piece? And how many machines are you using for training?
detetron2 uses DistributedDataParallel for multi GPU training, it launch one process per GPU for training,  is it possible for you to report metrics to NNI only on one of the GPU?  multiple process call `nni.report_intermediate_result()` concurrently may cause some problem.

**Comment by LovPe** [comment]
@chicm-ms Thanks for your reply
1-  I write nni.report_intermediate_result() and nni.report_final_result() in Evalhook like this:
when training, trainer will call `_do_eval`. So I write report code in line31-39
'''
1. class EvalHook(HookBase):
2.     """
3.     Run an evaluation function periodically, and at the end of training.
4. 
5.     It is executed every ``eval_period`` iterations and after the last iteration.
6.     """
7. 
8.     def __init__(self, eval_period, eval_function, main_metric=None):
9.         """
10.         Args:
11.             eval_period (int): the period to run `eval_function`.
12.             eval_function (callable): a function which takes no arguments, and
13.                 returns a nested dict of evaluation metrics.
14.             main_metric (str or None): main metric used for nni training
15.         Note:
16.             This hook must be enabled in all or none workers.
17.             If you would like only certain workers to perform evaluation,
18.             give other workers a no-op function (`eval_function=lambda: None`).
19.         """
20.         self._period = eval_period
21.         self._func = eval_function
22.         self._main_metric = main_metric
23. 
24.     def _do_eval(self, is_final):
25.         results = self._func()
26. 
27.         if results:
28.             assert isinstance(
29.                 results, dict
30.             ), "Eval function must return a dict. Got {} instead.".format(results)
31.             if self._main_metric is not None and comm.is_main_process():
32.                 assert isinstance(self._main_metric, tuple) and len(self._main_metric) == 2
33.                 if self._main_metric[0] in results.keys():
34.                     nni_result = copy.deepcopy(results)
35.                     nni_result["default"] = float(nni_result[self._main_metric[0]][self._main_metric[1]])
36.                     if is_final:
37.                         nni.report_final_result(nni_result)
38.                     else:
39.                         nni.report_intermediate_result(nni_result)
40.             flattened_results = flatten_results_dict(results)
41.             for k, v in flattened_results.items():
42.                 try:
43.                     v = float(v)
44.                 except Exception:
45.                     raise ValueError(
46.                         "[EvalHook] eval_function should return a nested dict of float. "
47.                         "Got '{}: {}' instead.".format(k, v)
48.                     )
49.             self.trainer.storage.put_scalars(**flattened_results, smoothing_hint=False)
50. 
51.         # Evaluation may take different time among workers.
52.         # A barrier make them start the next iteration together.
53.         comm.synchronize()
54. 
55.     def after_step(self):
56.         next_iter = self.trainer.iter + 1
57.         is_final = next_iter == self.trainer.max_iter
58.         if is_final or (self._period > 0 and next_iter % self._period == 0):
59.             self._do_eval(is_final)
60. 
61.     def after_train(self):
62.         # func is likely a closure that holds reference to the trainer
63.         # therefore we clean it to avoid circular reference in the end
64.         del self._func
'''

2-I use One machine with 2 GPU for training and testing and i use` comm.is_main_process()` to make sure only rank0 process can write. but the nni still can not wrire

**Comment by chicm-ms** [comment]
Hi @LovPe,
Thanks,  And would you please collect the trial log files (`trail.log`, `stderr`)?  you can find them per this doc:
https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory

**Comment by LovPe** [comment]
@chicm-ms Thanks for your reply. 
finally I find that This issue may caused by a remote desktop software(NoMachine on ubuntu16.4). After closing it and restart, nni works well.
So this issue may not caused by nni. 
I will close it. Again thanks for your help.
