### ISSUE TITLE
Error in NAS Visualization

### ISSUE THREAD

**Issue by kingaza** [microsoft/nni#2626]
**Environment**:
- NNI version: 1.5
- NNI mode (local|remote|pai): local
- Client OS: Win10
- Server OS (for remote mode only): 
- Python version: 3.7
- PyTorch/TensorFlow version: pytorch 1.5
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

I just follow guidance of ENAS:
`python search.py --visualization`
And the file graph.json is generated.

Then I try to have a look at the graph, but an error occurs on the browser:

```
(base) D:\3_Dev\nni\examples\nas\enas>nnictl webui nas --logdir=logs/1593596326.5554986
INFO: Starting NAS UI...
NNI NAS board is running on port 6060, logdir is logs/1593596326.5554986.
Error: ENOENT: no such file or directory, stat 'c:\programdata\anaconda3\nni\nasui\build\index.html'
```

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by ultmaster** [comment]
Hi, thanks for raising this issue? Could you list the contents in `c:\programdata\anaconda3\nni\nasui\`?

**Comment by kingaza** [comment]
Just now I upgrade NNI to 1.6, and the problem exists still.

Here is the contents, which seems that the build folder is missing...

 Directory of c:\ProgramData\Anaconda3\nni\nasui

07/02/2020  01:29 PM    <DIR>          .
07/02/2020  01:29 PM    <DIR>          ..
07/02/2020  01:29 PM             1,317 asset-manifest.json
07/02/2020  01:29 PM             2,287 icon.png
07/02/2020  01:29 PM             2,127 index.html
07/02/2020  01:29 PM             3,692 precache-manifest.0d13a53530427193f45755f892a0099d.js
07/02/2020  01:29 PM               854 server.js
07/02/2020  01:29 PM             1,183 service-worker.js
07/02/2020  01:29 PM    <DIR>          static
               6 File(s)         11,460 bytes
               3 Dir(s)  100,641,812,480 bytes free

**Comment by ultmaster** [comment]
Sorry for slow response. Are you still on this problem?

How did you install nni? From source or via pip install? Have you tried other environments like installing it in virtualenv?

**Comment by kingaza** [comment]
I suppose the problem still exists...
nni was install via pip, just in the base env. I would like to try it in other environment if helpful.

**Comment by mystous** [comment]
I'v faced same issue.

I copy all files in 'c:\programdata\anaconda3\nni\nasui' into 'c:\programdata\anaconda3\nni\nasui\build' after created build directory.
It worked temporary.

**Comment by tuttelikz** [comment]
@kingaza, i got exactly same issue (MacOS, conda). This is what worked for me.
Try to set global path for logdir argument instead of local, like as follows:
`nnictl webui nas --logdir /Users/tuttelikz/Documents/logs/1613294510.0829813 --port 6070`
And then access as usual from browser locally: "http://localhost:6070"

**Comment by scarlett2018** [comment]
closing as overdue (NNI v1.5).
