### ISSUE TITLE
 I am an intern in Tencent. I want to save the model and weight after the classification task training. I want to know how to save the weight. When I try to save the weight for others to use, I have the following error. I am looking forward to your reply. I am very grateful. We have more than 300 colleagues who hope that we can not only save the model, but also save the weight, and then use it for others 

### ISSUE THREAD

**Issue by xianglei3** [microsoft/nni#2636]
**Environment**:
- NNI version: 1.6
- NNI mode (local|remote|pai):
- Client OS: remote
- Server OS (for remote mode only):
- Python version:3
- PyTorch/TensorFlow version: 1
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: yes

**Log message**:
i save the  model  like this :  
torch.save(net, savepath+"/1.pth")

i use the model like this:
net=torch.load(savepath+"/1.pth")

the error is 
File "inference.py", line 171, in test
    net=torch.load(savepath+"/1.pth")    
  File "/home/gpdi/.local/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/gpdi/.local/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'nni.networkmorphism_tuner'

 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
 Models and weights can be saved and loaded successfully elsewhere, even in environments where NNI is not installed 

**How to reproduce it?**: 

save and load the net and weights 

**Additional information**:

**Comment by scarlett2018** [comment]
Closing the issue, as per offline discussion, this seems not an NNI issue but an missing dependency installaion. @xianglei3 feel free to reopen if it is still a problem on your side.
