### ISSUE TITLE
nnictl command not found(may be because of failing to add the necessary environment variable)

### ISSUE THREAD

**Issue by linbinskn** [microsoft/nni#2644]
**Environment**:
- NNI version: v1.7 testpkg
- NNI mode (local|remote|pai): local
- Client OS: ubuntu18.04, windows10
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version: not used
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: no

**Log message**:
 - command line: nnictl command not found

**What issue meet, what's expected?**:
After installing nniv1.7, the command "nnictl *" command can't be used directly. The error 'nnictl command not found' is caused and no warning about this problem emerging in the log. But when I manually add "/home/user/.local/bin" to the path variable, the 'nnictl *' command can be used normally.

**How to reproduce it?**: 
The specific condition to cause this problem haven't been comfirmed.   '/home/user/.local/bin' is not in the path after installing.
**Additional information**:
The nni version is v1.7 and the OS version is ubuntu 18.04.  The os is newly installed.

**Comment by JunweiSUN** [comment]
Hi, @linbinskn ,do you install nni by `pip install` or  from source code? By default nni will not add `/home/user/.local/bin` to your PATH, but it will show an info to suggest you add this path when the installation finished.

**Comment by linbinskn** [comment]
Get it, thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junwei Sun"<notifications@github.com&gt;; 
发送时间: 2020年7月8日(星期三) 中午1:30
收件人: "microsoft/nni"<nni@noreply.github.com&gt;; 
抄送: "756691769"<756691769@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [microsoft/nni] nnictl command not found(may be because of failing to add the necessary environment variable) (#2644)





 
Hi, @linbinskn ,do you install nni by pip install or  from source code? By default nni will not add /home/user/.local/bin to your PATH, but it will show an info to suggest you add this path when the installation finished.
