### ISSUE TITLE
Support dict metrics (switching keys) in intermediate result charts

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#2661]
If intermediate results are dicts with multiple keys, perferrably we can switch the key we are interested in.

**Comment by tabVersion** [comment]
Exactly what I need! 👍

**Comment by Lijiaoa** [comment]
@ultmaster @tabVersion Looks like we had supported dict intermediate result, but on v1.9-v2.2, we don't support this function.
And now we are planning to resupport dict on v2.3!
