### ISSUE TITLE
Running on the remote mode failed when number of servers surpasses 10

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2678]
Running on the remote mode when the number of servers surpasses 10 raise the error:
```
ERROR: Failed! Error is: {"error":"TrainingService setClusterMetadata timeout. Please check your config file."}
```
Having tested on the first 9 servers and the last 9 servers.

**Comment by SparkSnail** [comment]
https://github.com/microsoft/nni/pull/2725
