### ISSUE TITLE
RuntimeError: Has not supported infering input/output shape from mask for module/function: `ConvTranspose2d`, decoder4.deconv2

### ISSUE THREAD

**Issue by sunxirui310** [microsoft/nni#2707]
**Environment**:
- NNI version: 1.7
- NNI mode (local|remote|pai):local
- Client OS:windows 10
- Server OS (for remote mode only):
- Python version:3.7
- PyTorch/TensorFlow version: pytorch 1.5.1
- Is conda/virtualenv/venv used?:Y
- Is running in Docker?:N

**Log message**:
  File "C:\ProgramData\Anaconda3\lib\site-packages\nni\compression\torch\speedup\compressor.py", line 184, in speedup_model
    self.infer_modules_masks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nni\compression\torch\speedup\compressor.py", line 143, in infer_modules_masks
    self.infer_module_mask(module_name, None, mask=mask)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nni\compression\torch\speedup\compressor.py", line 99, in infer_module_mask
    .format(m_type, module_name))
RuntimeError: Has not supported infering input/output shape from mask for module/function: `ConvTranspose2d`, decoder4.deconv2

speedup_model cannot support processing "ConvTranspose2d"? or someting goes wrong with my environment?
thank you

**Comment by QuanluZhang** [comment]
@sunxirui310 thanks for reporting this issue. `ConvTranspose2d` has not been supported yet. For model speedup, operator's input/output shape should be properly inferred. This relies on writing shape inference logic for each operator.

**Comment by fantasy-fish** [comment]
Has ConvTranspose2D been supported now?

**Comment by Tudor33** [comment]
Ok ai go beak

Dne út 20. 10. 2020 21:16 uživatel fantasy-fish <notifications@github.com>
napsal:

**Comment by zheng-ningxin** [comment]
@fantasy-fish @sunxirui310   Hi~ Sorry for the late support, I am working it now and when it is done I'll let you know ASAP. Thanks~

**Comment by fantasy-fish** [comment]
Hi, I also met the same problem on the upsample layer. 
RuntimeError: Has not supported infering output shape from input shape for module/function: `Upsample`, res_feat1.5.up.0
Is there any advice on how to do it by ourselves?

**Comment by fantasy-fish** [comment]
In infer_shape.py, I implemented the upsample_inshape function in this way. Is it correct?
I also used then same infer_shape function for add operation to aten::sub.
```python
def upsample_inshape(module_masks, mask):
    assert isinstance(mask, CoarseMask)
    assert mask.mask_index[1] is not None
    assert mask.mask_index[0] is None
    assert mask.mask_index[2] is None
    assert mask.mask_index[3] is None
    if module_masks.input_mask is not None:
        assert module_masks.input_mask <= mask
    # assert module_masks.input_mask is None
    module_masks.set_input_mask(mask)
    module_masks.set_output_mask(mask)
    return mask
```

**Comment by guojunyao419** [comment]
@zheng-ningxin Hi, just would like to follow up on this issue. Do you have an ETA when `ConvTranspose2d` will be supported in model speed-up? Thanks.
