### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by htx-DeepLearning** [microsoft/nni#2709]
**Environment**:
- NNI version:1.7
- NNI mode (local|remote|pai):local
- Client OS:ubuntu
- Server OS (for remote mode only):
- Python version:3.7.3
- PyTorch/TensorFlow version: PyTorch 1.5.0
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
`Traceback (most recent call last):
  File "testFPGM.py", line 66, in <module>
    m_speedup.speedup_model()
  File "/home/htx/anaconda3/envs/modelcompression/lib/python3.7/site-packages/nni/compression/torch/speedup/compressor.py", line 182, in speedup_model
    fix_mask_conflict(self.masks, self.bound_model, self.dummy_input)
  File "/home/htx/anaconda3/envs/modelcompression/lib/python3.7/site-packages/nni/compression/torch/utils/mask_conflict.py", line 47, in fix_mask_conflict
    masks = padding_cat_mask.fix_mask()
  File "/home/htx/anaconda3/envs/modelcompression/lib/python3.7/site-packages/nni/compression/torch/utils/mask_conflict.py", line 126, in fix_mask
    b_shape = module.bias.data.size()
AttributeError: 'NoneType' object has no attribute 'data'`

 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
Using nni "FPGM" method to speedup a classification model in which convolution layers have no bias, and got error "AttributeError: 'NoneType' object has no attribute 'data'";

**How to reproduce it?**: 

**Additional information**:
After got this error, I add a statement in `mask_conflict.py` Line 125, from `if hasattr(module, 'bias'):` to `if hasattr(module, 'bias')  and module.bias is not None:`. It works fine. 
But the accuracy is extremely low when using speedup, it's about 2%.
I also calculate the accuracy when using apply_compression_results, it's a about 95%.

Moreover, I inspect the model weights between "apply_compression_results" and "speedup", and I find that the weights seems 
not to be loaded properly. The followings are sum value of each channel in second convolution layer (The first convolution layer is normal ):
Using apply_compression_results:

![emobile_2020-07-22_11-44-49](https://user-images.githubusercontent.com/51436385/88132044-09413480-cc11-11ea-9fe0-e1218070518a.png)
Using speedup:

![emobile_2020-07-22_11-45-00](https://user-images.githubusercontent.com/51436385/88132047-0a726180-cc11-11ea-98a3-58dd77d7ed9c.png)

Ps: I also tried other methods such as L1FilterPruner, and got the same results above.

**Comment by chicm-ms** [comment]
@htx-DeepLearning   Thanks for reporting this issue.  Would you please paste your model code?

**Comment by htx-DeepLearning** [comment]
@chicm-ms 
I load the model weights here:
`masks_file= 'Mask_DenseNet.pth'` 
`model = DenseNet(32, (6, 12, 32, 32), 64, num_classes=100, memory_efficient=False)`
`model.load_state_dict(torch.load('Prune_denseNet.pth'))`
`model.to('cuda:0')`
`model.eval()`

Using apply_compression_results:
`apply_compression_results(model, masks_file= masks_file )`

Using: ModelSpeedup
`dummy_input = torch.randn([64,3,224,224]).to('cuda:0')`
`m_speedup = ModelSpeedup(model, dummy_input, masks_file= masks_file )`
`m_speedup.speedup_model()`

**Comment by chicm-ms** [comment]
@htx-DeepLearning what is your version of `torchvision` ?
Densenet has not been supported yet by `model_speedup` and we are working on it, but my error result of densenet169 is not exactly same as yours, so I would like to know your version of torchvision. My torchvison version is 0.6.0 and torch is v1.5.0.
We have tested vgg, resnet, mobilenet, squeezenet and mobilenet_v2, you can try with these.

**Comment by htx-DeepLearning** [comment]
@chicm-ms
It's strange, I use the same version as yours. One possible reason maybe that I only compress some convolution layers instead of the whole network. The following is the config list, and I hope it will be helpful.
[config_list.txt](https://github.com/microsoft/nni/files/4963837/config_list.txt)

**Comment by chicm-ms** [comment]
I can reproduce your first `AttributeError: 'NoneType' object has no attribute 'data'` problem with your config_list, but can not reproduce the second one (lay sum problem).  
Do you use the same `dummy_input` data for both speed up model and apply_compression_results model?  `torch.randn` generates different data every time.   And please ensure call model.eval() before calling forward pass.

**Comment by htx-DeepLearning** [comment]
@chicm-ms
I think it's nothing to do with the input data, and I just inspect the model weights obtained from `model_speedup` and `apply_compression_results`.
Would you just calculate the sum value of the weights  in second convolution layer after applying `model_speedup` and `apply_compression_results` separately? It should be same, but it's different.

**Comment by chicm-ms** [comment]
@htx-DeepLearning Thanks, I can reproduce your problem now.  We are planning to support densenet speedup in next release.

**Comment by htx-DeepLearning** [comment]
@htx-DeepLearning
Thanks for your work.
