### ISSUE TITLE
是否支持scikit-learn==0.23.1

### ISSUE THREAD

**Issue by pengliang1226** [microsoft/nni#2763]
**Environment**:
- NNI version:
- NNI mode (local|remote|pai):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by scarlett2018** [comment]
Thanks for raising the issue. Current support is still for 0.22, will plan for 0.23.1 later. You are encouraged to help us with this feature =)!

**Comment by kvartet** [comment]
Sorry for the delayed reply, NNI has already supported scikit-learn==0.23.1 and will support scikit-learn==0.24.1 in version 2.1.
So I'm closing the issue, please feel free to reopen if you are still seeing it as an active issue.
