### ISSUE TITLE
sort NaN trials furthest from optimal trials in WebUI

### ISSUE THREAD

**Issue by yhidaka** [microsoft/nni#2775]
Currently NaN appears to be treated as zero when sorting the "Default metric" column in WebUI. (I'm using NNI v1.6 by the way.)

This becomes an issue, for example, when you have a minimization problem with non-NaN metrics being always positive. After sorting in the ascending order, if you have many NaN cases, you'll have to scroll down a lot to see the best (minimal) metric. You will encounter the same issue even you sort in the descending order.

Since NaN is always undesirable, it would be nice if NaN is treated as positive infinity for minimization problems, while treated as negative infinity for maximization problems, for the WebUI sorting purpose only

**Comment by scarlett2018** [comment]
@Lijiaoa - this issue is fixed in #2776 and will be released in the Aug iteration, right? thanks.

**Comment by Lijiaoa** [comment]
@scarlett2018  @yhidaka PR #2776 is closed by some reasons. But this issue had been fixed in PR https://github.com/microsoft/nni/pull/2773, will be released in v1.8!
