### ISSUE TITLE
Multiple Experiments Management Design

### ISSUE THREAD

**Issue by yangou1988** [microsoft/nni#2779]
User could check and view the history of all experiments from Web UI.

Optimize the experience of Overview UI
- Redesign the sections of Experiment, Status and Top trials
- Show waiting trials in overview page. (v1.0 feedback) 
- Update duration and max trial numbers. 

Framework design
![image](https://user-images.githubusercontent.com/44491713/89851337-d6121580-dbbe-11ea-961f-4a1cb4735499.png)
![image](https://user-images.githubusercontent.com/44491713/89851358-e3c79b00-dbbe-11ea-814a-e87d53dc1ea7.png)
![image](https://user-images.githubusercontent.com/44491713/89851396-f8a42e80-dbbe-11ea-9a3b-5ca123576d70.png)

v0.1
![image](https://user-images.githubusercontent.com/44491713/89851591-6b150e80-dbbf-11ea-85c3-3e401632d82e.png)
![image](https://user-images.githubusercontent.com/44491713/89851605-7700d080-dbbf-11ea-92b1-630dba8b5835.png)

v0.2
![MicrosoftTeams-image (37)](https://user-images.githubusercontent.com/44491713/90224734-b5f28880-de42-11ea-9520-8eae7822a096.png)
![MicrosoftTeams-image (36)](https://user-images.githubusercontent.com/44491713/90224740-b7bc4c00-de42-11ea-9b23-d191a60a65f8.png)
![MicrosoftTeams-image (38)](https://user-images.githubusercontent.com/44491713/90224745-b9860f80-de42-11ea-8409-3ae4bcc4ff74.png)

**Comment by sharonxingyufan** [comment]
Web UI design update v0.3

Optimization regarding the last version
- Changed the placement of "Config" and "Search space" buttons in Overview page;
- Refined the Top trials section in Overview page;
- Refined the filter and tags sections in All experiments page.

v0.3
![overview-1](https://user-images.githubusercontent.com/69844841/91537473-f1b04680-e948-11ea-92b2-98386fd977b0.png)
![overview-2](https://user-images.githubusercontent.com/69844841/91537479-f412a080-e948-11ea-843d-d6d4d2257100.png)
![overview-3](https://user-images.githubusercontent.com/69844841/91537483-f543cd80-e948-11ea-87c6-11c79d5a10f0.png)
![All experiment – 2](https://user-images.githubusercontent.com/69844841/91537460-ea893880-e948-11ea-9aaf-6c5c5fb55341.png)

**Comment by sharonxingyufan** [comment]
Web UI design update v0.4

Optimization based on the need of responsive Web UI design.

1. Changed the proportion of each sections in the overview page;
2. Added the "Tensorboard" button in the trial details page as well as in the overview page;
2. Redesigned the interaction of "Config", "Search space", "Tensorboard", and "Log files" buttons in the overview page;

![1366px – 6](https://user-images.githubusercontent.com/69844841/95838342-f470ca80-0d41-11eb-838b-7ee1365543be.png)
![1366px – 7](https://user-images.githubusercontent.com/69844841/95838347-f5096100-0d41-11eb-8994-43856a3c53f1.png)
![1366px – 8](https://user-images.githubusercontent.com/69844841/95838349-f5a1f780-0d41-11eb-8617-a0e92a4490ad.png)
![1366px – 9](https://user-images.githubusercontent.com/69844841/95838351-f5a1f780-0d41-11eb-9897-f5ce121f647d.png)
![1366px – 10](https://user-images.githubusercontent.com/69844841/95838353-f63a8e00-0d41-11eb-9381-c69bfc26a382.png)

**Comment by xingyufan** [comment]
Web UI design update v0.5

Improved the user experience of viewing the chart and trial list.

![image](https://user-images.githubusercontent.com/64711762/99418129-f9a1d600-28fa-11eb-81be-3184be031e90.png)

**Comment by Lijiaoa** [comment]
This issue had been done on v2.0, so will close it.

**Comment by kvartet** [comment]
closing the issue as it has been finished.
