### ISSUE TITLE
Please, clarify enas micro result JSON meaning

### ISSUE THREAD

**Issue by mystous** [microsoft/nni#2798]
**Environment**:
- NNI version: 1.7
- NNI mode (local|remote|pai): local
- Client OS: Windows
- Server OS (for remote mode only):
- Python version: 3.7
- PyTorch/TensorFlow version: 1.5.0 / 2.X
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

I'd like to understanding the result of NNI ENAS macro and micro result.
I faced the problem with ENAS micro result
Below is the result of ENAS NNI macro result

{
  "normal_node_0_x_input": 0,
  "normal_node_0_x_op": 0,
  "normal_node_0_y_input": 1,
  "normal_node_0_y_op": 1,
  "normal_node_1_x_input": 1,
  "normal_node_1_x_op": 2,
  "normal_node_1_y_input": 2,
  "normal_node_1_y_op": 4,
  "normal_node_2_x_input": 0,
  "normal_node_2_x_op": 3,
  "normal_node_2_y_input": 0,
  "normal_node_2_y_op": 1,
  "normal_node_3_x_input": 0,
  "normal_node_3_x_op": 3,
  "normal_node_3_y_input": 1,
  "normal_node_3_y_op": 3,
  "normal_node_4_x_input": 0,
  "normal_node_4_x_op": 3,
  "normal_node_4_y_input": 1,
  "normal_node_4_y_op": 4,
  "reduce_node_0_x_input": 1,
  "reduce_node_0_x_op": 1,
  "reduce_node_0_y_input": 0,
  "reduce_node_0_y_op": 1,
  "reduce_node_1_x_input": 0,
  "reduce_node_1_x_op": 0,
  "reduce_node_1_y_input": 1,
  "reduce_node_1_y_op": 3,
  "reduce_node_2_x_input": 0,
  "reduce_node_2_x_op": 2,
  "reduce_node_2_y_input": 1,
  "reduce_node_2_y_op": 3,
  "reduce_node_3_x_input": 2,
  "reduce_node_3_x_op": 3,
  "reduce_node_3_y_input": 3,
  "reduce_node_3_y_op": 1,
  "reduce_node_4_x_input": 0,
  "reduce_node_4_x_op": 3,
  "reduce_node_4_y_input": 2,
  "reduce_node_4_y_op": 3
}

My question on "normal_node_0_x_input": 0, "normal_node_0_y_input": 1

I have no idea the index after 'x|y_input: ' Does it mean the node index on normal cell and reduction cell? If that, node_0_x_input: 0 -> is it fed by it self?

Anybody can clarify this result? There is no documentation for it.

**Comment by ultmaster** [comment]
Hi @mystous, thanks for asking. The index basically means which one (the index) in the list of input candidates is chosen here. You can view more details here: https://nni.readthedocs.io/en/latest/NAS/NasGuide.html#retrain-with-exported-architecture

We will soon post a update PR for this.
