### ISSUE TITLE
remote training service: the error is inaccurate

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2804]
**Environment**:
- NNI version: v1.8
- NNI mode (local|remote|pai): remote

I set a wrong sshKeyPath, but the error is `Missing key: 'passwd'`
![image](https://user-images.githubusercontent.com/23700012/90712636-10259a80-e2d6-11ea-9b71-dbbd855ee046.png)

**Comment by Lijiaoa** [comment]
fix in #1966
