### ISSUE TITLE
Issues speeding up pytorch MobileNet v2 model

### ISSUE THREAD

**Issue by radu-diaconescu13** [microsoft/nni#2807]
**Environment**:
- NNI version: 1.7.1
- NNI mode (local|remote|pai): local
- Client OS: ubuntu 16.04
- Python version: 3.6.2
- PyTorch/TensorFlow version: pytorch 1.5.1
- Is conda/virtualenv/venv used?: conda env
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:

**What issue meet, what's expected?**:
Hello. I am trying to prune and speed up a MobileNet v2 0.35 model which was obtained from tensorflow using mmdnn.
I have used the L1FilterPruner to obtain the weights mask successfully.
When I try to use ModelSpeedup I get the following error:

`  m_speedup.speedup_model()
File "/home/radud/anaconda3/envs/model-converter/lib/python3.6/site-packages/nni/compression/torch/speedup/compressor.py", line 184, in speedup_model
    self.infer_modules_masks()
  File "/home/radud/anaconda3/envs/model-converter/lib/python3.6/site-packages/nni/compression/torch/speedup/compressor.py", line 143, in infer_modules_masks
    self.infer_module_mask(module_name, None, mask=mask)
  File "/home/radud/anaconda3/envs/model-converter/lib/python3.6/site-packages/nni/compression/torch/speedup/compressor.py", line 135, in infer_module_mask
    self.infer_module_mask(_module_name, module_name, in_shape=output_cmask)
  File "/home/radud/anaconda3/envs/model-converter/lib/python3.6/site-packages/nni/compression/torch/speedup/compressor.py", line 135, in infer_module_mask
    self.infer_module_mask(_module_name, module_name, in_shape=output_cmask)
  File "/home/radud/anaconda3/envs/model-converter/lib/python3.6/site-packages/nni/compression/torch/speedup/compressor.py", line 106, in infer_module_mask
    .format(m_type, module_name))
RuntimeError: Has not supported infering output shape from input shape for module/function: aten::hardtanh, .aten::hardtanh.105 `
 
 It seems that the model uses hardtanh as a subtitute for Relu6
 Do you have any idea how I can work around this issue?
 Thank you

**Comment by radu-diaconescu13** [comment]
Hello @zheng-ningxin 
Thank you for the fix.

I have applied the code from the commit  to my local copy.
It fixes the issue with the hardtanh, but now i have a different unsupported op.

`Has not supported infering output shape from input shape for module/function: `aten::constant_pad_nd`, .aten::constant_pad_nd.106`

I tried fixing this in a similar manner to what you have done:

`'aten::constant_pad_nd': lambda module_masks, mask: relu_inshape(module_masks, mask),`

This way I have no more errors. However, when i compare the results from model speedup to results from apply_compression_results I get different outputs.
Do you have any idea how to fix the issue? Thank you :)

**Comment by zheng-ningxin** [comment]
Hi, @radu-diaconescu13 It's normal that the output of the speedup model is different from the pruned model. Basically, this difference is caused by the bias in the BN layers.  Please reference the [unit test]( https://github.com/microsoft/nni/blob/a8e77fe2d9a0410e1723287e2e414dd3b5f3d475/src/sdk/pynni/tests/test_model_speedup.py#L147) for more details. To check if the speedup module works fine, you can set all the bias in the BN layers to zero and compare the outputs of the pruned model and the speedup model. I suggest you that speedup the model directly after the pruning, then you can finetune the speedup model. This way, you can avoid the difference caused by bias in the BN layer

**Comment by radu-diaconescu13** [comment]
Hello @zheng-ningxin 
Thank you for your help!
