### ISSUE TITLE
NNI experiments all failed with two Errors

### ISSUE THREAD

**Issue by UTUnex** [microsoft/nni#2819]
**Environment**: 
- NNI version: 1.7.1
- NNI mode (local|remote|pai): local
- Client OS: windows 10 64 bit
- Server OS (for remote mode only):
- Python version: 3.8.5 64bit
- PyTorch/TensorFlow version: I didn't use pytorch ,it's a sklearn example
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: no

**What issue meet, what's expected?**: 
I downloaded the example from nni/examples/trials/sklearn/classification and want to reproduce it in my local computer.
I didn't change any code, yaml and json;
first I run the main.py without lunch nni experiment and no error and the output is like :
![image](https://user-images.githubusercontent.com/45436205/91109712-12904780-e67c-11ea-9f5c-4715ce63ee95.png)

Then, I lunched a nni experiment using nnictl create --config config.yml and the experiment successfully lunched but all experiments failed, I checked the log file in *.stderr and it showed 'python was not found ...', then I adjusted the yml file to:
![image](https://user-images.githubusercontent.com/45436205/91109824-6569ff00-e67c-11ea-9262-d3899a8b83c3.png)
Then I tried it again and another error showed:
![image](https://user-images.githubusercontent.com/45436205/91109887-98ac8e00-e67c-11ea-913c-47a23485b020.png)

I don't know what happened and I have to come here for help and guide.

**Additional information**:
![image](https://user-images.githubusercontent.com/45436205/91109952-c5f93c00-e67c-11ea-926a-58f0a6406415.png)
![image](https://user-images.githubusercontent.com/45436205/91109987-dc06fc80-e67c-11ea-97a1-1888d2ca2f04.png)

I'm sure the directory of the files are correct and I'm working under my virtual environment created by anaconda. The python was inner installed with anaconda and its directory is D:\Anaconda\anaconda\python.exe

I checked the other related issues and have uninstalled and reinsintalled the nni three times and repeat the procedure above three times but it just failed.

Please let me know what's wrong and how to make it work.

Thank you.

**Comment by UTUnex** [comment]
![image](https://user-images.githubusercontent.com/45436205/91110500-4ff5d480-e67e-11ea-8a6b-bf02189ec84e.png)
![image](https://user-images.githubusercontent.com/45436205/91110545-7287ed80-e67e-11ea-819e-f3c7a6764349.png)

**Comment by ultmaster** [comment]
You need to use the same python. Check which python you are using in `ml` environment. And use that python instead of `D:\Anaconda\anaconda\python`.

**Comment by UTUnex** [comment]
Sir, thank you for your reply. Now I made it run without fail after these steps:
(1) in the vscode terminal, conda activate myenvs
(2) change the yml--trial--command to python main.py: 
![image](https://user-images.githubusercontent.com/45436205/91275888-093cd300-e781-11ea-9051-a3d5cbcdcce0.png)

(3) Sir, you are correct, the python used here is the python.exe or python3.exe in the __virtual environment__  

Summary:
(1) activate the virtual environment 
(2) check the python in the virtuala environment 
(3) set the python in the yml file

Well, thank you again for you guide to a newbie :)
