### ISSUE TITLE
AttributeError: 'ModuleWrapper' object has no attribute 'net_if_addrs'

### ISSUE THREAD

**Issue by ZhongLi-Shi** [microsoft/nni#2824]
**Environment**:
- NNI version:
- NNI mode (local|remote|pai):
- Client OS:
- Server OS (for remote mode only): win10
- Python version: 3.7
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
AttributeError: 'ModuleWrapper' object has no attribute 'net_if_addrs'
and 
ValueError: only SIGTERM is supported on Windows

**How to reproduce it?**: 

**Additional information**:

**Comment by chicm-ms** [comment]
@ZhongLi-Shi Thanks for reporting this issue.

Would you please describe the detail steps how you get the error message,  such as what command did you run and the output of the command.

**Comment by ZhongLi-Shi** [comment]
I tried to run the example\sklearn\classification and changed the config.yml file
I have 3 file in the source, NNI_test.py, config.yml, and search_space.json
Then I run the 'nnictl create --config ./config.yml' and get the two error.
'
AttributeError: 'ModuleWrapper' object has no attribute 'net_if_addrs'
During handling of the above exception, another exception occurred:
ValueError: only SIGTERM is supported on Windows
'
The infomation said the experiment started.
'
INFO:  expand searchSpacePath: search_space.json to D:\project\dynamicGCN\code\search_space.json
INFO:  expand codeDir: . to D:\project\dynamicGCN\code\.
INFO:  Starting restful server...
INFO:  Successfully started Restful server!
INFO:  Setting local config...
INFO:  Successfully set local config!
INFO:  Starting experiment...
'
I'm new to this pakage and didn't found the similar error= =.

**Comment by chicm-ms** [comment]
Have you been able to run the example successfully if you do not make changes?
And would you please paste the files your are using?

**Comment by ZhongLi-Shi** [comment]
I run the example without changes.
nni/examples/trials/sklearn/classification/
I still get the same errors.

**Comment by chicm-ms** [comment]
Would you please paste the `nnimanager.log` and the output of `nnictl stderr` and `nnictl stdout`?

**Comment by ZhongLi-Shi** [comment]
First  'nnictl create --config ./config.yml',  then 'nnictl log stdout'
The info said no experiment.

INFO:  There is no experiment running...
ERROR: Please set correct experiment id.

I think maybe the experiment fail to start and therefore no log infomation? 
And this is the error message.

INFO:  expand searchSpacePath: search_space.json to D:\task\python\NNI_test\search_space.json
INFO:  expand codeDir: . to D:\task\python\NNI_test\.
INFO:  Starting restful server...
INFO:  Successfully started Restful server!
INFO:  Setting local config...
INFO:  Successfully set local config!
INFO:  Starting experiment...
Traceback (most recent call last):
  File "d:\tool\anaconda\envs\shienv\lib\site-packages\nni_cmd\launcher.py", line 539, in create_experiment
    launch_experiment(args, experiment_config, 'new', config_file_name)
  File "d:\tool\anaconda\envs\shienv\lib\site-packages\nni_cmd\launcher.py", line 502, in launch_experiment
    web_ui_url_list = get_local_urls(args.port)
  File "d:\tool\anaconda\envs\shienv\lib\site-packages\nni_cmd\url_utils.py", line 69, in get_local_urls
    for _, info in psutil.net_if_addrs().items():
AttributeError: 'ModuleWrapper' object has no attribute 'net_if_addrs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\tool\anaconda\envs\shienv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\tool\anaconda\envs\shienv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\tool\anaconda\envs\shiEnv\Scripts\nnictl.exe\__main__.py", line 7, in <module>
  File "d:\tool\anaconda\envs\shienv\lib\site-packages\nni_cmd\nnictl.py", line 234, in parse_args
    args.func(args)
  File "d:\tool\anaconda\envs\shienv\lib\site-packages\nni_cmd\launcher.py", line 544, in create_experiment
    kill_command(restServerPid)
  File "d:\tool\anaconda\envs\shienv\lib\site-packages\nni_cmd\command_utils.py", line 38, in kill_command
    process.send_signal(signal.CTRL_BREAK_EVENT)
  File "d:\tool\anaconda\envs\shienv\lib\site-packages\psutil\__init__.py", line 273, in wrapper
    return fun(self, *args, **kwargs)
  File "d:\tool\anaconda\envs\shienv\lib\site-packages\psutil\__init__.py", line 1014, in send_signal
    raise ValueError("only SIGTERM is supported on Windows")
ValueError: only SIGTERM is supported on Windows

**Comment by SparkSnail** [comment]
Hi @ZhongLi-Shi , NNI use `psutil.net_if_addrs()` function to get local net address, seems it does not work in your environment. Could you please check the version of your `psutil`? Have you ever tried upgrading the version of `psutil` and try again?

**Comment by ZhongLi-Shi** [comment]
@SparkSnail Hi, thx!  I upgrad psutil and solve this problem, but all the trials seem fail.
![image](https://user-images.githubusercontent.com/49721204/91792833-08a4b080-ec49-11ea-82ed-443d85bf58de.png)
and I run the stderr get '(node:15564) ExperimentalWarning: The fs.promises API is experimental'
would you please give me some advice?

**Comment by ZhongLi-Shi** [comment]
I found the answer from the other issue.
I change the config file, from "python3 main.py" to "python main.py"
I don't know why this word but it actually solve my problem!!

**Comment by SparkSnail** [comment]
> I found the answer from the other issue.
> I change the config file, from "python3 main.py" to "python main.py"
> I don't know why this word but it actually solve my problem!!

This is because your environment is windows, and windows use `python` command as default command, if you want to use `python3` in windows, you need to config it manually.

**Comment by ZhongLi-Shi** [comment]
Thanks for the details!
