### ISSUE TITLE
NAS搜索的模型是否可以转化成py文件？

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#2832]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**
目前搜索到的网络结构都是以json文件来保存的，这样有两个问题，一是搜索到的模型结构必须依赖NNI才能构建，二是如果一旦我们修改了搜索空间，之后就没法继续使用json文件。所以想问一下是否可以增加一个功能，就是把搜索到的模型结构解析成可以直接调用的py文件？

**Comment by ultmaster** [comment]
Sorry for late response.

May I ask what do you need for creating a new model without NNI. Is it used for deployment or do you want to run the model on other machines that do not have NNI installed?

In the first case, you can resort to tools like onnxruntime. I'm sure the model used for deployment is normally not a pure PyTorch model. In the second case, why can't this "other machine" install NNI as one of its dependency?

**Comment by marsggbo** [comment]
你好，我之所以有这样的诉求是因为我在实际使用过程中遇到了如下问题：

比如我写了一个net.py，第一次实验的时候我可能吧最后的全连接层的`bias`设置为了True，在search和retrain之后我保存了模型参数。

第二次实验的时候我可能又改了好几个地方的参数，比如我把`bias`设置成了False，还修改了其他几个地方。

做了若干次试验后，如果我想导入第一次试验模型参数的话基本上就不行了，因为我完全不记得第一次实验原始的py文件是什么了，所以就想问问能不能每次搜索完一个模型之后生成单独的py文件，而不是json文件，这样的话我们就可以以后想要使用就直接使用。

**Comment by ultmaster** [comment]
首先，完全 nni-free 是不大容易做到的。因为对于 inputChoice，他需要在候选的 tensor 中选若干个加起来，这肯定需要一个独立的 nn.Module 来做这个事情。目前这个 nn.Module 的名字就叫 InputChoice。

如果我没理解错的话，你的意思是说你想要对搜出来的 final architecture 进行一些手工的微调。我不是很理解为什么带 nni 的模型（apply_fixed_architecture 的模型）不能做类似的微调。但是，如果你是想要的是下面这种 code 的话，

```python
class Net(nn.Module):
  def __init__(self):
    self.choice1 = nn.Conv2d(...)  # 选好了

  def forward(self, x):
    tensor1 = self.choice1(x)
    # tensor2, tensor3, tensor4...
    return sum([tensor1, tensor3, tensor4])  # 选择若干个输入
```

在未来版本中我们会进行支持。可以预见的是这样生成的 code 可读性会更差，因为会破坏你原先 code 的 coding style（包括命名规范、注释、代码重用、空白符等等）。

**Comment by marsggbo** [comment]
可能是我没说清楚，我主要是以实验为主。每一次实验

**Comment by ultmaster** [comment]
你需要的是一个类似于版本控制的东西。你可以试试 git。

**Comment by kvartet** [comment]
> 可能是我没说清楚，我主要是以实验为主。每一次实验都会生成假设10个json文件，然后这个10个json文件都依赖于model.py。 下一次实验，我可能会修改model.py里的search space，然后又生成10个json文件。但是此时我再想使用第一次试验的json文件的话，就得还原回最初的model.py，可是一旦实验次数多了的话根本就记不住最开始的model.py是什么了。如果每次实验都生成一个新的model.py又感觉这样的方式有点笨，或者说有其他简单的方法吗？

@marsggbo Any updates? Thank you.
