### ISSUE TITLE
Is StackedLSTMCell correct implementation?

### ISSUE THREAD

**Issue by jyh2986** [microsoft/nni#2839]
For enas, StackedLSTMCell is implemented as below
 https://github.com/microsoft/nni/blob/bf8be1e705cdc0c153d6f38d1a83bd3fe55d7a1e/src/sdk/pynni/nni/nas/pytorch/enas/mutator.py#L23-L28

nn.LSTMCell outputs (hidden state, cell state) but the order of output is changed in the implementation.
As a result, the cell state is used for output of LSTM.

Is this an intention or wrong implementation?

**Comment by ultmaster** [comment]
Hi @jyh2986. Thanks for asking.

If you are right, the implementation is definitely buggy. You can raise a PR. Meanwhile, I'll check the PyTorch documentation for verification. Thanks.
