### ISSUE TITLE
Please add examples of using BOHB in sklearn: Thank you

### ISSUE THREAD

**Issue by UTUnex** [microsoft/nni#2840]
**What would you like to be added**:  Add examples of using BOHB in sklearn

**Why is this needed**: BOHB is a faster searching algorithm than TPE and I hope to use it in sklearn program

**Without this feature, how does current nni work**：it works with TPE but I have the expectations that BOHB can reduce the training time and get the result with similar or better score, especially with data of very large scale

**Components that may involve changes**:https://github.com/microsoft/nni/tree/master/examples/trials/sklearn

**Brief description of your proposal if any**:

**Comment by tabVersion** [comment]
This example will be added in the next release.

**Comment by UTUnex** [comment]
Thank you and I'll wait for that.

**Comment by tabVersion** [comment]
#2844  Please check whether this example meets your requirement.

**Comment by UTUnex** [comment]
Sir, I only found a configuration file *.yml and I didn't find the updated main.py.  Sorry but I hope you can update all of the yml, json and py files for BOHB in sklearn.

**Comment by tabVersion** [comment]
Actually BOHB is a tuning algorithm and it is used to find the best hyper-parameters in `main.py`.
You can use `nnictl create --config config_BOHB.yml` to start an experiment. Further details can be found [here](https://nni.readthedocs.io/en/latest/Tutorial/QuickStart.html).

**Comment by UTUnex** [comment]
Sir, thank you for your reply. First, I retried the sklearn-tpe version and it works fine . Then, without any change to the main.py and search_space.json, I just change the original yml file to the new config_BOHB.yml and tried but it failed and the information in the terminal is as follows:
![image](https://user-images.githubusercontent.com/45436205/91760178-2e8f6e00-ebd3-11ea-95ea-e25db9293afd.png)
I tried several times and nothing changed, it just showed this information ...
Please let me know what happened and what else I should set or change to make the BOHB run in sklearn.
Thank you.

**Comment by tabVersion** [comment]
Thanks for reporting the issue. Although getting the warning, please check port 8080 whether the experiment has started. It is expected to work well. 
The warning message is inaccurate and we are trying to refine it. #2847

**Comment by UTUnex** [comment]
Sir, I retried it again and yes the warning information showed again, but as you said,  when I opened the local:8080, I just found it's working. Well,  I still hope this inaccurate warning can be fixed because it's really misleading. Anyway, thank you for your guide:)

**Comment by kvartet** [comment]
closed as it had been added.
