### ISSUE TITLE
suggest_discrete_uniform?

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/nni#2843]
suggest_discrete_uniform

**Comment by QuanluZhang** [comment]
@Jie-Yuan could you give more description of your problem?

**Comment by Jie-Yuan** [comment]
离散值怎么表示，比如1 2 3 4 5等差数列

**Comment by QuanluZhang** [comment]
you can use `quniform`, detailed usage can be found [here](https://nni.readthedocs.io/en/latest/Tutorial/SearchSpaceSpec.html)

**Comment by scarlett2018** [comment]
> you can use `quniform`, detailed usage can be found [here](https://nni.readthedocs.io/en/latest/Tutorial/SearchSpaceSpec.html)

closing the issue as the answer had been provided. @Jie-Yuan - feel free to reopen if you still have questions around the answer.
