### ISSUE TITLE
(NAS/ENAS) Question about the functionality of MutableScope class, and the functionality of choose_from parameter of InputChoice class

### ISSUE THREAD

**Issue by TranSirius** [microsoft/nni#2845]
**Environment**:
- NNI version: 1.8
- NNI mode (local|remote|pai): local
- Client OS: Ubuntu 18.04.1 LTS
- Server OS (for remote mode only): N/A
- Python version: 3.7.7
- PyTorch/TensorFlow version: Pytorch 1.6.0
- Is conda/virtualenv/venv used?: Yes
- Is running in Docker?: No

**What issue meet, what's expected?**:
Hi, 
Thanks for providing NNI for the NAS community!

I find difficulty when creating the NAS search space. 
Specifically:

-  (In PyTorch) What's the difference between implementing a Neural Network Layer inheriting from torch.nn.module class and inheriting from nni.nas.pytorch.mutable.MutableScope? Or, What does `search space will be flattened as a list' means? Would the flattened search space make a difference between a hierarchical search space?
- (In PyTorch) What's the functionality of the parameter **choose_from** of nni.nas.pytorch.mutable.InputChoice.__init__()? Why does nni.nas.pytorch.mutatble.InputChoice.forward() still require a **optional_inputs** parameter? What's the connection between the two parameters?

Much appreciate it if you can provide any related information!

**Comment by ultmaster** [comment]
For the first question, the hierarchy is a hint for mutator that how layer choices and input choices are organized. Typically, this will be useful for mutators that relies on this information, for example, ENASMutator, that choose inputs accroding to their corresponding semantics. If you feel confused, it's very likely that you don't need them.

For the second question, `choose_from` is a semantic hint for mutator that allows mutator to know what they are choosing from. This is typically combined with the usage of MutableScope. Again, if you need no semantics in your mutator, you can ignore this and use `n_candidates`.

**Comment by TranSirius** [comment]
Hi,

Thanks for your clarification!

Does `semantics` mean that the input (to InputChoice) tensor is related to the operator (in `choose_from`) and `semantical` relation does not require the tensor to be the direct output of the operator (in `choose_from`)?

In this case, does this only make better readable codes with explicit annotations? There are no differences during runtime between using `n_candidates` and `choose_from`?

Much appreciate it if you can provide any related information!

**Comment by ultmaster** [comment]
Yes. You can think of it as an annotation of the inputs, as where the tensors come from cannot be directly inferred from the "tensors" themselves.

**Comment by TranSirius** [comment]
Thanks again for your valuable suggestion :)
