### ISSUE TITLE
# Intermediate result

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/nni#2846]
这里为空哇
![image](https://user-images.githubusercontent.com/20265321/91722441-d3f31380-ebcc-11ea-9421-58550eb36fb8.png)

**Comment by Lijiaoa** [comment]
@Jie-Yuan Sorry for late reply. Could you provide more information for debug?

**Comment by scarlett2018** [comment]
@Jie-Yuan - 方便发一下how to reproduce issue的steps嘛？谢谢

**Comment by kvartet** [comment]
> @Jie-Yuan - 方便发一下how to reproduce issue的steps嘛？谢谢

@Jie-Yuan Any updates? Thank you.

**Comment by kvartet** [comment]
I’m closing this issue as it has no updates from customer for 3 months, please feel free to reopen if you are still seeing it as an active issue.
