### ISSUE TITLE
[NAS, Customizing Searching Space] How to create a model searching space, where models are constructed by multiple identical cells?

### ISSUE THREAD

**Issue by Anifled** [microsoft/nni#2848]
Environment: Ubuntu 18.04, Python 3.7, PyTorch 1.6, Running Locally.

How to create a model searching space, in which sub-models are represented by multiple identical structures (or cells in some literature) of different parameters?

This kind of searching space is introduced by [ Learning Transferable Architectures for Scalable Image Recognition ]( https://openaccess.thecvf.com/content_cvpr_2018/papers/Zoph_Learning_Transferable_Architectures_CVPR_2018_paper.pdf ). This is also what [ENAS]( https://arxiv.org/pdf/1802.03268.pdf ) (Section 2.4. Designing Convolutional Cells ) does in its Micro CNN model.

**Comment by ultmaster** [comment]
By default, each `LayerChoice` and `InputChoice` are independent. That means, if `layer1` chooses `a`, `layer2` can choose anything.

What you want is basically to share choices among layers. This can be done by setting the same key to multiple layer/input choices. You can refer to NAS docs (https://nni.readthedocs.io/en/latest/NAS/NasReference.html#nni.nas.pytorch.mutables.Mutable) for more details.

**Comment by kvartet** [comment]
> What you want is basically to share choices among layers. This can be done by setting the same key to multiple layer/input choices. You can refer to NAS docs (https://nni.readthedocs.io/en/latest/NAS/NasReference.html#nni.nas.pytorch.mutables.Mutable) for more details.

@Anifled Any updates? Thank you.
