### ISSUE TITLE
Add various pruner algorithm for different pruning schedule

### ISSUE THREAD

**Issue by tu1258** [microsoft/nni#2853]
**What would you like to be added**: As title

**Why is this needed**: All pruning schedule except AGPPruner only support level, L1, L2. While there are FPGM, APoZ, MeanActivation and Taylor, it would be much better if we can choose any pruner with any pruning schedule.

**Without this feature, how does current nni work**：Still good.

**Components that may involve changes**: I am not so sure tho.

**Brief description of your proposal if any**: I look into source code of some pruning schedule and it's like 
```
if self.base_algo == 'level':
            schema = CompressorSchema([{
                'sparsity': And(float, lambda n: 0 < n < 1),
                Optional('op_types'): [str],
                Optional('op_names'): [str],
            }], model, _logger)
        elif self.base_algo in ['l1', 'l2']:
            schema = CompressorSchema([{
                'sparsity': And(float, lambda n: 0 < n < 1),
                'op_types': ['Conv2d'],
                Optional('op_names'): [str]
            }], model, _logger) 
```
Just add more types into it I guess?
Maybe you guys have tried others but met some bug or the loss exploded or anything.

**Comment by chicm-ms** [comment]
@tu1258 Thanks for reporting this issue.  Do you have some specific requirement about adding which pruner to which scheduler? Some pruners such as Apoz need to collect activation before using, and TaylorFO needs to collect gradients,  they may not fit every scheduler easily.  We need to handle this case by case if you have specific requirement.

**Comment by tu1258** [comment]
@chicm-ms Thanks for the reply. Honestly, I don't plan to use specific pruner or pruning schedule, and that's why I report this issue. I want to try different setting and see which is better. I think the more choice the better.

**Comment by chicm-ms** [comment]
@tu1258 FPGM can be added since it does not need to collect activation/gradient.

**Comment by kvartet** [comment]
closed as it has been merged.
