### ISSUE TITLE
从其他机器copy的experiment log无法resume

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/nni#2858]
本机的experiment log可以resume
从其他机器copy的experiment log无法resume

**Comment by Jie-Yuan** [comment]
![image](https://user-images.githubusercontent.com/20265321/92081226-56f6b280-edf5-11ea-8323-42456b6100f3.png)

**Comment by Jie-Yuan** [comment]
(base) ➜  horovod-distributed-example-1.0 git:(master) ✗ nnictl experiment load -p nni_experiment_mmTt074m.zip -c ./horovod-distributed-example-1.0

(base) ➜  horovod-distributed-example-1.0 git:(master) ✗ nnictl resume iEQ8sX5F            
INFO:  resume experiment iEQ8sX5F...
INFO:  Starting restful server...
ERROR: [Errno 2] No such file or directory: '/horovod-distributed-example-1.0/trainer/search_space.json'
(base) ➜  horovod-distributed-example-1.0 git:(master) ✗

**Comment by Jie-Yuan** [comment]
why???
![image](https://user-images.githubusercontent.com/20265321/92091418-506f3780-ee03-11ea-91d2-2d09591d062d.png)

**Comment by SparkSnail** [comment]
NNI does not support packing search_space right now, you need to put a search_space.json file in correct location in new machine.

**Comment by scarlett2018** [comment]
> NNI does not support packing search_space right now, you need to put a search_space.json file in correct location in new machine.

@Jie-Yuan 你试着自己把search_space.json copy过去后work了嘛？可否关掉issue，谢谢。
