### ISSUE TITLE
WARNING (nni) Requesting parameter without NNI framework, returning empty dict

### ISSUE THREAD

**Issue by pangsy0211** [microsoft/nni#2867]
**Environment**:
- NNI version:
- NNI mode (local|remote|pai):
- Client OS:CentOS Linux release 7.5.1804 (Core) 
- Server OS (for remote mode only):
- Python version:3.6.10
- PyTorch/TensorFlow version:1.12.0
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?:No

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**: when run "tuner_params = nni.get_next_parameter()", there is a warning "WARNING (nni) Requesting parameter without NNI framework, returning empty dict" and the params from search_space.json cannot be read successfully.

**How to reproduce it?**: 

**Additional information**: I have alread checked the format of search_space.json which is totally the same as which NNI defined.

**Comment by liuzhe-lz** [comment]
NNI hyper-parameter tuning is not a pure Python library, it must be launched with `nnictl`.
Please read [quick start guide](https://nni.readthedocs.io/en/latest/Tutorial/QuickStart.html) for detail.

**Comment by lorenelhuang** [comment]
I got the same problem. And I started the experiment from config file as suggested. But it didn't work.

**Comment by tarunpulluri** [comment]
Same issue

**Comment by leiqing110** [comment]
> NNI hyper-parameter tuning is not a pure Python library. You need to create a config file [(example)](https://github.com/microsoft/nni/blob/master/examples/trials/mnist-tfv1/config.yml) and launch it with `nnictl create --config config.yml`. Please read "step 3" part of [quick start guide](https://nni.readthedocs.io/en/latest/Tutorial/QuickStart.html) for details.

Hello This page can't be opened

**Comment by scarlett2018** [comment]
> > NNI hyper-parameter tuning is not a pure Python library. You need to create a config file [(example)](https://github.com/microsoft/nni/blob/master/examples/trials/mnist-tfv1/config.yml) and launch it with `nnictl create --config config.yml`. Please read "step 3" part of [quick start guide](https://nni.readthedocs.io/en/latest/Tutorial/QuickStart.html) for details.
> 
> Hello This page can't be opened

@J-shang is this fixed in the coming doc update? thanks.

**Comment by J-shang** [comment]
@scarlett2018 yes, there is a new hpo quickstart tutorial in doc refactor.
