### ISSUE TITLE
can not generate graph using TorchModuleGraph in pytorch 1.6

### ISSUE THREAD

**Issue by LovPe** [microsoft/nni#2879]
Hello Thanks for amazing project. I use nni to prune a model and then speedup.
when running TorchModuleGraph in pytorch 1.6, an error happend :
`AttributeError: module 'torch.onnx' has no attribute 'set_training'` in nni._graph_utils, I checked doc in pytorch, it seems `torch.onnx.set_training` has changed to `torch.onnx.select_model_mode_for_export`. 
After change it `torch.onnx.select_model_mode_for_export`, there still problems:
```
  File "/home/adas/anaconda3/envs/py36_ch/lib/python3.6/site-packages/nni/_graph_utils.py", line 247, in __init__
    self.name_to_node, self.input_to_node, self.output_to_node = self._build_graph()
  File "/home/adas/anaconda3/envs/py36_ch/lib/python3.6/site-packages/nni/_graph_utils.py", line 689, in _build_graph
    return self._build_index(self.nodes_py.nodes_op)
  File "/home/adas/anaconda3/envs/py36_ch/lib/python3.6/site-packages/nni/_graph_utils.py", line 517, in _build_index
    "One output cannot be generated by multiple nodes"
AssertionError: One output cannot be generated by multiple nodes
```
I write a test code like this:
```
from torch import nn
import torch
from nni._graph_utils import TorchModuleGraph


class CBR(nn.Module):
    def __init__(self, i, o):
        super(CBR, self).__init__()
        self.conv1 = nn.Conv2d(i, o, kernel_size=1)
        self.bn1 = nn.BatchNorm2d(o)
        self.act1 = nn.ReLU()

    def forward(self, x):
        return self.act1(self.bn1(self.conv1(x)))


class A(nn.Module):
    def __init__(self):
        super(A, self).__init__()
        self.conv1 = CBR(3, 6, )
        self.conv2 = CBR(6, 8, )
        self.conv3 = CBR(6, 12)

    def forward(self, x):
        x1 = self.conv1(x)
        x2 = self.conv2(x1)
        x3 = self.conv3(x1)
        return [x2, x3]


class B1(nn.Module):
    def __init__(self):
        super(B1, self).__init__()
        self.conv1 = CBR(12, 32)
        self.conv2 = CBR(32, 32)
        self.conv3 = CBR(32, 32)

    def forward(self, x):
        ret = list()
        x = self.conv1(x)
        ret.append(x)
        x = self.conv2(x)
        ret.append(x)
        x = self.conv3(x)
        ret.append(x)
        return ret


class B(nn.Module):
    def __init__(self):
        super(B, self).__init__()
        self.b = B1()

    def forward(self, x):
        return self.b(x[-1])


class C(nn.Module):
    def __init__(self):
        super(C, self).__init__()
        self.conv1_1 = CBR(8, 32)
        self.conv1_2 = CBR(8, 32)
        self.conv2_1 = CBR(12, 32)
        self.conv2_2 = CBR(12, 32)
        self.conv3_1 = CBR(32, 32)
        self.conv3_2 = CBR(32, 32)
        self.conv4_1 = CBR(32, 32)
        self.conv4_2 = CBR(32, 32)
        self.conv5_1 = CBR(32, 32)
        self.conv5_2 = CBR(32, 32)

    def forward(self, x):
        out_a = list()
        out_b = list()
        out_a.append(self.conv1_1(x[0]))
        out_a.append(self.conv2_1(x[1]))
        out_a.append(self.conv3_1(x[2]))
        out_a.append(self.conv4_1(x[3]))
        out_a.append(self.conv5_1(x[4]))
        out_b.append(self.conv1_2(x[0]))
        out_b.append(self.conv2_2(x[1]))
        out_b.append(self.conv3_2(x[2]))
        out_b.append(self.conv4_2(x[3]))
        out_b.append(self.conv5_2(x[4]))
        return out_a, out_b


class TestMod(nn.Module):
    def __init__(self):
        super(TestMod, self).__init__()
        self.a = A()
        self.b = B()
        self.c = C()

    def forward(self, x):
        x_a = self.a(x)
        x_b = self.b(x_a)
        x_a.extend(x_b)
        xc = self.c(x_a)
        return xc


if __name__ == "__main__":
    # from experiment.vis_nni_graph import visualize
    dummy_input = torch.randn([1, 3, 28, 28])
    m_test = TestMod()
    graph = TorchModuleGraph(m_test, dummy_input)
    # for ii in graph.name_to_node:
    #     print("node {}, successor: {}".format(ii, graph.find_successors(ii)))
    # visualize(graph, "./test_before")
    print("=" * 100)
    # graph.unpack_manually()
    # for ii in graph.name_to_node:
    #     print("node {}, successor: {}".format(ii, graph.find_successors(ii)))
    # visualize(graph, "./test_after")
```
I wonder if pytorch 1.6 is supported.
My envs:
----------------------  --------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42) [GCC 7.5.0]
numpy                   1.19.1
detectron2              0.2.1 @/home/adas/remote/detectron2/detectron2
Compiler                GCC 5.4
CUDA compiler           CUDA 10.2
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0 @/home/adas/anaconda3/envs/py36_ch/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3             GeForce RTX 2080 (arch=7.5)
CUDA_HOME               /usr/local/cuda-10.2
Pillow                  7.2.0
torchvision             0.7.0 @/home/adas/anaconda3/envs/py36_ch/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.1.post20200716
cv2                     4.4.0
nni                     1.8
----------------------  --------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by chicm-ms** [comment]
@LovPe Thanks for reporting this issue.
We have not tested pruners with pytorch 1.6 yet.  We will investigate it.

**Comment by kvartet** [comment]
closed as it had been merged.
