### ISSUE TITLE
[Feature request] Create experiment manually

### ISSUE THREAD

**Issue by HudsonHuang** [microsoft/nni#2892]
**What would you like to be added**:
A feature of create experiment manually. 

**Why is this needed**:
Use case 1: When I start a research, I always have some initial hyperparameter sets that already works well, adding these initial experiments help me to compare with other experiments start by NNI.
Use case 2: When running NNI, I would like to adding new experiments as I wish, while keep the batch running and grid search running.

**Without this feature, how does current nni work**：
I have to use an old version of NNI which does have this feature.

**Components that may involve changes**:
Web interface, python API(maybe)

**Brief description of your proposal if any**:
For example adding a button on the web interface, clicking the button will show a text box, we could paste json format hyperparameter sets, one or many, to it. And NNI should giving priority to these manual experiemnts. 
If adding manual experiment doesn't support by advanced tunning Algos like TPE and hyperopt, we could seperate manual experiments with experiments start by tunning Algos, just run manual experiments as referrance without affecting tunning Algos, or even only support batch running and grid search.

**Comment by QuanluZhang** [comment]
@HudsonHuang thanks for proposing new feature and a possible solution. Does customized trial below solves your problem? you can modify the value of the hyper-parameters.

![image](https://user-images.githubusercontent.com/16907603/93045600-22eb7f00-f68a-11ea-9987-b127fdefb7bb.png)

For "experiment", you mean a trial or an NNI experiment? In NNI, an experiment includes many trials, each trial is one hyper-parameter configuration. You want to import several well-performed trials into an experiment, or you want to compare two NNI experiments?

We have designed experiments management page in issue #2779 . Please check whether it fits in your scenario. The comparison of two experiments on WebUI has not been designed yet.

**Comment by HudsonHuang** [comment]
Thank you, it works fine.

**Comment by g1910** [comment]
Hi @QuanluZhang,  is it possible to submit a customized trial programmatically?

**Comment by QuanluZhang** [comment]
@g1910 good suggestion. We are working on NNI python APIs for creating and managing NNI experiments programmatically. we will support submitting customized trials in it.

For your information, the following are NNI python APIs related doc and prs
https://nni.readthedocs.io/en/stable/Tutorial/HowToLaunchFromPython.html
pr https://github.com/microsoft/nni/pull/3334
