### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nnictl'

### ISSUE THREAD

**Issue by yangboye** [microsoft/nni#2893]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**
使用PyCharm运行写在`.py`文件中的`nnictl.start_experiment()`报错：`FileNotFoundError: [Errno 2] No such file or directory: 'nnictl'`

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version: 1.8
- nni mode(local|pai|remote): local
- OS: Ubuntu 18.04
- python version: 3.8
- is conda or virtualenv used?: yes
- is running in docker?: no

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**
No

**其他分享内容 :**
**Anything else we need to know :**
看到`nni v1.8`更新了`nictl`的API很开心就试了试，我是按照[
Python wrapper for nni restful APIs](https://github.com/microsoft/nni/blob/v1.8/examples/notebooks/retrieve_nni_info_with_python.ipynb)中的示例来的，不过是用PyCharm远程连接服务器运行的，以下是我的代码：
```python
import nni
from nnicli import Experiment
import json

def show_json(res):
    print(json.dumps(res, indent=4))


if __name__ == '__main__':
    print(nni.__version__)

    exp = Experiment()
    exp.start_experiment("/xxx/remote_src/NNI-Test/test/config.yml", port=9090)

    exp.update_concurrency(3)
    show_json(exp.get_experiment_status())
    show_json(exp.get_experiment_profile())
    show_json(exp.list_trial_jobs())
```
在PyCharm中运行后报如下错误：
```
Traceback (most recent call last):
  File "/xxx/remote_src/NNI-Test/test/main.py", line 15, in <module>
    exp.start_experiment("/xxx/remote_src/NNI-Test/test/config.yml", port=9090)
  File "/disks/disk1/damon/anaconda3/envs/pytorch/lib/python3.8/site-packages/nnicli/nni_client.py", line 286, in start_experiment
    self._exec_command(cmd, port)
  File "/disks/disk1/damon/anaconda3/envs/pytorch/lib/python3.8/site-packages/nnicli/nni_client.py", line 258, in _exec_command
    if _create_process(cmd) != 0:
  File "/disks/disk1/damon/anaconda3/envs/pytorch/lib/python3.8/site-packages/nnicli/nni_client.py", line 67, in _create_process
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/disks/disk1/damon/anaconda3/envs/pytorch/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/disks/disk1/damon/anaconda3/envs/pytorch/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nnictl'
```
我尝试定位到错误的地方，发现在`nni_client.py`中执行`cmd = 'nnictl create --config {}`等命令时是通过`subprocess.Popen(cmd, stdout=subprocess.PIPE)`来执行的，这好像会使用默认的anaconda环境，所以我又做实验验证了一下，验证代码如下：

print_env.py
```python
import sys
print(sys.path)
```
main.py
```python
if __name__ == '__main__':
    print(nni.__version__)
    import subprocess

    process = subprocess.Popen(['python', 'print_env.py'], stdout=subprocess.PIPE)

    while process.poll() is None:
        output = process.stdout.readline()
        if output:
            print(output.decode('utf-8').strip())
```
运行后输出的结果如下：
```
1.8
['/xxx/remote_src/NNI-Test/test', '/xxx/remote_src/NNI-Test', '/home/damon/.pycharm_helpers/pycharm_display', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/damon/.pycharm_helpers/pycharm_matplotlib_backend']

```
这个问题在用Ubuntu命令行时不会报错，而在PyCharm中出错，所以我猜测应该是`nni_client.py`中使用`subprocess.Popen(cmd, stdout=subprocess.PIPE)`的问题。
**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by JunweiSUN** [comment]
@yangboye 你好，请先确定你在pycharm里面是否用了virtualvenv（pycharm默认给新项目新建一个virtualvenv环境），即你在pycharm运行和在命令行中运行是否用的是同一个python；如果是同一个，则你可能需要在pycharm里面把nnictl的命令所在的位置添加到PATH这个环境变量中；如果不是同一个，可以设置成同一个，或者在virtualvenv的环境中装NNI。

**Comment by yangboye** [comment]
@JunweiSUN 你好，我的PyCharm已经设置了服务器中名字为`pytorch`的环境，也按照您的建议在pycharm中加上了`nnictl`的位置到PATH中（在Environment variables中添加`PATH=/disks/disk1/damon/anaconda3/envs/pytorch/bin/nnictl`）。我注意到您在`nni_client.py`中生成`nnictl`命令的代码是`cmd = 'nnictl create --config {}'.format(config_file).split(' ')`，所以我照此写了一个类似的测试代码，功能是打印nni的版本号:
```python
if __name__ == '__main__':
    import subprocess

    process = subprocess.Popen(['nnictl', '--version'], stdout=subprocess.PIPE)

    while process.poll() is None:
        output = process.stdout.readline()
        if output:
            print(output.decode('utf-8').strip())
```
编译器还是会报错：
```
Traceback (most recent call last):
  File "/disks/disk1/damon/remote_src/YPlatformServer/test/main.py", line 17, in <module>
    process = subprocess.Popen(['nnictl', '--version'], stdout=subprocess.PIPE)
  File "/disks/disk1/damon/anaconda3/envs/pytorch/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/disks/disk1/damon/anaconda3/envs/pytorch/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nnictl'
```
上述代码在服务器命令行切换到`pytroch`环境是没有问题的。而如果改为`process = subprocess.Popen(['/disks/disk1/damon/anaconda3/envs/pytorch/bin/nnictl', '--version'], stdout=subprocess.PIPE)`，那么在PyCharm中也可以运行。
