### ISSUE TITLE
Suggest to get rid of netifaces dependency

### ISSUE THREAD

**Issue by liuzhe-lz** [microsoft/nni#2895]
`netifaces` is hard to build on Windows. It does not provide wheel for latest Python.
This package is used to get IP address of `eth0`, which should be simply done by `hostname -i`. `eth0` is not preferred by systemd comparing to "predictable" interface name.
Of course `hostname` is not supported by Windows, but I believe `eth0` will not work either.

I think we should be conservative to introduce binary/native dependencies. They will cause installation problem sooner or later.

**Comment by J-shang** [comment]
This does cause some trouble. It ask me to install `visual c++ build tools 2016` with 3GB to install `netifaces`, when I want to install nni on my laptop with clean dev env.
