### ISSUE TITLE
ModelSpeedUp support for aten::mul?

### ISSUE THREAD

**Issue by guojunyao419** [microsoft/nni#2901]
When I ran ModelSpeedup on a model which uses an operator "*" in the model definition, I ran into the following error:
`RuntimeError: Has not supported infering output shape from input shape for module/function: aten::mul, conv2.0.gate.aten::mul.418`

My question is:
1. Will aten::mul be supported by ModelSpeedup anytime soon?
2. How much effort it requires to write custom function to infer input/output shape associated with aten:mul? If I want to implement it by myself, where should I start?

Thanks in advance!

**Comment by zheng-ningxin** [comment]
Hi~ thanks for the feedback! Could you please give us the code snippet (looks like it's in the conv2) that has the `aten::mul` so that I can add the support for `aten::mul` and test on it?

**Comment by guojunyao419** [comment]
Thanks @zheng-ningxin for your prompt feedback. I am using the OSNet model implemented in the[ torchreid](https://github.com/KaiyangZhou/deep-person-reid) package. Here is the code snippet for speed-up. To run the following snippet, you need to install the torchreid package.

    import torchreid
    
    n_classes = 751 

    device = torch.device("cuda:0")

    model = torchreid.models.build_model(
        name='osnet_x1_0',
        num_classes=n_classes,
        loss='softmax',
        pretrained=True
    )

    model.load_state_dict(torch.load('pruned_AGP_l1.pth'))
    model = model.to(device)

    dummy_input = torch.randn([1,3,256,128]).to(device)
    dummy_input = dummy_input.to(device)
    
    masks_file = 'mask_AGP_l1.pth'
    m_speedup = ModelSpeedup(model, dummy_input.to(device), masks_file)
    m_speedup.speedup_model()


I have attached the OSNet model definition file from torchreid, pruned_AGP_l1.pth, and mask_AGP_l1.pth. The aten::mul operator seems to result from the `ChannelGate` class in osnet.py. In the `ChannelGate.forward` function, there is an operation` input * x`used.

[osnet.zip](https://github.com/microsoft/nni/files/5241895/osnet.zip)

**Comment by guojunyao419** [comment]
Thank you for adding the suppor for aten::mul. I tried the newly added feature, and it seems that the ModelSpeedup function does not report any error on my previously attached example. However, when I tested the model after speed up (model_speed_up) on a test dataset, the latency even increases a bit compared to the model without speedup (which is the pruned_AGP_l1.pth in the previous attachment). Also, the accuracy of the model_speed_up drops a lot compared to pruned_AGP_l1.pth. It seems that the zero filters are now removed correctly by ModelSpeedup. Could you take a further look into the added support for aten:mul? Thanks.

**Comment by zheng-ningxin** [comment]
@guojunyao419 Hi~ I also found this problem when testing with the example you gave. First of all, there is no acceleration effect because the dependence between the channels of the submodules is very heavy. As for why the channel dependency will reduce the acceleration effect of the model, you can refer to [ChannelDependency tools](https://nni.readthedocs.io/en/latest/Compressor/CompressionUtils.html#channeldependency) for more details.

Basically, you can try to enable the [dependency-aware mode](https://nni.readthedocs.io/en/latest/Compressor/DependencyAware.html) for the pruners you used(only Filter Pruner supported), or you can align the pruned channel manually in the pruning algo for the channel-dependent layers(you can get the layers that have channel dependencies at [ChannelDependency tools](https://nni.readthedocs.io/en/latest/Compressor/CompressionUtils.html#channeldependency) )

FYI: I also visualize your model:
![2901](https://user-images.githubusercontent.com/49771382/94503415-024e2800-0239-11eb-850c-af0f46adf82e.jpg)

**Comment by LuckGuySam** [comment]
I have the same problem, but is the Mish activate function! I use the easy model with mish ,then speedup will have error `RuntimeError: Has not supported infering output shape from input shape for module/function: `Mish`, Mish`
my model is this
`class Mish(nn.Module): 
    def forward(self, x):
        return x * F.softplus(x).tanh()
        
class NaiveModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.bn1 = nn.BatchNorm2d(self.conv1.out_channels)
        self.bn2 = nn.BatchNorm2d(self.conv2.out_channels)
        self.fc1 = nn.Linear(4 * 4 * 50, 500)
        self.fc2 = nn.Linear(500, 10)
        
        self.Mish = Mish()

    def forward(self, x):
        x = self.Mish(self.bn1(self.conv1(x)))
        x = F.max_pool2d(x, 2, 2)
        x = self.Mish(self.bn2(self.conv2(x)))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(x.size(0), -1)
        x = self.Mish(self.fc1(x))
        x = self.fc2(x)
        return x`

can you tell me if i want to do this , how can i do?

**Comment by LuckGuySam** [comment]
I have the same problem, but is the Mish activate function! I use the easy model with mish ,then speedup will have error 
`RuntimeError: Has not supported infering output shape from input shape for module/function: Mish, Mish`
my model is this
`
class Mish(nn.Module):
def forward(self, x):
return x * F.softplus(x).tanh()

class NaiveModel(torch.nn.Module):
def init(self):
super().init()
self.conv1 = nn.Conv2d(1, 20, 5, 1)
self.conv2 = nn.Conv2d(20, 50, 5, 1)
self.bn1 = nn.BatchNorm2d(self.conv1.out_channels)
self.bn2 = nn.BatchNorm2d(self.conv2.out_channels)
self.fc1 = nn.Linear(4 * 4 * 50, 500)
self.fc2 = nn.Linear(500, 10)

    self.Mish = Mish()

def forward(self, x):
    x = self.Mish(self.bn1(self.conv1(x)))
    x = F.max_pool2d(x, 2, 2)
    x = self.Mish(self.bn2(self.conv2(x)))
    x = F.max_pool2d(x, 2, 2)
    x = x.view(x.size(0), -1)
    x = self.Mish(self.fc1(x))
    x = self.fc2(x)
    return x
`
can you tell me if i want to do this ,how can i do

**Comment by scarlett2018** [comment]
> @guojunyao419 Hi~ I also found this problem when testing with the example you gave. First of all, there is no acceleration effect because the dependence between the channels of the submodules is very heavy. As for why the channel dependency will reduce the acceleration effect of the model, you can refer to [ChannelDependency tools](https://nni.readthedocs.io/en/latest/Compressor/CompressionUtils.html#channeldependency) for more details.
> 
> Basically, you can try to enable the [dependency-aware mode](https://nni.readthedocs.io/en/latest/Compressor/DependencyAware.html) for the pruners you used(only Filter Pruner supported), or you can align the pruned channel manually in the pruning algo for the channel-dependent layers(you can get the layers that have channel dependencies at [ChannelDependency tools](https://nni.readthedocs.io/en/latest/Compressor/CompressionUtils.html#channeldependency) )
> 
> FYI: I also visualize your model: ![2901](https://user-images.githubusercontent.com/49771382/94503415-024e2800-0239-11eb-850c-af0f46adf82e.jpg)

close the issue as the answer had been provided.
