### ISSUE TITLE
Could you please add an example for Colab because I would like it to work eventually with GPUs and TPUs?

### ISSUE THREAD

**Issue by shyamalschandra** [microsoft/nni#2910]
**What would you like to be added**:

Colab example demonstrating nni.

**Why is this needed**:

Because it is easier than downloading the code and running it on CPU.

**Without this feature, how does current nni work**：

No problem, I just need to use CPU or GPU but I also want to use TPU.

**Components that may involve changes**:

Add support for TPU with an example in Colab.

**Brief description of your proposal if any**:

Colab example with TPU version.

**Comment by dssc-codebase** [comment]
Dear @shyamalschandra , we do have an example about how to use NNI on Colab, please refer to this [documentation](https://nni.readthedocs.io/en/latest/CommunitySharings/NNI_colab_support.html). Using NNI on Colab is basically the same as using NNI on your own machine. Currently we only support CPU and GPU.

**Comment by JunweiSUN** [comment]
Dear @shyamalschandra , we do have an example about how to use NNI on Colab, please refer to this documentation. Using NNI on Colab is basically the same as using NNI on your own machine. Currently we only support CPU and GPU.

**Comment by shyamalschandra** [comment]
Thank you for your response!

**Comment by scarlett2018** [comment]
closing the issue as the ask had been solved.

**Comment by whubaichuan** [comment]
@JunweiSUN hi, this link is invalid now.

**Comment by JunweiSUN** [comment]
> @JunweiSUN hi, this link is invalid now.

Updated the doc link inline. Pls try again~
