### ISSUE TITLE
is there a elegant way to register training service ?

### ISSUE THREAD

**Issue by maxxx580** [microsoft/nni#2928]
**Environment**:
- NNI version: 1.8
- NNI mode (local|remote|pai): custom training service
- Client OS: macos
- Server OS (for remote mode only): linux
- Python version: 3.7
- PyTorch/TensorFlow version: pytorch-1.6
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: N/A
 - dispatcher.log: N/A
 - nnictl stdout and stderr: N/A
 

**What issue meet, what's expected?**:
question: as i built a custom training service from my infra, is there an elegant way to register this service without having to download and modify the source code itself ? the way to extend training service [here](https://nni.readthedocs.io/en/latest/TrainingService/HowToImplementTrainingService.html) doesn't scale well within an organization. thanks advance for your response. 
**How to reproduce it?**: 
N/A
**Additional information**:
N/A

**Comment by SparkSnail** [comment]
This feature seems reasonable, we will discuss feasibility of this feature.

**Comment by maxxx580** [comment]
I saw the PR, and it looks great. I look forward to v2.3.

**Comment by liuzhe-lz** [comment]
https://github.com/liuzhe-lz/nni-training-service-template
This is a naive example for 3rd-party training service. It's considered an early preview since the APIs and toolchain are not formalized yet.
