### ISSUE TITLE
New Overview Table & Chart UI Improvement 

### ISSUE THREAD

**Issue by yangou1988** [microsoft/nni#2937]
Can't display complete Trial metric chart in low-resolution environment as below:
![MicrosoftTeams-image (73)](https://user-images.githubusercontent.com/44491713/95700766-67af0980-0c7a-11eb-8632-bae4f6d9c39f.png)

New design
Combine chart and table together on the right side.
![MicrosoftTeams-image (72)](https://user-images.githubusercontent.com/44491713/95701449-333c4d00-0c7c-11eb-9cac-379ab876b209.png)

**Comment by sharonxingyufan** [comment]
New design
1. Optimization of the section alignment:
![image](https://user-images.githubusercontent.com/69844841/99524875-5d7adc00-2999-11eb-8265-2c19bd10e922.png)

2. Direct to the trial in the table when pressing the dot in the chart
3. Optimization of the information layout in the tooltip
![image](https://user-images.githubusercontent.com/69844841/99524997-87cc9980-2999-11eb-9fe2-a3289481a816.png)

**Comment by Lijiaoa** [comment]
@kvartet This issue had been done on v2.x, could you help close this issue?
