### ISSUE TITLE
[webui enhancement] about the tooltip content for default metric chart

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/nni#2964]
**What would you like to be added**:
show more infomation on webui default metric chart, like chart, add trial id message. And on overview page, the default metric chart show less message when hover to the point, It's not friendly.
![image](https://user-images.githubusercontent.com/61399850/96207033-c9ce7e00-0f9c-11eb-877e-0c13278182fb.png)
![image](https://user-images.githubusercontent.com/61399850/96207195-35b0e680-0f9d-11eb-8e76-e2de98889b3c.png)

**Why is this needed**: 信息一致，更加友好

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by kvartet** [comment]
closed as it has been merged.
