### ISSUE TITLE
Typo in Overview.md

### ISSUE THREAD

**Issue by DanielMcSheehy** [microsoft/nni#2970]
**What would you like to be added**:
`The following step could help us to better integrate with sklearn, which means we could treat the customized feature selector as a mudule of the pipeline.`
should be 
`The following step could help us to better integrate with sklearn, which means we could treat the customized feature selector as a module of the pipeline.`
**Why is this needed**:
the typo made me wonder if mudule was a word that I did not know. it confused me.
**Without this feature, how does current nni work**：
it works fine. 
**Components that may involve changes**:
Docs
**Brief description of your proposal if any**:

**Comment by QuanluZhang** [comment]
thanks @DanielMcSheehy  and @AnshuTrivedi for the fix.
