### ISSUE TITLE
运行auto-gbdt的时候，按照代码提供的search_space和config设置，所有的trial状态都是failed

### ISSUE THREAD

**Issue by LianShuaiLong** [microsoft/nni#2984]
**Environment**:
- NNI version:1.8
- NNI mode (local|remote|pai):pai
- Client OS:ubuntu 18.04
- Server OS (for remote mode only):
- Python version:3.6.6
- PyTorch/TensorFlow version:tensorflow 1.13.3-gpu
- Is conda/virtualenv/venv used?:No
- Is running in Docker?:Yes

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

-------------------------------------------------------------------------------------
Id: GlnIsMF0    Status: DONE    Port: 8080    Platform: local
StartTime: 2020/10/19 17:36:40    Duration: 0d 0h 1m 45s
-------------------------------------------------------------------------------------
trialId         startTime                 endTime                   status
-------------------------------------------------------------------------------------
wKP0b           2020/10/19 17:36:45       2020/10/19 17:36:50       FAILED
ioAVb           2020/10/19 17:37:00       2020/10/19 17:37:00       FAILED
jSHf1           2020/10/19 17:37:10       2020/10/19 17:37:10       FAILED
BdD8o           2020/10/19 17:37:20       2020/10/19 17:37:20       FAILED
xtPC3           2020/10/19 17:37:30       2020/10/19 17:37:30       FAILED
jGT7l           2020/10/19 17:37:40       2020/10/19 17:37:40       FAILED
HjAgB           2020/10/19 17:37:50       2020/10/19 17:37:50       FAILED
wZ26z           2020/10/19 17:38:00       2020/10/19 17:38:00       FAILED
g78ag           2020/10/19 17:38:10       2020/10/19 17:38:10       FAILED
g9Hsx           2020/10/19 17:38:20       2020/10/19 17:38:20       FAILED
-------------------------------------------------------------------------------------

**Comment by SparkSnail** [comment]
@LianShuaiLong, do you have nniManager.log and trialkeeper_stdout.log info?

**Comment by LianShuaiLong** [comment]
> @LianShuaiLong, do you have nniManager.log and trialkeeper_stdout.log info?

 i have fixed this "bug" ， i forgot to install lightgbm in my docker
