### ISSUE TITLE
如何利用auto-gbdt训练完的结果进行预测？

### ISSUE THREAD

**Issue by LianShuaiLong** [microsoft/nni#2990]
**Environment**:
- NNI version:
- NNI mode (local|remote|pai):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by xuehui1991** [comment]
Hello @LianShuaiLong , thanks for your question.

There are two ways that you could find the best model and use it to predict:

1) you could check the best parameters in WebUI, and use those parameters to retrain your model in the same training set.
2) you could dump the all the models  with every parameters to json. And check the best model id in WebUI and reload the json file to predict.  For how to dump the model, you could reference this [link](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.dump.html)  

Thank you.

**Comment by LianShuaiLong** [comment]
> Hello @LianShuaiLong , thanks for your question.
> 
> There are two ways that you could find the best model and use it to predict:
> 
> 1. you could check the best parameters in WebUI, and use those parameters to retrain your model in the same training set.
> 2. you could dump the all the models  with every parameters to json. And check the best model id in WebUI and reload the json file to predict.  For how to dump the model, you could reference this [link](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.dump.html)
> 
> Thank you.

thanks for your reply
