### ISSUE TITLE
Refine search by paramters

### ISSUE THREAD

**Issue by Sundrops** [microsoft/nni#3024]
**Environment**:
- NNI version: <=1.8

**What issue meet, what's expected?**:
It's very inconvenient to input complex and ordered  json string when we want to search by paramters like this:  
`{\"block0_channel\":1,\"block1_channel\":1.1,\"block2_channel\":0.9}`
And we can't search trials only match `{\"block0_channel\":1,\"block2_channel\":0.9}` without `block1_channel`

![微信截图_20201024173122](https://user-images.githubusercontent.com/14829222/97078443-ef9ff680-161e-11eb-8600-0d9ce1c73fde.png)

Looking forward to your improvement.

**Comment by liuzhe-lz** [comment]
Thanks for your suggestion. This is a useful feature.
We will implement it future version.

**Comment by Lijiaoa** [comment]
Hi, @Sundrops . According to your feedback we had designed it on issue #3099. The proposal is latest comment [img](https://user-images.githubusercontent.com/69844841/102287626-23224180-3f3b-11eb-94bf-f83ceb588f88.png), [img2](https://user-images.githubusercontent.com/69844841/102288318-895b9400-3f3c-11eb-913e-3aba0ca6979e.png), [img3](https://user-images.githubusercontent.com/69844841/102288346-924c6580-3f3c-11eb-802e-724831152216.png).

**Comment by Sundrops** [comment]
@Lijiaoa Thanks for your great work.

**Comment by kvartet** [comment]
hello @Sundrops, this feature had been supported in NNI v2.3, so I will close this pr. Feel free to reopen it, thanks for your suggestions again!
