### ISSUE TITLE
how can i close the port

### ISSUE THREAD

**Issue by LianShuaiLong** [microsoft/nni#3027]
**Environment**:

how can i close the port automatically when all the trials finish ?

- NNI version:
- NNI mode (local|remote|pai):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by liuzhe-lz** [comment]
Use `nnictl stop` to stop the experiment. And the port will be released automatically in about 10 seconds.

**Comment by LianShuaiLong** [comment]
> Use `nnictl stop` to stop the experiment, and the port will be released in about 10 seconds.

ok,thanks for your reply
