### ISSUE TITLE
KeyError: 'NNI_OUTPUT_DIR'’    How can I do? help.

### ISSUE THREAD

**Issue by xiajingjie** [microsoft/nni#3028]
**Environment**:
- NNI version:1.9
- NNI mode (local|remote|pai):local
- Client OS:windows10
- Server OS (for remote mode only):
- Python version:3.6
- TensorFlow version:1.15.0
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?:no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
When I use keras-mnist, the error has happened ‘Traceback (most recent call last):

  File "E:/ML/NIItry/mnist-keras.py", line 34, in <module>
    TENSORBOARD_DIR = os.environ['NNI_OUTPUT_DIR']
  File "D:\Users\HSSS\Anaconda3\envs\tensorflow-gpu\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'NNI_OUTPUT_DIR'’

How can I  deal with it?
**How to reproduce it?**: 

**Additional information**:

**Comment by liuzhe-lz** [comment]
Did you use `nnictl` to start the experiment?
NNI experiments must be launched with `nnictl create --config CONFIG.YML`. You can see more details in the [tutorial](https://nni.readthedocs.io/en/stable/Tutorial/QuickStart.html#id2)

**Comment by kvartet** [comment]
hello @xiajingjie, I will close this issue as it has not been updated for more than three months, feel free to reopen it if you still think it an active issue.
