### ISSUE TITLE
Question in darts _compute_hessian 

### ISSUE THREAD

**Issue by hroken** [microsoft/nni#3044]
In the darts trainer.py, which function is _compute_hessian, shows :
"_hessian = (dalpha { L_trn(w+, alpha) } - dalpha { L_trn(w-, alpha) }) / (2*eps)_"
but the below is written by this :
hessian = [(p - n) / **2. * eps** for p, n in zip(dalpha_pos, dalpha_neg)]
Is that wrong?

**Comment by ultmaster** [comment]
Hi @hroken , thanks for your suggestion. I think you are quite right. Could you kindly submit a PR for this?

**Comment by hroken** [comment]
> Hi @hroken , thanks for your suggestion. I think you are quite right. Could you kindly submit a PR for this?
Ok，I will try it.
