### ISSUE TITLE
General question on torch.jit.trace failure and its impact on ModelSpeedUp/DependencyAwarePruning

### ISSUE THREAD

**Issue by guojunyao419** [microsoft/nni#3050]
**What issue meet, what's expected?**:
I have a general question on using ModelSpeedUp and DependencyAwarePrunning. It seems that to be able to use these methods, the topology needs to be found by running through `torch.jit.trace` as the first step. So my question is, if for some reason the model cannot be scripted by using `torch.jit.trace` successfully, does it mean that we cannot apply ModelSpeedUp to this model? Or is there a workaround? Thanks.

**Environment**:
- NNI version: v1.8
- NNI mode (local|remote|pai): local
- Client OS: Ubuntu 18.04
- Python version: 3.6
- PyTorch/TensorFlow version: torch 1.4.0
- Is conda/virtualenv/venv used?: venv is used
- Is running in Docker?: No

**Comment by chicm-ms** [comment]
Hi @guojunyao419 ,
Yes  ModelSpeedUp and DependencyAwarePrunning are depending on `torch.jit.trace` to generate model graph by calling  `torch.jit.trace(model, dummy_input)`.  If a model can not be scripted, ModelSpeedUp and DependencyAwarePrunning will break.
If a model can not be scripted using `torch.jit.trace` at all no matter how you set the parameters of `torch.jit.trace`, there is no workaround for now.

**Comment by kvartet** [comment]
hello @guojunyao419 , I will close this issue as it has not been updated for more than three months, feel free to reopen it if you still think it an active issue.
