### ISSUE TITLE
Refine webui when compare trials

### ISSUE THREAD

**Issue by Sundrops** [microsoft/nni#3055]
**Environment**:
- NNI version: <=1.9

**What issue meet, what's expected?**:
- Can not zoom in when compare many trials.
- It's better to show Trial No. additionly for locate the trial in the following table.
![image](https://user-images.githubusercontent.com/14829222/97847157-1dc1bc80-1d2a-11eb-9194-17a6495caa58.png)

**Comment by Lijiaoa** [comment]
Thanks for your feedback! We'll improve this.

**Comment by kvartet** [comment]
Closed as it had been Improved, feel feel to reopen it. Thanks again!
