### ISSUE TITLE
ERROR: [Errno 2] No such file or directory: 'node'

### ISSUE THREAD

**Issue by LianShuaiLong** [microsoft/nni#3066]
您好，有个问题想咨询一下，利用nni训练xgb的程序我已经跑通了，现在想在linux环境下利用crontab设置定时任务：利用nni训练xgb，但是运行的时候出现了 
INFO:  expand codeDir: . to /data/home/lianshuailong/automl/lianshuailong_nni/nni_xgb/.
INFO:  Starting restful server...
ERROR: [Errno 2] No such file or directory: 'node'
~
，请问可以帮忙看一下是不是nni的问题嘛？
**Environment**:
- NNI version:
- NNI mode (local|remote|pai):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by JunweiSUN** [comment]
@LianShuaiLong 可以贴一下crontab脚本吗，nni的后端是基于nodejs，看上去似乎是找不到nni的node，您自己之前安装过nodejs吗

**Comment by liuzhe-lz** [comment]
Which version of NNI are you using?

**Comment by ntu-juking** [comment]
I have met this problem too, when I restarted the computer.
I had to reinstall the nni to resolve this issue.  :)

**Comment by scarlett2018** [comment]
@LianShuaiLong - For current released version, a known resolution from other users is to reinstall node.js. For upcoming 2.0 release, this issue seems fixed in master. cc @liuzhe-lz for confirm.

**Comment by sharoseali** [comment]
hi i upgrade my nni with verion 2 its, giving me same error when i run MNIST basic example to check if mt nni is working or not.
When i build using this command , following is the error
```
`(base) casper@caspe:~/nni$ python3 setup.py build_ts
running build_ts
# Building NNI manager 
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.28s.
yarn run v1.22.10
$ tsc
Done in 3.35s.
# Building web UI 
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.45s.
yarn run v1.22.10
$ node --max-old-space-size=3072 scripts/build.js
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Compiled successfully.

File sizes after gzip:

  804.49 KB          build/static/js/4.426d9949.chunk.js
  202.69 KB          build/static/js/1.33e11246.chunk.js
  66.85 KB           build/static/js/5.dd14e50b.chunk.js
  66.13 KB           build/json.worker.js
  43.34 KB           build/static/js/0.a6fc6d39.chunk.js
  38.79 KB           build/editor.worker.js
  27.72 KB           build/static/js/11.ce3b39f5.chunk.js
  21.1 KB            build/static/js/10.9ae5ecb9.chunk.js
  17.54 KB (+225 B)  build/static/css/4.5e338c54.chunk.css
  16 KB              build/static/js/main.edc4bca4.chunk.js
  13.85 KB           build/static/js/7.0bbd3cfd.chunk.js
  8.81 KB            build/static/js/6.2942e4e6.chunk.js
  4.95 KB            build/static/js/9.be12774e.chunk.js
  4.48 KB            build/static/js/8.630e2937.chunk.js
  2.27 KB            build/static/css/7.2a46f779.chunk.css
  2.25 KB (+23 B)    build/static/css/main.75616bc0.chunk.css
  1.82 KB            build/static/css/6.319e436d.chunk.css
  1.52 KB (-1 B)     build/static/js/runtime~main.a1aee87b.js
  759 B              build/static/css/8.501d43b7.chunk.css
  408 B (+11 B)      build/static/css/5.00ce0611.chunk.css
The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy

Done in 22.76s.
# Building NAS UI 
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.37s.
yarn run v1.22.10
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`
Compiled successfully.

File sizes after gzip:

  245.54 KB  build/static/js/2.9c383d18.chunk.js
  6.34 KB    build/static/js/main.8e6efb80.chunk.js
  779 B      build/static/js/runtime-main.e9ef6ed1.js
  583 B      build/static/css/2.47271137.chunk.css
  454 B      build/static/css/main.03bde5da.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

Done in 7.27s.
# Copying files 
yarn install v1.22.10
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning npm > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning npm > node-gyp > request > har-validator@5.1.5: this library is no longer supported
warning azure-storage > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning express-joi-validator > joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning express-joi-validator > boom@2.6.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning express-joi-validator > joi > topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning kubernetes-client > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning kubernetes-client > swagger-fluent > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sqlite3 > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning webhdfs > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[3/5] Fetching packages...
error yargs@17.0.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.23.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Traceback (most recent call last):
  File "setup.py", line 242, in <module>
    _setup()
  File "setup.py", line 105, in _setup
    'develop': Develop,
  File "/home/casper/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/casper/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/casper/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/casper/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 172, in run
    setup_ts.build(release)
  File "/home/casper/nni/setup_ts.py", line 44, in build
    copy_nni_node(release)
  File "/home/casper/nni/setup_ts.py", line 200, in copy_nni_node
    _yarn('ts/nni_manager', '--prod', '--cwd', str(Path('nni_node').resolve()))
  File "/home/casper/nni/setup_ts.py", line 218, in _yarn
    subprocess.run([str(_yarn_path), *args], cwd=path, check=True, env=_yarn_env)
  File "/home/casper/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/casper/nni/toolchain/yarn/bin/yarn', '--prod', '--cwd', '/home/casper/nni/nni_node']' returned non-zero exit status 1.
`
```
when i run the command `**nnictl create --config nni/examples/trials/mnist-pytorch/config.yml**`
its an output:
`ERROR: [Errno 2] No such file or directory: 'node': 'node'`

**Comment by scarlett2018** [comment]
> hi i upgrade my nni with verion 2 its, giving me same error when i run MNIST basic example to check if mt nni is working or not.
> When i build using this command , following is the error
> 
> ```
> `(base) casper@caspe:~/nni$ python3 setup.py build_ts
> running build_ts
> # Building NNI manager 
> yarn install v1.22.10
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> success Already up-to-date.
> Done in 0.28s.
> yarn run v1.22.10
> $ tsc
> Done in 3.35s.
> # Building web UI 
> yarn install v1.22.10
> [1/4] Resolving packages...
> success Already up-to-date.
> Done in 0.45s.
> yarn run v1.22.10
> $ node --max-old-space-size=3072 scripts/build.js
> Creating an optimized production build...
> Browserslist: caniuse-lite is outdated. Please run:
> npx browserslist@latest --update-db
> 
> Why you should do it regularly:
> https://github.com/browserslist/browserslist#browsers-data-updating
> Compiled successfully.
> 
> File sizes after gzip:
> 
>   804.49 KB          build/static/js/4.426d9949.chunk.js
>   202.69 KB          build/static/js/1.33e11246.chunk.js
>   66.85 KB           build/static/js/5.dd14e50b.chunk.js
>   66.13 KB           build/json.worker.js
>   43.34 KB           build/static/js/0.a6fc6d39.chunk.js
>   38.79 KB           build/editor.worker.js
>   27.72 KB           build/static/js/11.ce3b39f5.chunk.js
>   21.1 KB            build/static/js/10.9ae5ecb9.chunk.js
>   17.54 KB (+225 B)  build/static/css/4.5e338c54.chunk.css
>   16 KB              build/static/js/main.edc4bca4.chunk.js
>   13.85 KB           build/static/js/7.0bbd3cfd.chunk.js
>   8.81 KB            build/static/js/6.2942e4e6.chunk.js
>   4.95 KB            build/static/js/9.be12774e.chunk.js
>   4.48 KB            build/static/js/8.630e2937.chunk.js
>   2.27 KB            build/static/css/7.2a46f779.chunk.css
>   2.25 KB (+23 B)    build/static/css/main.75616bc0.chunk.css
>   1.82 KB            build/static/css/6.319e436d.chunk.css
>   1.52 KB (-1 B)     build/static/js/runtime~main.a1aee87b.js
>   759 B              build/static/css/8.501d43b7.chunk.css
>   408 B (+11 B)      build/static/css/5.00ce0611.chunk.css
> The project was built assuming it is hosted at the server root.
> You can control this with the homepage field in your package.json.
> For example, add this to build it for GitHub Pages:
> 
>   "homepage" : "http://myname.github.io/myapp",
> 
> The build folder is ready to be deployed.
> You may serve it with a static server:
> 
>   yarn global add serve
>   serve -s build
> 
> Find out more about deployment here:
> 
>   https://bit.ly/CRA-deploy
> 
> Done in 22.76s.
> # Building NAS UI 
> yarn install v1.22.10
> [1/4] Resolving packages...
> success Already up-to-date.
> Done in 0.37s.
> yarn run v1.22.10
> $ react-scripts build
> Creating an optimized production build...
> Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`
> Compiled successfully.
> 
> File sizes after gzip:
> 
>   245.54 KB  build/static/js/2.9c383d18.chunk.js
>   6.34 KB    build/static/js/main.8e6efb80.chunk.js
>   779 B      build/static/js/runtime-main.e9ef6ed1.js
>   583 B      build/static/css/2.47271137.chunk.css
>   454 B      build/static/css/main.03bde5da.chunk.css
> 
> The project was built assuming it is hosted at /.
> You can control this with the homepage field in your package.json.
> 
> The build folder is ready to be deployed.
> You may serve it with a static server:
> 
>   yarn global add serve
>   serve -s build
> 
> Find out more about deployment here:
> 
>   bit.ly/CRA-deploy
> 
> Done in 7.27s.
> # Copying files 
> yarn install v1.22.10
> info No lockfile found.
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> warning hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> warning npm > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning npm > node-gyp > request > har-validator@5.1.5: this library is no longer supported
> warning azure-storage > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning express-joi-validator > joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> warning express-joi-validator > boom@2.6.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> warning express-joi-validator > joi > topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> warning kubernetes-client > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning kubernetes-client > swagger-fluent > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning sqlite3 > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
> warning webhdfs > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> [3/5] Fetching packages...
> error yargs@17.0.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.23.0"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> Traceback (most recent call last):
>   File "setup.py", line 242, in <module>
>     _setup()
>   File "setup.py", line 105, in _setup
>     'develop': Develop,
>   File "/home/casper/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/home/casper/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/home/casper/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/home/casper/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "setup.py", line 172, in run
>     setup_ts.build(release)
>   File "/home/casper/nni/setup_ts.py", line 44, in build
>     copy_nni_node(release)
>   File "/home/casper/nni/setup_ts.py", line 200, in copy_nni_node
>     _yarn('ts/nni_manager', '--prod', '--cwd', str(Path('nni_node').resolve()))
>   File "/home/casper/nni/setup_ts.py", line 218, in _yarn
>     subprocess.run([str(_yarn_path), *args], cwd=path, check=True, env=_yarn_env)
>   File "/home/casper/anaconda3/lib/python3.7/subprocess.py", line 512, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['/home/casper/nni/toolchain/yarn/bin/yarn', '--prod', '--cwd', '/home/casper/nni/nni_node']' returned non-zero exit status 1.
> `
> ```
> 
> when i run the command `**nnictl create --config nni/examples/trials/mnist-pytorch/config.yml**`
> its an output:
> `ERROR: [Errno 2] No such file or directory: 'node': 'node'`

@liuzhe-lz any suggestion?

**Comment by scarlett2018** [comment]
@sharoseali @LianShuaiLong - are you still facing the issues?

**Comment by scarlett2018** [comment]
> @sharoseali @LianShuaiLong - are you still facing the issues?

No responds, closing the issue as overdued. Feel free to reopen if it is still an issue.
