### ISSUE TITLE
ENAS macro training 

### ISSUE THREAD

**Issue by BasselAlhallak** [microsoft/nni#3067]
Hello, first thanks for this awesome project. My question is about ENAS training: in your home page is written " Since code to train from scratch on NNI is not ready yet, reproduction results are currently unavailable." So which code should be extended/modified in order to reproduce ENAS paper results?

**Comment by ultmaster** [comment]
You need a CIFAR-10 single model training script to train the model from scratch. Technically, you can use the script from DARTS example, but we do not guarantee results.

**Comment by BasselAlhallak** [comment]
Thanks for your Answer. Just to make sure, should I implement the methods where the abstract methods  train_one_epoch, validate_one_epoch in trainer.py exist? One more question, I didn't see anything related to training RNN controller in nni/examples/nas/enas/search.py, could you please clairefy to me where that happning.

**Comment by liuzhe-lz** [comment]
Seems solved. Closing the issue.
Feel free to re-open if you have any other questions.

**Comment by BasselAlhallak** [comment]
Hello, thanks for the Answer. I am using nni v1.9 checking the modules that are imported in nni/examples/nas/enas/search.py like EnasTrainer. There I found train_one_epoch mehtod and validate one epoch method of class Enastrainer implemented. EnasTrainer class inherits Trainer class where train_one_epoch and validate_one_epoch defined as abstract methods. Now I am really confused where should I implement this CIFAR-10 singel model training.
