### ISSUE TITLE
Where should I add ENAS training code 

### ISSUE THREAD

**Issue by BasselAlhallak** [microsoft/nni#3079]
Hi, my question is related to the issue I opend couple days ago #3067. I am using nni v1.9, checking the modules that are imported in nni/examples/nas/enas/search.py like EnasTrainer, there I found train_one_epoch mehtod and validate one epoch method of class Enastrainer implemented. EnasTrainer class inherits Trainer class where train_one_epoch and validate_one_epoch defined as abstract methods. Now I am really confused where should I implement this CIFAR-10 singel model training script.

**Comment by ultmaster** [comment]
Single model training script should not rely on Trainer that is designed by NNI. If you read the retrain code in DARTS, you will notice that it is a pure PyTorch script. You should forget about trainer in NNI and do whatever you have done with pure PyTorch.

**Comment by BasselAlhallak** [comment]
If I understand it correctly, after searching is done, I should train the searched architecture from scratch just like retrain.py in DARTS example

**Comment by ultmaster** [comment]
Yes. You are right.
