### ISSUE TITLE
How to install nni without accessing to github?

### ISSUE THREAD

**Issue by lipingbj** [Microsoft/nni#308]
I have a server with enough vm and gpu,but i can't access to github because of some reason,How can i install the nni?I can download the source code of nni in windows os.

**Comment by QuanluZhang** [comment]
you can download v0.2 code and put it into your vm through someway (e.g., scp, nfs) manually. In our upcoming v0.3 version, you can install nni through python wheel package.

**Comment by scarlett2018** [comment]
v0.1 and v0.2 only support linux. the upcoming v0.3 will add the macOS support. we don't have winOS support yet.

**Comment by lipingbj** [comment]
I have installed the nni v0.3.3 successfull ,you can close this issue now.

**Comment by lipingbj** [comment]
@scarlett2018
I have installed the nni v0.3.3 successfuall.You can close the issue now.
Successfully installed nni-0.3.3 nni-sdk-0.3.0
