### ISSUE TITLE
Could not visualize the enas MacroNetwork

### ISSUE THREAD

**Issue by ylzf0000** [microsoft/nni#3083]
Environment:

NNI version:1.9
NNI mode (local|remote|pai): local
Client OS: Win10 and Ubuntu16.04
Python version: python3.7.9
PyTorch/TensorFlow version: PyTorch 1.4
Is conda/virtualenv/venv used?: conda is used
Is running in Docker?: no

**What issue meet, what's expected?**:  I want to visualize the enas MacroNetwork.

**How to reproduce it?**: 
cd examples/nas/enas
python3 search.py --search-for macro --visualization
then as mentioned in https://nni.readthedocs.io/en/latest/NAS/Visualization.html, make sure these two files graph.json and log are generated, type
nnictl webui nas --logdir /path/to/your/logdir
at this moment, powshell prompt:

(nas37) PS E:\Github\nni\examples\nas\enas> nnictl webui nas --logdir logs/1605093335.9038405
INFO:  Starting NAS UI...
NNI NAS board is running on port 6060, logdir is logs/1605093335.9038405.

but I cannot open the url 127.0.0.1:6060.:
![image](https://user-images.githubusercontent.com/17083562/98807378-852bea80-2455-11eb-8096-96d1565b3cad.png)

**Comment by ylzf0000** [comment]
but I find index.html in this path:
![image](https://user-images.githubusercontent.com/17083562/98807582-d3d98480-2455-11eb-91ca-5f1345591fc3.png)

**Comment by ultmaster** [comment]
This is probably due to the build folder is erroneously unpacked when building. You can try to move this folder into build. We will investigate into this and fix it in future releases.
