### ISSUE TITLE
Got ModuleNotFoundError when verifying nni installation

### ISSUE THREAD

**Issue by wtysos11** [microsoft/nni#3092]
**Environment**:
- NNI version: 1.9
- NNI mode (local|remote|pai): Local
- Client OS: Windows 
- Server OS (for remote mode only):
- Python version: 3.6.10
- PyTorch/TensorFlow version: 2.1.0
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

 I want to verify my installation of nni and run command ` nnictl create --config .\examples\trials\mnist-tfv2\config_windows.yml` in the root directory of nni (downloaded by `git clone git@github.com:microsoft/nni.git`). But I got `ModuleNotFoundError`.

```
(keras-gpu) PS E:\code\openSource\github\microsoft\nni> nnictl create --config .\examples\trials\mnist-tfv2\config_windows.yml
INFO:  expand searchSpacePath: search_space.json to E:\code\openSource\github\microsoft\nni\examples\trials\mnist-tfv2\search_space.json
INFO:  expand codeDir: . to E:\code\openSource\github\microsoft\nni\examples\trials\mnist-tfv2\.
ERROR: some errors happen when import package TPE.
INFO:   Stdout:




INFO:   Stderr:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nni.hyperopt_tuner'

```

I saw [this issues](https://github.com/microsoft/nni/issues/1080) and tried to solve the problem. I have uninstalled and installed nni for several times, and restarted computers too. Nothing worked for me.

However, when I download zip file in [release](https://github.com/microsoft/nni/releases) and run the same command, it works.
![result](https://user-images.githubusercontent.com/21279827/99184714-ecaca780-277f-11eb-9a35-b153d88cdcd3.png)

And I directly copy those files, run the command and get the same result. It's confused that the same command run in the same environment is different for the same file.

**How to reproduce it?**: 

For situation 1:
1. In my environment `tensorflow-gpu==2.1.0, python==3.6.10`, use `python -m pip install --upgrade nni` to install nni 1.9.
2. Use `git clone git@github.com:microsoft/nni.git` to get the source code
3. `cd nni` and run `nnictl create --config .\examples\trials\mnist-tfv2\config_windows.yml`

For situation 2:
1. In my environment `tensorflow-gpu==2.1.0, python==3.6.10`, use `python -m pip install --upgrade nni` to install nni 1.9.
2. Download zip file nni-1.9.zip from [release](https://github.com/microsoft/nni/releases)
3. `cd nni-1.9` and run `nnictl create --config .\examples\trials\mnist-tfv2\config_windows.yml`

**Additional information**:

My friend successfully use his window laptop repeat this. His environment: python==3.7.7, tensorflow==1.14.0.
He use cmd to activate conda environment.

**Comment by liuzhe-lz** [comment]
If you start Python interpreter in an empty directory, can you `import nni.hyperopt_tuner`?
If yes, please check if `sys.executable` is correct value, and if you accidentally have a "nni" directory in your current working path.

**Comment by wtysos11** [comment]
> If you start Python interpreter in an empty directory, can you `import nni.hyperopt_tuner`?
> If yes, please check if `sys.executable` is correct value, and if you accidentally have a "nni" directory in your current working path.

Thanks, you are right. There is a `nni` directory in the root path of the code downloaded by `git clone` . I'm sorry I ignored it.
