### ISSUE TITLE
AMCPruner model load --After Finetuning pruned model I can't load model

### ISSUE THREAD

**Issue by mlbo** [microsoft/nni#3093]
After Finetuning pruned MobileNetV2 model my model structure is changed ,I can't load model.
![image](https://user-images.githubusercontent.com/29347606/99228515-b0348680-2827-11eb-900b-b8d09fd24382.png)

**Comment by chicm-ms** [comment]
@mlbo Thanks for reporting this issue.
Would you please describe the reproduce steps of the problem and nni version?

**Comment by chicm-ms** [comment]
If you are using amc example to do the pruning and finetuning. after finetuning, the model structure is pruned as smaller one.  So you can not call load_state_dict to load the checkpoint into original structure,  you can use `torch.load` to load the model directly.

**Comment by scarlett2018** [comment]
Close as the issue has been answered for a while, feel free to reopen if you still have problems with the issue.
