### ISSUE TITLE
[bug] Homepage links are broken.

### ISSUE THREAD

**Issue by SpongeBob-222** [microsoft/nni#3104]
Hello, I found that the links of Prunning are all broken.

![image](https://user-images.githubusercontent.com/11664658/99641211-e884d080-2a84-11eb-9da2-c2461e9a5017.png)
![image](https://user-images.githubusercontent.com/11664658/99641365-1ff37d00-2a85-11eb-861b-09942cd85bb2.png)

Thanks!

**Comment by kvartet** [comment]
Thank you, we have fixed it.

**Comment by scarlett2018** [comment]
closing the issue as it has been fixed.

Thanks @SpongeBob-222 again for reporting the bug!
