### ISSUE TITLE
cannot import name 'FPGMPruner' from 'nni.compression.tensorflow'

### ISSUE THREAD

**Issue by mymusise** [microsoft/nni#3112]
**Environment**:
- NNI version: 1.9

**Description**:

Hi, I followed this [example](https://github.com/microsoft/nni/blob/master/examples/model_compress/fpgm_tf_mnist.py) but got this error:

```
----> 6 from nni.compression.tensorflow import FPGMPruner
      7 
      8 def get_data():

ImportError: cannot import name 'FPGMPruner' from 'nni.compression.tensorflow'
```

**Comment by liuzhe-lz** [comment]
Sorry but the example was outdated.
TensorFlow model compression has been rewritten for supportting TF 2.x and the pruning algorithms have not been added back yet.
We suggest to use PyTorch model compression for now.

**Comment by mymusise** [comment]
Thanks to let me know.
