### ISSUE TITLE
Discussion of algorithm importing shorcut

### ISSUE THREAD

**Issue by liuzhe-lz** [microsoft/nni#3129]
This is more a task of decision rather than coding, so this is an issue not PR. Code snippets are attached though.

Importing algorithm classes have always been tedious, and v2.0 code hierarchy refactor pushed this to an unbearable degree.

  - v1.x: `from nni.hyperopt_tuner.hyperopt_tuner import HyperoptTuner`
  - v2.0: `from nni.algorithms.hpo.hyperopt_tuner.hyperopt_tuner import HyperoptTuner`.

I have three candidate preferred ways of importing algorithms class, from longer to shorter:

  1. `from nni.algorithms.hpo.hyperopt_tuner import HyperoptTuner`
  2. `from nni.algorithms.hpo import HyperoptTuner`
  3. `from nni.tuner import HyperoptTuner`

The second and third approaches raise the problem that not all tuners are guaranteed to be importable due to dependencies.

In Python 3.6, this can be done in two ways:

  1. Catch and ignore `ImportError`. The major drawback is that it might be slow to import all tuners.
  2. Compile a manifest of dependencies and check their existence before importing. This will be harder to maintain and can be slow as well.

For Python 3.7 and above, module level `__getattr__` is a perfect solution, which allows lazy import.

My personal preferred solution is to suggest users to use Python 3.7+, and if they stick with Python 3.6 we provide the functionality as well but have no guarantee on performance.

The code will be like this:

```Python
# nni/algorithms/hpo/__init__.py or nni/tuner.py

_class_package = {
    'HyperoptTuner': 'hyperopt_tuner',
    ...
}

if sys.version_info < (3, 7):
    for class_name, package in _class_package.items():
        with contextlib.suppress(ImportError):
            module = importlib.import_module('nni.algorithms.hpo.' + package)
            globals()[class_name] = getattr(module, class_name)

else:
    def __getattr__(self, class_name):
        if module not in _class_package:
            raise ImportError()
        module = importlib.import_module('nni.algorithms.hpo.' + _class_package[class_name])
        return getattr(module, class_name)
```

**Comment by kvartet** [comment]
@liuzhe-lz, seems this had been finished, so I will close this issue, feel free to reopen it.
