### ISSUE TITLE
If an experiment is over, what information will I get from terminal?

### ISSUE THREAD

**Issue by cjissmart** [microsoft/nni#3135]
I want to know whether an experiment is over from terminal. What information can indicate it？

**Comment by SparkSnail** [comment]
You can use `nnictl experiment status ` command to get experiment information.

**Comment by scarlett2018** [comment]
closing the issue as the answer had been provided. @cjissmart, thanks for using NNI and connecting us for help, feel free to reopen the issue if the provided answer was not sufficient and you have more to ask.
