### ISSUE TITLE
GPU memory cannot be released automatically when trial is completed

### ISSUE THREAD

**Issue by Yivory** [microsoft/nni#3136]
**Environment**:
- NNI version: **1.9**
- NNI mode (local|remote|pai): **local**
- Client OS: **ubantu 16.04**
- Server OS (for remote mode only):
- Python version: **3.7.9**
- PyTorch/TensorFlow version: **TF 2.3.0**
- Is conda/virtualenv/venv used?: **yes**
- Is running in Docker?: **no**

**What issue meet, what's expected?**:  
The completed trial still uses GPU memory.Is this normal?
<img width="654" alt="Snipaste_2020-11-29_23-26-19" src="https://user-images.githubusercontent.com/26850902/100546181-c4c94380-3257-11eb-95a3-2a18a0e993d2.png">
The python processes of Trial No1 and No2 were killed manually.
<img width="321" alt="Snipaste_2020-11-29_23-26-43" src="https://user-images.githubusercontent.com/26850902/100546182-c85cca80-3257-11eb-9a64-3fc5bf5a79ab.png">
So, how to end corresponding process automatically when the trial is completed?
Trial No.3 should release GPU memory when succeeded, right？

**Comment by Yivory** [comment]
The good news is that after a day of trials, the GPU memory usage has returned to normal.
<img width="802" alt="Snipaste_2020-11-30_19-40-39" src="https://user-images.githubusercontent.com/26850902/100606183-f5b18300-3300-11eb-9967-d5f9af906e6d.png">
<img width="318" alt="Snipaste_2020-11-30_19-40-58" src="https://user-images.githubusercontent.com/26850902/100606195-f9dda080-3300-11eb-9560-781ebb609fde.png">
I have been using nni for less than two days, and one thing I remembered was when I used nni for the first time and enabled 4 parallelization trials. After I entered the command **nnictl stop**, even after a period of time, 4 python processes were still running and the corresponding GPU memory was still used. Finally, I had to manually kill these python processes.

**Comment by J-shang** [comment]
Thanks for your issue, we will try to reproduce this situation. Can you show your `experiment config` and `nnimanager.log` for our reference?

**Comment by Yivory** [comment]
The following are the experiment config and log of the running trial. Some privacy strings have been replaced by **?**. You can download them from the link below.
**experiment config link:** https://1drv.ms/u/s!ArTZkqf2dBl-ppgCWHG4GZnEAxrvDg?e=J8rnGR
**nnimanager.log link:** https://1drv.ms/u/s!ArTZkqf2dBl-ppgA_qTKH7_ooaFN9Q?e=RAz8VL

And I checked the logs of previous experiments, the only log containing **WARNING** and **ERROR** is below.
**nnimanager_with_error.log link:** https://1drv.ms/u/s!ArTZkqf2dBl-ppgDGX_L5PVKNFapWA?e=NQesnO

**Comment by J-shang** [comment]
The information you provided is helpful to us, we will follow up with this issue as soon as there is progress.

**Comment by kvartet** [comment]
hello @J-shang - would you mind sharing the latest status of this issue? thanks!

**Comment by J-shang** [comment]
@kvartet We change `stop()` logic in local training in v2.0, and I think this issue has been solved and can be closed.
