### ISSUE TITLE
Add http in the Web UI Urls

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#3144]
Add `http://` in the Web UI URLs in training services like local mode for more convenient to open:

![image](https://user-images.githubusercontent.com/23700012/100822023-7fda2280-348c-11eb-9945-bd9d574e3b2d.png)

![image](https://user-images.githubusercontent.com/23700012/100821722-eb6fc000-348b-11eb-9c5b-7ceac964b587.png)

**Comment by Lijiaoa** [comment]
Hi @colorjam Thanks for raising this issue. It is a good user experience. The latest version of nni already supports this function. You can try our latest version v2.9. It will be released soon.
