### ISSUE TITLE
How many "_type" are there in the search_space.json file? Where can i find them?

### ISSUE THREAD

**Issue by JohnGithub917** [microsoft/nni#3149]
Don't know how to write _type parameter.

**Comment by CSH360** [comment]
Check out the link below to know how to define different types of strategies and parameters.
https://nni.readthedocs.io/en/stable/Tutorial/SearchSpaceSpec.html

**Comment by liuzhe-lz** [comment]
https://nni.readthedocs.io/en/stable/Tutorial/SearchSpaceSpec.html

**Comment by scarlett2018** [comment]
> https://nni.readthedocs.io/en/stable/Tutorial/SearchSpaceSpec.html

@JohnGithub917 - is the document sufficient enough for answering your question? feel free to let us know if you have further questions, thanks.

**Comment by JohnGithub917** [comment]
yes, it's quite informative. Thanks. @scarlett2018 @liuzhe-lz
