### ISSUE TITLE
Dispatcher error: read ECONNRESET

### ISSUE THREAD

**Issue by bregmangh** [microsoft/nni#3162]
**Environment**:
- NNI version:1.9
- NNI mode (local|remote|pai):local
- Client OS: CentOS
- Server OS (for remote mode only):
- Python version: 3.7
- PyTorch/TensorFlow version: 1.6
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: no

**Log message**:
 - nnimanager.log:  ERROR [ 'Dispatcher error: read ECONNRESET' ]
 - dispatcher.log: ERROR (nni.msg_dispatcher_base/Thread-1) 
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by J-shang** [comment]
Would you please show the full content of `nnimanager.log` and `dispatcher.log`, and the output of nnictl log `stderr` and `stdout`? And if convenient, `config.yml` is also need.

**Comment by kvartet** [comment]
hello @bregmangh, I will close this issue as it has not been updated for more than three months, feel free to reopen it if you still think it an active issue.
