### ISSUE TITLE
The process never gets terminated with --foreground flag

### ISSUE THREAD

**Issue by kvartet** [microsoft/nni#3165]
We are running hyperparameter tuning with --foreground flag as we want it not to shut down before all the trials completed. However, with the --foreground flag set it never gets terminated. The log says "Experiment done", but the process never gets terminated.

**Comment by kvartet** [comment]
@savan77 Hello, I opened this issue for you, so you can follow the latest progress here.

**Comment by SparkSnail** [comment]
It is by design for foreground mode. Users could use `Ctrl + C` to manually terminate process.
