### ISSUE TITLE
Use SIGTERM instead of SIGKILL when cancelling a trial job

### ISSUE THREAD

**Issue by maxxx580** [microsoft/nni#3166]
**Environment**:
- NNI version:1.9
- NNI mode (local|remote|pai):local
- Client OS: linux
- Server OS (for remote mode only):linux
- Python version:3.7
- PyTorch/TensorFlow version:1.5.1
- Is conda/virtualenv/venv used?: yes, conda
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: n/a
 - dispatcher.log: n/a
 - nnictl stdout and stderr:n/a
 

**What issue meet, what's expected?**:
Is it possible SIGTERM instead of SIGKILL when cancelling trial jobs. By doing so event handler can be registered to perform trial clean-up. 
https://github.com/microsoft/nni/blob/master/ts/nni_manager/training_service/local/localTrainingService.ts#L256
**How to reproduce it?**: 
n/a
**Additional information**:
n/a

**Comment by kvartet** [comment]
Hello @maxxx580, I’m closing this issue as it has been discussed in the wechat group, please feel free to reopen if you are still seeing it an active issue.
