### ISSUE TITLE
 nnictl not an internal or external command(Windows)

### ISSUE THREAD

**Issue by Dong7777** [microsoft/nni#3169]
**Environment**:
- NNI version:
- NNI mode (local|remote|pai):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by J-shang** [comment]
Could you please show more information? Such as the way you installed nni.
Thank you.

**Comment by kvartet** [comment]
hello @Dong7777, could you follow this and update the status of this issue? Thank you!

> Could you please show more information? Such as the way you installed nni.
> Thank you.

**Comment by scarlett2018** [comment]
as there are no responds so far, closing the issue as overdued. feel free to reopen if it is still an issue.
