### ISSUE TITLE
源码不包含 REQUEST_TRIAL_JOBS 实现逻辑

### ISSUE THREAD

**Issue by wulucxy** [microsoft/nni#3195]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**

全局搜索 `REQUEST_TRIAL_JOBS`，无法查找到相应的代码实现逻辑

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version: 1.9
- nni mode(local|pai|remote):
- OS: macOS
- python version: 3.7
- is conda or virtualenv used?:
- is running in docker?:

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by liuzhe-lz** [comment]
https://github.com/microsoft/nni/blob/master/nni/runtime/msg_dispatcher.py#L97
