### ISSUE TITLE
unable to compress squeeze-excite module?

### ISSUE THREAD

**Issue by twmht** [microsoft/nni#3206]
**Environment**:
- NNI version:3.0
- NNI mode (local|remote|pai):master

**What issue meet, what's expected?**:
I found out nni does not support se module compression in my network.

here is the net graph before compression

```
(stage2): _OSA_stage(
    (OSA2_1): _OSA_module(
      (layers): ModuleList(
        (0): Sequential(
          (0): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
        (1): Sequential(
          (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
        (2): Sequential(
          (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
      )
      (concat): Sequential(
        (0): Conv2d(320, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (ese): eSEModule(
        (avg_pool): AdaptiveAvgPool2d(output_size=1)
        (fc): Conv2d(112, 112, kernel_size=(1, 1), stride=(1, 1))
        (hsigmoid): Hsigmoid()
      )
    )
```

the output from `concat` module would be feed into `ese` module, the number of input channel and output channel of `ese` module should be same. however, after speeding up  the model, the number of input channel and output channel are different.

```
  (stage2): _OSA_stage(
    (OSA2_1): _OSA_module(
      (layers): ModuleList(
        (0): Sequential(
          (0): Conv2d(105, 52, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): BatchNorm2d(52, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
        (1): Sequential(
          (0): Conv2d(52, 39, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): BatchNorm2d(39, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
        (2): Sequential(
          (0): Conv2d(39, 19, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): BatchNorm2d(19, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
      )
      (concat): Sequential(
        (0): Conv2d(215, 100, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (ese): eSEModule(
        (avg_pool): AdaptiveAvgPool2d(output_size=1)
        (fc): Conv2d(100, 112, kernel_size=(1, 1), stride=(1, 1))
        (hsigmoid): Hsigmoid()
      )
    )
  )
``` 

**How to reproduce it?**: 

just put se module at any network. or use my network #3200

**Additional information**:

is it possible to support squeeze-excite module in nni? or should I just hard code some constraint in the compressor?

**Comment by xingxing-123** [comment]
I have a similar problem. After pruning, the mask conflict of the SE module cannot be resolved. A simple solution is to not pruning the conv related to the se module by setting the 'op_names'.

**Comment by zheng-ningxin** [comment]
Hi~ Thanks for the feedback! Would you please show us the code snippet of the model definition?

**Comment by twmht** [comment]
@zheng-ningxin 

https://drive.google.com/drive/folders/1IebklNoylXww7Wj0CpK9w52LZcpVyqPe?usp=sharing

or 

https://github.com/youngwanLEE/vovnet-detectron2/blob/master/vovnet/vovnet.py

**Comment by xingxing-123** [comment]
Hi, the code snippet is：
(catfeature): layer_feat_concate(
    (gate_member): ModuleList(
      (0): Sequential(
        (0): AdaptiveMaxPool2d(output_size=7)
        (1): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): LeakyReLU(negative_slope=0.01)
      )
      (1): Sequential(
        (0): AdaptiveMaxPool2d(output_size=7)
        (1): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): LeakyReLU(negative_slope=0.01)
      )
      (2): Sequential(
        (0): AdaptiveMaxPool2d(output_size=7)
        (1): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): LeakyReLU(negative_slope=0.01)
      )
      (3): Sequential(
        (0): AdaptiveMaxPool2d(output_size=7)
        (1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): LeakyReLU(negative_slope=0.01)
      )
    )
    (reweight): squeezeExtra_moudle(
      (avg_pol): AdaptiveAvgPool2d(output_size=1)
      (squeeze): Conv2d(2048, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (expand): Conv2d(128, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (sigmod): Sigmoid()
    )
  )

The compression config(AGP pruner) :
pruner_config = [{
        'initial_sparsity':
        0.0,
        'final_sparsity':
        0.8,
        'start_epoch':
        0,
        'end_epoch':
        50,
        'frequency':
        1,
        'op_types': ['Conv2d'],
        'op_names': [
            'backbone.conv1', 'backbone.layer1.0.conv1', 'backbone.layer1.0.conv2', 'backbone.layer1.0.conv3', 'backbone.layer1.0.downsample.0', 'backbone.layer1.1.conv1', 'backbone.layer1.1.conv2', 'backbone.layer1.1.conv3',
            'backbone.layer1.2.conv1', 'backbone.layer1.2.conv2'......**(exclude conv2d of catfeature and reweight)**
        ],
    }]
The problem I encountered is that after AGP pruning, there will be unresolved mask conflicts due to the SE module when using ModelSpeedup. Therefore, the conflicting conv2d is not pruned.

**Comment by kvartet** [comment]
hello @zheng-ningxin - would you mind sharing the latest status of this issue? thanks!

**Comment by scarlett2018** [comment]
as there are no responds so far, closing the issue as overdued. feel free to reopen if it is still an issue.
