### ISSUE TITLE
Problems in customizing new cells in DARTS

### ISSUE THREAD

**Issue by R1ckShi** [microsoft/nni#3225]
I am a beginner in NAS and DARTS.
I'm wondering that if there are 4 cells defined (3 normal and 1 reduction) in my model but why searched architecture only contains one architecture for the normal cell not 3?
If the reduction cell is cell2, and the normal cells are cell0, cell1, and cell3, the visualized model only contains graphs for cell0 and cell2, why, and where can I find the define for parameter sharing?
![image](https://user-images.githubusercontent.com/40013335/102966892-c373f980-452b-11eb-9e6f-1e3b65844057.png)
The two main blocks refer to cell0 (the first normal cell) and cell2 (the only reduction cell).

**Comment by ultmaster** [comment]
The other normal cells are collapsed as they share the similar structure. You can expand them with double-click.

**Comment by R1ckShi** [comment]
Thanks. Does that mean the darts mutator automatically considers all the normal cells have the same structure and these cells use the same arc controlling parameter alpha?

**Comment by ultmaster** [comment]
You can check the keys of LayerChoice. If they use the same key, they will share the same architecture.

**Comment by R1ckShi** [comment]
Thanks! @ultmaster

**Comment by R1ckShi** [comment]
@ultmaster Thanks for your help again.
Here is another problem I met, I customized a new cell with new nodes in it, and new a different key in layer choice, but the alpha for the new cell in the mutator doesn't change during the training.
Here is my code for the cell:
```
class Post_Node(nn.Module):
    def __init__(self, node_id, num_prev_nodes, channels):
        super().__init__()
        self.ops = nn.ModuleList()
        choice_keys = []
        stride = 1
        # print(num_prev_nodes)
        for i in range(num_prev_nodes):
            choice_keys.append("{}_p{}".format(node_id, i))
            self.ops.append(
                mutables.LayerChoice(OrderedDict([
                    '''
                        my ops
                    '''
                ]), key=choice_keys[-1]))
        self.drop_path = ops.DropPath()
        self.input_switch = mutables.InputChoice(choose_from=choice_keys, n_chosen=2, key="{}_switch".format(node_id))

class Post_Cell(nn.Module):
    def __init__(self, n_nodes, channels):
        super().__init__()
        self.n_nodes = n_nodes
        self.mutable_ops = nn.ModuleList()
        for depth in range(2, self.n_nodes + 2):
            self.mutable_ops.append(Post_Node("{}_n{}".format("post", depth),
                                         depth, channels))
    def forward(self, s0, s1):
        tensors = [s0, s1]
        for node in self.mutable_ops:
            cur_tensor = node(tensors)
            tensors.append(cur_tensor)
        output = torch.cat(tensors[2:], dim=1)
        return output
```
Is there any problem in the define of `post cell`?


![image](https://user-images.githubusercontent.com/40013335/103498001-3e1f0c00-4e7e-11eb-84a2-9c48352afed7.png)
Alpha for post cell in tensorboard (normal cell changes correctly).

**Comment by ultmaster** [comment]
I didn't see any obvious problems. Is the back propagation of post cell working properly. How about the gradients of other parameters other than alpha? For example, the convolutions in your layer choice?

**Comment by R1ckShi** [comment]
I checked the parameter in the post cell, and it turns out that the parameters other than alpha don't change either.

**Comment by ultmaster** [comment]
If so, there must be something wrong with your model. Please check your graph.

**Comment by R1ckShi** [comment]
@ultmaster Good afternoon.
I'm trying to make my trainer support unrolled backward method. 
But in the function `_compute_virtual_model()` in the DartsTrainer, when computing `gradients = torch.autograd.grad(loss, self.model.parameters()`, it raised _"RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior."_
Does that mean that some tensors in `model.parameters()` has no grad to the loss?
And is it OK to set allow_unused=True and apply momentum only to tensors that have grads to the loss?

**Comment by R1ckShi** [comment]
I judge if the `d` and `w` in `dw` is None in `_compute_hessian()`, as well as in the momentum applying in the `_compute_virtual_model()`, the program seems running well.
But I'm still curious about the season of the error. Orz.

**Comment by ultmaster** [comment]
I think it's a pure PyTorch problem. You are right to set allow_unused if some parameters are intended to be not used. However, momentum is more tricky. You can refer to the implementation of different optimizers on their behaviors in dealing with momentum.

**Comment by R1ckShi** [comment]
In the `sample_final()` function of `class DartsMutator`, why the last arc is not considered in max()? 
If so what's the purpose of inserting extra connection to all the layerchoice?
```python
def sample_final(self):
        result = dict()
        edges_max = dict()
        for mutable in self.mutables:
            if isinstance(mutable, LayerChoice):
                max_val, index = torch.max(F.softmax(self.choices[mutable.key], dim=-1)[:-1], 0)
                edges_max[mutable.key] = max_val
```

**Comment by R1ckShi** [comment]
@ultmaster Good afternoon.
I'm wondering what's the purpose of inserting extra connection to all the layerchoice?
Cause the last arc's weight in my experiments is always high.
![image](https://user-images.githubusercontent.com/40013335/106712488-fb468480-6633-11eb-8e7e-2368ee6308c0.png)
![image](https://user-images.githubusercontent.com/40013335/106712564-1913e980-6634-11eb-8800-c85abfbc77a4.png)
Around half of all the layerchoice mutators.

And will this influence the other arcs? All the mutators abandoned the fifth arc which is considered competitive humanly.
Thanks a lot.

**Comment by ultmaster** [comment]
In their paper, the authors of DARTS consider inserting an none-op, which cut off the connection. You can re-implement this if you don't want the cut-off.

I'd think there are researches that are investigating this issues, known as "architecture collapse", but I don't know much about it.

**Comment by R1ckShi** [comment]
But the `apply_fixed_architecture()` method doesn't cut off the connection indeed, right? @ultmaster

**Comment by ultmaster** [comment]
Yes. It will cut off. You will see some of the layer choices choose null as their results.

**Comment by R1ckShi** [comment]
Yes, i see. Much wrong understanding with the code before. Thanks a lot.
