### ISSUE TITLE
How to start  nni tuning based on historical tuning records?

### ISSUE THREAD

**Issue by jyhengcoder** [microsoft/nni#3226]
I have a question about using nni. Consider a certain scenario, when the automl tuning process continues for a long time, but suddenly terminates abnormally. In this case, how to save the current tuning results and continue the automl process based on the historical tuning records?

**Comment by jyhengcoder** [comment]
I think this case is similar to saving checkpoint during neural network training.

**Comment by J-shang** [comment]
Yes, this is an important feature and nni have supported. All tuning results will be saved under `~/nni-experiments/<experiment_id>/db/nni.sqlite` and you can use `nnictl resume [experiment_id]` to resume a stopped experiment. 

FYI: https://nni.readthedocs.io/en/stable/Tutorial/Nnictl.html#resume

**Comment by jyhengcoder** [comment]
@J-shang Thank you for your answer. One more question, can I dynamically change the parameter search space while the nni process is running?

**Comment by jyhengcoder** [comment]
> @J-shang Thank you for your answer. One more question, can I dynamically change the parameter search space while the nni process is running?

I found `nnictl  update` in the doc can answer my question, I will close this issue.
