### ISSUE TITLE
more python client support

### ISSUE THREAD

**Issue by maxxx580** [microsoft/nni#3236]
**What would you like to be added**: python api for more `nnictl` commands

**Why is this needed**: to mange experiments programmatically 

**Without this feature, how does current nni work**: python subprocess, but parsing its output is unreliable. 

**Components that may involve changes**: not sure

**Brief description of your proposal if any**: n/a

**Comment by liuzhe-lz** [comment]
For nni v1.9, you can use `nnicli.Experiment`, which is a wrapper over nnictl. (source: https://github.com/microsoft/nni/blob/v1.9/src/sdk/pycli/nnicli/nni_client.py )
For upcoming nni v2.0, the class is moved to `nni.experiment.LegacyExperiment`.

**Comment by maxxx580** [comment]
> For nni v1.9, you can use `nnicli.Experiment`, which is a wrapper over nnictl. (source: https://github.com/microsoft/nni/blob/v1.9/src/sdk/pycli/nnicli/nni_client.py )
> For upcoming nni v2.0, the class is moved to `nni.experiment.LegacyExperiment`.

Im aware of `nnicli.Experiment`, but it's functionality is limited. I was wondering if there's a plan to support more cmd such as `nnictl experiment` or `nnictl top`, which are helpful to monitor experiments programmatically. 

Given its name `LegacyExperiment`, is it going to be deprecated in the near future ? what's the alternative ?

**Comment by liuzhe-lz** [comment]
We are rewriting the experiment library from scratch. The new library will be named `nni.experiment.Experiment`.
It's not complete now and you can expect it to support the functions you mentioned in v2.1 release.

**Comment by maxxx580** [comment]
> We are rewriting the experiment library from scratch. The new library will be named `nni.experiment.Experiment`.
> It's not complete now and you can expect it to support the functions you mentioned in v2.1 release.
> 
> Implementation details: `LegacyExperiment` is a wrapper over `nnictl`. It uses `subprocess` module to invoke `nnictl` and parses its output. While `Experiment` is a native Python library and `nnictl` will be built on top of this library in future.

thank you for your reply and I look forward to v2.1.

**Comment by liuzhe-lz** [comment]
It's scheduled to release in Feb, but may delay to March because of Spring Festival.

**Comment by scarlett2018** [comment]
> It's scheduled to release in Feb, but may delay to March because of Spring Festival.

@liuzhe-lz @kvartet - has this one been released in 2.x? thanks.

**Comment by kvartet** [comment]
@maxxx580 @scarlett2018 - this feature had been released in v2.1, so I'm closing this issue, feel free to reopen it.
