### ISSUE TITLE
[Enhancement] View log message more conveniently 

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/nni#3246]
**qestion**:
as this picture, the log is too long in some line, It's inconvenient to view this log.
![image](https://user-images.githubusercontent.com/61399850/103402844-f8fe8f80-4b88-11eb-978b-9851a898eaa4.png)

**how to do it**:
maybe we could extend log box's width or use editor config to improment it.

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by scarlett2018** [comment]
自动折行

**Comment by Lijiaoa** [comment]
I'll close this issue because it had been released in `v2.2` .
