### ISSUE TITLE
any reason that slim pruner  does not support dependency aware mode?

### ISSUE THREAD

**Issue by twmht** [microsoft/nni#3256]
**Environment**:
- NNI version: 1.9
- NNI mode (local|remote|pai): local

I've read the code and can't get why `slim pruner` does not support dependency aware mode. the current implementation only supports `conv2d`. but it seems that it's easy to support` batchnorm2d` as well.

is there any reason that nni does not support that?

**Comment by zheng-ningxin** [comment]
Sincerely sorry for the late reply. There is actually no special reason. We are looking for a general way to analyze dependencies for the submodules, so we haven't supported more pruners for the time being
