### ISSUE TITLE
more error message for remote training service

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#3259]
**What would you like to be added**: could add more error information for remote training service. for example, if the directory `/tmp/nni-experiments` has incorrect permission, error message should be output in nnimanager.log. Second, when trialkeeper is not successfully started, error message should be output in nnimanager.log and nnimanager should do something for it.

**Why is this needed**: more friendly to users and developers

**Without this feature, how does current nni work**：it can work normally

**Comment by scarlett2018** [comment]
both issues had been fixed in 2.0 bug bash - @QuanluZhang to verify.

**Comment by Lijiaoa** [comment]
@liuzhe-lz Please help check this issue, thanks!
