### ISSUE TITLE
show the assigned training service of each trial in hybrid training service

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#3261]
**What would you like to be added**: The hybrid training service mode allows users to run an NNI experiment on multiple training services to leverage every training service's spare resource. It would be great to show the assigned training service of each trial in hybrid training service mode. With this feature, users can easily know how many trials are assigned to each training service.

**Why is this needed**: user friendly

**Without this feature, how does current nni work**：check each trial's log on webui

**Comment by kvartet** [comment]
Closing the issue because the feature request has been implemented.
