### ISSUE TITLE
export_model does not reduce the size of model. 

### ISSUE THREAD

**Issue by mwsunshine** [microsoft/nni#3273]
**Environment**:
- NNI version:1.9
- Client OS: ubuntu 16.04
- Python version:3.7.9
- PyTorch/TensorFlow version: pytorch 1.6.0
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

I try to compress my own model by using methods shared by this page: [(https://github.com/microsoft/nni/blob/v1.9/examples/model_compress/model_prune_torch.py](url)
and try several one-shot compression methods which could generate pruned model and mask via using function: pruner.export_model.

However my question comes as this function does not reduce the size of my model (original model size: 20,614KB, pruned model size: 20,612KB, mask size: 20,556KB). 

I check what could be done after obtaining the pruned model through this page:https://github.com/microsoft/nni/blob/v1.9/examples/model_compress/pruning_kd.py

Seems that the pruned model could be fine-tuned and inferenced afterwards.

However, I could barely find any advantages if the pruned model has a similar size as the original one( or even larger if taking the mask file into account) but lower accuracy, 

So Am I doing this compression process wrong? How could I use the pruned model?

**Comment by colorjam** [comment]
@mwsunshine Masks do not provide the real speedup of your pruned model, they are used to make some values to zero during fine-tuning. The model should be speeded up based on the exported masks. Please refer to [here](https://nni.readthedocs.io/en/stable/Compression/ModelSpeedup.html) for detail description.

**Comment by mwsunshine** [comment]
> @mwsunshine Masks do not provide the real speedup of your pruned model, they are used to make some values to zero during fine-tuning. The model should be speeded up based on the exported masks. Please refer to [here](https://nni.readthedocs.io/en/stable/Compression/ModelSpeedup.html) for detail description.

Hi, colorjam, 

many thanks for your answer! Now I see that mask is basicly used during fune-tuning. I also looked through the link you shared to me. However, I have a problem for the input(dummy_input) of the function of ModelSpeedup. At the page, dummy_input is created by torch.randn(shape), but my model has two inputs, e.g. image1 and image2. How could I transfer the two inputs of mine to the dummy_input?

I did the test as follows:
dummy_input = [img1, img2] or (img1, img2)
function ModelSpeedup can run, but generates an error when speedup_model is called. The error is :AssertionError only. No other information.

**Comment by mwsunshine** [comment]
Hi,

In order to check where am I wrong, I did several tests:
1. I changed the number of my net input from two to one(concatenate at first and then seperate into two tensors inside) to get rid of the influence of JIT trace. And my tried the function result = model(dummy_input), it worked. This indicates my error has no relation with JIT trace.

2.  The line for ModelSpeedup(model, dummy_input, masks_file) does not cause erros, but the line of m_speedup.speedup_model() does.

3.  I tried different pruned methods, errors are listed below:
**Level:** 'NoneType' object is not subscriptable
INFO (nni.compression.torch.utils.mask_conflict) dim0 sparsity: 0.000000
INFO (nni.compression.torch.utils.mask_conflict) dim1 sparsity: 0.000736
INFO (nni.compression.torch.utils.mask_conflict) detected conv prune dim: 1
**l1filter  and fpgm**:  AssertionError
{'fnet.conv1': 1, 'fnet.layer1.0.conv1': 1, 'fnet.layer1.0.conv2': 1, 'fnet.layer1.1.conv1': 1, 'fnet.layer1.1.conv2': 1, 'fnet.layer2.0.conv1': 1, 'fnet.layer2.0.conv2': 1, 'fnet.layer2.0.downsample.0': 1, 'fnet.layer2.1.conv1': 1, 'fnet.layer2.1.conv2': 1, 'fnet.layer3.0.conv1': 1, 'fnet.layer3.0.conv2': 1, 'fnet.layer3.0.downsample.0': 1, 'fnet.layer3.1.conv1': 1, 'fnet.layer3.1.conv2': 1, 'fnet.conv2': 1, 'cnet.conv1': 1, 'cnet.layer1.0.conv1': 1, 'cnet.layer1.0.conv2': 1, 'cnet.layer1.1.conv1': 1, 'cnet.layer1.1.conv2': 1, 'cnet.layer2.0.conv1': 1, 'cnet.layer2.0.conv2': 1, 'cnet.layer2.0.downsample.0': 1, 'cnet.layer2.1.conv1': 1, 'cnet.layer2.1.conv2': 1, 'cnet.layer3.0.conv1': 1, 'cnet.layer3.0.conv2': 1, 'cnet.layer3.0.downsample.0': 1, 'cnet.layer3.1.conv1': 1, 'cnet.layer3.1.conv2': 1, 'cnet.conv2': 1, 'update_block.encoder.convc1': 1, 'update_block.encoder.convc2': 1, 'update_block.encoder.convf1': 1, 'update_block.encoder.convf2': 1, 'update_block.encoder.conv': 1, 'update_block.gru.convz1': 1, 'update_block.gru.convr1': 1, 'update_block.gru.convq1': 1, 'update_block.gru.convz2': 1, 'update_block.gru.convr2': 1, 'update_block.gru.convq2': 1, 'update_block.flow_head.conv1': 1, 'update_block.flow_head.conv2': 1, 'update_block.mask.0': 1, 'update_block.mask.2': 1}# this should be my net parameters
INFO (nni.compression.torch.utils.mask_conflict) dim0 sparsity: 0.500000
INFO (nni.compression.torch.utils.mask_conflict) dim1 sparsity: 0.000000
INFO (nni.compression.torch.utils.mask_conflict) detected conv prune dim: 0
**Slim:** no errors generated, but blocked at this step and no more changes from then on
WARNING (nni.compression.torch.utils.mask_conflict) no multi-dimension masks found.
INFO (nni.compression.torch.utils.mask_conflict) detected conv prune dim: 0

Any helps are appreciated!

**Comment by mwsunshine** [comment]
@colorjam  @kvartet @QuanluZhang @zheng-ningxin  Anybody could help please?

**Comment by zheng-ningxin** [comment]
Hi, thanks for the feedback!  I'll support multi-inputs for `ModelSpeedup` ASAP.
By the way, could you please show us the code snippet of the model so that I can reproduce the problem you met?

**Comment by mwsunshine** [comment]
> Hi, thanks for the feedback! I'll support multi-inputs for `ModelSpeedup` ASAP.
> By the way, could you please show us the code snippet of the model so that I can reproduce the problem you met?

hi，ningxin,

Thank you for your quick response! As I changed the input from two to one, the error remained, I suppose multi-inputs is not the cause for this AssertionError.

Sure! I will show you the code. I am trying to prune the model given by this webpage: https://github.com/princeton-vl/RAFT, where the training code, testing code and models are all available.

I collect all the information you need in the attached file:
train.py is used to prune the model given by the author(I use the model named raft-things.pth)
validation.py is used to check the result of pruned model.
[RAFT.zip](https://github.com/microsoft/nni/files/5799325/RAFT.zip)

**Comment by mwsunshine** [comment]
> Hi, thanks for the feedback! I'll support multi-inputs for `ModelSpeedup` ASAP.
> By the way, could you please show us the code snippet of the model so that I can reproduce the problem you met?

Hi, ningxin,

Could you reproduce my error as I mentioned above? Feel free to ask for any information if you need!

**Comment by zheng-ningxin** [comment]
Nope, I try to run the code you gave to me but due to environmental issues, I have not successfully run your code.
Could you provide more information about the assertion error such as it fails at which line, and which version of NNI are you using?

**Comment by mwsunshine** [comment]
> Nope, I try to run the code you gave to me but due to environmental issues, I have not successfully run your code.
> Could you provide more information about the assertion error such as it fails at which line, and which version of NNI are you using?

If you could look at the file of validation.py, the error occurs at line 64(m_speedup.speedup_model()) 

NNI version:1.9. 

I upload one pruned model for you, which uses fpgm as the pruning method. You should be able to run this model via validation.py directly(Image1 and imag2 can be replaced by randn data)
[mask_raft_100_prune.zip](https://github.com/microsoft/nni/files/5817806/mask_raft_100_prune.zip)

[raft_100_prune.zip](https://github.com/microsoft/nni/files/5817804/raft_100_prune.zip)

**Comment by zheng-ningxin** [comment]
Hi, thanks for the kindly details, could you tell me the shape of image1 and image2 so that I can generate random data as the input?

**Comment by mwsunshine** [comment]
> Hi, thanks for the kindly details, could you tell me the shape of image1 and image2 so that I can generate random data as the input?

I set [368, 768] as the default height and width.

**Comment by mwsunshine** [comment]
> Hi, thanks for the kindly details, could you tell me the shape of image1 and image2 so that I can generate random data as the input?

Hi, is there any progression? Really looking forward to your conclusion. I am just wondering the reason of this error: is it related to the model I used which has the unsupported operation or the way I pruned is wrong.

**Comment by zheng-ningxin** [comment]
I'm a bit busy lately, sorry to reply late。 I run the code and met the following error
```
Traceback (most recent call last):
  File "validation.py", line 69, in <module>
    m_speedup.speedup_model() # where error occurs.
  File "/home/core/znx/nni/nni/compression/pytorch/speedup/compressor.py", line 179, in speedup_model
    _, conv_prune_dim = fix_mask_conflict(self.masks, self.bound_model, self.dummy_input)
  File "/home/core/znx/nni/nni/compression/pytorch/utils/mask_conflict.py", line 50, in fix_mask_conflict
    masks = fix_channel_mask.fix_mask()
  File "/home/core/znx/nni/nni/compression/pytorch/utils/mask_conflict.py", line 250, in fix_mask
    self.model, self.dummy_input, self.traced)
  File "/home/core/znx/nni/nni/compression/pytorch/utils/shape_dependency.py", line 58, in __init__
    model, dummy_input, traced_model)
  File "/home/core/znx/nni/nni/compression/pytorch/utils/shape_dependency.py", line 32, in __init__
    self.build_dependency()
  File "/home/core/znx/nni/nni/compression/pytorch/utils/shape_dependency.py", line 96, in build_dependency
    self.graph.unpack_manually()
  File "/home/core/znx/nni/nni/common/graph_utils.py", line 620, in unpack_manually
    assert len(node.inputs) == len(list(last_cpp.inputs())), errmsg
AssertionError: %13339 : Tensor, %13340 : Tensor, %13341 : Tensor, %13342 : Tensor, %13343 : Tensor = prim::TupleUnpack(%14897)
 Input number: 3 if inconsistent with the output number 5
```
Is this the same as the error you encountered?

**Comment by mwsunshine** [comment]
> I'm a bit busy lately, sorry to reply late. I run the code and met the following error
> 
> ```
> Traceback (most recent call last):
>   File "validation.py", line 69, in <module>
>     m_speedup.speedup_model() # where error occurs.
>   File "/home/core/znx/nni/nni/compression/pytorch/speedup/compressor.py", line 179, in speedup_model
>     _, conv_prune_dim = fix_mask_conflict(self.masks, self.bound_model, self.dummy_input)
>   File "/home/core/znx/nni/nni/compression/pytorch/utils/mask_conflict.py", line 50, in fix_mask_conflict
>     masks = fix_channel_mask.fix_mask()
>   File "/home/core/znx/nni/nni/compression/pytorch/utils/mask_conflict.py", line 250, in fix_mask
>     self.model, self.dummy_input, self.traced)
>   File "/home/core/znx/nni/nni/compression/pytorch/utils/shape_dependency.py", line 58, in __init__
>     model, dummy_input, traced_model)
>   File "/home/core/znx/nni/nni/compression/pytorch/utils/shape_dependency.py", line 32, in __init__
>     self.build_dependency()
>   File "/home/core/znx/nni/nni/compression/pytorch/utils/shape_dependency.py", line 96, in build_dependency
>     self.graph.unpack_manually()
>   File "/home/core/znx/nni/nni/common/graph_utils.py", line 620, in unpack_manually
>     assert len(node.inputs) == len(list(last_cpp.inputs())), errmsg
> AssertionError: %13339 : Tensor, %13340 : Tensor, %13341 : Tensor, %13342 : Tensor, %13343 : Tensor = prim::TupleUnpack(%14897)
>  Input number: 3 if inconsistent with the output number 5
> ```
> 
> Is this the same as the error you encountered?

Thank you for your time and support after a busy time!

It should be the same error. Regardless of the fact that only "AssertionError" is printed out on my side.
