### ISSUE TITLE
following the instruction by nni client document, got exception from the example code.   

### ISSUE THREAD

**Issue by Jar7** [microsoft/nni#3275]
I am following the instruction and trying to run the example code, got an exception:
https://nni.readthedocs.io/en/latest/nnicli_ref.html
Traceback (most recent call last):
  File "client.py", line 4, in <module>
    exp = Experiment()
TypeError: __init__() missing 1 required positional argument: 'tuner'.
Is it expected to create a tuner first?

**Comment by liuzhe-lz** [comment]
NNI v2.0 (in development) has rewritten "nnicli" module and the doc is not yet up-to-date.
Previous version of nnicli class has been renamed to `nni.experiment.LegacyExperiment`.

**Comment by Jar7** [comment]
thanks
