### ISSUE TITLE
 raised ImportError("cannot import name 'erf'",)

### ISSUE THREAD

**Issue by liuanhua110** [microsoft/nni#3280]
**Environment**:
- NNI version:1.9(1.8)
- NNI mode (local|remote|pai):
- Client OS: ubuntu
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:no

:~/automl$ nnictl create --config nni/examples/trials/mnist-tfv1/config.yml

INFO:  expand searchSpacePath: search_space.json to /home/automl/nni/examples/trials/mnist-tfv1/search_space.json 
INFO:  expand codeDir: . to /home/automl/nni/examples/trials/mnist-tfv1/. 
ERROR: Key 'tuner' error:
<nni_cmd.config_schema.AlgoSchema object at 0x7f9f173de4a8>.validate({'builtinTunerName': 'TPE', 'classArgs': {'optimize_mode': 'maximize'}}) raised ImportError("cannot import name 'erf'",)

**Comment by J-shang** [comment]
It seems a little strange, we don't have dependent package named 'erf'. Can you show more information? You can find error message in `~/.local/nnictl/XXX/stderr`. Or maybe reinstall NNI in a clean environment can solve this issue.

**Comment by liuanhua110** [comment]
Thx bro, I found the wrong place
Cause the scipy, the latest scipy hasn't scipy.special.erf T_T
I use the pip install scipy==1.4.1 and it worked. So hard to find where used the erf().

**Comment by J-shang** [comment]
Really thanks for your issue, we will check if we need to limit the version of `scipy`. I will close this issue and if there are any other problems, welcome to communicate anytime.
