### ISSUE TITLE
windows tfv1mnist WEBUI启动成功，总是从waiting直接failed

### ISSUE THREAD

**Issue by 1998yh** [microsoft/nni#3320]
**环境：**win10
           pycharm
           tensorflow-gpu1.14 cuda10.0
**问题：**
![image](https://user-images.githubusercontent.com/42435183/105027034-2e3f2480-5a47-11eb-81ee-cb00a141185e.png)

**配置文件：**
![1611053936(1)](https://user-images.githubusercontent.com/42435183/105025863-cf2ce000-5a45-11eb-8f8d-591c61d059c9.jpg)

**日志：**
![image](https://user-images.githubusercontent.com/42435183/105025972-eff53580-5a45-11eb-8988-5b774682fce8.png)
 
**单独运行mnist_before.py 也有报错，但是运行自己写的其他程序正常(GPU运行)**
![image](https://user-images.githubusercontent.com/42435183/105026462-76117c00-5a46-11eb-96d4-02f2444e650f.png)
![image](https://user-images.githubusercontent.com/42435183/105026512-845f9800-5a46-11eb-8780-8028968d1f97.png)

**不知道是哪里的问题 求大佬们帮帮**

**Comment by J-shang** [comment]
Seems you can not download mnist dataset, maybe your network has some problems. Maybe download from the mirror and specify the dataset file path could work.

**Comment by kvartet** [comment]
closed as it had been no response for more than three months
