### ISSUE TITLE
Errors when running example/nas/cream

### ISSUE THREAD

**Issue by duchengyao** [microsoft/nni#3322]
* `nni/examples/nas/cream/lib/utils/util.py` NameError: name 'logging' is not defined
* `nni/examples/nas/cream/lib/utils/util.py` NameError: name 'torch' is not defined
* `nni/examples/nas/cream/lib/utils/builder_util.py` NameError: name 're' is not defined
* `nni/examples/nas/cream/lib/utils/builder_util.py` NameError: name 'deepcopy' is not defined
* `nas/pytorch/cream/utils.py` RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by Z7zuqer** [comment]
Hi,

Could you provide more details about the environment setting?

Best, 
Hao.

**Comment by duchengyao** [comment]
The error is not due to the difference of environment setting.
It seems the code of cream example is not finished, or no regression test yet. 

Simply import missing modules and change "view" to "reshape" to fix the error. 
see https://github.com/microsoft/nni/pull/3325

**Comment by duchengyao** [comment]
One more issue.
https://github.com/microsoft/nni/blob/v2.0/nni/algorithms/nas/pytorch/cream/trainer.py#L399

`self.accuracy` seems to be `accuracy`

**Comment by duchengyao** [comment]
Some function is not defined in https://github.com/microsoft/nni/blob/v2.0/nni/algorithms/nas/pytorch/cream/trainer.py

* self.reduce_metrics
* self.distributed
* self.best_children_pool
* self.random_cand

**Comment by Z7zuqer** [comment]
Hi,

1) Different environment may cause the error 'view' and 'reshape'.(Wrong torch version may lead to the error, you should provide your environment details for reference.)

2)Missing packages may be the error use of codes. If you run code exactly as the readme, the error should not occur. Missing packages are included in other python file by recursive importing. You should detail your running procedure so we could know better.

3) *self.accuracy* is  *accuracy*, to fast test the codes, we ignore the validation procedure, this error would be fixed later, thanks.

4)*self.best_children_pool* is not used in training process, you could just L387 to L389.

5)*self.best_children_pool* is the same as 3).

6)*self.random_cand* should be self.current_student_arch

7)*self.distributed* should always be True.

You could take https://github.com/microsoft/Cream as reference for more details.

Best,
Hao.

**Comment by duchengyao** [comment]
Thanks for your reply, 

https://github.com/microsoft/nni/blob/master/nni/algorithms/nas/pytorch/cream/trainer.py#L401
And after convert `metrics = self.reduce_metrics(metrics, self.distributed)` to `metrics = reduce_metrics(metrics)`, the training code will be able to run.
