### ISSUE TITLE
Support tensorboard on webui

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/nni#3323]
**What would you like to be added**:
Add tensorboard: [design v1](https://user-images.githubusercontent.com/69844841/95838351-f5a1f780-0d41-11eb-9897-f5ce121f647d.png) from [this issue](https://github.com/microsoft/nni/issues/2779)

**Why is this needed**:

**Without this feature, how does current nni work**：

**Components that may involve changes**: `webui`, `rest`

**Brief description of your proposal if any**:

**Comment by Gracia-zhang** [comment]
Here's the [UI design of TensorBoard.
[https://www.figma.com/file/Pne01CuIXKG3H43d1bnaVN/0409-Fluent-Web-NNI-Tensorboard-view?node-id=40047%3A6959](url)
![0409-Fluent Web-NNI Tensorboard-view-1-Original Trial Details with tensorboard renew](https://user-images.githubusercontent.com/70793865/114148198-1a230900-994c-11eb-8161-078f93c0bffc.png)
![0409-Fluent Web-NNI Tensorboard-view-2-Tensorboard -comfirm-new](https://user-images.githubusercontent.com/70793865/114148204-1a230900-994c-11eb-8ef9-14d1260494a9.png)
![0409-Fluent Web-NNI Tensorboard-view-3-Tensorboard -comfirm-exist](https://user-images.githubusercontent.com/70793865/114148208-1abb9f80-994c-11eb-8496-cf8f92c01419.png)
![0409-Fluent Web-NNI Tensorboard-view-4-Tensorboard-tensorboards running](https://user-images.githubusercontent.com/70793865/114148213-1b543600-994c-11eb-8f8f-2ee0572bd670.png)
![0409-Fluent Web-NNI Tensorboard-view-5-Tensorboard-tensorboards running more](https://user-images.githubusercontent.com/70793865/114148215-1b543600-994c-11eb-9d7d-4fb8f96044ca.png)
![0409-Fluent Web-NNI Tensorboard-view-6-Tensorboard-tensorboards open](https://user-images.githubusercontent.com/70793865/114148189-17c0af00-994c-11eb-8d60-50174ac1c2c9.png)
![0409-Fluent Web-NNI Tensorboard-view-7-Tensorboard -tensorboards running dropdown](https://user-images.githubusercontent.com/70793865/114148195-198a7280-994c-11eb-865a-2db3522e9828.png)

**Comment by Lijiaoa** [comment]
Close this issue because it had been released on `v2.2`
