### ISSUE TITLE
ModelSpeedup support for Upsample, aten::chunk and aten::exp

### ISSUE THREAD

**Issue by abuvaneswari** [microsoft/nni#3329]
Hello,

I am trying to prune the [DBFace](https://github.com/dlunion/DBFace) model. While I was able to incorporate infer_shape and replace for Hswish and Hsigmoid along the same lines as ReLU, I am completely stuck at the following:
Upsample,
aten::chunk
aten::exp

I can share my code and the pth model files if needed.

**What would you like to be added**:
Shape inference and replacement functions for Upsample, aten::chunk and aten::exp

**Why is this needed**:
For pruning [DBFace](https://github.com/dlunion/DBFace) model 

**Without this feature, how does current nni work**：
Throws error message of:
File "/home/tfs/venv_dbface_nni/lib/python3.6/site-packages/nni/compression/pytorch/speedup/compressor.py", line 171, in replace_compressed_modules
    raise RuntimeError("Has not supported replacing the module: `{}`".format(m_type))
RuntimeError: Has not supported replacing the module: `Upsample`

And when I used a try-except around line 171 in compressor.py, I find that shape inference is not supported for aten::chunk and aten::exp as well.

**Components that may involve changes**:
Modules under nni/compression/pytorch/speedup

**Brief description of your proposal if any**:

**Comment by abuvaneswari** [comment]
Attaching:
1) A sample model compression code. git clone the DBFace repo, install torch & torchvision and run this code from the top directory.
2) The original model pth file (dbface.pth)
3) model_masked.pth
4) mask.pth
Save the pth files in the top directory as well.

[NNI_git_issue.zip](https://github.com/microsoft/nni/files/5863877/NNI_git_issue.zip)

**Comment by JohnsenJiang** [comment]
RuntimeError: Has not supported infering output shape from input shape for module/function: `aten::exp`, .aten::exp.44

nni can't support for torch.exp(), thanks for your reply.

class ExpTestNet(nn.Module):
    def __init__(self):
        super(ExpTestNet, self).__init__()
        self.backbone = models.vgg16_bn(pretrained=True).features

    def forward(self, x):
        x = self.backbone(x)
        return torch.exp(x)

**Comment by zheng-ningxin** [comment]
Hi, thanks for the valuable feedback, aten::exp has already been supported in this branch https://github.com/microsoft/nni/pull/3462？ Please have a try and let me know if there is some problem.

**Comment by JohnsenJiang** [comment]
Thanks for your excellent works. aten::exp support problem has been solved.
