### ISSUE TITLE
[Enhancement] Add support for Jupyter notebooks

### ISSUE THREAD

**Issue by tczhangzhi** [microsoft/nni#3338]
**What would you like to be added**:
Greeting, I believe NNI is one of the best practices of AutoML tools and it has saved my day to search for better network architecture in my research field. However, it would be better if we can add some support to make NNI compatible with jupyter notebooks, which are light-weight and friendly with agile software development.

**Why is this needed**:
**[Competition]** Notebooks are widely used in the machine learning contest community (e.g. kaggle). It is very efficient for sharing ideas, disseminating baseline methods, and providing reproducible results. I am sure they need some AutoML tools like NNI too.
**[Research]** In the first stage of my research, I would like to try different ideas and get a baseline to move on. I would like to utilize AutoML to build a strong baseline for me. But I don't want to struggle to manage a huge project because most of them would be cleaned up later.
**[Production]** I am not familiar with the current best practice of the production environment but to the best of my knowledge, there are many enterprises and teams that utilize notebooks to manage their projects. It would be much better if NNI can be compatible with jupyter notebooks.

**Without this feature, how does current nni work**：
1. In the current version of NNI, there are some bugs that only occur on jupyter notebook. Solving these problems is an urgent task.
2. Then, an example project is need to provide the best practice in jupyter notebooks.
3. For further steps, it would be better if the statistics and visualization results can be provided on jupyter notebooks in a more user-friendly way. Some other project already works on it, e.g. [pipelineprofiler](https://pypi.org/project/pipelineprofiler/).

**Components that may involve changes**:
I am struggling to make a way to utilize the NNI in jupyter notebooks. I would like to summary my issues on this topic. And here is the very first [PR](https://github.com/microsoft/nni/pull/3337) to clean bugs during an end-to-end experiment.

**Comment by J-shang** [comment]
HI @tczhangzhi , thanks for your suggestion, we support python API can be used in Jupyter notebook in v2.1, here is the usage case:
https://nni.readthedocs.io/en/stable/Tutorial/python_api_start.html
https://nni.readthedocs.io/en/stable/Tutorial/python_api_connect.html

**Comment by tczhangzhi** [comment]
Well done, dude! I have already applied it to my research project and it works well!
