### ISSUE TITLE
Enable optional Pod Spec for FrameworkController platform

### ISSUE THREAD

**Issue by mbu93** [microsoft/nni#3350]
**What would you like to be added**:
For the FrameworkController based training platform, NNI is missing an option to use the pod spec field. It would be great if one could optionally define this part of the FrameworkController config within the trial config. 

**Why is this needed**:
There is various corner case scenarios, such as adding security context / capabilities to a certain trials container or dealing with its resources, but in front of all this way one would have better control over storage operations. Especially when using NNI with a pipeline system (such as argo), the nfs based approach doesn't feel right, as nnictl is running from within a Pod and thus bypasses kubernetes' native storage handling. In addition, regardless of whether there is a central k8s nnictl service or a single instance (pod) of it per experiment, the need to be run in privileged mode (for the nfs mount part) seems like a potential security vulnerability to me. I understand that automatically creating volumes can easily mess up a cluster's storage management and thus needs to be done carefully, but an option to choose this exact approach would be great. In my very own scenario, I would like to upload data to a predefined pvc and access it from within each trial later, especially to avoid the overhead caused by the initial file copy processes in case of very large datasets (e.g. MRI imaging sets).

**Without this feature, how does current nni work**：
Currently, nni launches pods according to a fixed pod template, which can only be edited by the user in a very limited manner (image, name, cpuNum, gpuNum) 

**Components that may involve changes**:
Various changes to the frameworkcontroller's service would need to be done. This includes in front of all the TrainingService.ts.

**Brief description of your proposal if any**:
My proposal would be, to simple parse and pass the already available "pod: spec" field of the FrameworkController, if specified by the user. I would also be willing to implement it on my own, but hesitated to directly file a PR, as my time is very limited rn and I wanted to ask politely if such a change could be considered at all before starting to waste a lot of time. 

----

This is a great project! Thanks for spending so much effort and taking the time for investigating proposals such as mine :)

**Comment by SparkSnail** [comment]
Hi @mbu93 , your proposal is good and reasonable. For some advanced users, they do have some customized requirements for pod template, while NNI only support simplified configuration. In fact, in PAI training service, NNI has implemented such kind of functionality to let users provide their own job template, and NNI will read the job template and merge the job template with NNI's own generated job template, refer https://github.com/microsoft/nni/blob/master/docs/en_US/TrainingService/PaiMode.rst#trial-configurations, https://github.com/microsoft/nni/blob/master/ts/nni_manager/training_service/pai/paiTrainingService.ts#L438.  
For FrameworkController mode, NNI could also provide a configuration like `frameworkConfigPath` for users to specify their local frameworkcontroller pod template, and merge with NNI's pod template for their advanced configuration.

**Comment by mbu93** [comment]
Hi @SparkSnail, thanks for the quick reply! I didn't notice PAI already offers a similar functionality as my proposed one. Nice! I'm going to have a look at it and open a PR as soon as I have something working :)

**Comment by mbu93** [comment]
Hi @SparkSnail, 
I've created a PR covering the changes as discussed. It got quite more complex than I expected, as a large part of the frameworkcontroller training service kind of was "hard-coded" to use the generated config. I thus didn't (yet) pay attention to unit testing and documentation, so the changes can be discussed first. I also realized that there seems to be no certain linting rules or the typescript code? I am using prettier with eslint plugin and it kind of went full amok on the first commit. Therefore, please excuse the formatting changes, I tried to keep them as few as possible.
The changes are working with the mnist-pytorch example on my k8s 1.18 cluster.

**Comment by SparkSnail** [comment]
Hi @mbu93,
I've reviewed your PR, and the code is pretty good. I've given some comments, we can discuss details in PR. For linting rules, please follow https://github.com/microsoft/nni/blob/master/ts/nni_manager/.eslintrc.

**Comment by kvartet** [comment]
Hello @mbu93, the feature has been released in NNI v2.2, so I will close the issue, feel free to reopen it if you think it is active. Thanks for your contribution again!
