### ISSUE TITLE
GPU Memory-Usage not change when batchsize has changed

### ISSUE THREAD

**Issue by SicleBoypy** [microsoft/nni#3369]
trial:
  command: python3 mnist.py --epochs 40
  codeDir: .
  gpuNum: 2
localConfig:
  useActiveGpu: true

when experimenting for the mnist-pytorch，I set gpuNum to 2. But GPU1 seem not work.
===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   34C    P0    56W / 300W |   1476MiB / 32510MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:1B:00.0 Off |                    0 |
| N/A   36C    P0    44W / 300W |      3MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:3D:00.0 Off |                    0 |
| N/A   38C    P0    55W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:3E:00.0 Off |                    0 |
| N/A   35C    P0    56W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  Off  | 00000000:88:00.0 Off |                    0 |
| N/A   34C    P0    56W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |

another question is that bathsize has changed, but GPU0 Memory-Usage seem not change . Why?

**Comment by ultmaster** [comment]
You are not using two GPUs because you are not using DataParallel. Please see PyTorch docs for details.
