### ISSUE TITLE
search_space.json file can't add comments

### ISSUE THREAD

**Issue by szhang963** [microsoft/nni#3373]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**
您好我发现search_space.json无法添加注释，因为我想暂时取消某个参数的搜索，但想保留该字段以备下次可以直接取消注释就能添加该搜索字段，但是无法添加注释就导致我必须删除此字段，有没有解决方法呢？或者您可以改进一下这一点？
**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:2.0
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?:
- is running in docker?:

**Comment by liuzhe-lz** [comment]
Next release (v2.1) will support this feature.
Search space file will be parsed with YAML parser and therefore will support comment.
Thanks for your advice.

**Comment by zs963048949** [comment]
thanks



---Original---

**Comment by scarlett2018** [comment]
> Next release (v2.1) will support this feature.
> Search space file will be parsed with YAML parser and therefore will support comment.
> Thanks for your advice.

@liuzhe-lz - just to double check, this is supported in the released v2.1 and later versions? thanks.

**Comment by kvartet** [comment]
hello @szhang963, your feature request had been supported. You can use v2 config with inline search space and add comments as you want, refer [here](https://nni.readthedocs.io/en/latest/reference/experiment_config.html#local-mode-inline-search-space).
