### ISSUE TITLE
Publish new release to Pypi

### ISSUE THREAD

**Issue by snoopysecurity** [microsoft/nni#3380]
Hi, Is it possible to publish a new release of nni to pypi (https://pypi.org/project/nni/#description) with changes that was made for the https://github.com/microsoft/nni/pull/3311 pull request?

**Comment by Anon-Artist** [comment]
Yeah we are also waiting 😄

**Comment by QuanluZhang** [comment]
@snoopysecurity @Anon-Artist thanks for raising your request. Does nightly build solve your problem, we have nightly build but have not exposed to users. Or, in your scenario you need official release?

**Comment by snoopysecurity** [comment]
The vulnerability that the PR https://github.com/microsoft/nni/pull/3311 fixed was reported to Snyk Vulnerability disclosure program (https://snyk.io/vuln) We wanted to release an advisory crediting the reporter, as well as tell current users of `nni` to update to the latest version where this issue is fixed. So I mainly wanted a a pypi official release they could upgrade to (https://pypi.org/project/nni/#history) Am I right in thinking the nightly builds are not in pypi?

Also am I right to assume that Microsoft Security Response Center (MSRC) (https://msrc.microsoft.com/create-report) can assign a CVE to this issue?

**Comment by QuanluZhang** [comment]
@snoopysecurity thanks, got the scenario. We will release a new version soon.

**Comment by Anon-Artist** [comment]
Any update @QuanluZhang  😊

**Comment by QuanluZhang** [comment]
@Anon-Artist v2.1 will be released on March 8th.

**Comment by Anon-Artist** [comment]
> @Anon-Artist v2.1 will be released on March 8th.

Thats cool 😊

**Comment by B3EF** [comment]
hi @QuanluZhang did the new version have released 
?

**Comment by QuanluZhang** [comment]
@B3EF , will release today, after several hours. sorry for one day delay.

**Comment by Anon-Artist** [comment]
No issues 😀
Hope you see this @snoopysecurity

**Comment by snoopysecurity** [comment]
Hi, yep, thanks for letting me know. I'll close this issue.

**Comment by B3EF** [comment]
HI @QuanluZhang can we get a CVE id For this.

**Comment by Anon-Artist** [comment]
@QuanluZhang Snyk.io has recognized this vulnerability as https://snyk.io/vuln/SNYK-PYTHON-NNI-1073630 so can we get a CVE for this.

**Comment by QuanluZhang** [comment]
@Anon-Artist @B3EF , sorry, I am not familiar with Snyk.io. could you give me some context about CVE and how to do it. maybe some links and guidance?

**Comment by B3EF** [comment]
hi @snoopysecurity can you please explain  the criteria to be done to @QuanluZhang  ,to assign a CVE-id for us .

**Comment by snoopysecurity** [comment]
Hey, indeed I can help @QuanluZhang Snyk can't help with a CVE since its a microsoft product/software, Reading https://cve.mitre.org/cve/request_id.html, you should be able to assign a CVE by contacting `secure@microsoft.com` or directly MITRE through https://cveform.mitre.org/

All you need to do is contact one of the above authorities and provide the details, you can just copy and paste the details here https://snyk.io/vuln/SNYK-PYTHON-NNI-1073630 (fixed version, github commit, vulnerability information etc etc) and they will assign a CVE for you. hope this helps

**Comment by scarlett2018** [comment]
@qfyin @liuzhe-lz - Has the problem been solved? may we close the issue? thanks.

**Comment by Anon-Artist** [comment]
Yes sure the problem is fixed 
Thank you 😊

**Comment by kvartet** [comment]
I will close this issue as this problem had been solved, feel free to reopen it.
