### ISSUE TITLE
AutoCompression Class

### ISSUE THREAD

**Issue by MohamedAliRashad** [microsoft/nni#3385]
## What would you like to be added ?
A unified class for Automatic Compression (Pruning & Quantization).

## Why is this needed ?
Ease of Usage (and all the required blocks are already there).

## Without this feature, how does current nni work ?
The closest solution for something like this is this [script](https://github.com/microsoft/nni/blob/master/examples/model_compress/pruning/auto_pruners_torch.py), but it's still only for pruning and doesn't even use all purners.

## Brief description of my prposal
Simple Class called `AutoCompresser` that can be used like this
```
from nni.compression.pytorch import AutoCompressor

comp = AutoCompressor(pruners=["LevelPruner", "AGPPruner"], quantizers="All", training_dataset=training_dataloader, testing_dataset=testing_dataloader, evaluation_metrics=MSELoss())
model = comp(model, progress_bar=True) 
```

**Comment by J-shang** [comment]
Thanks for your issue. It is a great idea to make using pruner and quantizer more convenient. We will discuss the specific implementation plan and more ways to combine pruner and quantizer in later versions. We will continue to update the improvement plan under this issue and welcome to discuss together.

**Comment by MohamedAliRashad** [comment]
I will start a PR to work on this feature, feel free to join anytime @J-shang

**Comment by kvartet** [comment]
@J-shang, is AutoCompression Framework supported in NNI v2.3 satisfy the user's need? if it is, I will close this issue~

**Comment by J-shang** [comment]
> @J-shang, is AutoCompression Framework supported in NNI v2.3 satisfy the user's need? if it is, I will close this issue~

Yes, AutoCompression Framework is partial what this issue needs, and we need to improve sparsity recommendations in the future.
