### ISSUE TITLE
Auto-find port when port is occupied

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#3394]
It can be quite annoying to see the following message when starting the experiment.

```
port already in use.
```

Sometimes the port is written in the code and manually changing it is neither easy nor efficient.

Jupyter has the following feature when port is occupied, which looks charming to me.

```
[I 16:14:15.237 NotebookApp] The port 7788 is already in use, trying another port.
[I 16:14:15.237 NotebookApp] The port 7789 is already in use, trying another port.
```

Tensorboard also has a similar feature. Maybe we can implement a similar one.

**Comment by J-shang** [comment]
I implemented a `getFreePort()` function if you need this in `ts`. BTW, I need this because I need a port to start tensorboard, how can I auto-find port in tensorboard?

https://github.com/J-shang/nni/blob/6888b4c1476c3774548042100c901b85ea9826c8/ts/nni_manager/core/nniTensorboardManager.ts#L206
