### ISSUE TITLE
wrong field name in ExperimentConfig, "accessor" should be "assessor"

### ISSUE THREAD

**Issue by ByronCHAO** [microsoft/nni#3415]
**Environment**:
- NNI version: 2.0
- NNI mode (local|remote|pai): local
- Client OS: Ubuntu 20.10
- Server OS (for remote mode only):
- Python version: 3.8.5
- PyTorch/TensorFlow version: pytorch 1.9.0a+a62b0de
- Is conda/virtualenv/venv used?: conda 4.9.2
- Is running in Docker?: No

**Log message**:
 - nnimanager.log: None
 - dispatcher.log: None
 - nnictl stdout and stderr:
```
WARNING: Validation with V1 schema failed. Trying to convert from V2 format...
ERROR: Conversion from v2 format failed: ValueError('ExperimentConfig: Unrecognized fields assessor')
ERROR: Config in v1 format validation failed. KeyError('trial')
```

**What issue meet, what's expected?**:
In `ExperimentConfig`, field `accessor`  should be `assessor`.

**How to reproduce it?**: 
A V2 config with 'assessor'

**Additional information**:
Fix by renaming all `accessor` in `nni.experiment.config.common.py` to `assessor`.
There are some `accessor` in doc as well.

**Comment by scarlett2018** [comment]
Thanks @ByronCHAO for the feedback, would you like to contribute a PR to fix the issue? We are really welling to have your contributions on codes (as you already went so far, found the root cause =) ).
