### ISSUE TITLE
Question about cream nas

### ISSUE THREAD

**Issue by AliCloud-PAI** [microsoft/nni#3417]
When I run the cream nas with pytorch==1.7.1, problem appears:
  File "/app/nni_lib/trainer.py", line 294, in _calculate_2nd_gradient
    grad_outputs=grad_student_val,
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 192, in grad
    inputs, allow_unused)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3136, 1]], which is output 0 of TBackward, is at version 5; expected version 4 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

The second grad calculation may have some problem?
        grad_teacher = torch.autograd.grad(
                students_weight[0],
                self.model.rand_parameters(teacher_cand, self.pick_method=='meta'),
                grad_outputs=grad_student_val,
            )

**Comment by Z7zuqer** [comment]
Hi,

This problem is caused by installing different versions of pytorch. You could reinstall pytorch==1.2.1 as listed in *requirements*, pytorch1.7 is not supported for now.

Best,
Hao.

**Comment by penghouwen** [comment]
@AliCloud-PAI  Hi, I am wondering whether you have solved the issue? Pls feel free to contact us. Thanks~

**Comment by yiwuyao3863** [comment]
The problem is solved by using PyTorch 1.2.1, THX:)

**Comment by AliCloud-PAI** [comment]
The problem is solved by using PyTorch 1.2.1, THX:)
