### ISSUE TITLE
Use of itertools.cycle(dataloader) causes transforms on dataset not working after first iteration. Found in nni/nni/algorithms/nas/pytorch/enas/trainer.py

### ISSUE THREAD

**Issue by NazgulLee** [microsoft/nni#3428]
Bug in enas trainer. Found in nni/nni/algorithms/nas/pytorch/enas/trainer.py.

itertools.cycle() uses elements from the saved copy when the iterable is exhausted, causing transforms on dataset not working after first iteration on dataloader, causing overfit。

![image](https://user-images.githubusercontent.com/12666864/110116693-d1c77700-7df2-11eb-9a5a-ab71dc4c1f5f.png)

![image](https://user-images.githubusercontent.com/12666864/110117021-4ac6ce80-7df3-11eb-8574-a3f4571f2b43.png)

**Comment by ultmaster** [comment]
Nice catch. Might need to wrap the dataloader in some customized cycler. You can submit a fix if you want.

**Comment by NazgulLee** [comment]
> Nice catch. Might need to wrap the dataloader in some customized cycler. You can submit a fix if you want.

OK
