### ISSUE TITLE
ModuleNotFoundError: No module named 'nni.retiarii.oneshot'

### ISSUE THREAD

**Issue by serser** [microsoft/nni#3440]
**Environment**:
- NNI version: 2.0
- NNI mode (local|remote|pai): local
- Client OS: centos
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: 1.6
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: yes

**Log message**:
 - nnimanager.log:  n/a
 - dispatcher.log: n/a
 - nnictl stdout and stderr: n/a
 

**What issue meet, what's expected?**:
I am following the tutorial here https://nni.readthedocs.io/en/latest/NAS/DARTS.html, it seems `oneshot` is not registered as a module. 
```
NAME
    nni.retiarii

PACKAGE CONTENTS
    codegen (package)
    converter (package)
    debug_configs
    execution (package)
    experiment
    graph
    integration
    integration_api
    mutator
    nn (package)
    operation
    operation_def (package)
    strategies (package)
    trainer (package)
    trial_entry
    utils

SUBMODULES
    api
    interface
    listener

DATA
    MetricData = typing.Any

FILE
    /workdir/serser/nni/venv-nni/lib/python3.8/site-packages/nni/retiarii/__init__.py
```

**How to reproduce it?**: 
```
cp -r examples/nas/darts /path/to/my_darts && cd /path/to/my_darts
python3 search.py
```
**Additional information**:

**Comment by ultmaster** [comment]
Please install v2.1
