### ISSUE TITLE
Add Htop to the Webui

### ISSUE THREAD

**Issue by MaximilianArnold** [microsoft/nni#3441]
Hi, 

since we are doing NN there could be heavy datasets which explode the ram and thus it would be nice to see the current ram load/cpu gpu/load  in the webui.

**What would you like to be added**:
see top
**Why is this needed**:
It is a comfort feature

**Without this feature, how does current nni work**：
It does not show it
**Components that may involve changes**:

**Brief description of your proposal if any**:
Since its standard html you could easily add it.

**Comment by scarlett2018** [comment]
Thanks @MaximilianArnold  for raising the new feature request.

**Comment by scarlett2018** [comment]
@Lijiaoa may you suggest how big the effort for **prototyping** this request? would like to discuss this with team based on the prototype if it is simple one.

**Comment by Lijiaoa** [comment]
Maybe 3-5 days. First we should find this message(cpu/gpu), and then UI should design where to show this message. Also, we should add rest api for this.

Best wishes,
Lijiao

**Comment by QuanluZhang** [comment]
@MaximilianArnold , this is a valid request. There will be a lot of work to support this feature when there are many different training services. For training services like AML, OpenPAI, they have collected such information (CPU/GPU/Mem/Network utilization) and displayed on their WebUI. Following "separate of concern", it is a good design choice for NNI to link each trial job to their corresponding web page in the training service. This has been supported by NNI for training services such as OpenPAI. For the training services (i.e., local, remote) which are implemented by NNI, it might be good to collect those information and display on NNI WebUI. We will put this feature in our backlog, and encourage external contribution on this feature
