### ISSUE TITLE
[Retiarii] mnist/test.py: Error on trainer.fit

### ISSUE THREAD

**Issue by duchengyao** [microsoft/nni#3452]
- NNI version: latest

I tried to run CLI mode on `nni/test/retiarii_test/mnist/test.py` by adding some code blow, but error raised:

* `trainer.fit(NET)` : ```TypeError: __init__() missing 1 required positional argument: 'hidden_size'```
* `trainer.fit(base_model)` :  RuntimeError: mat1 and mat2 shapes cannot be multiplied (100x800 and 128x10)

Modify `base_model = Net(128)` to `base_model = Net(800)` seems to be able to run.

More importantly, I noticed [nn.LayerChoice](https://github.com/microsoft/nni/blob/master/test/retiarii_test/mnist/test.py#L19) is not take effect in the CLI mode (without RetiariiExperiment). The output on fc1 is the same as input.

Is there any way to change mnist.test to CLI mode?

Regards,

**Comment by J-shang** [comment]
Hi, do you mean that CLI mode uses `nnictl`? Retiarii currently does not support `nnictl`, and `RetiariiExperiment` is required if you want to use Retiarii. If you want to use `nnictl`, you can use the old NAS version, https://nni.readthedocs.io/en/stable/NAS/Overview.html .

> Modify `base_model = Net(128)` to `base_model = Net(128)` seems to be able to run.

And what is this mean?

**Comment by duchengyao** [comment]
Thanks for your reply.

I mean run this demo in command line mode, not running webserver or nnicli.
I uploaded modified script in https://github.com/duchengyao/nni/blob/master/test/retiarii_test/mnist/test.py

**Comment by J-shang** [comment]
Hi, what's the reason you don't want to use the webserver? all kind of launching nni experiment ways will start webserver.

@ultmaster please help if we can use `trainer` without `RetiariiExperiment`?

**Comment by ultmaster** [comment]
Yes you can. The main reason is that the base model is just a "base model". It's very possible that the base model is not a runnable-model before running any mutation and thus cannot be trained. If you want to debug a trainer (I believe it's called evaluator now), sure you can use `trainer.fit`. But keep in mind that this API is meant to be internal and subject to change in 1-2 releases.

**Comment by duchengyao** [comment]
It's convenience to visualize parameters, metrics of NAS on webserver, but the webserver prevents me from understanding how the algorithm works.

I'm interested in your new algorithm retiarii, and tried to understand its implementation at the code level. When I read the code, some threads unrelated to the algorithm confused me. If there is a way to run MNIST demo directly without web server, it will be very helpful to me.

BTW, following [retiarii/experiment/pytorch.py](https://github.com/microsoft/nni/blob/master/nni/retiarii/experiment/pytorch.py#L202), webserver is not required on oneshot nas algorithm?

**Comment by ultmaster** [comment]
For your first point, if we make the strategy running in the main thread, will it be more straightforward to you?

For your second point, oneshot experiment is just simply running trainer.fit without messy multi-trial issues. Therefore webserver is not needed.

**Comment by duchengyao** [comment]
It will be great helpful to me if the strategy is running in the main thread.

Thanks for your reply ^_^

**Comment by JiaqingFu** [comment]
@ultmaster  is it available now？

> For your first point, if we make the strategy running in the main thread, will it be more straightforward to you?
> 
> For your second point, oneshot experiment is just simply running trainer.fit without messy multi-trial issues. Therefore webserver is not needed.

**Comment by ultmaster** [comment]
Not really. As we have a lot of features going on, looks like it will take 1-2 months, probably longer.
