### ISSUE TITLE
{"error":"ENOENT: no such file or directory, open '/home/wyrx/textcla/logs/5m78AlYQ/trials/sbm7r/stderr'"}

### ISSUE THREAD

**Issue by LilAnthony123** [microsoft/nni#3463]
Hello, I have set logDir in config.yaml, that's it

authorName: wyrx
experimentName: textcla
logDir: logs
trialConcurrency: 2
maxExecDuration: 100h
maxTrialNum: 500
trainingServicePlatform: local
searchSpacePath: ./space.json

There is only db and log under "/home/wyrx/textcla/logs/5m78AlYQ/", no trials

**Comment by SparkSnail** [comment]
Hi @LilAnthony123, please set `logDir` as an absolute path value and try again.

**Comment by kvartet** [comment]
hello @LilAnthony123, could you follow this and update the status of this issue? Thank you!

> Hi @LilAnthony123, please set `logDir` as an absolute path value and try again.

**Comment by LxzGordon** [comment]
> hello @LilAnthony123, could you follow this and update the status of this issue? Thank you!
> 
> > Hi @LilAnthony123, please set `logDir` as an absolute path value and try again.

I have the same problem and doing so won't help

**Comment by SparkSnail** [comment]
> > hello @LilAnthony123, could you follow this and update the status of this issue? Thank you!
> > > Hi @LilAnthony123, please set `logDir` as an absolute path value and try again.
> 
> I have the same problem and doing so won't help

please run experiment with --debug mode and provide nniManager.log here.

**Comment by kaidiwang** [comment]
> > > hello @LilAnthony123, could you follow this and update the status of this issue? Thank you!
> > > > Hi @LilAnthony123, please set `logDir` as an absolute path value and try again.
> > 
> > 
> > I have the same problem and doing so won't help
> 
> please run experiment with --debug mode and provide nniManager.log here.

I have a similar issue. It would be great if you could help with it. Here is the nniManager.log I got with debug mode.
[nnimanager.log](https://github.com/microsoft/nni/files/9059649/nnimanager.log)

The dispatcher.log is also changed with debug mode. Here is it if you need it.
[dispatcher.log](https://github.com/microsoft/nni/files/9059653/dispatcher.log)

**Comment by kaidiwang** [comment]
The issue is solved after I move the files from cloud drive to the local machine.
