### ISSUE TITLE
RuntimeError: Has not supported infering output shape from input shape for module/function: `prim::TupleUnpack`, .prim::TupleUnpack.344

### ISSUE THREAD

**Issue by faj2007** [microsoft/nni#3467]
**Environment**:
- NNI version:2.1
- 
Error when in run model speedup. anyone has an idea?
- NNI mode (local|remote|pai):
- Client OS:ubuntu 18.04
- Server OS (for remote mode only):
- Python version:3.6
- PyTorch/TensorFlow version:1.6
- Is conda/virtualenv/venv used?:no
- Is running in Docker?:no

**Comment by AnonymousPaperSubmit** [comment]
Hi @faj2007,  could you please show us the code snippet of the model so that we can reproduce the problem you met?

**Comment by colorjam** [comment]
Hi @faj2007, could you please provide the code snippet of your model?

**Comment by xuezu29** [comment]
Hi, I encountered the same problem. Have you solved it? ths a lot!

**Comment by zheng-ningxin** [comment]
Hi all, thanks for the valuable feedback and sincerely sorry for the late reply.
There is a same issue on the `TupleUnpack`, please reference it for more details.
https://github.com/microsoft/nni/issues/3645
Thanks~
