### ISSUE TITLE
Can I use NNI to train parameters for doc2vec model?

### ISSUE THREAD

**Issue by jexterliangsufe** [microsoft/nni#3469]
**Environment**:
- NNI version:
- NNI mode (local|remote|pai):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by QuanluZhang** [comment]
yes, you can use NNI to tune hyperparameters of doc2vec model.

**Comment by jexterliangsufe** [comment]
> yes, you can use NNI to tune hyperparameters of doc2vec model.

Thank you!
