### ISSUE TITLE
How to use a self-defined docker image in AML mode?

### ISSUE THREAD

**Issue by hjptriplebee** [microsoft/nni#3470]
I have a self-defined docker image under an azure repository which is not public. To access the repository, some image registry details are needed. How can I provide these registry info or does NNI support to run exp in AML mode with private docker image?

**Comment by SparkSnail** [comment]
No, NNI does not support setting private registry in AML mode. You could add your registry configuration logic at [here](https://github.com/microsoft/nni/blob/master/ts/nni_manager/config/aml/amlUtil.py#L33), and follow [this](https://nni.readthedocs.io/en/latest/Tutorial/InstallationLinux.html#build-wheel-package-from-nni-source-code) to build NNI from source code in your machine.

**Comment by hjptriplebee** [comment]
Thanks
