### ISSUE TITLE
The duration of the experiment is inconsistent with the duration of the trials

### ISSUE THREAD

**Issue by kvartet** [microsoft/nni#3480]
**Environment**:
- NNI version: v2.1
- NNI mode (local|remote|pai): aml
- Client OS: ubuntu
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: yes

The duration of the trials is longer than the duration of the experiment.

![image](https://user-images.githubusercontent.com/48014605/112594735-53378580-8e44-11eb-857c-c4eb7e8e4919.png)

![image](https://user-images.githubusercontent.com/48014605/112594751-592d6680-8e44-11eb-917f-cb53a16eb7ba.png)

By the way, when the NNI versions are not consistent, there is no error message in the nnimanager.log

**Comment by SparkSnail** [comment]
Can not reproduce trial time issue.
