### ISSUE TITLE
The text is not displayed completely when searching in the right column

### ISSUE THREAD

**Issue by kvartet** [microsoft/nni#3484]
**Environment**:
- NNI version: v2.1

The text is not displayed completely when searching in the right column (Search Space, Config, and Log Files).

![image](https://user-images.githubusercontent.com/48014605/112614977-df55a700-8e5c-11eb-82c1-18f93d04ce30.png)

**Comment by kvartet** [comment]
@Lijiaoa

**Comment by Lijiaoa** [comment]
Thanks for raising this issue. Looks like `className repeat` cause that. will fix in v2.2

**Comment by kvartet** [comment]
closed as it had been fixed.
