### ISSUE TITLE
How to review log after trial? 

### ISSUE THREAD

**Issue by Roy-Kid** [microsoft/nni#3486]
After the experiment complete, I get a lot of logs and data in the nni-experiments fold. How can I use the webUI to review the details? I can not find a command to reload those JSON and log.

**Comment by kvartet** [comment]
You can use [this command](https://nni.readthedocs.io/en/latest/Tutorial/Nnictl.html#view) to view a stopped experiment.

If you want to view the trials' log, please refer to [here](https://nni.readthedocs.io/en/latest/Tutorial/WebUI.html#view-trials-status).

**Comment by Roy-Kid** [comment]
Thanks for your rapid reply and create such a brilliant code. 
When I cd to the nni-experiement, I type the ``` nnictl view f7pr8v2y ``` then error raise.
It told me:
TypeError: expected str, bytes or os.PathLike object, not NoneType

My python is 3.8 and nni is latest 2.1. How can I fix this? 

Thanks in advance!

**Comment by scarlett2018** [comment]
@SparkSnail - do you need more info or log from @Roy-Kid ?

**Comment by kvartet** [comment]
hello @Roy-Kid , seem it had been fixed in the previous version, could you upgrade the NNI version and try again? Thank you :)
