### ISSUE TITLE
how to customize dafault metric to multiple metrics

### ISSUE THREAD

**Issue by JohnGithub917** [microsoft/nni#3504]
**What would you like to be added**: web ui should be able to show more metircs

**Why is this needed**: to show more information

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by QuanluZhang** [comment]
@JohnGithub917 , nni supports customizing metrics. you can pass a dict to `nni.report_final_result` and `nni.report_intermediate_result`. if you are still using nni built-in tuners, there must be a key "default" in this dict, other keys can be freely customized. If you are using your customized tuner, then the dict could contain any content.

webui supports showing customized metrics. you can use the add/remove columns button on webui to how your customized metrics.

**Comment by JohnGithub917** [comment]
@QuanluZhang , i passed ```d = {'i': i, 'time': test_acc}  nni.report_intermediate_result(d)```, i used add/remove buttons in webui m but i can't see these values. I checked all the boxes in ```Customize columns```. 
nni version: 2.1

**Comment by QuanluZhang** [comment]
@JohnGithub917 , yes, the add/remove button only support the keys reported by `nni.report_final_result`. If you want to view the keys you added in the intermediate result, you can click the button at the end of trial row in the trial table,  to view intermediate result, it is supposed to show the curves for "i" and "time".

**Comment by JohnGithub917** [comment]
@QuanluZhang , you mean the little curve button under ```Operation``` ? But nothing shows.

**Comment by QuanluZhang** [comment]
@JohnGithub917 , yes.

@Lijiaoa could you help check this issue? thanks.

**Comment by Lijiaoa** [comment]
@JohnGithub917 We do not support this feature in versions after v1.7...

**Comment by JohnGithub917** [comment]
@Lijiaoa , ok... This seems to be an useful feature, may i know why it's not supported ?

**Comment by Lijiaoa** [comment]
Because I think few people care about `intermediate dict result`, they care more about `final dict result`. But you thought it's an useful feature, so we consider adding this feature after `v2.2`. Thanks for your feedback.

**Comment by JohnGithub917** [comment]
@Lijiaoa Thanks for the information. Closing this issue.
