### ISSUE TITLE
*** NotImplementedError: Deep copy doesn't work for mutables.

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#3523]
when I try to `copy.deepcopy` a model designed by nas mutables, it alerts `*** NotImplementedError: Deep copy doesn't work for mutables.`

**Comment by ultmaster** [comment]
This is by design. Deep copy on mutables will cause problems thus we forbid it.

And we are not maintaining the old versions of NAS any more. Please try to use Retiarii if possible.
