### ISSUE TITLE
Running trial is still timing when view and experiment status always is INITIALIZED

### ISSUE THREAD

**Issue by SparkSnail** [microsoft/nni#3529]
**Environment**:
- NNI version: v2.1
- NNI mode (local|remote|pai): local
- Client OS: Linux
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
Trials is still calculating running time in review mode, and experiment is still in `Initialized` state.
**How to reproduce it?**: 

**Additional information**:
![image](https://user-images.githubusercontent.com/48014605/115042115-c2653e80-9f05-11eb-8c01-b973970c7158.png)

![image](https://user-images.githubusercontent.com/48014605/115042646-48818500-9f06-11eb-828b-694e2984b768.png)

![image](https://user-images.githubusercontent.com/22682999/114648749-e7915b80-9d11-11eb-9620-589ad9b9ffca.png)

**Comment by kvartet** [comment]
When experiment status is INITIALIZED, several progress bars and texts are all blue. But they are all green in the DONE state, which may make users very confused...

**Comment by J-shang** [comment]
change `INITIALIZED` to `VIEWED` when in view mode #3545

**Comment by Lijiaoa** [comment]
It had been fixed on `v2.2`

**Comment by J-shang** [comment]
> It had been fixed on `v2.2`

![image](https://user-images.githubusercontent.com/33053116/116195296-9d25cb00-a764-11eb-9cfc-038cece51832.png)

Seems still timing in `v2.2`
