### ISSUE TITLE
create experiment has some unknown info

### ISSUE THREAD

**Issue by SparkSnail** [microsoft/nni#3530]
**Environment**:
- NNI version: v2.1
- NNI mode (local|remote|pai): local
- Client OS: Windows
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
When create experiment in python client, has some unknow info in console.
**How to reproduce it?**: 

**Additional information**:
![image](https://user-images.githubusercontent.com/22682999/114649286-cf6e0c00-9d12-11eb-8d19-e1dfca9f55c5.png)

**Comment by kvartet** [comment]
fixed in #3634, so closing this issue.
