### ISSUE TITLE
When to support HRNet for pruning?

### ISSUE THREAD

**Issue by ZexinYan** [microsoft/nni#3533]
**Environment**:
- NNI version: 2.2
- NNI mode (local|remote|pai): local
- Client OS: Linux
- Server OS (for remote mode only): Linux
- Python version: 3.8.3
- PyTorch/TensorFlow version: 1.7.1 pytroch
- Is conda/virtualenv/venv used?: coda
- Is running in Docker?: not

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
When to support HRNet for pruning?
**How to reproduce it?**: 

**Additional information**:

**Comment by colorjam** [comment]
Hi @ZexinYan, we currently support pruning for HRNet. 
Could you provide more details about what pruner you use that isn't working?

**Comment by ZexinYan** [comment]
> Hi @ZexinYan, we currently support pruning for HRNet.
> Could you provide more details about what pruner you use that isn't working?

Thanks for your reply. Could you provide some examples about pruning for HRNet in Cifar10? I can only find resnet or vgg as example.

**Comment by ZexinYan** [comment]
In master branch, I got the following error:

```
RuntimeError: Has not supported infering output shape from input shape for module/function: `prim::TupleUnpack`, .prim::TupleUnpack.201
```

**Comment by J-shang** [comment]
Hi, @ZexinYan 
Here has a similar issue https://github.com/microsoft/nni/issues/3645 for your reference, and this issue will be fixed in pr https://github.com/microsoft/nni/pull/3462. You could have a try when this pr merged, or clone this branch then install and try.
