### ISSUE TITLE
show more error info when nnimanager catches error, not just err.message

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/nni#354]
not just err.message, could also add err.name, err.stack, etc.

**Comment by chicm-ms** [comment]
@QuanluZhang   Did you mean to show stack info in webUI?   the stack info is logged in log file.

**Comment by chicm-ms** [comment]
Discussed with @QuanluZhang , err.stack is logged in log file, It is OK not to show it in Web UI. Closed.
