### ISSUE TITLE
Broken link on WebUI

### ISSUE THREAD

**Issue by JunweiSUN** [microsoft/nni#3549]
![image](https://user-images.githubusercontent.com/30487595/115360329-1c118580-a1f2-11eb-93ab-37ead0feefd4.png)
Link here should be `https://github.com/Microsoft/nni/tree/v2.1` instead of `https://github.com/Microsoft/nni/tree/2.1.0`

**Comment by Lijiaoa** [comment]
Yes. But I think this version should be `v2.1` rather than `v2.1.0`.

**Comment by JunweiSUN** [comment]
> Yes. But I think this version should be `v2.1` rather than `v2.1.0`.

I think maybe the `version` in `package.json`  was set to `2.1.0` when releasing nni v2.1 which caused this issue. Maybe we should make the version of nni more consistent instead using `2.1.0`, `2.1`, `v2.1` together.

**Comment by Lijiaoa** [comment]
hi @JunweiSUN Thanks for raising this bug. It had been fix in PR #5154.
