### ISSUE TITLE
Include sequenceId or failed/stopped trials in nnictl experiment export

### ISSUE THREAD

**Issue by arvoelke** [microsoft/nni#3551]
**What would you like to be added**:

`nnictl experiment export` could be extended to include the `sequenceId` information. In addition, it could optionally include the trials that failed or were "early stopped".

**Why is this needed**:

Sometimes it is important to refer back to the `sequenceId` in case that was used somehow in the trial (e.g., to name a model file or round-robin between GPUs, etc.). It's also a proxy for how much feedback the chosen tuner has gotten to that point, which can be useful in assessing how well the tuner is reducing the search space. This information is not in `nnictl experiment export` and it is not possible to infer by the index of the trials because they skip over those that failed or stopped.

Likewise, it can be useful to refer back to information about failed or stopped trials for diagnostic purposes.

**Without this feature, how does current nni work**:

The data for each trial includes a `trialJobId` but not a `sequenceId`. All cross-referencing must be done through the `trialJobId`.

Alternatively, `nnictl trial ls` can be used, which includes all of the trials and their `sequenceId`. However, it does not include the intermediate results (which `nnictl experiment export` does include via the `--intermediate` flag).

**Components that may involve changes**:

The command-line interface and documentation:
```
nnictl experiment export
```

**Brief description of your proposal if any**:

Add `sequenceId` as an additional column alongside `trialJobId` in `nnictl experiment export` by default.

An additional command-line option could also toggle the inclusion of failed and stopped trials (and then a `status` column will likely be needed as well).

**Comment by J-shang** [comment]
Hello @arvoelke , for the first one, add `sequenceId` to find the tuner on how to reduce the search space is an interesting idea. I think this is a feature worth adding.

For the second, `nnictl experiment export` is used for exporting results & hyper-parameter, and in the latest version, nni won't retry the `failed` trials, so the `failed` trials' hyper-parameters are never used. Or by the rule of tuner, or in the future nni version, the `failed` trial's hyper-parameter is retried, it will within a new trial. In these situations, I think the `failed` trial should not appear in `export`.
