### ISSUE TITLE
Multi and Auto Compressor

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#3584]
~ddl: 4.30~

After two meetings, we decide to extend ddl to 5.10

Link #3390

**Comment by J-shang** [comment]
- [ ] pruner & quantizer: if we need API to recover the wrapper from a file? for simulation next time.
- [ ] multi-compressor: 
  - [ ] naming
  - [ ] if we need support schedule pruner? (support one-shot now)
- [ ] auto-compressor
  - [ ] API naming
  - [ ] mode (use one compressor or multi-compressor)
  - [ ] default search space (it is like a tuner, support grid search now)
