### ISSUE TITLE
What's the NNI's plan to support folded bn?

### ISSUE THREAD

**Issue by un-knight** [microsoft/nni#3590]
I found that NNI doesn't support simulation of bn folding during QAT, so I am curious about what the plan is?

https://github.com/microsoft/nni/blob/063d6b744dc8252fb182acd6a9c2949fec8f8389/nni/algorithms/compression/pytorch/quantization/quantizers.py#L355

**Comment by linbinskn** [comment]
BN folding is in our TODO list. However, it may not be easy to add this feature. Do you think BN folding is necessary feature during QAT? If so, please tell me your reasons.

**Comment by un-knight** [comment]
In my case, I will merge bn with convolution in order to support integer-arithmetic-only inference during deployment, so I would like to get a convolution weight scaling factor that simulates bn folding during QAT. In factor, I already support bn folding and binary op(e.g. shortcut add, concate) fake quantization simulation in my own extension for NNI, but there are some prerequisites for the input model which requires the user to refactor the model's code by following some standards. In my extension, I already refactor quantizer and quantizer wrapper and many functions, so it can't be compatible with NNI quantizer directly, but my core simulation workflow still follows the NNI's design of quantizer, wrapper, QuantGrad, etc. Thanks to the NNI's architecture design, it's good for users to do extensions.

**Comment by linbinskn** [comment]
We will further discuss about how to add this feature into NNI QAT algorithm appropriately. We also look forward to your strategy which may contribute to NNI community.

**Comment by un-knight** [comment]
In fact, I am interested in `torch.fx` features, this feature may support QAT without refactoring in model structure codes in the future.

**Comment by chenbohua3** [comment]
We are going to add bn-fold to qat quantizers, more details can be found in #3890 . Look forward to your suggestions.

**Comment by un-knight** [comment]
> We are going to add bn-fold to qat quantizers, more details can be found in #3890 . Look forward to your suggestions.

@chenbohua3 That's really great!

**Comment by Lijiaoa** [comment]
hi @un-knight Thanks for using nni. Looks like this issue had been resolved at that time. Could you help confirm and closing it? Thanks!
