### ISSUE TITLE
Can we have example of utilizing one-shot NAS for DNN models?

### ISSUE THREAD

**Issue by ZhuJohnson** [microsoft/nni#3593]
**What would you like to be added**:
More example for one-shot NAS practice of DNN/MLP models
**Why is this needed**:
Didn't find this kind of example in the repo.
**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:
I'd like to apply NAS function to search the model structure for MLP(to searchhow many hidden layer/how many neurons in each layer/activation function/dropout rate/ layer type(dense or denseblock)), but I cannot find any examples about this problem in the repo.

**Comment by ultmaster** [comment]
Good suggestion. Some of what you want can be naturally fit into current one-shot algorithms (e.g., activation function), while for others we need to find papers and even improvise as current one-shot NAS might not work at all.

In summary, we have to investigate what is going on. For now, let's put it into our future plan.

**Comment by scarlett2018** [comment]
already provided in later release, closing the issue.
