### ISSUE TITLE
nni in remote mode experiment folder

### ISSUE THREAD

**Issue by BaptisteBrument** [microsoft/nni#3595]
**Environment**:
- NNI version: 2.1
- NNI mode remote
- Client OS: docker container with nni image
- Server OS: docker container with nni image
- Python version: 3.6.9 (default version in the image)
- PyTorch/TensorFlow version: Tensorflow 2.3.1 (default version in the image)
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: yes

Hello,

I am currently working with NNI and I wanted to try the remote mode.
On my host machine (Windows) I have two Ubuntu VMs running on Virtualbox.
On each VM, I have a docker container running with NNI on it.
I am able to connect to a shell on one of the container to run nnictl and to start an experiment.
I have the information needed to use the other container as a remote machine (IP, port and credentials)

I can see on the Web UI that the experiments are running. However I have no data for the metrics (like in this issue [#1939](https://github.com/microsoft/nni/issues/1939) )

If I understand well, the UI gets its information from the 'nni_experiment' folder located in the home directory of the container running nnictl. The metrics are stored in the 'nni_experiment' folder located in the /tmp directory of the remote machine (the other container.

Is that the expected behaviour? I don't see anything related to this in [the documentation](https://nni.readthedocs.io/en/latest/TrainingService/RemoteMachineMode.html) What is the correct way to send information between the machines?

Thank you in Advance,

Baptiste

edit : I have tried to create a shared directory between both VMs and to mount a volume on both containerso that they have access to the shared folder. The logDir in config.yml is pointing to the shared folder but the results are still in /tmp for the remote machine.

**Comment by SparkSnail** [comment]
Are your trials succeeded? Can you show your trial log here? You can get your trial log path from WebUI.
![image](https://user-images.githubusercontent.com/22682999/116672742-1c213a80-a9d5-11eb-946e-2f23592d9b6a.png)

**Comment by BaptisteBrument** [comment]
Thank you for your reply.
Yes the experiments are succeedeed.
Here are the logs of one of the trials:

- trial.log 
[2021-04-30  09:48:42] INFO (nni_syslog_trial/Thread-2) NNISDK_MEb'{"parameter_id": 0, "trial_job_id": "C5op9", "type": "FINAL", "sequence": 0, "value": "0;9755555555555555"}'
[2021-04-30  09:48:53] INFO (nni_syslog_trial/keeper/MainThread) [2021-04-30  09:48:53.074482] INFO subprocess terminated. Exit code is 0. Quit
[2021-04-30  09:48:53] INFO (nni_syslog_trial/keeper/MainThread) [2021-04-30  09:48:53.080498] INFO NNI trial keeper exit with code 0

- trialkeeper_stderr
HTTPConnectionPool(host='172.17.0.2' , port=8081): Max retries exceeded with url: /api/v1/nni-pai/stdout/J07VRyFD/C5op9 (Caused by NewConnectionError('<urllib3.connection.HTTPCONNECTION object at 0x7fb48df18588>:
Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='172.17.0.2' , port=8081): Max retries exceeded with url: /api/v1/nni-pai/stdout/J07VRyFD/C5op9 (Caused by NewConnectionError('<urllib3.connection.HTTPCONNECTION object at 0x7fb48df6a860>:
Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='172.17.0.2' , port=8081): Max retries exceeded with url: /api/v1/nni-pai/stdout/J07VRyFD/C5op9 (Caused by NewConnectionError('<urllib3.connection.HTTPCONNECTION object at 0x7fb48df18c50>:
Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='172.17.0.2' , port=8081): Max retries exceeded with url: /api/v1/nni-pai/stdout/J07VRyFD/C5op9 (Caused by NewConnectionError('<urllib3.connection.HTTPCONNECTION object at 0x7fb48df18d68>:
Failed to establish a new connection: [Errno 111] Connection refused',))

- trialkeeper_stdout
[2021-04-30  09:48:41.052883] INFO trial_keeper_version is 2.1
[2021-04-30  09:48:41.052973] INFO nni_manager_version is 2.1
[2021-04-30  09:48:41.053002] INFO Version match!
Get exception HTTPConnectionPool(host='172.17.0.2' , port=8081): Max retries exceeded with url: /api/v1/nni-pai/stdut/J07VRyFD/C5op9 (Caused by NewConnectionError('<urllib3.connection.HTTPCONNECTION object at 0x7fb48df72518>: Failed to establish a new connection: [Errno 111] Connection refused',)) when sending http post to url http://172.17.0.2:8081/api/v1/nni-pai/version/J07VRyFD/C5op9 
[2021-04-30  09:48:41.058836] INFO trial keeper spawns a subprocess (pid 259) to run commabd: ['CUDA_VISIBLE_DEVICES= ', 'python3', 'main.py']
NNISDK_MEb'{"parameter_id": 0, "trial_job_id": "C5op9", "type": "FINAL", "sequence": 0, "value": "0;9755555555555555"}'

So the problem seems to be related to the port 8081.
Currently, I access the WebUI on localhost on the port 8080. In order to access it I use port forwarding from the "host" container. Should I also port forward the port 8081 and if yes only for the host, the remote machine or both?

**Comment by SparkSnail** [comment]
@BaptisteBrument, host machine will start restserver on 8080 and 8081 port, 8080 port is used to connect webUI, 8081 port is used to collect remote metrics. You only need to open 8081 port on host machine.

**Comment by kvartet** [comment]
@BaptisteBrument, it seems that your problem had been solved, so I will close this issue, feel free to reopen it
