### ISSUE TITLE
Is it posible to input a list to nni.chose()

### ISSUE THREAD

**Issue by 666XD** [microsoft/nni#3623]
Hi, teams!

Recently, I try to apply the NNI annotation mode to my project, but I would like to make parameters fully control by the args.

For example:
```
"""@nni.variable(nni.choice(128, 256, 512, 1024), name=hidden_size)"""
# to
args.param = [128, 256, 512, 1024]
"""@nni.variable(nni.choice(args.param), name=hidden_size)"""
```

Is it possible to do it?

**Comment by kvartet** [comment]
@QuanluZhang

**Comment by QuanluZhang** [comment]
NNI annotation is not maintained anymore. It is replaced by NNI NAS interface (https://nni.readthedocs.io/en/stable/nas/construct_space.html).
