### ISSUE TITLE
gpuIndices

### ISSUE THREAD

**Issue by creater-zq** [microsoft/nni#3628]
**Describe the issue**:

**Environment**:
- NNI version:2.2
- Training service (local|remote|pai|aml|etc):local
- Client OS:Windows 10
- Python version:3.8.5
- PyTorch/TensorFlow version:1.7.1
- Is conda/virtualenv/venv used?:conda version 10.2
- Is running in Docker?:False

**Configuration**:
 - Experiment config (remember to remove secrets!):config.yml
authorName: default
experimentName: test_nni
trialConcurrency: 1
maxExecDuration: 1d
maxTrialNum: 30
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize
trial:
  command: python train_nni.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
  gpuIndices: 3

 - Search space:
{   "start_lr": {"_type": "choice", "_value": [0.0001, 0.001, 0.01, 0.1]},
    "batch_size": {"_type": "choice", "_value": [8, 12, 16, 32, 64, 128]}
}

error:
ERROR: Config V1 validation failed: SchemaError('gpuIndex format error!')

**Comment by scarlett2018** [comment]
> error:
> ERROR: Config V1 validation failed: SchemaError('gpuIndex format error!')

https://github.com/microsoft/nni/pull/3540
Adding error msg pr owner in to suggest.

**Comment by creater-zq** [comment]
> > error:
> > ERROR: Config V1 validation failed: SchemaError('gpuIndex format error!')
> 
> #3540
> Adding error msg pr owner in to suggest.
Thank you, but I don't quite understand your suggestion. Could you tell me more about it.

**Comment by creater-zq** [comment]
> > error:
> > ERROR: Config V1 validation failed: SchemaError('gpuIndex format error!')
> 
> #3540
> Adding error msg pr owner in to suggest.

> Thank you, but I don't quite understand your suggestion. Could you tell me more about it

**Comment by liuzhe-lz** [comment]
This bug will be fixed in next release.
For now you can walkaround by replacing `3` (int) with `'3'` (str).

**Comment by creater-zq** [comment]
> This bug will be fixed in next release.
> For now you can walkaround by replacing `3` (int) with `'3'` (str).

nice， thanks!

**Comment by liuzhe-lz** [comment]
Expected to be fixed in v2.3 release next week.

**Comment by kvartet** [comment]
hello @creater-zq, I'm closing this issue as it had been fixed, free feel to reopen it if you still think it an active issue.
