### ISSUE TITLE
Does AMCPruner only support 'mobilenet' and 'mobilenetv2' currently?

### ISSUE THREAD

**Issue by ichejun** [microsoft/nni#3632]
Hi!
Does AMCPruner only support 'mobilenet' and 'mobilenetv2' currently? Some comments in the code are confusing：

https://github.com/microsoft/nni/blob/60983149c571840ee9db99a0dd4ebc6185c56dec/nni/algorithms/compression/pytorch/pruning/amc/channel_pruning_env.py#L88

https://github.com/microsoft/nni/pull/2876  
and seems it already support resnet?https://github.com/microsoft/nni/blob/60983149c571840ee9db99a0dd4ebc6185c56dec/examples/model_compress/pruning/amc/amc_train.py#L16

These makes me confused, does AMCPruner support network structures other than 'mobilenet' and 'mobilenetv2' currently?

If yes, can I use it in more other network structures, or is there any restrictions of net when using the amc pruner?
If not, is the share index for residual connection here limits the expansion of the model? or is there any other restrictions?

https://github.com/microsoft/nni/blob/60983149c571840ee9db99a0dd4ebc6185c56dec/nni/algorithms/compression/pytorch/pruning/amc/channel_pruning_env.py#L387 

Thanks~

**Comment by J-shang** [comment]
Yes, it supports `resnet`. You could pull requests to modify the comments if it is convenient. : )

Because AMCPruner develops based on `mobilenet`, `mobilenetv2` open-source implementation, it is hard to expanse to other models.

**Comment by ichejun** [comment]
@J-shang OK, thanks~ I pull request to modify the comments in https://github.com/microsoft/nni/pull/3647, and going to try other nets maybe :)
