### ISSUE TITLE
nni pruning in pytorch  error

### ISSUE THREAD

**Issue by aa12356jm** [microsoft/nni#3633]
**Describe the issue**:
 i use nni  pruning  in pytorch to set dependency_aware=true gives error: Exception has occurred: KeyError 'backbone.model_backbone.features.18.0.module'

**Environment**:
- NNI version: 2.2
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu16.04
- Server OS (for remote mode only):
- Python version: 3.7
- PyTorch/TensorFlow version: pytorch 1.5.0
- Is conda/virtualenv/venv used?:yes , conda 
- Is running in Docker?:no 

`

    import torch,time
    from nni.compression.pytorch.utils.counter import count_flops_params
    
    import nni
    from nni.compression.pytorch import apply_compression_results, ModelSpeedup
    from nni.algorithms.compression.pytorch.pruning import (
        LevelPruner,
        SlimPruner,
        FPGMPruner,
        L1FilterPruner,
        L2FilterPruner,
        AGPPruner,
        ActivationMeanRankFilterPruner,
        ActivationAPoZRankFilterPruner
    )
    
    str2pruner = {
        'level': LevelPruner,
        'l1filter': L1FilterPruner,
        'l2filter': L2FilterPruner,
        'slim': SlimPruner,
        'agp': AGPPruner,
        'fpgm': FPGMPruner,
        'mean_activation': ActivationMeanRankFilterPruner,
        'apoz': ActivationAPoZRankFilterPruner
    }
    
    def get_pruner(model, pruner_name,sparsity=0.3, optimizer=None, dependency_aware=True):
        pruner_cls = str2pruner[pruner_name]
        if pruner_name in ['l1filter', 'mean_activation', 'apoz']:
            config_list = [{
                'sparsity': sparsity,
                'op_types': ['Conv2d'],
            }]
        else:
            config_list = [{
                'sparsity': sparsity,
                'op_types': ['Conv2d']
            }]
    
        kw_args = {}
        if dependency_aware:
            # dummy_input 
            dummy_input = torch.ones(1, 3, 224, 224).to(torch.device("cpu")) 
            print('Enable the dependency_aware mode')
            # note that, not all pruners support the dependency_aware mode
            kw_args['dependency_aware'] = True
            kw_args['dummy_input'] = dummy_input
        
        pruner = pruner_cls(model, config_list, optimizer, **kw_args)
        return pruner
    
    device = torch.device("cpu")
    model = torch.load('model_last_all.pt', map_location=device)
    pruner = get_pruner(model, "l1filter")
    model = pruner.compress() 
`

**Comment by aa12356jm** [comment]
[model_last_all.zip](https://github.com/microsoft/nni/files/6463253/model_last_all.zip)
this is model, please unzip the file model_last_all.zip  to get the file model_last_all.pt ,and torch.load('model_last_all.pt', map_location=device)

**Comment by J-shang** [comment]
hello @aa12356jm , do you modify the mobilenetv2? I got the following error:
`ModuleNotFoundError: No module named 'nanodet.model.backbone.mobilenetv2_torchvision_QAT'`

Have you tried `dependency_aware=False`? I will check if we support mobilenetv2 with dependency_aware.

**Comment by aa12356jm** [comment]
yes,i use the version mobilenetv2 for quantize training,  it is ok by set  dependency_aware=False

**Comment by aa12356jm** [comment]
我使用中文描述我的需求吧，方便一些，我现在是做一个检测模型，想把这个模型做压缩，现在使用l1filter结构化剪枝剪掉50%的kernel后,想把这些kernel为0的filter删除掉，请问modelspeedup这个函数是实现这个功能的吗？我在你们的basic_pruners_torch.py文件中使用modelspeedup后保存下来的模型大小并没有变化，请问是哪里有问题吗？谢谢

**Comment by aa12356jm** [comment]
> hello @aa12356jm , do you modify the mobilenetv2? I got the following error:
> `ModuleNotFoundError: No module named 'nanodet.model.backbone.mobilenetv2_torchvision_QAT'`
> 
> Have you tried `dependency_aware=False`? I will check if we support mobilenetv2 with dependency_aware.

i have tried mobilenetv2 by set dependency_aware=true in basic_pruners_torch.py,  it is ok，but it is not ok  in my model by set dependency_aware=true

**Comment by J-shang** [comment]
dependency_aware is an experimental feature, and complex structure may lead to failure, like the complex dependencies in shufflenet. So If it is not convenient to display the model, could you help us to find what changes in your model caused the failure?

Anyway, `dependency_aware=False` should work fine.
