### ISSUE TITLE
Distribution Code  of searching hyper-parameters

### ISSUE THREAD

**Issue by LicharYuan** [microsoft/nni#3636]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**
Hi, 在使用NNI超参搜索的时候, 比较好奇 分布式下 是怎么综合多台机器返回的结果的?  直观的想法是 Host收集机器结果, 然后实现搜索算法. 
具体的源码能指个路吗? 找了半天没找到...
谢谢!

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:999.dev0
- nni mode(local|pai|remote): remote
- OS: Ubuntu 16.04
- python version: 3.7
- is conda or virtualenv used?: no
- is running in docker?: yes

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**
no 
**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by SparkSnail** [comment]
NNI collect metric result reported by trial jobs in different, and use tuner to generate new parameter.
refer: [architecture doc](https://nni.readthedocs.io/en/stable/Overview.html#overview), [trainingService code](https://github.com/microsoft/nni/tree/master/ts/nni_manager/training_service)

**Comment by LicharYuan** [comment]
> NNI collect metric result reported from trial jobs in different training clusters, and use tuner to generate new parameter.
> refer: [architecture doc](https://nni.readthedocs.io/en/stable/Overview.html#overview), [trainingService code](https://github.com/microsoft/nni/tree/master/ts/nni_manager/training_service)

So, NNI use TypeScript to encode different machine's Infomation and send the relative information by socket?

**Comment by SparkSnail** [comment]
> > NNI collect metric result reported from trial jobs in different training clusters, and use tuner to generate new parameter.
> > refer: [architecture doc](https://nni.readthedocs.io/en/stable/Overview.html#overview), [trainingService code](https://github.com/microsoft/nni/tree/master/ts/nni_manager/training_service)
> 
> Thank your reply!!!!
> So, NNI use TypeScript to encode different machine's Infomation and send the relative information by socket?

NNI use restful server to communicate between different machines, and use IPC to communicate between nniManager and tuner.

**Comment by LicharYuan** [comment]
> > > NNI collect metric result reported from trial jobs in different training clusters, and use tuner to generate new parameter.
> > > refer: [architecture doc](https://nni.readthedocs.io/en/stable/Overview.html#overview), [trainingService code](https://github.com/microsoft/nni/tree/master/ts/nni_manager/training_service)
> > 
> > 
> > Thank your reply!!!!
> > So, NNI use TypeScript to encode different machine's Infomation and send the relative information by socket?
> 
> NNI use restful server to communicate between different machines, and use IPC to communicate between nniManager and tuner.

Gotta! Help a lot! 😊
