### ISSUE TITLE
NNI Config V2 Validation Failing Because of Invalid "\\t" Character

### ISSUE THREAD

**Issue by rohin-dasari** [microsoft/nni#3638]
**Describe the issue**:
I am trying to start a new NNI experiment using the v2 config, but I come across a Configuration Validation error that claims that I have, what appears to be, some sort of tab character (\\t) in my yaml file. I know that tabs are not allowed in yaml files, and I have tried explicitly replacing all tabs with spaces, but the validation still fails. The error message is shown below

**Environment**:
- NNI version: 2.2
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu 18.04
- Python version: 3.7
- PyTorch/TensorFlow version: Tensorflow 2.2.0
- Is conda/virtualenv/venv used?: No
- Is running in Docker?: Yes

**Configuration**:
 - Experiment config:

experimentName: BMC
trialConcurrency: 1
maxTrialNumber: 10
searchSpaceFile: search_space.json
useAnnotation: false
trialCommand: python3 ../src/search.py --data_path "/data"
trialGpuNumber: 1
trialCodeDirectory: .
tuner:
  name: Random
trainingService:
  platform: local
  useActiveGpu: True

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 
ERROR: Config V2 validation failed: ScannerError('while scanning for the next token', None, "found character '\\t' that cannot start any token", <ruamel.yaml.error.FileMark object at 0x7f25961f4a50>) 

ERROR: 'NoneType' object has no attribute 'get'

**How to reproduce it?**:
Run ```nnictl create --config $path_to_config```. In order to reproduce the error, I'm the sure the ```trialCommand``` value can be replaced by a simple command that doesn't reference any files/code in my environment.

**Comment by liuzhe-lz** [comment]
Can you upload the config file as attachment? So I can try it on my machine.

**Comment by rohin-dasari** [comment]
Yes, here you go:

[config_v2.zip](https://github.com/microsoft/nni/files/6472979/config_v2.zip)

Thanks

**Comment by liuzhe-lz** [comment]
Yaml library has been updated. Expected to be fixed in v2.3 release next week.

**Comment by rohin-dasari** [comment]
Just tried it out with v2.3rc0, but the error appears to persist. Which Yaml library is causing the problem? Is it ruamel.yaml?

**Comment by liuzhe-lz** [comment]
v2.3 has switched to pyyaml from ruamel.yaml.
I tried your config and it does not contain '\t' so I assumed it was an environment problem.
Have you tried config files from official examples? Does the problem affects every config files or only a specific one?

**Comment by liuzhe-lz** [comment]
v2.3 has switched to pyyaml from ruamel.yaml.
I tried your config and it does not contain '\t' so I assumed it was an environment problem.
Have you tried config files from official examples? Does the problem affects every config files or only a specific one?

**Comment by rohin-dasari** [comment]
Just confirmed that the latest release no longer throws this issue anymore. I tried both with the official examples and with some config files I had written.

If it was an environment problem, I'm not sure what it could've been.

Closing now since the original error is no longer being thrown.

Thanks!
