### ISSUE TITLE
Is the search space of model parameters for different experiments unrelated?

### ISSUE THREAD

**Issue by CXX1113** [microsoft/nni#3649]
**Describe the issue**:
That is, whether NNI is run like this: Suppose the first NNI experiment is forcibly terminated after completing 1/3 of the parameter search space. If we rerun the NNI experiment a second time, but instead of continuing the search from 2/3 of the remaining space, NNI again searches from the entire space.

**Environment**:
- NNI version: 2.2
- Training service (local|remote|pai|aml|etc): local
- Client OS: Windows
- Server OS (for remote mode only): Windows
- Python version: 3.8
- PyTorch/TensorFlow version: 1.6.0
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: no

**Comment by ultmaster** [comment]
What type of search algorithm are you using? Supposing that you are using grid search, you should be able to resume the experiment and complete the rest of search space.

**Comment by CXX1113** [comment]
OK，I got it. Thanks!
