### ISSUE TITLE
About sklearn in nni

### ISSUE THREAD

**Issue by learningelectric** [microsoft/nni#3657]
Why does the sklearn example you provided not work? It has been failed.
I really feel sad about it.
please you fix this error. Thank you very much

**Comment by kvartet** [comment]
These examples have no problems on my machine. Can you fill in the following template? Maybe I can help you.

**Describe the issue**:



**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:


**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:


**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 



**How to reproduce it?**:

**Comment by scarlett2018** [comment]
Closing as we can not reproduce the issue, @learningelectric .  Feel free to reopen if you are able to reproduce it, thanks.
