### ISSUE TITLE
support multi-phase trial tuning

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/nni#37]
A trial may need multiple phases of hyperparameter/neuralarchitecture tuning. More specifically, in phase one, the trial get some hyperparameters, then run and generate results. Then how to choose the hyperparameters in phase two should depend on the results generated in phase one. Likewise, the hyperparameters in phase three depends on the results in phase two, etc. After all the phases are completed, the trial is finished.

**Comment by chicm-ms** [comment]
Done.
