### ISSUE TITLE
NNI.Experiment; Optimization mode gets internally set to 'maximize' when working on remote device

### ISSUE THREAD

**Issue by JanikPi** [microsoft/nni#3710]
**Describe the issue**: Im fairly new to programming and NNI so maybe Im missing something. I want to launch NNI via script from python using nni.experiment. When Im working on my local machine everything seems to work well. But if i start NNI locally using a remote-desktop tool (still using training_service='local') the optimize_mode from exp.config.tuner.class_args['optimize_mode'] seems to always be set to 'maximize' internally, although it has explicitly been set to 'minimize' in my script. 
This can be seen in the web-UI by looking at the top trials (trials with the highest scoring points are displayed) or the optimization curve, which highlights maximas instead of minimas. I have included the pictures at the end.

When looking at the experiment summary in the UI, 'minimize' is chosen for the tuner.

**Environment**:
- NNI version: 2.2
- Training service (local|remote|pai|aml|etc): local
- Python version: 3.6.9 on remote and 3.8.7 on local 
- PyTorch/TensorFlow version: TensorFlow 2.4.1
- Is conda/virtualenv/venv used?: Yes venv
- my local device: Windows10
- remote device: Ubuntu 18.04.5 LTS

**Configuration**:
 - Experiment config (remember to remove secrets!):
            exp = Experiment('local')
            exp.config.experiment_name = self.config['experiment_name'][self.dataset_id]
            exp.config.trial_concurrency = self.config['trial_concurrency']
            exp.config.max_trial_number = self.config['max_trial_number']
            exp.config.search_space = self.search_space
            exp.config.tuner.name = TPE
            exp.config.trial_command = 'python main.py ' + str(self.dataset_id) + ' ' + self.scoring
            exp.config.trial_code_directory = '../nni_regression'
            exp.config.tuner.class_args['optimize_mode'] = 'minimize'
            exp.config.training_service.use_active_gpu = True  
            exp.config.max_experiment_duration = self.max_loop_duration()
            exp.start()

 - Search space: Pretty long, therefore not included. If it is necessary i can still post it. 

![RemoteOptiCurve](https://user-images.githubusercontent.com/75477075/120304449-14a0ca00-c2d0-11eb-8060-94c92c469eae.png)
![RemoteTopTrials](https://user-images.githubusercontent.com/75477075/120304460-18cce780-c2d0-11eb-8d28-59e64cfda482.png)
![ExpSummary](https://user-images.githubusercontent.com/75477075/120323284-a1a24e00-c2e5-11eb-82ca-1b6915ef21c7.png)

**Comment by ultmaster** [comment]
This seems to be a WebUI issue. @Lijiaoa please follow.

**Comment by Lijiaoa** [comment]
@JanikPi Thanks for reportering this issue. It is webui bug and will be fixed on `v2.5`.

**Comment by ultmaster** [comment]
fixed in #3731
