### ISSUE TITLE
Add some way of prepending the url prefix value to all of the included static files, etc.

### ISSUE THREAD

**Issue by rmfan** [microsoft/nni#3739]
**What would you like to be added**:

Right now there is a flag `--url_prefix` to have the UI be available at `http://<ip>:<port>/<url_prefix>`. I would also like some way for the UI's dependent javascript, css, etc files to be located at `http://<ip>:<port>/<url_prefix>/static` instead of `http://<ip>:<port>/static`. This may be similar to Tensorboard's `--path_prefix` flag.

**Why is this needed**:

When `http://<ip>:<port>/` (or `http://<ip>:<port>/static`) is not available, then the front end on `http://<ip>:<port>/<url_prefix>` produces errors. This may occur when the NNI UI is behind a reverse proxy like Nginx.

**Without this feature, how does current nni work**：

NNI's UI does not display anything if `http://<ip>:<port>/static` is not available

**Components that may involve changes**:

`ts/webui`

**Brief description of your proposal if any**:

**Comment by Lijiaoa** [comment]
Hi, @rmfan
We support `prefix` on nni `v2.3`.  you could start an experiment by `nnictl create ... --url_prefix yourPrefix` and the webui webportal is `http://<ip>:<port>/yourPrefix/oview`. It will be released soon.

**Comment by liuzhe-lz** [comment]
Thanks for your report. But seems we are too late for v2.3 release.
For now I suggest to workaround by copying static files to reverse proxy's path and add a special rule. All NNI experiments should share same static files.
We will fix this in v2.4.
