### ISSUE TITLE
support the training service: Microsoft PAI

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/nni#38]
Microsoft PAI (https://github.com/Microsoft/pai) is a resource scheduling and cluster management platform for AI. Some Universities and companies have deploy PAI on their GPU cluster. It would be great to support a training service for PAI, allowing submitting trial jobs on PAI cluster.

**Comment by scarlett2018** [comment]
Closing this item as OpenPAI is already supported in V0.2.0.
