### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by jianliu-ml** [microsoft/nni#3829]
Here is the command:

cd ~/git/nni/examples/trials/mnist-annotation
nnictl create -c config.yml --port 8004

The error is "ValueError: ExperimentConfig: search_space and search_space_file must be set one"

I use the updated config.yml

ANd the Error is:
Traceback (most recent call last):
  File "/home/jliu/venv3/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/home/jliu/venv3/lib/python3.6/site-packages/nni/tools/nnictl/nnictl.py", line 272, in parse_args
    args.func(args)
  File "/home/jliu/venv3/lib/python3.6/site-packages/nni/tools/nnictl/launcher.py", line 553, in view_experiment
    manage_stopped_experiment(args, 'view')
  File "/home/jliu/venv3/lib/python3.6/site-packages/nni/tools/nnictl/launcher.py", line 534, in manage_stopped_experiment
    experiment_config = Config(experiment_id, experiments_dict[args.id]['logDir']).get_config()
  File "/home/jliu/venv3/lib/python3.6/site-packages/nni/tools/nnictl/config_utils.py", line 88, in __init__
    self.conn = sqlite3.connect(os.path.join(log_dir, experiment_id, 'db', 'nni.sqlite'))
sqlite3.OperationalError: unable to open database file

**Comment by jianliu-ml** [comment]
nnictl create -c config.yml --port 8004
nnictl view b9JhTvAg

**Comment by J-shang** [comment]
Hi @jianliu-ml, seems you use `nnictl view` to view an un-successful launched experiment. If you want to start a new experiment with a new config, try using `nnictl create -c new_config.yml`. And if you want to find the log of the broken experiment, you can find the log files under `~/nni-experiments/EXPERIMENT_ID`.

**Comment by kvartet** [comment]
> Hi @jianliu-ml, seems you use `nnictl view` to view an un-successful launched experiment. If you want to start a new experiment with a new config, try using `nnictl create -c new_config.yml`. And if you want to find the log of the broken experiment, you can find the log files under `~/nni-experiments/EXPERIMENT_ID`.
> `annotation` has a bug in v2.2, and will be fixed in v2,3. You could fetch repo from master and install from source code, or wait for v2.3 release if you want to use `annotation`.

v2.3 had been released, you can try it.

**Comment by jianliu-ml** [comment]
> > Hi @jianliu-ml, seems you use `nnictl view` to view an un-successful launched experiment. If you want to start a new experiment with a new config, try using `nnictl create -c new_config.yml`. And if you want to find the log of the broken experiment, you can find the log files under `~/nni-experiments/EXPERIMENT_ID`.
> > `annotation` has a bug in v2.2, and will be fixed in v2,3. You could fetch repo from master and install from source code, or wait for v2.3 release if you want to use `annotation`.
> 
> v2.3 had been released, you can try it.

Hi, @kvartet, thank you very much for such a release!

**Comment by jianliu-ml** [comment]
> > Hi @jianliu-ml, seems you use `nnictl view` to view an un-successful launched experiment. If you want to start a new experiment with a new config, try using `nnictl create -c new_config.yml`. And if you want to find the log of the broken experiment, you can find the log files under `~/nni-experiments/EXPERIMENT_ID`.
> > `annotation` has a bug in v2.2, and will be fixed in v2,3. You could fetch repo from master and install from source code, or wait for v2.3 release if you want to use `annotation`.
> 
> v2.3 had been released, you can try it.

Hi, @kvartet, I have run the experiments without any problem!
And I will close this issue thread. Thank you again.
