### ISSUE TITLE
RuntimeError: Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions

### ISSUE THREAD

**Issue by jinfagang** [microsoft/nni#3855]
Got this error when try prune a HUGE model like MaskRCNN.

I tried both from torchvision and detectron2, all not work, is there any example on how to compress such big models?

**Comment by J-shang** [comment]
Hello @jinfagang , could you show more information about this error? such as the pruning code, the pruner used, and the full error log. It seems the type of return value in your model is not in `tensors, lists, tuples of tensors, or dictionary of tensors`, please check your model and [this issue](https://github.com/apache/tvm/issues/7971) may help you.

**Comment by J-shang** [comment]
Due to no reply for a long time, close this issue, if there are still problems, please open this issue again
