### ISSUE TITLE
`max_workspace_size` is not compatible with tensorrt8.x

### ISSUE THREAD

**Issue by un-knight** [microsoft/nni#3857]
The following codes will invoke `AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size'` in the TensorRT 8.0.0.3. So it seems that `max_workspace_size` attribute has been removed in TensorRT8

https://github.com/microsoft/nni/blob/ef15fc81967fa13c74da6147931fde236464bf04/nni/compression/pytorch/quantization_speedup/integrated_tensorrt.py#L126

reference issues: https://github.com/NVIDIA-AI-IOT/torch2trt/issues/557

**Comment by mallamsripooja** [comment]
Yes, same issue here. Had to downgrade to older version of Tensorrt.

**Comment by linbinskn** [comment]
Exactly, this problem exists due to api updating after TensorRT8.0. Have supported the latest version in PR #3866 , please wait for it merged.

**Comment by sriram-dsl** [comment]
builder = trt.Builder(TRT_LOGGER)
network = builder.create_network()

builder_config = builder.create_builder_config()

builder_config.max_workspace_size = 1 << 30
