### ISSUE TITLE
RuntimeError: Has not supported infering output shape from input shape for module/function: `SiLU`, model.0.conv.act

### ISSUE THREAD

**Issue by jinfagang** [microsoft/nni#3864]
Acivation functions SiLU support?

Or, how to write a simply infer_shape for this op since activation actually doesn't change shape at all. It should be easily pass by ModelSpeedup

**Comment by zheng-ningxin** [comment]
Hi, thanks for the valuable feedback! 
SiLU has been supported in the https://github.com/microsoft/nni/pull/3462, you can clone this branch and install from source and try again.

In addition, if you want to support SiLU in current NNI, you can just reuse the shape inference function of 'RELU'.
```
infer_from_inshape = {
    ...
    'ReLU': lambda module_masks, mask: relu_inshape(module_masks, mask),
    'SiLU': lambda module_masks, mask: relu_inshape(module_masks, mask),


infer_from_outshape = {
     ...
     'SiLU': lambda module_masks, mask: relu_outshape(module_masks, mask),
```

**Comment by zheng-ningxin** [comment]
Closed~ feel free to reopen it if you meet new problems.
