### ISSUE TITLE
no such file or directory, open 'logs\1625494862.352834\graph.json'

### ISSUE THREAD

**Issue by yuezhuang1387** [microsoft/nni#3902]
**Describe the issue**:
When I try to use NAS visualization, after making sure that all logs files are generated, opening the port (http://127.0.0.1:6060/) will report the following error,
![image](https://user-images.githubusercontent.com/61401199/124492252-c909a080-dde6-11eb-9ea2-00696c949ff0.png)
But all the logs files are generated
![image](https://user-images.githubusercontent.com/61401199/124492125-a11a3d00-dde6-11eb-837f-073bb897cf77.png)
Can someone help me，Thanks

**Environment**:
- NNI version: 2.3
- Training service (local|remote|pai|aml|etc):
- Client OS:  windows10
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: pytorch1.8.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**How to reproduce it?**:

**Comment by acured** [comment]
Seems there is one more space in your command, "logs/1625494862. 352834". Remove it and try again?

**Comment by yuezhuang1387** [comment]
> Seems there is one more space in your command, "logs/1625494862. 352834". Remove it and try again?

Hi, thanks, I'm sure there are no spaces. My operation process is as follows:
1. Make sure that the logs file is generated and is not empty
![image](https://user-images.githubusercontent.com/61401199/124572861-9362c700-de7b-11eb-8ce7-d22eb21d5daa.png)
2. Enter the nnictl command in cmd, it shows NNI NAS board is running
![image](https://user-images.githubusercontent.com/61401199/124573195-e8064200-de7b-11eb-85cd-96844621f51b.png)
3. Enter port(127.0.0.1:6060) in Google browser
![image](https://user-images.githubusercontent.com/61401199/124573864-82668580-de7c-11eb-9200-fbd3277910fa.png)
4. cmd shows Error: ENOENT: no such file or directory, open 'logs\1625556577.591588\graph.json'
![image](https://user-images.githubusercontent.com/61401199/124573992-9dd19080-de7c-11eb-8c75-ebf11a7cbf48.png)
NNI NAS board is always loading.
I don't know what's wrong.

**Comment by ultmaster** [comment]
Are you sure `logs/1625494862. 352834` is in your current folder? I found that your current working directory may be wrong.

**Comment by yuezhuang1387** [comment]
> Are you sure `logs/1625494862. 352834` is in your current folder? I found that your current working directory may be wrong.

Thanks, I solved this problem, just set the path to the global path, like this:
nnictl webui nas --logdir E:\Pytest\NAS\logs\1625650756.0291245 --port 6060
