### ISSUE TITLE
How can I use auto tuning if I have to login jump server

### ISSUE THREAD

**Issue by Asahi678** [microsoft/nni#3943]
If I want to login my server, I have to login jump server first. And then, I can connect to server by jump server. I can not connect to my server directly with server IP. So when I run auto tuning mnist_pytorch.py in the remote way, I get error below.
I also take the same test among local several PC. The code is correct, the config is available and everything works fine. But I can't get expected result when connect to server. How can I use remote nni in my server?

![2021-07-15 16-52-36屏幕截图](https://user-images.githubusercontent.com/34291827/125760045-48703786-6e2c-4544-af53-7e569f5bfed3.png)

**Comment by SparkSnail** [comment]
From your description, it seems you can't connect to remote server from local server, but you can connect remote server from jump server. If you can not connect this remote server, you can't use NNI on the machine. Why don't you use NNI on your jump server?

**Comment by Asahi678** [comment]
> From your description, it seems you can't connect to remote server from local server, but you can connect remote server from jump server. If you can not connect this remote server, you can't use NNI on the machine. Why don't you use NNI on your jump server?

Thanks for your reply. I don't use NNI on jump server because I can't. The jump server is just jump server. I can only login in my account and connect to the remote server. I can not do anything else on jump server. 
"If I can't connect to remote server directly, I can't use NNI." I agree with this. It's absolutely right. I just want to know if there are some solutions that i ignore.

**Comment by SparkSnail** [comment]
> > From your description, it seems you can't connect to remote server from local server, but you can connect remote server from jump server. If you can not connect this remote server, you can't use NNI on the machine. Why don't you use NNI on your jump server?
> 
> Thanks for your reply. I don't use NNI on jump server because I can't. The jump server is just jump server. I can only login in my account and connect to the remote server. I can not do anything else on jump server.
> "If I can't connect to remote server directly, I can't use NNI." I agree with this. It's absolutely right. I just want to know if there are some solutions that i ignore.

I don't think there is a solution in NNI side unless you can connect your remote server from local PC directly or you can use NNI in your jump machine. If you only need one remote server, you can start NNI in local mode in your remote server directly.

**Comment by Asahi678** [comment]
> > > From your description, it seems you can't connect to remote server from local server, but you can connect remote server from jump server. If you can not connect this remote server, you can't use NNI on the machine. Why don't you use NNI on your jump server?
> > 
> > 
> > Thanks for your reply. I don't use NNI on jump server because I can't. The jump server is just jump server. I can only login in my account and connect to the remote server. I can not do anything else on jump server.
> > "If I can't connect to remote server directly, I can't use NNI." I agree with this. It's absolutely right. I just want to know if there are some solutions that i ignore.
> 
> I don't think there is a solution in NNI side unless you can connect your remote server from local PC directly or you can use NNI in your jump machine. If you only need one remote server, you can start NNI in local mode in your remote server directly.

Thanks for your advice. I will use NNI on my local server. This can also help me a lot. NNI is really nice work.
