### ISSUE TITLE
View an experiment with experiment path.

### ISSUE THREAD

**Issue by EternalConfession** [microsoft/nni#3953]
All the experiment infomartion are stored in **~/nni-experiments/.experiments.**

When I want to view a experiment with exp_id, the client will first load the **~/nni-experiments/.experiments.** file, and find the relative path.

So if I delete the log file, I cant view my experiments anymore.

So at least, there should be a way to view an experiment with absolute experiments path.

**Comment by SparkSnail** [comment]
This feature has been supported, and will be released in next release (v2.4 release).
