### ISSUE TITLE
[Retiarii] Inconsistent usage of .to(device) and to_device() in one-shot NAS Trainers

### ISSUE THREAD

**Issue by thomasschmied** [microsoft/nni#3957]
**Describe the issue**:

Hello! 

While running one-shot NAS experiments on custom datasets, I encountered some inconsistencies in the usage of `.to(device)` and `to_device()`.

[EnasTrainer](https://github.com/microsoft/nni/blob/c80ed3e904e74db7126cecf5e24b9fc7c895c401/nni/retiarii/oneshot/pytorch/enas.py#L265), on the one hand, uses the `to_device()` function from `nni.retiarii.oneshot.pytorch.utils` to transfer the tensor to the specified device. [DartsTrainer](https://github.com/microsoft/nni/blob/c80ed3e904e74db7126cecf5e24b9fc7c895c401/nni/retiarii/oneshot/pytorch/darts.py#L163) and [ProxylessTrainer](https://github.com/microsoft/nni/blob/c80ed3e904e74db7126cecf5e24b9fc7c895c401/nni/retiarii/oneshot/pytorch/proxyless.py#L184), on the other hand, use the standard torch `.to()` function. 

Using `.to()` is problematic, as the `torch.utils.data.DataLoader` instances might return batches that are not of type `torch.Tensor` and hence have no `.to()` method. The `to_device` function handles these cases. 

Would it be possible to use `to_device()` across all Trainer classes? 

**Environment**:
- NNI version: 2.3
- Python version: 3.8.8
- PyTorch version: 1.9.0

Thank you,
Thomas

**Comment by ultmaster** [comment]
As I said in #3956, we will probably handle the device issue with a more general framework like PyTorch-lightning. Before this refactor, we encourage you to change all `.to()` to `to_device()` in a PR. Thanks in advance.

**Comment by scarlett2018** [comment]
closing the issue as the PR had been merged, thanks @thomasschmied for the support and contributions!
