### ISSUE TITLE
Are there any way to "export" the trained parameters and their final performance?

### ISSUE THREAD

**Issue by HudsonHuang** [Microsoft/nni#396]
Dear  Zhang ,Crysple and other developers:

Thank you for for your great work! The NNI is such an awesome system that all my friends using it!
But I think it could be more powerful if it can show the "hyper-parameters surface" which it had run . 
Here is a relevant project: https://github.com/lucfra/FAR-HO The heat map is cool, but a 3D version would be even better.

But it might be impossible to draw the picture, as the tuner doesn't traverse a path for optimization for all parameters, but it would be helpful to have a "one-button" way to export trained parameters and their final performance in form of text or .csv files.

**Comment by lvybriage** [comment]
@HudsonHuang Thanks for using NNI. We will support to export trained parameters and their final performance in form of json file.

**Comment by scarlett2018** [comment]
We support to download parameters in UI in the recent v0.4 release, please try it out.
