### ISSUE TITLE
How to print and save the best model when using one-shot nas

### ISSUE THREAD

**Issue by s974534426** [microsoft/nni#3969]
**Environment**:
- NNI version: 2.3
- PyTorch/TensorFlow version: PyTorch

I use DartsTrainer and build a model as follows:
``` python
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.LayerChoice([
            nn.Conv2d(3, 6, 3, padding=1),
            nn.Conv2d(3, 6, 5, padding=2),
            nn.Conv2d(3, 6, 7, padding=3),
        ], label='conv1')
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.LayerChoice([
            nn.Conv2d(6, 16, 3, padding=1),
            nn.Conv2d(6, 16, 5, padding=2),
            nn.Conv2d(6, 16, 7, padding=3),
        ], label='conv2')
        self.conv3 = nn.Conv2d(16, 16, 1)

        self.skipconnect1 = nn.InputChoice(n_candidates=2, label='skipconnection')
        self.bn = nn.BatchNorm2d(16)

        self.gap = nn.AdaptiveAvgPool2d(4)
        self.fc1 = nn.Linear(16*4*4, nn.ValueChoice([64, 128, 256], label='fc1'))
        self.fc2 = nn.Linear(
            nn.ValueChoice([64, 128, 256], label='fc1'), 
            nn.ValueChoice([32, 64, 128], label='fc2')
        )
        self.fc3 = nn.Linear(nn.ValueChoice([32, 64, 128], label='fc2'), 10)

    def forward(self, x):
        bs = x.size(0)
        x = self.pool(F.relu(self.conv1(x)))
        x0 = F.relu(self.conv2(x))
        x1 = F.relu(self.conv3(x0))

        x1 = self.skipconnect1([x1, x0+x1])
        x = self.pool(self.bn(x1))

        x = self.gap(x).view(bs, -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return x
```

The first problem is that I can't get all search parameters using ```trainer.export()```. It prints ```{'conv1': 1, 'conv2': 2, 'skipconnection': [1]}```, but I expect it prints like ```{'conv1': 1, 'conv2': 2, 'skipconnection': [1], 'fc1': 64, 'fc2': 32}```. I check the source code of [DartsTrainer](https://github.com/microsoft/nni/blob/master/nni/retiarii/oneshot/pytorch/darts.py). In line 123 and 124, it only replace layer choice and input choice, doesn't replace value choice. I think that is why I can't print 'fc1' and 'fc2'. Is it a bug? And how can I print the best value when using ```nn.ValueChoice```?

The second problem is that how can I save the best architecture. In NNI 2.0, trainer.export() has parameters 'file' to save architecture as json, and load using ```apply_fixed_architecture```. How can I do this in NNI 2.3?

Thinks.

**Comment by s974534426** [comment]
I tried to use ```json.dump``` save the result in ```trainer.export()```, and load the best architecture using ```nni.nas.pytorch.fixed.apply_fixed_architecture``` like [search.py](https://github.com/microsoft/nni/blob/master/examples/nas/oneshot/darts/search.py) and [retrain.py](https://github.com/microsoft/nni/blob/master/examples/nas/oneshot/darts/retrain.py). But it reports an error: ```RuntimeError: Unexpected keys found in fixed architecture: {'conv2', 'conv1', 'skipconnection'}.```. How can I solve it?

**Comment by Nickydusk** [comment]
> **Environment**:
> 
> * NNI version: 2.3
> * PyTorch/TensorFlow version: PyTorch
> 
> I use DartsTrainer and build a model as follows:
> 
> ```python
> class Net(nn.Module):
> 
>     def __init__(self):
>         super(Net, self).__init__()
>         self.conv1 = nn.LayerChoice([
>             nn.Conv2d(3, 6, 3, padding=1),
>             nn.Conv2d(3, 6, 5, padding=2),
>             nn.Conv2d(3, 6, 7, padding=3),
>         ], label='conv1')
>         self.pool = nn.MaxPool2d(2, 2)
>         self.conv2 = nn.LayerChoice([
>             nn.Conv2d(6, 16, 3, padding=1),
>             nn.Conv2d(6, 16, 5, padding=2),
>             nn.Conv2d(6, 16, 7, padding=3),
>         ], label='conv2')
>         self.conv3 = nn.Conv2d(16, 16, 1)
> 
>         self.skipconnect1 = nn.InputChoice(n_candidates=2, label='skipconnection')
>         self.bn = nn.BatchNorm2d(16)
> 
>         self.gap = nn.AdaptiveAvgPool2d(4)
>         self.fc1 = nn.Linear(16*4*4, nn.ValueChoice([64, 128, 256], label='fc1'))
>         self.fc2 = nn.Linear(
>             nn.ValueChoice([64, 128, 256], label='fc1'), 
>             nn.ValueChoice([32, 64, 128], label='fc2')
>         )
>         self.fc3 = nn.Linear(nn.ValueChoice([32, 64, 128], label='fc2'), 10)
> 
>     def forward(self, x):
>         bs = x.size(0)
>         x = self.pool(F.relu(self.conv1(x)))
>         x0 = F.relu(self.conv2(x))
>         x1 = F.relu(self.conv3(x0))
> 
>         x1 = self.skipconnect1([x1, x0+x1])
>         x = self.pool(self.bn(x1))
> 
>         x = self.gap(x).view(bs, -1)
>         x = F.relu(self.fc1(x))
>         x = F.relu(self.fc2(x))
>         x = self.fc3(x)
> 
>         return x
> ```
> 
> The first problem is that I can't get all search parameters using `trainer.export()`. It prints `{'conv1': 1, 'conv2': 2, 'skipconnection': [1]}`, but I expect it prints like `{'conv1': 1, 'conv2': 2, 'skipconnection': [1], 'fc1': 64, 'fc2': 32}`. I check the source code of [DartsTrainer](https://github.com/microsoft/nni/blob/master/nni/retiarii/oneshot/pytorch/darts.py). In line 123 and 124, it only replace layer choice and input choice, doesn't replace value choice. I think that is why I can't print 'fc1' and 'fc2'. Is it a bug? And how can I print the best value when using `nn.ValueChoice`?
> 
> The second problem is that how can I save the best architecture. In NNI 2.0, trainer.export() has parameters 'file' to save architecture as json, and load using `apply_fixed_architecture`. How can I do this in NNI 2.3?
> 
> Thinks.

I have the same problem and have no idea how to deal with it.

**Comment by ultmaster** [comment]
First of all, we are still figuring out how to support ValueChoice in one-shot trainers. The original solution proposed in paper doesn't support ValueChoice. If you know how, feel free to discuss with us.

Secondly, I think `apply_fixed_architecture` is not yet explicitly added in Retiarii. I think I can do this quickly.
