### ISSUE TITLE
Kubeflow setup

### ISSUE THREAD

**Issue by kruthikakr** [microsoft/nni#3978]
Hi ..I am trying to set up kubeflow with Microk8s ..Is this supported ?  I need information for running nni with kubeflow mode in local . 

I tried with minikube +kubeflow +NFS but for the example 
nnictl create --config mnist-tfv1/config_kubeflow.yml 
INFO:  expand searchSpacePath: search_space.json to /home/kruthika/PycharmProjects/nni/examples/trials/mnist-tfv1/search_space.json 
INFO:  expand codeDir: . to /home/kruthika/PycharmProjects/nni/examples/trials/mnist-tfv1/. 
INFO:  Starting restful server...
INFO:  Successfully started Restful server!
INFO:  Setting kubeflow config...

ERROR: Failed! Error is: None
any help is much appreciated ..

**Comment by kruthikakr** [comment]
@SparkSnail  any inputs for this  ?

**Comment by SparkSnail** [comment]
Hi @kruthikakr , I meet same issue and get same error message as yours, I'm not sure if this is a new bug in 'express-joi-validator' package in using latest node, I've fix the issue in latest NNI master branch, and it is not released yet, it can works in my environment now. You could install NNI from source code and try again, refer https://nni.readthedocs.io/en/stable/Tutorial/InstallationLinux.html#install-nni-through-source-code.
