### ISSUE TITLE
No gpu memory reduction after pruning

### ISSUE THREAD

**Issue by 2730gf** [microsoft/nni#3981]
Describe the issue:
After using the pruning model for yolov5, there is no reduction of gpu memory. The pruning method is FPGM, and the gpu memory test method is to load the model and no other operations are done, including the production of dataloader.

Environment:

NNI version: 2.3
Training service (local|remote|pai|aml|etc):
Client OS:
Server OS (for remote mode only):
Python version:3.6
PyTorch/TensorFlow version:1.7.1
Is conda/virtualenv/venv used?:yes
Is running in Docker?:no
Configuration:

**Comment by J-shang** [comment]
@2730gf Hello, do you use speed-up to reduct the model?

**Comment by 2730gf** [comment]
> @2730gf Hello, do you use speed-up to reduct the model?

I have already use  speed-up to reduct the model. The amount of parameters has been reduced by 50%，but the gpu memory reduced from 1300 to 1200M

**Comment by J-shang** [comment]
> > @2730gf Hello, do you use speed-up to reduct the model?
> 
> I have already use speed-up to reduct the model. The amount of parameters has been reduced by 50%，but the gpu memory reduced from 1300 to 1200M

As my point, the origin weight of yolov5 does not exceed 100M, if we prune 50%, the reduction of gpu memory also will not exceed 100M. Could you provide the size of the weight file changes before and after pruning?

**Comment by 2730gf** [comment]
> > > @2730gf Hello, do you use speed-up to reduct the model?
> > 
> > 
> > I have already use speed-up to reduct the model. The amount of parameters has been reduced by 50%，but the gpu memory reduced from 1300 to 1200M
> 
> As my point, the origin weight of yolov5 does not exceed 100M, if we prune 50%, the reduction of gpu memory also will not exceed 100M. Could you provide the size of the weight file changes before and after pruning?

The size of onnx file is from 80M to 35M

**Comment by J-shang** [comment]
> > > > @2730gf Hello, do you use speed-up to reduct the model?
> > > 
> > > 
> > > I have already use speed-up to reduct the model. The amount of parameters has been reduced by 50%，but the gpu memory reduced from 1300 to 1200M
> > 
> > 
> > As my point, the origin weight of yolov5 does not exceed 100M, if we prune 50%, the reduction of gpu memory also will not exceed 100M. Could you provide the size of the weight file changes before and after pruning?
> 
> The size of onnx file is from 80M to 35M

In this case, I think reducing around 100M GPU mem is normal behavior, because cuda or other kernels will take around 1GB gpu mem.
You can test with only run `torch.rand(1, device='cuda')` and check the GPU usage.

**Comment by 2730gf** [comment]
yeah,I just load the model in cuda and i do not input the data to the model. But the gpu mem only reduce 100M. Is this still normal?

**Comment by J-shang** [comment]
> yeah,I just load the model in cuda and i do not input the data to the model. But the gpu mem only reduce 100M. Is this still normal?

yes, it is normal, the entire model weight size is only around 100M, how can reduce more than the model size... even if you don't load the model in cuda, but only one small tensor in cuda, the gpu usage will also reach around 1GB, you can try `python3 -c "import torch;a=torch.rand(1, device='cuda');import time;time.sleep(60)" &` then `nvidia-smi` to check this.

**Comment by 2730gf** [comment]
Amazing!!!Thank you !
