### ISSUE TITLE
Replace view with reshape

### ISSUE THREAD

**Issue by skeletondyh** [microsoft/nni#3982]
**Describe the issue**:

I ran the darts example. When I computed top5 acc, line 19 in nni/examples/nas/oneshot/darts/utils.py raised RuntimeError:

view size is not compatible with input tensor's size and stride...

It seems after topk (line 9) and transpose (line 10) the tensor becomes non-contiguous and thus view method meets problem.
This issue seems to happen with newer versions of PyTorch (1.7+) and I suggest that we replace all view with reshape in implementation. Reshape would be the same as view if the tensor is contiguous, otherwise it would return a copy 

**Environment**:
- NNI version: 2.3 
- Training service (local|remote|pai|aml|etc): Local
- Client OS: Ubuntu 16.04
- Python version: 3.8
- PyTorch/TensorFlow version: PyTorch 1.9
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Comment by ultmaster** [comment]
I think it has already been done in master.
