### ISSUE TITLE
about speed up

### ISSUE THREAD

**Issue by TaekyungKi** [microsoft/nni#3984]
Hi. I'm new at pruning and NNI. Thanks for NNI.

I'm not sure about the speedup process. I'm trying to prune my model (MODEL) with pre-trained weight by followings steps:
1. load pre-trained weight to my Model
2. select pruner. I used one-shot pruners, level, L1 filter, L2 filter, FPGM.
3. use pruner.compress -> pruner.get_pruned_weights -> pruner.export_model, so obtain two weight files (ext: .pth).
4. Since the weight files obtain at step3 is not actually pruned ones, use ModelSpeedup
5. use apply_compression_results -> put dummy input to the model: ModelSpeedup -> use speedup_model 
6. at this point, when i use torchsummary package, actually the model' size, parameters and FLOPs are reduced (model2 below).
   but when i export the model's state_dict (by torch.save ). The model's size is actually same with the un-pruned one (model1).

Is there any way to get pruned weight with actually reduced size? should i always load pre-trained weights and generate additional files like mask, and speedup the model with the mask whenever i want to do inference or testing? Below is my source code.
 
Thanks ! 

    from torchsummary import summary
    ...
    ...    
    model = MODEL()
    print('=> Loading weights from checkpoint (' + args.trained_model + ')')
    model.load_state_dict(copyStateDict(torch.load(args.trained_model)))
    print("=> Successfully loaded pre-trained model")

    device = torch.device("cuda" if torch.cuda.is_available() else 'cpu')
    model.to(device)
    model.eval()
    
    summary(model, (1,3,768,768))
    
    if device.type == 'cuda' and torch.cuda.device_count() > 0:
        model = nn.DataParallel(model)
        print("=> DataParallel activated.")
    
    if args.pruner == 'level':
        pruner = LevelPruner(model, config_list)
    if args.pruner == 'l1':
        pruner = L1FilterPruner(model, config_list)
    if args.pruner == 'l2':
        pruner = L2FilterPruner(model, config_list)
    if args.pruner == 'fpgm':
        pruner = FPGMPruner(model, config_list)

    no_speedup, mask, speedup = path_builder(args, os.path.join("./pruned_weight", f"{args.pruner}"))
    no_speedup = os.path.join(no_speedup, f"no-speedup-{config_list[0]['sparsity']}" + ".pth")
    mask = os.path.join(mask, f"mask-{config_list[0]['sparsity']}"+".pth")
    speedup = os.path.join(speedup, f"speedup-{config_list[0]['sparsity']}"+".pth")
    
    model = pruner.compress()
    pruner.get_pruned_weights()
    pruner.export_model(model_path = no_speedup, mask_path = mask)

    model2 = MODEL()
    model2.to(device)
    model2.eval()
    dummy_input = torch.randn((1, 3, 768, 768)).to(device)

    apply_compression_results(model2, mask, device)
    for _ in range(32):
        use_mask_out = model2(dummy_input)
    
    m_speedup = ModelSpeedup(model2, dummy_input, mask, device)
    m_speedup.speedup_model()
    for _ in range(32):
        use_speedup_out = model2(dummy_input)

    summary(model2, (1,3,768,768))

    torch.save(model2.state_dict(), speedup)

**Environment**:
- NNI version: 2.3 ( i merged master branch to avoid speedup issues recently reported)
- Training service (local|remote|pai|aml|etc): local
- Client OS: windows
- Server OS (for remote mode only): linux
- Python version: 3.8.10
- PyTorch/TensorFlow version: Pytorch 1.7.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!): config_list = [ {'sparsity': 0.5, 'op_types': ['Conv2d'] } ]

**Comment by J-shang** [comment]
I think this because you prune the `nn.DataParallel(MODEL())`, but speed up the `MODEL()`. You can print the `keys()` of mask dict (the key is the layer name in pruned model) and check if the layer name is matched with `model2`.

If this is not the reason, please tell us.

**Comment by TaekyungKi** [comment]
Hi, i commented out the data parallel. and i got another error:

    RuntimeError: Has not supported infering output shape from input shape for module/function: `prim::TupleUnpack`, .prim::TupleUnpack.75

TupleunPack doesn't not occur before. i already merged the master branch. it  suddenly pop up. i checked my state_dict's keys (un_speedup and mask). The error occurs at m_speedup.speed_model() after m_speedup = ModelSpeedup(model2, dummy_input, mask, device)

**Comment by J-shang** [comment]
HI @TaekyungKi , seems you still use nni version <= 2.3, in master branch we refactor the `speedup`, you can reference this to install nni in dev mode:

https://nni.readthedocs.io/en/stable/Tutorial/SetupNniDeveloperEnvironment.html

In master, this error has been fixed, you could have a try. And the new `speedup` will also be recently released in nni v2.4.

**Comment by TaekyungKi** [comment]
Thanks for the reply! i already cloned master branch and installed it to my envs from 6 days ago.  i don't know why but, TupleUnpack Error occurs suddenly.. 
Aside from that, i created new conda env for doing your advice, and during installation, i got error
    .../nni/toolchain/yarn/bin/yarn', 'build']' returned non-zero exit status 1.

**Comment by J-shang** [comment]
Did you make a new `git clone`? Cause we upgrade the node version, you may need to del all build files under nni directory at first, include `./toolchain`, `./ts/nni_manager/dist`, `./ts/nni_manager/node_modules`, `./ts/webui/build`, `./ts/webui/node_modules`, then install nni.
If you don't want to clean these, recommend clone a new one in another place then install from the new code base.

**Comment by TaekyungKi** [comment]
Yep. i deleted all files under nni. i also tried to do it on new directory and change to other remote server.  and i updated yarn. But still got a same error during installation:
Done in 2.58s.
yarn run v1.22.10
$ tsc && jupyter labextension build .
Please supply at least one subcommand: check, disable, enable, install, link, list, uninstall, unlink, update
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "setup.py", line 243, in <module>
    _setup()
  File "setup.py", line 106, in _setup
    'develop': Develop,
  File "/home/tkki/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/tkki/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/tkki/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/tkki/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 207, in run
    setup_ts.build(release=None)
  File "/home/tkki/light-weight/sample/nni/setup_ts.py", line 42, in build
    compile_ts()
  File "/home/tkki/light-weight/sample/nni/setup_ts.py", line 158, in compile_ts
    _yarn('ts/jupyter_extension', 'build')
  File "/home/tkki/light-weight/sample/nni/setup_ts.py", line 226, in _yarn
    subprocess.run([str(_yarn_path), *args], cwd=path, check=True, env=_yarn_env)
  File "/home/tkki/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/tkki/light-weight/sample/nni/toolchain/yarn/bin/yarn', 'build']' returned non-zero exit status 1.

**Comment by J-shang** [comment]
Seems the error happens when ` jupyter labextension build`, maybe need to `conda install jupyter, jupyterlab` at first.

**Comment by TaekyungKi** [comment]
Um. That's not the reason. same error occurs.

**Comment by J-shang** [comment]
ok, it's sad, please feel free to contact us if you find something.

**Comment by TaekyungKi** [comment]
Hi shang. I solved it. For the installation problem, i had cloned the master branch with git option "--single-branch ". I didn't investigate details of that option, the installation is done without that option. Hope others don't waste time like me. 

Aside from the installation, pruner._unwrap_model() seems working for my pruning. The speedup-ed weight is actually light-weight. Additionally in speedup step, it seems that the pruner try to track the gradients of dummy input tensor even with requires_grad = False or detach() and model.eval(). So i used speedup within torch.no_grad() block. There is no torch.no_grad block in pruning example tutorials.

By the way, is there a way to automatically load model with speedup-ed weight? Of course since pruned, the speedup-ed weight  doesn't match with my model.py when directly load the weight like: model.load_state_dict(torch.load(pruned_weight)).

**Comment by J-shang** [comment]
Hi @TaekyungKi , it is not recommended to use `torch.no_grad()` during speedup, because the gradient usually is needed in the speedup stage.

**Comment by scarlett2018** [comment]
closing the issue as the problem had resolved.
