### ISSUE TITLE
running with aks kubeflow mode

### ISSUE THREAD

**Issue by kruthikakr** [microsoft/nni#3988]
**Describe the issue**:
I am trying to run the mnist example with the kubeflow mode 
The kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
nni-exp-lnjmikx3-trial-xxnec-master-0   1/1     Running   0          4m58s
nni-exp-lnjmikx3-trial-xxnec-worker-0   1/1     Running   0          4m58s

config file 

authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 20
#choice: local, remote, pai, kubeflow
trainingServicePlatform: kubeflow
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: maximize
trial:
  codeDir: .
  worker:
    replicas: 1
    command: python3 dist_mnist.py
    gpuNum: 0
    cpuNum: 1
    memoryMB: 8196
    image: tensorflow/tensorflow
kubeflowConfig:
  operator: tf-operator
  apiVersion: v1
  storage: azureStorage
  keyVault:
    vaultName: automlkey
    name: ExamplePassword
  azureStorage:
    accountName: kubernetstore
    azureShare: myshare
nniManagerIp: 192.168.1.23Events:
  Type     Reason            Age                   From                Message
  ----     ------            ----                  ----                -------
  Warning  FailedScheduling  19m                   default-scheduler   0/3 nodes are available: 2 Insufficient cpu, 3 Insufficient memory.
  Warning  FailedScheduling  19m                   default-scheduler   0/3 nodes are available: 2 Insufficient cpu, 3 Insufficient memory.
  Warning  FailedScheduling  17m                   default-scheduler   0/5 nodes are available: 2 Insufficient cpu, 2 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 3 Insufficient memory.
  Normal   Scheduled         17m                   default-scheduler   Successfully assigned default/nni-exp-lnjmikx3-trial-xxnec-worker-0 to aks-agentpool-32782193-vmss000008
  Normal   TriggeredScaleUp  19m                   cluster-autoscaler  pod triggered scale-up: [{aks-agentpool-32782193-vmss 3->5 (max: 5)}]
  Normal   Pulling           17m                   kubelet             Pulling image "alpine:3.10"
  Normal   Pulled            17m                   kubelet             Successfully pulled image "alpine:3.10" in 6.243755644s
  Normal   Created           17m                   kubelet             Created container init-pytorch
  Normal   Started           17m                   kubelet             Started container init-pytorch
  Normal   Pulled            14m                   kubelet             Successfully pulled image "mapler/pytorch-cpu:latest" in 1m50.75567684s
  Normal   Pulled            12m                   kubelet             Successfully pulled image "mapler/pytorch-cpu:latest" in 2.011354946s
  Normal   Pulled            10m                   kubelet             Successfully pulled image "mapler/pytorch-cpu:latest" in 2.276131316s
  Normal   Created           7m50s (x4 over 14m)   kubelet             Created container pytorch
  Normal   Started           7m50s (x4 over 14m)   kubelet             Started container pytorch
  Normal   Pulled            7m50s                 kubelet             Successfully pulled image "mapler/pytorch-cpu:latest" in 1.97693673s
  Normal   Pulling           5m12s (x5 over 16m)   kubelet             Pulling image "mapler/pytorch-cpu:latest"
  Warning  BackOff           2m15s (x11 over 10m)  kubelet             Back-off restarting failed container

error in the describe pods

**Comment by kruthikakr** [comment]
I am able to solve these errors with adding GPU to the AKS . Now the describe pods shows result :

Normal  Scheduled  2m57s  default-scheduler  Successfully assigned default/nni-exp-ppmdrdk4-trial-xjpkl-worker-0 to aks-nodepool1-37172299-vmss000000
  Normal  Pulling    2m56s  kubelet            Pulling image "msranni/nni:latest"
  Normal  Pulled     2m56s  kubelet            Successfully pulled image "msranni/nni:latest" in 614.997814ms
  Normal  Created    2m55s  kubelet            Created container tensorflow
  Normal  Started    2m55s  kubelet            Started container tensorflow

if the see the err log 

HTTPConnectionPool(host='192.168.1.23', port=8081): Max retries exceeded with url: /api/v1/nni-pai/stdout/5AfKvT3L/SAdeA (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8fe7496a58>, 'Connection to 192.168.1.23 timed out. (connect timeout=10)'))
HTTPConnectionPool(host='192.168.1.23', port=8081): Max retries exceeded with url: /api/v1/nni-pai/stdout/5AfKvT3L/SAdeA (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8fe74392e8>, 'Connection to 192.168.1.23 timed out. (connect timeout=10)'))
HTTPConnectionPool(host='192.168.1.23', port=8081): Max retries exceeded with url: /api/v1/nni-pai/stdout/5AfKvT3L/SAdeA (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8fe7496860>, 'Connection to 192.168.1.23 timed out. (connect timeout=10)'))


Please help me to solve this issue ?

**Comment by SparkSnail** [comment]
@kruthikakr This is because NNI will send metrics back to your nniManager machine from container in AKS, you should make sure the container in AKS could connect your nniManager machine(host machine which start nni experiment), host and port is available to AKS. You could set [nniManagerIp](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.rst#nnimanagerip) in your yaml file to change the host ip address in NNI.

**Comment by kruthikakr** [comment]
nniManagerIp  i have added this ..this should be public IP ?

Also after this i am getting the error 

[2021-07-30 12:11:13.109264] INFO trial_keeper_version is 2.3
[2021-07-30 12:11:13.109345] INFO nni_manager_version is 9
[2021-07-30 12:11:13.109371] WARNING Version does not match!
[2021-07-30 12:11:13.202038] INFO Trial keeper spawns a subprocess (pid 24) to run command: ['python3', 'mnist.py']
2021-07-30 12:11:13.688124: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-07-30 12:11:13.688182: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "mnist.py", line 10, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'
[2021-07-30 12:11:25.291002] INFO subprocess terminated. Exit code is 1. Quit
[2021-07-30 12:11:25.357540] INFO NNI trial keeper exit with code 1

**Comment by kruthikakr** [comment]
@SparkSnail can you please help to solve this ?

**Comment by SparkSnail** [comment]
You are using tensorflow1 code in NNI, but you use `tensorflow/tensorflow` image which installed tensorflow2 environment. Please prepare correct environment for your docker image or use correct trial code.

**Comment by kruthikakr** [comment]
if i need to add few python packages need for the training script .. How to add the packages to the docker images using config.yml file

**Comment by kruthikakr** [comment]
@SparkSnail  : msranni/nni:latest if there are missing packages in the docker image .  what is the way to install it with NNI in loop.

**Comment by SparkSnail** [comment]
Perhaps you could combine the installation command with normal command, like `command: pip install scikit-image && python3 train.py`. The better way is to build your own docker image by yourself , install your specific required packages in your own image.

**Comment by kruthikakr** [comment]
Thank you . I solved it by preparing the docker itself . 
I went through the examples and documentation but there is no option of saving the best model and later using it for serving for inference . Is there any possibility with NNI to save the best model ?

**Comment by SparkSnail** [comment]
No, NNI don't have API to save model directly.

**Comment by kruthikakr** [comment]
Then what is the possible option to save the best model so that we can test the model accuracy ?

**Comment by SparkSnail** [comment]
Are you using NNI to run NAS or HPO?

**Comment by kruthikakr** [comment]
Experimenting the NNI for HPO task .

**Comment by SparkSnail** [comment]
Better to save all modules for all of your trial jobs, you can get the best trial result after experiment finished, and then find the  saved module according to trial id. NNI don't have API to get the best trial in training process, this seems a good idea.

**Comment by kruthikakr** [comment]
Ok thank you .I will be trying it
