### ISSUE TITLE
The remaining time is error when the spent time has exceeded the duration time.

### ISSUE THREAD

**Issue by benchuang11046** [microsoft/nni#4015]
**Describe the issue**:
The remaining time is error when the spent time has exceeded the duration time.

![Imgur](https://i.imgur.com/jqv1ddw.png)

**Environment**: 
- NNI version: `Release 1.9 - 10/22/2020`
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu Linux 4.19.76-linuxkit
- Server OS (for remote mode only):
- Python version: 3.6.9
- PyTorch/TensorFlow version: 2.3.0
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: yes

**Configuration**:
 - Experiment config (remember to remove secrets!):
 
`maxExecDuration: 1h`

 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:

**How to reproduce it?**:
Configure `maxExecDuration` in Experiment config

**Comment by Lijiaoa** [comment]
Yes, it‘s a bug in webui. We will fix it as soon as possible. Thanks for your feedback.

**Comment by Lijiaoa** [comment]
hi, @benchuang11046 in pr #4164, if execDuration is less than maxExperimentDuration, webui will prompt error message.

**Comment by acured** [comment]
Close this issue since it has been fixed.
