### ISSUE TITLE
How could I know the effect of quantization?

### ISSUE THREAD

**Issue by Asahi678** [microsoft/nni#4053]
In order to speed up my network, I want to use quantization of NNI. 
I run the quantizing demo QAT_torch_quantizer.py  and get the results mnist_model.pth and mnist_calibration.pth. However,  the size of quantized model file is the samilar with original model file. And the parameters in model is still float. Is this right?
In inference, I load mnist_model.pth and then compress the model in QAT. It's slower than uncompressed model. It is so weird. Could you give me some advice to verify its effect?

**Comment by linbinskn** [comment]
You have to use quantize speedup module to quantize and speedup the model really. If you want to try, please refer to [quantization speedup example](https://github.com/microsoft/nni/blob/master/examples/model_compress/quantization/mixed_precision_speedup_mnist.py#L82). You can measure model size by exporting TensorRT engine and compare inference time between 32bit and 8bit.

**Comment by Asahi678** [comment]
Thanks for your reply. I was not clearly know the method of using quantized model. According to nni document of quantization  and demo code, I can use quantized model to speedup inference stage. The difference of inference time of the two experiments is obvious.
