### ISSUE TITLE
Error while running "Retiarii Example - Multi-trial NAS"

### ISSUE THREAD

**Issue by xv1nx** [microsoft/nni#4060]
Hi, 
I get the error: _AttributeError: 'NoneType' object has no attribute '__name__'_ while trying to run the raw notebook example of multi-trial.

I am using the latest released version of NNI, Python 3.6, Docker container of Ubuntu 18.04.
 
![image](https://user-images.githubusercontent.com/1759396/129025593-6d7aa927-4889-408a-b465-edebc96146ae.png)

I found a discussion about this error, but the fixed is reverted: 
[https://github.com/microsoft/nni/pull/3337](https://github.com/microsoft/nni/pull/3337)

**Comment by QuanluZhang** [comment]
@xv1nx thanks for reporting this issue. could you check whether this problem still exists in NNI v2.4?

**Comment by scarlett2018** [comment]
> @xv1nx thanks for reporting this issue. could you check whether this problem still exists in NNI v2.4?

@xv1nx - got a chance try the problem on NNI v2.4? the PR shall merged to 2.4.
May you update the status on your side accordingly?

**Comment by xv1nx** [comment]
> > @xv1nx thanks for reporting this issue. could you check whether this problem still exists in NNI v2.4?
> 
> @xv1nx - got a chance try the problem on NNI v2.4? the PR shall merged to 2.4.
> May you update the status on your side accordingly?

sorry for being very late. I tried the new version and the problem is fixed.
