### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: The model does not have an ir_version set properly.

### ISSUE THREAD

**Issue by donglinb** [microsoft/nni#4067]
**Describe the issue**:

When I tried to run the example of nni/examples/model_compress/quantization/mixed_precision_speedup_mnist.py, an error came out which said "onnx.onnx_cpp2py_export.checker.ValidationError: The model does not have an ir_version set properly".
How could I resolve this issue ?

This is complete output:
'''
$ python mixed_precision_speedup_mnist.py 
/anaconda/envs/nni/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448278899/work/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
# Epoch 0 #
/anaconda/envs/nni/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448278899/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
 0%  Loss 2.320023536682129
11%  Loss 0.5889971256256104
21%  Loss 0.4522935748100281
32%  Loss 0.276109904050827
43%  Loss 0.28521373867988586
53%  Loss 0.12202392518520355
64%  Loss 0.14588120579719543
75%  Loss 0.08671293407678604
85%  Loss 0.14353279769420624
96%  Loss 0.06767087429761887
Loss: 0.08850634384155273  Accuracy: 97.29%)

Traceback (most recent call last):
  File "mixed_precision_speedup_mnist.py", line 150, in <module>
    main()
  File "mixed_precision_speedup_mnist.py", line 144, in main
    post_training_quantization_example(train_loader, test_loader, device)
  File "mixed_precision_speedup_mnist.py", line 79, in post_training_quantization_example
    engine.compress()
  File "/home/donglinbai/.local/lib/python3.8/site-packages/nni/compression/pytorch/quantization_speedup/integrated_tensorrt.py", line 290, in compress
    _, self.onnx_config = fonnx.torch_to_onnx(self.model, self.config, input_shape=self.input_shape,
  File "/home/donglinbai/.local/lib/python3.8/site-packages/nni/compression/pytorch/quantization_speedup/frontend_to_onnx.py", line 147, in torch_to_onnx
    onnx.checker.check_model(model_onnx)
  File "/anaconda/envs/nni/lib/python3.8/site-packages/onnx/checker.py", line 106, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: The model does not have an ir_version set properly.
'''

**Environment**:
- NNI version: 2.4a3
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu 18.04.5 LTS
- Server OS (for remote mode only):
- Python version: Python 3.8.10
- PyTorch/TensorFlow version: 1.9.0
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No
- Other:
tensorrt: 8.0.1.6
onnx: 1.10.1
pycuda: 2021.1
GPU: Nvidia Tesla P100
Driver Version: 470.42.01
CUDA Version: 11.4

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by linbinskn** [comment]
Delete original generated TensorRT engine and onnx model can fix this problem.

**Comment by scarlett2018** [comment]
> Delete original generated TensorRT engine and onnx model can fix this problem.

@donglinb - thanks for trying NNI and connect us for help. had you try this out? is the problem fixed on your side?

**Comment by donglinb** [comment]
> > Delete original generated TensorRT engine and onnx model can fix this problem.
> 
> @donglinb - thanks for trying NNI and connect us for help. had you try this out? is the problem fixed on your side?

Yes, it works in my side. Many thanks for your kindly help.
