### ISSUE TITLE
retiarii/oneshot/pytorch/enas.py中在_train_model函数中做self._resample()是不是没意义？

### ISSUE THREAD

**Issue by GeorgeW9527** [microsoft/nni#4069]
**Describe the issue**:
enas在train_model时，不需要每次迭代都对模型进行进行修改~只需要修改一次
（虽然加了self._resample()不影响结果）

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by ultmaster** [comment]
我觉得应该是每个模型 train 一个 mini-batch，然后换一个 mini-batch？

**Comment by GeorgeW9527** [comment]
是我自己理解错了，在train_model的时候，虽然大model不变，但是每次迭代的forward的path是会改变的。
