### ISSUE TITLE
the example of OpenPAI could not run success

### ISSUE THREAD

**Issue by DC-y** [microsoft/nni#4076]
**Describe the issue**:
I have followed the step to run example [OpenPAI Mode Example](https://nni.readthedocs.io/zh/latest/TrainingService/PaiMode.html) ,  failed ...
Could you update the example with the lastest version of NNI？
```shell
ERROR: Config V1 validation failed: SchemaError('If you set useAnnotation=true, please leave searchSpacePath empty',)
```
My config content is as follow:
```shell
authorName: your_name
experimentName: auto_mnist
# how many trials could be concurrently running
trialConcurrency: 2
# maximum experiment running duration
maxExecDuration: 1h
# empty means never stop
maxTrialNum: 10
# choice: local, remote, pai
trainingServicePlatform: pai
# search space file
searchSpacePath: search_space.json
# choice: true, false
useAnnotation: true
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  command: python3 mnist.py
  codeDir: ~/docker/nni/examples/trials/mnist-annotation
  gpuNum: 0
  cpuNum: 1
  memoryMB: 8196
  image: msranni/nni:latest
  virtualCluster: default
  nniManagerNFSMountPath: /mnt/data
  containerNFSMountPath: /mnt/test-storage
  paiStorageConfigName: test-storage
# Configuration to access OpenPAI Cluster
paiConfig:
  userName: xxxxx
  token: eyxxxxyJ1c2VybmFtZSxxxxmZhbHNlLCJqb2JTcGVxvxxxxxxTUwLCJleHAiOjE2MxxxxxnId24Nw-wd2vA3s
  host: https://xx.xx.xx.xx
  # optional, experimental feature.
  reuse: true

```

**Environment**:
- NNI version: v2.4
- Training service (local|remote|pai|aml|etc): pai
- Client OS: ubuntu 18.04
- Server OS (for remote mode only): ubuntu 18.04
- Python version: python3.6
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:
```
 nnictl create --config test.yml 
```

**Comment by SparkSnail** [comment]
From the error log `ERROR: Config V1 validation failed: SchemaError('If you set useAnnotation=true, please leave searchSpacePath empty',)`, please set useAnnotation:false in your configure file.
