### ISSUE TITLE
ERROR: Restful server start failed!  Failed to create log dir: RangeError: Invalid time value

### ISSUE THREAD

**Issue by Stanlay19** [microsoft/nni#4077]
**Describe the issue**:

**Environment**:
- NNI version:2.4
- Training service (local|remote|pai|aml|etc):
- Client OS:Windows 10
- Server OS (for remote mode only):
- Python version:3.7
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

 nnictl create --config nni\examples\trials\mnist-pytorch\config_windows.yml
INFO:  expand searchSpacePath: search_space.json to D:\workspace\nni\examples\trials\mnist-pytorch\search_space.json
INFO:  expand codeDir: . to D:\workspace\nni\examples\trials\mnist-pytorch\.
INFO:  Starting restful server...
ERROR: Restful server start failed!
INFO:   Stdout:
-----------------------------------------------------------------------
                Experiment start time 2021-08-17 13:33:45
-----------------------------------------------------------------------

INFO:   Stderr:
-----------------------------------------------------------------------
                Experiment start time 2021-08-17 13:33:45
-----------------------------------------------------------------------
Failed to create log dir: RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Logger.log (D:\Program\Anaconda3\lib\site-packages\nni_node\common\log.js:54:72)
    at Logger.error (D:\Program\Anaconda3\lib\site-packages\nni_node\common\log.js:41:14)
    at D:\Program\Anaconda3\lib\site-packages\nni_node\main.js:109:33

**How to reproduce it?**:

**Comment by acured** [comment]
Hi @Stanlay19 Thanks for your feedback. 

Which web browser do you use? could you try this on console: "new Date(new Date().toLocaleString()+ " UTC").toISOString()" which got this error, but I can not reproduce it.

**Comment by acured** [comment]
There is a fix about this issue, https://github.com/microsoft/nni/pull/4108. 
Have a try with source code or wait for next release.

**Comment by sisrfeng** [comment]
+1

**Comment by fsmosca** [comment]
> There is a fix about this issue, #4108.
> Have a try with source code or wait for next release.

I have the same issue on win10 with python 3.9, that 4108 does not fix the issue.

**Comment by fsmosca** [comment]
Version 2.4 does not work. Tried 2.3 and it is working so far.

**Comment by scarlett2018** [comment]
> Version 2.4 does not work. Tried 2.3 and it is working so far.

@acured - may we add this to 2.5 test? just make sure that there are no regressions from 2.3 to 2.4 (then 2.5), thanks.

**Comment by liuzhe-lz** [comment]
Fixed in v2.5.
