### ISSUE TITLE
hyper-parameter graph are not showing properly

### ISSUE THREAD

**Issue by ZhiyuanChen** [microsoft/nni#4079]
**Describe the issue**:

hyper-parameter graph are not showing properly

![1629264536(1)](https://user-images.githubusercontent.com/28757366/129842427-2843b27e-c0fd-4303-97c9-e3608b943da1.png)

**Environment**:
- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): remote
- Client OS: ubuntu 18.04
- Server OS (for remote mode only): ubuntu 18.04
- Python version: 3.8
- PyTorch version: 1.8.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**How to reproduce it?**:

**Comment by Lijiaoa** [comment]
Hi, @ZhiyuanChen~ Thanks for reporting this issue. I'm also interested in your issue about this hyper-parameter graph. Could you submit the message on here or upload a file to introduce the content of `Experiment summary` on the nav bar? It's useful message to debug this question.

![image](https://user-images.githubusercontent.com/61399850/130191258-0b5dcf29-fccb-4ac4-9eb0-d7525db11104.png)

**Comment by ZhiyuanChen** [comment]
> Hi, @ZhiyuanChen~ Thanks for reporting this issue. I'm also interested in your issue about this hyper-parameter graph. Could you submit the message on here or upload a file to introduce the content of `Experiment summary` on the nav bar? It's useful message to debug this question.
> 
> ![image](https://user-images.githubusercontent.com/61399850/130191258-0b5dcf29-fccb-4ac4-9eb0-d7525db11104.png)

Can I send you via teams? It could involve confidential information.

**Comment by Lijiaoa** [comment]
It's ok. my alias is `v-ligu`.

**Comment by scarlett2018** [comment]
> It's ok. my alias is `v-ligu`.

@Lijiaoa - may you help to update the latest status of this problem? thanks.

**Comment by Lijiaoa** [comment]
@scarlett2018 zhiyuan had sloved this issue by changing his experiment code, but seems like he forgot to close this issue. I think we could close this issue.

**Comment by ZhiyuanChen** [comment]
I dont recall this issue has been resolved... we weren't doing any hp searching recently.
I'll close it for now, and re-open it should I encounter it again
