### ISSUE TITLE
Exponential Notation is not allowed anymore

### ISSUE THREAD

**Issue by immonomono** [microsoft/nni#4080]
**Describe the issue**:
After when I update version to 2.4, exponential notation is not working.

When I use v2.1, exponential notation was no issue
{
   "weightDecay": {"_type":"uniform", "_value":[1e-7, 1e-5]}
}

from v2.4, following error was occured
ERROR (nni.common.hpo_utils/Thread-1) search space "weightDecay" (uniform) must have float values : OrderedDict([('_type', 'uniform'), ('_value', ['1e-7', '1e-5'])])

But when I convert exponential notation to float, it is working. 
Should I not use exponential notation?

**Environment**:
- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): local
- Client OS: Red Hat
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: PyTorch 1.8.1
- Is conda/virtualenv/venv used?: virtualenv
- Is running in Docker?: No

**Configuration**:
 - Search space:
{
   "weightDecay": {"_type":"uniform", "_value":[1e-7, 1e-5]}
}

**Log message**:
 - dispatcher.log:
 ERROR (nni.common.hpo_utils/Thread-1) search space "weightDecay" (uniform) must have float values : OrderedDict([('_type', 'uniform'), ('_value', ['1e-7', '1e-5'])])

**Comment by QuanluZhang** [comment]
@immonomono , thanks for reporting this issue! we have reproduced this issue, will fix it soon.

**Comment by QuanluZhang** [comment]
@immonomono , upgrading pyyaml to >= 5.4 can resolve this issue. we will update the dependency in NNI v2.5

**Comment by immonomono** [comment]
@QuanluZhang, Thanks for the kind explanation.

**Comment by liuzhe-lz** [comment]
Fixed in v2.5.
