### ISSUE TITLE
SyntaxError on WebUI with old version of Firefox

### ISSUE THREAD

**Issue by immonomono** [microsoft/nni#4081]
**Describe the issue**:
After upgrading 2.4, WebUI is not working properly with error like below
SyntaxError: fields are not currently supported             main.d8aa9c3f.js:1:452
There was no problem with nni v2.1, **firefox 65.0.2**

Unfortunatly I have no authority for browser  upgrading 
and I can't access node server where nni is running from outside because of the firewall.
The only way to access WebUI is using built-in firefox with X11-forwarding.

**Environment**:
- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): local
- Client OS: Red Hat
- Server OS (for remote mode only): 
- Python version: 3.8
- PyTorch/TensorFlow version: PyTorch 1.8.1
- Is conda/virtualenv/venv used?: virtualenv
- Is running in Docker?: No

**Comment by immonomono** [comment]
Thanks for reply. WebUI with Firefox 65.0.2 is working on v2.3

**Comment by Lijiaoa** [comment]
As we all know, the front end is updated very fast. We launched support for jupyter in version `2.4`. At the same time, we have done a lot of framework updates. The version cannot be rolled back. I'm sorry to say that. Welcome to PR for it If you could fix this issue.

**Comment by Lijiaoa** [comment]
@cruiseliu Could help close this issue?
