### ISSUE TITLE
nni==2.3 tensorboard uninstall then install get __version__ erro,how solve it?

### ISSUE THREAD

**Issue by DavideHe** [microsoft/nni#4087]
**Describe the issue**:

**Environment**:
- NNI version: 2.3  
- Training service (local|remote|pai|aml|etc):local
- Client OS: win10
- Server OS (for remote mode only):  no
- Python version: 3.6
- PyTorch/TensorFlow version:tf 1.12.0
- Is conda/virtualenv/venv used?:  no
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorboard'
(node:2672) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at NNIManager.setStatus (d:\anaconda3\lib\site-packages\nni_node\core\nnimanager.js:700:77)
    at NNIManager.stopExperimentTopHalf (d:\anaconda3\lib\site-packages\nni_node\core\nnimanager.js:223:14)
    at NNIManager.stopExperiment (d:\anaconda3\lib\site-packages\nni_node\core\nnimanager.js:219:20)
    at process.cleanUp (d:\anaconda3\lib\site-packages\nni_node\main.js:117:38)
    at process.emit (events.js:198:13)
    at processEmit [as emit] (d:\anaconda3\lib\site-packages\nni_node\node_modules\signal-exit\index.js:161:32)
(node:2672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
==================================================================================
But, i install tensorboard.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorboard' has no attribute '\_\_version\_\_'
D:\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
D:\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
D:\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
  stacklevel=1)

 

**How to reproduce it?**:

**Comment by SparkSnail** [comment]
please upgrade to latest v2.4 version and try again.

**Comment by DavideHe** [comment]
> please upgrade to latest v2.4 version and try again.

but 2.4，i come cross this issue -->https://github.com/microsoft/nni/issues/4083. it's the reason that i choose lower version.
