### ISSUE TITLE
Access the stored data in the azure through the NNI trial config

### ISSUE THREAD

**Issue by kruthikakr** [microsoft/nni#4096]
Using NNI on azure platform with Kubeflow .
so when i start a trial , the data and the code will be copied from local ( ubuntu) to azure storage files , it takes more time for huge data transfer.

Would like to know the options : 

1. Can the trial ID can be user defined ?
2. The data stored in the azure storage can be linked with the nni config ?
3. What is the best option to access the data if is stored in the azure storage files only.

The reason being is every time the trial starts with different HPO , the data has to be transferred from local to azure . So how to handle the larger data with NNI ?

Looking for some inputs here ?

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc): kubeflow
- Client OS: ubuntu
- Is conda/virtualenv/venv used?:venv
- Is running in Docker?: yes

**Comment by acured** [comment]
Hi @kruthikakr, have a try with sharedstorage, https://nni.readthedocs.io/en/stable/Tutorial/HowToUseSharedStorage.html?highlight=sharedstorage

**Comment by scarlett2018** [comment]
> Hi @kruthikakr, have a try with sharedstorage, https://nni.readthedocs.io/en/stable/Tutorial/HowToUseSharedStorage.html?highlight=sharedstorage

Closing the issue as the answer has been provided.

@kruthikakr - feel free to reopen if the answer does not resolve your issue, thanks.

**Comment by kruthikakr** [comment]
@acured  : I tried to use the sharedstorage config file , But unable to understand how to link the datastored in the Azure Blob container to the configfile /training  code. 
My training platform is Kubeflow .
Please help me to link the data in the azure blob to the nni manager running at local.
