### ISSUE TITLE
Multi GPU training with nni Retiarii Multi-Trial or One-Shot NAS

### ISSUE THREAD

**Issue by Waerden001** [microsoft/nni#4105]
# Question
If I want to use multiple GPUs (say 8 GPUs) with ```retiarii``` which one of the following is "correct"?
- In Multi-Trial NAS, instantiate a ```pl.Trainer```class with given number of gpus, i.e. ```pl.Trainer(..., gpus=8)```
- In Multi-Trial NAS, set  ```trial_gpu_number=8```  in  a ```RetiariiExeConfig``` instance
- In One-Shot NAS, use one of the implemented one-shot trainers, set ```device=torch.device("cuda")``` and let ```retiarii``` decide how to partition and train the super-model, as well as how to feed/sync data with multiple GPUs. 

Another some-what related question is that 
- Is it possible to use ```pytorch-lightning``` and/or  ```RetiariiExperiment``` with  One-Shot NAS? 

# Multi-Trial 
If we use the multi-trial method and implement a ```Lightning``` object. e.g.
```python
import nni.retiarii.evaluator.pytorch.lightning as pl
from nni.retiarii.experiment.pytorch import RetiariiExperiment

lightning = pl.Lightning(AutoEncoder(),
                         pl.Trainer(max_epochs=10),
                         train_dataloader=pl.DataLoader(train_dataset, batch_size=100),
                         val_dataloaders=pl.DataLoader(test_dataset, batch_size=100))
```

Presumably we can instantiate ```pl.Trainer``` with ```pl.Trainer(..., gpus=8)``` since the class is basically a wrapper of the ```Trainer``` class in ```pytorch-lighting```?

# One-Shot

Assume we use the one-shot trainer ```DartsTrainer``` as shown in the documentation

```python
from nni.retiarii.oneshot.pytorch import DartsTrainer
trainer = DartsTrainer(
    model=model,
    loss=criterion,
    metrics=lambda output, target: accuracy(output, target, topk=(1,)),
    optimizer=optim,
    num_epochs=args.epochs,
    dataset=dataset_train,
    batch_size=args.batch_size,
    log_frequency=args.log_frequency,
    unrolled=args.unrolled
)
trainer.fit()
final_architecture = trainer.export()
```
To the best of my knowledge,  except the fact that we can set ```device=torch.device("cuda")``` in most one-shot trainers, there's no retiarii APIs specifically controls the way we use the GPUs (for example, some API that accept argument like ```gpus=8```).  ```retiarii``` uses multiple GPUs to accelerate the training and exploration process via methods like Mixed-Parallelism and Weight-Sharing, and handles model/data allocation/feed automatically?

**Comment by ultmaster** [comment]
In multi-trial NAS, you should set both gpus=8 in trainer and trial_gpu_number=8 in experiment config.

In one-shot NAS, unfortunately we don't support multi-GPU in one-shot trainers natively due to implementation limitation. So far, you still have to inherit the trainer or copy the trainer code for customization. We have a plan to support one-shot algorithms in a more general framework, which is probably in next few months.

**Comment by scarlett2018** [comment]
Closing the issue as the answer has been provided. 
@Waerden001 - feel free to re-open the issue if the answer does not resolve your question, thanks.

> In multi-trial NAS, you should set both gpus=8 in trainer and trial_gpu_number=8 in experiment config.
> 
> In one-shot NAS, unfortunately we don't support multi-GPU in one-shot trainers natively due to implementation limitation. So far, you still have to inherit the trainer or copy the trainer code for customization. We have a plan to support one-shot algorithms in a more general framework, which is probably in next few months.
