### ISSUE TITLE
Can't run mnist example to verify installation, using conda env

### ISSUE THREAD

**Issue by politecat314** [microsoft/nni#4110]
I installed nni as in the readme.md by doing
`python -m pip install --upgrade nni`

Under the section to verify installation, I followed the steps
`git clone -b v2.4 https://github.com/Microsoft/nni.git`

However, after this, when I do
`nnictl create --config nni\examples\trials\mnist-pytorch\config_windows.yml`
as in the readme.md, I get **ERROR: Please set correct config path!**

So when I checked the directory `nni\examples\trials\mnist-pytorch\config_windows.yml`, config_windows.yml file doesn't even exist! So I think this is an issue with outdate readme.md? 

Everything works as expected when I do: 
`nnictl create --config nni/examples/trials/mnist-pytorch/config.yml`

**Environment**:
- NNI version: 2.4
- Client OS: Windows 10
- Python version: 3.9.6
- conda env

**How to reproduce it?**:
Create a virtual env using conda and activate it. Do:
`python -m pip install --upgrade nni`
`git clone -b v2.4 https://github.com/Microsoft/nni.git`
`nnictl create --config nni\examples\trials\mnist-pytorch\config_windows.yml`

**Comment by JunweiSUN** [comment]
Just use `nni\examples\trials\mnist-pytorch\config.yml` and change the command `python3 mnist.py` to `python mnist.py` in that file. The doc may have not be updated. BTW, you may need to use v2.3 since there is a issue in v2.4, see #4108
