### ISSUE TITLE
cudnn.deterministic been set while import, suggestion to avoid this kind of behavior

### ISSUE THREAD

**Issue by mstczuo** [microsoft/nni#4117]
https://github.com/microsoft/nni/blob/e85f029bd4e4b1bdf3e679893fb6447e4d6b2c79/nni/algorithms/compression/pytorch/pruning/amc/amc_pruner.py#L17

This line of code executes when someone just import `nni.algorithms.compression.pytorch.pruning`, I suggest to move it into the constructor function of `AMCPruner` and reset `cudnn.deterministic` after training because it changed an import setting but does not tell the user.

**Comment by scarlett2018** [comment]
@mstczuo - would you like to submit a PR for the suggestion? thanks.

**Comment by mstczuo** [comment]
> @mstczuo - would you like to submit a PR for the suggestion? thanks.

sure. I have submitted this PR: #4139

**Comment by mstczuo** [comment]
PR #4161 solved this issue.
