### ISSUE TITLE
qustion not bug : could nni show the history log in web when i stop the task?

### ISSUE THREAD

**Issue by DavideHe** [microsoft/nni#4120]
i have a need as below:
i run a "nnictl ..." and it finish , i kill the all pid about nni
then i want check the task agin on the web ui .
--> Is there some command that can show the nni log finished
i found pid command is "xxxx/nni_node/node --max-old-space-size=4096 xxxx/nni_node/main.js --port 8080 --mode local --experiment_id fQR5b76t --start_mode new"
Is there some docs to exlain it,then i cound use it right.

**Comment by acured** [comment]
Hi @DavideHe, have a try with **view** https://nni.readthedocs.io/en/stable/Tutorial/Nnictl.html?highlight=view%20%20mode#nnictl-view

**Comment by scarlett2018** [comment]
closing the issue as the answer has been provided. 

@DavideHe - feel free to reopen if the answer does not solve your issue.
