### ISSUE TITLE
Let BOHB directly use ConfigSpace file

### ISSUE THREAD

**Issue by khituras** [microsoft/nni#4140]
**What would you like to be added**:
The possibility to use a native ConfigSpace configuration file to use with BOHB.

**Why is this needed**:
ConfigSpace is a very sophisticated framework to represent parameter configuration spaces. It supports conditional and forbidden configurations.
The NNI search space does not support conditional parameters directly and, for BOHB, does not support conditionals at all. Forbidden configurations are not supported in any way.

**Without this feature, how does current nni work**：
You use the possibilities that are given via the search space and its translation to ConfigSpace in BOHB which excludes conditionals and forbidden configurations.

**Components that may involve changes**:
* Search space definition
* BOHB advisor initialization

**Brief description of your proposal if any**:
I actually don't see an easy way to tackle this. Two possibilities would be
1. use ConfigSpace to begin with
2. extend NNI's search space definition to include conditionals and and forbidden configurations and translate them appropriately to ConfigSpace within BOHB.

I see that 1. would be a major overhaul that is most probably not desired. Also, ConfigSpace might have properties not desired by the NNI team.
2. Would seem to be quite some work.

For now, I went another, not quite clean, way in a personal NNI fork at https://github.com/khituras/nni:
There, I allow to specify a native ConfigSpace configuration file as a search space parameter like this:
```json
{
    "ConfigSpace": {"_type":"choice", "_value": ["bohb-parameters.pcs"]}
}
```
1. In `launcher.py`, I check if such a parameter is there and, if so, extend the given path with trial code directory to make it absolute
2. In `bohb_advisor.py`, I check again for the `ConfigSpace` parameter and, if found, load the given file directly.

I could create a PR from that. I didn't until now because I don't expect this solution to be favorable for your framework. But it was a quick fix that seems to work fine for me.

**Comment by ultmaster** [comment]
Could you make the "bohb-parameter.pcs" an optional argument for BOHB advisor init function. When this pcs is available, it becomes the search space for tuner and directly ignores the search space json from NNI. I think this is more elegantly than defining a new search space format.

**Comment by khituras** [comment]
Thank you for the response! I would like the optional argument. However, the init function is called in a generic way, as far as I understand the code, so I wouldn't know how to actually pass the .pcs file (or the ConfigSpace .json file; ConfigSpace understands multiple file formats).
Any hints appreciated, I would love to make a useful contribution here.

**Comment by ultmaster** [comment]
Closing as PR has been merged.
