### ISSUE TITLE
AMC pruner for InceptionV3

### ISSUE THREAD

**Issue by dingguodong-826** [microsoft/nni#4155]
Thank you very much for nni's excellent open source. I used the AMC algorithm to automatically prun the inceptionv3. After running Amc_search.py, I got best_model.pth and best_mask.pth. When I executed the second amc_train.py, the description is as follows: 
![017d8e45b258e472f55760d6dbdd629](https://user-images.githubusercontent.com/57715990/132192848-9e035dd2-a4ab-4b2a-a7d7-dea115214331.png)
![3fd0ac9697a97181aed30ff4cf65767](https://user-images.githubusercontent.com/57715990/132192864-b1b581e6-63f9-4f3d-adab-cffbec4ce876.png)
During the fine-tuning of the network, I printed out the output dimensions of some layers, and you can see that some channels were indeed cut off, but the training failed due to the mismatch of the dimensions during training. 
The tutorial I refer to is as follows: https://github.com/microsoft/nni/tree/9a4d0d67506f5e1197238344fed858305fbb4494/examples/model_compress/pruning/amc
All files for performing search and training are in: https://pan.baidu.com/s/1Uq0aaFEcw9P-dyVZ0tFc3Q 提取码：1234 
Is there any solution to the training failure caused by channel mismatch? thank you !

**Comment by zheng-ningxin** [comment]
Hi, thanks for the valuable feedback!!
I run the code on your checkpoint and find that you have pruned the 320th-1088th input channel of the `fc` linear which will lead to cut off one of the branches in the Inception model as shown in the following figure.

![image](https://user-images.githubusercontent.com/49771382/132675078-944405f0-abe1-4aa2-a7e9-6a83d67d241b.png)

Pruning a layer to empty currently is not legal in speedup. To work around this problem you can use the `exclude` primitive in the config_list to exclude the FC in the pruning.
