### ISSUE TITLE
Sharedstorage for Kubeflow to link the data stored in the Azure blob

### ISSUE THREAD

**Issue by kruthikakr** [microsoft/nni#4157]
Hi i am facing issue , please guide me
**Describe the issue*
I am trying to do HPO for object detection model in the kubeflow mode , the code directory has data which is of 10GB . And i am using azure storage and this is my config file :

authorName: default
experimentName: example_dist_pytorch
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 1
trainingServicePlatform: kubeflow
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  codeDir: .
  master:
    replicas: 1
    command: python3 dist_mnist.py
    gpuNum: 0
    cpuNum: 1
    memoryMB: 4096
    image: tensorflow/tensorflow
  worker:
    replicas: 1
    command: python3 dist_mnist.py
    gpuNum: 0
    cpuNum: 1
    memoryMB: 4096
    image: mapler/pytorch-cpu:latest
kubeflowConfig:
  operator: pytorch-operator
  apiVersion: v1
  storage: 
  keyVault:
    vaultName: 
    name: 
  azureStorage:
    accountName: 
    azureShare: 

The training is not being started , giving error as 

Error message is {"error":"Error: File total size too large in code dir (315750676 bytes already scanned, exceeds 300MB)."}
ERROR: Failed! Error is: None

I checked with the shared storage option https://nni.readthedocs.io/en/stable/Tutorial/HowToUseSharedStorage.html  As i see in the example config , the training platform is remote . But i am running NNI from Local to Kubeflow mode, 

I am looking for option to link the data stored in the azure blob to the nni manager and my training code here in the local .

**Comment by acured** [comment]
Hi @kruthikakr , "Kubeflow" training service do not support sharedstorage for now, sorry for that, you can run it at remote mode if you want using sharedstorage.
