### ISSUE TITLE
Small spelling error when executing NNI via Python Script

### ISSUE THREAD

**Issue by JanikPi** [microsoft/nni#4158]
**Describe the issue**:
When launching a nni-computation via a python script the following output is shown:
![Spelling-error](https://user-images.githubusercontent.com/75477075/132204866-c903fe32-05b0-44fb-9ea8-dbaa8b185be8.png)

It says 'Statring' instead of 'Starting'.
I have seen this minor error for quite some time now and just wanted to let you know about this.

**Comment by acured** [comment]
Thanks, It has been fixed. Can you pull the latest code and have a try?
