### ISSUE TITLE
[Won't Fix] A document for restAPI instruction for user

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#417]
Like this: 
https://github.com/Microsoft/pai/blob/master/docs/rest-server/API.md

**Comment by xuehui1991** [comment]
Yan will investigate nodejs comments to doc.

**Comment by leckie-chn** [comment]
> Yan will investigate nodejs comments to doc.

will investigate on [TypeDoc](https://typedoc.org/)

**Comment by scarlett2018** [comment]
Will implement a Python API and will expose that to external usage.
