### ISSUE TITLE
Serialization of custom dataset

### ISSUE THREAD

**Issue by Annika10** [microsoft/nni#4179]
I try to use in some way the [multi_trial](https://github.com/microsoft/nni/blob/master/examples/nas/oneshot/spos/multi_trial.py) example but with my own custom dataset. When I run it, I get in my `nni_experiments` folder in the `stderr` file for each trial following error: 
```
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch
```
I assume the issue is that I do not serialize my dataset. But I'm not even sure how to do this because I have a `TensorDataset` and not a `VisionDataset` like in your examples. Do you have any examples or description how to serialize a TensorDataset?

**Environment**:
- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu 18.04
- Python version: Python 3.8.11
- PyTorch/TensorFlow version: torch 1.9.0
- Is conda/virtualenv/venv used?: venv
- Is running in Docker?: No

**Comment by ultmaster** [comment]
You might want to wrap `TensorDataset` with serialize like `serialize(TensorDataset, x, y)`. However this might not be successful, as serialize requires "recursive serializable" and both x and y need to be serializable. As far as I know, pytorch tensor cannot be directly serialized.

One workaround is to wrap the whole TensorDataset into a VisionDataset-like dataset. An example is as follows:

```python
class MyDataset(TensorDataset):
  def __init__():
    # initialize x and y and ...
    super().__init__(x, y)
```

Then you can use `serialize(MyDataset)`.

**Comment by Annika10** [comment]
I will try it!

**Comment by Annika10** [comment]
Hmm the code runs but I'm getting again the original Error in my trials stderr: 

```
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch
```

I don't know why the dataloader returns zero because when I check the lengths of the dataloader in the classification beforehand it returns a length equal to one. 

This is a draft of my code: 
```

    # hyper parameters
    batch_size = 512

    timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

    model = Model()

    # save training
    device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
    os.makedirs("savings/" + timestamp + "/")
    torch.save(model, "savings/" + timestamp + "/" + "model")  # for netron visuaisation
    model.to(device)

    # own constraint
    simple_strategy = strategy.Random(model_filter=ModelParameterFilter(threshold=700))

    tmp_train_dataset = serialize(MyDataset, x_train, y_train)
    tmp_valid_dataset = serialize(MyDataset, x_valid, y_valid)

    trainer = pl.Classification(train_dataloader=pl.DataLoader(tmp_train_dataset, batch_size=batch_size),
                                val_dataloaders=pl.DataLoader(tmp_valid_dataset, batch_size=batch_size * 2),
                                max_epochs=2)

    # define experiment
    exp = RetiariiExperiment(model, trainer, strategy=simple_strategy)

    exp_config = RetiariiExeConfig('local')
    exp_config.trial_concurrency = 2
    exp_config.max_trial_number = 2
    #exp_config.trial_gpu_number = 1
    #exp_config.training_service.use_active_gpu = False
    # for using pure python engine this needs to be commented out (https://nni.readthedocs.io/en/stable/NAS/ExecutionEngines.html)
    # exp_config.execution_engine = 'base'
    # exp_config.dummy_input = [1, 3, 32, 32]

    exp.run(exp_config, 8081)
```

**Comment by Annika10** [comment]
Could solve it by serialize the dataset alone with my x and y data items. Thanks!
