### ISSUE TITLE
hard to debug

### ISSUE THREAD

**Issue by benwu232** [Microsoft/nni#418]
I'm trying to use annotation in my own code by following the examples and the doc 
[https://microsoft.github.io/nni/docs/howto_1_WriteTrial.html#nni-python-annotation](url).

I just tried adding one variable

> """@nni.variable(nni.choice(0.5, 0.9), name=dropout_rate)"""

 and the output

> """@nni.report_final_result(best_score)"""

 
into my code, and 

> useAnnotation: true

in config.yml.

When I running the config.yml, the webgui displayed well, but all trials were failed. Becaue all my output to the screen and logger are disappeared (blocked?), I can hardly find where the error is.  Here is a screenshot. I don't know why the default metric are NaNs. 

![image](https://user-images.githubusercontent.com/3946864/49215047-de361b80-f402-11e8-9326-1419c4bb33a1.png)

Is there any good way to debug in such case?

Thanks a lot!

**Comment by Crysple** [comment]
Hi, your output and logger in the trial.py will be redirected to trial.log, whose location is shown in the webui. You can click the '+' in the left of a trial to expand it, and the logpath is shown in the bottom.
BTW, the stderr is also in the same directory

**Comment by benwu232** [comment]
@Crysple Thank you very much! 
I found the log. Now I am analyzing it!
