### ISSUE TITLE
NNI FAILED: gpu_metrics file does not exist!

### ISSUE THREAD

**Issue by ibowennn** [microsoft/nni#4187]
**Describe the issue**:
The NNI failed the moment I run my project, which reported: "gpu_metrics file does not exist". But I can run the mnist-pytorch demo.

I have checked that the gpu_metrics file exist in /tmp/*/nni/script
![image](https://user-images.githubusercontent.com/51699450/133473658-c377d904-10d9-4e09-9ba5-4a221e3598b4.png)

**Environment**:
- NNI version: 2.3
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu 20.04
- Server OS (for remote mode only):
- Python version: python 3.8
- PyTorch/TensorFlow version: 1.9
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - authorName: Bowen
experimentName: cem
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 10
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
localConfig:
  useActiveGpu: true
  gpuIndices: 1
  maxTrialNumPerGpu: 4
trial:
  command: python train_nni.py
  codeDir: .
  gpuNum: 1

 - Search space:
 - {
  "optimizer":{"_type":"choice", "_value":["Adam", "Adamax", "Adagrad", "RMSprop", "Adagrad"]},
  "Transpose":{"_type":"choice", "_value":[0.3, 0.4, 0.5]},
  "HorizontalFlip":{"_type":"choice", "_value":[0.3, 0.4, 0.5]},
  "VerticalFlip":{"_type":"choice", "_value":[0.3, 0.4, 0.5]},
  "ShiftScaleRotate":{"_type":"choice", "_value":[0.3, 0.4, 0.5]},
  "hue_shift_limit":{"_type":"choice", "_value":[0.2, 0.3, 0.4]},
  "sat_shift_limit":{"_type":"choice", "_value":[0.2, 0.3, 0.4]},
  "val_shift_limit":{"_type":"choice", "_value":[0.2, 0.3, 0.4]},
  "HueSaturationValue":{"_type":"choice", "_value":[0.3, 0.4, 0.5]}
}

**Log message**:
 - nnimanager.log:
 - [nnimanager.log](https://github.com/microsoft/nni/files/7171866/nnimanager.log)
 - dispatcher.log:
 - [dispatcher.log](https://github.com/microsoft/nni/files/7171870/dispatcher.log)

 - nnictl stdout and stderr:
 (pytorch) bowen@fsk-workstation:~$ nnictl log stdout
[2021-09-16 00:38:47] INFO (numexpr.utils/MainThread) Note: NumExpr detected 48 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2021-09-16 00:38:47] INFO (numexpr.utils/MainThread) NumExpr defaulting to 8 threads.
-----------------------------------------------------------------------
                Experiment start time 2021-09-16 00:38:31
-----------------------------------------------------------------------

(pytorch) bowen@fsk-workstation:~$ nnictl log stderr
[2021-09-16 00:39:15] INFO (numexpr.utils/MainThread) Note: NumExpr detected 48 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2021-09-16 00:39:15] INFO (numexpr.utils/MainThread) NumExpr defaulting to 8 threads.
-----------------------------------------------------------------------
                Experiment start time 2021-09-16 00:38:31
-----------------------------------------------------------------------

**How to reproduce it?**:

**Comment by ibowennn** [comment]
Solved.

**Comment by wubo2180** [comment]
How to solve it?
