### ISSUE TITLE
support running multiple experiments on the same machine

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/nni#42]
In the current implementation, the port of the rest server in an experiment is fixed, i.e., 51188. Therefore, different experiments cannot run simultaneously on the same machine due to port conflict.

**Comment by scarlett2018** [comment]
@chicm-ms - may we close this item? as we already has the basic support in V0.3.0.

**Comment by chicm-ms** [comment]
> @chicm-ms - may we close this item? as we already has the basic support in V0.3.0.

Yes, it can be closed.
