### ISSUE TITLE
gpu_metrics file does not exist! on windows 10

### ISSUE THREAD

**Issue by wubo2180** [microsoft/nni#4226]
**Describe the issue**:
On windows 10，I can not use gpu to get nni start since there is a warning “gpu_metrics file does not exist!”. And I see here
![image](https://user-images.githubusercontent.com/47293569/135120484-d9ed798e-2463-49b5-b8b7-fca38af33b81.png)
[https://nni.readthedocs.io/en/stable/Tutorial/ExperimentConfig.html?highlight=useActiveGpu#useactivegpu](url). So is there another solution for the problem?

**Environment**:
- NNI version: 2.3
- Training service (local|remote|pai|aml|etc): local
- Client OS: windows 10
- Server OS (for remote mode only): None
- Python version: 3.8..8
- PyTorch/TensorFlow version: Pytorch 1.9.0
- Is conda/virtualenv/venv used?:  Using conda
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!): `authorName: default
experimentName: test
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
trainingServicePlatform: local

searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
localConfig:
  useActiveGpu: true
trial:
  command: python test.py
  codeDir: .
  gpuNum: 1`
 - Search space: `{
    "batch_size": {"_type":"choice", "_value": [16, 32, 64, 128]},

    "lr":{"_type":"choice","_value":[0.0001, 0.001, 0.01, 0.1]},

    
}`

**Log message**:
 - nnimanager.log: [2021-09-28 22:39:37] WARNING (GPUScheduler) gpu_metrics file does not exist!
 - dispatcher.log: `[2021-09-28 22:37:11] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-09-28 22:37:11] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001007 seconds
[2021-09-28 22:37:11] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-09-28 22:49:50] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2021-09-28 22:49:52] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated`
 - nnictl stdout and stderr: None
 

**How to reproduce it?**:

**Comment by wubo2180** [comment]
I used example code (e,g, mnist.py) and it failed either on my machine. But when I run the code in my notebook, it works. So I want to know if NNI is hardware-related. My PC: cpu: ryzen 2700x memory: 64G GPU:1080ti * 2. My notebook: cpu: i5 9400 memory:16G GPU:1660ti. The most important key is that I can not find gpu_metrics file in ’C:\Users\***\AppData\Local\Temp\***\nni\script‘  on my PC.

**Comment by SparkSnail** [comment]
@wubo2180 @EroData  NNI use `nvidia-smi` command to get gpu information and generate gpu_metric file, here are some tips you could check:
1. Check if `nvidia-smi` commands works in your machine.
2. `gpu_metrics` file will be generated under `/tmp/{username}/nni/script` in linux and `C:\Users\{user}\AppData\Local\Temp\nni\script` in windows, you could check if you have permission to write files under the path. There will be stdout and stderr file under the path, you could check the error log when the experiment is running.
3. Run `METRIC_OUTPUT_DIR=${scriptFolder} python3 -m nni.tools.gpu_tool.gpu_metrics_collector` to check if NNI gpu metrics command could run under your temp path.

**Comment by scarlett2018** [comment]
Closing the issue as the question has been answered, feel free to reopen if you have question with the answer.

**Comment by WeigangLu** [comment]
> @wubo2180 @EroData NNI use `nvidia-smi` command to get gpu information and generate gpu_metric file, here are some tips you could check:
> 
> 1. Check if `nvidia-smi` commands works in your machine.
> 2. `gpu_metrics` file will be generated under `/tmp/{username}/nni/script` in linux and `C:\Users\{user}\AppData\Local\Temp\nni\script` in windows, you could check if you have permission to write files under the path. There will be stdout and stderr file under the path, you could check the error log when the experiment is running.
> 3. Run `METRIC_OUTPUT_DIR=${scriptFolder} python3 -m nni.tools.gpu_tool.gpu_metrics_collector` to check if NNI gpu metrics command could run under your temp path.

<img width="1268" alt="image" src="https://github.com/microsoft/nni/assets/82763310/52018801-680f-4d96-bf49-d5adfc83e20e">

I have this problem.
gpu_metrics_collector error: syntax error: line 1, column 0

**Comment by redLinmumu** [comment]
> 

When I check 3, I got msgs like:
{'Timestamp': 'Wed Aug 30 17:47:03 2023', 'gpuCount': 3, 'gpuInfos': [{'index': 0, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 1, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 2, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}]}
{'Timestamp': 'Wed Aug 30 17:47:16 2023', 'gpuCount': 3, 'gpuInfos': [{'index': 0, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 1, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 2, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}]}
{'Timestamp': 'Wed Aug 30 17:47:29 2023', 'gpuCount': 3, 'gpuInfos': [{'index': 0, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 1, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 2, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}]}
{'Timestamp': 'Wed Aug 30 17:47:42 2023', 'gpuCount': 3, 'gpuInfos': [{'index': 0, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 1, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 2, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}]}
{'Timestamp': 'Wed Aug 30 17:47:56 2023', 'gpuCount': 3, 'gpuInfos': [{'index': 0, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 1, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 2, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}]}
{'Timestamp': 'Wed Aug 30 17:48:09 2023', 'gpuCount': 3, 'gpuInfos': [{'index': 0, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 1, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 2, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}]}
{'Timestamp': 'Wed Aug 30 17:48:22 2023', 'gpuCount': 3, 'gpuInfos': [{'index': 0, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 1, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 2, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}]}
{'Timestamp': 'Wed Aug 30 17:48:36 2023', 'gpuCount': 3, 'gpuInfos': [{'index': 0, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 1, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 2, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}]}
{'Timestamp': 'Wed Aug 30 17:48:49 2023', 'gpuCount': 3, 'gpuInfos': [{'index': 0, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 1, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}, {'index': 2, 'gpuUtil': '0', 'gpuMemUtil': '0', 'activeProcessNum': 0}]}



But when I check 2, there are "pid  stderr  stdout" there files under folder script. So what can I do?

**Comment by feiguofeiguo** [comment]
I meet the same problem, when i  check the stderr ,it show that the nni use base environment  rather than my conda environment  , even i  designate the conda environment  in command line(config.yaml).
So I install nni package in base environment , and then solve this question.
Hope help someone.
