### ISSUE TITLE
error when using annotation

### ISSUE THREAD

**Issue by benwu232** [Microsoft/nni#423]
I tried the mnist-annotation example and everything is ok. When I tried to use annotation in my own code, there is something wrong.

Here is the code:
> """@nni.variable(nni.uniform(0.5, 0.99), name=self.fc_dropout_keep)"""
        self.fc_dropout_keep = pars['fc_dropout_keep']
        self.fc_dropout1 = nn.Dropout(1 - self.fc_dropout_keep)

I also add some other code such as nni.report_final_result() and useAnnotation: true to make the code runnable. But when running, I got: TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
It seems nni.uniform() return a None value. I checked the generated code, which uses

> self.fc_dropout_keep = nni.uniform(0.5, 0.99, name=
            'self.fc_dropout_keep')

to replace the following line, but it doesn't work.

Is there anything wrong? 
BTW, when I trying disable annotation and used search_space.json, the code worked.
Many thanks!

**Comment by QuanluZhang** [comment]
could you provide your code and your experiment config file, so that we can reproduce your problem.

**Comment by benwu232** [comment]
Sorry! The code is quite messy. I double checked. I only changed the places mentioned above. And the model class and fit function are in different files.
here is the screenshot of webgui
![image](https://user-images.githubusercontent.com/3946864/49271108-3f172f80-f4a7-11e8-877f-c451912eccb5.png)
and config file

> authorName: WB
experimentName: qute
trialConcurrency: 1
maxExecDuration: 100d
maxTrialNum: 10000
#choice: local, remote
trainingServicePlatform: local
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: true
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #optimize_mode: minimize
trial:
  command: python qfapp_nni.py yaml/new3.yaml
  codeDir: .
  gpuNum: 1

**Comment by QuanluZhang** [comment]
Could you provide the full error log: 
provide the file `~/nni/experiments/{your_exp_id}/log/nnimanager.log`, and also provide one trial's error log `~/nni/experiments/{your_exp_id}/trials/{your_trial_id}/stderr`.

**Comment by benwu232** [comment]
[nnimanager.log](https://github.com/Microsoft/nni/files/2632593/nnimanager.log)

[stderr.txt](https://github.com/Microsoft/nni/files/2632595/stderr.txt)

**Comment by QuanluZhang** [comment]
we made a change on nni annotation in v0.3, in order to support multi-phase tuning in a single trial. That is,  `'''@nni.get_next_parameter()'''`, as shown in https://github.com/Microsoft/nni/blob/master/examples/trials/mnist-annotation/mnist.py#L233. This annotation will be replaced by a function of retrieving hyperparameters. Only with this line, the hyperparameters will be obtained by the trial, then could be read by other annotation lines.
We will update doc to make this more clear.
