### ISSUE TITLE
The model of pruning didn't become smaller ?

### ISSUE THREAD

**Issue by moyans** [microsoft/nni#4230]
**Describe the issue**:
I hope to get a small model through structured pruning， But when I execute Modelspeedup, the saved model size becomes larger？

**Environment**:
- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: torch1.9
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: NO

**Comment by J-shang** [comment]
Hi @moyans, could you show your pruning and speedup code for our reference?

**Comment by J-shang** [comment]
Hi @moyans , the model pass to `ModelSpeedup` should be the original structure model, and the model pass to the pruner will be wrapped, so you need to add
`pruner._unwrap_model()`
to unwrap the model, before
`m_speedup = ModelSpeedup(model, dummy_input, mask_file='pruned_model_mask.pth')`
or just
`m_speedup = ModelSpeedup(resnet50().to(devices), dummy_input, mask_file='pruned_model_mask.pth')`

**Comment by moyans** [comment]
@J-shang Thank you for sucessfully solving my problem.
finally
origin.pth 98M
pruned_speedup_model.pth 45M
