### ISSUE TITLE
Some document seems to be outdated.

### ISSUE THREAD

**Issue by louis-she** [microsoft/nni#4232]
Many parts of the documents are outdated, and even 404 link.

For example:
the bottom link `standalone mode` in the doc page https://nni.readthedocs.io/en/latest/Tutorial/HowToDebug.html is 404.

**Comment by Fiascolsy** [comment]
Thank you for discovering the problems, I have fixed 2 of them at PR #4240. We would continue to do this!

**Comment by scarlett2018** [comment]
closing the issue as the PR has been merged.
