### ISSUE TITLE
Google drive url of NAS-bench-201 is invalid

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#4233]
```bash
https://github.com/microsoft/nni/blob/master/examples/nas/benchmarks/nasbench201.sh
```

The following url is invalid: https://drive.google.com/uc\?id\=1OOfVPpt-lA4u2HJrXbgrRd42IbfvJMyE

**Comment by ultmaster** [comment]
Please wait for this PR: https://github.com/microsoft/nni/pull/4205
