### ISSUE TITLE
[Model Compression] Mobilenet_v2 After SpeedUp Encounterd Size Mismatch

### ISSUE THREAD

**Issue by Veal98** [microsoft/nni#4247]
**torchvision.models.mobilenet_v2, it pruned successful and it also SpeedUp  successful, but when i use the .pth generater by SpeedUp to inference, some errors occurred, it tells me that size mismatch**:

**Environment**:

- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu 16.04
- Python version: 3.7
- PyTorch version: 1.9
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**How to reproduce it?**:

It's easy to reporduce this problem, there is only one file, look :down

```java
if __name__ == "__main__":
    net = torchvision.models.mobilenet_v2(pretrained=True)
    dummy_input = torch.rand(1, 3, 416, 416)
    start = time.time()
    out = net(dummy_input)
    print('Before Pruning, the Time Latency: ', time.time() - start)


    cfg = [{ 'sparsity': 0.7, 'op_types': ['Conv2d'] }]
    pruner = L1FilterPruner(net, cfg)
    pruner.compress()
    pruner.export_model('test/mobile_v2_mask.pth', 'test/mobile_v2_mask')
  
    
    start = time.time()
    out = net(dummy_input)
    print('After Pruning, the Time Latency: ', time.time() - start)

    
    another = torchvision.models.mobilenet_v2()
    state_dict = torch.load('test/mobile_v2_mask.pth')
    another.load_state_dict(state_dict)

    ms = ModelSpeedup(another, dummy_input, 'test/mobile_v2_mask')
    ms.speedup_model()
    torch.save(another.state_dict(), 'test/speedup_model.pth')
    
    start = time.time()
    out = another(dummy_input)
    print('After SpeedUp, the Time Latency: ', time.time() - start)

    another = torchvision.models.mobilenet_v2()
    state_dict = torch.load('test/speedup_model.pth')
    another.load_state_dict(state_dict)
```

**Comment by zheng-ningxin** [comment]
This is in line with expectations. The shape of the model weights after speedup has changed. You cannot load the speeduped weights with the original mobilenet_v2.  You should directly finetune/inference after the speedup rather than create a new original mobilenet_v2.

**Comment by J-shang** [comment]
Speedup will modify the model structure, so if you want to save the model after speedup, you should save the entire model, `torch.save(another, 'test/speedup_model.pth')`
