### ISSUE TITLE
smac problem

### ISSUE THREAD

**Issue by benwu232** [Microsoft/nni#426]
When trying SMAC, I got this error
ValueError: Negative lower bound (-9.000000) for log-scale hyperparameter l2_scale is forbidden.
Here is the search_space.json
{
    "fc_dropout_keep":{"_type":"uniform","_value":[0.5, 0.99]},
    "l2_scale":{"_type":"loguniform","_value":[-9, -2.3]}
}
The parameters are ok in TPE. I'm not so familiar with SMAC. The doc said It support loguniform. Anybody tell me what is wrong?
Thanks!

**Comment by QuanluZhang** [comment]
loguniform does not support negative number. the expression of loguniform is `exp(uniform(log(low), log(high)))`.

**Comment by benwu232** [comment]
Thanks @QuanluZhang 

I just did a test,
in TPE:

>     "learning_rate":{"_type":"loguniform","_value":[-11.6, -5.8]},

in SMAC:

>     "learning_rate":{"_type":"loguniform","_value":[0.00001, 0.003]},

Am I right?

**Comment by benwu232** [comment]
when I set 

> "learning_rate":{"_type":"loguniform","_value":[0.00001, 0.003]}

I found in webgui

>  "learning_rate": {
        "_type": "loguniform",
        "_value": [
            1.0000230261160268,
            1.0069316688518042
        ]
    },
seems not right, cuz 10 ** 0.003 = 1.0069316688518042
is there any clear equation for this?

**Comment by QuanluZhang** [comment]
TPE and SMAC have different interpretation of `loguniform`. 
In TPE, `loguniform` means `exp(uniform(low, high))`. In SMAC, `loguniform` means `uniform(exp(low), exp(high))`. 
These are confusing, thus, we unified the meaning of `loguniform` among all our supported tuners, it means `exp(uniform(log(low), log(high)))`. This change is included in nni v0.4 release, which will be released next week.

**Comment by benwu232** [comment]
Dazzling!
I make some examples, correct me if I am wrong.
If lr [0.01, 0.1] in loguniform,
in TPE and SMAC: lr [np.log(0.01), np.log(0.1)], although the actual values are different.
in NNI: lr [0.01, 0.1]. More clear. 
Looking forward to the next version!
Good job!

**Comment by QuanluZhang** [comment]
In TPE and SMAC: lr [np.exp(0.01), np.exp(0.1)]. 
There is still difference between TPE and SMAC. To be more specific, TPE uniformly random a number `n` between 0.01 and 0.1, then returns the value np.exp(`n`), while SMAC uniformly random and return the value between np.exp(0.01) and np.exp(0.1).

**Comment by QuanluZhang** [comment]
Yes, the display on webui is not correct in v0.3, and will be fixed in v0.4
