### ISSUE TITLE
NAS search space Repeat raise error

### ISSUE THREAD

**Issue by aimfreshwater** [microsoft/nni#4294]
**Describe the issue**:
Search space module "Repeat" doesn't work at one-shot nas DARTS, ENAS

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu 18
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: 1.8
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: yes

**Configuration**:
 - Experiment config (remember to remove secrets!): use oneshot DartsTrainer
 - Search space: `Repeat`

**Log message**:
 - nnimanager.log:X
 - dispatcher.log:X
 - nnictl stdout and stderr:X
 - stderr :  KeyError: "Fixed context with `num_of_block` not found. Existing values are:  ~~~
 the num_of_block is label that I give like this
        self.body_center_00 = Repeat(Block(128, self.act), (2, 20), label='num_of_block')
 
when I give search space with Repeat at one-shot NAS like DARTS, ENAS, it trained well but can't export model.
error : KeyError: "Fixed context with `num_of_block` not found. Existing values are:  ~~~ like this

**How to reproduce it?**:

**Comment by ultmaster** [comment]
`Repeat` is not supported for one-shot algorithm like DARTS and ENAS. It's a surprise that it can run, but you can use a multi-trial strategy.
