### ISSUE TITLE
Chinese doc discussion

### ISSUE THREAD

**Issue by liuzhe-lz** [microsoft/nni#4298]
The table below shows monthly viewed times for top 30 doc pages, ordered by readthedocs catalogue.

These pages should be translated in this release: (15 in total)
- [x] Readme (index) @scarlett2018 
- [ ] Installation @SparkSnail 
- [ ] 　　Linux & Mac @SparkSnail 
- [ ] 　　Windows @SparkSnail 
- [x] QuickStart @JiahangXu 
- [ ] Auto (Hyper-parameter) Tuning @liuzhe-lz 
- [ ] 　　Write Trial @QuanluZhang 
- [ ] 　　Tuners (merge with Overview) @liuzhe-lz 
- [x] 　　WebUI @Lijiaoa
- [x] Neural Architecture Search @ultmaster 
- [x] 　　Quick Start @ultmaster 
- [x] Model Compression @Fiascolsy 
- [ ] 　　Overview @J-shang
- [ ] 　　Quick Start @linbinskn

**Comment by liuzhe-lz** [comment]
| | English | Chinese |
| - | - | - |
| [**(index)**](https://nni.readthedocs.io/en/latest/index.html) | 1904 | 766 |
| [**Overview**](https://nni.readthedocs.io/en/latest/Overview.html) | 783 | 571 |
| [**Installation**](https://nni.readthedocs.io/en/latest/installation.html) | 661 | 460 |
| 　　[**Linux & Mac**](https://nni.readthedocs.io/en/latest/Tutorial/InstallationLinux.html) | 436 | 307 |
| 　　[**Windows**](https://nni.readthedocs.io/en/latest/Tutorial/InstallationWin.html) | 297 | |
| 　　Use Docker | | |
| [**QuickStart**](https://nni.readthedocs.io/en/latest/Tutorial/QuickStart.html) | 965 | 862 |
| [**Auto (Hyper-parameter) Tuning**](https://nni.readthedocs.io/en/latest/hyperparameter_tune.html) | 800 | 772 |
|　　 [**Write Trial**](https://nni.readthedocs.io/en/latest/TrialExample/Trials.html) | 403 | 473 |
|　　 [**Tuners**](https://nni.readthedocs.io/en/latest/builtin_tuner.html) | | 266 |
|　　　　 [**Overview**](https://nni.readthedocs.io/en/latest/Tuner/BuiltinTuner.html) | 538 | 383 |
|　　　　 ... | | |
|　　 Assessors... | | |
|　　 Training Platform... | | |
|　　 Examples... | | |
|　　 [**WebUI**](https://nni.readthedocs.io/en/latest/Tutorial/WebUI.html) | 403 | |
|　　 How to Debug | | |
|　　 Advanced... | | |
|　　 HPO Benchmarks... | | |
| [**Neural Architecture Search**](https://nni.readthedocs.io/en/latest/nas.html) | 763 | 509 |
|　　 [**Overview**](https://nni.readthedocs.io/en/latest/NAS/Overview.html) | 578 | 249 |
|　　 [**Quick Start**](https://nni.readthedocs.io/en/latest/NAS/QuickStart.html) | 432 | 276 |
|　　 Construct Model Space... | | |
|　　 Multi-trial NAS... | | |
|　　 One-shot NAS | | |
|　　　　 [**DARTS**](https://nni.readthedocs.io/en/latest/NAS/DARTS.html) | 326 | |
|　　　　 ... | | |
|　　 NAS Benchmarks... | | |
|　　 _NAS API References_ | | |
| [**Model Compression**](https://nni.readthedocs.io/en/latest/model_compression.html) | 631 | 382 |
|　　 [**Overview**](https://nni.readthedocs.io/en/latest/Compression/Overview.html) | 395 | 283 |
|　　 [**Quick Start**](https://nni.readthedocs.io/en/latest/Compression/QuickStart.html) | | 239 |
|　　 [**Pruning**](https://nni.readthedocs.io/en/latest/Compression/pruning.html) | 435 | 267 |
|　　　　 [**Pruners**](https://nni.readthedocs.io/en/latest/Compression/Pruner.html) | 704 | 430 |
|　　　　 Dependency Aware Mode | | |
|　　　　 Model Speedup | | |
|　　 Pruning V2... | | |
|　　 Quantization | | |
|　　　　 [**Quantizers**](https://nni.readthedocs.io/en/latest/Tutorial/HowToLaunchFromPython.html) | 351 | |
|　　　　 Quantization Speedup | | |
|　　 Utilities | | |
|　　 Advanced Usage | | |
|　　 _API Reference_ | | |
| [**Feauture Engineering**](https://nni.readthedocs.io/en/latest/feature_engineering.html) | | 230 |
|　　 ... | | |
| [**References**](https://nni.readthedocs.io/en/latest/reference.html) | | 304 |
|　　 [**nnictl Commands**](https://nni.readthedocs.io/en/latest/Tutorial/Nnictl.html) | 540 | 302 |
|　　 [**Experiment Configuration**](https://nni.readthedocs.io/en/latest/reference/experiment_config.html) | 427 | 356 |
|　　 [**Experiment Configuration (legacy)**](https://nni.readthedocs.io/en/latest/Tutorial/ExperimentConfig.html) | | 202 |
|　　 [**Search Space**](https://nni.readthedocs.io/en/latest/Tutorial/SearchSpaceSpec.html) | 301 | 207 |
|　　 NNI Annotation | | |
|　　 SDK API References | | |
|　　　　 Auto Tune | | |
|　　　　 NAS | | |
|　　　　 Compression | | |
|　　　　 [**Python API**](https://nni.readthedocs.io/en/latest/Tutorial/HowToLaunchFromPython.html) | 351 | |
|　　 Supported Framework Library | | |
|　　 Launch from Python | | |
|　　　　 ... | | |
|　　 Shared Storage | | |
|　　 Tensorboard | | |
| [**Use Cases and Solutions**](https://nni.readthedocs.io/en/latest/CommunitySharings/community_sharings.html) | 293 | 260 |
|　　 ... | | |
| Research and Publications | | |
| FAQ | | |
| How to Contribute... | | |
| Change Log | | |

**Comment by liuzhe-lz** [comment]
My voted pages:

(index)
Overview
Installation
　　Linux & Mac
　　Windows
QuickStart (suggest rename to "Quick Start")
Auto (Hyper-parameter) Tuning (suggest rename to "Auto Hyper-parameter Tuning")
　　Write Trial
　　Tuners
　　　　Overview
　　Assessors
　　Web UI
Neural Architecture Search
　　Overview
　　Quick Start
Model Compression
　　Overview
　　Quick Start
　　Pruning V2
　　　　Pruning Speedup? (not exist yet)
　　Quantization
　　　　Quantizers
　　　　Quantization Speedup
References
　　nnictl Commands
　　Experiment Configuration
　　Search Space
　　SDK API References - Python API (this is launching experiment from python, I think it should not be here)
Use Cases and Solutions
Research and Publications

**Comment by ultmaster** [comment]
I vote for:

Readme
Installation
Quickstart
HPO (should merge them into quickstart?)
  Write Trial
  Tuner Overview
  WebUI
NAS
  Quickstart
Compression
  Quickstart

**Comment by QuanluZhang** [comment]
vote for: 

(index)
Overview
QuickStart
Auto (Hyper-parameter) Tuning
　　Write Trial
　　Tuners
　　Training Platform
Neural Architecture Search
　　Overview
　　Quick Start
　　Multi-trial NAS
　　One-shot NAS
Model Compression
　　Overview
　　Quick Start
　　Pruning
　　　　Pruners
　　Quantization
　　　　Quantizers
Use Cases and Solutions (two or three)

**Comment by SparkSnail** [comment]
I vote for:

(index)
Overview
Installation
　　Linux & Mac
　　Windows
QuickStart
Auto (Hyper-parameter) Tuning
　　Write Trial
　　Tuners
　　Training Platform
Neural Architecture Search
　　Overview
　　Quick Start
Model Compression
　　Overview
　　Quick Start
References
　　nnictl Commands
　　Experiment Configuration
  Search Space
  Python API
Use Cases and Solutions

**Comment by Lijiaoa** [comment]
**index**
**Overview**
**Installation**
 - Linux & Mac
 - Windows
 
**QuickStart**
**Auto(Hyper-parameter) Tuning**
  - Write Trial
  - Tuners
  - How to Debug
  - WebUI
  
**Neural Architecture Search** (不做参考)
**Model Compression**（不做参考）
    
**References**
  - nnictl Commands
  - Experiment Configuration
  - Experiment Configuration (legacy)
  - Search Space
 
**Use Cases and Solutions**
**FAQ**
**How to Contribute**

**Comment by J-shang** [comment]
**Readme (index)**
**Overview**
**Installation**
- **Linux & Mac**
- **Windows**

**QuickStart**
**Auto (Hyper-parameter) Tuning**
- **Write Trial**
- **Tuner Overview**
- **Assessors Overview**
- **Training Platform**
- **WebUI**

**Neural Architecture Search**
- **Overview**
- **Quick Start**

**Model Compression**
- **Overview**
- **Quick Start**
