### ISSUE TITLE
Running Example mnist code on local

### ISSUE THREAD

**Issue by yhung119** [Microsoft/nni#431]
Hi, I was running the example code and encounter this error. 
```sh
 TypeError: Cannot read property 'writeFile' of undefined
    at LocalTrainingServiceForGPU.runTrialJob (/home/user/.local/nni/training_service/local/localTrainingService.js:258:27)
    at process._tickCallback (internal/process/next_tick.js:178:7) name: 'Training service error' }
```
I am not  sure how to debug this. I have tried running the mnist.py just using python3 and it was not able to proceed because it was trying to get next parameter from nni.

Other info: I'm running locally using
Ubuntu 16.04
Python 3.5.2
node v10.0.0
tensorflow gpu 1.4.1

Thanks for you help in advanced

**Comment by leelaylay** [comment]
The master branch works fine with me.
I wonder that the node version may not be appropriate. 
My environment:
Ubuntu 16.04
node v10.13.0. 
Python 3.6.4 
tensorflow gpu 1.12.0

**Comment by QuanluZhang** [comment]
@yhung119  Thanks for telling us the error and your solution. 
For your question, nni does work with Pytorch. nni does **not** depend on a specific framework, it works with all the frameworks which support python language (nni only supports python sdk currently).

**Comment by yhung119** [comment]
Great! I'll give it a try. Thank you!
