### ISSUE TITLE
How to print log in the foreground mode?

### ISSUE THREAD

**Issue by Root970103** [microsoft/nni#4315]
**Describe the issue**:
When I use nnictl command, the log will be showed in the terminal, like this 
```shell
nnictl create --config config.yml --foreground
```

But when I use python API to launch a experiment, I cannot print any log about experiment information. I add "print("xxxx")" code in the main.py, but this only is showed in the log file. I only want to print some log in the terminal, how can I achieve this?

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc): local
- Client OS:
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version: 1.7.0
- Is conda/virtualenv/venv used?:
- Is running in Docker?: yes

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by liuzhe-lz** [comment]
In v2.5 when you create an experiment with Python API, there will be 3+ Python processes running concurrently:
1. manager process where you run `Experiment.run()`
2. your trial code
3. the tuner

For manager process, printing should just work normally.
For trials, you can only view output with web UI or nnictl. Because they are running in a somewhat sandboxed environment, their outputs are designed to isolate from manager process.
For tuner, we are still thinking about how to integrate it with Python experiment APIs. If you are using your own tuner, please let us know more about your use case.

**Comment by Root970103** [comment]
> In v2.5 when you create an experiment with Python API, there will be 3+ Python processes running concurrently:
> 
> 1. manager process where you run `Experiment.run()`
> 2. your trial code
> 3. the tuner
> 
> For manager process, printing should just work normally. For trials, you can only view output with web UI or nnictl. Because they are running in a somewhat sandboxed environment, their outputs are designed to isolate from manager process. For tuner, we are still thinking about how to integrate custom tuners with Python experiment API. If you are using your own tuner, please let us know more about your use case.

Thank you for your reply.

1. When I launch an experiment with Python API, I just get the output in the terminal as follow.

![image](https://user-images.githubusercontent.com/44917879/142378532-567a40e8-3d25-48fc-9a41-1c14c7ea8c0f.png)

How can I display the content ins {log_dir}/{experiment_id}/log/nnimanager.log to the terminal?

2. Yes, I find that whatever I add the print code, the output is written into the log file, instead of display in the terminal.

3. I just use the builtintuner, sorry cannot to provide some custom tuners case.

**Comment by cruiseliu** [comment]
Oh so you want logs of NNI manager service?
This feature is expected to be added in next release.
For a quick hack you can add `'foreground': 'true'` [here](https://github.com/microsoft/nni/blob/v2.5/nni/experiment/launcher.py#L120).

**Comment by Root970103** [comment]
> Oh so you want logs of NNI manager service? This feature is expected to be added in next release. For a quick hack you can add `'foreground': 'true'` [here](https://github.com/microsoft/nni/blob/v2.5/nni/experiment/launcher.py#L120).

Thank you! This temporarily solved my problem. Looking forward to the next release.

**Comment by scarlett2018** [comment]
Closing the issue as the question has been answered, feel free to reopen if you have question with the answer.
