### ISSUE TITLE
Cannot start restful server

### ISSUE THREAD

**Issue by wenku1992abc** [Microsoft/nni#432]
@scarlett2018 Hi,I use new nni source code to install nnictl,after installed, i use such command:
nnictl create --config ./examples/trials/mnist/config.yml --port 8085

the output is :

INFO: Starting restful server...
ERROR: Restful server start failed!
INFO:  Stdout:
-----------------------------------------------------------------------
                Experiment start time 2018-11-30 15:23:19
-----------------------------------------------------------------------

INFO:  Stderr:
-----------------------------------------------------------------------
                Experiment start time 2018-11-30 15:23:19
-----------------------------------------------------------------------

_Originally posted by @wenku1992abc in https://github.com/Microsoft/nni/issues/80#issuecomment-443115755_

**Comment by leelaylay** [comment]
The node version might be the reason.
I type the `node -v`, and get `v10.13.0` in stdout.
As far as I know, node version below v10.0.0 is not supported.

**Comment by Crysple** [comment]
It is likely that your node isn't installed correctly or it is out of date.
NNI will install node for you actually. So you can type `node -v` to see if its version is above v10.0.0
If node is not found, you can check it in ~/.local/bin.
If so, is there any errors output when you are installing?

**Comment by wenku1992abc** [comment]
I type the node -v, and get v10.13.0! 
@scarlett2018 
yes,I second install the source code ,below is output:
 user@:~/nni$ source install.sh
# Extracting Node.js
rm -rf /tmp/nni-node-linux-x64
mkdir /tmp/nni-node-linux-x64
tar -xf /home/user/Code/nni-master/nni-node-linux-x64.tar.xz -C /tmp/nni-node-linux-x64 --strip-components 1
mkdir -p /home/user/.local/bin
rm -f /home/user/.local/bin/node
cp /tmp/nni-node-linux-x64/bin/node /home/user/.local/bin/node
# Extracting Yarn
rm -rf /tmp/nni-yarn
mkdir /tmp/nni-yarn
tar -xf /home/user/Code/nni-master/nni-yarn.tar.gz -C /tmp/nni-yarn --strip-components 1
# Building NNI Manager
cd src/nni_manager && PATH=/home/user/.local/bin:${PATH} /tmp/nni-yarn/bin/yarn && PATH=/home/user/.local/bin:${PATH} /tmp/nni-yarn/bin/yarn build
yarn install v1.12.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.36s.
yarn run v1.12.1
$ tsc
$ cp -rf scripts ./dist/
Done in 5.21s.
# Building WebUI
cd src/webui && PATH=/home/user/.local/bin:${PATH} /tmp/nni-yarn/bin/yarn && PATH=/home/user/.local/bin:${PATH} /tmp/nni-yarn/bin/yarn build
yarn install v1.12.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.73s.
yarn run v1.12.1
$ react-scripts-ts-antd build
Creating an optimized production build...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
ts-loader: Using typescript@3.1.3 and /home/user/Code/nni-master/src/webui/tsconfig.json
No valid rules have been specified for JavaScript files
Compiled successfully.

File sizes after gzip:

  925.12 KB  build/static/js/main.b5b4541e.js
  37.79 KB   build/static/css/main.f29eae26.css

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  http://bit.ly/2vY88Kr

Done in 37.51s.
# Building Python SDK
cd src/sdk/pynni && python3 setup.py build
running build
running build_py
# Building nnictl
cd tools && python3 setup.py build
running build
running build_py
# Installing Python SDK
cd src/sdk/pynni && python3 -m pip install --user .
Processing /home/user/Code/nni-master/src/sdk/pynni
  Requirement already satisfied (use --upgrade to upgrade): nni-sdk==0.3.0 from file:///home/user/Code/nni-master/src/sdk/pynni in /home/user/.local/lib/python3.6/site-packages
Requirement already satisfied: hyperopt in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from nni-sdk==0.3.0)
Requirement already satisfied: json_tricks in /home/user/.local/lib/python3.6/site-packages/json_tricks-3.12.2-py3.6.egg (from nni-sdk==0.3.0)
Requirement already satisfied: numpy in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from nni-sdk==0.3.0)
Requirement already satisfied: scipy in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from nni-sdk==0.3.0)
Requirement already satisfied: pymongo in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from hyperopt->nni-sdk==0.3.0)
Requirement already satisfied: six in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from hyperopt->nni-sdk==0.3.0)
Requirement already satisfied: networkx in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from hyperopt->nni-sdk==0.3.0)
Requirement already satisfied: future in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from hyperopt->nni-sdk==0.3.0)
Requirement already satisfied: decorator>=3.4.0 in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from networkx->hyperopt->nni-sdk==0.3.0)
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
# Installing nnictl
cd tools && python3 -m pip install --user .
Processing /home/user/Code/nni-master/tools
  Requirement already satisfied (use --upgrade to upgrade): nnictl==0.3.4 from file:///home/user/Code/nni-master/tools in /home/user/.local/lib/python3.6/site-packages
Requirement already satisfied: requests in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from nnictl==0.3.4)
Requirement already satisfied: pyyaml in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from nnictl==0.3.4)
Requirement already satisfied: psutil in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from nnictl==0.3.4)
Requirement already satisfied: astor in /home/user/Developer/anaconda3/lib/python3.6/site-packages (from nnictl==0.3.4)
Requirement already satisfied: schema in /home/user/.local/lib/python3.6/site-packages/schema-0.6.8-py3.6.egg (from nnictl==0.3.4)
Requirement already satisfied: pyhdfs in /home/user/.local/lib/python3.6/site-packages (from nnictl==0.3.4)
Requirement already satisfied: simplejson in /home/user/.local/lib/python3.6/site-packages (from pyhdfs->nnictl==0.3.4)
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
# Installing NNI Package
rm -rf /home/user/.local/nni
cp -r src/nni_manager/dist /home/user/.local/nni
cp src/nni_manager/package.json /home/user/.local/nni
PATH=/home/user/.local/bin:${PATH} /tmp/nni-yarn/bin/yarn --prod --cwd /home/user/.local/nni
yarn install v1.12.1
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning express-joi-validator > boom@2.6.1: This version is no longer maintained. Please upgrade to the latest version.
warning express-joi-validator > joi@6.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning express-joi-validator > boom > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning express-joi-validator > joi > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning express-joi-validator > joi > topo@1.1.0: This version is no longer maintained. Please upgrade to the latest version.
warning express-joi-validator > joi > topo > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning rmdir > node.flow > node.extend > object-keys@0.4.0:
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > express-joi-validator@2.0.0" has unmet peer dependency "joi@6.x.x".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 120.38s.
cp -r src/webui/build /home/user/.local/nni/static
mkdir -p /home/user/.bash_completion.d
install -m644 tools/bash-completion /home/user/.bash_completion.d/nnictl
# Complete! You may want to add /home/user/.local/bin to your PATH environment
# Updating bash configurations
# Complete!

**Comment by wenku1992abc** [comment]
I remove all i had installed about nni. Install NNI with a new environment,meet such error:

# Building NNI Manager
cd src/nni_manager && PATH=/home/user/.local/bin:${PATH} /tmp/nni-yarn/bin/yarn && PATH=/home/user/.local/bin:${PATH} /tmp/nni-yarn/bin/yarn build
yarn install v1.12.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > express-joi-validator@2.0.0" has unmet peer dependency "joi@6.x.x".
warning " > tslint-microsoft-contrib@5.1.0" has incorrect peer dependency "typescript@^2.1.0".
[5/5] Building fresh packages...
error /home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@10.13.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.2/node-v64-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.2 and node@10.13.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error tunneling socket could not be established, statusCode=504
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/Code/nni-master/src/nni_manager/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
node-pre-gyp ERR! System Linux 4.10.0-42-generic
node-pre-gyp ERR! command "/home/user/.local/bin/node" "/home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Makefile:56: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by leelaylay** [comment]
> @scarlett2018 I remove all i had installed about nni. Install NNI with a new environment,meet such error:
> 
> # Building NNI Manager
> cd src/nni_manager && PATH=/home/user/.local/bin:${PATH} /tmp/nni-yarn/bin/yarn && PATH=/home/user/.local/bin:${PATH} /tmp/nni-yarn/bin/yarn build
> yarn install v1.12.1
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> [4/5] Linking dependencies...
> warning " > express-joi-validator@2.0.0" has unmet peer dependency "[joi@6.x.x](mailto:joi@6.x.x)".
> warning " > tslint-microsoft-contrib@5.1.0" has incorrect peer dependency "typescript@^2.1.0".
> [5/5] Building fresh packages...
> error /home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3: Command failed.
> Exit code: 1
> Command: node-pre-gyp install --fallback-to-build
> Arguments:
> Directory: /home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3
> Output:
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.10.3
> node-pre-gyp info using node@10.13.0 | linux | x64
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp info check checked for "/home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" (not found)
> node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.2/node-v64-linux-x64.tar.gz
> node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.2 and node@10.13.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
> node-pre-gyp WARN Hit error tunneling socket could not be established, statusCode=504
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
> node-pre-gyp ERR! stack at ChildProcess. (/home/user/Code/nni-master/src/nni_manager/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
> node-pre-gyp ERR! stack at ChildProcess.emit (events.js:182:13)
> node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
> node-pre-gyp ERR! stack at onErrorNT (internal/child_process.js:407:16)
> node-pre-gyp ERR! stack at process._tickCallback (internal/process/next_tick.js:63:19)
> node-pre-gyp ERR! System Linux 4.10.0-42-generic
> node-pre-gyp ERR! command "/home/user/.local/bin/node" "/home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /home/user/Code/nni-master/src/nni_manager/node_modules/sqlite3
> node-pre-gyp ERR! node -v v10.13.0
> node-pre-gyp ERR! node-pre-gyp -v v0.10.3
> node-pre-gyp ERR! not ok
> Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> Makefile:56: recipe for target 'build' failed
> make: *** [build] Error 1

I meet with this error once. I remove the local node file and reinstall it with successfully.

If you are familiar with Docker, you can use this `msranni/nni:latest` docker with pre-installed environment.

**Comment by wenku1992abc** [comment]
@leelaylay Thanks a lot .I will try.

**Comment by cxy229** [comment]
@wenku1992abc Hello. Did you solve it? I have the same error: "ERROR: Restful server start failed!"
I have tried to update the node to v10.15.0. But it didn't work out.

**Comment by Dinghow** [comment]
I've met the same problem too, and my node version is 10.13.0.

**Comment by Dinghow** [comment]
> I've met the same problem too, and my node version is 10.13.0.

I just restarted my PC and solved it.

**Comment by ioAoi** [comment]
Same error, did you solve it or not ?feels like it is the proxy or company certificate caused the problem……how exactly does it  work？

**Comment by VDeamoV** [comment]
I ran into the same issue. But I fixed it by installing nom in system manually.

**Comment by yitelee** [comment]
Weird .. I changed nothing, just run the failed command again, this time the server started!

**Comment by dliang0406** [comment]
@VDeamoV How did you install nom? Did you mean npm?

**Comment by VDeamoV** [comment]
> @VDeamoV How did you install nom? Did you mean npm? I me the same issue and nothing changed with "sudo apt install npm"

It has been a long time since I love this problem, memory are obscure. I think I mean use npm to install the missing package (mentioned in the error info)
