### ISSUE TITLE
How to use NNI with AllenNLP module?

### ISSUE THREAD

**Issue by unikcc** [microsoft/nni#4331]
**What would you like to be added**: I need use AllenNLP(run with jsonnet) to manage my data preprocessing  & training & evaluation work flow. But NNI is also needed to be embeded in the code to search the best hyperparamete. I wonder if they are compatible

**Why is this needed**: Allenlp and NNI are both awesome tools for NLPer, they should work fine together.

**Without this feature, how does current nni work**：I have to write so many duplicate code to manage building vocab,  loss backward, etc.

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by liuzhe-lz** [comment]
@ChrisZRen to follow

**Comment by ChrisZRen** [comment]
Hi, I think you can use the standalone mode https://nni.readthedocs.io/en/stable/TrialExample/Trials.html#standalone-mode-for-debugging if you are only using the HPO function of NNI.

**Comment by scarlett2018** [comment]
closing the issue as the answer has been provided, feel free to reopen the issue if there are any further questions.
