### ISSUE TITLE
Multiple volumes usage when the training platform is frameworkcontroller

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/nni#4335]
**What would you like to be added**: 
Current YAML for frameworkcontroller accepts only one volume mount point (ex. nfs, azure, etc.).

In kubernetes environment, engineers need more volumes for logging, secrets.

Is there any way to add more volumes when training platform is frameworkcontroller?

OR

If frameworkcontroller mount a volume, this volume can be shared to all nni trial pods?

If it is possible, then it is the one of the solution for my question.

**Why is this needed**:
In kubernetes envrionment, volumes for various purpose like logging, secrets are needed. 

**Without this feature, how does current nni work**：
Required files are moved to the sub-directory of mount point(ex. sub-directory of nfs mount point).

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by SparkSnail** [comment]
No, NNI only support setting single volume mount (azure, nfs), you could change source code https://github.com/microsoft/nni/blob/master/ts/nni_manager/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.ts#L480 and build nni by yourself to support customized feature.

**Comment by mf-giwoong-lee** [comment]
Thanks for replying :)
