### ISSUE TITLE
How implement a Mean Standard Error (MSE) metric for NNI (Neural network intelligence) in pytorch?

### ISSUE THREAD

**Issue by pittnerf** [microsoft/nni#4342]
I want to run a network architecture search (NAS) based on DARTS: Differentiable Architecture Search (see https://nni.readthedocs.io/en/stable/NAS/DARTS.html) and it is based on pytorch. All examples available use accuracy as a metric, but I would need to calculate MSE. This metric is an imput parameter of the DartsTrainer. As a criterion I use nn.MSELoss : `criterion = nn.MSELoss(reduction='sum')`

As a trial I wrote this code: 

```
def accuracy_mse(output, target):
    batch_size = target.size(0)

    
    diff = torch.square(output.t()-target)/batch_size
    diff = diff.sum()

    res = dict()

    res["acc_mse"] = diff
    return res    
```
It seems to be working but the mse metric calculated is significantly greater than the value reported by the loss function.... so I am not sure.

**Environment**: Windows, 
- NNI version:2.4
- Training service (local|remote|pai|aml|etc): local
- Client OS: Windows
- Server OS (for remote mode only):
- Python version: 3.7.9
- PyTorch/TensorFlow version: 1.10.0 / 1.13.1
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: no

**Comment by ultmaster** [comment]
I think you shouldn't use `reduction="sum"`.

Suggest asking the PyTorch community as this looks like a question for PyTorch usage.

**Comment by pittnerf** [comment]
Hi, thanks for the hint. On the one hand you are right, this is PyTorch, but it strongly relates to what DartsTrainer requires, e.q. what to return exactly. That's why I created this issue here.

**Comment by pittnerf** [comment]
Finally I implemented it.

```
def accuracy_mse(output, target):
   
    """ Computes the mse """
    batch_size = target.size(0)
    
    diff = torch.square(output-target)/batch_size
    diff = diff.sum()
    res = dict()

    res["mse"] = diff

    return res  
```

**Comment by ShrutiSarikaChakraborty** [comment]
Hi,

I am trying to implement this but getting error  :IndexError: too many indices for tensor of dimension 0
