### ISSUE TITLE
如何在不同的trial中保存模型到不同的目录

### ISSUE THREAD

**Issue by geekhch** [microsoft/nni#4354]
现在保存模型时，不同的trial输出目录都是同一个，会导致保存的文件互相覆盖。
有没有相关的api可以在程序内捕获当前trail的输出目录呢？

**Comment by geekhch** [comment]
i found `os.getenv('NNI_OUTPUT_DIR')` is working.

**Comment by kingxp** [comment]
Bingo，thanks
