### ISSUE TITLE
[Question] nni frameworkcontroller, running nnictl on worker node

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/nni#4360]
**Describe the issue**:
I construct k8s environment and utilize 2 ubuntu servers as a master and a worker node.

It is fine when running nnictl which has training platform "frameworkcontroller" on the master node. And I know that by copying `/etc/kubernetes/admin.conf`, other worker nodes can run `kubectl` command. In similar manner, I guess that it can be possible if `/etc/kubernetes/admin.conf` of the master is copied and located on worker node, then nnictl also works on worker node.

However, it returns some errors in this setting.

```
INFO:  Successfully set frameworkcontroller config!
INFO:  Starting experiment...
ERROR: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
ERROR: Start experiment failed!
INFO:   Stdout:
-----------------------------------------------------------------------
                Experiment start time 2021-12-02 10:45:23
-----------------------------------------------------------------------




INFO:   Stderr:
-----------------------------------------------------------------------
                Experiment start time 2021-12-02 10:45:23
-----------------------------------------------------------------------
/home/mofl/.local/lib/python3.8/site-packages/nni_node/node_modules/child-process-promise/lib/index.js:33
            var cpError = new ChildProcessError(err.message, err.code, child_process, stdout, stderr);
                          ^

ChildProcessError: Command failed: mkdir -p /home/mofl/nni-experiments/ogvNXDYF/trials-nfs-tmp/nni/ogvNXDYF/nni-code
mkdir: cannot create directory ‘/home/mofl/nni-experiments/ogvNXDYF/trials-nfs-tmp/nni/ogvNXDYF’: Permission denied
 `mkdir -p /home/mofl/nni-experiments/ogvNXDYF/trials-nfs-tmp/nni/ogvNXDYF/nni-code` (exited with error code 1)
    at callback (/home/mofl/.local/lib/python3.8/site-packages/nni_node/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (node:child_process:333:5)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:661:12) {
  code: 1,
  childProcess: {
    _forkChild: [Function: _forkChild],
    ChildProcess: [Function: ChildProcess],
    exec: [Function: exec],
    execFile: [Function: execFile],
    execFileSync: [Function: execFileSync],
    execSync: [Function: execSync],
    fork: [Function: fork],
    spawn: [Function: spawn],
    spawnSync: [Function: spawnSync]
  },
  stdout: '',
  stderr: 'mkdir: cannot create directory ‘/home/mofl/nni-experiments/ogvNXDYF/trials-nfs-tmp/nni/ogvNXDYF’: Permission denied\n'
}
```

I want to know how to launch nnictl which has training platform as frameworkcontroller on worker nodes.

Or is it impossible?

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by cruiseliu** [comment]
`mkdir: cannot create directory ‘/home/mofl/nni-experiments/ogvNXDYF/trials-nfs-tmp/nni/ogvNXDYF’: Permission denied`
Maybe you can try to create the directory manually and see if it succeeds.
