### ISSUE TITLE
Hello, why can't the model pruning experiment code link be clicked

### ISSUE THREAD

**Issue by bopker** [microsoft/nni#4363]
**Describe the issue**:

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by J-shang** [comment]
Hi @bopker , could you show which link?

**Comment by scarlett2018** [comment]
> Hi @bopker , could you show which link?

@bopker - may you help provide more info so that we can help? thanks.

**Comment by scarlett2018** [comment]
Closing the issue as overdue as it has no responds for a while, feel free to reopen if you are still seeing the problem on your side.
