### ISSUE TITLE
Do I have to copy experiment codes to remote servers if I store codes in shared store (like NFS)?

### ISSUE THREAD

**Issue by LspongebobJH** [microsoft/nni#4374]
**Describe the issue**:
Hi there,
I've put my codes and datasets in NFS (shared store) so that all remote servers can share the same codes. I think I don't need to spend time transferring codes from local machine to remote machines. I find that `trialCodeDirectory` would send the codes to remote machines. When setting all files to be ignored in `.nniignore`, I would get an error message as `Training service error: no files or directories specified` in `nnimanager.log`. Is there any option can be set to avoid copying codes to remote servers?

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc): remote
- Client OS: Ubuntu 18.04.5 LTS
- Server OS (for remote mode only): Ubuntu 18.04.5 LTS
- Python version: Python 3.7.10
- PyTorch/TensorFlow version: PyTorch 1.9.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: Nope

**Comment by liuzhe-lz** [comment]
NNI has not considered this use case.
To workaround, you can put an empty file in trial code directory, and set trial command to `python /path/to/nfs/main.py`.

**Comment by ljh1064126026** [comment]
Thanks!
Sorry for the delay reply. I'm also wondering if `nni` will upload all specified files or incrementally copy files in trial code directory to remote servers every time when starting trials?

**Comment by liuzhe-lz** [comment]
No it only uploads once.
