### ISSUE TITLE
Trial failed: log file not found error

### ISSUE THREAD

**Issue by dengkaiDK** [microsoft/nni#4388]
**Describe the issue**:
When I use nnictl command tool to start an experiment, server can start normally but all the trial jobs fail. When I check the trials detail and view trial log, it shows a file not found error which means a log file (**trial.log, stderr, stdout**) is missing. To verify that information, I open the file browser and a log file is indeed missing! I don't have a clue on how to solve this problem. By the way, the experiment I run is the mnist tutorial.

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc): local
- Client OS: Windows
- Server OS (for remote mode only): None
- Python version: 3.7.8
- PyTorch/TensorFlow version: torch 1.7.0 ; tensorflow 2.7.0
- Is conda/virtualenv/venv used?: no
- Is running in Docker?:  no

**Configuration**:
 - Experiment config (remember to remove secrets!):   
<img width="229" alt="image" src="https://user-images.githubusercontent.com/36464510/145801252-4f37af02-e6d6-4033-82bf-4e9f35da4d8a.png">

 - Search space: 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/36464510/145801413-dc1a46d3-aca2-4941-997c-b86854173afc.png">

**Log message**:
 - nnimanager.log:
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/36464510/145914822-fb987942-19f9-4a75-a97a-c82e9ae658f4.png">

 - dispatcher.log:
 - nnictl stdout and stderr: 
 

**How to reproduce it?**:

**Comment by liuzhe-lz** [comment]
Please upload `nni-experiments/<experiment-id>/log/nnimanager.log` and `nni-experiments/<experiment-id>/trials/<trial-id>/run.sh`.

**Comment by dengkaiDK** [comment]
[nnimanager.log](https://github.com/microsoft/nni/files/7716836/nnimanager.log)

[run.txt](https://github.com/microsoft/nni/files/7716844/run.txt)

**Comment by dengkaiDK** [comment]
I uninstall nni and try a new experiment, but the same trial error occurs. Trial.log, stdout and stderr files are missing under directory: nni-experiments/experiment-id/trials/trial-id/.

**Comment by liuzhe-lz** [comment]
Sorry for late reply, I missed the notification......
If you are still trying to solve the problem, you can run the powershell script directly and see what happens.

**Comment by dengkaiDK** [comment]
Here is what I think about the trail error. The experiment can start successfully, but NNIManager log shows that every trial status changed from waiting to failed. Then I check trial details and click the "view trail error" button under one trial, it shows information like : "{"error":"File not found: `C:\\Users\\<my-username>\\nni-experiments\\5BpRqkOt\\trials\\HKDSU\\stderr`"}". So I check corresponding directory and find these files:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/36464510/147353164-a31f43d7-71ca-47e5-a354-8ff0550caa55.png">
It indeed doesn't include stderr and stdout! To solve this problem, I inspect NNIManager.log and try to locate the error, however, it is too demanding for me to understand the meaning of JS file. So I have to report this issue on Github, hoping technician able to help me. 

Appendix: config_detailed.yml 

experimentName: MNIST         
searchSpace:
  batch_size:
    _type: choice
    _value: [16, 32, 64, 128]
  hidden_size:
    _type: choice
    _value: [128, 256, 512, 1024]
  lr:
    _type: choice
    _value: [0.0001, 0.001, 0.01, 0.1]
  momentum:
    _type: uniform
    _value: [0, 1]

trialCommand: python mnist.py  
trialCodeDirectory: .          
trialGpuNumber: 0             

trialConcurrency: 4            
maxTrialNumber: 10             
maxExperimentDuration: 1h      

tuner:                         
  name: TPE                    
                              
  classArgs:                   
    optimize_mode: maximize   

trainingService:
  platform: local
  useActiveGpu: false

**Comment by liuzhe-lz** [comment]
The `run` powershell script in the screenshot should run `trialCommand` and redirect its output to `stderr`. Looks like there is something wrong with the script.
So please show the script content, and try to run the script directly in powershell, to see why it failed to create `stderr` file.

**Comment by scarlett2018** [comment]
> Looks like there is something wrong with the script. So please show the script content, and try to run the script directly in powershell, to see why it failed to create `stderr` file.

@dengkaiDK - had you get a chance try this suggestion? any new findings? thanks.

**Comment by dengkaiDK** [comment]
It is finished, thank you for the advice.

**Comment by VVER0114** [comment]
I suffer the same problem.
The same information: {"error":"File not found: C:\\Users\\Water\\nni-experiments\\jyH7lFIR\\trials\\OaRFi\\stdout"}
How do you solve this problem?
