### ISSUE TITLE
ChildProcessError: “powershell.exe”is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by DoveEchoing** [microsoft/nni#4391]
**Describe the issue**:
I started NNI yesterday by following the  tutorial,but I had a problem when I was running the MNIST example——the experiment has been successfully launched, there was an error in the "Status" property of the experimental interface. The detailed content of Error is Command failed: powershell.exe New-Item -Path "XXX" -ItemType "directory" -Force 'powershell.exe' is not recognized as an internal or external command,operable program or batch file. `powershell.exe' New-Item -Path "XXX" -ItemType "directory" -Force` (exited with error code 1). I tried to solve the problem but not succeeded.

**Environment**:
- NNI version:2.5
- Training service (local|remote|pai|aml|etc):local
- Client OS:Windows 10
- Server OS (for remote mode only):None
- Python version:3.8.5
- PyTorch/TensorFlow version: torch 1.1.0/ tf 2.7.0
- Is conda/virtualenv/venv used?:maybe no,but I had conda
- Is running in Docker?:no

**Experimental Interface**
![捕获](https://user-images.githubusercontent.com/96108370/145974003-d5508d52-dd96-49cd-87bb-5b8f201af3cc.PNG)

![2](https://user-images.githubusercontent.com/96108370/145974244-4d0e46c6-7e7a-4b6d-9928-7ff8fc17ad6b.PNG)

**dispatcher**
![3](https://user-images.githubusercontent.com/96108370/145974879-7f0877cf-19ec-495e-88c3-add9ada115d9.PNG)

**nnictl_stderr**
![4](https://user-images.githubusercontent.com/96108370/145974959-62808cd7-5045-447b-a296-84342bf91118.PNG)

**nnimanager**
![5](https://user-images.githubusercontent.com/96108370/145975033-e914b234-3b2a-42af-ae23-a8419c50e8db.PNG)

**nnictl_stdout**
blank

**Comment by J-shang** [comment]
Hello @DoveEchoing , maybe this can help you.

https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr

**Comment by DoveEchoing** [comment]
> Hello @DoveEchoing , maybe this can help you.
> 
> https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr

Thank you, I will read it carefully.

**Comment by DoveEchoing** [comment]
> Hello @DoveEchoing , maybe this can help you.
> 
> https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr

I fixed this problem by adding powershell path to environment variable, but I had another problem——all trials had failed.
![捕获](https://user-images.githubusercontent.com/96108370/146151107-a26599a5-3cb6-4ed9-8c50-27b5208ffaaa.PNG)

**Comment by DoveEchoing** [comment]
> > Hello @DoveEchoing , maybe this can help you.
> > https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr
> 
> I fixed this problem by adding powershell path to environment variable, but I had another problem——all trials had failed. ![捕获](https://user-images.githubusercontent.com/96108370/146151107-a26599a5-3cb6-4ed9-8c50-27b5208ffaaa.PNG)

I will try to solve it.

**Comment by feiguofeiguo** [comment]
I meet this problem when use nni in vscode, and adding path donot work .I solve it by starting nni in powershell directly.
