### ISSUE TITLE
Checkpoint folder is empty

### ISSUE THREAD

**Issue by baynaa7** [microsoft/nni#4392]
Hello, I am running, nni/test/retiarii_test/darts/test.py script. I can see result on webUI, after all trials are finished, I cannot obtain the trained model and checkpoint files in directory nni-experiment/my_exp_id/checkpoint/ folder.
How to obtain the best pytorch model?
Thanks,

**Comment by baynaa7** [comment]
In nni/test/retiarii_test/naive/lightning_logs/version_x/checkpoints/ folder, I could find the pytorch checkpoint file,
By running python search.py  --exec graph --budget 20, I can obtain python script as plain test (that defines the best model).
However, when I use this script with above checkpoint, and do evaluation, by loading:
```
PATH = "nni/test/retiarii_test/naive/lightning_logs/version_x/checkpoints/epoch=9-step=1199.ckpt"
checkpoint = torch.load(PATH)
model.load_state_dict(checkpoint['state_dict'], strict=False)
```
it seems every time I run the scripts, evaluation results are different, (I also used generated onnx file to evaluate, but onnx's evaluation output is the same every time)

If I set model.load_state_dict(checkpoint['state_dict']), it raises a error:

File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for _model:
        Missing key(s) in state_dict: "_model__conv1.weight", "_model__conv1.bias", "_model__conv2.weight", "_model__conv2.bias", "_model__fc1.layerchoice_fc1_choice_0.weight", "_model__fc1.layerchoice_fc1_choice_0.bias", "_model__fc2.weight", "_model__fc2.bias". 
        Unexpected key(s) in state_dict: "model._model__conv1.weight", "model._model__conv1.bias", "model._model__conv2.weight", "model._model__conv2.bias", "model._model__fc1.layerchoice_fc1_choice_0.weight", "model._model__fc1.layerchoice_fc1_choice_0.bias", "model._model__fc2.weight", "model._model__fc2.bias".


while I run retiarii with web UI, model accuracy was 0.97 something. Now, even onnx model cannot reach to that score.

what is the problem?

**Comment by JiahangXu** [comment]
Hi, sorry for the late reply. The code from test/retiarii_test is only for automatic integration test. We suggest to use example code of DARTS from https://github.com/microsoft/nni/tree/master/examples/nas/oneshot/darts.
