### ISSUE TITLE
AttributeError: trial_code_directory is not supposed to be set in Retiarii mode by users!

### ISSUE THREAD

**Issue by Hukongtao** [microsoft/nni#4405]
**Describe the issue**:

**Environment**:
- NNI version:  The latest version
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:
When I run the example: https://github.com/microsoft/nni/blob/master/examples/nas/multi-trial/mnist/search.py

**Comment by Hukongtao** [comment]
Yesterday it was still running normally, but after updating the code today, it reported an error

**Comment by Hukongtao** [comment]
@ultmaster Looks like you updated the code?

**Comment by ultmaster** [comment]
Please report the full error traceback for our investigation.

Also which version of NNI are you using? Did you checkout the example from release branch or master(dev) branch?

**Comment by Hukongtao** [comment]
I pulled the code of the latest master branch. According to the instructions in the document, I run the [example](https://github.com/microsoft/nni/blob/master/examples/nas/multi-trial/mnist/search.py).   
```
python examples/nas/multi-trial/mnist/search.py
```
Before this, the code can run normally

**Comment by Hukongtao** [comment]
It should not be caused by the code you submitted, but I don’t know why

**Comment by Annika10** [comment]
@Hukongtao could you solve it? I receive the same error for this example on the master branch. This is my console output:

**Comment by Hukongtao** [comment]
No， I don't.  Now, I did not use the latest code, I installed the v2.5 version

**Comment by ultmaster** [comment]
We confirm that this is a bug caused by latest refactoring. Please install nni using pip and try v2.5 examples for now.
