### ISSUE TITLE
check validation of nni annotation in trial code

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/nni#441]
The new version of nni annotation requires '''@nni.get_next_parameter()''' to retrieve hyperparameters. nni should check whether this annotation is added in the trial code before running the experiment, if not, then show error message to users.

**Comment by Crysple** [comment]
This issue can be closed.
Now no matter whether user adds this line or not, nni will work

**Comment by Crysple** [comment]
Related to PR #526 @
