### ISSUE TITLE
The QR code of WeChat expired

### ISSUE THREAD

**Issue by Hukongtao** [microsoft/nni#4413]
**Describe the issue**:

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by Hukongtao** [comment]
Can someone share it again?

**Comment by scarlett2018** [comment]
> Can someone share it again? Thank you

@Hukongtao - thanks for the reminder, just updated.

**Comment by Hukongtao** [comment]
> > Can someone share it again? Thank you
> 
> @Hukongtao - thanks for the reminder, just updated.

Thank you very much
