### ISSUE TITLE
how to load with "mask.pth"

### ISSUE THREAD

**Issue by mozpp** [microsoft/nni#4422]
# export model weights and mask
pruner.export_model(model_path='model.pth', mask_path='mask.pth')

how to load with mask.pth?

**Comment by J-shang** [comment]
Hi @mozpp,

This mask is mainly for speed_up. But if you want to load the masks, there are two ways:
1. If you just want to inference, the following function can help you.
`from nni.compression.pytorch.pruning.apply_compression import apply_compression_results`
It simply multiplies weights with corresponding masks.

2. If you want to train with masks, `apply_compression_results` is not enough, you need to wrap the model again.
I recommend you use pruning v2 to wrap your model, the masks' format between v1 and v2 is the same.
```
from nni.algorithms.compression.v2.pytorch.base import Pruner
model = ...
masks = torch.load('mask.pth')
pruner = Pruner(model, config_list)
pruner.load_masks(masks)

# Then you can train with masks
trainer(model, ...)
```

**Comment by scarlett2018** [comment]
Closing the issue as the question has been answered, feel free to reopen if you have question with the answer.

**Comment by mrwu-mac** [comment]
How to load_masks with `LotteryTicketPruner`, which inherits from `IterativePruner` instead of `Pruner`?
