### ISSUE TITLE
nnictl：command not found

### ISSUE THREAD

**Issue by DoveEchoing** [microsoft/nni#4433]
Describe the issue:
I have already ran the mnist-pytorch case on a computer,but an error occurred when I tried to run nni on another computer.
the error is :
![捕获](https://user-images.githubusercontent.com/96108370/147542947-61d41650-319f-4def-9e8c-b7e144585995.PNG)
or
![147459793-a078c045-b889-47ed-9e9d-a9ceebbc4281](https://user-images.githubusercontent.com/96108370/147542955-1ec7d331-5cfc-45b4-9332-bb4a34a98f6c.PNG)

Environment:

NNI version:2.5
Training service (local|remote|pai|aml|etc):local
Client OS: Windows10
Server OS (for remote mode only):None
Python version:3.8.5
PyTorch/TensorFlow version:torch 1.10.0/ tf 2.7.0
Is conda/virtualenv/venv used?:I have installed Anaconda,but I think I don't use it
Is running in Docker?:None

**Comment by liuzhe-lz** [comment]
You can first check NNI installation with `import nni` and find its installation path with `print(nni.__path__)`.
If NNI package is correctly installed, then it's likely that the Python executable directory is not added to your PATH.

The location of nnictl script is either located in `pip._internal.locations.get_bin_py()` or `pip._internal.locations.get_bin_prefix()`.
And both two directories should be inside PATH variable. Check it with `echo $env:PATH`.

**Comment by DoveEchoing** [comment]
Thanks for your reply! You have helped me many times!
I certainly sure I have installed nni package,and the path is `C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\nni`
I found this path is different from my previous python path(my previous python path is:`C:\\Users\Administrator\\AppData\\Local\\Programs\\Python\\Python38`——This is another computer,it only has python environment in pycharm,no Anaconda. I need torch to run my code,so I reinstalled python and installed Anaconda on this computer,leading to different paths.)
When I add the new path, `nnictl` command is ready to run.
But!
An error occurs!! Like this: 
![powershell](https://user-images.githubusercontent.com/96108370/147645985-abd878ec-e282-48f3-8e2f-d5f31e72ce63.PNG)
I found the specific error in nnictl_stderr file.
![捕获](https://user-images.githubusercontent.com/96108370/147646150-71e44a97-abd5-431d-a317-9b564fb61ea4.PNG)
My Windows version is Windows7,maybe the version is old,I need to upgrade the Windows version from 7 to 10,crying...
Anyway,thanks for your help and...
Loving you!!!
