### ISSUE TITLE
TypeError: zip argument #2 must support iteration

### ISSUE THREAD

**Issue by iksooman** [microsoft/nni#4444]
I'm trying to use nni to test ppo_tuner.
And I got this error message today:

```
C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\nni\nas\tensorflow\mutables.py:97 call  *
    out, mask = self.mutator.on_forward_layer_choice(self, *inputs)
C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\nni\nas\tensorflow\mutator.py:37 on_forward_layer_choi
ce  *
    out = self._select_with_mask(lambda choice: choice(*inputs), mutable.choices, mask)
C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\nni\nas\tensorflow\mutator.py:52 _select_with_mask  *
    out = [map_fn(cand) for cand, m in zip(candidates, mask) if m]
C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\autograph\operators\py_builtins.py:4
16 zip_  **
    return _py_zip(*iterables)
C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\autograph\operators\py_builtins.py:4
24 _py_zip
    return zip(*iterables)

TypeError: zip argument #2 must support iteration
```
I think this error message means that tf.Tensor(i.e. mask) is not iterable.
So I tried changing the type of mask into numpy() like this:
**(in Mutator.py)**
```
    def _select_with_mask(self, map_fn, candidates, mask):
        if mask.dtype.is_bool:
            out = [map_fn(cand) for cand, m in zip(candidates, mask.numpy()) if m]
        elif mask.dtype.is_floating:
            out = [map_fn(cand) * m for cand, m in zip(candidates, mask.numpy()) if m]
        else:
            raise ValueError('Unrecognized mask, dtype is {}'.format(mask.dtype.name))
        return out
```
And my problem solved.
It looks like this issue depends on training script.
Sometimes this issue make an error, sometimes it doesn't.
I don't know why ...

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc): local
- Client OS: Windows 10
- Server OS (for remote mode only): Windows10
- Python version: 3.7.8
- PyTorch/TensorFlow version: Tensorflow 2.5.0
- Is conda/virtualenv/venv used?: No
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by liuzhe-lz** [comment]
Sorry but architecture search for TensorFlow is out of maintenance due to lack of developer.
If you can use PyTorch, `nni.retiarii` is actively maintained for latest NAS algorithms.

**Comment by iksooman** [comment]
Ok.. It would be needed to consider using pytorch.
Thank you for your answer.
