### ISSUE TITLE
Unrecognized fileds authorname and builtnassessorname

### ISSUE THREAD

**Issue by DoveEchoing** [microsoft/nni#4453]
**Describe the issue**:
When I launched the `"nnictl create"` command,it occurred this mistake(I have came acrossed it):
![error](https://user-images.githubusercontent.com/96108370/148675377-cd59d758-5be0-47ae-b174-5443ca05613e.PNG)

I know the error is in the `config_windows.yml` file
![ebe90a81479783a0bceff8f71f2b73b](https://user-images.githubusercontent.com/96108370/148675424-8b5ff46e-8101-4e91-8601-0b7c915749a2.png)

I try to use "Assessor" module to early stop my trials,and modify my `config_windows.yml` file through the source code. But it also occurred error.

The example has ran successfully because I have deleted the autorname/experimentname/assessor module,but I want to know why it occurred mistake and I hope to fix it.

the source code
![assessor](https://user-images.githubusercontent.com/96108370/148675678-94b3f7bb-626c-4f05-ad09-3f905d26c0d8.PNG)

**Environment**:
- NNI version:2.5
- Training service (local|remote|pai|aml|etc):local
- Client OS:Windows 10
- Server OS (for remote mode only):None
- Python version:3.8
- PyTorch/TensorFlow version:1.10.1/2.7.0
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?:no

**Comment by liuzhe-lz** [comment]
Sorry the assessor example is outdated.
`builtinAssessorName` should be `name`.

**Comment by DoveEchoing** [comment]
> Sorry the assessor example is outdated. `builtinAssessorName` should be `name`.

I have fixed the error as your reply ! Thank you !
But the `authorName` still has problem, and the `experimentName` is ok.

![authorname](https://user-images.githubusercontent.com/96108370/148725553-9ecb5f11-cea6-46e2-adb4-2e7287604ad5.PNG)

**Comment by cruiseliu** [comment]
`authorName` has been removed.
`config_assessor.json` is totally outdated. Please ignore it.

**Comment by DoveEchoing** [comment]
> `authorName` has been removed. `config_assessor.json` is totally outdated. Please ignore it until we update.

OK,I have known it,thank you!
