### ISSUE TITLE
WEB UI is empty

### ISSUE THREAD

**Issue by yzj19870824** [microsoft/nni#4467]
**Describe the issue**:

**Environment**: 
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc):local
- Client OS:centOS
- Server OS (for remote mode only):
- Python version:3.6
- PyTorch/TensorFlow version:PyTorch 1.7
- Is conda/virtualenv/venv used?:no
- Is running in Docker?:yes

**Log message**:
 - nnimanager.log: NO ERROR
 - dispatcher.log:
 - nnictl stdout and stderr: NOTHING

**How to reproduce it?**:
When I input "http://[serverIP]:8080", the web UI shows nothing after executing "nnictl create --config minist_pytorch/config.yml". but shows "You need to enable Javascript to run the app." 

in my offline environment, checklist as follows:
0 enter nni docker using "docker run -it -p 8080:8080 msranni/nni:latest"
1 copy nni-master into nni docker
2 copy mnist dataset files into mnist_pytorch/dataset/MNIST/data/raw
3 experiment creation is OK, "nnictl log stderr" and nnimanager shows nothing error
4 "nnictl top" shows  ongly two status:"RUNNING" and "SUCCESS"
5 firewall in the server is disable
6 enable Javascript on Chrome

Please help me and tell me what should I do, thanks

**Comment by liuzhe-lz** [comment]
Please press F12 to open browser console and check the error message.

**Comment by scarlett2018** [comment]
> Please press F12 to open browser console and check the error message.

@yzj19870824 - are you still bother by the problem? any feedback about the above question. we can close the issue if you can not reproduce after F12. thanks.

**Comment by scarlett2018** [comment]
Closing the issue as overdue as it has no responds for a while.
