### ISSUE TITLE
The trials detail do not have anything after change the search space.

### ISSUE THREAD

**Issue by iimlearning** [microsoft/nni#4472]
**Describe the issue**:
I run the `nnictl update searchspace -f ./search_space.json` to change the search space value.

However, I cannot look the trials detail in the Webui now.

The view:
![image](https://user-images.githubusercontent.com/46561673/149851510-3a3a473d-d565-49f7-9a32-0155bb0f49c3.png)

The web after I click the **trials detail**.
![image](https://user-images.githubusercontent.com/46561673/149851534-34ba5ffb-8485-4fd8-be72-e609a998e765.png)

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by Lijiaoa** [comment]
Hi, @iimlearning 
1. Could you tell me your original search space and changed search space?
2. Please press F12 to open browser console and paste the error message.

**Comment by iimlearning** [comment]
The original search space : 
{
    "desc_conv_output_size": {"_type":"choice", "_value": [10,20,30,40,50,80]},
    "desc_conv_window_size": {"_type":"choice", "_value": [2,3,4,5,6,8]}
}

The changed:
{
    "desc_conv_output_size": {"_type":"choice", "_value": [10,20,30,40,50]},
    "desc_conv_window_size": {"_type":"choice", "_value": [2,3,4,5,6,8]}
}

The difference is to delete a value **80** in the first parameter.

The error:
```
react-dom.production.min.js:5058 TypeError: Cannot read property '0' of undefined
    at function.ts:372
    at Array.forEach (<anonymous>)
    at O (function.ts:371)
    at new Ve (TableList.tsx:116)
    at ko (react-dom.production.min.js:3174)
    at Va (react-dom.production.min.js:4307)
    at ks (react-dom.production.min.js:6700)
    at mu (react-dom.production.min.js:6150)
    at gu (react-dom.production.min.js:6139)
    at su (react-dom.production.min.js:5880)
rs @ react-dom.production.min.js:5058
n.callback @ react-dom.production.min.js:5568
vo @ react-dom.production.min.js:3108
ls @ react-dom.production.min.js:5182
Cu @ react-dom.production.min.js:6408
t.unstable_runWithPriority @ scheduler.production.min.js:309
jr @ react-dom.production.min.js:2816
bu @ react-dom.production.min.js:6204
su @ react-dom.production.min.js:5895
(anonymous) @ react-dom.production.min.js:2851
t.unstable_runWithPriority @ scheduler.production.min.js:309
jr @ react-dom.production.min.js:2816
$r @ react-dom.production.min.js:2846
Z @ scheduler.production.min.js:203
k.port1.onmessage @ scheduler.production.min.js:94
scheduler.production.min.js:96 Uncaught TypeError: Cannot read property '0' of undefined
    at function.ts:372
    at Array.forEach (<anonymous>)
    at O (function.ts:371)
    at new Ve (TableList.tsx:116)
    at ko (react-dom.production.min.js:3174)
    at Va (react-dom.production.min.js:4307)
    at ks (react-dom.production.min.js:6700)
    at mu (react-dom.production.min.js:6150)
    at gu (react-dom.production.min.js:6139)
    at su (react-dom.production.min.js:5880)
```

> Hi, @iimlearning
> 
> 1. Could you tell me your original search space and changed search space?
> 2. Please press F12 to open browser console and paste the error message.

**Comment by Lijiaoa** [comment]
nni version?

**Comment by iimlearning** [comment]
> nni version?

2.5.0

**Comment by Lijiaoa** [comment]
I also got this error with 2.5. Because changed search space became `string`. It should be `object`. NNI v2.6 had fix this issue and would be released soon.

![image](https://user-images.githubusercontent.com/61399850/149866757-8343752d-7d18-415f-985e-577296600383.png)

**Comment by iimlearning** [comment]
> 

Thanks, professional and meticulous.

**Comment by Lijiaoa** [comment]
fixed pr: https://github.com/microsoft/nni/pull/4438
