### ISSUE TITLE
Unable to instantiate LSTM and GRU layers.

### ISSUE THREAD

**Issue by ERamaM** [microsoft/nni#4483]
**Describe the issue**:

Using version 2.6 of NNI is impossible to instantiate LSTM and GRU layers. However, this does not happen in version 2.5. This can be reproduced with the following [Code](https://gist.github.com/ERamaM/59a86be3a0a9491706e4bde595835552)

This can be reproduced in Google Colab. Remember to restart the runtime between each pip installation of NNI.

**Environment**:
- NNI version: 2.6 and 2.5
- Training service (local|remote|pai|aml|etc): remote
- Client OS: 
- Server OS (for remote mode only): Ubuntu 18.04.5 LTS
- Python version: 3.7.12
- PyTorch/TensorFlow version: 1.10.0+cu111
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!): no experiment config is needed.
 - Search space: no search space is needed.

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

No experiments have been performed

**How to reproduce it?**:

- Install version 2.6 of NNI
- Import the library using "import nni.retiarii.nn.pytorch as nn"
- Create an LSTM or GRU layer using "nn.LSTM()"

**Comment by ultmaster** [comment]
Please try `nn.LSTM(input_size=2, hidden_size=2)` for now.

We will figure out a fix for this.
