### ISSUE TITLE
How to add early stop in NNI?

### ISSUE THREAD

**Issue by RuojiWang** [microsoft/nni#4485]
**Describe the issue**:
How to add early stop in NNI? 
i learn from this: https://nni.readthedocs.io/en/stable/Assessor/BuiltinAssessor.html#MedianStop
but when i run command: nnictl create --config nni/examples/trials/mnist-pytorch/config.yml
i get the following error:
Traceback (most recent call last):
  File "/home/jingyu/anaconda3/envs/nni/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/home/jingyu/anaconda3/envs/nni/lib/python3.8/site-packages/nni/tools/nnictl/nnictl.py", line 286, in parse_args
    args.func(args)
  File "/home/jingyu/anaconda3/envs/nni/lib/python3.8/site-packages/nni/tools/nnictl/launcher.py", line 92, in create_experiment
    exp.start(port, debug, run_mode)
  File "/home/jingyu/anaconda3/envs/nni/lib/python3.8/site-packages/nni/experiment/experiment.py", line 120, in start
    config = self.config.canonical_copy()
  File "/home/jingyu/anaconda3/envs/nni/lib/python3.8/site-packages/nni/experiment/config/base.py", line 161, in canonical_copy
    canon._canonicalize([])
  File "/home/jingyu/anaconda3/envs/nni/lib/python3.8/site-packages/nni/experiment/config/experiment_config.py", line 113, in _canonicalize
    if algo is not None and algo.name == '_none_':
AttributeError: 'dict' object has no attribute 'name'

i am cofused what does it mean?

**Environment**:
- NNI version: 2.6
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu 18.04
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: Pytorch 1.10.1
- Is conda/virtualenv/venv used?:  virtualenv in anaconda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
searchSpaceFile: search_space.json
trialCommand: python3 mnist.py  # NOTE: change "python3" to "python" if you are using Windows

trialGpuNumber: 1
trialConcurrency: 1
maxTrialNumber: 10
maxExperimentDuration: 1h

tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local

trainingService:
  platform: local
  useActiveGpu: true           # NOTE: Use "true" if you are using an OS with graphical interface (e.g. Windows 10, Ubuntu desktop)
  maxTrialNumberPerGpu: 1      # Reason and details:  https://nni.readthedocs.io/en/latest/reference/experiment_config.html#useactivegpu

assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: maximize
 
 - Search space:
{
    "batch_size": {"_type":"choice", "_value": [16, 32, 64, 128]},
    "hidden_size":{"_type":"choice","_value":[128, 256, 512, 1024]},
    "lr":{"_type":"choice","_value":[0.0001, 0.001, 0.01, 0.1]},
    "momentum":{"_type":"uniform","_value":[0, 1]}
}

**Log message**:
 - no log message, i can not even run the experiment.
 

**How to reproduce it?**:
use my config.yml, and run command: nnictl create --config nni/examples/trials/mnist-pytorch/config.yml

**Comment by J-shang** [comment]
Hello @RuojiWang , please use `name: Medianstop` instead of `builtinAssessorName: Medianstop` and have a try.

**Comment by RuojiWang** [comment]
> Hello @RuojiWang , please use `name: Medianstop` instead of `builtinAssessorName: Medianstop` and have a try.

thanks, it works, you are very helpful.

**Comment by RuojiWang** [comment]
@J-shang, i have anthor question, how to set max_epoch_number of a trial?

i did not find something about it in docs.

**Comment by J-shang** [comment]
> @J-shang, i have anthor question, how to set max_epoch_number of a trial?
> 
> i did not find something about it in docs.

`max_epoch_number` is a fixed number or a tunable parameter in your task? If it is a fixed number, directly hard code in your script. If it is a tunable parameter, set it in your `seach_space.json`.

**Comment by RuojiWang** [comment]
> > @J-shang, i have anthor question, how to set max_epoch_number of a trial?
> > i did not find something about it in docs.
> 
> `max_epoch_number` is a fixed number or a tunable parameter in your task? If it is a fixed number, directly hard code in your script. If it is a tunable parameter, set it in your `seach_space.json`.

thanks.
