### ISSUE TITLE
can't run examples/mnist-pytorch/config_detailed.yml

### ISSUE THREAD

**Issue by cdp-study** [microsoft/nni#4491]
**Describe the issue**:
When I run "nnictl  create --config examples/trails/mnist-pytorch/config_detailed.yml”，Web UI cann't open.  no log. The result is:
![0D612F68BEB7341E49C8091B01D1A47E](https://user-images.githubusercontent.com/59856350/150503088-45b822fb-2010-434a-a2e1-f5d204ceb8ed.jpg)
![D4E7E6BE63B78B18900DDE730BA7AA84](https://user-images.githubusercontent.com/59856350/150503104-b9e1442e-d252-4ac1-95f3-c4c237fad317.jpg)
https://github.com/microsoft/nni/issues/3853
Previous answers don't work. How to solve it? Thank you!!!

**Environment**:
- NNI version: 2.4/2.5
- Training service (local|remote|pai|aml|etc):local
- Client OS:ubuntu16.04
- Server OS (for remote mode only):
- Python version:3.8
- PyTorch/TensorFlow version:1.6
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?:no 

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 no log

**How to reproduce it?**:

**Comment by cruiseliu** [comment]
Please attach `~/nni-experiments/FV5isKXd/log/dispatcher.log`.

**Comment by cdp-study** [comment]
I'm sorry. I can't find any logs. 
![image](https://user-images.githubusercontent.com/59856350/151681816-9ffe140c-c8d5-4edc-b5b5-17dc7be5b16b.png)

**Comment by liuzhe-lz** [comment]
The `nni-experiments` directory is under user home, not source code folder.

**Comment by scarlett2018** [comment]
> The `nni-experiments` directory is under user home, not source code folder.

@cdp-study  - can you find the logs and get hint of the problems with the log? we are closing resolved issues, let us know if it is still an open issue.

**Comment by scarlett2018** [comment]
Closing the issue as overdue as it has no responds for a while, feel free to reopen if you are still seeing the problem on your side.
