### ISSUE TITLE
All trail failed while very first using default mnist-pytorch/config.yml

### ISSUE THREAD

**Issue by 21wang12** [microsoft/nni#4530]
**Describe the issue**:

I follow the instruction in the official website: https://nni.readthedocs.io/zh/stable/installation.html. However when I running the command `nnictl create --config nni/examples/trials/mnist-pytorch/config.yml` and open the website it shows up, I notice all trail failed.

**Environment**:
- NNI version:v2.6
- Training service :remote
- Client OS:Macos
- Server OS (for remote mode only): Ubuntu 16.04
- Python version: 3.8
- PyTorch/TensorFlow version: NAN
- Is conda/virtualenv/venv used?: use conda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!): mnist-pytorch/config.yml
 - Search space: <default in `mnist-pytorch/config.yml` >

Here is the screen shoot:
![image](https://user-images.githubusercontent.com/38482259/152629940-58322cae-1aea-4820-b5f8-d42fa32d807f.png)

**Comment by cruiseliu** [comment]
Please check the trial log to see why it failed.
And check if `mnist.py` works without nnictl (run the python script directly).

**Comment by scarlett2018** [comment]
> Please check the trial log to see why it failed. And check if `mnist.py` works without nnictl (run the python script directly).

@21wang12 - had you reviewed the logs? wondering whether you had resolve the issue by review error messages logs.

**Comment by 21wang12** [comment]
> > Please check the trial log to see why it failed. And check if `mnist.py` works without nnictl (run the python script directly).
> 
> @21wang12 - had you reviewed the logs? wondering whether you had resolve the issue by review error messages logs.

No, after days debugging, the problem still not be solved. I am not using it anymore now. Thanks for your reply, and I am deciding to close this issue.
