### ISSUE TITLE
Regarding .experiment file 

### ISSUE THREAD

**Issue by BakingBrains** [microsoft/nni#4536]
The .experiment file is locked in the folder, what might be the reason. 
![Screenshot 2022-02-09 181537](https://user-images.githubusercontent.com/51019420/153203876-246a3788-89e1-4c81-a811-8a0a3cf9806a.jpg)

**Comment by J-shang** [comment]
Hello @BakingBrains , which kind of experiment have you launched, NAS or HPO? This may be because of experiment unexpected termination when `.experiment` file is read or written. You can del this file safely.

**Comment by scarlett2018** [comment]
closing the issue as the answer had been provided, feel free to reopen if the answer does not work well for you, thanks.
