### ISSUE TITLE
I have to set _AlgorithmConfig launching NNI from Python with Custom Tuner

### ISSUE THREAD

**Issue by survexman** [microsoft/nni#4545]
**I have to set _AlgorithmConfig launching NNI from Python with Custom Tuner**:

I have to run an Experiment from Python with Custom Tuner:

It worked fine with classic command-line launching `nni create --config=...`:

```
tuner:     
  codeDirectory: tuners/custom_tuner
  className: my_tuner.CustomTuner

```
But it failed when I launched an Experiment from Python with the following config:

```
experiment.config.tuner.code_directory = Path(__file__).parent 
experiment.config.tuner.class_name = 'my_tuner.CustomTuner'

```
After hours of debugging NNI source code, I've found that initializing tuner config as **_AlgorithmConfig** (not AlgorithmConfig) fixes the problem, and the experiment launches correctly:

```
experiment.config.tuner = _AlgorithmConfig()
experiment.config.tuner.code_directory = Path(__file__).parent
experiment.config.tuner.class_name = 'my_tuner.CustomTuner'
```

That is kinda tricky. I think an explicit _AlgorithmConfig() usage should be avoided in such situations.

**Comment by liuzhe-lz** [comment]
Please use `CustomAlgorithmConfig`.

```python
experiment.config.tuner = CustomAlgorithmConfig(
    class_name = 'my_tuner.CustomTuner',
    code_directory = ...,
    class_args = ...
)
```

**Comment by survexman** [comment]
Oh, thanks. That solves the problem!
