### ISSUE TITLE
mnist-keras示例bug

### ISSUE THREAD

**Issue by liuxiangchao369** [microsoft/nni#4553]
**Describe the issue**:
在nni/example/trials/mnist-keras/mnist-keras.py 第71行，72行报错如下

Traceback (most recent call last):
  File "mnist-keras.py", line 133, in <module>
    train(ARGS, PARAMS)
  File "mnist-keras.py", line 98, in train
    x_train, y_train, x_test, y_test = load_mnist_data(args)
  File "mnist-keras.py", line 71, in load_mnist_data
    y_train = keras.utils.to_categorical(y_train, NUM_CLASSES)[:args.num_train]
AttributeError: module 'keras.utils' has no attribute 'to_categorical'

此外，第56行报错如下：
Traceback (most recent call last):
  File "mnist-keras.py", line 133, in <module>
    train(ARGS, PARAMS)
  File "mnist-keras.py", line 99, in train
    model = create_mnist_model(params)
  File "mnist-keras.py", line 56, in create_mnist_model
    optimizer = keras.optimizers.SGD(lr=hyper_params['learning_rate'], momentum=0.9)
AttributeError: module 'keras.optimizers' has no attribute 'SGD'

试着将 import keras 改为 from tensorflow import keras 后问题解决

**Environment**:
- NNI version:2.6
- Training service (local|remote|pai|aml|etc):local
- Client OS:7.3
- Server OS (for remote mode only):
- Python version:3.7.4
- PyTorch/TensorFlow version: TensorFlow2.7.0 Keras 2.7.0
- Is conda/virtualenv/venv used?: venv
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:
均使用2.6版本默认配置，未作任何改动

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by liuzhe-lz** [comment]
If you are using TensorFlow, please use "mnist-tfv2" example instead.

**Comment by scarlett2018** [comment]
closing the issue as the answer had been provided, feel free to reopen if the answer does not work well for you, thanks.
