### ISSUE TITLE
How to log to file?

### ISSUE THREAD

**Issue by Fei-Wang** [microsoft/nni#4566]
Without nni, I log to ```filename```  by
```python
logging.basicConfig(filename=filename)
```

But with nni, I find ```init_logger()``` in the ```__init__.py``` file, and when I run
```python
import nni 
```
the log output to console, and with no file?
So, when I use nni, how can I log to file as before?

**Comment by liuzhe-lz** [comment]
You can hack it by run with environment `NNI_PLATFORM=unittest`.
We are working on this problem.

**Comment by Fei-Wang** [comment]
> You can hack it by run with environment variable `NNI_PLATFORM=unittest`.
> We are working on this problem.

Thanks for your reply, I have add ```force=True``` in my logging config code, 
```python3
logging.basicConfig(filename=filename, force=True, ...)
```
and it looks good.
