### ISSUE TITLE
RuntimeError: Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions

### ISSUE THREAD

**Issue by HappyPeanuts** [microsoft/nni#4568]
**Describe the issue**:
When I used NNI to compress the DLA34 network model,
executing ModelSpeedup(model, dummy_input=dummy_input, masks_file='mask_fairmot.pth')
there is a wrong:
 "File"/home/user /. Conda/envs/yang_pytorch/lib/python3.7 / site - packages/torch/jit / _trace py ", line 940, in trace_module_force_outplace,RuntimeError: Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions'. 
Some people have proposed that my model returned is a dictionary. I would like to know how to convert my model from dictionary format to Tensors format.

The return of my model is:
    def forward(self, x):
        x = self.base(x)
        x = self.dla_up(x)
        y = []
        for i in range(self.last_level - self.first_level):
            y.append(x[i].clone())
        self.ida_up(y, 0, len(y))
        output = {}
        output['hm'] = self.__getattr__('hm')(y[-1])
        output['wh'] = self.__getattr__('wh')(y[-1])
        output['reg'] = self.__getattr__('reg')(y[-1])
        output['id'] = self.__getattr__('id')(y[-1])

        return [output]

thanks a lot

**Comment by J-shang** [comment]
I think just `return output` may work, and you need to check if the `values` in `output` are all tensor.
