### ISSUE TITLE
DARTS finds the same architecture after different search epochs

### ISSUE THREAD

**Issue by singagan** [microsoft/nni#4585]
**Describe the issue:**

In my use-case, my search space implementation looks something like:
```
self.block1 = nn.LayerChoice([CustomBlock_kernelsize1(...), CustomBlock_kernelsize2(...), .........., nn.Identity()])
self.block2 = nn.LayerChoice([CustomBlock_kernelsize1(...), CustomBlock_kernelsize2(...), .........., nn.Identity()])
```
CustomBlock= consists of several layers (conv+batchnorm+activation) (similar to[ proxylessnass example](https://github.com/microsoft/nni/blob/c13392ab45104e644151501250593efb336c8ca5/examples/nas/oneshot/proxylessnas/model.py#L60))

While performing NAS, I am getting the same architecture after 1 or 40 epochs.
However, I see the loss decreasing. Is this normal?

I am using the following command to print the architecture:

`print('Final architecture:', trainer.export())`

Also, I noticed that trainer.export() only reports the modules with layerchoice options but it does not report other non-layerchoice modules. Do I need to manually add those during retraining?

Thanks!

**Environment:** Remote Server

**NNI version:** 2.6
**Training service (local|remote|pai|aml|etc):** remote
**Client OS:** Ubuntu 20.04.3 LTS
**Server OS (for remote mode only):** Ubuntu 20.04.3 LTS
**Python version:** Python 3.8.12
**PyTorch/TensorFlow version:** Toch 1.10.0+cu111
**Is conda/virtualenv/venv used?:** conda
**Is running in Docker?:** No

**Experiment config (remember to remove secrets!):** one-shot DARTS

**Comment by ultmaster** [comment]
There has been study over whether DARTS is prone to overfit early. https://arxiv.org/abs/1909.06035 It's related to your search space.

You mentioned `other non-layerchoice modules`. What exactly are you talking about?

**Comment by singagan** [comment]
That's interesting. Indeed, my search space had many skip connects. Now I tried without any skip connects. I still observe the same thing: DARTS seems to be stuck in some sort of local minima. 
What could be the reason for it? 
I am playing with the hyperparameters, but it doesn't seem to help at the moment.

**Comment by ultmaster** [comment]
As I'm not a expert specialized in mathematics behind DARTS, I'm afraid I cannot answer that question. You can read some literatures from recent top-tier conferences. I'm sure they do have some insights and convincing explanations.

Meanwhile, try to tune some hyper-parameters. If you have priors about what kind of architectures might be better, you can also play with initializations and regularizations. You can also try ENAS or ProxylessNAS. In my experience, sometimes (on some search spaces) they work better than DARTS. But, it seems to me that which algo works better is also nothing but luck.

**Comment by singagan** [comment]
Thanks @ultmaster! Indeed it's alot about luck. I am still trying with DARTS and might also give ENAS a shot!

Regarding other `non-layerchoice modules`, I meant all the modules that are not part of `nn.LayerChoice`. For example, if I have a Sequential block before nn.Layerchoice module. These are not reported by trainer.export() 
```
self.block0= nn.Sequential(OrderedDict([
                ('conv', nn.Conv2d(in_C, out_C, 1, 1, 0, bias=False)),
                ('bn', nn.BatchNorm2d(out_C)),
                ('act', nn.ReLU6(inplace=True)),
            ]))
in_C=out_C
for width in width_stage:
        self.block1 = nn.LayerChoice([CustomBlock_kernelsize1(in_C, width,kernel1), CustomBlock_kernelsize2(in_C, width,kernel2), .........., nn.Identity()in_C, width])
        self.block2 = nn.LayerChoice([CustomBlock_kernelsize1(in_C, width,kernel1), CustomBlock_kernelsize2(in_C, width,kernel2), .........., nn.Identity(in_C, width)])
in_C=width
```

So self.block0 would not be reported by trainer.export(), right?

I just realized that adding nn.identity in the above manner leads to the following runtime issue, which is a bit strange

RuntimeError: stack expects each tensor to be equal size, but got [32, 344, 3600] at entry 0 and [32, 480, 3600] at entry 3

**Comment by ultmaster** [comment]
> So self.block0 would not be reported by trainer.export(), right?

Right. No choice, no export.
You need to use `with fixed_arch(...)` to get final model.

> RuntimeError: stack expects each tensor to be equal size, but got [32, 344, 3600] at entry 0 and [32, 480, 3600] at entry 3

I guess it could be `CustomBlock_kernelsize1` and `nn.Identity` are returning different shape for the same input. You should make sure every candidate module in a LayerChoice returns the same shape.

**Comment by singagan** [comment]
Yes, you are right about different shapes. `nn.Identity` returns the tensor as it is while `CustomBlock_kernelsize1` gives a different shape. Would the best approach be to downsample in case of identity or would you recommend something different? Because I am exploring the case where the NAS completely removes this block.

**Comment by singagan** [comment]
I was able to fix the sizes. So I will close the issue for now.
