### ISSUE TITLE
[Dev] Doc Review

### ISSUE THREAD

**Issue by J-shang** [microsoft/nni#4590]
Doc Related PR:
- [ ] #4561
Reviewer: 
- [ ] #4557
Reviewer: 
- [ ] #4560
Reviewer: 
- [ ] #4570
Reviewer: 
- [ ] #4573
Reviewer: 
- [ ] #4574
Reviewer: 
- [ ] #4575
Reviewer: 
- [ ] #4577
Reviewer: 
- [ ] #4579
Reviewer: 
- [ ] #4584
Reviewer: 
- [ ] #4587
Reviewer: 
- [ ] #4589
Reviewer: 
- [ ] #4591
Reviewer:

**Comment by ultmaster** [comment]
https://nni.readthedocs.io/en/doc-refactor/experiment/webui.html   webui -> webportal
https://nni.readthedocs.io/en/doc-refactor/experiment/exp_management.html  exp_management -> experiment_management or exp_manage

![image](https://user-images.githubusercontent.com/8463288/155944913-81377fb5-6654-432a-8593-64ec0d8c1fda.png)
table width is weird. Maybe 25%-75% is better than 50%-50%.
Suggest add link to each training service in this table.

**Comment by Lijiaoa** [comment]
`https://nni.readthedocs.io/en/doc-refactor/experiment/webui.html webui -> webportal` had done in PR https://github.com/microsoft/nni/pull/4570

**Comment by Lijiaoa** [comment]
`https://nni.readthedocs.io/en/doc-refactor/experiment/webui.html webui -> webportal` had done in PR https://github.com/microsoft/nni/pull/4570

**Comment by J-shang** [comment]
Compression:
- Scheduled Pruner or Iterative Pruner: Use scheduled pruner because the pruning process in these pruners is scheduled and iteratively, but some other pruners also have some kind of iterative (sparsifying)...

**Comment by LikeJulia** [comment]
### Review on model compression【Pruning】part.

- 语法部分：

- [ ] A pruning process is usually driven by a pruning scheduler, it contains a specific pruner and a task generator. 
==》 A pruning process is usually driven by a pruning scheduler, **which** contains a specific pruner and a task generator.

- [ ]

**Comment by ultmaster** [comment]
HPO:

This looks like "cite". Might be caused by extra indent.
![image](https://user-images.githubusercontent.com/8463288/157589345-bad78377-48f6-400b-9d9e-5ea87f89e2ae.png)

WebUI -> Web portal

Suggest including tuner reference under HPO toc.

**Comment by matluster** [comment]
https://nni.readthedocs.io/en/latest/hpo/custom_algorithm_installation.html

* ``.. contents`` is not needed.
* Links are broken: https://nni.readthedocs.io/en/latest/hpo/custom_algorithm_installation.html#create-a-customized-tuner-assessor-advisor

*

**Comment by matluster** [comment]
https://nni.readthedocs.io/en/latest/sharings/community_sharings.html

* There is only one document in each of Compression / Feature Engineering. Suggest flattening it.
* Suggest adding `Last updated version` / `Last updated date`, as many of the use cases are out-of-date.

https://nni.readthedocs.io/en/latest/notes/build_from_source.html

* We should ask users to install `dependencies/develop.txt` before running `setup.py develop`. Installing `dependencies/required.txt` is also recommended to avoid automatically installing over-aggressive versions (e.g., rc version). We should also explain the usage of `recommended.txt`.
* Try avoiding mentioning a specific version number (e.g., 2.7) in commands, as this requires updating every release.

**Comment by matluster** [comment]
Quickstart:

* Suggest naming those QuickStarts with a uniformed title format.

**Comment by matluster** [comment]
HPO Overview:

* The three points correspond to three key features. Suggest adding jumping links: 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/79736092/161021707-170dec1e-bf8c-47b0-a9a4-5c451b622b31.png">

*

**Comment by scarlett2018** [comment]
@J-shang - shall we close this issue? are we still working on any of these items?

**Comment by J-shang** [comment]
> @J-shang - shall we close this issue? are we still working on any of these items?

yes, this can be closed
