### ISSUE TITLE
Pruning of Any Object Detection Model

### ISSUE THREAD

**Issue by shenoynikhil98** [microsoft/nni#4601]
1. Is it possible to prune (with ModelSpeedup) torchvision object detection models using nni? (If you could briefly describe the approach to handle this it would be great)
3. I have tried following the yolo example, but it throws some or the other error.

**Comment by shenoynikhil98** [comment]
@xueliang Will be open sharing my codebase in 25 days, is it possible to wait till then. Currently, I am able to prune SSD (Single Shot Detector) with nni.

**Comment by pjl1995** [comment]
@shenoynikhil98 Hi，is your codebase opened？I also want to prune the object detection model. Thanks!

**Comment by VidhiRambhia** [comment]
Hi @shenoynikhil98, I am also working on pruning an object detection model with nni. Can you please share your codebase or some tips to go about this? Really appreciate it!
