### ISSUE TITLE
Issue with model speedup for PyTorch flatten layers

### ISSUE THREAD

**Issue by pmmitche** [microsoft/nni#4620]
### Problem
I'm trying to use NNI's model_speedup function to speedup a pruned efficientnet model. However, it seems that this function has issues when trying to replace the flatten module. From the runtime error, it seems that replacing flatten layers is not allowed/supported. As such, I was wondering how to get around this, or convert it to some form that *can* be replaced. I was not able to find a relevant section when searching the documentation for a while, so any help would be greatly appreciated. I noticed in the [speedup tutorial](https://nni.readthedocs.io/en/stable/Compression/ModelSpeedup.html), there are limitations noted about implementing my own shape inference and module replacement functions, and was wondering if that's what I should do, and if so, if there was a relevant link walking through that a bit? Thanks!

### Environment:
- nni: 2.6.1
- Python: 3.8.10
- torch: 1.10.2+cu113
- using Python virtual environment

### Runtime error:
The runtime error I receive is the following:
```
Traceback (most recent call last):
  File "nni_testing.py", line 72, in <module>
    m_speedup.speedup_model()
  File "......./pt-env/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 516, in speedup_model
    self.replace_compressed_modules()
  File "......./pt-env/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 386, in replace_compressed_modules
    self.replace_submodule(unique_name)
  File "......./pt-env/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 442, in replace_submodule
    raise RuntimeError(
RuntimeError: Has not supported replacing the module: `Flatten`
```

### Example code
Below is a minimal working example of the program I am running:

```
import timm
import torch
from torch import nn
from torchsummary import summary
import torch.nn.utils.prune as prune
import torch.nn.functional as F
from nni.algorithms.compression.pytorch.pruning import LevelPruner
from nni.algorithms.compression.pytorch.pruning import L1FilterPruner
from nni.compression.pytorch import ModelSpeedup
import torch.optim as optim



# create pretrained model
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = timm.create_model('efficientnet_lite0', pretrained=True)
model.to(device)

# define optimizer and critierion
optimizer = optim.Adadelta(model.parameters(), lr=1)
criterion = torch.nn.NLLLoss()

# define pruning configuration list - prune conv2d layers 50%
config_list = [{
    'sparsity': 0.5,
    'op_types': ['Conv2d'],
}]

[print('op_name: {}\nop_type: {}\n'.format(name, type(module))) for name, module in model.named_modules()]

print(model.conv_head.weight.data.size())
print(model.conv_head.weight.data)

# use L1 filter pruning on the model
pruner = L1FilterPruner(model, config_list)

[print('op_name: {}\nop_type: {}\n'.format(name, type(module))) for name, module in model.named_modules()]

# compress the model
pruner.compress()

print(model.conv_head.weight_mask.data.size())
print(model.conv_head.weight_mask.data)

# use a dummy input to apply the sparsify.
dummy_input = torch.randn(100, 3, 360, 640).to(device)
model(dummy_input)

# the weights of `conv1` have been sparsified
print(model.conv_head.module.weight.data)

# export the sparsified model state and mask
pruner.export_model(model_path='pruned_en_l1filter.pth', mask_path='mask_en_l1filter.pth')

# unwrap the model before speeding up
pruner._unwrap_model()
print(model)

# perform model speedup
m_speedup = ModelSpeedup(model, dummy_input, masks_file='mask_en_l1filter.pth')
# ISSUE HERE: Due to flatten layer
m_speedup.speedup_model()

print(model)
```

### How to reproduce it?:
Run the minimal example above with `python3 nni_example.py`, where nni_example.py is whatever you name the file to run that code.

### Log output
Found in the attached `nni_speedup_log.txt` file, here: [nni_speedup_log.txt](https://github.com/microsoft/nni/files/8193678/nni_speedup_log.txt)

**Comment by zheng-ningxin** [comment]
Thanks for the valuable feedback! I have submitted a PR and please have a try when this [pr](https://github.com/microsoft/nni/pull/4628) merged. If you still have some problems, please feel free to connect me.
