### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by thatkiddslash55** [microsoft/nni#4632]
**What would you like to be added**:

**Why is this needed**:

**Without this feature, how does current nni work**：

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by J-shang** [comment]
@thatkiddslash55 you truly open an issue😆, if there is no problem, I will close this issue.

**Comment by thatkiddslash55** [comment]
Help

**Comment by J-shang** [comment]
@thatkiddslash55 , do you meet some trouble?
