### ISSUE TITLE
How to modify experiment names?

### ISSUE THREAD

**Issue by CapFreddy** [microsoft/nni#4647]
Is there a way to modify experiment names? Will changing via `nni-experiments/.experiment` cause some unexpected issues?

**Comment by cruiseliu** [comment]
NNI currently do not have this feature.
The experiment name is also stored in sqlite database in `nni-experiments/<experiment-id>` so your method might not work.
But I believe it will not cause real problem, because the name is merely for display and is never used internally.

**Comment by CapFreddy** [comment]
Thank you for your reply!
