### ISSUE TITLE
quantitation speed up on ARM devices

### ISSUE THREAD

**Issue by bl6g6** [microsoft/nni#4673]
HI, I followed the example code and got a quantized model and its ONNX file by this command 
```
  quantizer.export_model(model_path, calibration_path, onnx_path, input_shape, device)
```
The ONNX file has the same size as the one that didn't do quantization, and the inference speed on ARM devices is the same as well.
So how could I get the quantized ONNX and get speed up on ARM devices?

Thanks for any information.

**Comment by scarlett2018** [comment]
@bl6g6 - refer to https://nni.readthedocs.io/en/stable/Compression/QuantizationSpeedup.html for speedup tool usage after export the model.

**Comment by bl6g6** [comment]
> @bl6g6 - refer to https://nni.readthedocs.io/en/stable/Compression/QuantizationSpeedup.html for speedup tool usage after export the model.

I saw it could speed up on TensorRT, what if I want to use other c++ inference framwork like NCNN?

**Comment by J-shang** [comment]
Hello @bl6g6 , nni only supports using TensorRT as backend right now, if you want to use NCNN,  after `export_model` and getting the `calibration_config`, you need to implement the logic to interface with NCNN.

**Comment by bl6g6** [comment]
> Hello @bl6g6 , nni only supports using TensorRT as backend right now, if you want to use NCNN, after `export_model` and getting the `calibration_config`, you need to implement the logic to interface with NCNN.

I see, thank you both!
