### ISSUE TITLE
SinglePathTrainer中train_loader是否应该设置shuffle=True

### ISSUE THREAD

**Issue by dutxubo** [microsoft/nni#4685]
**Describe the issue**:

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by dutxubo** [comment]
> Probably. Which file are you referring to?

nni/nni/retiarii/oneshot/pytorch/random.py 中
第144行
self.train_loader = torch.utils.data.DataLoader(self.dataset_train,
                                                        batch_size=batch_size,
                                                        num_workers=workers)

**Comment by matluster** [comment]
ok. Could you open a pull request for this?
