### ISSUE TITLE
Configure experiment in python

### ISSUE THREAD

**Issue by lrlofgren** [microsoft/nni#4702]
I am trying to configure an experiment in python, however I have not found a way to edit the tpe_args of the tuner. 

experiment.config.tuner.class_args returns a dictionary and I do not know how to access tpe_args.n_startup_jobs. 

Thanks.

**Comment by liuzhe-lz** [comment]
The new doc has covered this.
https://nni.readthedocs.io/en/latest/reference/hpo.html#nni.algorithms.hpo.tpe_tuner.TpeTuner
