### ISSUE TITLE
How to use multiple GPUs in local mode?

### ISSUE THREAD

**Issue by Data-reindeer** [microsoft/nni#4704]
**Describe the issue**:
I want to use multiple local GPUs to speed up search. However, it does not work as expected when I follow the official tutorial. When I set the _useActiveGpu_ to false, it just keep waiting and report an error. Some advice on my configuration?
(I can successfully run my code with only one GPU with NNI, which eliminates the code problem.)

**Environment**:
- NNI version: 2.6.1
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu 20.04.3 LTS x86_64
- Server OS (for remote mode only): None
- Python version: 3.7.11
- PyTorch/TensorFlow version: 1.10.2+cu113
- Is conda/virtualenv/venv used?: Yes, virtualenv
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!):
experimentName: Fine-tune
trialCommand:  python finetune.py
trialGpuNumber: 1
trialConcurrency: 4
maxExperimentDuration: 24h
maxTrialNumber: 100
tuner:
  name: GridSearch
trainingService:
  platform: local
  useActiveGpu: false

 - Search space:
   runseed:
      _type: choice
      _value: [0, 1, 2]
   dataset:
      _type: choice
      _value: ['bbbp', 'tox21', 'sider', 'clintox', 'bace', 'hiv', 'muv']

**Log message**:
 - nnimanager.log:
 ERROR (NNIRestHandler) Error: File not found: /home/nni-experiments/wo0by6pq/trials/WDkrE/trial.log
 - dispatcher.log: "error": 
 - nnictl stdout and stderr: "error":"File not found: /home/nni-experiments/wo0by6pq/trials/WDkrE/trial.log"
 

**How to reproduce it?**:

**Comment by scarlett2018** [comment]
@Data-reindeer  - refer to the following doc for multiple GPU usage:

https://github.com/microsoft/nni/blob/51d261e7256e2344f8d4cf270bff439819945c9a/docs/source/experiment/local.rst#id3

**Comment by liuzhe-lz** [comment]
Is there anything else running on the GPU?
Please run `nvidia-smi` to confirm the GPU is idle. Or otherwise `useActiveGpu` must be set to `true`.

**Comment by Data-reindeer** [comment]
> Is there anything else running on the GPU? Please run `nvidia-smi` to confirm the GPU is idle. Or otherwise `useActiveGpu` must be set to `true`.

Hi, 
Thank you for your reply. 
I tried to set `useActiveGpu` to `true`. However,  an error raised when I load pre-trained model to device. The detailed trial error show as follow: 

Traceback (most recent call last):
  File "finetune.py", line 172, in <module>
    model.from_pretrained(args.input_model_file)
  File "/home/pretrain/src/models/model2D.py", line 351, in from_pretrained
    self.molecule_model.load_state_dict(torch.load(model_file))
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 142, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

**Comment by Data-reindeer** [comment]
Thank you for your reply !
When I set `useActiveGpu` to `true`, it concurrently runs on 4 Gpus with no error.
