### ISSUE TITLE
TypeError: Dimension value must be integer or None or have an __index__ method, got value '16.0' with type '<class 'float'>'

### ISSUE THREAD

**Issue by DoveEchoing** [microsoft/nni#4719]
**Describe the issue**:
This is the question of my friend,she doesn’t have GitHub account,so I write this issue instead of her.
She uses nni to adjust bilstm model,the codes can run successfully in pycharm but failed in nni.
The problem is here

**the trial log and error**
![FC2D13A7-8765-479D-94BE-FAFAC3E274F0](https://user-images.githubusercontent.com/96108370/160812971-96e4cb69-bc24-41a8-998a-181a672cf342.jpeg)
![F9495F22-FB4E-44A8-97BA-C27C0B673CE5](https://user-images.githubusercontent.com/96108370/160812989-d7249cc7-4788-4e05-ab56-fbc492333292.png)

**Environment**:
- NNI version:2.5
- Training service (local|remote|pai|aml|etc):local
- Client OS:win10
- Server OS (for remote mode only):none
- Python version:3.10
- PyTorch/TensorFlow version:1.1.1/2.7.0
- Is conda/virtualenv/venv used?:no
- Is running in Docker?:no

**Log message**:
 - nnimanager.log:
![C5244F27-D875-4B4F-910C-C61904D821BF](https://user-images.githubusercontent.com/96108370/160816341-80125b50-a702-446f-845e-d3f235d07606.jpeg)
![823C2E59-9D43-469C-97A0-13445B3375D7](https://user-images.githubusercontent.com/96108370/160816351-64ef1508-617b-4fb4-9e39-8e764b059637.jpeg)

 - dispatcher.log:
![15F8E222-70B2-4022-8666-157BD1275C86](https://user-images.githubusercontent.com/96108370/160813334-e2636750-d864-41b6-a9ed-49b7a6d74494.png)

 - nnictl stdout and stderr:blank

code

 
![6CEE6302-81E9-4523-A292-0659F2248B2A](https://user-images.githubusercontent.com/96108370/160813876-775d1693-fbcf-42ea-9fbf-6b1e19dbe723.jpeg)
![4F3C8443-98BE-45D4-8DBC-2D928E53FB2B](https://user-images.githubusercontent.com/96108370/160813897-122dcba0-7652-4f04-9a36-771865886885.jpeg)
![5E0AD6AD-2558-4966-A9A3-3B9CD86F6AD0](https://user-images.githubusercontent.com/96108370/160813948-56bd00a7-a9f1-4e2a-9797-105374c0d412.jpeg)
![CBA5FEAE-CFC9-4913-9F42-B84F12919C98](https://user-images.githubusercontent.com/96108370/160813975-bf7966c4-87cd-486b-a285-bc9f148de2af.jpeg)
![CE2BCB12-667E-4BFF-A490-6449DA84322A](https://user-images.githubusercontent.com/96108370/160814036-4018eae8-1008-4b6b-a466-aec8ade1bad9.png)
![2C72D97B-7C75-4B87-A0F1-E12094640C10](https://user-images.githubusercontent.com/96108370/160814061-f189a69e-ed60-4a45-8037-b7ab9dd27de2.jpeg)

**Comment by liuzhe-lz** [comment]
The parameter is received as float.
Please add for example `int(PARAMS.get('neuron_one'))`.

**Comment by DoveEchoing** [comment]
> The parameter is received as float.
> Please add for example `int(PARAMS.get('neuron_one'))`.

OK，I will tell her your meaning(Maybe because the GitHub site is unstable at home I can’t select ‘quote reply’ to reply you directly. But now I can reply you as this method! Maybe the GitHub site is really unstable in China.)

**Comment by DoveEchoing** [comment]
> The parameter is received as float.
> Please add for example `int(PARAMS.get('neuron_one'))`.

Oh my friend told me she could run that code in nni. Thank you very much!

**Comment by DoveEchoing** [comment]
The problem was solved. I will close this issue.

> The parameter is received as float.
> Please add for example `int(PARAMS.get('neuron_one'))`.

The problem was solved. I will close this issue. Thank you!( Although I have said many times)
