### ISSUE TITLE
Which op_types does QAT support?

### ISSUE THREAD

**Issue by haoshuai-orka** [microsoft/nni#4737]
Hi,

I am trying QAT and I would like to know whether QAT supports op_types like Conv1d, ConvTranspose2d, PReLU and Sigmoid? Or it only supports Conv2d, Linear and ReLU.

Thank you!

**Comment by J-shang** [comment]
Hello @haoshuai-orka , we have not tested on those module types, but I think QAT is supports those types, if you meet any issue, let us know and we will fix it.

**Comment by scarlett2018** [comment]
Closing the issue as the question has been answered. 

@haoshuai-orka - thanks for raising the question, wondering how things going with your QAT experiment, highly appreciated to keep us posted with your findings.
