### ISSUE TITLE
Current support of Retiarii for TensorFlow

### ISSUE THREAD

**Issue by Hrayo712** [microsoft/nni#4756]
I am interesting in evaluating Retiarii for my particular use-case. Looking at the examples, and issues, it seems like currently only Pytorch is supported. However, I do see some mention of TensorFlow support to be introduced in the roadmap [V2.4](https://github.com/microsoft/nni/discussions/3744)  

My question is then: Can retiarii be used with TensorFlow at the moment ? 

I am particularly interested in using ProxylessNAS and FBNet

**Comment by J-shang** [comment]
https://github.com/microsoft/nni/discussions/4605

**Comment by Hrayo712** [comment]
Clear, thank you!
