### ISSUE TITLE
v2.7 Release Note

### ISSUE THREAD

**Issue by J-shang** [microsoft/nni#4763]
## Documentation ##
A full-size upgrade of the documentation, with the following significant improvements in the reading experience, practical tutorials, and examples:
 - Reorganized the document structure with a new document template. ([Upgraded doc entry](https://nni.readthedocs.io/en/v2.7))
 - Add more friendly tutorials with jupyter notebook. ([New Quickstarts](https://nni.readthedocs.io/en/v2.7/quickstart.html))

## Hyperparameter Optimization ##
 - [Improvement] TPE and random tuners will not generate duplicate hyperparameters anymore.
 - [Improvement] Most Python APIs now have type annotations.

## Neural Architecture Search ##
* Jointly search for architecture and hyper-parameters: ValueChoice in evaluator ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#valuechoice))
* Support composition (transformation) of one or several value choices ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#valuechoice))
* Enhanced Cell API (`merge_op`, preprocessor, postprocessor) ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#cell))
* Repeat depth now allows a ValueChoice ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#repeat))
* Support loading `state_dict` between sub-net and super-net ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/others.html#nni.retiarii.utils.original_state_dict_hooks), [example in spos](https://nni.readthedocs.io/en/v2.7/reference/nas/strategy.html#spos))
* Support BN fine-tuning and evaluation in SPOS example ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/strategy.html#spos))
* _(Experimental)_ Model hyper-parameter choice ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#modelparameterchoice))
* _(Preview)_ Lightning implementation for Retiarii including DARTS, ENAS, ProxylessNAS and RandomNAS ([example usage](https://github.com/microsoft/nni/blob/v2.7/test/ut/retiarii/test_oneshot.py))
* _(Preview)_ A search space hub that contains 10 search spaces ([code](https://github.com/microsoft/nni/tree/v2.7/nni/retiarii/hub))

## Model Compression ##
 - Pruning V2 is promoted as default pruning framework, old pruning is legacy and keeps for few releases.([doc](https://nni.readthedocs.io/en/v2.7/reference/compression/pruner.html))
 - A new pruning mode `balance` is supported in `LevelPruner`.([doc](https://nni.readthedocs.io/en/v2.7/reference/compression/pruner.html#level-pruner))
 - Support coarse-grained pruning in `ADMMPruner`.([doc](https://nni.readthedocs.io/en/v2.7/reference/compression/pruner.html#admm-pruner))
 - [Improvement] Support more operation types in pruning speedup.
 - [Improvement] Optimize performance of some pruners.

## Experiment ##
 - [Improvement] `Experiment.run()` no longer stops web portal on return.

## Notable Bugfixes ##
 - Fixed: experiment list could not open experiment with prefix.
 - Fixed: serializer for complex kinds of arguments.
 - Fixed: some typos in code. (thanks @a1trl9 @mrshu)
 - Fixed: dependency issue across layer in pruning speedup. 
 - Fixed: uncheck trial doesn't work bug in the detail table.
 - Fixed: filter name | id bug in the experiment management page.

**Comment by matluster** [comment]
### NAS

* Support ValueChoice in evaluator for mutating hyper-parameters ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#valuechoice))
* Support composition (transformation) of one or several value choices ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#valuechoice))
* Enhanced Cell API (`merge_op`, preprocessor, postprocessor) ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#cell))
* Repeat depth now allows a ValueChoice ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#repeat))
* Support loading `state_dict` between sub-net and super-net (DOC LINK TBD, [example in spos](https://nni.readthedocs.io/en/v2.7/reference/nas/strategy.html#spos))
* Support BN fine-tuning and evaluation in SPOS example ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/strategy.html#spos))
* Model hyper-parameter choice ([doc](https://nni.readthedocs.io/en/v2.7/reference/nas/search_space.html#modelparameterchoice))
* _(Preview)_ Lightning implementation for Retiarii including DARTS, ENAS, Proxyless and RandomNAS. ([example usage](https://github.com/microsoft/nni/blob/v2.7/test/ut/retiarii/test_oneshot.py))
* _(Preview)_ A search space hub that contains 10 search spaces ([code](https://github.com/microsoft/nni/tree/v2.7/nni/retiarii/hub))

**Comment by Lijiaoa** [comment]
bugfixes
- fix uncheck trial doesn't work bug in the detail table #4541
- fix filter name | id bug in the experiment management page #4541
