### ISSUE TITLE
Can nni construct a base model

### ISSUE THREAD

**Issue by ly0303521** [microsoft/nni#4770]
**Hello, if I have no base model first, nni can construct a base model automatically??**:

**Comment by matluster** [comment]
Not really.

You can however, start with a search space from [space hub](https://github.com/microsoft/nni/tree/master/nni/retiarii/hub).

**Comment by ly0303521** [comment]
> Not really.
> 
> You can however, start with a search space from [space hub](https://github.com/microsoft/nni/tree/master/nni/retiarii/hub).

Thank you

**Comment by ly0303521** [comment]
> Not really.
> 
> You can however, start with a search space from [space hub](https://github.com/microsoft/nni/tree/master/nni/retiarii/hub).

I copy the "/home/inspur/Projects/nni/nni/retiarii/hub/pytorch/*"  to "/home/inspur/Projects/nni/examples/nas/multi-trial/mnist/model/*"  . In "/home/inspur/Projects/nni/examples/nas/multi-trial/mnist/search.py", I replace "base_model = Net()" by "base_model = MobileNetV3Space(num_labels=10)", but "AttributeError: type object 'ValueChoice' has no attribute 'max'"

**Comment by ly0303521** [comment]
I know, my nni version is 2.6.1, and the code is 2.7, when I upgrade, the error is gone
