### ISSUE TITLE
网络结构搜索oneshot和超参搜索可以同时进行吗

### ISSUE THREAD

**Issue by ly0303521** [microsoft/nni#4771]
**网络结构搜索oneshot和超参搜索可以同时进行吗**:
在“examples/nas/oneshot/darts” 有网络结构自动搜索，超参是固定的，在“examples/trials/mnist-pytorch”有超参搜索，但是模型固定的，有办法实现网络结构搜索和超参搜索同时进行吗

**Comment by ly0303521** [comment]
“examples/nas/oneshot/darts” realizing the searching network architecture, “examples/trials/mnist-pytorch” realizing the searching hyperparameter, Do they can run at one experiment??

**Comment by matluster** [comment]
There's an upcoming feature in v2.7 release that supports ValueChoice in evaluator.
