### ISSUE TITLE
Google Colab WebUI NAS

### ISSUE THREAD

**Issue by NotSure2732** [microsoft/nni#4779]
**Describe the issue**:
I found the documentation for running the WebUI in google colab: https://nni.readthedocs.io/en/v2.7/sharings/nni_colab_support.html?highlight=colab

Is it possible to get the WebUI in google colab running nas with exp (exp_config & exp.run)?
I followed the documentation until I run into an issue when trying the following:
exp.run(exp_config, 8745)
get_ipython().system_raw('./ngrok http 8745 &')
! curl -s http://localhost:4040/api/tunnels # don't change the port number 4040

The issue is that the second line is only run once the first has finished processing. 
Firstly it would be preferable to see the WebUI during the experiment.
More importantly though, the first line does not seem to finish. It waits for the experiment to be over, which does not happen unless one ctlr+c in the WebUI...

Help is appreciated!

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by matluster** [comment]
Could you run `ngrok` before `exp.run` to see what will happen?

I admit that I'm not an expert in Colab. The Colab tutorial is also a contribution from the community. If you think something is wrong in it, feel free to update the tutorial.

**Comment by NotSure2732** [comment]
I have not been able to get a solution to this. If anyone does have one/ is able to do show how it can be done, I would really appreciate it.

Other than that, is it possible to retain all the information in the webUI (such as trial metrics, intermediate scores, duration for each trial etc without using the WebUI. For example from the logs?

**Comment by matluster** [comment]
> Could you run `ngrok` before `exp.run` to see what will happen?

So this doesn't work?

**Comment by NotSure2732** [comment]
Tbh I have never used ngrok so I am struggling to even get a browser to open up with it.

I tried it following the example from https://nni.readthedocs.io/en/v2.7/sharings/nni_colab_support.html?highlight=colab 
and running the ngrok before the exp.run() and this is:
! ./ngrok authtoken 281HjX10yrKjAO5TrtmxoXGGylX_7k6c4Q6ECKjshgUkF1hqu
get_ipython().system_raw('./ngrok http 5000 &')
! curl -s http://localhost:4040/api/tunnels # don't change the port number 4040

gives me the following output:
Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml
{"tunnels":[],"uri":"/api/tunnels"}

But after running the experiment (with exp.run(exp_config, 5000)) and trying to open the URL, no working web page shows up.

So I was hoping someone has been able to use google colab to get the WebUI (using experiment configuration) and is able to share how they did it.

Any help is appreciated.

**Comment by matluster** [comment]
Have you tried running other web services on this port, e.g., visdom, or tensorboard? Tensorboard is by Google, it could be special. You might want to try visdom. What I'm trying to say here is that you need to be sure whether this is an NNI-related issue or it's a ngrok + colab issue in general.

> So I was hoping someone has been able to use google colab to get the WebUI (using experiment configuration) and is able to share how they did it.

From my experience, it's hard to get other helps here because not many people are using Colab + NNI. Also, this is a GitHub issue forum, not Stackoverflow.

**Comment by sun-tao** [comment]
> Tbh I have never used ngrok so I am struggling to even get a browser to open up with it.
> 
> I tried it following the example from https://nni.readthedocs.io/en/v2.7/sharings/nni_colab_support.html?highlight=colab and running the ngrok before the exp.run() and this is: ! ./ngrok authtoken 281HjX10yrKjAO5TrtmxoXGGylX_7k6c4Q6ECKjshgUkF1hqu get_ipython().system_raw('./ngrok http 5000 &') ! curl -s http://localhost:4040/api/tunnels # don't change the port number 4040
> 
> gives me the following output: Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml {"tunnels":[],"uri":"/api/tunnels"}
> 
> But after running the experiment (with exp.run(exp_config, 5000)) and trying to open the URL, no working web page shows up.
> 
> So I was hoping someone has been able to use google colab to get the WebUI (using experiment configuration) and is able to share how they did it.
> 
> Any help is appreciated.

Hello,I also want to use Colab + NNI, and I try the nas quickstart on colab.I do as [matluster] say,running ngork first and then run the exp. Finally,When I connect to the url it gives,I got the web UI successfully! I think the method is workable.

**Comment by ultmaster** [comment]
I'm closing this issue as there seems to be a feasible solution.
