### ISSUE TITLE
sys.path.append(path) and import model work wrong when coding as https://github.com/microsoft/nni/blob/v2.6/examples/nas/multi-trial/mnist/search.py

### ISSUE THREAD

**Issue by DavideHe** [microsoft/nni#4851]
I want coding the model below the src file path.so I sys.path.append("xxx/src")
but I import the model successfully in  test.py simplly with "sys.path.append("xxx/src");import model"

**Comment by ultmaster** [comment]
Didn't understand. Please provide more details.

**Comment by DavideHe** [comment]
src
├── nas_net.py
├── test.py
scripts
├── nas_train.py
as above, I run code  below scripts filepath.  and  in nas_train.py,I add src path to sys.path and  import nas_net. In nas_net.py there is defined model with model_wrapper.
But ,  In trials/trial_id/stderr, ModuleNotFoundError: No module named 'nas_net' .
If I  add src path to sys.path in test.py and  import nas_net without evaluate_model and nni , it run well. It prove my way of coding  import  nas_net is OK. I comfused  why sys.path.insert failed to add in sys.path in function of evaluate_model with nni.retiarii

**Comment by matluster** [comment]
I think adding sys.path doesn't work for now. You need to run setup.py to install the package in src like this:

Here's an example: https://pytorch-lightning.readthedocs.io/en/1.5.8/advanced/multi_gpu.html#distributed-data-parallel-spawn

**Comment by DavideHe** [comment]
> I think adding sys.path doesn't work for now. You need to run setup.py to install the package in src like this:
> 
> Here's an example: https://pytorch-lightning.readthedocs.io/en/1.5.8/advanced/multi_gpu.html#distributed-data-parallel-spawn

So, sys.path doesn't work  because pytorch-lightning  doesn't support ?
In the link,  I should package my model to libs and setup it to python packages. import it like using the python packages. Is it Right ?
or THE OTHER WAY is moving nas_net.py to scripts filepath.

**Comment by matluster** [comment]
> So, sys.path doesn't work because pytorch-lightning doesn't support ?

No, it's because cloudpickle doesn't support dynamically adding sys.path. Honestly, `sys.path.insert` is a well-known hack, and there's no smart way to identify such hacks and support it.

> In the link, I should package my model to libs and setup it to python packages. import it like using the python packages. Is it Right ?

This is the general approach to avoid `sys.path.append`. I provide the tutorials from pytorch-lightning because it's well written and easy to follow.

**Comment by DavideHe** [comment]
I See , Thank you  very much.

**Comment by DavideHe** [comment]
> 
I See , Thank you very much.

**Comment by mittsommer** [comment]
> > So, sys.path doesn't work because pytorch-lightning doesn't support ?
> 
> No, it's because cloudpickle doesn't support dynamically adding sys.path. Honestly, `sys.path.insert` is a well-known hack, and there's no smart way to identify such hacks and support it.
> 
> > In the link, I should package my model to libs and setup it to python packages. import it like using the python packages. Is it Right ?
> 
> This is the general approach to avoid `sys.path.append`. I provide the tutorials from pytorch-lightning because it's well written and easy to follow.

hello i met the same problem but setup doesn't work
my code dir is
project
|----model
|--------model.py
|----traiin.py
in model.py i define a model named model and in train.py import the model ```from model.model import model```
