### ISSUE TITLE
Are there any tutorials to build NNI on existing frameworks (e.g., mmdetection/detectron2) 

### ISSUE THREAD

**Issue by mitming** [microsoft/nni#4869]

**Comment by QuanluZhang** [comment]
@mitming , thanks for raising this issue. We will add such a tutorial in the next release. The simplest way of tuning mmdetection on NNI for now is writing a python script (as trial code) to receive hyper-parameter values and generate mmdetection config for model training, and report final metric after the training.

**Comment by mitming** [comment]
> @mitming , thanks for raising this issue. We will add such a tutorial in the next release. The simplest way of tuning mmdetection on NNI for now is writing a python script (as trial code) to receive hyper-parameter values and generate mmdetection config for model training, and report final metric after the training.

Thanks for your reply, could you please provide an example for reference? I think I can modify based on it.

**Comment by mitming** [comment]
> > @mitming , thanks for raising this issue. We will add such a tutorial in the next release. The simplest way of tuning mmdetection on NNI for now is writing a python script (as trial code) to receive hyper-parameter values and generate mmdetection config for model training, and report final metric after the training.
> 
> Thanks for your reply, could you please provide an example for reference? I think I can modify based on it.

Hi @QuanluZhang,

Could you please kindly provide me an example for reference?

**Comment by QuanluZhang** [comment]
@mitming , no formal example yet. I wrote one below for your reference.

You should prepare three files in total: 

- `nni_search.py`, the python script that creates and runs an NNI experiment
- `nni_trial_code.py`, the python script that runs an mmdetection training with one received hyper-parameter config
- `nnieval.py`, a customized evaluation hook for mmdetection

The following example is based on training with `config/fast_rcnn/fast_rcnn_r50_fpn_1x_coco.py` in mmdetection. It tunes two hyper-parameters: `num_max_proposals` and `flip_ratio`.

Here is `nni.search.py`:
```python
from nni.experiment import Experiment

search_space = {
    'num_max_proposals': {'_type': 'choice', '_value': [2000, 1500, 1000]},
    'flip_ratio': {'_type': 'uniform', '_value': [0.4, 0.7]}
}

experiment = Experiment('local')
experiment.config.trial_command = 'python3 nni_trial_code.py'
experiment.config.trial_code_directory = '.'
experiment.config.search_space = search_space
experiment.config.tuner.name = 'TPE'
experiment.config.tuner.class_args['optimize_mode'] = 'maximize'
experiment.config.max_trial_number = 10
experiment.config.trial_concurrency = 1

experiment.run(8090)
input('press enter to exit')
```

Here is `nni_trial_code.py`. It receives hyper-parameter values with `nni.get_next_parameter` and updates mmdetection config accordingly, then trains the model using `tools/train.py` provided by mmdetection. At last, it reads the metric hooked with `NniHook` and reports the metric using `nni.report_final_result`.
```python
import os
import json
import nni
from mmcv import Config

cfg = Config.fromfile('configs/fast_rcnn/fast_rcnn_r50_fpn_1x_coco.py')
hyperparams = nni.get_next_parameter()
for tp in cfg.train_pipeline:
    if tp.type == 'LoadProposals':
        tp.num_max_proposals = hyperparams['num_max_proposals']
    if tp.type == 'RandomFlip':
        tp.flip_ratio = hyperparams['flip_ratio']

trial_id = nni.get_trial_id()
nni_eval_hook = {'custom_imports': dict(imports=['mmdet.core.utils.nnieval'], allow_failed_imports=False),
                 'custom_hooks': [dict(type='NniHook', trial_id=trial_id)]}
cfg.merge_from_dict(nni_eval_hook)

cfg_file_name = f'trial_cfg_{trial_id}.py'
cfg.dump(cfg_file_name)
os.system(f'python3 tools/train.py {cfg_file_name}')
with open(f'metric_{trial_id}.json') as f:
    metric = json.load(f)
    nni.report_final_result(metric['acc'])
```

Here is `nnieval.py`, you can following [this doc](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_runtime.html#customize-self-implemented-hooks) to put it in the right place. In this example, I put it under `mmdet/core/utils/`.
```python
import json
from mmcv.runner import HOOKS, Hook

@HOOKS.register_module()
class NniHook(Hook):

    def __init__(self, trial_id):
        self.trial_id = trial_id

    def after_run(self, runner):
        print('nni report after run', runner.outputs)
        with open(f'metric_{self.trial_id}.json', 'w') as f:
            json.dump(runner.outputs['log_vars'], f)
```

Put `nni_search.py` and `nn_trial_code.py` under the root directory of the cloned mmdetection repo. Then, simply run `python3 nni_search.py` to start NNI experiment.

**Comment by mitming** [comment]
> @mitming , no formal example yet. I wrote one below for your reference.
> 
> You should prepare three files in total:
> 
> * `nni_search.py`, the python script that creates and runs an NNI experiment
> * `nni_trial_code.py`, the python script that runs an mmdetection training with one received hyper-parameter config
> * `nnieval.py`, a customized evaluation hook for mmdetection
> 
> The following example is based on training with `config/fast_rcnn/fast_rcnn_r50_fpn_1x_coco.py` in mmdetection. It tunes two hyper-parameters: `num_max_proposals` and `flip_ratio`.
> 
> Here is `nni.search.py`:
> 
> ```python
> from nni.experiment import Experiment
> 
> search_space = {
>     'num_max_proposals': {'_type': 'choice', '_value': [2000, 1500, 1000]},
>     'flip_ratio': {'_type': 'uniform', '_value': [0.4, 0.7]}
> }
> 
> experiment = Experiment('local')
> experiment.config.trial_command = 'python3 nni_trial_code.py'
> experiment.config.trial_code_directory = '.'
> experiment.config.search_space = search_space
> experiment.config.tuner.name = 'TPE'
> experiment.config.tuner.class_args['optimize_mode'] = 'maximize'
> experiment.config.max_trial_number = 10
> experiment.config.trial_concurrency = 1
> 
> experiment.run(8090)
> input('press enter to exit')
> ```
> 
> Here is `nni_trial_code.py`. It receives hyper-parameter values with `nni.get_next_parameter` and updates mmdetection config accordingly, then trains the model using `tools/train.py` provided by mmdetection. At last, it reads the metric hooked with `NniHook` and reports the metric using `nni.report_final_result`.
> 
> ```python
> import os
> import json
> import nni
> from mmcv import Config
> 
> cfg = Config.fromfile('configs/fast_rcnn/fast_rcnn_r50_fpn_1x_coco.py')
> hyperparams = nni.get_next_parameter()
> for tp in cfg.train_pipeline:
>     if tp.type == 'LoadProposals':
>         tp.num_max_proposals = hyperparams['num_max_proposals']
>     if tp.type == 'RandomFlip':
>         tp.flip_ratio = hyperparams['flip_ratio']
> 
> trial_id = nni.get_trial_id()
> nni_eval_hook = {'custom_imports': dict(imports=['mmdet.core.utils.nnieval'], allow_failed_imports=False),
>                  'custom_hooks': [dict(type='NniHook', trial_id=trial_id)]}
> cfg.merge_from_dict(nni_eval_hook)
> 
> cfg_file_name = f'trial_cfg_{trial_id}.py'
> cfg.dump(cfg_file_name)
> os.system(f'python3 tools/train.py {cfg_file_name}')
> with open(f'metric_{trial_id}.json') as f:
>     metric = json.load(f)
>     nni.report_final_result(metric['acc'])
> ```
> 
> Here is `nnieval.py`, you can following [this doc](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_runtime.html#customize-self-implemented-hooks) to put it in the right place. In this example, I put it under `mmdet/core/utils/`.
> 
> ```python
> import json
> from mmcv.runner import HOOKS, Hook
> 
> @HOOKS.register_module()
> class NniHook(Hook):
> 
>     def __init__(self, trial_id):
>         self.trial_id = trial_id
> 
>     def after_run(self, runner):
>         print('nni report after run', runner.outputs)
>         with open(f'metric_{self.trial_id}.json', 'w') as f:
>             json.dump(runner.outputs['log_vars'], f)
> ```
> 
> Put `nni_search.py` and `nn_trial_code.py` under the root directory of the cloned mmdetection repo. Then, simply run `python3 nni_search.py` to start NNI experiment.

Thanks a lot!
