### ISSUE TITLE
why every trial hava same code？

### ISSUE THREAD

**Issue by donghucey** [microsoft/nni#4884]
**Describe the issue**:

in reuse  and strorage mode，why every trial dir hava same code dir，the trial code in each trial is same,we can tar code dir to  envs dir,so that look like simple.

**E nvironment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by liuzhe-lz** [comment]
Do you mean to copy the code for each run, or to have multiple versions of trial codes?

**Comment by donghucey** [comment]
> Do you mean to copy the code for each run, or to have multiple versions of trial codes?

all trial code is same。which case need  multiple versions of trial codes ?

**Comment by scarlett2018** [comment]
the major purpose of <reuse and storage mode> is to use a same code to avoid duplications of codes. 

@liuzhe-lz and @donghucey

**Comment by donghucey** [comment]
1
