### ISSUE TITLE
Retiarii  - Model Accuracy Calculation Question

### ISSUE THREAD

**Issue by impulsecorp** [microsoft/nni#4915]
I was able to get Retiarii working with my custom dataset (for classification), but I don't understand how to get a test or val score for it. It shows what I assume is the training score:
[2022-06-06 15:47:55] INFO (nni.retiarii.oneshot.pytorch.darts/MainThread) Epoch [494/500] Step [1/5]  acc1 1.000000 (1.000000)  loss 0.052471 (0.052471)

I am using the DARTS code from https://nni.readthedocs.io/en/v2.3/NAS/OneshotTrainer.html where the metric is 
metrics=lambda output, target: accuracy(output, target, topk=(1,)),

I defined a val set like this:
train_dataset = ImageFolder('data/my/train', transform=transform)
val_dataset = ImageFolder('data/my/val', transform=transform)
but I don't understand how to use the val set. 

If I add the train=True/False parameter like:
train_dataset = ImageFolder('data/my/train', train=True, transform=transform)
val_dataset = ImageFolder('data/my/val', train=False, transform=transform)
I get this error:   TypeError: __init__() got an unexpected keyword argument 'train'

As an alternative, I assume I could use your Evaluator code (https://nni.readthedocs.io/en/latest/nas/evaluator.html), but I am a little confused on how to use it.  Is this what I need:  https://nni.readthedocs.io/en/v2.3/NAS/QuickStart.html#pick-or-write-a-model-evaluator or maybe https://nni.readthedocs.io/en/latest/tutorials/hello_nas.html#pick-or-customize-a-model-evaluator ?

Or I am doing it the wrong way by using https://nni.readthedocs.io/en/v2.3/NAS/OneshotTrainer.html in the first place for this. I just simply want to try DARTS on my custom classification dataset and see what the Val score is. I don't need anything customized, other than the dataset loading part, which I already have working.

**Comment by matluster** [comment]
Are you using v2.3 or latest?

If you are using v2.3, you should follow examples on v2.3, and documentation on v2.3. If latest, you should follow latest. Seems that you are using two versions interchangeably. This won't work.

The error you get here about unexpected keyword argument `train`, is an incorrect usage of `ImageFolder`. Probably you should firstly read PyTorch documents on the correct usage of `ImageFolder`.
