### ISSUE TITLE
ImportError: DLL load failed while importing _sqlite3: 找不到指定的模块。

### ISSUE THREAD

**Issue by maziyi234** [microsoft/nni#4917]
我按照错误 百度了一下 ，下载了_sqlite3 然后解压到anaconda ddl中，但是还是报错，请问这个问题如何解决呢

**Comment by liuzhe-lz** [comment]
Could you provide full log?

**Comment by scarlett2018** [comment]
看到群里的讨论，结论是“试了环境变量，重启后解决了”。

I'm closing the issue, based on the above WeChat group discussions. feel free to reopen if there are still problems.
