### ISSUE TITLE
RuntimeError: Has not supported replacing the module: `GroupNorm`

### ISSUE THREAD

**Issue by qhy991** [microsoft/nni#4927]
**Describe the issue**:

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by J-shang** [comment]
Sorry for not replying for a long time, we will let you know after we support `GroupNorm`.

**Comment by J-shang** [comment]
`GroupNorm` is supported in nni v2.9
