### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.compression_mnist_model'

### ISSUE THREAD

**Issue by Yaolang003** [microsoft/nni#4939]
My enviriment is  Pyhton3.8.12 and nni2.7. When I run pruning_quick_start_mnist.py，I meet the problem "ModuleNotFoundError: No module named 'scripts.compression_mnist_model'"

**Comment by james20141606** [comment]
run in same issue, did you solve this?

**Comment by Yaolang003** [comment]
您的邮件已收到，谢谢

**Comment by J-shang** [comment]
> run in same issue, did you solve this?

please download https://github.com/microsoft/nni/tree/master/examples/tutorials/scripts and have a try

**Comment by Smile-L-up** [comment]
How does it work?

**Comment by Yaolang003** [comment]
您的邮件已收到，谢谢

**Comment by J-shang** [comment]
> How does it work?

the link is updated, please using https://github.com/microsoft/nni/tree/v2.9/examples/tutorials/scripts

**Comment by xbbkok** [comment]
I also got this problem, how to solve it?

**Comment by Yaolang003** [comment]
您的邮件已收到，谢谢

**Comment by J-shang** [comment]
> I also got this problem, how to solve it?

the link is updated, please try https://github.com/microsoft/nni/tree/v2.9/examples/tutorials/scripts
