### ISSUE TITLE
WebUI界面图标不显示

### ISSUE THREAD

**Issue by xiayouran** [microsoft/nni#4943]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**

**WebUI界面图标不显示 浏览器为Chrome 92.0.4515.107(64位， win7系统)**

![image](https://user-images.githubusercontent.com/45480822/174017709-55ca87a6-1461-419a-9b56-e023a8ca8db3.png)

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version: **2.7**
- nni mode(local|pai|remote): **local**
- OS: Ubuntu **18.04**
- python version: **3.8.13**
- is conda or virtualenv used?: **conda**
- is running in docker?: **no**

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :** **no**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 
```
# path: nni/examples/nas/multi-trial/mnist
 python search.py
```

![image](https://user-images.githubusercontent.com/45480822/174018784-1f067444-84b5-4e3d-a496-ce87730632c5.png)

 - [nnictl stdout and stderr](https://nni.readthedocs.io/en/stable/reference/nnictl.html#nnictl-log-stdout) :

**Comment by scarlett2018** [comment]
> Please make sure your network connection is normal (not stuck), and try to use `ctrl+F5` to refresh the page

@xiayouran - does this answer resolved your problem? thanks.

**Comment by xiayouran** [comment]
@scarlett2018 hi，I tried this method, but it didn't work. Then I cleaned up the cache, but it still didn't work

**Comment by xiayouran** [comment]
nice！Thank you for your reply！

**Comment by scarlett2018** [comment]
> 1. try to use other browser(Microsoft edge) to test these icon issue
> 2. You could run `rm -rf node_modules` `yarn` and `yarn build` in `nni/ts/webui` folder. **It's possible that the dependence doesn't install right.**

@xiayouran - does this work for you?

**Comment by Lijiaoa** [comment]
hi @xiayouran nni v2.9 had been released! And your issue maybe had been fix by these proposal. If you still have this issue, please let me know or reopen this issue. Thanks for using nni.
