### ISSUE TITLE
要是有能支持list为参数的_type就好了

### ISSUE THREAD

**Issue by BraveDrXuTF** [microsoft/nni#4948]
**What would you like to be added**:

**Why is this needed**:比如在多层卷积网络中设计卷积通道数，希望一次设计多层，而不是单个层的通道数设计，因为这样会产生很多冗余的不想要的没有价值的参数组合。这样一来，就需要一系列的list来表达这些设计方案。
![image](https://user-images.githubusercontent.com/47685165/174472758-398507b2-e8e3-4197-a541-52620fb29348.png)
这个batch tuner的办法似乎可以，但是又不支持普通的参数输入了。
**Without this feature, how does current nni work**：
![image](https://user-images.githubusercontent.com/47685165/174472875-3b118dba-fb5b-4c65-810b-3e43dd351f6d.png)

现有的所有seach space的type全都是标量
**Components that may involve changes**:
_type 
**Brief description of your proposal if any**:
暂时没有

**Comment by liuzhe-lz** [comment]
You can workaround using following search space:
```python
search_space = {
    'channels': {
        '_type': 'choice',
        '_value': [
            {'channel1': 16, 'channel2': 64},
            {'channel1': 32, 'channel2': 32},
            {'channel1': 64, 'channel2': 16}
        ],
    },
    'learning_rate': {
        '_type': 'loguniform',
        '_value': [0.00001, 0.1]
    }
}
```
And then in trial code:
```python
params = nni.get_next_parameter()
channel1 = params['channels']['channel1']
channel2 = params['channels']['channel2']
learning_rate = params['learning_rate']
```
