### ISSUE TITLE
detail page empty with tensorflow tutorial code because of the "None"

### ISSUE THREAD

**Issue by osayes** [microsoft/nni#4969]
![temp](https://user-images.githubusercontent.com/18533904/176320472-c1099be4-693b-4e0e-9fae-0a5c78d9911c.jpg)
tutorial link:
https://nni.readthedocs.io/en/stable/tutorials/hpo_quickstart_tensorflow/main.html
https://nni.readthedocs.io/zh/stable/tutorials/hpo_quickstart_tensorflow/main.html
No one would have thought the problem was here

platform: win10
nni version: 2.8
tensorflow version: 2.7.0
python version: 3.9.7

**Comment by ultmaster** [comment]
It's a WebUI bug. @Lijiaoa
