### ISSUE TITLE
ImportError: Cannot use a path to identify something from __main__.

### ISSUE THREAD

**Issue by toufunao** [microsoft/nni#4995]
**Describe the issue**:

When I tried to use NAS, it reported 'ImportError: Cannot use a path to identify something from __main__.' and 'ValueError: Pickle too large when trying to dump <function evaluate_model at 0x7f4112c2d290>. Please try to raise pickle_size_limit if you insist.' 

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:
{'parameter_id': 1, 'parameters': {'class': <class 'tcn.TemporalConvNet'>, 'init_parameters': {'num_inputs': 1, 'output_size': 10, 'num_channels': [10, 10, 10, 10, 10, 10, 10, 10], 'kernel_size': 8, 'dropout': 0.0}, 'mutation': {'model_1': '0', 'model_2': '1', 'model_3': '0', 'model_4': '0', 'model_5': '0', 'model_6': '1', 'model_7': '0', 'model_8': '0'}, 'evaluator': {'type': <class 'nni.retiarii.evaluator.functional.FunctionalEvaluator'>, 'function': <function evaluate_model at 0x7f4112c2d290>, 'arguments': {}}, 'mutation_summary': {'model_1': '0', 'model_2': '1', 'model_3': '0', 'model_4': '0', 'model_5': '0', 'model_6': '1', 'model_7': '0', 'model_8': '0'}}, 'parameter_source': 'algorithm', 'placement_constraint': {'type': 'None', 'gpus': []}, 'version_info': {'python': (3, 7), 'numpy': (1, 18), 'torch': (1, 12), 'pytorch_lightning': None, 'tensorflow': (1, 13), 'cloudpickle': (0, 8), 'json_tricks': (3, 15), 'pyyaml': (5, 4), 'nni': (2, 8)}}

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by ultmaster** [comment]
You should probably raise `pickle_size_limit` as instructed, or put `evaluate_model` in another file.

**Comment by toufunao** [comment]
Thanks, after putting evaluate_model in another file, it could run.

**Comment by ultmaster** [comment]
Closing as there seems to be a feasible workaround.
