### ISSUE TITLE
How to get the best params of a model after the experiment stop

### ISSUE THREAD

**Issue by joshua-xia** [microsoft/nni#5000]
**Describe the issue**:
I am try to use python code to read the best params of a model and then apply them to train the model.
Now I hope the nni store the best params of a model in I defined file after the experiment finished or stopped so that I can read the params in it

Is there this feature?

Thanks!

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by joshua-xia** [comment]
I don't want search the best params from web UI or trial log manually, I wish there is a file store the best params in such as json format so that I can read it using python code and start to train my model automatically.

**Comment by MartinMashalov** [comment]
Hey there, 
I have solved this issue by using the export_data method. First, you run the experiment with: 

_experiment.run(port=8000, wait_completion=True) _

Then I fetch the results with: 

_experiment.export_data()_

I believe the export_data method returns the results in JSON. 

Hope that helps!

**Comment by Lijiaoa** [comment]
hi @joshua-xia  Looks like this issue having a good solution to take it. Could you tell me what's your issue status? Can I close it? Expect your reply. Thanks.
