### ISSUE TITLE
Unable to kill all python threads after `nnictl stop` in async dispatcher mode

### ISSUE THREAD

**Issue by leckie-chn** [Microsoft/nni#501]
**Problem**
User is running multi-thread, when the trial end, not all the python threads are killed.

**How to reproduce**
@leckie-chn can always reproduce -_-|||... 

Currently user has to manually run `killall -9 python3` to kill the zombie threads.

**Comment by QuanluZhang** [comment]
this problem is fixed by https://github.com/Microsoft/nni/pull/968

**Comment by BitCalSaul** [comment]
I encounter the same issue. have to kill them by command.
