### ISSUE TITLE
where is scripts.compression_mnist_model

### ISSUE THREAD

**Issue by james20141606** [microsoft/nni#5019]
**Describe the issue**:
When I tried to run the demo from the doc here https://nni.readthedocs.io/en/stable/tutorials/quantization_speedup.html, I could not found `scripts.compression_mnist_model` in 
`from scripts.compression_mnist_model import TorchModel, trainer, evaluator, device, test_trt`

**Environment**:
- NNI version: 2.8
- Training service (local|remote|pai|aml|etc):
- Client OS: linux
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by J-shang** [comment]
hello @james20141606 , sorry for confusing about this file, here is the scripts https://github.com/microsoft/nni/tree/master/examples/tutorials/scripts

**Comment by scarlett2018** [comment]
> hello @james20141606 , sorry for confusing about this file, here is the scripts https://github.com/microsoft/nni/tree/master/examples/tutorials/scripts

@J-shang shall we add a corresponding fix to the document?

**Comment by J-shang** [comment]
> > hello @james20141606 , sorry for confusing about this file, here is the scripts https://github.com/microsoft/nni/tree/master/examples/tutorials/scripts
> 
> @J-shang shall we add a corresponding fix to the document?

Yes, trying to package these files into nni pipy package

**Comment by J-shang** [comment]
have moved `.scripts` to `nni_assets`, close this issue
