### ISSUE TITLE
How to set useActivateGpu=true in remote mode?

### ISSUE THREAD

**Issue by unikcc** [microsoft/nni#5031]
**Describe the issue**:
I can use the NNI normally with Remote mode on the CPU, although it is very slow.
When I try to use NNI to run the program on GPU under the remote mode, the program is always waiting but didn't run at all. 
One possible reason is that all of the GPUs in the remote machine are partly occupied and the NNI won't use the GPU until the GPU is totally free.
When using the local environment, NNI allows me to set useActivateGpu=true to use the working GPU.
However, in remote mode, it will throw the error that **"AttributeError: RemoteConfig does not have field(s) useactivegpu"**
So I want to know how to set the config to use active GPU under remote Configuration.

**Environment**:
- NNI version: 2.7 
- Training service (local|remote|pai|aml|etc): remote
- Client OS: Ubuntu 20.04
- Server OS (for remote mode only): Ubuntu 20.04
- Python version: 3.8.5
- PyTorch/TensorFlow version: PyTorch v1.8.1
- Is conda/virtualenv/venv used?: use conda environment
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!):
 ```
maxTrialNumber: 20
trialCommand: python main.py
trialCodeDirectory: .
trialGpuNumber: 2
trialConcurrency: 4
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  useActiveGpu: true
  platform: remote
  reuseMode: true
  # gpuIndices: '0'
  machineList:
    - host: xxx.xxx.xx.xx
      user: xxx
      ssh_key_file: ~/.ssh/id_rsa
```
 - Search space:
```
{
  "lr": {"_type": "choice", "_value": [0.002, 0.001, 0.0005]},
  "l2": {"_type": "choice", "_value": [1e-5, 2e-5, 5e-5]}
}
```

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 ```
Traceback (most recent call last):
  File "/home/xxx/.miniconda3/envs/torch/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/home/xxx/.miniconda3/envs/torch/lib/python3.8/site-packages/nni/tools/nnictl/nnictl.py", line 497, in parse_args
    args.func(args)
  File "/home/xxx/.miniconda3/envs/torch/lib/python3.8/site-packages/nni/tools/nnictl/launcher.py", line 77, in create_experiment
    config = ExperimentConfig.load(config_file)
  File "/home/xxx/.miniconda3/envs/torch/lib/python3.8/site-packages/nni/experiment/config/base.py", line 140, in load
    config = cls(**data)
  File "/home/xxx/.miniconda3/envs/torch/lib/python3.8/site-packages/nni/experiment/config/experiment_config.py", line 104, in __init__
    self.training_service = utils.load_training_service_config(self.training_service)
  File "/home/xxx/.miniconda3/envs/torch/lib/python3.8/site-packages/nni/experiment/config/utils/internal.py", line 157, in load_training_service_config
    return cls(**config)
  File "/home/xxx/.miniconda3/envs/torch/lib/python3.8/site-packages/nni/experiment/config/base.py", line 93, in __init__
    raise AttributeError(f'{class_name} does not have field(s) {fields}')
AttributeError: RemoteConfig does not have field(s) useactivegpu
```

**How to reproduce it?**:

**Comment by liuzhe-lz** [comment]
It is a per-machine config for remote mode.
```
maxTrialNumber: 20
trialCommand: python main.py
trialCodeDirectory: .
trialGpuNumber: 2
trialConcurrency: 4
tuner:
 name: TPE
 classArgs:
   optimize_mode: maximize
trainingService:
 platform: remote
 reuseMode: true
 # gpuIndices: '0'
 machineList:
   - host: xxx.xxx.xx.xx
     user: xxx
     ssh_key_file: ~/.ssh/id_rsa
     useActiveGpu: true
```
