### ISSUE TITLE
nnictl webui nas

### ISSUE THREAD

**Issue by tanmay2798** [microsoft/nni#5048]
When I run - nnictl webui nas --logdir logs/<current_time_stamp> --port <port>

I get error - 
usage: nnictl webui [-h] {url} ...
nnictl webui: error: invalid choice: 'nas' (choose from 'url')

nni version - 2.8

**Comment by ultmaster** [comment]
`nnictl webui nas` has been deprecated long ago. If you intend to use it, please downgrade your nni.

**Comment by tanmay2798** [comment]
So in latest version of NNI, how can I see the plots of oneshot algorithms?

**Comment by ultmaster** [comment]
With v2.8, you have to do it on your own.

With the upcoming next release (v2.9), there are some metrics in tensorboard that you can monitor.
