### ISSUE TITLE
nnictl update duration did not validate

### ISSUE THREAD

**Issue by vanzejeffery** [microsoft/nni#5057]
nnictl update duration did not validate
I changed the duration in my terminal, but the duration on the website did not change.
version 2.6.0

**Comment by Lijiaoa** [comment]
Hi, @vanzejeffery Thanks for raising this issue. Could you test it with nni version v2.9? It will be released soon. I often change the experiment duration. And you could change the duration on the webui overview page directly, It's very convenient. Expect your reply.
