### ISSUE TITLE
Unable to access experiments that have previously finished running

### ISSUE THREAD

**Issue by nnnnnzy** [microsoft/nni#5061]
**Describe the issue**:

After stopping a run of experiments at one time and opening a new one, all previous experiments that have ended their run are no longer available. Neither `nnictl view/resume`, `nnictl experiment list --all`, nor Web ui interface will work.

<img width="397" alt="1660239846878" src="https://user-images.githubusercontent.com/55190599/184199078-fe7772b1-b26c-41c6-a7dc-9f4e417b48a5.png">

<img width="241" alt="1660240160350" src="https://user-images.githubusercontent.com/55190599/184200591-6b51688b-4a20-4b0c-8b60-b2b33ec0a98f.png">

Currently only running experiments are available, none of the previously concluded experiments are available.

<img width="1679" alt="1660239946539" src="https://user-images.githubusercontent.com/55190599/184199384-e82d9185-0324-4c12-90e8-1d0f74730978.png">

And in the `~/nni-experiments` directory, the results of previously run experiments are actually there.

What can I do to enable previously closed experiments to be viewed again?

**Environment**:
- NNI version: 2.7
- Training service (local|remote|pai|aml|etc):local
- Client OS:ubuntu
- Server OS (for remote mode only):
- Python version:3.8
- PyTorch/TensorFlow version:pytorch
- Is conda/virtualenv/venv used?:yes
- Is running in Docker?:no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by ultmaster** [comment]
I think your experiment meta-data file might be corrupted. The file can be found in `~/nni-experiments/.experiment`. You can check whether some experiments are missing in the file. As it's a JSON file, you can expect that it's not very reliable. If you want to restore some experiments back, you can use `nnictl experiment load/save`.

**Comment by scarlett2018** [comment]
> I think your experiment meta-data file might be corrupted. The file can be found in `~/nni-experiments/.experiment`. You can check whether some experiments are missing in the file. As it's a JSON file, you can expect that it's not very reliable. If you want to restore some experiments back, you can use `nnictl experiment load/save`.

@nnnnnzy any updates for the issue with these suggestions? thanks.
