### ISSUE TITLE
nni cannot use tensorboard

### ISSUE THREAD

**Issue by cehw** [microsoft/nni#5064]
When I use NNI to conduct hyperparameter searching, I cannot use tensorboard.
As I selected the experiment and click tensorboard button, it will quickly pop up a python window (fig.1), and then the tensorboard page shows error (fig.2). 

for the path in trail source code, I use
log_dir = os.path.join(os.environ["NNI_OUTPUT_DIR"], 'tensorboard')

Indeed, I can see tensorboard log file in each exp directory, but I cannot open the file via nni platform.

However, when I open terminal, and use the tensorboard from there,  open the file in the trail output dir, the tensorboard can work well.   

![Screenshot 2022-08-12 173918](https://user-images.githubusercontent.com/76143149/184328582-880460da-6cc0-4c09-a016-fec9f2a1f385.jpg)
![Screenshot 2022-08-12 174009](https://user-images.githubusercontent.com/76143149/184328607-5c011589-4cd0-447e-889b-d76b26e89099.jpg)

**Environment**:
- NNI version: v2.8
- Training service (local|remote|pai|aml|etc): local
- Client OS: windows
- Server OS (for remote mode only):
- Python version: 3.9.12
- PyTorch/TensorFlow version: pytorch
- Is conda/virtualenv/venv used?: conda 
- Is running in Docker?: no 

**Configuration**:
 - Experiment config : hyperparameter tuning

**Comment by Lijiaoa** [comment]
Did you still have this issue? I really hope that you can try the latest version to test it.

**Comment by cehw** [comment]
Thank you, after I moved to Ubuntu, all the issues were disappeared.

Thanks,
Han
From: Lijiaoa ***@***.***>
Date: Monday, 8 May 2023 at 4:23 PM
To: microsoft/nni ***@***.***>
Cc: Han WANG ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/nni] nni cannot use tensorboard (Issue #5064)

Did you still have this issue? I really hope that you can try the latest version to test it.
