### ISSUE TITLE
Error: not supported

### ISSUE THREAD

**Issue by zjh908491372** [microsoft/nni#5085]
ERROR: aten::zero_ is not Supported!
ERROR: aten::clone is not Supported!

**Comment by J-shang** [comment]
we have a new feature to deal with these ops, https://github.com/microsoft/nni/pull/4996
it will release in nni v2.9.
for now, you can have a try with Alpha version `pip install --extra-index-url https://test.pypi.org/simple/ nni==2.9a2`

**Comment by scarlett2018** [comment]
Close as duplicated.
