### ISSUE TITLE
ERROR: aten:: is not Supported!

### ISSUE THREAD

**Issue by SolomidHero** [microsoft/nni#5090]
ERROR: aten::zeros_like is not Supported!
ERROR: aten::randint is not Supported!
ERROR: aten::ScalarImplicit
ERROR: aten::neg
ERROR: aten::full
ERROR: aten::clamp
ERROR: aten::max

**Comment by jia0511** [comment]
I also encountered the same problem of ERROR: aten::clamp, I hope the next version will solve it.

**Comment by J-shang** [comment]
@SolomidHero @jia0511 

you can have a try on `pip install --extra-index-url https://test.pypi.org/simple/ nni==2.9a2`, most ops you mentioned are supported, except `aten::zeros_like` and `aten::randint`, and we will support them in next official version.

@SolomidHero 

could you give an example for which operation using `aten::ScalarImplicit`?

**Comment by SolomidHero** [comment]
@J-shang
Thank you
I will try workaround for left `aten::zeros_like` and `aten::randint`, I guess you can find somewhere a list of all aten operations torchscript uses.

aten::ScalarImplicit is used in `torch.full` if you provide statistic of tensor. I created an issue, where such example and error is provided
#5097

**Comment by scarlett2018** [comment]
> @J-shang Thank you I will try workaround for left `aten::zeros_like` and `aten::randint`, I guess you can find somewhere a list of all aten operations torchscript uses.
> 
> aten::ScalarImplicit is used in `torch.full` if you provide statistic of tensor. I created an issue, where such example and error is provided #5097

@SolomidHero - thanks for reporting the issue and digging in more, would you like to commit a PR for it?
