### ISSUE TITLE
Use nni in Colab without web UI

### ISSUE THREAD

**Issue by enderminyard** [microsoft/nni#5123]
**Describe the issue**: I would like to use NNI without the Web UI.

**Environment**: Colab
- NNI version: latest
- Training service (local|remote|pai|aml|etc): remote
- Client OS: N/A
- Server OS (for remote mode only): Linux
- Python version: latest
- PyTorch/TensorFlow version: latest
- Is conda/virtualenv/venv used?: Yes
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!): n/a
 - Search space: [default, from quickstart tutorial](https://nni.readthedocs.io/en/v2.5/NAS/QuickStart.html)

**Log message**:
 - nnimanager.log: n/a
 - dispatcher.log: n/a
 - nnictl stdout and stderr: n/a
 

**How to reproduce it?**: When following the tutorial for using NNI in Colab (we followed this [tutorial](https://nni.readthedocs.io/en/stable/sharings/nni_colab_support.html)) you have to use NNI with a web UI. I would like to use NNI programmatically. 

My research partner and I are trying to run an experiment where NNI is just the first step, so the web UI interrupts our experiment and prevents us from making progress.

**Comment by ultmaster** [comment]
The tutorial doesn't enforce you to use WebUI. It only proposes a way for you to access WebUI. If you don't want to see WebUI, you can skip the steps of ngrok and etc.

**Comment by scarlett2018** [comment]
Closing the issue as the question has been answered. 

Yes, you can use nnictl or nni pythonic approach instead of WebUI.

**Comment by enderminyard** [comment]
As far as I could tell, nnictl only allows you to tune the hyperparameters but not the parameters of the model using an evolutionary strategy, which was my goal. Is it possible to do this with nnictl?

Alternatively, is there a way to use the nni pythonic approach that skips the WebUI?
