### ISSUE TITLE
After AGPPrunner，The Flops change to small, But model‘s input output and weight did not change anymore. convert to .onnx before prune and after prune. It also did not change anymore.  

### ISSUE THREAD

**Issue by zctang** [microsoft/nni#5132]
**Describe the issue**:
torch.manual_seed(0)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = get_origin_model(cfg)
    print(model)
    #calculate_kpi(cfg, model, '/data/0530/test/origin_pred')
    dummy_input=torch.rand([1, 12, 272, 480])
    dummy_input=dummy_input.to(device)

    #torch.onnx.export(model, dummy_input.to(device), 'origin.onnx', export_params=True, opset_version=9)

    pre_flops, pre_params, _ = count_flops_params(model, dummy_input.to(device))

    print('start finetuning...')
    config_list = [
        {
        'sparsity': 0.5,
        # 'op_names': ['backbone.features.{}.conv.2'.format(x) for x in range(2, 14)],
        #'op_names': ['backbone.features.{}.conv.0.0'.format(x) for x in range(1, 14)],
        #'op_names': ['backbone.features.{}.conv.1.0'.format(x) for x in range(2, 18)],
        'op_names': ['block{}.conv1.0'.format(x) for x in range(15, 24)],
        'op_types': ['Conv2d']
        # 'op_names': ['backbone.features.0.0', 'backbone.features.2.conv.0.0']
    },
    # {
    #     'sparsity': 0.5,
    #     # 'op_names': ['backbone.features.{}.conv.2'.format(x) for x in range(2, 14)],
    #     #'op_names': ['backbone.features.{}.conv.0.0'.format(x) for x in range(1, 14)],
    #     # 'op_names': ['backbone.features.{}.conv.1.0'.format(x) for x in range(2, 18)],
    #     'op_names': ['block{}.conv2.0'.format(x) for x in range(15, 24)],
    #     'op_types': ['Conv2d']
    #     # 'op_names': ['backbone.features.0.0', 'backbone.features.2.conv.0.0']
    # },
    ]
    criterion = CurveSegmentLoss(cfg)
    optimizer = torch.optim.Adam(params=model.parameters(),lr=cfg.train.learning_rate,weight_decay=cfg.train.weight_decay)
    traced_optimizer=  nni.trace(torch.optim.Adam)(params=model.parameters(),lr=cfg.train.learning_rate,weight_decay=cfg.train.weight_decay)
    # pruner = AGPPruner(model, config_list, pruning_algorithm ='slim', total_iteration=200, finetuner=finetuner,
    #     speedup=True, dummy_input=dummy_input, pruning_params={
    #         "trainer":trainer, "traced_optimizer": traced_optimizer, "criterion": criterion, "training_epochs":1} )
    pruner = AGPPruner(model, config_list, optimizer,  trainer, criterion,
                        num_iterations=200, epochs_per_iteration=1, pruning_algorithm='l2') # 200  1
    pruner.compress()

    model_path = os.path.join("model_path")
    mask_path = os.path.join("mask_path")
    pruner.export_model(model_path=model_path, mask_path=mask_path)
    pruner._unwrap_model()
    ModelSpeedup(model, dummy_input.to(device), mask_path, device).speedup_model()

    flops, params, _ = count_flops_params(model, dummy_input.to(device))
    print(f'Pretrained model FLOPs {pre_flops/1e6:.2f} M, #Params: {pre_params/1e6:.2f}M')
    print(f'pruned model FLOPs {flops/1e6:.2f} M, #Params: {params/1e6:.2f}M')
    calculate_kpi(cfg, model, '/data/0530/test/0913_ni200_e20_block1_pred') # '/data/0530/test/lld_pred'

    torch.onnx.export(model, dummy_input.to(device), '0919_ni200_e1_block1.onnx', export_params=True, opset_version=9)
    print('model convert successfully')

Before prune:
![origin_img_v2_dd94e1ab-16f5-4ff8-80a5-8616a2f5460g](https://user-images.githubusercontent.com/50061822/191151469-4117199b-ffba-4edc-ba2a-727aac049637.png)

After prune：
![origin_img_v2_ffdf2e6c-a2cc-42bc-9371-901d329bdf4g](https://user-images.githubusercontent.com/50061822/191151554-66387337-2647-432f-bd49-2e4a5ba40091.png)

**Comment by J-shang** [comment]
hello @zctang, could you check if the layer named `'block{}.conv1.0'` become smaller after speedup? 
and seems that you use the old pruning version, you can have a try with https://nni.readthedocs.io/en/stable/reference/compression/pruner.html#agp-pruner

**Comment by zctang** [comment]
> hello @zctang, could you check if the layer named `'block{}.conv1.0'` become smaller after speedup? and seems that you use the old pruning version, you can have a try with https://nni.readthedocs.io/en/stable/reference/compression/pruner.html#agp-pruner

Thanks，I already try to use the new version.

**Comment by scarlett2018** [comment]
> > hello @zctang, could you check if the layer named `'block{}.conv1.0'` become smaller after speedup? and seems that you use the old pruning version, you can have a try with https://nni.readthedocs.io/en/stable/reference/compression/pruner.html#agp-pruner
> 
> Thanks，I already try to use the new version.

Seems works on new version, closing the issue. @zctang feel free to reopen if it is not fixed.
