### ISSUE TITLE
The pruning process gets stuck and does not run.

### ISSUE THREAD

**Issue by Alex-Songs** [microsoft/nni#5136]
Hello:
I pruned the network with residual connections in the following way, but the pruning process got stuck and did not run for more than 10 hours:
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/67909291/191679430-01d0e708-5baa-4467-a033-8269fafefa29.png">

The model structure is as follows：
<img width="350" alt="image" src="https://user-images.githubusercontent.com/67909291/191679717-349d19ec-0f29-4c5a-a5c6-9de8ae484377.png">

**Comment by J-shang** [comment]
hello @Alex-Songs , could you give a simple demo model to reproduce your problem?

**Comment by Alex-Songs** [comment]
hello, @J-shang Setting the Model to a 20-layer Transformer encoder can reproduce my problem. I don't know if the residual connection is causing the problem.

**Comment by J-shang** [comment]
> hello, @J-shang Setting the Model to a 20-layer Transformer encoder can reproduce my problem. I don't know if the residual connection is causing the problem.

which kind of transformer do you use? do you use some package like `transformers` or `mmdetection`? we have tested on some transformers like `Bert` `T5` and did not meet the issue.

**Comment by Alex-Songs** [comment]
@J-shang 
I use my own Transformer. After 24 hours, the program runs with an error: ERROR: aten::ScalarImplicit is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks~

**Comment by J-shang** [comment]
please refer https://github.com/microsoft/nni/issues/5097, you can work around by using something like `int(...)` for now.

and it will be fixed in https://github.com/microsoft/nni/pull/5107

**Comment by Alex-Songs** [comment]
@J-shang  I found the problem, the problem is that NNI currently does not support Conv1d, so the program is stuck.

**Comment by Lijiaoa** [comment]
the same issue as #5144
