### ISSUE TITLE
Tutorial based experiment does not end.

### ISSUE THREAD

**Issue by makonaga** [microsoft/nni#5139]
**Describe the issue**:
I am following your tutorial at https://nni.readthedocs.io/en/latest/tutorials/hello_nas.html.
And I have tried changing the "exp_config.max_trial_number" value to 20, but the search always stops at trial 18.
The WebUI also stays at "RUNNING" and does not terminate.
Why is this situation happening?

![nni_webui_screen](https://user-images.githubusercontent.com/68645049/192072490-925255b7-c2f0-4765-9365-18b55b740d1d.png)

**Environment**:
NNI version:2.9
Training service (local|remote|pai|aml|etc):local
Client OS:Ubuntu
Server OS (for remote mode only):
Python version:3.8.8
PyTorch/TensorFlow version: Pytorch 1.10.1
Is conda/virtualenv/venv used?:conda
Is running in Docker?:Pycharm

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 
[nnimanager.log](https://github.com/microsoft/nni/files/9637588/nnimanager.log)

[dispatcher.log](https://github.com/microsoft/nni/files/9637590/dispatcher.log)

**How to reproduce it?**:　Yes

**Comment by matluster** [comment]
Could you provide the logs in your console?

Setting `debug=True` in `exp.run` if you can.

**Comment by makonaga** [comment]
@matluster 
I attach the log file with debug=True.
[nnimanager_with_degub.log](https://github.com/microsoft/nni/files/9642825/nnimanager_with_degub.log)
[dispatcher_with_debug.log](https://github.com/microsoft/nni/files/9642827/dispatcher_with_debug.log)

**Comment by ultmaster** [comment]
Could you provide the logs shown on your console?

**Comment by makonaga** [comment]
Hi, @ultmaster 
私はコンソールログを共有します。
強制終了しない限り、この状態のままです。

[2022-09-27 04:48:53] Creating experiment, Experiment ID: bfnyrlid
[2022-09-27 04:48:53] Starting web server...
[2022-09-27 04:48:54] Setting up...
[2022-09-27 04:48:54] Web portal URLs: http://127.0.0.1:8081 http://192.168.0.110:8081 http://172.17.0.1:8081
[2022-09-27 04:48:54] Dispatcher started
[2022-09-27 04:48:54] Start strategy...
[2022-09-27 04:48:54] Successfully update searchSpace.
[2022-09-27 04:48:54] Random search running in fixed size mode. Dedup: on.

I will also share the Notebook capture screen.

![Screenshot 2022-09-27 04:59:11](https://user-images.githubusercontent.com/68645049/192368671-ca3d8f0b-327e-48b1-a445-7e48cce218fe.png)

**Comment by ultmaster** [comment]
The problem here is that, when you turned dedup on, the strategy won't submit any new models once the space is exhausted. In the tutorial, the space size is 18. But NNI training service believes that there should be at least 20 trials. This is not a bug, but I think we can at least print a warning message for this.

**Comment by scarlett2018** [comment]
> The problem here is that, when you turned dedup on, the strategy won't submit any new models once the space is exhausted. In the tutorial, the space size is 18. But NNI training service believes that there should be at least 20 trials. This is not a bug, but I think we can at least print a warning message for this.

@ultmaster I think we should add a "skipped" status for deduped trials in this case. 
cc @QuanluZhang @liuzhe-lz

**Comment by QuanluZhang** [comment]
In NNI HPO, the experiment status will become "Tuner_No_More_Trial" in this case. NNI NAS has not supported this status.

**Comment by scarlett2018** [comment]
> In NNI HPO, the experiment status will become "Tuner_No_More_Trial" in this case. NNI NAS has not supported this status.

@ultmaster do you think it make senses to use this status for the 2 dedup trials for NAS.

**Comment by ultmaster** [comment]
I think we should add the ability to "done" an experiment through Rest API.

**Comment by scarlett2018** [comment]
Per scrum discussion today, we will discuss the update the current API to change the "Running" status to "Tuner_No_More_Trial" in 3.0. 

Thanks @makonaga for reporting the issue, stay tuned on the update.

**Comment by makonaga** [comment]
@matluster @matluster @scarlett2018 
Thank you.
I could understand the reasons leading to this phenomenon.
(And I could also confirm that this does not happen by setting ”dedup=False.”)
I will close this issue.
