### ISSUE TITLE
Inference fails after speed up 

### ISSUE THREAD

**Issue by hitesh-hitu** [microsoft/nni#5150]
There are many add layers in my model. Pruning and speed up will happen without any issue. I have used dependency aware mode. 

When I run the inference on the compressed model, there is a mismatch in the number of channels in the add layer. Please fix this issue as soon as possible.

**Comment by scarlett2018** [comment]
@hitesh-hitu - would you mind share the model to reproduce the problem? 
cc @J-shang

**Comment by hitesh-hitu** [comment]
Hi, 

I can't share the exact model because of IP. I'll try to share the backbone and see if I can replicate the issue on the same.

**Comment by Lijiaoa** [comment]
hi @hitesh-hitu I'm very pleasure if you could provide the demo for debug!
