### ISSUE TITLE
template for model compression and speedup

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/nni#5156]
template for `model compression and model speedup`

**Describe the issue**:

**NNI version**:

**Demo or example**:

**Reproduce progress**:

**Type(bug | feature)**:

**Comment by J-shang** [comment]
### Report a Bug

**Describe the bug**

**Environment**
platform: linux | windows ...
python: 3.7 | 3.8 | 3.9 ...
nni: v2.8 | v2.9 ...
pytorch: 1.10 | 1.11 | 1.12 ...
cuda: 10.3 | 11.1 | 11.3 | ...

**How to reproduce**
Showing the code is helpful for us to locate the issue.

### Feature request

**Describe the feature**

**Motivations**

**Alternatives**

**Additional context**
