### ISSUE TITLE
HPO not terminate as expect  `max_experiment_duration`

### ISSUE THREAD

**Issue by Tonyhao96** [microsoft/nni#5157]
**Describe the issue**:

How to understand `experiment.config.max_experiment_duration = "1m"` option? The HPO process keeps running although reaching DDL.

I just use the example configuration:
```python

SEARCH_SPACE = {
    "lr": {"_type": "qloguniform", "_value": [1e-4, 1, 1e-4]},
    "momentum": {"_type": "quniform", "_value": [0.1, 0.99, 0.01]},
    "weight_decay": {"_type": "qloguniform", "_value": [1e-5, 1e-2, 1e-5]},
    "batch_size": {"_type": "choice", "_value": [32, 64, 128, 256, 512]},
}

experiment = Experiment("local")
experiment.config.experiment_name = "Cifar Test"
experiment.config.trial_concurrency = 4
experiment.config.max_trial_number = 10
experiment.config.trial_gpu_number = 1
experiment.config.search_space = SEARCH_SPACE
experiment.config.max_experiment_duration = "1m"
experiment.config.trial_command = "python cifar.py"
experiment.config.tuner.name = "TPE"
experiment.config.tuner.class_args["optimize_mode"] = "maximize"
experiment.config.training_service.use_active_gpu = True
experiment.config.training_service.gpu_indices = [0, 1, 2, 3]

experiment.run(8080)
```
**Environment**:
- NNI version: 2.9
- Training service: local
- Client OS: Unbuntu 20.04
- Python version: 3.9
- PyTorch/TensorFlow version: Pytorch 1.12
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

**Comment by Lijiaoa** [comment]
@Tonyhao96 I run the [example](https://github.com/microsoft/nni/blob/master/examples/tutorials/hpo_quickstart_pytorch/main.py) and set `max_experiment_duration = '1h'`. I aslo got this error. Thanks for raising this bug.

**Comment by Tonyhao96** [comment]
Thanks! @Lijiaoa 

Besides, I wonder to know how to disable Web UI and print results in command lines.

**Comment by Lijiaoa** [comment]
> Currently, I cannot see logger/ print intermediate information. Each experiment as below:
> 
> ```shell
> (base) ➜  nni_workload git:(master) ✗ /home/xxx/miniconda3/bin/python /home/xxx/workdir/HPO/hydro/workloads/nni_workload/launch.py
> [2022-10-14 15:38:27] Creating experiment, Experiment ID: 2siw6rbz
> [2022-10-14 15:38:27] Starting web server...
> [2022-10-14 15:38:28] Setting up...
> [2022-10-14 15:38:28] Web portal URLs: http://127.0.0.1:8080 http://10.100.73.111:8080 http://192.168.1.43:8080 http://169.254.3.1:8080 http://172.17.0.1:8080
> [2022-10-14 15:47:59] Stopping experiment, please wait...
> [2022-10-14 15:47:59] Experiment stopped
> ```

so why not see these results in webui...

**Comment by Tonyhao96** [comment]
Thanks for your quick response. 

I am doing some system research work based on NNI. How can I get the debugging information from CLI instead of entering nni-experiments dir to check the log?

**Comment by Lijiaoa** [comment]
hi @Tonyhao96 Could you try the hpo experiment again? My machine could work now, it seems that it may be because of the cache in the browser. I suggest you change a port(`experiment.run(8099)`) to try. Thanks~

**Comment by Tonyhao96** [comment]
I change to the port 8099, but still keep running after 1min DDL

![Screenshot from 2022-10-14 17-32-36](https://user-images.githubusercontent.com/27758466/195814120-454260ab-1b63-42c6-85a6-438f82e71319.png)

**Comment by Lijiaoa** [comment]
`no_more_trial` is not the same as the experiment status `Running`. It means tuner could not dispatch trial because this experiment had reached max duration `1min`. So I suggest you set `max_duration` to `1h` and re-run the experiment.

**Comment by Tonyhao96** [comment]
Noted,  the DDL meaning is different from Ray Tune.

Thanks!
