### ISSUE TITLE
Question on GlobalSparsityAllocator while pruning

### ISSUE THREAD

**Issue by Jonxjdong** [microsoft/nni#5173]
Hello, 

When using NNI to do pruning job, it seems that only TayorFOPruner & SlimPruner support GlobalSparsityAllocator in the sparsity allocating stage, while the rest pruner has to use NormalSparsityAllocator. 

After I went through the whole non-iterative pruners on VGG/Resnet model, the pruners using GlobalSparsityAllocator perform better than the ones using NormalSparsityAllocator. And from the perspective of code, it seems that the pruners also have no problem calling the GlobalSparsityAllocator, so why do not the rest pruners support global mode in sparsity allocation?

**Comment by J-shang** [comment]
> Hello,
> 
> When using NNI to do pruning job, it seems that only TayorFOPruner & SlimPruner support GlobalSparsityAllocator in the sparsity allocating stage, while the rest pruner has to use NormalSparsityAllocator.
> 
> After I went through the whole non-iterative pruners on VGG/Resnet model, the pruners using GlobalSparsityAllocator perform better than the ones using NormalSparsityAllocator. And from the perspective of code, it seems that the pruners also have no problem calling the GlobalSparsityAllocator, so why do not the rest pruners support global mode in sparsity allocation?

Hello @Jonxjdong , good question! There is no problem for other pruners supporting `GlobalSparsityAllocator` from a technical point of view. The reason why other pruners did not support `GlobalSparsityAllocator` is we don't know if it works on these pruners. From the original paper of `TayorFOPruner` and `SlimPruner`, the authors used the global sort in their pruning algorithm, so we support `global` in these two pruners.

Luckily it is possible to support `GlobalSparsityAllocator` in other pruners just by adding several lines in the source code. Please let us know if you expect native support for global mode in other pruners.😉

**Comment by lixuechenAlfred** [comment]
> > Hello,
> > When using NNI to do pruning job, it seems that only TayorFOPruner & SlimPruner support GlobalSparsityAllocator in the sparsity allocating stage, while the rest pruner has to use NormalSparsityAllocator.
> > After I went through the whole non-iterative pruners on VGG/Resnet model, the pruners using GlobalSparsityAllocator perform better than the ones using NormalSparsityAllocator. And from the perspective of code, it seems that the pruners also have no problem calling the GlobalSparsityAllocator, so why do not the rest pruners support global mode in sparsity allocation?
> 
> Hello @Jonxjdong , good question! There is no problem for other pruners supporting `GlobalSparsityAllocator` from a technical point of view. The reason why other pruners did not support `GlobalSparsityAllocator` is we don't know if it works on these pruners. From the original paper of `TayorFOPruner` and `SlimPruner`, the authors used the global sort in their pruning algorithm, so we support `global` in these two pruners.
> 
> Luckily it is possible to support `GlobalSparsityAllocator` in other pruners just by adding several lines in the source code. Please let us know if you expect native support for global mode in other pruners.😉

Actually I have done some experiments to check out if  `GlobalSparsityAllocator`  works on other basic pruners. Basically, NormPruners and ADMMPruner have little improvement (they all use NormMetricsCaculator). FPGM has to do some extra math to conduct cross-layer comparison. ActivationMeanRank supports well, while APoZ turns out unsatisfied. APoZ may be a good metric for unstructured pruning, but I wonder if it works for structured case.

If possible, can I make some contribution to this 'global mode' expansion?

**Comment by J-shang** [comment]
> > > Hello,
> > > When using NNI to do pruning job, it seems that only TayorFOPruner & SlimPruner support GlobalSparsityAllocator in the sparsity allocating stage, while the rest pruner has to use NormalSparsityAllocator.
> > > After I went through the whole non-iterative pruners on VGG/Resnet model, the pruners using GlobalSparsityAllocator perform better than the ones using NormalSparsityAllocator. And from the perspective of code, it seems that the pruners also have no problem calling the GlobalSparsityAllocator, so why do not the rest pruners support global mode in sparsity allocation?
> > 
> > 
> > Hello @Jonxjdong , good question! There is no problem for other pruners supporting `GlobalSparsityAllocator` from a technical point of view. The reason why other pruners did not support `GlobalSparsityAllocator` is we don't know if it works on these pruners. From the original paper of `TayorFOPruner` and `SlimPruner`, the authors used the global sort in their pruning algorithm, so we support `global` in these two pruners.
> > Luckily it is possible to support `GlobalSparsityAllocator` in other pruners just by adding several lines in the source code. Please let us know if you expect native support for global mode in other pruners.😉
> 
> Actually I have done some experiments to check out if `GlobalSparsityAllocator` works on other basic pruners. Basically, NormPruners and ADMMPruner have little improvement (they all use NormMetricsCaculator). FPGM has to do some extra math to conduct cross-layer comparison. ActivationMeanRank supports well, while APoZ turns out unsatisfied. APoZ may be a good metric for unstructured pruning, but I wonder if it works for structured case.
> 
> If possible, can I make some contribution to this 'global mode' expansion?

Sure, any contribution is welcome. we will adjust the directory structure in v3.0, and some improvements will be done on wrapper, please be aware of this. If you have any question, we could communicate at any time😉. Which pruners are you currently planning to support for?
