### ISSUE TITLE
NNI v3.0 preview iteration plan

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#5175]
Release manager: @liuzhe-lz 
Release start date: 10.31
Feature freeze date (at most 30 days): ~~2.10~~ 2.20
Code freeze date & first package: ~~2.17~~ ~~2.24~~ 2.28
Tutorial freeze: ~~2.24~~ 3.3
Release date (3 weeks since feature freeze): ~~3.3~~ 3.10

## Misc ##

* NAS Fine-tune
* HPO integrated to other tool
* Speed up support with Graph (Chunyang)

**Comment by liuzhe-lz** [comment]
## NAS ##

* Refactor `nas.nn`
  * Search space
    * Support `uniform` and `normal` mutable types
    * Support constraints between parameters
    * Support annotation of search space
    * Prettify model space interface
  * Strategy
    * Symbolic execution engine
    * Strategy for new space
  * Execution
    * Support single-process mode 
* Refactor `nas.experiment`
  * Rewrite `exp.__init__` and `exp.run`
  * Support checkpoint
* Debuggability
  * Export summary of search space for every submodule
  * Freeze any submodule to any specific architecture
  * Validation of sampled architecture
  * Run sampled models in one process
* Refactor hardware-ware NAS
  * Refactor
  * One more example
* ~~Evaluation of existing strategies & models~~ (need intern)

## Compression ##

* Common
  * Open more module type in compression
  * Wrapper refactor
  * Simplify invocation path
  * Config key redesign
  * Integrate with fvcore/thop
* Disillation
  * Distillation as a util
  * Pruning examples
  * More distillation loss computing method
* Pruning
  * Remove pruning v1
  * System support block-sparse
  * Huggingface extension
  * More pruning op type
* Speed up
  * troch.fx graph generation (Chunyang)
  * (design) Transformer speedup
  * Review propagate mask method
  * Fix bugs...
* Quantization
  * Refactor
* Quantization speed up (Quanlu)
  * Improve QS on tensorRT
  * Support QS on ORT
  * New PTQ algo AdaRound

**Comment by liuzhe-lz** [comment]
## Compression ##

* Common
  * Open more module type in compression
  * Wrapper refactor
  * Simplify invocation path
  * Config key redesign
  * Integrate with fvcore/thop
* Disillation
  * Distillation as a util
  * Pruning examples
  * More distillation loss computing method
* Pruning
  * Remove pruning v1
  * System support block-sparse
  * Huggingface extension
  * More pruning op type
* Speed up
  * troch.fx graph generation (Chunyang)
  * (design) Transformer speedup
  * Review propagate mask method
  * Fix bugs...
* Quantization
  * Refactor
* Quantization speed up (Quanlu)
  * Improve QS on tensorRT
  * Support QS on ORT
  * New PTQ algo AdaRound

**Comment by liuzhe-lz** [comment]
## HPO ##

* Change default `optimize_mode`
* Pythonic search space factory
* Sklearn tutorial

## NNI Manager ##

* Refactor training service framework
  * Compatibility layer for old training services
  * Merge new local
  * Merge new remote
* Update NNI manager
  * Callback based shutdown
  * Fix & new experiment life cycle test cases
* Refine utilities
  * Log collect
  * Metric collect (check TensorBoard support)
  * GPU scheduler
* Rough distributed trial support

**Comment by liuzhe-lz** [comment]
## Web UI ##

* Unify max/min buttons
* Show cluster info
* Select all & select none
* Export trials to CSV
* Hide trials from chart
* New design for overview page

**Comment by liuzhe-lz** [comment]
## Bug bash ##

### NNI manager ##
* [ ] Local
  + [ ] Basic
  + [ ] Resume
  + [ ] Log
* [ ] Remote
  + [ ] Basic
  + [ ] Resume
  + [ ] Log
  + [ ] Error recovery

**Comment by Lijiaoa** [comment]
> ## Web UI
> * [x]  Unify max/min buttons (1 week)  ~11.8~ 11.10
>   
>   * [use global optimized_mode in related components #5222](https://github.com/microsoft/nni/pull/5222)
> * [ ]  New design for overview page (1 week)  11.19
>   
>   * [x]  main
>     
>     * [PR for overview page new design #5240](https://github.com/microsoft/nni/pull/5240)
>   * [x]  nav bar 12.2
>     
>     * [add nav options changes to overview page #5260](https://github.com/microsoft/nni/pull/5260)
> * [x]  Fix some bugs
>   
>   * [[dev-webui] fix bugs #5246](https://github.com/microsoft/nni/pull/5246)
> * [ ]  (2 weeks total)
>   
>   * [ ]  Show cluster info
>   * [ ]  Select all & select none
>   * [ ]  Export trials to CSV
>   * [ ]  Hide trials from chart

### +1 update
- [x] select all & select none https://github.com/microsoft/nni/pull/5297

**Comment by Lijiaoa** [comment]
### +1 update

Known bugs to be fixed:

- [x] Web UI trial log path does not work (though viewing log should work)
- [x] Resuming trials does not work (resuming experiment should work) **in resume mode, trial‘s ’duration will be recalculated**

**Comment by liuzhe-lz** [comment]
## Release Note ##

### NAS ###

@ultmaster

### Compression ###

@J-shang

### NNI Manager ###

@liuzhe-lz

**Comment by Lijiaoa** [comment]
### V3.0 Related issue ###
https://github.com/microsoft/nni/issues/5531
https://github.com/microsoft/nni/issues/5477
https://github.com/microsoft/nni/issues/5464
https://github.com/microsoft/nni/issues/5452
https://github.com/microsoft/nni/issues/5418
https://github.com/microsoft/nni/issues/5263
https://github.com/microsoft/nni/issues/5253
https://github.com/microsoft/nni/issues/5239
https://github.com/microsoft/nni/issues/4786
https://github.com/microsoft/nni/issues/5192
https://github.com/microsoft/nni/issues/5046
https://github.com/microsoft/nni/issues/5097
https://github.com/microsoft/nni/issues/5090

------------------------------------------------------------------------
https://github.com/microsoft/nni/issues/5248
https://github.com/microsoft/nni/issues/5202
https://github.com/microsoft/nni/issues/5143
https://github.com/microsoft/nni/issues/5104
https://github.com/microsoft/nni/issues/5064

**Comment by ShrutiSarikaChakraborty** [comment]
Hi,

The instruction was - "Use nni.nas.model_context, rather than nni.nas.fixed_arch". 

However I am getting error for 2.10 version -,

import nni.nas.model_context
Traceback (most recent call last):

  File "C:\Users\ADMIN\AppData\Local\Temp\ipykernel_14148\1503585595.py", line 1, in <module>
    import nni.nas.model_context

ModuleNotFoundError: No module named 'nni.nas.model_context'

I checked that nni.nas has NOT got any module named model_context in either v2.10 or v3.0. Please help.

Thanks

**Comment by ultmaster** [comment]
> Hi,
> 
> 
> 
> The instruction was - "Use nni.nas.model_context, rather than nni.nas.fixed_arch". 
> 
> 
> 
> However I am getting error for 2.10 version -,
> 
> 
> 
> import nni.nas.model_context
> 
> Traceback (most recent call last):
> 
> 
> 
>   File "C:\Users\ADMIN\AppData\Local\Temp\ipykernel_14148\1503585595.py", line 1, in <module>
> 
>     import nni.nas.model_context
> 
> 
> 
> ModuleNotFoundError: No module named 'nni.nas.model_context'
> 
> 
> 
> I checked that nni.nas has NOT got any module named model_context in either v2.10 or v3.0. Please help.
> 
> 
> 
> Thanks

Dup of #5585
