### ISSUE TITLE
Please provide updated example code of pruning

### ISSUE THREAD

**Issue by wwdok** [microsoft/nni#5192]
**What would you like to be added**:
provide updated example code of pruning

**Why is this needed**:
I got warning: `WARNING: The old API trainer,traced_optimizer,criterion,training_batches,mode,dummy_input will be deprecated after NNI v3.0, please using the new one evaluator,training_steps,mode,dummy_input` when runing the example pruning code from [here](https://github.com/microsoft/nni/blob/master/examples/model_compress/pruning/activation_pruning_torch.py). As far as i know, other pruning api have the same warning like TaylorFOWeightPruner, ADMMPruner etc.

**Without this feature, how does current nni work**：
It can work in nni 2.9, but after nni 3.0, the api will deprecated

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by J-shang** [comment]
Thanks for your reminder! we will update the latest examples in v3.0!
