### ISSUE TITLE
Some NAS Search Strategy won't exit even the experiment reaches the maxTrialNum

### ISSUE THREAD

**Issue by amznero** [microsoft/nni#5202]
**Environment**:
- NNI version: 2.8
- Training service (local|remote|pai|aml|etc): Local
- Client OS: Ubuntu 18.04
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: 
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: Yes

**Configuration**:
 - Experiment config:
   - NAS(Retiarii) + RegularizedEvolution

**Describe the issue**:

When I use the `RegularizedEvolution` strategy to search models, the experiment will hang even if the trial number reaches the maxTrialNum.

So I check the implementation and found the status check function cannot be called, despite the NNIManager sending the `Done` message to terminate the experiment.

https://github.com/microsoft/nni/blob/f39b811cd71688eae2c22c09aedc87fe904f2191/nni/nas/experiment/pytorch.py#L306-L308

I try to push a simple PR to fix it #5201.

**How to reproduce it?**:
Use RegularizedEvolution Strategy and set maxTrialNum.

Related issues: #4891

**Comment by ultmaster** [comment]
We are aware that it's a known issue, and 've been already working on a fix.
Thanks for your contribution!
