### ISSUE TITLE
How to selectively input training data during hpo

### ISSUE THREAD

**Issue by doubelejjyy** [microsoft/nni#5203]
The current hpo run is: `experiment.config.trial_command` = 'python model.py'
But what I want is to not write the training data in model.py, but to pass in different data during the experiment, how to achieve this

**Comment by liuzhe-lz** [comment]
You can use [`nni.get_sequence_id()`](https://nni.readthedocs.io/en/stable/reference/hpo.html#nni.get_sequence_id) (returns integer index) or [`nni.get_trial_id()`](https://nni.readthedocs.io/en/stable/reference/hpo.html#nni.get_trial_id) (returns string unique ID) in trial code and load different data depending on the return value.

**Comment by Lijiaoa** [comment]
hi @doubelejjyy Could I close this issue as completed?
