### ISSUE TITLE
Network Morphism - Deepening a layer

### ISSUE THREAD

**Issue by salisjoshi** [Microsoft/nni#521]
Hi,

I have a query related to deepening operation in the project. After going through the implementation for deepening a network, I found that the approach is the one defined in Net2Net Paper rather than Network Morphism Paper. Is the deepening operation based on Network Morphism Paper or Net2Net Paper ?

**Comment by leelaylay** [comment]
Yes, the deeper operation and wider operation is similar to the implementation in [Net2Net](https://github.com/DanielSlater/Net2Net).
