### ISSUE TITLE
HPO for a deep MLP Regression Tensorflow model

### ISSUE THREAD

**Issue by Seyedfarazeftehar** [microsoft/nni#5236]
Hi 
I am trying to do HPO for a deep MLP Regression Tensorflow model.
My question is that I read the below documentation, but I could not find how to tune the number of layers and I want to use PTE. 
https://nni.readthedocs.io/en/latest/tutorials/hpo_quickstart_tensorflow/model.html 
It should be mentioned that I am doing my HPO on High Performance Computing (HPC) server. Should I consider any points for this as well?

Really appreciate your help and feedback.

**Comment by cruiseliu** [comment]
You can use a hyper-parameter like `'layer_num': {'_type': 'choice', '_value': [3, 4, 5]}` and then in model code, build the network depending on the value:
```python
layer_num = nni.get_next_parameter()['layer_num']
for i in range(layer_num):
    self.layers.append(...)
```

**Comment by Lijiaoa** [comment]
Thanks for @Seyedfarazeftehar raising this usage issue. Could you close this issue as completed? Thanks!
