### ISSUE TITLE
NAS export source code error

### ISSUE THREAD

**Issue by xiaoerqi** [microsoft/nni#5237]
**Describe the issue**:
With the NAS, i want export source code, but when i set exp_config.execution_engine = 'base', it has a error:

Exception has occurred: PayloadTooLarge
Pickle too large when trying to dump <nni.nas.nn.pytorch.mutator.ParameterChoiceMutator object at 0x7f1f99a64c40>. This might be caused by classes that are not decorated by @nni.trace. Another option is to force bytes pickling and try to raise pickle_size_limit.

**Environment**:
- NNI version:2.10
- Training service (local|remote|pai|aml|etc):local
- Client OS:linux
- Server OS (for remote mode only):
- Python version:3.8
- PyTorch/TensorFlow version:1.10.0
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?:No

**Configuration**:
 - Experiment config (remember to remove secrets!):
```
exp = RetiariiExperiment(model_space, evaluator, [], search_strategy)
exp_config = RetiariiExeConfig('local')
exp_config.experiment_name = 'mnist_search'

exp_config.max_trial_number = 4   
exp_config.trial_concurrency = 1

exp_config.trial_gpu_number = 1
exp_config.training_service.use_active_gpu = True
exp_config.experiment_working_directory = '/training/mango/Etch/NAS/nni-exp'
print(exp_config)
exp_config.execution_engine = 'base'
export_formatter = 'code'
```
 - Search space:
```
@model_wrapper
class ModelSpace(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        feature = nn.ValueChoice([64, 128, 256])
        feature2 = nn.ValueChoice([1, 0.5])

        fc1 = nn.Sequential(
        nn.Linear(input_size, output_size),
        )

        fc2 = nn.Sequential(
        nn.Linear(input_size, feature),
        nn.ReLU(), 
        nn.Linear(feature, output_size),
        )

        fc3 = nn.Sequential(
        nn.Linear(input_size, feature),
        nn.ReLU(), 
        nn.Linear(
            feature,           
            cast(int, nn.ValueChoice.to_int(feature * feature2))),
        nn.ReLU(), 
        nn.Linear(cast(int, nn.ValueChoice.to_int(feature * feature2)), output_size),
        )
        
        self.fc = nn.LayerChoice([
        fc1,
        fc2,
        fc3,
        ])

    def forward(self, x):
        output = self.fc(x)
        return output
```

**Log message**:
 - nnimanager.log:
 [2022-11-21 17:10:53] INFO (main) Start NNI manager
[2022-11-21 17:10:53] INFO (NNIDataStore) Datastore initialization done
[2022-11-21 17:10:53] INFO (RestServer) Starting REST server at port 8080, URL prefix: "/"
[2022-11-21 17:10:53] INFO (RestServer) REST server started.
[2022-11-21 17:10:54] INFO (NNIManager) Starting experiment: m4bto2ez
[2022-11-21 17:10:54] INFO (NNIManager) Setup training service...
[2022-11-21 17:10:54] INFO (LocalTrainingService) Construct local machine training service.
[2022-11-21 17:10:54] INFO (NNIManager) Setup tuner...
[2022-11-21 17:10:54] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2022-11-21 17:10:54] INFO (NNIManager) Add event listeners
[2022-11-21 17:10:54] INFO (LocalTrainingService) Run local machine training service.
[2022-11-21 17:10:54] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
 - dispatcher.log:
 - nnictl stdout and stderr:

**Comment by matluster** [comment]
Please try to raise pickle size limit by `export PICKLE_SIZE_LIMIT=1048576`.

Also there are many known issues with "base" execution engine. I wouldn't recommend trying it.

**Comment by xiaoerqi** [comment]
Thank you for your answer. I tried to set PICKLE_ SIZE_ LIMIT, but it seems to have no effect. Even I ran the script provided in exsample form https://github.com/microsoft/nni/blob/b06f3921fbb483740d5f43d12f4866f08aa95ea6/test/retiarii_test/naive/search.py，also with the same error. I hope this function can have a stable version

**Comment by ultmaster** [comment]
I noticed the version in retiarii_test is really out-of-date. Sorry for that.

Could you try the example in examples/nas/multi-trial/mnist?
