### ISSUE TITLE
WARNING: throw some args away when calling the function "upsample_nearest2d"

### ISSUE THREAD

**Issue by mawj111** [microsoft/nni#5245]
**Describe the bug**:
When I use the ModelSpeedup function, the terminal reports a warning as follow.
**WARNING: throw some args away when calling the function "upsample_nearest2d"**
This causes errors in the sampling process on the FPN network. **Does ModelSpeedup not support this operation?** 
I would appreciate it if someone can answer it.

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): remote
- Python version: 3.8.0
- PyTorch version: 1.8.1
- Cpu or cuda version: cuda10.1

**Reproduce the problem**
- Code|Example:
FPN pytorch code:
```
def forward(self, input):
    input = list(input.values())

    output1 = self.output1(input[0])
    output2 = self.output2(input[1])
    output3 = self.output3(input[2])

    up3 = F.interpolate(output3, size=[output2.size(2), output2.size(3)], mode="nearest")
    output2 = output2 + up3
    output2 = self.merge2(output2)

    up2 = F.interpolate(output2, size=[output1.size(2), output1.size(3)], mode="nearest")
    output1 = output1 + up2
    output1 = self.merge1(output1)

    out = [output1, output2, output3]
    return out
```

After modelspeedup, the terminal reports the message and an error as follows.
![image](https://user-images.githubusercontent.com/65847115/203932956-28a48b9a-8586-41ce-84da-e0d8916e3ed6.png)
![image](https://user-images.githubusercontent.com/65847115/203932892-38b88a06-fd72-41da-9fea-b4ba4bc0bd1d.png)

**Comment by Louis-J** [comment]
the upsample_nearest2d has an input 'size' whose value is a list, and the current version of ModelSpeedup has bugs to list or tuple inputs.

we are refactoring ModelSpeedup, and this bug will be solved in the new version.

**Comment by Louis-J** [comment]
Could you offer a reproducible code to help me test new version? The new ModelSpeedup is at `https://github.com/Louis-J/nni/tree/new_speedup` If you are interested.

**Comment by mawj111** [comment]
@Louis-J  I am very interested in this new version! But I'm just a student with limited abilities, so I can only test again. If there is a problem, I hope you can understand. 
Before testing, I ran ~pip install nni --upgrade~. Just now I retested my code and found that this warning still exists, but finally I can successfully prune. I don't know if the new version has been merged into ~https://github.com/microsoft/nni~. Not sure if it is of some help to you? The test code I used is below, which is referenced from ~https://github.com/biubug6/Pytorch_Retinaface~
[retina.zip](https://github.com/microsoft/nni/files/10151131/retina.zip)

**Comment by Louis-J** [comment]
thanks a lot. i'll try the new version with your code.

**Comment by Louis-J** [comment]
tested ok on cpu. There is a bug on gpu in the old ModelSpeedup that might cause the mismatch between layers. you can try on cpu again.

**Comment by Lijiaoa** [comment]
@mawj111 any updates? Could you close this issue if you have any problem?

**Comment by mawj111** [comment]
no updates, as for Louis-J, cpu is ok. I will close this issue, thank you very much.
