### ISSUE TITLE
AssertionError: Could not found shapes for layer body.conv1" for QAT_quantizer()

### ISSUE THREAD

**Issue by ToniButland1998** [microsoft/nni#5253]
**Describe the issue**:

I am using QAT_quantizer() and my quantize config is :

Config_list = [{
'quant_tyes': ['input'],
'quant_bits': {'input': 8},
'op_types': ['Conv2d']
}]
 I call the quantizer by "quantizer = QAT_quantizer (net, config_list, optimizer)" without passing "dummy_input". But I encounter such error "Traceback (most recent call last):
  File "quantize.py", line 184, in <module>
    quantizer = QAT_Quantizer(net, config_list,optimizer)
  File "/mnt/ssd/anaconda3/envs/yolov6/lib/python3.7/site-packages/nni/algorithms/compression/pytorch/quantization/quantizers.py", line 405, in __init__
    assert name in self.all_shapes, "Could not found shapes for layer {}".format(name)
AssertionError: Could not found shapes for layer body.conv1"
![img_v2_a3b244e7-3c1d-4782-b6de-a42e9d314beg](https://user-images.githubusercontent.com/42618317/204927830-332cf670-4feb-45b5-b73a-f277ca54eeb9.png)

The error could be solved by passing a dummy_input into the QAT_quantizer. But I do not want to pass it(I don not need BN fold here). Therefore, I would like to know how can I solve the error without passing a dummy_input.

**Environment**:
- NNI version: 2.5, 2.9
- Python version: 3.7

**Comment by Lijiaoa** [comment]
any updates?

**Comment by J-shang** [comment]
> any updates?

nni 3.0 will support this
