### ISSUE TITLE
use L1NormPruner to prune unet model, but get no helpful debug info

### ISSUE THREAD

**Issue by dreamlychina** [microsoft/nni#5255]
The code is following:
        config_list = [{'sparsity_per_layer': 0.5,
                                'op_types': ['Conv2d']}
                            ]
          pruner = L1NormPruner(net, config_list)
          print(net)
          _, masks = pruner.compress()
          pruner._unwrap_model()
          ModelSpeedup(net, torch.rand(1, 1, 312, 312).cuda(), masks).speedup_model()
          print(net)
          exit()

The debug info:
   
Columns 307 to 312 -3.7252 -6.3372 -5.5232 -6.1787 -3.3691 -6.0092
 -3.1199 -3.0342 -2.3292 -2.6208 -3.0857 -2.1151
 -2.7310 -2.5961 -2.7734 -2.6970 -2.9965 -2.2961
 -2.4285 -2.7244 -3.0192 -2.2976 -2.4773 -2.3920
 -3.2919 -3.1520 -2.5450 -2.4608 -2.8553 -2.3553
 -2.9280 -2.8643 -2.8208 -3.0457 -2.9394 -2.3887
 -2.3652 -2.7316 -2.9549 -2.5012 -2.7490 -2.3050
 -2.7703 -2.8257 -2.8247 -2.5856 -2.5687 -2.2536
...              ...          ...          ...            ...             ...
 -1.7599 -1.9253 -2.0118 -2.0225 -2.0360 -1.3106
[ torch.cuda.FloatTensor{1,1,312,312} ]

I just want to know how to get the log file and find the error info?

**Comment by Lijiaoa** [comment]
@dreamlychina Thanks for raising this issue. Please use the issue template to refine your issue. Thanks! https://github.com/microsoft/nni/issues/new?assignees=&labels=&template=model-compression-bug-report.md

 **Describe the bug**:



**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Python version:
- PyTorch version:
- Cpu or cuda version:


**Reproduce the problem**
- Code|Example:


- How to reproduce:

**Comment by dreamlychina** [comment]
> 

thanks for your reply, 
NNI Version：2.10
Training service：remote
Python version: 3.8.3
PyTorch version: 1.10.0+cu111
Cpu or cuda version: GPU


code：
net = Unet()

config_list = [{'sparsity_per_layer': 0.5,
'op_types': ['Conv2d']}
]
pruner = L1NormPruner(net, config_list)
print(net)
_, masks = pruner.compress()
pruner._unwrap_model()
ModelSpeedup(net, torch.rand(1, 1, 312, 312).cuda(), masks).speedup_model()
print(net)

I just want to know how to get the log file and find the error info?

**Comment by Bonytu** [comment]
@dreamlychina. Thanks for raising this issue. Did you use the NNI Experiment? If you use the NNI Experiment, the ModelSpeedUp log is in the trail log, otherwise, it is printed on the console.

**Comment by dreamlychina** [comment]
> yes, it is printed on the console, but only "[ torch.cuda.FloatTensor{1,1,312,312} ]" was printed on the console and i do not konw what make this bug happen.
the link of the code is https://github.com/milesial/Pytorch-UNet/blob/master/train.py.
could please help me find the bug if it's convenient for you.

**Comment by Bonytu** [comment]
Hey, @dreamlychina, I will try it. Thank you!

**Comment by Bonytu** [comment]
@dreamlychina, hi, according to your hint, I ran the code, and the printed error is as follows:
```
File "/anaconda/envs/test_bug/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/anaconda/envs/test_bug/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/test_bug/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/anaconda/envs/test_bug/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/anaconda/envs/test_bug/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/test_bug/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/anaconda/envs/test_bug/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[8, 1, 312, 312] to have 3 channels, but got 1 channels instead
```
Can you provide your complete code and environment? Thanks.

**Comment by Lijiaoa** [comment]
feel free to reopen if you have any other question. @dreamlychina
