### ISSUE TITLE
couldn't run model speedup successfully

### ISSUE THREAD

**Issue by dreamlychina** [microsoft/nni#5283]
**Describe the issue**:

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by Lijiaoa** [comment]
Thanks for @dreamlychina raising this issue. Please paste your model error message by using the issue template, thanks.

**Comment by J-shang** [comment]
close this issue for no more infos
