### ISSUE TITLE
The shape of final 1x1 conv layer in UNet changed due to which inference fails after model speed up

### ISSUE THREAD

**Issue by nralka2007** [microsoft/nni#5285]
**Describe the issue**:

for a 3 class semantic segmentation problem , the dense model has weights (conv_final): Conv2d(16, 3, kernel_size=(1, 1), stride=(1, 1)). But after the speedup operation, it is changed to (conv_final): Conv2d(4, 1, kernel_size=(1, 1), stride=(1, 1)) - the model inference fails as it expects a 3 channel output and gets 1. I am using L1 pruner with dependency-aware mode for a UNet architecture

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by J-shang** [comment]
hello @nralka2007 , please have a try with `exclude` in config_list
```
[
    ...,
    {
        'exclude': True,
        'op_names': ['conv_final']
    }
]
```

**Comment by Lijiaoa** [comment]
@nralka2007 any update?

**Comment by J-shang** [comment]
Closed due to no reply for a long time, please reopen if have any questions.
