### ISSUE TITLE
master's default version is v0.3.0-139-gce58518

### ISSUE THREAD

**Issue by PurityFan** [Microsoft/nni#529]
It seems that master branch doesn't specify a tag. The current default value is v0.3.
I think v0.3 is unreasonable, it should be specified as the latest version or not display.

**Comment by PurityFan** [comment]
Use the correct way when merge back to master.

**Comment by leelaylay** [comment]
> Use the correct way when merge back to master.

I also think it no appropriate.

**Comment by PurityFan** [comment]
> > Use the correct way when merge back to master.
> 
> I also think it no appropriate.

Why?

**Comment by leelaylay** [comment]
It seems that  the default environment now in master branch is still v0.3.0.

**Comment by PurityFan** [comment]
Has been resolved in a recent release
