### ISSUE TITLE
cannot fix the mask of the interdependent layers

### ISSUE THREAD

**Issue by sungh66** [microsoft/nni#5298]
**Describe the issue**:
When i pruned the segmentation model.After saving the mask.pth,when i speed up ,the mask cannot fix the new architecture of the model

**Environment**:
- NNI version:2.0
- Training service (local|remote|pai|aml|etc):local
- Client OS:ubuntu
- Server OS (for remote mode only):
- Python version:3.7
- PyTorch/TensorFlow version:pytorch
- Is conda/virtualenv/venv used?:yes
- Is running in Docker?:no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
mask_conflict.py,line195,in fix_mask_conflict
assert shape[0] % group == 0
AssertionError

when i print shape[0] and group:
32 32
32 32
16 1
96 96
96 96
24 320
the group==320 is bigger than the shape[0]==24
how can i fix the problem?

**How to reproduce it?**:

**Comment by Lijiaoa** [comment]
@sungh66 I really suggest you to use nni `v2.10`.

**Comment by J-shang** [comment]
hello @sungh66 , if you still meet this issue after trying nni v2.10, you could give us a model that can reproduce this issue, and we will try to fix it.

**Comment by sungh66** [comment]
I installed v2.10,but i cannot import the module.
ImportError: cannot import name 'OrderedDict' from 'typing' (/home//anaconda3/lib/python3.7/typing.py)

**Comment by Lijiaoa** [comment]
suggest to upgrade python version, such as 3.8...

**Comment by sungh66** [comment]
when i speedup the model ,the CUDA out of memory,tried to allocate 16.00MiB, how to free the space??Must dummy input be the input size of my model?

**Comment by J-shang** [comment]
> when i speedup the model ,the CUDA out of memory,tried to allocate 16.00MiB, how to free the space??Must dummy input be the input size of my model? I reduced the dummy input but had the problem:nni.compression.pytorch.speedup.error_code.UnBalancedGroupError:The number remained filters in each group is different

you could set dummy input batch size by passing `confidence`, for example set batch size to 4, `ModelSpeedup(..., confidence=4)`. speedup performs sparse propagation based on data, the larger the batch size, the more accurate.

For the second issue, you could have a try with dependency aware mode, `L1NormPruner(..., mode='dependency_aware', dummy_input=...)`
https://nni.readthedocs.io/en/stable/reference/compression/pruner.html#nni.compression.pytorch.pruning.L1NormPruner

**Comment by sungh66** [comment]
For the second issue, it still reported the error, i had tried L1Norm,L2Norm,FPGMpruner
        ```
dummy_input = torch.randn([4, 3, 223, 223]).to(self.device)
        
        pruner = L1NormPruner(self.model, config_list, mode='dependency_aware',dummy_input=dummy_input)

        _, masks = pruner.compress()
        pruner._unwrap_model()
        ModelSpeedup(self.model, dummy_input=dummy_input, masks_file=masks, confidence=4).speedup_model()
```
My model is resnet101+deeplabv3plus,is there any other way to solve the issue?

**Comment by J-shang** [comment]
> For the second issue, it still reported the error, i had tried L1Norm,L2Norm,FPGMpruner
> 
> ```
> dummy_input = torch.randn([4, 3, 223, 223]).to(self.device)
>         
>         pruner = L1NormPruner(self.model, config_list, mode='dependency_aware',dummy_input=dummy_input)
> 
>         _, masks = pruner.compress()
>         pruner._unwrap_model()
>         ModelSpeedup(self.model, dummy_input=dummy_input, masks_file=masks, confidence=4).speedup_model()
> ```
> 
> My model is resnet101+deeplabv3plus,is there any other way to solve the issue?
> 
> I tried another model ,it worked ,but when i continue to finetune ,it had CUDA error:../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [11,0,0], thread: [536,0,0] Assertion `t >= 0 && t < n_classes` failed. return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing) RuntimeError: CUDA error: device-side assert triggered

could you show the entire code or a demo for us to reproduce the issue? It is difficult to locate the problem without code.

**Comment by J-shang** [comment]
Closed due to no reply for a long time, please reopen if have any questions.
