### ISSUE TITLE
peek stdout / stderr of a running trial in the web portal

### ISSUE THREAD

**Issue by mydmdm** [Microsoft/nni#53]

**Comment by QuanluZhang** [comment]
Thanks for pointing this out. Showing trial's stdout/stderr on web portal is an appealing feature. In the current version, web portal shows each trial's log path, you can get the log path by clicking the plus sign in the trial job table, then access that path on your machine (local machine or remote machine). This feature will be supported in future.

**Comment by suhailsinghbains** [comment]
Hi, I am new here.
I would love to work on a MS project. Can I please solve this bug.
Thanks

**Comment by QuanluZhang** [comment]
@suhailsinghbains , it would be great, thanks. Before implementing, could you give a proposal about how to support this feature, the design choice?

**Comment by suhailsinghbains** [comment]
How do I re-create this bug in my local machine.

**Comment by QuanluZhang** [comment]
@suhailsinghbains , this is not a bug but a feature. In the current version, webui only shows trial log's uri, e.g., directory path. Sometimes, users want directly get log file's content from webui instead of only uri.

**Comment by SparkSnail** [comment]
In latest version of nni, we have support show log content in web portal.
