### ISSUE TITLE
Prune Problem

### ISSUE THREAD

**Issue by shu0o0yX** [microsoft/nni#5302]
**Describe the issue**:
The code is normal before adding prune code(L2filterPruner), but there is an error after adding.
My project code is from: https://github.com/minar09/cp-vton-plus.
It's error:
![mmexport1672317665038](https://user-images.githubusercontent.com/96320419/209952565-426dc2df-d41c-43f8-b04c-6348098180a4.jpg)
error part:
![mmexport1672317667485](https://user-images.githubusercontent.com/96320419/209952662-9677367a-bd59-4b23-b2c3-c01e3979f6a4.jpg)
my code:
![mmexport1672317670054](https://user-images.githubusercontent.com/96320419/209952692-84c4258c-2997-4910-a2f9-21b81cd62e10.jpg)

**Environment**:
- NNI version:2.10
- Training service (local|remote|pai|aml|etc): local
- Client OS:
- Server OS (for remote mode only):
- Python version:3.10
- PyTorch/TensorFlow version:1.12.1
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by J-shang** [comment]
@ShuYangXie I think this is because the `dummy_input` is wrong, GMM has two inputs in forward, https://github.com/minar09/cp-vton-plus/blob/ff222a79ee3f1f02f41b45c49c16a3b12c5d312d/test.py#L100

please have a try with tuple input `dummy_input = (torch.randn([3, 1, 28, 28]), torch.randn(...))`

**Comment by ShuYangXie** [comment]
> @ShuYangXie I think this is because the `dummy_input` is wrong, GMM has two inputs in forward, https://github.com/minar09/cp-vton-plus/blob/ff222a79ee3f1f02f41b45c49c16a3b12c5d312d/test.py#L100
> 
> please have a try with tuple input `dummy_input = (torch.randn([3, 1, 28, 28]), torch.randn(...))`

Thanks for your reply!

**Comment by Lijiaoa** [comment]
@shu0o0yX Could you help close this issue? It looks like the problem has been solved.
