### ISSUE TITLE
Some questions about the default install environment.

### ISSUE THREAD

**Issue by leelaylay** [Microsoft/nni#531]
1. I think [these lines](https://github.com/Microsoft/nni/blob/master/Makefile#L61-L63) are not appropriate. When develop or modify the tuner in the `nni/src/sdk/pynni` and `tools` directory, the default command `source install.sh` does not meet this demand. I suggest that it should mention `make dev-install` in the `README.md` though it doesn't work sometimes.
2. When I install the nni environment, I find that bash is the default shell while I use zsh as my productive tool. So I often get confused by the install output.
3. Another question is that  I find there are a lot of the same line in the file `~/.bash_completion` when I install the nni for many times.

**Comment by QuanluZhang** [comment]
@Crysple  please double check whether the installation still needs `source ~/.bashrc`.

**Comment by leelaylay** [comment]
When I install nni in my environment and reload my bash, I often meet with the problem below.
 
```shell
: command not found
: command not found
: command not found
: command not found
: command not found
bash: /home/XXX/.bash_completion.d/nnictl: line 31: syntax error near unexpected token `$'\r''
'ash: /home/XXX/.bash_completion.d/nnictl: line 31: `__nnictl_remain_args()
```
