### ISSUE TITLE
How can I get the HPO result from the nni HPO

### ISSUE THREAD

**Issue by robinzixuan** [microsoft/nni#5310]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**
How can I get the HPO result from the nni if we could not use the webpage to see the work process and use the python run the hop directly. 
**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version: 2.10
- nni mode(local|pai|remote):local
- OS:ubuntu20
- python version:3.9
- is conda or virtualenv used?:condo
- is running in docker?:no

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**yep

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://nni.readthedocs.io/en/stable/reference/nnictl.html#nnictl-log-stdout) :

**Comment by liuzhe-lz** [comment]
`nnictl experiment export` command can be used to get metrics in csv or json format.
https://nni.readthedocs.io/en/stable/reference/nnictl.html#nnictl-experiment-export

**Comment by Lijiaoa** [comment]
@robinzixuan Could you help closing this issue? It looks like the problem has been resolved.
