### ISSUE TITLE
Necessity of ModelSpeedup?

### ISSUE THREAD

**Issue by MT010104** [microsoft/nni#5312]
If all I want is the result of inputs on the quantized model, but not the reduction of the model volume and the speedup, can I skip the acceleration step?

**Comment by QuanluZhang** [comment]
If you only want the output of the given input on the quantized model and do not want to reduce inference latency and model size, then ModelSpeedup is not needed. You can directly run the inference of the quantized model by quantizers (e.g., QAT, LSQ). That is, running the model inference after `<your_quantizer>.compress()`, where the model is wrapped with quant/dequant.

**Comment by MT010104** [comment]
OK! Thanks for the quick reply!

**Comment by JornyWan** [comment]
If i wanna deploy the LSQ to a pretrained model (like wav2vec2 model, which is a self-supervised learning model) and fine-tune the model in low-precision quantization(e.g., 2bit, 8bit) with a 10h dataset, what should I do after I load this pretrained model?

**Comment by QuanluZhang** [comment]
> 

you can refer to this tutorial https://nni.readthedocs.io/en/stable/tutorials/quantization_quick_start_mnist.html

**Comment by QuanluZhang** [comment]
close this issue, feel free to reopen if there are related questions.
