### ISSUE TITLE
How to deploy the LSQ quantization on a pre-trained model?

### ISSUE THREAD

**Issue by JornyWan** [microsoft/nni#5314]
If i wanna deploy the LSQ to a pretrained model (like wav2vec2 model, which is a self-supervised learning model) and fine-tune the model in low-precision quantization(e.g., 2bit, 8bit) with a 10h dataset, what should I do after I load this pretrained model?

**Comment by JornyWan** [comment]
because i know that you tried to deploy LSQ to the pretrained model (like Yolox-s) but i did not find the open source code here, while i just found that you build a mnist model with LSQ quantization method, so I really want to know how to deploy it to a pretrained model, thank you guys so much!

**Comment by Bonytu** [comment]
hi，@JornyWan, you can refer to the tutorial: https://nni.readthedocs.io/en/stable/reference/compression/quantizer.html#lsq-quantizer .
Firstly, you can load a pre-trained model,  then you should define a config_list.  The rest of procedures are consistent with https://nni.readthedocs.io/en/stable/reference/compression/quantizer.html#lsq-quantizer

**Comment by JornyWan** [comment]
Thanks for your fast response so much! So do i need to finetune the model with my dataset after the following code in the given website? 
>>> quantizer.compress()
>>> # Training Process...
>>> # so do I need to add my fine-tune step here?

**Comment by Bonytu** [comment]
yeah, if you want your model have a better performance on a specific task, you can finetune it after model.compress().

**Comment by JornyWan** [comment]
Thanks a lot!

**Comment by Lijiaoa** [comment]
@JornyWan Could you help closing this issue? It looks like the problem had been resolved.
