### ISSUE TITLE
How to use DDP in multi-trial NAS?

### ISSUE THREAD

**Issue by heibaidaolx123** [microsoft/nni#5318]
Hi, is there a easy way to use DDP in multi-trial NAS?
I tried multi-trial NAS based on this example: https://github.com/microsoft/nni/blob/master/examples/nas/multi-trial/mnist/search.py. Is it possible to wrap it with DDP?

**Comment by matluster** [comment]
Do you want to make each trial a DDP trial, or do you want to make the whole experiment parallel (might be pointless?)?

To make each trial DDP, you can increase GPU number for each trial and write DDP logics in the evaluator function.

**Comment by Lijiaoa** [comment]
@heibaidaolx123 hi, Li xiang. If you don't have other problem, please help close this issue. Thanks!

**Comment by kingxp** [comment]
please,give a example of ddp,based on example https://github.com/microsoft/nni/blob/master/examples/nas/multi-trial/mnist/search.py.
