### ISSUE TITLE
TypeError: forward() missing 1 required positional argument for ModelSpeedup

### ISSUE THREAD

**Issue by ankitknitj** [microsoft/nni#5321]
**Describe the issue**:

TypeError: forward() missing 1 required positional argument: 'input' while doing ModelSpeedup for VGG19 (basically for every architecture out there)

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): remote
- Server OS (for remote mode only): centOS
- Python version: 3.9
- PyTorch/TensorFlow version: 1.13

**Log message**:
 
Completed pruner.compress()
[2023-01-20 11:24:16] WARNING: Nothing will happen when calling this function.            This pruner is an iterative pruner and does not directly wrap the model.
WARNING:nni.algorithms.compression.v2.pytorch.pruning.iterative_pruner:Nothing will happen when calling this function.            This pruner is an iterative pruner and does not directly wrap the model.
[2023-01-20 11:24:17] start to speedup the model
INFO:nni.compression.pytorch.speedup.compressor:start to speedup the model
WARNING:FixMaskConflict:both dim0 and dim1 masks found.
[2023-01-20 11:24:17] infer module masks...
INFO:nni.compression.pytorch.speedup.compressor:infer module masks...
[2023-01-20 11:24:17] Update mask for .prim::TupleUnpack.55
INFO:nni.compression.pytorch.speedup.compressor:Update mask for .prim::TupleUnpack.55
[2023-01-20 11:24:17] Update mask for module.features.0
INFO:nni.compression.pytorch.speedup.compressor:Update mask for module.features.0
Traceback (most recent call last):
  File "/scratch/work/khatria1/pr_1/DeeperCompression/extract_metadata.py", line 344, in <module>
    main_prepare_metadata(dataset_list, model_dict, combo,
  File "/scratch/work/khatria1/pr_1/DeeperCompression/extract_metadata.py", line 246, in main_prepare_metadata
    model_copy, complexity_dict = prune_tune_quant_tune('level', model_name, model_copy, sparsity, quant_prec, tune_set, tune_epochs,
  File "/scratch/work/khatria1/pr_1/DeeperCompression/compression_methods/compress.py", line 157, in prune_tune_quant_tune
    pruned_model, pruned_inf_time, pruner_obj = gradual_prune_model(pruning_method, model, model_name, target_sparsity, dataset,
  File "/scratch/work/khatria1/pr_1/DeeperCompression/compression_methods/compress.py", line 59, in gradual_prune_model
    pruned_model, pruner_obj = pruner.process()
  File "/scratch/work/khatria1/pr_1/DeeperCompression/compression_methods/nni_compression.py", line 135, in process
    ModelSpeedup(model, self.dummy_input, masks).speedup_model()
  File "/home/khatria1/.local/lib/python3.9/site-packages/nni/compression/pytorch/speedup/compressor.py", line 546, in speedup_model
    self.infer_modules_masks()
  File "/home/khatria1/.local/lib/python3.9/site-packages/nni/compression/pytorch/speedup/compressor.py", line 383, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/home/khatria1/.local/lib/python3.9/site-packages/nni/compression/pytorch/speedup/compressor.py", line 244, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/home/khatria1/.local/lib/python3.9/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/share/apps/anaconda-ci/fgci-centos7-anaconda/software/anaconda/2022-04/18a3eb7e/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'

**How to reproduce it?**:
The AGP pruner code we're using:

def process(self):
        # Define Evaluator
        optimizer = nni.trace(torch.optim.Adam)(self.model.parameters(), lr=5e-5)
        criterion = torch.nn.CrossEntropyLoss()
        lr_scheduler = nni.trace(StepLR)(optimizer, step_size=5, gamma=0.1)

        # TorchEvaluator initialization
        evaluator = TorchEvaluator(training_func=self.train_func, optimizers=optimizer, criterion=criterion,
                                   lr_schedulers=lr_scheduler, dummy_input=self.dummy_input, evaluating_func=self.eval_func)

        # Define AGPPruner
        config_list = [{'op_types': ['Conv2d', 'Linear'], 'sparsity': self.sparsity}]
        if self.pruning_method == 'level':
            pruner = AGPPruner(self.model, config_list, pruning_algorithm='level', total_iteration=self.iters,
                               log_dir='meta_logs/compressed/'+self.model_name+'_'+str(self.sparsity), 
                               evaluator=evaluator, speedup=False)
        elif self.pruning_method == 'taylorfo':
            # params = {'criterion': criterion,
            #           'trainer': self.train_func(self.model, optimizer, criterion, lr_scheduler, max_epochs=self.iters),
            #           'training_batches': 20,
            #           'traced_optimizer': optimizer}
            params = {'evaluator': evaluator, 'training_steps': 5, 'mode': 'normal', 'dummy_input': self.dummy_input}
            pruner = AGPPruner(self.model, config_list, pruning_algorithm='taylorfo', total_iteration=self.iters,
                               log_dir='meta_logs/compressed/'+self.model_name+'_'+str(self.sparsity), 
                               evaluator=evaluator, speedup=False,
                               pruning_params=params)
        # Prune and evaluate the model
        pruner.compress()
        print("Completed pruner.compress()")
        _, model, masks, _, _ = pruner.get_best_result()
        # show the masks sparsity
        # for name, mask in masks.items():
        #     print(name, ' sparsity : ', '{:.2}'.format(mask['weight'].sum() / mask['weight'].numel()))
        # print("Pruned model accuracy on tuning dataset: ", self.eval_func(model))

        # Perform speedup
        pruner._unwrap_model()
        ModelSpeedup(model, self.dummy_input, masks).speedup_model()
        return model, pruner

**Comment by J-shang** [comment]
hello @ankitknitj , could you have a try with the following code, if it worked, please replace the torchvision vgg19 with your own vgg19.

```
import torch
from nni.compression.pytorch.pruning import L1NormPruner
from nni.compression.pytorch.speedup import ModelSpeedup

from torchvision.models import vgg19

model = vgg19()
config_list = [{'op_types': ['Conv2d', 'Linear'], 'sparsity': 0.5}]

pruner = L1NormPruner(model, config_list)
_, masks = pruner.compress()
pruner._unwrap_model()

ModelSpeedup(model, torch.rand(8, 3, 128, 128), masks).speedup_model()

```

**Comment by Lijiaoa** [comment]
@ankitknitj Have you tried Ning's solution yet?

**Comment by ankitknitj** [comment]
@Lijiaoa @J-shang Actually, just passing the dummy input in the form of tuple , fixed the issue. 
Like this: 
ModelSpeedup(model, (torch.rand(8, 3, 128, 128)), masks).speedup_model()

**Comment by J-shang** [comment]
Thanks @ankitknitj , I will close this issue, feel free to contact us if you encounter any other issue.
