### ISSUE TITLE
ValueError: RetiariiExeConfig: type of experiment_name ('mnist_search') is not typing.Optional[str]

### ISSUE THREAD

**Issue by whubaichuan** [microsoft/nni#5324]
**Describe the issue**:

I run the tutorial NAS on my M1 laptop. I build the NNI library as this [instruction](https://nni.readthedocs.io/zh/stable/notes/build_from_source.html). But an error happen: 

```
ValueError: RetiariiExeConfig: type of experiment_name ('mnist_search') is not typing.Optional[str]
[2023-01-26 13:27:25] Stopping experiment, please wait...
[2023-01-26 13:27:25] Experiment stopped
```

**Environment**:
- NNI version: 999.devo
- Training service (local|remote|pai|aml|etc): local
- Client OS: M1 MacOS
- Server OS (for remote mode only):
- Python version: 3.10.5
- PyTorch/TensorFlow version: 1.12.0
- Is conda/virtualenv/venv used?: miniforge3 (conda in Mac)
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!): 
 - Search space: 

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by matluster** [comment]
Could you post the full traceback (if any) and see where the error raises?

My wild guess though, is that it might be an issue with [typeguard](https://github.com/agronholm/typeguard).

**Comment by whubaichuan** [comment]
Hi, the full traceback is here:

```
Traceback (most recent call last):
  File "~/nas.py", line 133, in <module>
    exp.run(exp_config, 8081)
  File "~/nni/nni/nas/experiment/pytorch.py", line 283, in run
    canoni_conf = self._start_impl(port, debug, RunMode.Background, ws_url, ['retiarii'])
  File "~/nni/nni/experiment/experiment.py", line 94, in _start_impl
    config = self.config.canonical_copy()
  File "~/nni/nni/experiment/config/base.py", line 167, in canonical_copy
    canon._validate_canonical()
  File "~/nni/nni/experiment/config/experiment_config.py", line 155, in _validate_canonical
    super()._validate_canonical()
  File "~/nni/nni/experiment/config/base.py", line 237, in _validate_canonical
    utils.validate_type(self)
  File "~/nni/nni/experiment/config/utils/internal.py", line 106, in validate_type
    raise ValueError(f'{class_name}: type of {field.name} ({repr(value)}) is not {field.type}')
ValueError: RetiariiExeConfig: type of experiment_name ('mnist_search') is not typing.Optional[str]
[2023-01-27 11:40:15] Stopping experiment, please wait...
[2023-01-27 11:40:15] Experiment stopped
```

**Comment by matluster** [comment]
Please downgrade to typeguard 2.13, as there is a [breaking change](https://typeguard.readthedocs.io/en/latest/versionhistory.html) in typeguard 3.0 API.

**Comment by whubaichuan** [comment]
hi, @matluster , it works with downgraded typeguard when I do not use GPU in my M1 Macbook. I guess currently this code does not support GPU use in M1 Macbook.

**Comment by liuzhe-lz** [comment]
The GPU features are designed for systems with multiple NVIDIA GPUs.
For other setup please don't set ``trial_gpu_number`.

**Comment by Lijiaoa** [comment]
hi @whubaichuan Looks like this issue had been resolved. Could you help close this issue? Thanks!
