### ISSUE TITLE
nni webportal doesn't show

### ISSUE THREAD

**Issue by yiqiaoc11** [microsoft/nni#5342]
**Describe the issue**:
webportal doesn't appear after executing nnictl create --config config_detailed.yml

**Environment**: Google Cloud VM 
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc):
- Client OS: Ubuntu 20
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?: Yes
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by liuzhe-lz** [comment]
Please check whether your firewall blocks the port.
You can test it with `python -m http.server 8080`. The command will create a FTP-like web server on port 8080. If it cannot be accessed, than the port is blocked.

**Comment by Lijiaoa** [comment]
hi @yiqiaoc11 Do you still have this issue? If this issue had been resolved, please close it. Thanks!

**Comment by yiqiaoc11** [comment]
Hi @liuzhe-lz, I'm able to access http://35.247.79.178:8080/ in ftp-like webpage after executed python -m http.server 8080
Directory listing for /
[config.yml](http://35.247.79.178:8080/config.yml)
[config_assessor.yml](http://35.247.79.178:8080/config_assessor.yml)
[config_detailed.yml](http://35.247.79.178:8080/config_detailed.yml)
[config_hybrid.yml](http://35.247.79.178:8080/config_hybrid.yml)

But I'm still not able to access http://127.0.0.1:8080 http://10.138.0.5:8080 after executed "nnictl create --config config_detailed.yml"
[2023-02-16 03:22:25] Creating experiment, Experiment ID: bq2i5sal
[2023-02-16 03:22:25] Starting web server...
[2023-02-16 03:22:26] Setting up...
[2023-02-16 03:22:26] Web portal URLs: http://127.0.0.1:8080 http://10.138.0.5:8080
[2023-02-16 03:22:26] To stop experiment run "nnictl stop bq2i5sal" or "nnictl stop --all"
[2023-02-16 03:22:26] Reference: https://nni.readthedocs.io/en/stable/reference/nnictl.html

Not sure what happend.

**Comment by liuzhe-lz** [comment]
Have you tried http://35.247.79.178:8080/ for NNI?
The IP addresses in nnictl output are inference and not always correct.

**Comment by yiqiaoc11** [comment]
Thank you, [liuzhe-lz](https://github.com/liuzhe-lz). It worked.
