### ISSUE TITLE
nni installation issue

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/nni#535]
nni installation from source does not support installation from different users on the same machine, because they download node and yarn to the same path (i.e., /tmp/)

**Comment by egg-west** [comment]
I guess it can be solved by editing Makefile?

**Comment by Crysple** [comment]
> I guess it can be solved by editing Makefile? More specifically, in line 41-42.
> And is it the same as issue #468 ?

It's the same problem in different locations. I am planning to use username to create a folder in /tmp for every user to install or use NNI.

**Comment by egg-west** [comment]
> > I guess it can be solved by editing Makefile? More specifically, in line 41-42.
> > And is it the same as issue #468 ?
> 
> It's the same problem in different locations. I am planning to use username to create a folder in /tmp for every user to install or use NNI.

Sounds good.
