### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Nafees-060** [microsoft/nni#5350]

**Comment by liuzhe-lz** [comment]
If you still have problem, feel free to reopen the issue.

**Comment by Nafees-060** [comment]
@liuzhe-lz thanks I want to reopen this issue. But I could not see any button for reopening this issue.

**Comment by Lijiaoa** [comment]
like this:
![无标题](https://user-images.githubusercontent.com/61399850/218963456-c6a9da1d-3564-43b1-b1e1-212477d4c1aa.png)

**Comment by Nafees-060** [comment]
@Lijiaoa thanks but I can get only the "comment" button not the "Reopen" button.

**Comment by Lijiaoa** [comment]
so you could open a new issue

**Comment by Nafees-060** [comment]
@Lijiaoa just created new issue at [https://github.com/microsoft/nni/issues/5354]
