### ISSUE TITLE
define HPO process in one file

### ISSUE THREAD

**Issue by heibaidaolx123** [microsoft/nni#5423]
Hi,  in the example [Port PyTorch Quickstart to NNI](https://nni.readthedocs.io/en/stable/tutorials/hpo_quickstart_pytorch/model.html), the search space and experiment are defined in one file, and the trial is defined in another file.
Is there a way to put them together in one single py file, just like NAS (defining a fit function and using FunctionalEvaluator and RetiariiExperiment)?
Thanks a lot.

**Comment by liuzhe-lz** [comment]
Currently this is not supported without hack.

It can be hacked like this:
```python
def trial():
    ...

def main():
    ...
    exp.config.trial_command = 'python this.py trial'

if sys.argv[1] == 'trial':
    trial()
else:
    main()
```

This feature is on our roadmap, but we currently don't have enough bandwidth to implement it.

**Comment by heibaidaolx123** [comment]
> Currently this is not supported without hack.
> 
> It can be hacked like this:
> 
> ```python
> def trial():
>     ...
> 
> def main():
>     ...
>     exp.config.trial_command = 'python this.py trial'
> 
> if sys.argv[1] == 'trial':
>     trial()
> else:
>     main()
> ```
> 
> This feature is on our roadmap, but we currently don't have enough bandwidth to implement it.

@liuzhe-lz Yes, I've used this method. Thanks.
