### ISSUE TITLE
Export best-performing paramter after CTRL-C during HPO

### ISSUE THREAD

**Issue by heibaidaolx123** [microsoft/nni#5425]
Hi, in the [pytorch HPO example](https://nni.readthedocs.io/en/stable/tutorials/hpo_quickstart_pytorch/main.html#), I tried to export best-performing parameter after HPO. So I add `print(experiment.export_data())` before `experiment.stop()`, when the experiments is normally finished, I can get the best performing param from output of export_data(). But if I interrupt the process with CTRL-C, `experiment.export_data()` will rais an error:

> RuntimeError: Experiment is not running 

I know, for NAS, there's a `export_top_models` method for `RetiariiExperiment`, which will export top models even after `RetiariiExperiment.stop` is called or after a CTRL-C.
So, how can I export best performing param after CTRL-C, in HPO?

**Comment by liuzhe-lz** [comment]
For now you can try to ["view"](https://nni.readthedocs.io/en/stable/reference/experiment.html#nni.experiment.Experiment.view) the experiment to export data.
We will consider support exporting without running in future release.
