### ISSUE TITLE
count_flops_params in nas,return 0

### ISSUE THREAD

**Issue by kingxp** [microsoft/nni#5433]
**Describe the issue**:
i use count_flops_params or thop.profile in nas
import nni.retiarii.nn.pytorch as nn
the flops/parameters is return 0

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by Lijiaoa** [comment]
Please refine your issue by using `compression` template, thanks.

**Comment by matluster** [comment]
What‘s your network?

**Comment by kingxp** [comment]
i find the problem and solve it

In counter.py，count_flops_params only count the flops of nn.Conv1d etc.
In this file，nn is torch.nn，only count the flops of torch.nn
but in nas task， nn is nni.retiarii.nn.pytorch，so replace the ‘import torch.nn as nn‘ by ‘nn is nni.retiarii.nn.pytorch’
count_flops_params  can work

**Comment by kingxp** [comment]
Similarly，the thop.profile in nas count_flops task also return 0
