### ISSUE TITLE
Process to automatically find sparsity per layer

### ISSUE THREAD

**Issue by TheSeriousProgrammer** [microsoft/nni#5434]
Hi I am new to NNI framework

I have read in a few papers that , following a single sparsity ratio for pruning across all layers is less efficient than having per layer sparsity ratio. The Once-For-All paper from MIT suggests that the per layer pruning ratio can be identified through a greedy selection process

Do we have something like that here? I was not able to find anything related to the same in documentation. Does the current framework indirectly support that through some schedulers?

Thanks for creating this super awesome framework though !!!!

**Comment by J-shang** [comment]
Hello @TheSeriousProgrammer , yes, we have some pruners like that, and smarter then greedy, please ref:
https://nni.readthedocs.io/en/stable/reference/compression/pruner.html#movement-pruner
https://nni.readthedocs.io/en/stable/reference/compression/pruner.html#auto-compress-pruner
https://nni.readthedocs.io/en/stable/reference/compression/pruner.html#lottery-ticket-pruner

and if you want to manual set sparse ratio for each layer with greedy, you could set them by combing `nni hpo` and `nni compression`.

**Comment by TheSeriousProgrammer** [comment]
Yes that works !!
