### ISSUE TITLE
Meet an error when we try to prune the yolov5s.pt

### ISSUE THREAD

**Issue by Ku-Buqi** [microsoft/nni#5471]
**Describe the bug**:
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.onnx_dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
Comparison exception: 	expected tensor shape torch.Size([1, 3, 1, 1, 2]) doesn't match with actual tensor shape torch.Size([])!

**Environment**:
- NNI version:2.10
- Training service (local|remote|pai|aml|etc):local
- Python version:3.8.13
- PyTorch version:1.9.0
- Cpu or cuda version:10.2

**Reproduce the problem**
- Code|Example:

import torch
from nni.compression.pytorch.pruning import L2NormPruner
from nni.compression.pytorch import ModelSpeedup

from models.experimental import attempt_load

##Load
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = attempt_load('yolov5s.pt', map_location=device) 
##'attempt_load()' function is from yolov5-master.models.experimental.py.  And it has been attached below.

##Create instance
config_list = [{
    'sparsity': 0.2,
    'op_types': ['Conv2d'], 'op_names': [
        'model.0.conv',
        'model.1.conv',
        ]
}]
pruner = L2NormPruner(model, config_list, mode='dependency_aware', dummy_input=torch.rand(1, 3, 32, 32).to(device))

##Prune
_, masks = pruner.compress()
pruner.export_model(model_path='../Myweights/deepsort_yolov5m.pt', mask_path='../Myweights/deepsort_mask.pt')
pruner.show_pruned_weights()
pruner._unwrap_model()

##Speedup
PR_model = ModelSpeedup(model, torch.rand(1, 3, 32, 32).to(device), masks_file="../Myweights/deepsort_mask.pt")
PR_model.speedup_model()
print("The number of model parameters after acceleration：", sum(p.numel() for p in model.parameters()))

- How to reproduce:
[models.zip](https://github.com/microsoft/nni/files/11047995/models.zip)

Thanks for any help！

**Comment by super-dainiu** [comment]
hi, would u pls upgrade nni version to 3.0 and try the following code instead?
```python
import torch

from nni.common.concrete_trace_utils import concrete_trace
from nni.contrib.compression.pruning import L1NormPruner
from nni.contrib.compression.utils import auto_set_denpendency_group_ids
from nni.compression.pytorch.speedup.v2 import ModelSpeedup

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', device='cpu')

model(torch.rand([1, 3, 640, 640]))

config_list = [{
    'sparsity': 0.2,
    'op_types': ['Conv2d'],
    'exclude_op_names_re': ['model.model.model.24.*'],  # this layer is detector head
}]

config_list = auto_set_denpendency_group_ids(model, config_list, torch.rand([1, 3, 640, 640]))

pruner = L1NormPruner(model, config_list)
masked_model, masks = pruner.compress()
pruner.unwrap_model()

graph_module = concrete_trace(model, (torch.rand([1, 3, 640, 640]), None, None, None))
ModelSpeedup(model, torch.rand([1, 3, 640, 640]), masks, graph_module=graph_module).speedup_model()

model(torch.rand([1, 3, 640, 640]))
```

we used torch.fx to refactor ``ModelSpeedup``. hope that can solve ur probs.

**Comment by Ku-Buqi** [comment]
> hi, would u pls upgrade nni version to 3.0 and try the following code instead?
> 
> ```python
> import torch
> 
> from nni.common.concrete_trace_utils import concrete_trace
> from nni.contrib.compression.pruning import L1NormPruner
> from nni.contrib.compression.utils import auto_set_denpendency_group_ids
> from nni.compression.pytorch.speedup.v2 import ModelSpeedup
> 
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s', device='cpu')
> 
> model(torch.rand([1, 3, 640, 640]))
> 
> config_list = [{
>     'sparsity': 0.2,
>     'op_types': ['Conv2d'],
>     'exclude_op_names_re': ['model.model.model.24.*'],  # this layer is detector head
> }]
> 
> config_list = auto_set_denpendency_group_ids(model, config_list, torch.rand([1, 3, 640, 640]))
> 
> pruner = L1NormPruner(model, config_list)
> masked_model, masks = pruner.compress()
> pruner.unwrap_model()
> 
> graph_module = concrete_trace(model, (torch.rand([1, 3, 640, 640]), None, None, None))
> ModelSpeedup(model, torch.rand([1, 3, 640, 640]), masks, graph_module=graph_module).speedup_model()
> 
> model(torch.rand([1, 3, 640, 640]))
> ```
> 
> we used torch.fx to refactor `ModelSpeedup`. hope that can solve ur probs.

Thanks again, but a new problem arose as following, ''ModuleNotFoundError: No module named 'torch.fx._compatibility'''. 
It might help a lot if you could tell which version of ptroch you are using.

**Comment by super-dainiu** [comment]
mine is torch 1.13.

**Comment by Lijiaoa** [comment]
Could you close this issue if you don't have any questions? @Ku-Buqi
