### ISSUE TITLE
ModuleNotFoundError: No module named 'nni.nas.execution.common'

### ISSUE THREAD

**Issue by singagan** [microsoft/nni#5473]
Hi, I just installed nni using `python setup.py develop` and I get the below error on importing `nni.retiarri.nn.pytorch`
Please could you help?

```
Traceback (most recent call last):
  File "model.py", line 6, in <module>
    import nni.retiarii.nn.pytorch as nn
  File "/nni/nni/retiarii/__init__.py", line 4, in <module>
    from .operation import Operation
  File "/nni/nni/retiarii/operation.py", line 6, in <module>
    from nni.nas.execution.common.graph_op import *
ModuleNotFoundError: No module named 'nni.nas.execution.common'

```
**Environment**:
- NNI version:nni==999.dev0

**Comment by matluster** [comment]
I think `nni.retiarri.nn.pytorch` is broken right now. Please use `nni.nas` instead.

We will fix the backward compatibility hopefully in coming weeks.

**Comment by singagan** [comment]
I see. Thanks for the quick reply.
I tried using it but I get another error. Is there an example that I could follow for `nni.nas` as all the examples are for `nni.retiarri`?

```
import nni.nas.nn.pytorch as mutables

self.down1 = mutables.LayerChoice(OrderedDict([
            ("conv3x3", (conv_block(64, 128))),
            ("conv5x5", (conv_block(32, 128)))
        ]))
```

[```
2023-03-24 08:25:08] [33mWARNING: Label is not provided, and label scope is also missing. Global numbering will be used. Note that we always recommend specifying `label=...` manually.[0m
WARNING: Label is not provided, and label scope is also missing. Global numbering will be used. Note that we always recommend specifying `label=...` manually.
[2023-03-24 08:25:08] [33mWARNING: No context found when `add_mutable()`. You are probably adding a MutableModule outside the `__init__` of a ModelSpace. This can possibly make the MutableModule untrackable and inconsistent: global/1[0m
WARNING: No context found when `add_mutable()`. You are probably adding a MutableModule outside the `__init__` of a ModelSpace. This can possibly make the MutableModule untrackable and inconsistent: global/1
Traceback (most recent call last):
  File "train.py", line 218, in <module>
    model = UNet_nas_quant(n_channels=3, n_classes=args.classes, bilinear=args.bilinear)
  File "model.py", line 20, in __init__
    self.down1 = mutables.LayerChoice(OrderedDict([
  File "/nni/nni/nas/nn/pytorch/choice.py", line 114, in __init__
    self._dry_run_choice = ensure_frozen(self.choice)
  File "/nni/nni/mutable/frozen.py", line 82, in ensure_frozen
    raise RuntimeError(
RuntimeError: No frozen context is found for Categorical(['conv3x3', 'conv5x5'], label='global/1'). Assuming no context. If you are using NAS, you are probably using `ensure_frozen` in forward, or outside the init of ModelSpace. Please avoid doing this as they will lead to erroneous results.

```

**Comment by ultmaster** [comment]
Example: https://github.com/ultmaster/nni/tree/nas-nn-refactor/examples/nas/hub

**Comment by singagan** [comment]
Thanks. I tried following this to setup my search space but I still get the frozen context error:
`RuntimeError: No frozen context is found for Categorical(['conv3x3', 'conv5x5'], label='global/1'). Assuming no context. If you are using NAS, you are probably using ensure_frozen in forward, or outside the init of ModelSpace. Please avoid doing this as they will lead to erroneous results.`

I was checking ProxylessNas search space, there is a `load_searched_model` function where we call `cls.frozen_factory()`
https://github.com/ultmaster/nni/blob/09617be1ddd6b2724057ded35b6f4658b763abc8/nni/nas/hub/pytorch/proxylessnas.py#L531

Is the issue related to this? 
I worked with retiarri version before, there after setting up the search space using `LayerChoice`, everything used to work. Are things different now?

**Comment by singagan** [comment]
I resolved this issue. Thanks.
