### ISSUE TITLE
how to run unittest ?

### ISSUE THREAD

**Issue by south-ocean** [microsoft/nni#5479]
**Describe the issue**:

**Environment**:
- NNI version: 2.9
- Training service (local|remote|pai|aml|etc): local
- Client OS:
- Server OS (for remote mode only):
- Python version:  3.7
- PyTorch/TensorFlow version:  TF2.9
- Is conda/virtualenv/venv used?:  yes
- Is running in Docker?:  yes

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

I  have builded the nni  whl package  from source code successfully,  and i find the test folder in nni source  code, so how to run  the unnitest  for nni ? can you give me the command or relevant  path. Thanks.

**How to reproduce it?**:

I  have builded the nni  whl package  from source code successfully,  and i find the test folder in nni source  code, so how to run  the unnitest  for nni ? can you give me the command or relevant  path. Thanks.

**Comment by south-ocean** [comment]
can you answer it ? @liuzhe-lz

**Comment by liuzhe-lz** [comment]
You can check the commands used by our pipeline `https://github.com/microsoft/nni/blob/master/pipelines/fast-test.yml`.
The python UT is run by `cd test && python -m pytest ut`.
It may requires extra dependencies defined in [develop.txt](`https://github.com/microsoft/nni/blob/master/dependencies/develop.txt`) and [recommended.txt](https://github.com/microsoft/nni/blob/master/dependencies/recommended.txt)
