### ISSUE TITLE
NAS with differential privacy

### ISSUE THREAD

**Issue by Drxdx** [microsoft/nni#5490]
i want to use dp with NAS, when i use the pre-trained DARTS model , ModuleValidator.fix() function does't work! anyone meet this problem?
DP with NAS and meet a ‘Model contains a trainable layer that Opacus doesn't currently support’ .
Then I use a simple code to view it:

darts_conv = darts_v2_model.stages[0][0].preprocessor.pre0[1]
resnet_conv = resnet18.conv1

print(type(darts_conv),type(resnet_conv))
**result:<class 'torch.nn.modules.conv.Conv2d'> <class 'torch.nn.modules.conv.Conv2d'>**

if type(darts_conv) == type(resnet_conv):
    print("The types of the first layers of darts_v2_model and resnet18 are equal.")
else:
    print("The types of the first layers of darts_v2_model and resnet18 are not equal.")
**result:not equal**

**Comment by matluster** [comment]
Probably one is from `nni.retiarii.nn.pytorch` and the other one is from `torch.nn`.

Might need to change `import `nni.retiarii.nn.pytorch as nn` to `torch.nn` and try again.

**Comment by Lijiaoa** [comment]
Could you close this issue if you don't have any questions? @Drxdx
