### ISSUE TITLE
':=' not supported in python 3.7

### ISSUE THREAD

**Issue by heibaidaolx123** [microsoft/nni#5495]
':=' is used in https://github.com/microsoft/nni/blob/master/nni/compression/pytorch/speedup/jit_translate.py.
According to [installation guide](https://nni.readthedocs.io/en/stable/installation.html), python 3.7 is supported.

**Comment by censhallwe** [comment]
> ':=' is used in https://github.com/microsoft/nni/blob/master/nni/compression/pytorch/speedup/jit_translate.py. According to [installation guide](https://nni.readthedocs.io/en/stable/installation.html), python 3.7 is supported.

I searched from Internet that ':=' is supported in python 3.8. I follow the installation guide to install and also meet this question.

**Comment by J-shang** [comment]
you are right, `:=` is new in python 3.8. NNI plans to deprecate python 3.7 in next release version, so `:=` is used in the master branch.
if you want to build from master branch and using python 3.7, please have a try on this pr https://github.com/microsoft/nni/pull/5500

**Comment by censhallwe** [comment]
> you are right, `:=` is new in python 3.8. NNI plans to deprecate python 3.7 in next release version, so `:=` is used in the master branch. if you want to build from master branch and using python 3.7, please have a try on this pr #5500

Thank you for your reply!
