### ISSUE TITLE
Is there any way to see the ranking of hyperparameters without the webui?

### ISSUE THREAD

**Issue by Jia-py** [microsoft/nni#5549]
**Describe the issue**:
Can we see the ranking of hyperparameters without the webui? For there are some scenarios without web browsers, such as some remote scenarios.

**Comment by cruiseliu** [comment]
Please try out [`get_job_metrics`](https://nni.readthedocs.io/en/v2.10/reference/experiment.html#nni.experiment.Experiment.get_job_metrics) API.

**Comment by Lijiaoa** [comment]
Could you close this issue? @Jia-py
