### ISSUE TITLE
Recheck the link in the doc after we complete doc refactor

### ISSUE THREAD

**Issue by PurityFan** [Microsoft/nni#556]
In the process of refactoring the document, we will encounter some doc link conflicts. We should check if there is a fake link and fix it after the refactoring document is completed.

**Comment by gilbertacosta** [comment]
nice

**Comment by leelaylay** [comment]
In [Docker README](https://github.com/Microsoft/nni/tree/master/deployment/docker), the nni version is 0.3, so can we fix it?

**Comment by PurityFan** [comment]
> In [Docker README](https://github.com/Microsoft/nni/tree/master/deployment/docker), the nni version is 0.3, so can we fix it?

Of course. You can submit a pr.

**Comment by leelaylay** [comment]
> > In [Docker README](https://github.com/Microsoft/nni/tree/master/deployment/docker), the nni version is 0.3, so can we fix it?
> 
> Of course. You can submit a pr.

Can we just call it version stable?

**Comment by PurityFan** [comment]
> > > In [Docker README](https://github.com/Microsoft/nni/tree/master/deployment/docker), the nni version is 0.3, so can we fix it?
> > 
> > 
> > Of course. You can submit a pr.
> 
> Can we just call it version stable?

I have discussed this with Gems Guo, but he said it is bother to do that.
