### ISSUE TITLE
The trial process is still alive after the nnictl stop command.

### ISSUE THREAD

**Issue by leelaylay** [Microsoft/nni#558]
The trial process is still running after the nnictl stop command, so it takes so much resources of the computer and I have to kill it by force.

PS: My `trainingServicePlatform` is remote.

**Comment by QuanluZhang** [comment]
I suspect that it is because of this line: 
https://github.com/Microsoft/nni/blob/master/src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts#L266
Could @SparkSnail or someone take a look?

**Comment by SparkSnail** [comment]
fixed in https://github.com/Microsoft/nni/pull/564
