### ISSUE TITLE
Trial jobs need to get a unique ID value

### ISSUE THREAD

**Issue by chicm-ms** [Microsoft/nni#56]
For example, it is a common practice to do k fold data split to improve model performance.  In order to do k fold split, each of my trial jobs need to train on a unique split, to do this, my trial jobs need to get a unique ID value.
In short, trial jobs need to get an Id if they need to corporate on something. 
There are two possible solutions to implement this:
1. Use search space, need to add new type, such as sequence, can be implemented in either builtin or customized Tuner.
2. Add an API, such as nni.get_trial_id()

**Comment by yds05** [comment]
We need to provide a new API in SDK, like nni.get_sequence_num(), enable NNI trial identify it's unique auto-incremented sequence ID(start from 0. e.g)

**Comment by chicm-ms** [comment]
Done,
https://github.com/Microsoft/nni/pull/203
