### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by sunjian2015** [microsoft/nni#5601]
**Describe the issue**:
<img width="1116" alt="988a2d62f21801bbc49dafb253a1281c" src="https://github.com/microsoft/nni/assets/24861234/4c0c864c-d6d3-4456-ae7c-9c8f1d6d3e49">
<img width="1115" alt="95fad960da4a0ae0af53bdd5416e5e12" src="https://github.com/microsoft/nni/assets/24861234/34c64ca1-b5a1-4829-9d9f-5dca1ac75d2e">

**Environment**:
- NNI version: 2.10.1
- Training service (local|remote|pai|aml|etc): local
- Client OS: Linux
- Server OS (for remote mode only):
- Python version: 3.7.0
- PyTorch version: 1.12.1
- Is conda/virtualenv/venv used?: virtualenv
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by J-shang** [comment]
hello @sunjian2015 , you could upgrade your python version to 3.8.

**Comment by sunjian2015** [comment]
> hello @sunjian2015 , you could upgrade your python version to 3.8.

Ok, thanks for your reply, i will try it next time. Now i have installed NNI version 2.0 from source code.😂

**Comment by Lijiaoa** [comment]
any updates for it? @sunjian2015

**Comment by sunjian2015** [comment]
> any updates for it? @sunjian2015

no, i use the old version

**Comment by Lijiaoa** [comment]
So could you close it if you don't have any questions?
