### ISSUE TITLE
Serializer behavior in v2.8 and v2.9 or higher

### ISSUE THREAD

**Issue by makonaga** [microsoft/nni#5602]
**Describe the issue**:
I'm trying to perform a model search in retiarii, but the behavior differs depending on the version of NNI.

The settings for nni.trace are as follows:

```
@nni.trace
class MyDataset(torch.utils.data.Dataset):

     def __init__(self, root: str, train: bool = True):
        filename = 'train.csv' if train else 'valid.csv'
        df = pd.read_csv(os.path.join(root, filename))
        self.x = df.iloc[:, 1:].values
        self.y = df.iloc[:, 0].values

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return torch.Tensor(self.x[idx]), self.y[idx]

train_dataset = MyDataset(root='./data', train=True)
test_dataset = MyDataset(root='./data', train=False)

import nni.retiarii.evaluator.pytorch.lightning as pl

trainer = pl.Classification(train_dataloader=pl.DataLoader(train_dataset, batch_size=100),
                            val_dataloaders=pl.DataLoader(test_dataset, batch_size=100),
                            optimizer=torch.optim.SGD,
                            max_epochs=100,
                            accelerator='gpu', devices=1)
```

note) pl.Classification and pl.DataLoader are used as they are since nni.trace is already defined.

When the NNI version is 2.8, it works fine, but when the NNI version is 2.9/2.10, an error occurs.

`PayloadTooLarge: Pickle too large when trying to dump <nni.nas.nn.pytorch.mutator.ParameterChoiceMutator object at 0x7f7379699550>. This might be caused by classes that are not decorated by @nni.trace. Another option is to force bytes pickling and try to raise pickle_size_limit.`

I need advice on how to modify nni.trace to work with NNI version 2.9/2.10.
Because I would like to check the completed trial in nnictl view, but the results in retiarii can be checked from NNI version 2.9,
I want to execute the search with the same version.

**Environment**:
- NNI version: 2.8/2.9/2.10
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu
- Server OS (for remote mode only):
- Python version: 3.8.8
- PyTorch/TensorFlow version:1.9.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

**Comment by ultmaster** [comment]
I might need more info as the object failing to dump is a ParameterChoiceMutator, which is part of your model space.

Could you post more diagnostic information? For example, print out the mutator that fails to dump, along with its `__dict__`.

**Comment by makonaga** [comment]
Hi, @ultmaster  Thank you for reply.

My base model is bellow:
```
@model_wrapper
class Net(nn.Module):

    def __init__(self, input_size):
        super().__init__()

        self.output_dim = 19

        self.fc1 = nn.Linear(input_size, 114)
        self.bn1 = nn.BatchNorm1d(114)
        self.activate_fn1 = nn.ReLU()

        self.fc2 = nn.Linear(114, 94)
        self.bn2 = nn.BatchNorm1d(94)
        self.activate_fn2 = nn.ReLU()

        self.fc3 = nn.Linear(94, 74)

        self.fc4 = nn.Linear(74, 92)
        self.activate_fn4 = nn.ReLU()

        self.fc5 = nn.Linear(92, self.output_dim)

    def forward(self, x):

        y = self.activate_fn1(self.bn1(self.fc1(x)))
        y = self.activate_fn2(self.bn2(self.fc2(y)))
        y = self.fc3(y)
        y = self.activate_fn4(self.fc4(y))
        y = self.fc5(y)
        return y

model_space = Net(len(train_dataset.__getitem__(0)[0]))
```

And, mutation definition is bellow:  *A simple trial level mutation definition.

```
@model_wrapper
class Net(nn.Module):

    def __init__(self, input_size):
        super().__init__()

        self.output_dim = 19

        self.fc1 = nn.Linear(input_size, 114)
        self.bn1 = nn.BatchNorm1d(114)
        self.activate_fn1 = nn.LayerChoice([nn.ReLU(), nn.LeakyReLU()], label='activation_1')

        self.fc2 = nn.Linear(114, 94)
        self.bn2 = nn.BatchNorm1d(94)
        self.activate_fn2 = nn.LayerChoice([nn.ReLU(), nn.LeakyReLU()], label='activation_2')

        self.fc3 = nn.Linear(94, 74)

        self.fc4 = nn.Linear(74, 92)
        self.activate_fn4 = nn.LayerChoice([nn.ReLU(), nn.LeakyReLU()], label='activation_4')

        self.fc5 = nn.LayerChoice([nn.Linear(92, self.output_dim),
                                   nn.LogSoftmax(nn.Linear(92, self.output_dim), dim=1)], label='output')

    def forward(self, x):
        y = self.fc1(x)
        y = self.bn1(y)
        y = self.activate_fn1(y)
        y = self.fc2(y)
        y = self.bn2(y)
        y = self.activate_fn2(y)
        y = self.fc3(y)
        y = self.fc4(y)
        y = self.activate_fn4(y)
        y = self.fc5(y)
        return y

model_space = Net(len(train_dataset.__getitem__(0)[0]))
```
This definition works for v2.8, but  "PayloadTooLarge: Pickle too large when trying to dump" occurs in v2.9/2.10.


I will also share the log with Debug=ON in the WebUI.

[nnimanager.log](https://github.com/microsoft/nni/files/11720594/nnimanager.log)
[dispatcher.log](https://github.com/microsoft/nni/files/11720595/dispatcher.log)

If you need other information, please let us know what information you need.

**Comment by matluster** [comment]
At this place:

https://github.com/microsoft/nni/blob/1037f585678280e9242ed1ad73bca7c00e7a0eab/nni/common/serializer.py#L862

Print `obj` and `obj.__dict__` and tell us what you observe. Thanks.

**Comment by makonaga** [comment]
@matluster 
I share the print log below:
```
[2023-06-14 13:05:45] Creating experiment, Experiment ID: po47bmwi
[2023-06-14 13:05:45] Starting web server...
[2023-06-14 13:05:46] Setting up...
[2023-06-14 13:05:46] Web portal URLs: http://127.0.0.1:8084 http://192.168.0.110:8084 http://172.17.0.1:8084 http://172.19.0.1:8084 http://172.18.0.1:8084
[2023-06-14 13:05:46] Dispatcher started
obj :  <nni.nas.nn.pytorch.mutator.LayerChoiceMutator object at 0x7f321f2d9820>
hasattr(obj, '__class__') :  True
hasattr(obj, '__dict__' :  True
hasattr(obj, '__slots__') :  False
obj, '__class__' :  <class 'nni.nas.nn.pytorch.mutator.LayerChoiceMutator'>
obj, '__dict__' :  {'sampler': None, 'label': 'activation_1', '_cur_model': None, '_cur_choice_idx': None, 'nodes': [Node(id=8, name=_model__activate_fn1, python_name=activate_fn1, label=None, operation=Cell(type="_cell", mutation='layerchoice', label='activation_1', candidates=['layerchoice_activation_1_0', 'layerchoice_activation_1_1']))]}
```
I did the same with nni ver. 2.8, but no print log was output, so I assume it is handled by cloudpickle, not jsontrick.

**Comment by matluster** [comment]
I see a `LayerChoiceMutator` here. This suggests that you are configuring the experiment to use graph execution engine rather than python execution engine. Any specific reasons why you are doing so?

**Comment by makonaga** [comment]
@matluster 
No reason given.
I composed the experiment based on the code in the tutorial.
Although it worked in v2.8, I had no way to check the results of the experiment later and learned that it was supported in v2.9.
Therefore, when I performed the experiment with v2.9, I encountered this problem.

What kind of experiment definition should I use in v2.9? Could you please tell me?

**Comment by matluster** [comment]
Do you mean this tutorial? https://nni.readthedocs.io/en/v2.10/tutorials/hello_nas.html

Could you print `exp_config` before `exp.run`? Set `exp_config.execution_engine = 'py'` if it's not `py`.

**Comment by makonaga** [comment]
@matluster 

Yes, I am referring to "examples/nas/legacy/notebooks/tabular_data_classification_in_AML.ipynb" as well as the tutorial you mentioned.

Here are the print results for exp.config

`RetiariiExeConfig(experiment_name='test', experiment_type='nas', search_space_file=None, search_space='', trial_command='_reserved', trial_code_directory='.', trial_concurrency=2, trial_gpu_number=1, max_experiment_duration='48h', max_trial_number=16, max_trial_duration=None, nni_manager_ip=None, use_annotation=False, debug=False, log_level=None, experiment_working_directory='~/nni-experiments', tuner_gpu_indices=None, tuner=_AlgorithmConfig(name='_none_', class_name=None, code_directory=None, class_args={}), assessor=_AlgorithmConfig(name='_none_', class_name=None, code_directory=None, class_args={}), advisor=_AlgorithmConfig(name='_none_', class_name=None, code_directory=None, class_args={}), training_service=LocalConfig(platform='local', trial_command=<dataclasses._MISSING_TYPE object at 0x7f594fef9460>, trial_code_directory=<dataclasses._MISSING_TYPE object at 0x7f594fef9460>, trial_gpu_number=<dataclasses._MISSING_TYPE object at 0x7f594fef9460>, nni_manager_ip=<dataclasses._MISSING_TYPE object at 0x7f594fef9460>, debug=<dataclasses._MISSING_TYPE object at 0x7f594fef9460>, use_active_gpu=True, max_trial_number_per_gpu=1, gpu_indices=None, reuse_mode=False), shared_storage=None, execution_engine='base', _trial_command_params=None)`

I have it set as "exp_config.execution_engine = 'base'".
How should I set it up in v2.9 or later?

**Comment by matluster** [comment]
`examples/nas/legacy/notebooks/tabular_data_classification_in_AML.ipynb` is a legacy tutorial as suggested in the path.

Change `execution_engine` to `py`.

**Comment by makonaga** [comment]
@matluster 
Thanks for the advice.
I confirmed that changing to 'py' works correctly with Ver.2.9 or Ver.2.10.

I will now close this Issue.

**Comment by makonaga** [comment]
@matluster
Thanks for the advice.
I confirmed that changing to 'py' works correctly with Ver.2.9 or Ver.2.10.

I will now close this Issue.
