### ISSUE TITLE
ChannelMaskConflict loop skips one element dependency sets

### ISSUE THREAD

**Issue by fatih-ilhan** [microsoft/nni#5612]
mask_conflict.ChannelMaskConflict.fix_mask() loop skips one element dependency sets. Should not those elements also be updated? For instance in my trials for BERT, 'bert.encoder.layer.0.attention.self.value' may enter the loop as one-element and its mask would not be fixed properly.

https://github.com/microsoft/nni/blob/928575b4a65ff4b26faf3ef55f178eefbec25364/nni/compression/pytorch/utils/mask_conflict.py#LL229C24-L229C24

**Comment by J-shang** [comment]
Hello @fatih-ilhan , do you mean you want `bert.encoder.layer.0.attention.self.value` and `bert.encoder.layer.0.attention.self.key` in the same dependency set?

**Comment by fatih-ilhan** [comment]
I am not sure about this. But, I was confused when the query, key weights were fixed after fix_mask() whereas the value weights were not fixed because they were skipped in the for loop.

**Comment by fatih-ilhan** [comment]
I understand now, we can close the issue. Thanks!

**Comment by Lijiaoa** [comment]
I am very glad to hear that your issue had been resolved, congratulations! So could you close it? @fatih-ilhan
