### ISSUE TITLE
Hello NAS notebook fails running the experiment

### ISSUE THREAD

**Issue by ekurtgl** [microsoft/nni#5619]
**Describe the issue**:

Hi,

I am trying to get the hello_nas.ipynb notebook run on company's remote machine. Although I get no error in the notebook, my experiments seem to be failed in the WEB UI, hence I cannot export the top models:

<img width="811" alt="image" src="https://github.com/microsoft/nni/assets/66868163/19a8f514-c689-4581-8cb0-6d34a7ad5aed">

I tried multiple times without any changes in the code, but no luck. I looked into the stderr log file under /home/{username}/nni-experiments/{exp_id}/trials/{trial_id}/stderr file, and it looks like this:

<img width="857" alt="image" src="https://github.com/microsoft/nni/assets/66868163/7bbcdd9a-77e6-4d63-94f2-7609882da7f1">

I can import torchvision and use it without any problem. What do you think the problem might be here? Thank you.

**Comment by ultmaster** [comment]
You can import torchvision. Can you use mnist dataset?

**Comment by ekurtgl** [comment]
Ah, I see now. MNIST website doesn't have https header, so it is not recognized as a secure website, hence was being blocked by the company's network. Manually downloading the data should solve the problem. Thank you for your help!
