### ISSUE TITLE
Custom Operations in PointNet++ Implementation

### ISSUE THREAD

**Issue by ekurtgl** [microsoft/nni#5621]
**Describe the issue**:
Hi,

I am trying to implement PointNet++ model with NNI module for NAS, but I am getting the error mentioned in #5610. I was wondering if the custom operations used in pointnet are supported by NNI. You may find the custom ops used in this file:

https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet2_utils.py

I am not sure if the cause of the error is one of these functions, but if you have any guess on what might be the reason, I can take a look at it. Thank you in advance!

**Comment by ultmaster** [comment]
If you are not using hardware-aware NAS, the error is unlikely to be correlated to the operations you are using.

**Comment by ekurtgl** [comment]
Got it, thank you!
