### ISSUE TITLE
NAS export_top_models exports highest scored model

### ISSUE THREAD

**Issue by sw33zy** [microsoft/nni#5626]
**Describe the issue**:
Before version 3.0rc1, export_top_models received optimize_mode, which could be 'minimize'. 

I can retrieve the number of models trained and export k=num_models to get, in my case, the lowest-scored model. Is this the simplest way?

This leads me to my next question. How does a search strategy know whether it is supposed to be minimizing the metric (e.g. mse, crossentropy) or maximizing (e.g. accuracy)? Previously some search strategies did use optimize_mode as a parameter.

**Environment**:
- NNI version: 3.0rc1

**Comment by sw33zy** [comment]
I'm glad I asked then since I was getting the feeling that was the case, with removing optimize_mode and with examples always using a maximizable metric. 

However, I think it would be helpful to explicitly document the default behavior of the search strategies (I'm not sure if it is on the docs).

Also, doesn't pl.Regression use mse as a metric? From what I can see it isn't being reversed, which means search strategies are maximizing it

**Comment by ultmaster** [comment]
Haven't really realized what's the case of pl.Regression. But what you are saying makes sense to me. There's indeed a problem in minimizing mse.

I can update the docs if the PR workflow is still working smoothly. Otherwise, this issue looks like a good reference. :)

**Comment by sw33zy** [comment]
Awesome! I'll close the issue now.
