### ISSUE TITLE
DARTS experiment does not save

### ISSUE THREAD

**Issue by ekurtgl** [microsoft/nni#5638]
Hi,

I was able to run the darts tutorial. However, when I want to save the experiment,  although it doesn't show any error, it doesn't save the experiments:

![image](https://github.com/microsoft/nni/assets/66868163/a6321b25-dceb-443c-9233-12a48bc7994c)

Other multi-trial experiements are being save without any problem, and I use the exact same two lines of codes. Is there a different way of saving oneshot methods?

![image](https://github.com/microsoft/nni/assets/66868163/7353dcd8-2d40-42c9-9d80-8031d757265a)

Thank you!

**Comment by matluster** [comment]
For versions below v3.0, saving one-shot experiments does not work.

**Comment by ekurtgl** [comment]
Got it, thank you!
