### ISSUE TITLE
"Feedback" button

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/nni#575]
1. Feed**B**ack should be Feedback.

2. may we add "label" to the new issue? for differentiate versions.
current issue link: https://github.com/Microsoft/nni/issues/new
sample change: https://github.com/Microsoft/pai/issues/new?labels=v0.8.3

**Comment by scarlett2018** [comment]
@lvybriage - not in a hurry, no need to fix it in 0.5 =).

**Comment by jpat6179** [comment]
Lol, can I have my terrot?

**Comment by xuehui1991** [comment]
Fixed.
