### ISSUE TITLE
Pytorch HPO tutorials stucked in strating server

### ISSUE THREAD

**Issue by rrc693** [microsoft/nni#5782]
**Describe the issue**:
The pytorch tutorials code stucked in Starting web server... for long time(more than 20mins), without setting up logged in console 

**Environment**:
- NNI version:3.0
- Training service (local|remote|pai|aml|etc):local
- Client OS:windows 11
- Server OS (for remote mode only): local
- Python version:3.9.11
- PyTorch/TensorFlow version:2.10
- Is conda/virtualenv/venv used?:yes
- Is running in Docker?:No

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - 
![image](https://github.com/microsoft/nni/assets/68151037/cf780746-f5c2-48c8-aee1-9b7f823bf1e1)

 - dispatcher.log:
 - nnictl stdout and stderr:
 

![image](https://github.com/microsoft/nni/assets/68151037/2eff21d0-afb8-4b08-9690-06e24d97afea)
![image](https://github.com/microsoft/nni/assets/68151037/d6004b85-dbb4-4038-a2a6-93a49c1ed0b7)

**How to reproduce it?**:

**Comment by jimmy133719** [comment]
Hi, I have the same problem. How did you fix it?
