### ISSUE TITLE
IP:logs/trial_trialID.log interface return 200, but actually don't exit.

### ISSUE THREAD

**Issue by lvybriage** [microsoft/nni#583]
version: v0.5
mode: pai

When a trial's status is waiting or running, 
sometimes I got nothing when I click the “trial stdout” link.
The "trial stdout" link should be trial's log content.

![1](https://user-images.githubusercontent.com/35484733/52610781-81a0b380-2ebd-11e9-98c3-af3b58e46fcd.png)

![2](https://user-images.githubusercontent.com/35484733/52610783-84030d80-2ebd-11e9-8460-ed418a3821b3.png)

**Comment by ultmaster** [comment]
The design is outdated. Closing it.
