### ISSUE TITLE
slow rendering of webui

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#590]
when using https://github.com/Microsoft/nni/blob/master/examples/trials/mnist/config_pai.yml, and set trialConcurrency to 50, 2 issues were found. 

**In scope**
Issue 1: The rendering becomes very slow. 

**Out of scope**
Issue 2: The update of trial jobs' state has high latency compared to the states from pai's webui. **This issue will cover in #592** 

The original problem is not able to reproduce. We had discussed and would like to fix the problem in 2 aspects:
- reduce the loading actions and frequency
- batch get results

**Exit Criteria**
Precondition: mock 6000 trial with 100 intermediate results for each (yuge)

**Comment by jpat6179** [comment]
Hello

**Comment by scarlett2018** [comment]
Are we still seeing this in v0.6? how slow it is?

**Comment by QuanluZhang** [comment]
"the update of trial jobs' state has high latency compared to the states from pai's webui" this part will be fixed in v0.7 by @chicm-ms

**Comment by scarlett2018** [comment]
> "the update of trial jobs' state has high latency compared to the states from pai's webui" this part will be fixed in v0.7 by @chicm-ms

Thanks, updating this Issue's scope in the first comment.

**Comment by scarlett2018** [comment]
Assign to Quanlu to verify whether this is still an issue for the latest build.

**Comment by scarlett2018** [comment]
@LeonardoWang had verified the issue is no longer reproducible, closing it.

**Comment by ultmaster** [comment]
Tracked in #1425. Closing it.
