### ISSUE TITLE
mnist example seems frozen at the begging

### ISSUE THREAD

**Issue by nathanningbo** [Microsoft/nni#604]
when I using this code :
nnictl create --config nni/examples/trials/mnist/config.yml
the output seems right:
INFO: Starting restful server...
INFO: Successfully started Restful server!
INFO: Setting local config...
INFO: Successfully set local config!
INFO: Starting experiment...
INFO: Successfully started experiment!

but until I wait for more than ten minutes, the  nnictl log stdout    stay the same 
-----------------------------------------------------------------------
                Experiment start time 2019-01-14 14:31:31
-----------------------------------------------------------------------

and the webui is full of no data .
what happened and how can I  fix this ?

**Comment by Crysple** [comment]
hi, nathanningbo.
Could you please post your nni_manager.log and dispatcher.log, which are in the experiment root path.
And do you install NNI from source code(which branch) or PIP?
I guess it is because nni-sdk is not installed correctly. (If so, you might try to type `python3 -c 'import nni; print(nni.__file__)'` and see if it works correctly. If not, use pip to install nni-sdk package again.

**Comment by nathanningbo** [comment]
@Crysple  use PIP ..  And I find out it was the network problem ..... when i download the mnist by hand and put it in the Directory, it  worked .   But the log doestn't give any hints before ,i  suggest maybe you should add same log when the code deal with the data ..

**Comment by xuehui1991** [comment]
@nathanningbo  thank you for your suggestion. We will find some solution to fix it.

**Comment by scarlett2018** [comment]
@nathanningbo - seems the problem is resolved (per the discussion in gitter), may you confirm whether it is already resolved? if so, would you mind also summarize how it is fixed? thanks.

**Comment by nathanningbo** [comment]
i download the 4 .gz files  by hand  and put it together . And then  change the  data dir in mnist.py like 
 params = {
        'data_dir': '/data0/nni_mnist/input_data',
    }
Then it will work , i might be the network problem cause the issue
