### ISSUE TITLE
mnist example on the local machine  the restful server failed 

### ISSUE THREAD

**Issue by nathanningbo** [Microsoft/nni#607]
nnictl create --config nni/examples/trials/mnist/config.yml
WARNING: expand searchSpacePath: search_space.json to /data0/tengfei15/nnitmo/nni/examples/trials/mnist/search_space.json 
WARNING: expand codeDir: . to /data0/tengfei15/nnitmo/nni/examples/trials/mnist/. 
INFO: Starting restful server...
ERROR: Restful server start failed!
INFO:  Stdout:
-----------------------------------------------------------------------
                Experiment start time 2019-01-14 17:53:04
-----------------------------------------------------------------------

INFO:  Stderr:
-----------------------------------------------------------------------
                Experiment start time 2019-01-14 17:53:04
-----------------------------------------------------------------------

I  have checkout  the 51188 port which is not be occupied by 
netstat -tunap | grep 8080

/root/nni/experiments/p2LHrjeY/log/nnimanager.log outputs:
  [2019-01-14T09:53:05.187Z] INFO Rest server listening on: http://0.0.0.0:8080
  [2019-01-14T09:53:05.178Z] INFO RestServer start
  [2019-01-14T09:53:05.184Z] INFO RestServer base port is 8080
  [2019-01-14T09:53:19.591Z] INFO Experiment done, cleaning up...

Tips:python3 install by source, not by anaconda 
how can I fix this ,thanks!!!

**Comment by nathanningbo** [comment]
> Dear nathanningbo, can I asked which branch do you install? thank you~

@xuehui1991 , i use PIP instead of source

**Comment by xuehui1991** [comment]
But we still want to figure out this question, could you told us which branch you install? thank you

**Comment by nathanningbo** [comment]
you mean the version?
here is the pip list :
nni                      0.4.1     
nni-sdk                  0.4.1    
@xuehui1991
any hints that i can fix this ? the mnist example  works on my mac. but it can't run on the local machine or k8s on my company's servers. my boss wanna choose autokeras or nni to be our base . so please give some suggest  and our team may give same strength in the future.

**Comment by Crysple** [comment]
hi, nathanningbo.
Could you please post your nni_manager.log and **dispatcher.log**, which are in the experiment root path.
And do you install NNI from source code(which branch) or PIP?
I guess it is because nni-sdk is not installed correctly. (If so, you might try to type python3 -c 'import nni; print(nni.__file__)' and see if it works correctly. If not, use pip to install nni-sdk package again.

**Comment by xuehui1991** [comment]
By the way, could you try to use the "auto-gbdt" example and put some log here? We would like to figure out this question~  Thank you very much.

**Comment by nathanningbo** [comment]
@xuehui1991 using code like nnictl create --config nni/examples/trials/auto-gbdt/config.yml ?

nnictl create --config nni/examples/trials/auto-gbdt/config.yml
WARNING: expand searchSpacePath: search_space.json to /data0/tengfei15/nnitmo/nni/examples/trials/auto-gbdt/search_space.json 
WARNING: expand codeDir: . to /data0/tengfei15/nnitmo/nni/examples/trials/auto-gbdt/. 
INFO: Starting restful server...
ERROR: Restful server start failed!
INFO:  Stdout:
-----------------------------------------------------------------------
                Experiment start time 2019-01-15 10:25:47
-----------------------------------------------------------------------




INFO:  Stderr:
-----------------------------------------------------------------------
                Experiment start time 2019-01-15 10:25:47
-----------------------------------------------------------------------


 cat  /root/nni/experiments/Y3kZDCly/log/nnimanager.log 
[2019-01-15T02:25:50.742Z] INFO Rest server listening on: http://0.0.0.0:8080
[2019-01-15T02:25:50.730Z] INFO RestServer start
[2019-01-15T02:25:50.738Z] INFO RestServer base port is 8080
[2019-01-15T02:26:02.601Z] INFO Experiment done, cleaning up...
auto-gdbt test ouptputs the samme error as mnist 
it seems like a envirment error or system error ?

**Comment by Crysple** [comment]
Hi, could you check if node works? Just type `node --version`. If not, try to export your python bin path to PATH, which might be /usr/local/bin (you can type `which nnictl` to see the path but I think its already in PATH)


BTW, we release nni 0.5 yesterday. So it better to try to upgrade nni and see if it works.

Currently NNI is separeted into two package (nni and nni-sdk). So if you upgrade nni, make sure this two package is of the same version.  (We will combine these two packages in the future)

**Comment by nathanningbo** [comment]
node --version
v10.13.0
[root@node60 tengfei15]# echo $PATH
/root/ali/local/hadoop-2.8.1/bin:/root/ali/local/hadoop-2.8.1/sbin:/usr/lib/java/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/cuda/bin:/usr/local/python3.6.7/bin:/root/bin

ok ，i will try.
@Crysple

**Comment by nathanningbo** [comment]
pip3 list :
nni                      0.5       
nni-sdk                  0.5

nnictl create --config nni/examples/trials/mnist/config.yml
INFO: expand searchSpacePath: search_space.json to /data0/tengfei15/nnitmo/nni/examples/trials/mnist/search_space.json 
INFO: expand codeDir: . to /data0/tengfei15/nnitmo/nni/examples/trials/mnist/. 
INFO: Starting restful server...
ERROR: Restful server start failed!
INFO:  Stdout:
-----------------------------------------------------------------------
                Experiment start time 2019-01-15 11:50:28
-----------------------------------------------------------------------




INFO:  Stderr:
-----------------------------------------------------------------------
                Experiment start time 2019-01-15 11:50:28
-----------------------------------------------------------------------
SAME  error @Crysple

**Comment by xuehui1991** [comment]
@nathanningbo  We have a Gitter Chat Room for in time communication on the usage of API. https://gitter.im/Microsoft/nni. You could join and we could have a further discussion.

**Comment by Crysple** [comment]
The problem might be that there're some exceptions in Rest that are passed instead of thrown out. Therefore, related logs are missing. We are now trying to figure it out. We have temporarily modified some codes and you can install that branch to see what's wrong. It's being done so I will post that branch here soon. Or you might also post a reproduce process (including how python is install etc.

**Comment by nathanningbo** [comment]
It may causes by many reasons, but when i change the machine which`s network is well dealed ,and then used this docker,everything works well , i hope i will help guys in china ,because i find out the docker provided by nni team can not be pulled .
 # Docker image for running examples in Tensorflow models.
# base_image depends on whether we are running on GPUs or non-GPUs
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

# Add custom china source
# RUN rm /etc/apt/sources.list.d/*
# COPY docker/pytorch/sources.list /etc/apt/

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    checkinstall \
    libx11-dev \
    libxext-dev \
    zlib1g-dev \
    libpng12-dev \
    libfreetype6-dev \
    libxml2-dev \
    wget \
    cmake \
    git \
    curl \
    vim \
    ca-certificates \
    libjpeg-dev \
    libpng-dev \
    zip \
    wget \
    libfreetype6-dev \
    libhdf5-serial-dev \
    libzmq3-dev \
    software-properties-common && \
  rm -rf /var/lib/apt/lists/*

ARG USE_PYTHON_3_NOT_2=True
ARG _PY_SUFFIX=${USE_PYTHON_3_NOT_2:+3}
ARG PYTHON=python${_PY_SUFFIX}
ARG PIP=pip${_PY_SUFFIX}

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y \
    ${PYTHON} \
    ${PYTHON}-pip

RUN ${PIP} install --upgrade \
    pip \
    setuptools

RUN ${PIP} install jupyter && \
    mkdir /root/.jupyter && \
    echo "c.NotebookApp.ip = '*'" \
         "\nc.NotebookApp.open_browser = False" \
         "\nc.NotebookApp.token = ''" \
         > /root/.jupyter/jupyter_notebook_config.py
EXPOSE 8888

RUN python3 -m pip install --upgrade nni
RUN pip install tensorflow-gpu
