### ISSUE TITLE
Multiple trials on the same GPU

### ISSUE THREAD

**Issue by Iftimie** [microsoft/nni#608]
Hello nni team!

I managed to start successfully  this manager, however I want to know if it is possible to start multiple trainings on the same GPU
In your [description](https://github.com/Microsoft/nni/blob/master/docs/tutorial_1_CR_exp_local_api.mdl) is says:

> The following steps assume that you have 4 NVIDIA GPUs installed at local and tensorflow with GPU support. The demo enables 4 concurrent trail jobs and each trail job uses 1 GPU.

I have 2 GPUs with 11 GB memory each, and a training session only takes 1 GB. So I could start at least 16.

However, in the WebUI only two of them are shown as running.

Is there any way to overcome this limitation? 

Thank you

**Comment by QuanluZhang** [comment]
This GPU assignment is implemented in training service (i.e., https://github.com/Microsoft/nni/tree/master/src/nni_manager/training_service). In the current implementation, each GPU can only be assigned to one trial job. A possible way is to customize your own training service, NNI defines clear interface for training service.

Your requirement is reasonable, we may support this feature in future release.

**Comment by scarlett2018** [comment]
@Iftimie - Aside from waiting the implementation, you are also highly encouraged to use this issue as a "good first issue" to contribute back to NNI. We have a Gitter Chat Room for in time communication on the usage of API and how to contribute. https://gitter.im/Microsoft/nni

**Comment by QuanluZhang** [comment]
@Iftimie There is another possible way to meet your requirement.
NNI supports [multiphase](https://github.com/Microsoft/nni/blob/master/docs/multiPhase.md) which can be used in your scenario. Specifically, each trial job requests 11 configurations (i.e., hyperparameters), and run them concurrently on a single GPU. If you have further questions about this, feel free to discuss in this track.

**Comment by wang-kangkang** [comment]
I solve this problem. use the following command:
nnictl create --config config.yml --port 8080    
nnictl create --config config.yml --port 8081
the "--port 8080" is default, you can do not write it.But you need write --port 8081, you can set other port number . than "nnictl top", you can find there is two experiments Id, it means you can start more than one experiment in one GPU card.

**Comment by Iftimie** [comment]
@wang-kangkang I believe it may work, but do you have any idea if both servers will use the same tuner. Do they share the explored search space. I think they will work independently, but hey, that's still a good idea.
btw, I have been using this tool for a few days and it's pretty good, I found some good hyper-parameters with it.

**Comment by aminshabani** [comment]
@wang-kangkang This was working when I used the version 0.5.2.1, thank you so much. However, in the new release, V0.7, the second experiment will just wait because the GPU is not completely free. Do you know how we can use it now?
