### ISSUE TITLE
Fail to find nni under both "%s" and "%s"' % (local_python_dir, python_dir)

### ISSUE THREAD

**Issue by gonghuiyun** [Microsoft/nni#626]
![nni_fail](https://user-images.githubusercontent.com/12653453/51316141-c12ada00-1a8e-11e9-94b3-3db8b17da14c.png)

**Comment by gonghuiyun** [comment]
> It seems nni is not correctly installed.
> Could you describe how did you install nni?
> Your python version?
> Did you installed nni out of python virtualenv before?
> Could you list the directory: ~/.local/ and <your virtualenv>/ ? Is there nni/ directory there?

1)my OS:Ubuntu 16.04
Firstly I activate tensorflow env in anaconda, then I use pip command:
(tensorflow) abc@abc-System-Product-Name:~$ python3 -m pip install --user --upgrade nni
install information:
![install](https://user-images.githubusercontent.com/12653453/51390376-11c33580-1b6a-11e9-9b33-f758c755d5f0.png)
2)my python version:
![python vi](https://user-images.githubusercontent.com/12653453/51390427-3e774d00-1b6a-11e9-9a3e-9ebd627064ec.png)
3)I'm not sure is anaconda belong to python virtualenv?I installed nni in anaconda env.
4)~/.local/ 
![local](https://user-images.githubusercontent.com/12653453/51390619-be9db280-1b6a-11e9-9fc9-bcba17aa7cd3.png)
I don't find any nni directory in my anaconda path:
~/anaconda3/envs/tensorflow/lib/python3.6/site-packages

**Comment by QuanluZhang** [comment]
@gonghuiyun If you use `--user` for the installation in virtualenv, nni will be installed under `~/.local/lib/python` rather than in your virtualenv. This is the property of python package installation. Due to a bug in nni v0.5, nnictl cannot find the nni installed under `~/.local/lib/python`. We will fix this bug very soon. **You can work around this bug by installing nni in virtualenv through the command** `python3 -m pip install --upgrade nni`.

**Comment by gonghuiyun** [comment]
> @gonghuiyun If you use `--user` for the installation in virtualenv, nni will be installed under `~/.local/lib/python` rather than in your virtualenv. This is the property of python package installation. Due to a bug in nni v0.5, nnictl cannot find the nni installed under `~/.local/lib/python` in virtualenv. We will fix this bug very soon (#631). **You can workaround this bug by installing nni in virtualenv through the command** `python3 -m pip install --upgrade nni`.

It seems still don't work after I fix the command.

![fix](https://user-images.githubusercontent.com/12653453/51421391-9d73ab00-1bd8-11e9-9e41-fcf43a3a67a5.png)

**Comment by gonghuiyun** [comment]
> @gonghuiyun If you use `--user` for the installation in virtualenv, nni will be installed under `~/.local/lib/python` rather than in your virtualenv. This is the property of python package installation. Due to a bug in nni v0.5, nnictl cannot find the nni installed under `~/.local/lib/python` in virtualenv. We will fix this bug very soon (#631). **You can workaround this bug by installing nni in virtualenv through the command** `python3 -m pip install --upgrade nni`.

(tensorflow) abc@abc-System-Product-Name:~$ python3 -m pip install --upgrade nni
Requirement already up-to-date: nni in ./.local/lib/python3.6/site-packages (0.5)
Requirement already satisfied, skipping upgrade: psutil in ./.local/lib/python3.6/site-packages (from nni) (5.4.8)
Requirement already satisfied, skipping upgrade: schema in ./.local/lib/python3.6/site-packages (from nni) (0.6.8)
Requirement already satisfied, skipping upgrade: astor in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from nni) (0.7.1)
Requirement already satisfied, skipping upgrade: requests in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from nni) (2.21.0)
Requirement already satisfied, skipping upgrade: nni-sdk==0.5 in ./.local/lib/python3.6/site-packages (from nni) (0.5)
Requirement already satisfied, skipping upgrade: pyhdfs in ./.local/lib/python3.6/site-packages (from nni) (0.2.1)
Requirement already satisfied, skipping upgrade: pyyaml in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from nni) (3.13)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from requests->nni) (1.24.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from requests->nni) (2018.11.29)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from requests->nni) (2.8)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from requests->nni) (3.0.4)
Requirement already satisfied, skipping upgrade: coverage in ./.local/lib/python3.6/site-packages (from nni-sdk==0.5->nni) (4.5.2)
Requirement already satisfied, skipping upgrade: json-tricks in ./.local/lib/python3.6/site-packages (from nni-sdk==0.5->nni) (3.12.2)
Requirement already satisfied, skipping upgrade: numpy in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from nni-sdk==0.5->nni) (1.15.4)
Requirement already satisfied, skipping upgrade: scipy in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from nni-sdk==0.5->nni) (1.2.0)
Requirement already satisfied, skipping upgrade: hyperopt in ./.local/lib/python3.6/site-packages (from nni-sdk==0.5->nni) (0.1.1)
Requirement already satisfied, skipping upgrade: simplejson in ./.local/lib/python3.6/site-packages (from pyhdfs->nni) (3.16.0)
Requirement already satisfied, skipping upgrade: networkx in ./.local/lib/python3.6/site-packages (from hyperopt->nni-sdk==0.5->nni) (2.2)
Requirement already satisfied, skipping upgrade: six in ./anaconda3/envs/tensorflow/lib/python3.6/site-packages (from hyperopt->nni-sdk==0.5->nni) (1.12.0)
Requirement already satisfied, skipping upgrade: future in ./.local/lib/python3.6/site-packages (from hyperopt->nni-sdk==0.5->nni) (0.17.1)
Requirement already satisfied, skipping upgrade: pymongo in ./.local/lib/python3.6/site-packages (from hyperopt->nni-sdk==0.5->nni) (3.7.2)
Requirement already satisfied, skipping upgrade: decorator>=4.3.0 in ./.local/lib/python3.6/site-packages (from networkx->hyperopt->nni-sdk==0.5->nni) (4.3.0)

**Comment by QuanluZhang** [comment]
Could you run several commands and report the results:
1. in your virtualenv (i.e., anaconda), run `which nnictl`
2. in your virtualenv (i.e., anaconda), run `nnictl --version`
3. run `ls ~/anaconda3/envs/tensorflow/`

**Comment by scarlett2018** [comment]
@gonghuiyun - thanks for reporting the issue and support us with the information. You are also encouraged to join the Gitter Chat Room, which has Mobile Client, that might more convenience for in time communication. Our Gitter Chat Room is: https://gitter.im/Microsoft/nni , FYI.

**Comment by gonghuiyun** [comment]
> Could you run several commands and report the results:
> 
> 1. in your virtualenv (i.e., anaconda), run `which nnictl`
> 2. in your virtualenv (i.e., anaconda), run `nnictl --version`
> 3. run `ls ~/anaconda3/envs/tensorflow/`

![tensorenv](https://user-images.githubusercontent.com/12653453/51428540-d1ce8200-1c3f-11e9-8d9a-aa8160c21ffd.png)

**Comment by QuanluZhang** [comment]
fixed, close
