### ISSUE TITLE
Installation for nni from source code on Azure B1s VM is stuck

### ISSUE THREAD

**Issue by goooxu** [Microsoft/nni#65]
Create a `B1s` type Azure VM (Ubuntu 16.04), and try to follow the command
```
git clone https://github.com/Microsoft/nni.git@v0.4
cd nni
make easy-install
```
to install nni, but it stuck, the last message is

```
$ react-app-rewired build --scripts-version react-scripts-ts
    Creating an optimized production build...
    Starting type checking and linting service...
    Using 1 worker with 2048MB memory limit
    ts-loader: Using typescript@3.0.1 and /tmp/pip-vcid8cpq-build/src/webui/tsconfig.json
    No valid rules have been specified
```

**Comment by yds05** [comment]
Need to update documentation to list NNI minimum hardware limitation.

**Comment by QuanluZhang** [comment]
Please use a VM with larger memory (> 4GB), recommend 8GB

**Comment by lipingbj** [comment]
Is 4GB enough?

**Comment by scarlett2018** [comment]
@lipingbj - in v0.3, we start to support pip package install which requires less Memory during installation.

May you try the following method to install with 4GB memory:
python3 -m pip install --user --upgrade nni

**Comment by yds05** [comment]
@goooxu  Could you please help confirm if it is fixed since NNI v0.3.x?

**Comment by goooxu** [comment]
@yds05 still reproduce in v0.4

**Comment by scarlett2018** [comment]
For NNI installation, please make sure your system meet the recommended system requirement: https://github.com/Microsoft/nni/blob/master/docs/Installation.md#system-requirements
