### ISSUE TITLE
Add citation details

### ISSUE THREAD

**Issue by imirzadeh** [microsoft/nni#651]
Hi, 

I think it would be good if you add citation details so people who use NNI can cite it.

**Comment by xuehui1991** [comment]
@imirzadeh really thank you. We are preparing about this, you could reference the link of opensource for now.

**Comment by ashutoshIITK** [comment]
Any update on this?

**Comment by Cherishty** [comment]
Any update?

**Comment by ashutoshIITK** [comment]
I just added the link to this GitHub repo in paper. :p

**Comment by scarlett2018** [comment]
> I just added the link to this GitHub repo in paper. :p

Thanks @ashutoshIITK !

**Comment by kvartet** [comment]
Thank you again, we have add citation details in PR #3150. 

I’m closing this issue, please feel free to reopen if you are still seeing it an active issue.
