### ISSUE TITLE
Multiphase doc should be more clear on scenarios.

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/nni#659]
I read through below doc, but cannot fully understand 3 scenarios in this doc. It's great, if some example can be provided. It doesn't need to be code example, some situation and related configuration is enough.

https://github.com/Microsoft/nni/blob/master/docs/multiPhase.md

**Comment by squirrelsc** [comment]
new location of it.

https://github.com/Microsoft/nni/blob/master/docs/en_US/multiPhase.md

**Comment by QuanluZhang** [comment]
refactored this part in pr https://github.com/Microsoft/nni/pull/969
