### ISSUE TITLE
Experiment didn't stop after reaching max trial number

### ISSUE THREAD

**Issue by goooxu** [Microsoft/nni#69]
Try to create an experiment following the basic example

```
nnictl create --config ~/nni/examples/trials/mnist-annotation/config.yml
```

the max trial number is 1 in the config.yml

![image](https://user-images.githubusercontent.com/22703054/45539221-a5db6400-b83b-11e8-8a88-680dc3f84f26.png)

but after the only 1 trial is succeeded, the experiment didn't stop
I try to create it again, but got the below error

![image](https://user-images.githubusercontent.com/22703054/45539186-8fcda380-b83b-11e8-87df-cb2fac78d55d.png)

**Comment by SparkSnail** [comment]
Do you mean that we should stop restful server after job is succeeded?

**Comment by QuanluZhang** [comment]
This is by design, restserver will not stop until you explicitly issue `nnictl stop`
