### ISSUE TITLE
Help for nnictl is confused

### ISSUE THREAD

**Issue by goooxu** [Microsoft/nni#70]
After create an experiment, I want to check the status of the experiment
Firstly, I run the command `nnictl --help` to see how can I check the status of the experiment,
![image](https://user-images.githubusercontent.com/22703054/45539415-46ca1f00-b83c-11e8-9225-4b6c7b60775c.png)
It shows maybe I can use `nnictl experiment`, but after I run the command `nnictl experiment`, but it shows
![image](https://user-images.githubusercontent.com/22703054/45539367-1a160780-b83c-11e8-82e7-1d5d6807045b.png)

It just a loop, I don't know how to check the status of the experiment finally.

**Comment by SparkSnail** [comment]
fixed.
https://github.com/Microsoft/nni/pull/71
