### ISSUE TITLE
Same parameters are sent to trial 

### ISSUE THREAD

**Issue by leelaylay** [Microsoft/nni#731]
When search space is limited to only some choices and there is many trials working concurrently, some tuners will send same config to trials.

**Comment by zehuichen123** [comment]
I've met the same problem when using TPE tuner.

**Comment by leelaylay** [comment]
Fix for TPE #729

**Comment by leelaylay** [comment]
> I've met the same problem when using TPE tuner.

@zehuichen123  I think it

**Comment by zehuichen123** [comment]
I noticed that NNI using TPE from hyperopt, maybe that's the reason

**Comment by leelaylay** [comment]
> I noticed that NNI using TPE from hyperopt, maybe that's the reason

@zehuichen123 
Yeah, I am considering how to fix it in an elegant way.

**Comment by xuehui1991** [comment]
@zehuichen123  You could reference this PR: random search when suggested parameter appeared in the history #734.   Fixed this problem.
