### ISSUE TITLE
Request for a command to restore the log and to start the WebUI

### ISSUE THREAD

**Issue by leelaylay** [Microsoft/nni#748]
When the experiment is stopped, I found it no way to see the results except for analysing the "dispatcher.log" mannually. I hope that NNI could provide a command to restore the log and to start the WebUI in [NNICTLDOC](https://github.com/Microsoft/nni/blob/master/docs/NNICTLDOC.md) such as "nnictl log restore /path/to/dispatcher.log".

**Comment by QuanluZhang** [comment]
There is such a command, `nnictl resume`. Please refer to https://nni.readthedocs.io/en/latest/NNICTLDOC.html

**Comment by leelaylay** [comment]
Thank you.
