### ISSUE TITLE
undocumented `STEPS` hyper-param of Hyperband advisor.

### ISSUE THREAD

**Issue by leckie-chn** [Microsoft/nni#754]
Hyperband advisor introduced a hard-coded hyper-parameter `STEPS` and there's only a piece of comments about it:
https://github.com/Microsoft/nni/blob/a6c2ac2b56de6586ec801fba76a77bacd2436429/examples/trials/mnist-hyperband/mnist.py#L228-L230

Should be added to hyperband documentation.

**Comment by QuanluZhang** [comment]
We have doc for `STEPS`, it is in https://github.com/Microsoft/nni/blob/master/src/sdk/pynni/nni/hyperband_advisor/README.md. I will make it more clear. And this file will be moved under docs/

**Comment by xuehui1991** [comment]
Shufan will fix this.

**Comment by QuanluZhang** [comment]
fixed
