### ISSUE TITLE
NNI doesn't support private docker registry

### ISSUE THREAD

**Issue by yds05** [microsoft/nni#755]
Right now, NNI user has to upload docker image into a public docker registry like docker hub. However, in some case user may not want to upload the image into public registry because the image contains private source code or data. 
Could NNI support private docker registry as well?

**Comment by leckie-chn** [comment]
@yds05 According to [Pull from a different registry
](https://docs.docker.com/engine/reference/commandline/pull/#pull-from-a-different-registry), pulling from a different registry is natrually supported. For example, `private.docker.registry.io/msranni/nni`

**Comment by yds05** [comment]
For the image name, we can put registry's realm into the full name path. However, NNI still need to support auth provided by user like token/cert.
