### ISSUE TITLE
missing metric value with annotation

### ISSUE THREAD

**Issue by songqiqqq** [Microsoft/nni#771]
**Short summary about the issue/question**:

**Brief what process you are following**: 
I try to use `"""@nni.report_intermediate_result(loss)"""` and `"""@nni.report_final_result(loss)"""` annotation to report the metric. However , at the side of web-UI, I can not get any value of the metric.  The status shows the program is successfully executed.  

I tried to locate this bug source:
(1) First , I checked the file at :`cat ~/nni/experiments/ANF1NHa8/trials/WxIJU/.nni/metrics` and the file exist there but nothing is in it.  Therefore, I suspect the metric written process has some problems.

(2)Then, I checked the function for metric writting.`(report_final/intermediate_result at the file: ~/.local/lib/python3.5/site-packages/nni/trial.py)`. I made some experiments and found this function is not executed in the whole process.

(3)Then, I checked the command in the run.sh file, 
```
vim ~/nni/experiments/ANF1NHa8/trials/WxIJU/run.sh 

cd /tmp/qsong/nni/annotation/tmpw4iu7xwj
export NNI_PLATFORM=local
export NNI_SYS_DIR=/home/qsong/nni/experiments/ANF1NHa8/trials/WxIJU
export NNI_TRIAL_JOB_ID=WxIJU
export NNI_OUTPUT_DIR=/home/qsong/nni/experiments/ANF1NHa8/trials/WxIJU
export NNI_TRIAL_SEQ_ID=0
export MULTI_PHASE=false
export CUDA_VISIBLE_DEVICES=0
eval python /work/qsong/myusim/src/squtils/nni/tfmain_nni.py 2>/home/qsong/nni/experiments/ANF1NHa8/trials/WxIJU/stderr
echo $? `date +%s000` >/home/qsong/nni/experiments/ANF1NHa8/trials/WxIJU/.nni/state
```
It shows that, the origin file is executed. In that file, the """@nni.report_intermediate_result(loss)""" is still the string. In my mind, the produced file at /tmp/qsong/nni/annotation/ should be executed. In that file, the report function is changed to command from string. 

It looks like a bug ?

**How to reproduce it**: 

**nni Environment**:
- nni version: 0.5.1
- nni mode(local|pai|remote): local
- OS:Linux
- python version: python3.5
- is conda or virtualenv used?:  NO
- is running in docker?:NO

**Anything else we need to know**:

**Comment by songqiqqq** [comment]
The problem is solved. I should not write the path information at comand line in the yml file.  After it's removed, everything is ok.

**Comment by caiqi** [comment]
@songqiqqq I met the same problem. Could you please explain more on how you solved the problem?

**Comment by caiqi** [comment]
I found out the problem is due to I use mmdetection(mmclassificatoin, detectron2,etc. should have similar phenomenon) for training. I post the solution here if anyone else met the same problem. Although the code is copied to trial dir, it actually uses the original code path where nni.report_intermediate_result is still commented. Change ```python tools/train.py ...``` to ```python setup.py develop && python tools/train.py ...``` would solve the problem.
