### ISSUE TITLE
Review / compare several experiments 

### ISSUE THREAD

**Issue by kostasfilip** [microsoft/nni#774]
Hi NNI Team

I just started working with nni and it is a great and simple management tool. My question is if it is possible to view and compare several experiments on the UI or load old experiments to review them again. I couldn't find this in the documentation. Are there any future plans for that? 

Thank you very much for your time and for the great work. 
Best

**Comment by leelaylay** [comment]
@kostasfilip 
Review old experiment: `nnictl resume [experiment_id]`
Compare several experiments: as far as I know, there is no such command now.
If you want to know more about the nnictl usage, please refer to [this](https://github.com/Microsoft/nni/blob/master/docs/en_US/NNICTLDOC.md).

**Comment by QuanluZhang** [comment]
@kostasfilip Thanks for your feedback. May I ask what kind of information do you want to see from the UI, and what do you want to compare between different experiments? With your feedback, we can further improve the UI of nni.

**Comment by kostasfilip** [comment]
Hi @QuanluZhang 
I am new at experimenting with machine learning so this is an inexperienced point of view. For hyperparameter search one would try in the first experiment some random values based on some assumptions. Then, in the next experiments one would try parameter refinements until the best model is found. In this workflow I would like to compare all runs against each other in one list, being able to differentiate or filter based on experiment. If this list grows a lot (I expect that one experiment creates many runs,) I would like to be able to select the best run or the best i runs of each experiment and verify the progress. This is how I imagine the UI. 

Best regards

**Comment by QuanluZhang** [comment]
@kostasfilip These are valuable feedback, thanks, we will take them into nni's future enhancement.

**Comment by scarlett2018** [comment]
The issue had raised 3 improvements ask, we had implemented 2 of them so far:
- [Done] support replay (resume);
- [Done] support compare between trials;
- [To do] #1218 - considering this in July.

**Comment by ultmaster** [comment]
Tracked in #1529. Closing it.
