### ISSUE TITLE
Report final metrics with early stop

### ISSUE THREAD

**Issue by songqiqqq** [Microsoft/nni#776]
When the early stop is raised by the assessor of medianstop and curvefitting, the final metric value is missing (Web UI) . Is it possible to still report a 'final metric'  when early stop is raised with the two built-in assessor? Or how to implement this using a customized assessor ?

**Comment by scarlett2018** [comment]
Thanks @songqiqqq for reporting the issue, this is an known limitation for NNI, we are working on the design and discussion. Any feedback or suggestions are appreciated =).

**Comment by chicm-ms** [comment]
Done, implemented in v0.6.
