### ISSUE TITLE
stopExperiment problem in Ubuntu unit test for nniManager

### ISSUE THREAD

**Issue by demianzhang** [microsoft/nni#779]
**Short summary about the issue/question**:
Unit test for nniManager in Ubuntu without delaying for a while to stopExperiment will get an error.
```
1) Unit test for nnimanager  
       "after all" hook:  
     Uncaught Error: read ECONNRESET  
      at Pipe.onStreamRead (internal/stream_base_commons.js:111:27)
```
**Brief what process you are following**: 
delay for a while to stopExperiment to do the unit test.

**How to reproduce it**: 

in `nni/src/nnimanager/core/test/nnimanager.test.ts` change the code as follows:

```typescript
after(async () => {
        await nniManager.stopExperiment();
        //await setTimeout(() => nniManager.stopExperiment(),15000);
        cleanupUnitTest();
    })
```
**Windows version** is normal when stop without delaying

**nni Environment**:
- nni version: 0.5.1
- nni mode(local|pai|remote): local
- OS: Ubuntu16.04
- python version: 3.5.2
- is conda or virtualenv used?:  no
- is running in docker?: no

**Comment by scarlett2018** [comment]
This is an pretty old issue (on v0.5), ping @demianzhang and @chicm-ms to confirm whether this is still valid, thanks.
