### ISSUE TITLE
WebUI does not support nested search space

### ISSUE THREAD

**Issue by Crysple** [microsoft/nni#781]
**What would you like to be added**:
Show nested search space in WebUI

**Why is this needed**:
If NNI supports nested search space, it would be better to handle this in WebUI

**Without this feature, how does current nni work**：
Currently WebUI show nothing when you have a nested search space

**Components that may involve changes**:
WebUI

**Brief description of your proposal if any**:
None

**Comment by ultmaster** [comment]
Tracked in #1110.
