### ISSUE TITLE
Add more details about tuner, assessor design.

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/nni#784]
**What would you like to be added**:
For below tuners, assessors and advisors in docs folder, they have only overview usage, but not introduce how they are implemented. 

evolutionTuner.md, gridsearchTuner.md, hyperoptTuner.md, medianstopAssessor.md, smacTuner.md

**Why is this needed**:
Those information is helpful for who want to write customized tuner, assessor, and advisor.

**Without this feature, how does current nni work**：
it works without document changes..

**Components that may involve changes**:
document

**Brief description of your proposal if any**:
as above..

**Comment by scarlett2018** [comment]
We had made lots of improvement on documentation since Feb, the fundmental problem raised here should already addressed. Assigning to @rabbit008 to quickly go through the doc and list out what is left to be improved.
