### ISSUE TITLE
Typo in WebUI?

### ISSUE THREAD

**Issue by PurityFan** [Microsoft/nni#789]
**Short summary about the issue/question**:
It seems that there is a typo in WebUI

**Brief what process you are following**: 
Start a NNI experiment, then you can see the typo like this:
![capture](https://user-images.githubusercontent.com/26495978/53464318-c105fd00-3a84-11e9-99ac-05b84b73feb2.PNG)
"Metric" not "Metrc"?

**nni Environment**:
- nni version: 0.5.1
- nni mode(local|pai|remote): local
- OS: Linux
- python version: 3.6
- is conda or virtualenv used?: no
- is running in docker?: no

@lvybriage please recheck and help to fix this typo?

**Comment by leelaylay** [comment]
There Lines:
https://github.com/Microsoft/nni/blob/master/src/webui/src/components/overview/SuccessTable.tsx#L6
https://github.com/Microsoft/nni/blob/master/src/webui/src/components/trial-detail/TableList.tsx#L13
https://github.com/Microsoft/nni/blob/master/src/webui/src/components/TrialsDetail.tsx#L95

**Comment by PurityFan** [comment]
Yes, it should be modified in the recent pr

**Comment by lvybriage** [comment]
@PurityFan  @leelaylay 
Thanks.
Had fixed in pr 790.

**Comment by PurityFan** [comment]
Solved by https://github.com/Microsoft/nni/pull/790
