### ISSUE TITLE
can not install psutil and nni installation failed

### ISSUE THREAD

**Issue by ltg001** [Microsoft/nni#818]
**Short summary about the issue/question**:
Can not install package Psutil and nni installation failed in setting up developer environment.
**Brief what process you are following**: 
1. git clone https://github.com/Microsoft/nni.git
2. make install-dependencies
3. make build
4. make dev-install

  just as the tutorial

**How to reproduce it**: 

**nni Environment**: the latest
- nni version: the latest
- nni mode(local|pai|remote): local
- OS: ubuntu
- python version: 3.6.7
- is conda or virtualenv used?: No, naive pip 
- is running in docker?: No

**Anything else we need to know**: the error information

 x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=560 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
  psutil/_psutil_common.c:9:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for psutil

**Comment by Crysple** [comment]
Hi @ltg001 , 
This error seems to have nothing to do with NNI. The error message shows that a python package dependency `psutil` is not installed correctly. I've checked it on google and found another [ISSUE](https://github.com/giampaolo/psutil/issues/1143) here

According to it, you might try `sudo apt-get install python-dev` first and then install `psutil` again.
> (Note that if you have multiple versions installed (like me, I have python 3.4.3 and 3.5.4 installed), you need to specify a more granular version, like so: `sudo apt-get install python3.5-dev`)

After that, it installed without issues. Or you could first try to install it yourself by `python3 -m pip install psutil`

**Comment by ltg001** [comment]
@Crysple Thank very much.
It seems to work for me. I think there is something wrong with my python3 provided by ubuntu18.04.
