### ISSUE TITLE
NNI does not support shmMB parameter in pai mode

### ISSUE THREAD

**Issue by gemfield** [Microsoft/nni#823]
For a standalone PAI jobconfig, I can configure shmMB in the config yaml file on web, which works ok for my training;
However, for NNI PAI mode, if I configure shmMB in the exp_pai.yml, and run the command:
```bash
nnictl create --config exp_pai.yml
```
then the error occurs:
```bash
ERROR: Your config file is not correct, please check your config file content!
Key 'trial' error:
Wrong key 'shmMB' in {'gpuNum': 2, 'shmMB': 8196, 'command': 'bash test.sh', 'codeDir': '/bigdata/gemfield/.', 'outputDir': 'hdfs://192.168.1.121:9000/nni', 'dataDir': 'hdfs://192.168.1.121:9000/DataSet/data2016', 'memoryMB': 8196, 'cpuNum': 2, 'image': 'gemfield/pytorch4hdfs:1.0.1'}
```
If I decide to not set shmMB in exp_pai.yml, then the job will fail during the training phase because of the shm limit.

**Comment by SparkSnail** [comment]
NNI does not support this param yet, we will support this feature in this sprint.
https://github.com/Microsoft/nni/issues/842
