### ISSUE TITLE
Models and other files written to disk do not appear when running code through NNI

### ISSUE THREAD

**Issue by proever** [microsoft/nni#848]
**Short summary about the issue/question**:
Hi there, normally my keras code saves the model's weights after each epoch. However, when I run it through NNI, these saved weights (and other files that should be saved) do not appear anywhere that I can find.

**Brief what process you are following**: 
Code that runs normally and has been annotated to allow NNI to run experiments with it has lines that write model parameters to disk, or generate images of model outputs and save those to disk. When that same code is evaluated through NNI, the files do not appear. 

**nni Environment**:
- nni version: 0.5.2.1
- nni mode(local|pai|remote): local
- OS: Ubuntu 16.04.5 LTS, AWS Deep Learning AMI (Ubuntu) Version 21.2
- python version: Python 3.6.5 :: Anaconda custom (64-bit)
- is conda or virtualenv used?: Yes, using the tensorflow_p36 virtualenv from the AMI above
- is running in docker?: no

**Comment by leelaylay** [comment]
@proever 
Hello, Paul. The model file or outputs may be found just below your own code directory.
I just try the simple example `mnsit-keras` and add the code below
```python
# mnist-keras example to save model
# it's better to save model with id in nni local mode
model_id = nni.get_sequence_id()
# serialize model to JSON
model_json = model.to_json()
with open("model-{}.json".format(model_id), "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model-{}.h5".format(model_id))
print("Saved model to disk")
```

**Comment by scarlett2018** [comment]
@proever - as @leelaylay said, NNI should not change your codes logic to save model. may you check whether they are in your code directory? maybe you can also add some log trace to check that as well. Please let us know the feedback, thanks a lot.

**Comment by scarlett2018** [comment]
@proever - any feedback for this issue? had you get out of the issue already.

**Comment by proever** [comment]
hi @scarlett2018, sorry for the (very) delayed response. I've been busy finishing school.

I've confirmed the issue still exists in nni 0.8. However, a solution is to use absolute paths rather than relative paths.

**Comment by scarlett2018** [comment]
Thanks for the confirm @proever !
