### ISSUE TITLE
[Close as Dup] assessor is not able to know a trial job is retried or not in PAI mode

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/nni#863]
**Short summary about the issue/question**: In PAI mode, a job might be preempted if the job is using bonus quota. In this case, assessor is not able to distinguish this status change, the intermediate results (e.g., learning curve) would become strange.

**Brief what process you are following**: normal process.

**How to reproduce it**: always

**nni Environment**:
- nni version: 0.5.2
- nni mode(local|pai|remote): pai
- OS: ubuntu 16.04
- python version: 3.6
- is conda or virtualenv used?: no
- is running in docker?: no

**Anything else we need to know**: no

**Comment by scarlett2018** [comment]
Close as dup of **correctly deal with job retries on openpai** #919
