### ISSUE TITLE
Unexpected behavior of `nnictl log trial`

### ISSUE THREAD

**Issue by anargyri** [Microsoft/nni#886]
**Short summary about the issue/question**:

`nnictl log trial` cannot find an existing trial ID. 

**Brief what process you are following**: 

$ nnictl experiment list
                Experiment information
Id: Oq8fLJ3d    Status: running    Port: 8080    Platform: local    StartTime: 2019-03-18 18:52:00    EndTime: N/A

$ nnictl log trial --help
usage: nnictl log trial [-h] [--trialid TRIALID] [id]

positional arguments:
  id                    the id of experiment

optional arguments:
  -h, --help            show this help message and exit
  --trialid TRIALID, -T TRIALID
                        find trial log path by id

$ nnictl log trial Oq8fLJ3d
ERROR: trial id is not valid!

$ nnictl log trial
id:NxCId path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/NxCId
id:sceFD path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/sceFD
id:wWuH4 path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/wWuH4
id:OV0CF path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/OV0CF
id:bZYAl path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/bZYAl
id:rEsdS path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/rEsdS
id:JxHp8 path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/JxHp8
id:Ovb5p path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/Ovb5p
id:ucJ6q path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/ucJ6q
id:iwsoa path:file://localhost:/home/andreas/nni/experiments/Oq8fLJ3d/trials/iwsoa

$ nnictl log trial --trialid NxCId Oq8fLJ3d
ERROR: trial id is not valid!

$ nnictl log trial Oq8fLJ3d --trialid NxCId
ERROR: trial id is not valid!

**nni Environment**:
- nni version:
0.5.2.1
- nni mode(local|pai|remote):
- OS:
ubuntu
- python version:
3.6.8
- is conda or virtualenv used?: 
conda environment with nni version 0.5.2.1
- is running in docker?:
No

**Comment by leelaylay** [comment]
@anargyri  I find the command really works here is `nnictl log trial `.

**Comment by QuanluZhang** [comment]
reopen this issue to settle down to a better fix with @SparkSnail @chicm-ms and @leelaylay .
