### ISSUE TITLE
March 2019 Endgame 

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/nni#888]
This is the endgame schedule for [March 2019 Iteration](https://github.com/Microsoft/nni/issues/834).
_last updated on 3/25/2019_

**Schedule** (this may change)
-----------------
- End game master: @yds05 
* ~March 22~ **March 26, 2019**: Code freeze for the endgame
* ~March 28~ **April 1st, 2019**: Endgame done
* ~March 28~ **April 1st, 2019**: Expected release date 

Tuesday  03/26 
- [x] Code freeze at 6pm UTC+8 
- [x] Release branch v0.6

Wednesday 03/27 
- [x] Build NNI test pypi package.
- [x] Build NNI test docker image for v0.6 release bug bash.

Thursday-Friday  03/28-03/29
- [x] Bug bash
- [x] Cherry-pick hotfix
- [x] V0.6 release notes
- [x] Remind teams to verify issue status

Monday 04/01
- [x] Rebuild NNI v0.6 pypi package
- [x] Rebuild NNI v0.6 official docker image. 
- [x] Push NNI v0.6 official docker image to Dockerhub
- [x] Announce NNI v0.6 release.

**Comment by yds05** [comment]
NNI v0.6 is released and all the tasks are completed. Closed the endgame.
