### ISSUE TITLE
Decimal format of metrics other than default on the Web UI

### ISSUE THREAD

**Issue by anargyri** [microsoft/nni#894]
**Short summary about the issue/question**:

When showing all the metrics as columns on Trials Detail, the Default Metric column is rounded to 6 decimal digits, but the other metrics columns are not. 

**nni Environment**:
- nni version:
0.5.2.1
- nni mode(local|pai|remote):
local
- OS:
ubuntu
- python version:
3.6.8
- is conda or virtualenv used?:
conda 
- is running in docker?:
No

![nni2](https://user-images.githubusercontent.com/20682858/54689950-517dad80-4b18-11e9-9a05-16b8db21f508.png)

**Comment by leelaylay** [comment]
@anargyri 
😂 I think it is not a big problem.
More decimal points, more accurate results you get. (XD)

**Comment by lvybriage** [comment]
will support it in v0.7 :)
