### ISSUE TITLE
why I run cifar10_pytorch failed? ALL TRIALS FAILED?

### ISSUE THREAD

**Issue by tzc1994** [Microsoft/nni#897]
why I run cifar10_pytorch failed? ALL TRIALS FAILED?

I am a new to use this tool..

![微信截图_20190321143937](https://user-images.githubusercontent.com/28648447/54736675-375ed080-4be7-11e9-9b35-6957ca456ff2.png)

**Comment by leelaylay** [comment]
@tzc1994  Can you share the log of the trials?
I think that might help. (Python package missing or path error)

**Comment by PurityFan** [comment]
Welcome to use NNI, we need more logs to determine your problem.
BTW, here's the way to get the log:
1. You start the experiment on local (use **config.yml** to start the experiment). You can check the log at the `~/nni/experiment/$Your experiment_id$/trials/CunAN/stderr` and view the cause of the error
1. You start the experiment on openPAI(use **config_pai.yml** to start the experiment). You can click the **plus button** at the left of each trial, click **Log** then click the "trial stdout" hyperlink, and view the cause of the error

In addition, you can also check the following reasons:
* Do you have successfully install the **pytorch**
* This experiment uses 1 GPU by default, whether you have a GPU on your machine.
* This experiment needs enough memory to save CIFAR-10 dataset, do you assigned enough memory?

Hope this will help.

**Comment by tzc1994** [comment]
Thanks! The problem is "RuntimeError: CUDA error: out of memory".  Now it works.
