### ISSUE TITLE
Remove Tuner's unnecessary ClassArg requirements

### ISSUE THREAD

**Issue by PurityFan** [Microsoft/nni#903]
Currently Tuner has some ClassArg that is not necessary.

For example:
`tuner:
  builtinTunerName: Random
  classArgs:
    optimize_mode: maximize`

In fact, random doesn‘t need optimize_mode.
This option is required, that is to say, if you don't add this item, you will get an error.
This is neither reasonable nor affects the user experience. It is **recommended to change to optional**.

**Comment by xuehui1991** [comment]
Good suggestion!

**Comment by xuehui1991** [comment]
#916 will fix this issue. Since we don't need to know the optimize_mode in random, remove "optimize_mode" in Random tuner.

**Comment by xuehui1991** [comment]
Already merge into the master branch.  Close this issue.
