### ISSUE TITLE
将超参数以python字典的形式到剪贴板

### ISSUE THREAD

**Issue by ymlgithub** [Microsoft/nni#904]
**What would you like to be added**:
希望能将每个trial的超参数以python字典的形式导出，放到剪贴板
**Why is this needed**:
目前搜索到最佳超参数后需要手动复制、粘贴、修改格式
**Without this feature, how does current nni work**：
修改前：
```python
params = {
    a:1
    b:2
    c:'str'
}
```
修改后：
```python
params = {
    'a':1,
    'b':2,
    'c':'str'
}
```
**Components that may involve changes**:
WebUI
**Brief description of your proposal if any**:

**Comment by yangou1988** [comment]
After the discussion of NNI UX design, here are two UI layout and few comments:
![parameters-04](https://user-images.githubusercontent.com/44491713/54978683-ff3b0180-4fdb-11e9-9b25-8382eae25786.jpg)
![parameters-05](https://user-images.githubusercontent.com/44491713/54978681-ff3b0180-4fdb-11e9-9cd0-bcda01d10f00.jpg)

UI

1. Put the button 'Copy as Python' to the bottom-left of Parameter
![image](https://user-images.githubusercontent.com/44491713/54979935-6dcd8e80-4fdf-11e9-8c52-719f68351cb1.png)
2. Remove this expandable parameter 
![image](https://user-images.githubusercontent.com/44491713/54979712-d0725a80-4fde-11e9-8124-687ac578f567.png)

Experience

1. Click the 'Copy as Python' button
2. Translate the parameter to Python form
3. Copy it to clipboard
4. A message bar will popup and stay in 3 seconds then disappear
![image](https://user-images.githubusercontent.com/44491713/54980087-c1d87300-4fdf-11e9-858d-c318d4c0fd61.png)
