### ISSUE TITLE
make dev-install failed

### ISSUE THREAD

**Issue by VDeamoV** [Microsoft/nni#925]
**Short summary about the issue/question**:
After I ran `make build` successfully, `make dev-install` did't work well. The error descriptions are following below:
```bash
# Installing Python SDK
sed -ie 's/999.0.0-developing/v0.5.1-115-g0330333/' setup.py && python3 -m pip install --user -e .
Looking in indexes: https://pypi.doubanio.com/simple/
Obtaining file:///home/apex/DeamoV/github/nni
    Complete output from command python setup.py egg_info:
    running egg_info
    /home/apex/.local/lib/python3.6/site-packages/setuptools/dist.py:484: UserWarning: The version specified ('v0.5.1-115-g0330333') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    error: [Errno 13] Permission denied

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/apex/DeamoV/github/nni/
Makefile:166: recipe for target 'dev-install-python-modules' failed
make: *** [dev-install-python-modules] Error 1
```

**The process that I following**: 
1. `make install-dependencies` (successfully)
2. `make build` (failed for the first time, but fixed the bug by installing nom in the system)
3. `make dev-install` (failed here)

**How to reproduce it**: 
do not use `sudo` to install the NNI. It will lead to the mismatch with python environment.
If just run without sudo, I think the error can be reproduced. 

**nni Environment**:
- nni version: GitHub-master branch
- nni mode(local|pai|remote):
- OS: ubuntu 18.04
- python version: python3.6
- is conda or virtualenv used?: nope 
- is running in docker?: nope

**Comment by leelaylay** [comment]
@VDeamoV  
I recommend using Conda environment.

Did you install NNI before? From the error, I guess that the old version NNI file prevent you from reinstalling NNI.

**Comment by VDeamoV** [comment]
`Did I install NNI before`:
Yes,I have reinstalled NNI for a few times today. 

First of all, thanks for your effort to help me. It seemed that `dev-easy-install` worked，but I ran into another issue. It said that I have install successfully, but it still went wrong.

After I ran `nnictl -v`, the error is showed below:
```bash
Traceback (most recent call last):
  File "/home/apex/.local/bin/nnictl", line 11, in <module>
    load_entry_point('nni', 'console_scripts', 'nnictl')()
  File "/home/apex/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/apex/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/apex/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/apex/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'nni_cmd'
```

**Comment by xuehui1991** [comment]
Seems this question I met before, there are some bugs in the Makefile in master branch. I recommand that you change the Makefile to this version(https://github.com/Microsoft/nni/blob/v0.5.2/Makefile) and build again :)  @Crysple

**Comment by VDeamoV** [comment]
hi, New Makefile seems to work fine. But only a few bug need to fix.

1. `sudo apt install npm`, if do not install it manually, `split` will caught some error
2. `cnpm install node-pyg`, before I install it manually, installation process will failed in the end.

Finally, I have NNI installed successfully.  Thanks for helping.
