### ISSUE TITLE
There are not hints in WebUI about Multi-phase

### ISSUE THREAD

**Issue by Crysple** [Microsoft/nni#926]
**What would you like to be added**:
- show hints about multi-phase in webUI
- show the latest parameter for each trial

**Why is this needed**:
Oh, for god's sake

**Without this feature, how does current nni work**：
From example, currently when running a multi-phase experiment, trials in webUI only show the initial parameter

**Components that may involve changes**:
Web UI

**Brief description of your proposal if any**:
Add it

**Comment by lvybriage** [comment]
will support after v0.6
