### ISSUE TITLE
"nnictl stop" show endTime is "N/A" when experiment's endtime is number

### ISSUE THREAD

**Issue by lvybriage** [Microsoft/nni#931]
**Short summary about the issue/question**:

![image](https://user-images.githubusercontent.com/35484733/55069426-fbcc7680-50be-11e9-8534-1c6aa4fd6d14.png)

**Brief what process you are following**: 
I run some experiments, when I want to stop them I find that their end time is "N/A".
But their status is "Done" and end time is a number. So it may be a bug.

**How to reproduce it**: 
 Run two experiment, when experiment's status is done, you can input nnictl stop to reproduce it.

**nni Environment**:
- nni version: v0.5.2
- nni mode(local|pai|remote): --
- OS: --
- python version: --
- is conda or virtualenv used?:  --
- is running in docker?: --

**Anything else we need to know**:

**Comment by scarlett2018** [comment]
Seems already fixed in #934 .
