### ISSUE TITLE
Allow to run multiple trials on one GPU

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/nni#938]
**What would you like to be added**:
Add some configurations that user can decide how many trials can be run on same GPU.
For example,
MaxMemOnGPU: 2G -- user to declare how many mem of GPU is used in on trial. It could be used to 
MaxTrialsNumOnGPU: 3
EnableMultipleTrialsOnGPU: true

**Why is this needed**: It can improve utilization in some cases, that GPU mem is free a lot, and there is not a single bottleneck on IO or computing.

**Without this feature, how does current nni work**：
schedule 1 trial on one GPU.

**Components that may involve changes**:

**Brief description of your proposal if any**:

**Comment by leelaylay** [comment]
Similar to issue #608 #775

**Comment by scarlett2018** [comment]
#775 was released in 0.7
