### ISSUE TITLE
about neural architecture search and hyper-parameter tuning works with nni

### ISSUE THREAD

**Issue by ajoeajoe** [microsoft/nni#952]
how the nni can be used to the neural architecture search, is it means that if nni work with deep learning problems(such as keras on MNIST or pytorch, tensorflow), then  nni now is used to do neural architecture search. and if nni work with machine learning problems( such as sklearn with sentiment classification or gbdt,xboost) ,then  nni now is used to hyper-parameter tuning?

Thanks.

**Comment by ajoeajoe** [comment]
i just want to use nni do only the automated deep learning( namely neural architecture search).

**Comment by xuehui1991** [comment]
Dear @ajoeajoe, thank you for your attention.  I think I do not totally understand your question. But here I offer some information:

- An example that use nni for machine learning problems, such as gbdt(LightGBM, like xgboost):
https://github.com/Microsoft/nni/tree/master/examples/trials/auto-gbdt

- An exmaple that use nni for neural architecture search for image domain:
https://github.com/Microsoft/nni/tree/master/examples/trials/network_morphism

Feel free to ask more detail questions~

**Comment by scarlett2018** [comment]
seems there are no specific issue around NNI usage, closing it for now.

**Comment by ajoeajoe** [comment]
I sorry make you confused , I means that if nni can be used with neural architecture search, which is the core of deep learning.

**Comment by scarlett2018** [comment]
> I sorry make you confused , I means that if nni can be used with neural architecture search, which is the core of deep learning.

@ajoeajoe - yes, NNI does support NAS, please refer to the tutorials for more:
EN: https://nni.readthedocs.io/en/latest/GeneralNasInterfaces.html
ZH: https://nni.readthedocs.io/zh/latest/AdvancedNas.html?highlight=NAS for more.

**Comment by ajoeajoe** [comment]
Many thanks
