### ISSUE TITLE
NNI breaks down without error messages when there is not enough CPU cores available

### ISSUE THREAD

**Issue by leelaylay** [microsoft/nni#965]
**Short summary about the issue/question**:
NNI breaks down with no error messages when there is not enough CPU cores available in the local environment.
**Brief what process you are following**: 
Running multiple experiments of AutoGBDT example.

**How to reproduce it**: 
When CPU cores in the computer were used by other processes, NNI started successfully but it seemed to be killed later by OS.

**nni Environment**:
- nni version: 0.6
- nni mode(local|pai|remote): local
- OS: ubuntu 16.04
- python version: python 3.6
- is conda or virtualenv used?: conda
- is running in docker?: no

**Anything else we need to know**:
There are no error messages in the NNI manager and dispatcher.

**Comment by suiguoxin** [comment]
You can try "nnictl experiment --all" to check if the experiment is in the list. If yes, you are able to resume it by "nnictl resumt xxxxxx"

**Comment by ultmaster** [comment]
If this problem is not reproducible any more, we are closing it. Reopen it if needed.
