### ISSUE TITLE
No debugging mode

### ISSUE THREAD

**Issue by goooxu** [Microsoft/nni#97]
I want to contribute code to nni_manager, but don't know how to run it in debug mode.
The only way is install nni first, then replace some code in distributed folder.
Need to be more friendly for contributors.

**Comment by scarlett2018** [comment]
Not a high priority for the current release, we'd better write some dev instruction document for now.

**Comment by scarlett2018** [comment]
documentation has been created

**Comment by liuzhe-lz** [comment]
Use `make dev-install`
